dhis2/dhis2-core

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CodeGenerator.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceContentStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/JCloudsFileResourceContentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerMockTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AuditController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DocumentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExternalFileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SvgConversionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/CspFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/action/LoginAction.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
This PR merges the following DHIS2 security advisories:
CVE-2022-41948
CVE-2022-41947
CVE-2022-41949
> fix: include fixes from 2.38.2.1

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CodeGenerator.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceContentStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/JCloudsFileResourceContentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerMockTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AuditController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DocumentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExternalFileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SvgConversionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/CspFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/action/LoginAction.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
This PR merges the following DHIS2 security advisories:
CVE-2022-41948
CVE-2022-41947
CVE-2022-41949
> fix: include fixes from 2.39.0.1

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CodeGenerator.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceContentStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/JCloudsFileResourceContentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerMockTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AuditController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DocumentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExternalFileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SvgConversionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/CspFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/action/LoginAction.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
This PR merges the following DHIS2 security advisories:
CVE-2022-41948
CVE-2022-41947
CVE-2022-41949
> fix: include fixes from 2.37.8.1

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/config/TrackerValidationConfig.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultValidators.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/RuleEngineValidators.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/Validators.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentDateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentGeoValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentNoteValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentRuleValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentDateValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentGeoValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentNoteValidatorTest.java
next in line are the TrackerValidationHooks for Enrollment like for TEI done in https://github.com/dhis2/dhis2-core/pull/12524
> chore: migrate enrollment validators DHIS2-14298

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/config/TrackerValidationConfig.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultValidators.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/RuleEngineValidators.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/Validators.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventGeoValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventNoteValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventRuleValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventGeoValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventNoteValidatorTest.java
next in line after https://github.com/dhis2/dhis2-core/pull/12526
> chore: migrate event validators DHIS2-14298

- dhis-2/dhis-services/dhis-service-tracker/pom.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/config/TrackerPreheatConfig.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/EnrollmentStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/EventStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/TrackerEntityInstanceStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/strategy/TrackerEntityInstanceStrategyTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHookTest.java
The reference tree is not needed anymore due to the work in https://github.com/dhis2/dhis2-core/pull/12495
> chore: Remove reference tree from Preheat [TECH-14298]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
(cherry picked from commit a20013079af9d181dd9fc0406da147a9a96a06f1)
> fix: speed up data import delete mode [DHIS2-14293] (#12514)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/config/TrackerValidationConfig.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultValidators.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentPreCheckDataRelationsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentPreCheckUpdatableFieldsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventPreCheckDataRelationsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventPreCheckUpdatableFieldsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipPreCheckDataRelationsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityPreCheckUpdatableFieldsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentPreCheckDataRelationsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentPreCheckUpdatableFieldsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventPreCheckDataRelationsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventPreCheckUpdatableFieldsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipPreCheckDataRelationsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityPreCheckUpdatableFieldsValidatorTest.java
migrate
* PreCheckDataRelationsValidationHook
* PreCheckUpdatableFieldsValidationHook
to `Validator<T>` by type
> chore: migrate pre check hooks to validator DHIS2-14298

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
backport https://github.com/dhis2/dhis2-core/pull/12544 but removed the integration controller test as its not available in 2.39
> fix: api/events.json ignores skipPaging parameter (2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
backport https://github.com/dhis2/dhis2-core/pull/12545
> fix: api/events.json ignores skipPaging parameter (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
backport https://github.com/dhis2/dhis2-core/pull/12546
> fix: api/events.json ignores skipPaging parameter (2.37)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultQueryItemLocator.java
Reverting change that caused inconsistency in events reports.
> fix: Revert org unit changes

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
> fix: always sort notifications newest first on redis [DHIS2-9048] (2.38)

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/multiOrgSectionForm.vm
Backport fix for addressing missing organisation unit information in multiorganisation unit forms, see [DHIS2-13088](https://dhis2.atlassian.net/browse/DHIS2-13088?focusedCommentId=178868).
> fix: ou info for multiOrgUnit forms [DHIS2-13088] (2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/CsvMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/XmlMessageConverter.java
_[Backport from master/2.40]_
It seems that we have the same issue in 2.39.
PR: https://github.com/dhis2/dhis2-core/pull/12577
> fix: Fix NPE when Spring try to convert XML and pathInfo is null

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/teis/TEIimportTest.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/teis/teisWithEventsAndEnrollments.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/mapper/TrackedEntityInstanceRowCallbackHandler.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/query/TrackedEntityInstanceQuery.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/TrackedEntityInstanceCriteria.java
see https://github.com/dhis2/dhis2-core/pull/12392
> fix: TEIs are not filterable by potentialDuplicate property [ DHIS2-11625 ] [ 2.37 ] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/teis/TEIimportTest.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/teis/teisWithEventsAndEnrollments.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/mapper/TrackedEntityInstanceRowCallbackHandler.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/query/TrackedEntityInstanceQuery.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/TrackedEntityInstanceCriteria.java
see https://github.com/dhis2/dhis2-core/pull/12392
> fix: TEIs are not filterable by potentialDuplicate property [ DHIS2-11625 ] [ 2.38 ] 

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/EnrollmentRuleEngineValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/EnrollmentValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/EventRuleEngineValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/EventValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/RelationshipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/RuleEngineValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/TrackedEntityValidator.java
@formatting:off with a missing closing @formatting:on caused some files to avoid formatting.
> chore: Add formatting:on after custom formatting

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/IntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/SingleSetupIntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/TransactionalIntegrationTest.java
- dhis-2/dhis-web-api-test/pom.xml
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerIntegrationTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerTestBase.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TEIControllerIntegrationTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/EventControllerIntegrationTest.java
backport https://github.com/dhis2/dhis2-core
> feat: add DhisControllerIntegrationTest (2.39)

- dhis-2/dhis-web/dhis-web-portal/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/12623
> fix: set group of /opt/dhis2 in Docker image to nogroup [2.39]

- dhis-2/dhis-web/dhis-web-portal/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/12623
> fix: set group of /opt/dhis2 in Docker image to nogroup [2.38]

- dhis-2/dhis-web/dhis-web-portal/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/12623
> fix: set group of /opt/dhis2 in Docker image to nogroup [2.37]

- .github/workflows/run-api-tests.yml
- .gitignore
- README.md
- dhis-2/dhis-web/dhis-web-portal/pom.xml
- docker-compose.yml
- jenkinsfiles/dev
- jenkinsfiles/stable
backport of https://github.com/dhis2/dhis2-core/pull/12046 (and docs change https://github.com/dhis2/dhis2-core/pull/12573) and fix https://github.com/dhis2/dhis2-core/pull/12616
> ci: support running Docker image on arm64 TECH-1454 [2.39]

- .github/workflows/run-api-tests.yml
- .gitignore
- README.md
- dhis-2/dhis-web/dhis-web-portal/pom.xml
- docker-compose.yml
- jenkinsfiles/dev
- jenkinsfiles/stable
backport of https://github.com/dhis2/dhis2-core/pull/12046 (and docs change https://github.com/dhis2/dhis2-core/pull/12573) and fix https://github.com/dhis2/dhis2-core/pull/12616
> ci: support running Docker image on arm64 TECH-1454 [2.38]

- .github/workflows/run-api-tests.yml
- .gitignore
- README.md
- dhis-2/dhis-web/dhis-web-portal/pom.xml
- docker-compose.yml
- jenkinsfiles/dev
- jenkinsfiles/stable
backport of https://github.com/dhis2/dhis2-core/pull/12046 (and docs change https://github.com/dhis2/dhis2-core/pull/12573) and fix https://github.com/dhis2/dhis2-core/pull/12616
> ci: support running Docker image on arm64 TECH-1454 [2.37]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
just backport, please see https://dhis2.atlassian.net/browse/DHIS2-13909
> fix: Sort org unit DE results in "No data available" message [2.38-DHIS2-13909-backport]

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/multiOrgSectionForm.vm
Backport fix for addressing missing organisation unit information in multiorganisation unit forms, see [DHIS2-13088](https://dhis2.atlassian.net/browse/DHIS2-13088?focusedCommentId=178868).
> fix: ou info for multiOrgUnit forms [DHIS2-13088] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/PreheatIdentifier.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Query.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/PreheatServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/sharing/CascadeSharingTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/resources/dashboard/create_dashboard.json
- dhis-2/dhis-web-api-test/src/test/resources/dashboard/update_dashboard.json
backport https://github.com/dhis2/dhis2-core/pull/12453
> fix: update dashboard with nonaccessible item objects (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/PreheatIdentifier.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Query.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/PreheatServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/sharing/CascadeSharingTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/resources/dashboard/create_dashboard.json
- dhis-2/dhis-web-api-test/src/test/resources/dashboard/update_dashboard.json
backport https://github.com/dhis2/dhis2-core/pull/12633
> fix: update dashboard with nonaccessible item objects (2.37)

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
see https://github.com/dhis2/dhis2-core/pull/12392
> fix: TEIs are not filterable by potentialDuplicate property (NTI) [ DHIS2-14362]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/ProgramStageInstanceUpdatePreProcessor.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
Backport  [[DHIS2-12934]](https://dhis2.atlassian.net/browse/DHIS2-12934)
> fix: (2.39) Updating dueDate if a data value is updated [DHIS2-12934] (#12120)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableGenerator.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
(cherry picked from commit f1b6749267b07c73bec750f621c72f50ff4ca138)
> fix: Analytics resource tables updated [DHIS2-14417] (#12660)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
please see https://dhis2.atlassian.net/browse/DHIS2-13173
> fix: Param displayProperty:SHORTNAME doesn't return short name [DHIS2-13173]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/AxisV2.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Line.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/visualization/CompatibilityGuardTest.java
**_[Backporting from master/2.40]_**
Support double values in Visualization (Axes/Lines).
> fix: Use double instead of int in Axes/Line [DHIS2-14206] (#12689)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/action/validation/ProgramRuleActionValidationContextLoader.java
backport https://github.com/dhis2/dhis2-core/pull/12489
> fix: NPE when updating programRuleActions (2.39)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/action/validation/ProgramRuleActionValidationContextLoader.java
backport https://github.com/dhis2/dhis2-core/pull/12489
> fix: NPE when updating programRuleActions (2.37)

- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/CacheInvalidationListener.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/PostCacheEventPublisher.java
(cherry picked from commit bbdd9410124dfde0b8c0d77901a8d2b07a29f824)
> fix: broken Redis cache invalidation for non-long identifiers (#12560)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
backport https://github.com/dhis2/dhis2-core/pull/12705
> fix: lazy exception when load attributes in getMetadataWithDependencies (2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
backport https://github.com/dhis2/dhis2-core/pull/12705
> fix: lazy exception when load attributes in getMetadataWithDependencies (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
backport https://github.com/dhis2/dhis2-core/pull/12705
> fix: lazy exception when load attributes in getMetadataWithDependencies (2.37) 

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerator.java
As reported by  @mm1024 in DHIS2-14004 the generated OpenAPI documents had two issues:
1.  schema names contained `:` which is not legal
Using `.` instead of `:` is valid and a good suggestion but sadly stoplight behaves strange with `.` in names. I opted to use `-` as delimiter but made the used delimiters configurable as well.
2. some `array` type schemas did not have an `items` property but the MUST have it
This was the case for the "simple" type mapping for `ArrayNode`. For any simple type of type `"array"` now the items are added as `"items": {}` which means they are of any type (unknown).
> fix: name mangling to valid names, arrays always have items [DHIS2-14004]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/OrgUnitTableJoiner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipWriter.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/OrgUnitTableJoinerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcOwnershipWriterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
* feat: Add orgUnitField to Program Inds DHIS2-13373
* fix: JdbcOwnershipAnalyticsTableManagerTest
* fix: JdbcOwnershipAnalyticsTableManagerTest
* fix: SonarCloud
(cherry picked from commit 6c0af94d3c4e5a4b28cb03a7fa217283e2eda26f)
> feat: Add orgUnitField to program indicators [DHIS2-13373] (#12675)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapView.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_9__Add_labeltemplate_column_into_mapview.sql
Just adds a new attribute/column to MapView.
> feat: Add new attribute to MapView [DHIS2-14305]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ProgramExpressionParams.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
(cherry picked from commit 8e3809780d29e4bce6587ac8f27e946f85ae9354)
> fix: P.I. custom aggregation func desc DHIS2-14500 (#12755)

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
(cherry picked from commit 3cf882b4bd9d13d77a1cd32b586c68d0cf823203)
> fix: Predictor skipTest with no data DHIS2-14422 (#12754)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EnrollmentEventsParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EnrollmentParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EventParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EventAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/NoRegistrationSingleEventServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/security/EventSecurityTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EventFieldsMapperTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/RelationshipController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EventFieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/RelationshipControllerTest.java
see https://github.com/dhis2/dhis2-core/pull/12717
> fix: Extends nested fields to Events in /trackedentities endpoint [ NTI ] [ DHIS2-14407 ] [2.38] 

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EnrollmentEventsParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EnrollmentParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EventParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EventAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/NoRegistrationSingleEventServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/security/EventSecurityTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EventFieldsMapperTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/RelationshipController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EventFieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/RelationshipControllerTest.java
see https://github.com/dhis2/dhis2-core/pull/12717
> fix: Extends nested fields to Events in /trackedentities endpoint [ NTI ] [ DHIS2-14407 ] [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/MetadataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/orgunit/OrgUnitHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/orgunit/OrgUnitHelperTest.java
please see: https://dhis2.atlassian.net/browse/DHIS2-14069
> feat: Support org unit hierarchy names in analytics events/enrollments APIs [DHIS2-14069]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/OrderParamsHelper.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
Fix order field supported values for /trackedEntityInstanceFilters endpoint
> fix: Allow ordering TEIs by attribute [DHIS2-13981] [2.39]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerTrackedEntityCriteria.java
see https://github.com/dhis2/dhis2-core/pull/12666
> fix: TEIs are not filterable by potentialDuplicate property [DHIS2-14362] [2.39]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerTrackedEntityCriteria.java
see https://github.com/dhis2/dhis2-core/pull/12666
> fix: TEIs are not filterable by potentialDuplicate property [DHIS2-14362] [2.37]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerTrackedEntityCriteria.java
see https://github.com/dhis2/dhis2-core/pull/12666
> fix: TEIs are not filterable by potentialDuplicate property [DHIS2-14362] [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/12825
> fix: cannot add sharing userGroup using json patch api (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/12825
> fix: cannot add sharing userGroup using json patch api (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/12825
> fix: cannot add sharing userGroup using json patch api (2.37)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
Back port to 2.39 of https://github.com/dhis2/dhis2-core/pull/12817
> fix: Check dynamic properties sorting by attribute [DHIS2-14560] [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
Back port to 2.38 of https://github.com/dhis2/dhis2-core/pull/12817
> fix: Check dynamic properties sorting by attribute [DHIS2-14560] [2.38]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
Back port to 2.37 of https://github.com/dhis2/dhis2-core/pull/12817
> fix: Check dynamic properties sorting by attribute [DHIS2-14560] [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/OrderParamsHelper.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
Back port of https://github.com/dhis2/dhis2-core/pull/12817
> fix: Check dynamic properties sorting by attribute [DHIS2-14560] [2.39.1]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/CsvImportClass.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/DefaultCsvImportService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/csv/CsvImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/csv/indicators.csv
https://dhis2.atlassian.net/browse/DHIS2-10529
- Support import Indicator using csv file via Import/Export app.
- For testing, import sample payload provided in the docs.
Docs PR https://github.com/dhis2/dhis2-docs/pull/1128
> feat: support import indicator using csv

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/DataInputPeriod.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/DataSet.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
2.39 backport from cherr-pick #12858
> fix: data value validation - compare date ranges as dates not timestamps [DHIS2-14591] (2.39)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/AssertValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckUpdatableFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHookTest.java
backport of https://github.com/dhis2/dhis2-core/pull/12473
(14 instead of 15 files changes since this PR is without the accidentally committed file dhis-2/dhis-services/dhis-service-tracker/.attach_pid646883)
> refactor: clean ValidationErrorReporter DHIS2-14213 [2.39]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/AtomicModeTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/enrollments/EnrollmentsTests.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/PersistablesFilter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/ValidationFailFastException.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/package-info.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerBundleTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/PersistablesFilterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/AssertTrackerValidationReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
backport of https://github.com/dhis2/dhis2-core/pull/12495
> fix: invalidation of tracker tree DHIS2-14213 [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupService.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/JsonPatchOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/AddOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/RemoveByIdOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/RemoveOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/ReplaceOperation.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
backport https://github.com/dhis2/dhis2-core/pull/12841
> fix: cannot patch user.userGroups using api/users endpoint

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/JsonPatchOperation.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
The fix from https://github.com/dhis2/dhis2-core/pull/12841 is already in master, but the code styles is a bit different and the controller test hasn't been added.
So this PR makes sure codes in master and 2.39 branch are the same.
> chore: add controllerTest for patching user.userGroups

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/OpenApiControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerator.java
> docs: add basic auth security scheme in API descriptor

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DefaultDataApprovalService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceCategoryOptionGroupTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreUserTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataApprovalControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataApprovalController.java
(cherry picked from commit 70dc9f2190af69ce69085a47412c49090340d22f) (cherry picked from commit a5c510de1990fa35e8f46bf7b74b0198843122ca)
> feat: /dataApprovals/categoryOptionCombos args [DHIS2-14371] (#12862)

- docker-compose.yml
- docker/log4j2.xml
backport of
1. https://github.com/dhis2/dhis2-core/pull/12900
2. https://github.com/dhis2/dhis2-core/pull/12320
> ci: log to STDOUT only in docker-compose setup [2.39]

- docker-compose.yml
- docker/log4j2.xml
backport of
1. https://github.com/dhis2/dhis2-core/pull/12900
2. https://github.com/dhis2/dhis2-core/pull/12320
> ci: log to STDOUT only in docker-compose setup [2.38]

- docker-compose.yml
- docker/log4j2.xml
backport of
1. https://github.com/dhis2/dhis2-core/pull/12900
2. https://github.com/dhis2/dhis2-core/pull/12320
> ci: log to STDOUT only in docker-compose setup [2.37]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
Some cleaning up of HibernateDataApprovalStore comments from when they were originally line-wrapped.
> chore: HibernateDataApprovalStore comment fixes

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EnrollmentParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
see https://github.com/dhis2/dhis2-core/pull/12892
> fix: TrackedEntities returning soft deleted events [Dhis2-14562] [2.39]

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/EnrollmentParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
see https://github.com/dhis2/dhis2-core/pull/12892
> fix: TrackedEntities returning soft deleted events [Dhis2-14562] [2.38]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_12__Add_icon_column_to_visualization.sql
This fixes broken dashboards and visualizations.
> fix: Flyway migration [DHIS2-14691]

- dhis-2/dhis-e2e-test/README.md
remove duplication and outdated information
> docs: update e2e readme with regards to Docker [skip ci]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Back port of https://github.com/dhis2/dhis2-core/pull/12961
> fix: Return events if explicit fields provided [DHIS2-14720] [2.38]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Back port of https://github.com/dhis2/dhis2-core/pull/12961
> fix: Return events if explicit fields provided [DHIS2-14720] [2.39]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Back port of https://github.com/dhis2/dhis2-core/pull/12961
> fix: Return events if explicit fields provided [DHIS2-14720] [2.39.1.1]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Back port of https://github.com/dhis2/dhis2-core/pull/12961
> fix: Return events if explicit fields provided [DHIS2-14720] [2.38.3]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
backport of https://github.com/dhis2/dhis2-core/pull/12973
> ci: Remove timeout duration from slack message [skip ci] [2.39]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
backport of https://github.com/dhis2/dhis2-core/pull/12973
> ci: Remove timeout duration from slack message [skip ci] [2.38]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
backport of https://github.com/dhis2/dhis2-core/pull/12973
> ci: Remove timeout duration from slack message [skip ci] [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
> fix: Check if dueDate param is null [DHIS2-14736] [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
> fix: Check if dueDate param is null [DHIS2-14736] [2.38]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
> fix: Check if dueDate param is null [DHIS2-14736] [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
> fix: Check if dueDate param is null [DHIS2-14736] [2.39.1.1]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
> fix: Check if dueDate param is null [DHIS2-14736] [2.38.3]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/security/CategorySecurityUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/security/CategorySecurityUtilsTest.java
The check is only performed when Program has non default Categories
> fix: check only applies on Programs without default category [DHIS2-14241]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstageworkinglist/ProgramStageQueryCriteria.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programstageworkinglist/hibernate/ProgramStageWorkingList.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageWorkingListObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageWorkingListObjectBundleHookTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageSchemaDescriptor.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_19__Add_primary_key_working_list.sql
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
This is a continuation of the feature program stage working list, the [original PR](https://github.com/dhis2/dhis2-core/pull/12657) was merged a bit too son, in this one I'll tackle some pending minor improvements.
Ticket: https://dhis2.atlassian.net/browse/DHIS2-14367
> feat: Add minor working list improvements [DHIS2-14367]

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
backport of https://github.com/dhis2/dhis2-core/pull/13001 commit [a0cb0e7c4d6902ba2b8e33b49515405d5fa1ddb5](https://github.com/dhis2/dhis2-core/pull/13001/commits/a0cb0e7c4d6902ba2b8e33b49515405d5fa1ddb5)
> fix: allow attribute UID in fields param for all overloaded methods DHIS2-14735 [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/DataSetObjectBundleHook.java
- dhis-2/dhis-web-api-test/src/test/resources/dataset/dataset_with_compulsoryDataElementOperand.json
- dhis-2/dhis-web-api-test/src/test/resources/dataset/dataset_with_compulsoryDataElementOperand_update.json
backport https://github.com/dhis2/dhis2-core/pull/13041
> fix: delete compulsoryDataElementOperand when updating DataSet (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/DataSetObjectBundleHook.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataSetControllerTest.java
- dhis-2/dhis-web-api-test/src/test/resources/dataset/dataset_with_compulsoryDataElementOperand.json
- dhis-2/dhis-web-api-test/src/test/resources/dataset/dataset_with_compulsoryDataElementOperand_update.json
backport https://github.com/dhis2/dhis2-core/pull/13041
> fix: delete compulsoryDataElementOperand when updating DataSet (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/DataSetObjectBundleHook.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataSetControllerTest.java
- dhis-2/dhis-web-api-test/src/test/resources/dataset/dataset_with_compulsoryDataElementOperand.json
- dhis-2/dhis-web-api-test/src/test/resources/dataset/dataset_with_compulsoryDataElementOperand_update.json
backport https://github.com/dhis2/dhis2-core/pull/13041
> fix: delete compulsoryDataElementOperand when updating DataSet (2.39)

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
foward port https://github.com/dhis2/dhis2-core/pull/13055
> perf: remove unnecessary attributeValue handler in FieldFilterService (2.39)

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
forward port https://github.com/dhis2/dhis2-core/pull/13055
> perf: remove unnecessary attributeValue handler in FieldFilterService

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/13055
> perf: remove unnecessary attributeValue handler in FieldFilterService (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParams.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParser.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathConverter.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldFilterParamsTest.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldFilterParserTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/FieldPathConverterTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FieldFilterServiceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EnrollmentFieldsMapperTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EventFieldsMapperTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapperTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/trigramsummary/TrigramSummaryControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsGatewayController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EnrollmentFieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EventFieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/FieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trigramsummary/TrigramSummaryController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
backport of
* commit [chore: remove duplication](https://github.com/dhis2/dhis2-core/pull/13001/commits/6e0be910429ccdf5a0c943e1dccc90a8126527ad) from https://github.com/dhis2/dhis2-core/pull/13001 as the fix for https://dhis2.atlassian.net/browse/DHIS2-14735 is already in 2.39
* https://github.com/dhis2/dhis2-core/pull/12936
* https://github.com/dhis2/dhis2-core/pull/13045
* https://github.com/dhis2/dhis2-core/pull/13029
> fix: tracker does not return fields in accordance with field filtering DHIS2-14783 [2.39]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/13079
/tracker/trackedEntities does not support CSV in 2.39
> fix: ignore fields parameter in tracker CSV endpoints DHIS2-14792 [2.39]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/13079
/tracker/trackedEntities does not support CSV in 2.38
> fix: ignore fields parameter in tracker CSV endpoints DHIS2-14792 [2.38]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParams.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParser.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathConverter.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldFilterParamsTest.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldFilterParserTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/FieldPathConverterTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FieldFilterServiceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EnrollmentFieldsMapperTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EventFieldsMapperTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/EnrollmentFieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/FieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/fieldsmapper/TrackedEntityFieldsParamMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
backport of https://github.com/dhis2/dhis2-core/pull/13076
> fix: tracker does not return fields in accordance with field filtering DHIS2-14783 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityCheck.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReader.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
backport from cherry-pick of #13102 (2.38)
> fix: provide displayName for all data integrity checks [DHIS2-14770] (2.38.3)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-14825
> fix: error when request with filter userAttribute:eq:true

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datastatistics/DataStatisticsController.java
Adds support for field filtering in `/api/dataStatistics` endpoint.
[DHIS2-11658](https://dhis2.atlassian.net/browse/DHIS2-11658)
[DHIS2-11658]: https://dhis2.atlassian.net/browse/DHIS2-11658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: support field filtering in /api/dataStatistics

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13070
> fix: Add due date filter in sql generation [DHIS2-14497] [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13070
> fix: Add due date filter in sql generation [DHIS2-14497] [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/13088
> chore: remove unused href field from new tracker event export DHIS2-14828 [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/13088
> chore: remove unused href field from new tracker event export DHIS2-14828 [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13070
> fix: Add due date filter in sql generation [DHIS2-14497] [2.37]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/12989
> ci: Disable concurrent builds for dev pipeline [skip ci] [2.39]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/12989
> ci: Disable concurrent builds for dev pipeline [skip ci] [2.38]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/12989
> ci: Disable concurrent builds for dev pipeline [skip ci] [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EnrollmentImportTest.java
see https://github.com/dhis2/dhis2-core/pull/13149
> fix: Createdbyuserinfo and lastupdatedbyuserinfo jsonb fields in programinstance are all blank (Old Tracker Capture) [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EnrollmentImportTest.java
see https://github.com/dhis2/dhis2-core/pull/13149
> fix: Createdbyuserinfo and lastupdatedbyuserinfo jsonb fields in programinstance are all blank (Old Tracker Capture) [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsSqlUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsSqlUtilsTest.java
plsease see last comments of https://dhis2.atlassian.net/browse/DHIS2-13528
> feat: Fallback logic for geometry, backward compatible default behavior [DHIS2-13528-4]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EnrollmentImportTest.java
see https://github.com/dhis2/dhis2-core/pull/13149
> fix: Createdbyuserinfo and lastupdatedbyuserinfo jsonb fields in programinstance are all blank (Old Tracker Capture) [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramStageInstanceSupplier.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
[DHIS2-14836](https://dhis2.atlassian.net/browse/DHIS2-14836)
[DHIS2-14836]: https://dhis2.atlassian.net/browse/DHIS2-14836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: eventDate does not contain timestamp [DHIS2-14836]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EnrollmentImportTest.java
see https://github.com/dhis2/dhis2-core/pull/13149
> Dhis2 14524 2.38 patch

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
Rolling back default sorting for analytics event/enrollment APIs.
> fix: Remove default sorting in events/enrollments [DHIS2-14805]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
[DHIS2-11731](https://dhis2.atlassian.net/browse/DHIS2-11731)
[DHIS2-11731]: https://dhis2.atlassian.net/browse/DHIS2-11731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.39) Fetch nested event notes in trackedEntityInstance endpoint [DHIS2-11731]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/13145
> ci: add Jenkins build status to GitHub commit [skip ci] [2.38]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/13145
> ci: add Jenkins build status to GitHub commit [skip ci] [2.37]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/DefaultOrganisationUnitService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CrudControllerAdvice.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SpringBindingTest.java
Backport of [DHIS2-13928](https://github.com/dhis2/dhis2-core/pull/13048)
[DHIS2-13928]: https://dhis2.atlassian.net/browse/DHIS2-13928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Handle BindException [DHIS2-13928] (#13048)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/route/RouteService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
Fixes a bug when using `code` based API for `Router`. Also adds translations for `Route`/`EventHook` aurhorities.
> fix: add authority translations and fix code matching

- jenkinsfiles/dev
Related to https://github.com/dhis2/jenkins-pipeline-library/pull/18
> ci: update pipeline shared lib git helper use [skip ci]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/13197
> ci: update pipeline shared lib git helper use [skip ci] [2.39]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/13197
> ci: update pipeline shared lib git helper use [skip ci] [2.38]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/13197
> ci: update pipeline shared lib git helper use [skip ci] [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
please see: https://dhis2.atlassian.net/browse/DHIS2-14805
> feat: Default pe dimension [2.39-DHIS2-14805-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
please see: https://dhis2.atlassian.net/browse/DHIS2-14805
> feat: Default pe dimension [2.38-DHIS2-14805-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
please see: https://dhis2.atlassian.net/browse/DHIS2-14805
> feat: Default pe dimension [2.40-DHIS2-14805-3]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramStageInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
backport[ DHIS2-12934](https://dhis2.atlassian.net/browse/DHIS2-12934)
> fix:(2.38) Unexpected change of dueDate if a datavalue is updated

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/13245
> ci: Add Flyway repair flag to dev pipeline [skip ci] [2.40]

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/13245
> ci: Add Flyway repair flag to dev pipeline [skip ci] [2.39]

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/13245
> ci: Add Flyway repair flag to dev pipeline [skip ci] [2.38]

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/13245
> ci: Add Flyway repair flag to dev pipeline [skip ci] [2.37]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notification.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationDataType.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationMapTest.java
> feat: Include job parameters in first notifier message of a job run [DHIS2-14372] (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleVariable.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleVariableService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleVariableService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_update_datavalue_same_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
This reverts commit b2b6bbb10d92c6e1692cf6f667d4725ca7793551 as it introduced https://dhis2.atlassian.net/browse/DHIS2-14916 and it is blocking Android
> Revert "fix: Unable to save event in Capture when program rule assigns option name

- dhis-2/pom.xml
Reverts dhis2/dhis2-core#13269
> Revert "chore(deps): bump spring-security.version from 5.7.5 to 5.8.2 in /dhis-2"

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/route/RouteService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/RouteController.java
Adds `X-Forwarded-User` to `/api/routes/X/run` requests.
> feat: add username in route requests

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/DataSet.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/dataelement/DataElementTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/dataset/DataSetTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/validation/ExpirationDaysCheck.java
> fix: period date range check should consider end date as full day [DHIS2-14591] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/DataInputPeriod.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/DataSet.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/dataelement/DataElementTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/dataset/DataSetTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/validation/ExpirationDaysCheck.java
Based on cherry-pick from  #13261.
Needed some manual merge. Mostly imports and differences between junit4/5 and methods that got renamed.
> fix: period date range check should consider end date as full day [DHIS2-14591] (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramStageInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/mapper/EventRowCallbackHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
backport [DHIS2-14836](https://dhis2.atlassian.net/browse/DHIS2-14836)
[DHIS2-14836]: https://dhis2.atlassian.net/browse/DHIS2-14836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.39) correct eventDate in NTI [DHIS2-14836]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PingController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
backport https://github.com/dhis2/dhis2-core/pull/13170 & https://github.com/dhis2/dhis2-core/pull/13187
> feat: add ping endpoint [DHIS2-14531] (2.39)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PingController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
backport https://github.com/dhis2/dhis2-core/pull/13170 & https://github.com/dhis2/dhis2-core/pull/13187
> feat: add ping endpoint [DHIS2-14531] (2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PingController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
backport https://github.com/dhis2/dhis2-core/pull/13170 & https://github.com/dhis2/dhis2-core/pull/13187
> feat: add ping endpoint [DHIS2-14531] (2.37) 

- .github/workflows/analyse-pr.yml
If there are better ways I'm open to suggestions.
> fix: Add new branch range as attempt to fix SonarQube analysis

- .github/workflows/analyse-pr.yml
Applying the same fix from branch 2.40
> fix: Add new branch range to fix SonarQube analysis

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/DataSet.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/dataelement/DataElementTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/dataset/DataSetTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/validation/ExpirationDaysCheck.java
> fix: period date range check should consider end date as full day [DHIS2-14591] (2.40)

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionParam.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/TeiStaticField.java
please see: https://dhis2.atlassian.net/browse/DHIS2-14852
> feat: New "ounamehierarchy" column in CPL [CPL_DEVELOPMENT_14852]

- dhis-2/build-dev.sh
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/feedback/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/TrackerTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
backport of https://github.com/dhis2/dhis2-core/pull/13253
> fix: event pageSize is not respected with more than 1 category DHIS2-13135 [2.40]

- dhis-2/build-dev.sh
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/feedback/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/TrackerTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
backport of https://github.com/dhis2/dhis2-core/pull/13253
> fix: event pageSize is not respected with more than 1 category DHIS2-13135 [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
[[DHIS2-7318](https://dhis2.atlassian.net/browse/DHIS2-7318)]
[DHIS2-7318]: https://dhis2.atlassian.net/browse/DHIS2-7318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: broken oauth [DHIS2-7318]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAttribute.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonNote.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonProgramOwner.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationship.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationshipItem.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
backporting https://github.com/dhis2/dhis2-core/pull/13328 since we need the tests as a base to fix https://dhis2.atlassian.net/browse/DHIS2-14407 in https://github.com/dhis2/dhis2-core/pull/13334
> test: /tracker/relationships returns nested fields TECH-1515 [2.40]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAttribute.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonNote.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonProgramOwner.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationship.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationshipItem.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
backporting https://github.com/dhis2/dhis2-core/pull/13328 since we need the tests as a base to fix https://dhis2.atlassian.net/browse/DHIS2-14407 in https://github.com/dhis2/dhis2-core/pull/13334
> test: /tracker/relationships returns nested fields TECH-1515 [2.39]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackedEntityAttributeControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAttribute.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonNote.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonProgramOwner.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationship.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationshipItem.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
backporting https://github.com/dhis2/dhis2-core/pull/13328 since we need the tests as a base to fix https://dhis2.atlassian.net/browse/DHIS2-14407 in https://github.com/dhis2/dhis2-core/pull/13334
> test: /tracker/relationships returns nested fields TECH-1515 [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExpressionDimensionItemController.java
please see: https://dhis2.atlassian.net/browse/DHIS2-14906
> fix: Users should be able to see EDIs by default in shared dashboards[DHI2S-14906] 2.40 backport

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/security/EnrollmentSecurityTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
backport https://github.com/dhis2/dhis2-core/pull/13274
Had to fix many unit tests because after this PR the error is not really accurate.
> fix: refactor owner check in AclService [TECH-1516] (2.38)

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/security/EnrollmentSecurityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
backport https://github.com/dhis2/dhis2-core/pull/13274
> fix: refactor owner check in AclService [TECH-1516] (2.39)

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/security/EnrollmentSecurityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
backport https://github.com/dhis2/dhis2-core/pull/13274
> fix: refactor owner check in AclService [TECH-1516] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonDataValue.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationshipItem.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonUser.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13334
> fix: fetch nested fields of trackedEntity and events in /tracker/relationships DHIS2-14407 [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonDataValue.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationshipItem.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonUser.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13334
> fix: fetch nested fields of trackedEntity and events in /tracker/relationships DHIS2-14407 [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonDataValue.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationshipItem.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonUser.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13334
> fix: fetch nested fields of trackedEntity and events in /tracker/relationships DHIS2-14407 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleVariable.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleVariableService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleVariableService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_update_datavalue_same_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
This reverts commit b2b6bbb10d92c6e1692cf6f667d4725ca7793551.
> Revert "fix: Unable to save event in Capture when program rule assigns option name"

- dhis-2/build-dev.sh
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/simple_metadata.json
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
backport of https://github.com/dhis2/dhis2-core/pull/13253
> fix: event pageSize is not respected with more than 1 category DHIS2-13135 [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expressiondimensionitem/ExpressionDimensionItem.java
Removing the EDI removes all EDIs with the same expression.
> fix: removing EDIs from visualization[DHIS2-14906-fix]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportConflict.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/ImportContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidatorTest.java
backport from cherry-pick of #13309
> fix: data value set import stric data element fallback [DHIS2-14693] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportConflict.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidatorTest.java
Manual backport.
Reapplies the changes in #12533 in a simpler form.
> fix: data value set import stric data element fallback [DHIS2-14693]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportConflict.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/ImportContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidatorTest.java
backport from cherry-pick of #13309
> fix: data value set import stric data element fallback [DHIS2-14693] (2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
backport https://github.com/dhis2/dhis2-core/pull/13370
> chore: remove unused code DHIS2-13135 [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
backport https://github.com/dhis2/dhis2-core/pull/13370
> chore: remove unused code DHIS2-13135 [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
backport https://github.com/dhis2/dhis2-core/pull/13370
> chore: remove unused code DHIS2-13135 [2.40] (#13371)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13303
> perf: Build context and call rule engine only when needed [DHIS2-14917]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notification.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationDataType.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationMapTest.java
Manual backport of #13226
Mostly picked individual files from master using `git checkout master <file>`. 
Reimplemented the newly added method `notify` in `Notifier` with additional arguments.
> feat: Include job parameters in first notifier message of a job run [DHIS2-14372] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notification.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationDataType.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationMapTest.java
Manual backport of https://github.com/dhis2/dhis2-core/pull/13226
Mostly picked individual files from master using git checkout master <file>.
Reimplemented the newly added method notify in Notifier with additional arguments.
> feat: Include job parameters in first notifier message of a job run [DHIS2-14372] (2.38)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
Please see: https://dhis2.atlassian.net/browse/DHIS2-14932.
> fix: redundant "0" digits for ProgramIndicators [DHIS2-14932]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
Please see https://dhis2.atlassian.net/browse/DHIS2-14932.
> fix: redundant "0" digits for ProgramIndicators [2.40-DHIS2-14932]-backport

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
* fix: broken password generator in invite user
(cherry picked from commit 9660a645e6dec6eec48f3bc962d56af63170c537)
> fix: broken password generator in invite user (#12418)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportConflict.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/ImportContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidatorTest.java
backport from cherry-pick of #13309
> fix: data value set import strict data element fallback [DHIS2-14693] (2.40.0)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtilsTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
see https://github.com/dhis2/dhis2-core/pull/13377
> fix: Characters not accepted in Tracker capture Attributes [ DHIS2-10215 ] REVERT patch/2.40

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/event_and_enrollment.json
Back port of https://github.com/dhis2/dhis2-core/pull/13123
> fix: Respect sort event's order criteria [DHIS2-13735]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13303
> perf: Build context and call rule engine only when needed [DHIS2-14917](2.40.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValue.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/email/EmailResponse.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/RelativePeriods.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/FieldFilterService.java
Fixes several issues reported in https://sonarcloud.io/project/issues?resolved=false&types=BUG%2CVULNERABILITY&id=dhis2_dhis2-core
> chore: sonar issues

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CombinationGenerator.java
backport https://github.com/dhis2/dhis2-core/pull/13354
> fix: empty CSV file download from VisualizationDataController [DHIS2-14240]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13455
> fix: Sort when no sortable attributes found [DHIS2-15020] [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13455
> fix: Sort when no sortable attributes found [DHIS2-15020] [2.38]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13455
> fix: Sort when no sortable attributes found [DHIS2-15020] [2.40]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
> fix: set last login of replicated user to null [DHIS2-14995]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
cherry-pick backport of #13472
> fix: set last login of replicated user to null [DHIS2-14995] (2.40)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
cherry-pick backport of #13473
> fix: set last login of replicated user to null [DHIS2-14995] (2.39)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SchemaControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SchemaController.java
Removes the feature. MH:
> it was just meant to dynamically introspect what was inside dhis2.. unused and not useful :slightly_smiling_face: please remove it
> fix: remove schema by java class name API [DHIS2-15028]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
> fix: set last login of replicated user to null [DHIS2-14995] (2.37)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
cherry-pick backport of #13473
> fix: set last login of replicated user to null [DHIS2-14995] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DhisHttpSessionEventListener.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
- dhis-2/dhis-web-embedded-jetty/src/main/java/org/hisp/dhis/web/embeddedjetty/JettyEmbeddedCoreWeb.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
* chore: enable explicit session saving in authentication filters
(cherry picked from commit a551554c10b0ef868e33da3187ec95ae5c46d663)
> chore: enable explicit session saving in authentication filters (#13431)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/maintenance/MaintenanceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/maintenance/MaintenanceStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/DefaultMaintenanceService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
cherry-pick backport of #13478
> perf: prune periods with database statement [DHIS2-14996] (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/apikey/ApiTokenAuthenticationToken.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/apikey/ApiTokenAuthManager.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/apikey/Dhis2ApiTokenFilter.java
(cherry picked from commit 3e42c9e464e2df2f9b4afaa90adc0766b981ab07)
> chore: log API token authentication events (#13444)

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.validation.js
backport of https://github.com/dhis2/dhis2-core/pull/13360
> fix: data entry struts app coordinate validator [DHIS2-14930] [2.40]

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.validation.js
backport of https://github.com/dhis2/dhis2-core/pull/13360
> fix: data entry struts app coordinate validator [DHIS2-14930] [2.39]

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.validation.js
backport of https://github.com/dhis2/dhis2-core/pull/13360
> fix: data entry struts app coordinate validator [DHIS2-14930] [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtilsTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
see https://github.com/dhis2/dhis2-core/pull/13285
> fix: Characters not accepted in Tracker capture Attributes [DHIS2-10215] [2.40]

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.validation.js
backport of https://github.com/dhis2/dhis2-core/pull/13360
> fix: data entry struts app coordinate validator [DHIS2-14930] [2.37]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
Assigned user was retrieved correctly from the DB but never actually set to the event.
> fix: Missing assigned user mapping for events [TECH-1526]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataExportParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DeflatedDataValue.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataConsolidator.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataConsolidatorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
* fix: Predictor w/multiple queryMods [DHIS2-15061]
* fix: getDdvDataElementLists
(cherry picked from commit 6aca45efb71db395303c51aeeb4fce7e5e6a0df2)
[DHIS2-15061]: https://dhis2.atlassian.net/browse/DHIS2-15061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Predictor w/multiple queryMods [DHIS2-15061] (#13507)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/web/WebClientUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonError.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/domain/DomainJsonResponseTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerTestBase.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractDataValueControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueFileResourceControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueMultiTextControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
cherry-pick backport of #13412
> fix: clear file resource data value with empty value/file [DHIS2-12735] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/web/WebClientUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonError.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/domain/DomainJsonResponseTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerTestBase.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractDataValueControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueFileResourceControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueMultiTextControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
cherry-pick backport of #13412
> fix: clear file resource data value with empty value/file [DHIS2-12735] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/jdbc/JdbcOrgUnitAssociationsStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationsStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
see https://github.com/dhis2/dhis2-core/pull/13503
> fix:  Enrollments POST API failure with caching issue [ 2.40 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/jdbc/JdbcOrgUnitAssociationsStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationsStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
see https://github.com/dhis2/dhis2-core/pull/13503
> fix: Enrollments POST API failure with caching issue [ 2.39 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationsStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationsStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
see https://github.com/dhis2/dhis2-core/pull/13503
> fix: Enrollments POST API failure with caching issue [ 2.38 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationsStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationsStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
see https://github.com/dhis2/dhis2-core/pull/13503
> fix: Enrollments POST API failure with caching issue [ 2.37 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/collection/CollectionUtils.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/duplicate_categories.json
backport https://github.com/dhis2/dhis2-core/pull/12899
> feat: add validation for duplicate items in collection [DHIS2-10313]

- dhis-2/dhis-test-integration/src/test/resources/dxf2/dataset_with_accesses_merge_mode.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/dataset_with_accesses_skipSharing.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/dataset_with_accesses_update.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/dataset_with_publicAccess_update.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/de_create_and_update1.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/de_create_and_update2.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/de_update1.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/de_update2.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/defaults_invalid.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/favorites/metadata_visualization_with_accesses.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/import/te_type_missing_tea.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/import/te_type_tea_ok.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/program_programStage_with_sharing.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/simple_metadata_uga.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/usergroups.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/usergroups_update.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/ownership_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_with_tea_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata_mandatory_attr.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_metadata_with_program_rules.json
This is a part of https://github.com/dhis2/dhis2-core/pull/12991
> chore: use new Sharing for integration tests

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/relationship/LinkValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/relationship/MandatoryFieldsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/relationship/LinkValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/relationship/MandatoryFieldsValidatorTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13588
> fix:Move validation from link to mandatory validator [DHIS2-14711][2.40]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/relationship/LinkValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/relationship/MandatoryFieldsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/relationship/LinkValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/relationship/MandatoryFieldsValidatorTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13588
> fix: Move validation from link to mandatory validator [DHIS2-14711][patch/2.40]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/recovery.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/recovery.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/useraccount/action/IsInviteTokenValidAction.java
(cherry picked from commit b39e05b2cd6dca8592e2c7bb86d574d9936aad48)
> fix: broken invite and recovery due to new CSP policy (#13602)

- dhis-2/pom.xml
(cherry picked from commit b0a29e41e36661e2127edceaba6b50002f683fc7)
> chore: change to Google's maven repo1 mirror (#13569)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/expressiondimensionitem/hibernate/ExpressionDimensionItem.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_21__Update_shortname_in_expressiondimensionitem.sql
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_4__Expression_Dim_Item_Remove_Names_Uniquiness.sql
_[Backport from master/2.41]_
Remove uniqueness from name/shortName in EDIs.
> fix: EDIs name/shortName should not be unique [DHIS2-15106]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
> fix: backward comp for update analytics dimension restrictions [DHIS2-14870]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/ImportContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportSummary.java
> feat: list rejected indexes in data value set import [DHIS2-4678] (2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/ImportContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportSummary.java
> feat: list rejected indexes in data value set import [DHIS2-4678] (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/TeiQueryRequestMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/TeiQueryRequestMapperTest.java
This PR adds a validation to check if all programs passed to Tei Analytics endpoints are defined for the given tracked entity type
> feat: Programs are now validate against TET [DHIS2-15042]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
Fixes issue where the user can not update/change their profile picture without having admin like F_USER_ADD authority.
This fix moves this functionality from the /users endpoint to the /me endpoint which it should have been in the first place, since it does not require any special authorities to use. 
1. Upload a picture by using going to profile and chose upload picture. This will fail but the picture will be uploaded.
2. Use chrome inspector and look at the POST request to /fileResources, capture the result and get the fileResource ID.
3. Use the following curl to link the new uploaded file to the avatar:
```
curl -X PUT --location "http://localhost:8080/api/41/me" \
-H "Content-Type: application/json;charset=UTF-8" \
-d "{\"avatar\": {\"id\": \"FILE_RESOURCE_UID\"}}" \
--basic --user …
```
> fix: users cannot change their avatar [DHIS2-14223]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/AppOverrideFilter.java
> fix: use etag cache control instead of last-modified-by for app overrides [DHIS2-14957] (2.40)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/AppOverrideFilter.java
> fix: use etag cache control instead of last-modified-by for app overrides [DHIS2-14957] (2.39)

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterSimpleBeanPropertyFilter.java
* fix: cache always expand field filter test
> fix: cache always expand field filter test (#13685)

- dhis-2/dhis-services/dhis-service-field-filtering/pom.xml
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
Jira: [BETA-40](https://dhis2.atlassian.net/browse/BETA-40)
[BETA-40]: https://dhis2.atlassian.net/browse/BETA-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: missing transactional annotation in field filter service 2.40.0

- dhis-2/dhis-services/dhis-service-field-filtering/pom.xml
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
Jira: [BETA-40](https://dhis2.atlassian.net/browse/BETA-40)
[BETA-40]: https://dhis2.atlassian.net/browse/BETA-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: missing transactional annotation in field filter service

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_7__Add_index_in_table_datasetsource.sql
https://dhis2.atlassian.net/browse/TECH-1521
> feat: add index sourceid in table datasetsource [TECH-1521]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/executor/RuleActionExecutor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/executor/event/AssignDataValueExecutor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/executor/event/AssignDataValueExecutorTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13284 and https://github.com/dhis2/dhis2-core/pull/13644
>  fix: Assign null when option for data element is invalid [DHIS2-14190] (2.40)

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
https://dhis2.atlassian.net/browse/BETA-25
https://dhis2.atlassian.net/browse/BETA-26
> fix: aggregate data entry lock issues [BETA-25][BETA-26]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13684
> fix: Validate user scope when program protected [DHIS2-15145] [2.37]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13684
> fix: Validate user scope when program protected [DHIS2-15145] [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13684
> fix: Validate user scope when program protected [DHIS2-15145] [2.39]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteriaMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/13684
> fix: Validate user scope when program protected [DHIS2-15145] [2.40]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementerTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13284 and https://github.com/dhis2/dhis2-core/pull/13644
> fix: Assign null when option for data element is invalid [DHIS2-14190] (2.38)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementerTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13284 and https://github.com/dhis2/dhis2-core/pull/13644
> fix: Assign null when option for data element is invalid [DHIS2-14190] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/FollowupAnalysisMetadata.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/FollowupAnalysisResponse.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/FollowupAnalysisService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/FollowupValue.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/dataanalysis/DefaultFollowupAnalysisService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataAnalysisController.java
backport https://github.com/dhis2/dhis2-core/pull/13681
> fix: support download followUp analysis report [BETA-27]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_22__Add_index_in_table_datasetsource.sql
backport https://github.com/dhis2/dhis2-core/pull/13700
> feat: add index sourceid in table datasetsource [TECH-1521](2.40)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_24__Add_index_in_table_datasetsource.sql
backport https://github.com/dhis2/dhis2-core/pull/13700
> feat: add index sourceid in table datasetsource [TECH-1521](2.39)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_48__Add_index_in_table_datasetsource.sql
backport https://github.com/dhis2/dhis2-core/pull/13700
> feat: add index sourceid in table datasetsource [TECH-1521](2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageDataElementStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/mapper/RelationshipRowCallbackHandler.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/job/TrackerRuleEngineThread.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/ReferenceTrackerEntity.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/supplier/strategy/EventStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/StrategyPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/converter/RelationshipTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preheat/TrackerPreheatTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/UpdatableFieldsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/event/UpdatableFieldsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/UpdatableFieldsValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EventStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramMessageStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerEventBundleServiceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
its methods. Replace programStageInstance with event.
follow up to https://github.com/dhis2/dhis2-core/pull/13753
> chore: rename ProgramInstanceStore to EventStore TECH-1537

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13756
> fix: Filter out from sync teis updated before last sync [DHIS2-15223](2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13756
> fix: Filter out from sync teis updated before last sync [DHIS2-15223](2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramStageNotificationMessageRenderer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/EventDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramNotificationInstanceDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/event/ProgramRuleStageEvent.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/event/ProgramStageCompletionNotificationEvent.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/RelationshipDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitycomment/TrackedEntityCommentDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitydatavalue/hibernate/HibernateTrackedEntityDataValueAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementerTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MaintenanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/RelationshipController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/RelationshipControllerTest.java
more variables and method names containing `psi`, `programStageInstance`
> chore: rename programStageInstance to event TECH-1537

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/OrgUnitTableJoiner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipWriter.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/OrgUnitTableJoinerTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
* fix: Three ownership analytics bugs [DHIS2-13373]
* fix: OrgUnitTableJoinerTest
* fix: DhisConvenienceTest SonarLint smells
(cherry picked from commit 5b9ef693e9c216372e933e212907283c3a9c1dc0)
[DHIS2-13373]: https://dhis2.atlassian.net/browse/DHIS2-13373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Three ownership analytics bugs [DHIS2-13373] (#13365) (#13380)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
backport https://github.com/dhis2/dhis2-core/pull/13737
> fix: hibernate lazy collection issue in attributeCache [DHIS2-10331] (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
backport https://github.com/dhis2/dhis2-core/pull/13737
> fix: hibernate lazy collection issue in attributeCache [DHIS2-10331] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
backport https://github.com/dhis2/dhis2-core/pull/13737
> fix: hibernate lazy collection issue in attributeCache [DHIS2-10331] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13756
> fix: Filter out from sync teis updated before last sync [DHIS2-15223](2.38)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
Backport of https://github.com/dhis2/dhis2-core/pull/13633
> fix: Validate capture scope if program protected [DHIS2-15021] [2.38]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/13633
> fix: Validate capture scope when program protected [DHIS2-15021] [2.40]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
Backport of https://github.com/dhis2/dhis2-core/pull/13633
> fix: Validate capture scope if program protected [DHIS2-15021] [2.37]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
Backport of https://github.com/dhis2/dhis2-core/pull/13633
> fix: Validate capture scope if program protected [DHIS2-15021] [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/route/Route.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/route/RouteTest.java
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/route/RouteService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/RouteController.java
- dhis-2/dhis-web-embedded-jetty/pom.xml
Backport of #13710 to 2.40.0 (approved by RCB)
> feat: add support for subpath wildcards in route urls [DHIS2-15098] (2.40.0)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/route/RouteService.java
- dhis-2/dhis-services/dhis-service-event-hook/pom.xml
- dhis-2/dhis-services/dhis-service-event-hook/src/main/java/org/hisp/dhis/eventhook/handlers/WebhookHandler.java
Disables cookie management for webhooks.
> fix: disable cookie management for web requests

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/route/RouteService.java
- dhis-2/dhis-services/dhis-service-event-hook/pom.xml
- dhis-2/dhis-services/dhis-service-event-hook/src/main/java/org/hisp/dhis/eventhook/handlers/WebhookHandler.java
Disables cookie management for webhooks.
> fix: disable cookie management for web requests [DHIS2-15197]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobSchedulerController.java
> fix: handle fixed delay jobs in scheduler list API and startup [DHIS2-15241] (2.40.0)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobSchedulerController.java
> fix: handle fixed delay jobs in scheduler list API and startup [DHIS2-15241] (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
backport https://github.com/dhis2/dhis2-core/pull/13737
> fix: hibernate lazy collection issue in attributeCache [DHIS2-10331] (2.40.0)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
> fix: handle fixed delay jobs in scheduler list API and startup [DHIS2-15241] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
EventsExportController should only depend on the new tracker service. get... methods should throw if entity is not found as discussed in the backend meeting a while ago
> chore: replace programStageInstance with event TECH-1537

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionContextGenerator.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDisaggregator.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionContextGeneratorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDisaggregatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
(cherry picked from commit c7afebbb7fbdb63343c1700aaeb7b1c09acc257b)
> fix: Prediction by COC enabling [DHIS2-9832] (#13743)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
Please see: https://dhis2.atlassian.net/browse/DHIS2-15260
> fix: Time value missing in event table (line listing app) [2.41-DHIS2-15260]

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
backport https://github.com/dhis2/dhis2-core/pull/13828
> fix: owner should not have data access by default [DHIS2-15250] (2.40)

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
backport https://github.com/dhis2/dhis2-core/pull/13828
> fix: owner should not have data access by default [DHIS2-15250] (2.39)

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
backport https://github.com/dhis2/dhis2-core/pull/13828
> fix: owner should not have data access by default [DHIS2-15250] (2.38)

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
backport https://github.com/dhis2/dhis2-core/pull/13828
> fix: owner should not have data access by default [DHIS2-15250] (2.40.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstagefilter/EventFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstagefilter/EventFilterService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstagefilter/EventFilterStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/programstagefilter/DefaultEventFilterService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/programstagefilter/hibernate/HibernateEventFilterStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programstagefilter/hibernate/EventFilter.hbm.xml
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultSchemaService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/EventFilterSchemaDescriptor.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programstagefilter/EventFilterTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SchemaBasedControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventFilterController.java
to use the name event instead of programStageInstance.
> chore: rename internals of /eventFilters TECH-1537

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramIndicator.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
* feat: PI first/last aggregation type [DHIS2-14795]
* fix: formatting
* fix: cognitive complexity
* fix: SonarLint
* fix: ticket comments
* chore: SonarLint
* feat: Extend 'order by' to created, add tests
* fix: order by in EventAnalyticsManagerTest
* fix: reduce SonarCloud complexity
(cherry picked from commit 5b6236be36b8f60f062fe32956a86ecf26a03d69)
[DHIS2-14795]: https://dhis2.atlassian.net/browse/DHIS2-14795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: PI first/last aggregation type [DHIS2-14795] (#13549)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/13795
> fix: Createdbyuserinfo and lastupdatedbyuserinfo jsonb fields in trackedentityinstance are also blank [DHIS2-15225] [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/13795
> fix: Createdbyuserinfo and lastupdatedbyuserinfo jsonb fields in trackedentityinstance are also blank [DHIS2-15225] [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/13795
> fix: Createdbyuserinfo and lastupdatedbyuserinfo jsonb fields in trackedentityinstance are also blank [DHIS2-15225] [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspConstants.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/CspFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/action/LoginAction.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
(cherry picked from commit b1e7d903e3f7f9dbcfb9684ad8b6137905c09598)
> fix: add CSP frame ancestor header to mostly all responses (#13164)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityAttributeStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeStoreIntegrationTest.java
rename `entityInstance` to `trackedEntity` in `HibernateTrackedEntityAttributeStore`
> fix: TrackedEntityAttribute store entityIntsance to trackedEntity renaming TECH-1552

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/RequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/RequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/RequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/RequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/RequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/RequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RequestParamsTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/RequestParamsMapperTest.java
Simply rename Criteria classes to RequestParams and include field `fields` in it
> chore: Rename Criteria classes to RequestParams [TECH-1563]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DefaultDimensionService.java
Please see https://dhis2.atlassian.net/browse/DHIS2-15268
> fix: Cannot save visualisations with a fixed future period [2.41-DHIS2-15268]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManagerTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
Backport of https://github.com/dhis2/dhis2-core/pull/14068
> fix: Use search scope if no program provided [DHIS2-15021] [2.38]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManagerTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/14068
> fix: Use search scope if no program provided [DHIS2-15021] [2.37]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManagerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapperTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/14068
> fix: Use search scope if no program provided [DHIS2-15021] [P2.38.3.1]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsDimensionsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsDimensionsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsDimensionsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsDimensionsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/TeiAnalyticsDimensionsServiceTest.java
Please see https://dhis2.atlassian.net/browse/DHIS2-15069
> fix: Sharing settings on program indicators do not work [2.41-DHIS2-1509]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/expressiondimensionitem/ExpressionDimensionItemService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/expressiondimensionitem/ExpressionDimensionItemServiceTests.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/EnrollmentQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/EventQueryTest.java
Please see https://dhis2.atlassian.net/browse/DHIS2-15332.
> fix: EDI - parsing error for numeric expression [2.41-DHIS2-15332]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspConstants.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/CspFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/action/LoginAction.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
backport https://github.com/dhis2/dhis2-core/pull/13857
> fix: add CSP frame ancestor header to mostly all responses [DHIS2-14504] (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
Cherry-pick backport of #14124
> fix: always flush/close batch handlers in DVS import [DHIS2-15362] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
Cherry-pick backport of #14124
> fix: always flush/close batch handlers in DVS import [DHIS2-15362] (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
Cherry-pick backport of #14124
> fix: always flush/close batch handlers in DVS import [DHIS2-15362] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/expressiondimensionitem/hibernate/ExpressionDimensionItem.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_25__Fix_hibernate_validate_ddl.sql
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/postgresTestConfig.conf
see https://github.com/dhis2/dhis2-core/pull/14167
> fix: Validate Hibernate schema using hibernate.hbm2ddl.auto = validate [ TECH-1576 ] [2.40]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/hibernate/HibernateFileResourceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/icon/jdbc/JdbcCustomIconStore.java
Lookup custom icon keys by the storage key of the file resource used by the icon.
> feat: reverse lookup support for custom icon file resources [DHIS2-15414]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DimensionalObjectProducerTest.java
Please see  https://dhis2.atlassian.net/browse/DHIS2-15044
> fix: Visualizer download resulting in ERR_INVALID_RESPONSE when ALL_ITEMS is in use [2.41-DHIS2-15044]

- dhis-2/dhis-web-api/src/main/resources/openapi/EnrollmentsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/EventsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/RelationshipsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/Tags.md
- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
might relate to changes in https://github.com/dhis2/dhis2-core/pull/14087
* fix externalDocs in Tags which had its header at the same level of its parent
> docs: fix OpenAPI descriptions TECH-1568

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/JacksonPropertyIntrospector.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/patch/PatchServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/14251
> fix: Date property type should be simple [DHIS2-15068] (2.40)

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/JacksonPropertyIntrospector.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/patch/PatchServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/14251
> fix: Date property type should be simple [DHIS2-15068] (2.39)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/patch/PatchServiceTest.java
> fix: flaky test in PatchServiceTest (2.40)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/patch/PatchServiceTest.java
> fix: flaky test in PatchServiceTest (2.39)

- jenkinsfiles/dev
The fields were updated in this PR - https://github.com/dhis2-sre/im-manager/pull/276, so the references here need to be updated as well.
> ci: update IM JSON field references [skip ci]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/user/UserTest.java
Small refactor for the `User` class
- simplify some utility methods on the User class
- add tests for refactored methods
- add tests for methods calling refactored methods
> chore: Refactor to User class to simplify some 'get' and 'has' methods

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
* Adds a list of the user's personal access tokens to the /me endpoint for convenience.
> feat: add PATs to the me API enpoint

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/database/DatabaseInfo.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/database/DatabaseInfoTest.java
* fix: show database spatialSupport in the system info endpoint
(cherry picked from commit 7398f29fa03875bfbf42c3db73fbd63b1988a1b2)
> fix: show database spatialSupport in the system info endpoint (#13564)

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/useraccount/action/IsSelfRegistrationAllowedAction.java
JIRA: [DHIS2-15107](https://dhis2.atlassian.net/browse/DHIS2-15107)
[DHIS2-15107]: https://dhis2.atlassian.net/browse/DHIS2-15107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bug: fix broken recaptcha on invite page due to csp

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
backport https://github.com/dhis2/dhis2-core/pull/13810
> fix: error when deleting Dashboard [BETA-66] (2.37)

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/useraccount/action/IsSelfRegistrationAllowedAction.java
(cherry picked from commit 174150aaf99cff3cccb9eed9312702753b14adfc)
> bug: fix broken recaptcha on invite page due to csp (#14403)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
See #14458
This backport only contains the relevant functional change.
> fix: data value sets export CSV via file extionsion [DHIS2-15294] (2.40)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
See #14458
This backport only contains the relevant functional change.
> fix: data value sets export CSV via file extionsion [DHIS2-15294] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserGroupService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonUserGroup.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
backport, see original PR fix #14462
> fix: Update User API to update lastUpdatedBy when updating UserGroups [DHIS2-15357]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
> fix: only read patch body once from HTTP input stream [DHIS2-15516] (2.37.10)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DefaultDataApprovalService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceCategoryOptionGroupTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataApprovalController.java
* feat: multiple aocs for approvals/coc DHIS2-14371
* fix: special case null aoc in approval COGStest
* Review comments
(cherry picked from commit 3cbddd12d38947f2f43a215c0a3e544809bd7c77)
> feat: multiple aocs for approvals/coc DHIS2-14371 (#14343)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteria.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtilsTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
see https://github.com/dhis2/dhis2-core/pull/13981
> fix: escape attribute filter value when it contains comma or colon [ DHIS2-15298 ] [ 2.40 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
Since #14185 multiple properties could be plucked - also this allowed to pluck non `String` properties.
When plucking a property of type `IdentifiableObject` this way this would result in its `long` database ID but should have become its UID instead. 
Also plucking a single non `String` property would result in an error rather than using the JSON solution that can handle such properties. 
Both issue get fixed in this PR.
> fix: Gist API - pluck IdentifiableObject as UID not long ID [DHIS2-15567]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/RedisNotifierTest.java
> fix: Sort returned Notifications from Redis by time [DHIS2-14838]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventvisualization/EventRepetition.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/orgunit/handler/DataOrgUnitMergeHandler.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AssignedUserSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/NoteSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/OrganisationUnitSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/TrackedEntityInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContextLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramInstanceRepeatableStageCheck.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathConverter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/PersistablesFilterTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/dataanalysis/jdbc/JdbcDataAnalysisStore.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/outlierdetection/service/MinMaxOutlierDetectionManager.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/outlierdetection/service/ZScoreOutlierDetectionManager.java
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/security/JwtBearerTokenTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/security/utils/Jwks.java
- dhis-2/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/14512
> chore: allow turning off formatter for java via spotless DHIS2-15518 [2.39]

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistValidator.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistPagerControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistValidationControllerTest.java
- dhis-2/dhis-web-api/pom.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/JsonBuilder.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
backport of #14544
A cherry-picking attempt made it obvious that some previous improvements did not get backported. I decided to backport entire Gist API by copying entire files from master (and then fixing Java 17 feature usages).
> fix: Gist API - array fields as array of objects [DHIS2-15168]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobConfigurationTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/scheduling/hibernate/JobConfiguration.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_21__Drop_jobconfiguration_leaderonlyjob_column.sql
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
cherry-pick from #14570
manual merge to drop changes in controller that did not exist yet.
> fix: leader only job as job type property [DHIS2-15288] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityCheck.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReader.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
> fix: provide displayName for all data integrity checks [DHIS2-14770] (2.37.10)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/CodecUtils.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
checkout of the touched files from `master` just copied/moved to the different maven module the code was in in 2.38.
> fix: use etag cache control instead of last-modified-by for app overrides [DHIS2-14957] (2.38)

- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorCount.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorFunction.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorFunctionDoubleArray.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorMedian.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorPercentileBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
* fix: PI count() for text values DHIS2-14769
* fix: protected constructors for abstract classes
(cherry picked from commit ef5c7b229379529d66e15dfe5290ada1c6c234aa)
> fix: PI count() for text values DHIS2-14769 (#14614)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
backport of https://github.com/dhis2/dhis2-core/pull/14631
> fix: /tracker/trackedEntities?order=createdAt DHIS2-15325 [2.40]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerTrackedEntityCriteriaTest.java
backport of https://github.com/dhis2/dhis2-core/pull/14661
> fix: /tracker/trackedEntities?order=createdAt DHIS2-15325 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityQueryParams.java
this was commenting a line that has been removed
> chore: remove invalid comment DHIS2-15325

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/14678
> fix: event with multiple notes returned multiple times by /tracker/events DHIS2-15603 [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/14679
> fix: event with multiple notes returned multiple times by /tracker/events DHIS2-15603 [2.38]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/Relationships.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
[Continuing from https://github.com/dhis2/dhis2-core/pull/14677](https://github.com/dhis2/dhis2-core/pull/14701)
Harmonize pagination in Relationships Controller
**What it is in this PR**
- Push down pagination logic to the service layer
> chore: Harmonize Relationship Controller [TECH-1572]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsUtilsTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/EventQueryTest.java
please see https://dhis2.atlassian.net/browse/DHIS2-14932
> fix: Visualization download should remove redundant "0" digits for Program Indicators[2.41-DHIS2-14932_2]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RegistrationSingleEventServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EventParamsMapperUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/RequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToParamsMapperTest.java
- dhis-2/pom.xml
Back port of: https://github.com/dhis2/dhis2-core/pull/14402
>  fix: Harmonize ACL depending on org unit mode [DHIS-15394] [2.38] 

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/deprecated/tracker/event/EventExportTests.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/RegistrationSingleEventServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/EventUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/EventRequestToSearchParamsMapperTest.java
Back port to old API of: https://github.com/dhis2/dhis2-core/pull/14402
> fix: Adapt old api to org unit mode acl standard [DHIS2-1604]

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
- was able to replicate failing tests locally when DHIS2_HOME not set
- fix resolves the failing tests
> fix: Surround location manager call in try catch [DHIS2-15626]

- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorCount.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorFunction.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorFunctionDoubleArray.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorMedian.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorPercentileBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
* fix: PI count() for text values DHIS2-14769
* fix: protected constructors for abstract classes
(cherry picked from commit ef5c7b229379529d66e15dfe5290ada1c6c234aa) (cherry picked from commit c17592e9072bdd9c8aa69c17d03367a02f59ab15)
> fix: PI count() for text values DHIS2-14769 (#14614) (#14637)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Cherry picked from: https://github.com/dhis2/dhis2-core/pull/14730
> fix: update createdby when replicating users [DHIS2-15595]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Cherry picked from: https://github.com/dhis2/dhis2-core/pull/14730
> fix: update createdby when replicating users [DHIS2-15595] 

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapperTest.java
backport of: https://github.com/dhis2/dhis2-core/pull/14787
> fix: Avoid org unit and unit mode in events request [TECH-1585] [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/RequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToParamsMapperTest.java
backport of: https://github.com/dhis2/dhis2-core/pull/14787
> fix: Avoid org unit and unit mode in events request [DHIS2-1585] [2.38]

- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SpringBindingTest.java
Weirdly binding of default values in binding object done by Spring MVC seems to work fine.
I am just adding a Controller test to verify that.
> chore: Add test for default value in binding object [TECH-1592]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryDownloadTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tei/TeiAnalyticsController.java
Adds support for the download of TEIs, following the same way already implemented for events/enrollments.
Also, some e2e tests were added to test the basic functions of each endpoint.
> feat: Download for analytics query TEI [DHIS2-15182]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
just backport, please see https://dhis2.atlassian.net/browse/DHIS2-14932
> fix: Visualization download should remove redundant "0" digits for Program Indicators[2.39-DHIS2-14932-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
just backport, please see https://dhis2.atlassian.net/browse/DHIS2-14932
>  fix: Visualization download should remove redundant "0" digits for Program Indicators[2.38-DHIS2-14932-backport]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerTypeReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleImportReportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonBundleReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonEntity.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonImportReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonTypeReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportReportTest.java
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_flatten_payload.json
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_nested_payload.json
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_nested_payload_repeated_relationships.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/BodyConverter.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/BodyConverterTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/14737 and https://github.com/dhis2/dhis2-core/pull/14758
> chore: Order objects in tracker import report [DHIS2-15596] (#14737)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipStore.java
this decouples us from old tracker allowing us to implement ordering and more as in other entities.
> chore: create new tracker relationship store TECH-1535

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapperTest.java
this decouples us from old tracker allowing us to implement ordering and more as in other entities.
> chore: create new tracker enrollment store TECH-1535

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityCheck.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReader.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
> fix: provide displayName for all data integrity checks [DHIS2-14770] (2.37 backport)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerObjectReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerTypeReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleImportReportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonBundleReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonEntity.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonImportReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonTypeReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportReportTest.java
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_flatten_payload.json
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_nested_payload.json
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_nested_payload_repeated_relationships.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerBundleParamsConverter.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerBundleParamsConverterTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/14737 and https://github.com/dhis2/dhis2-core/pull/14758
> chore: Order objects in tracker import report [DHIS2-15596] 2.39

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerObjectReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerTypeReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleImportReportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonBundleReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonEntity.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonImportReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonTypeReport.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportReportTest.java
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_flatten_payload.json
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_nested_payload.json
- dhis-2/dhis-test-web-api/src/test/resources/tracker/import_nested_payload_repeated_relationships.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerBundleParamsConverter.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerBundleParamsConverterTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/14737 and https://github.com/dhis2/dhis2-core/pull/14758
> chore: Order objects in tracker import report [DHIS2-15596] 2.38

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
[DHIS2-14836](https://dhis2.atlassian.net/browse/DHIS2-14836)
> fix:(2.40) Add timestamp to event executionDate, created

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/recovery.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/recovery.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/useraccount/action/IsInviteTokenValidAction.java
(cherry picked from commit b39e05b2cd6dca8592e2c7bb86d574d9936aad48)
> fix: broken invite and recovery due to new CSP policy

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/report/AbstractEventRowService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/report/EventRowService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/AbstractStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventXmlImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationSingleEventServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/14851
> chore: rename EventSearchParams to EventQueryParams [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/report/AbstractEventRowService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/report/EventRowService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventXmlImportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RegistrationSingleEventServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/RequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToParamsMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/14851
> chore: rename EventSearchParams to EventQueryParams [2.38]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/report/AbstractEventRowService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/report/EventRowService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/AbstractStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventXmlImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationSingleEventServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToQueryParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/14851
> chore: rename EventSearchParams to EventQueryParams [2.39]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractGistControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DimensionControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/WebRequestData.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/utils/PaginationUtilsTest.java
> fix: Fix Dimensions Pager info [DHIS2-15613]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserDetailsImpl.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/pom.xml
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/CacheInvalidationConfiguration.java
- dhis-2/dhis-web-api/pom.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/session/RedisSpringSessionConfiguration.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/session/SpringHttpSessionInitializer.java
- dhis-2/dhis-web-embedded-jetty/src/main/java/org/hisp/dhis/web/embeddedjetty/SpringConfiguration.java
- dhis-2/dhis-web/dhis-web-commons/pom.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
Fixes long standing issue with not being able to configure max concurrent sessions.
N/A
1. Set `max.sessions.per_user` to 1 in dhis.conf and start server.
2. Open two different browsers or one incognito tab and one regular.
3. Login in to one 'regular tab'/browser with admin user.
4. Long to another 'incognito tab'/browser with admin user. 
5. Refresh the first tab/browser and observe you are logged out and redirected to the login page.
JIRA: [DHIS2-13453](https://dhis2.atlassian.net/browse/DHIS2-13453)
> fix: not possible to change max concurrent user sessions [DHIS2-13453]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidator.java
to work for one or more fields that cannot be ordered by.
> chore: rephrase order validation message TECH-1535

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/validation/DefaultSchemaValidator.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/validation/DefaultSchemaValidatorTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/users/UserTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/systemsettings/SystemSettingsTests.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Backport of: [13787](https://github.com/dhis2/dhis2-core/pull/13787) & [14904](https://github.com/dhis2/dhis2-core/pull/14904)
Jira: [DHIS2-15195](https://dhis2.atlassian.net/browse/DHIS2-15195)
[DHIS2-15195]: https://dhis2.atlassian.net/browse/DHIS2-15195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Misleading message about password requirements [DHIS2-15195]

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/multiOrgSectionForm.vm
Backport of https://github.com/dhis2/dhis2-core/pull/13227 for 2.37.10.
Ticket: https://dhis2.atlassian.net/browse/DHIS2-13088
> fix: use correct customSectionCategoryCombos name [DHIS2-13088] (#13227)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/openapi/PropertyTest.java
with JsonProperty so that DB serialisation doesn't break and add support for OpenApi.Ignore on Lombok generated setters
> fix: re-annotate idSchemes in Import

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataset/notifications/DataSetNotificationServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/11475
> fix: null value for CompleteDataSetRegistration.periodName [DHIS2-12566] (2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToQueryParamsMapperTest.java
Back port of: https://github.com/dhis2/dhis2-core/pull/14901
> fix: Ignore org unit if org unit mode does not use it [TECH-1628][2.39]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EventParamsMapperUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/RequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToParamsMapperTest.java
Back port of: https://github.com/dhis2/dhis2-core/pull/14901
> fix: Ignore org unit if org unit mode does not use it [TECH-1628][2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/hibernate/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/hibernate/EventReport.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventvisualization/hibernate/EventVisualization.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_17__Add_sorting_to_eventvisualization.sql
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_27__Add_skip_rounding_to_eventvisualization.sql
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
Adds a new boolean flag into `EventVisualization`.
As this flag is shared with `Visualization` I decided to move this flag up in the hierarchy.
> feat: Add skipRounding flag into EV [DHIS2-15689] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/userdatastore/UserDatastoreEntry.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/userdatastore/UserDatastoreService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/userdatastore/UserDatastoreStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DatastoreQueryValidator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DefaultDatastoreService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/DatastoreQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/HibernateDatastoreStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/userdatastore/DefaultUserDatastoreService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/userdatastore/hibernate/HibernateUserDatastoreStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/orgunitprofile/impl/DefaultOrgUnitProfileService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastore/DatastoreEntryStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastore/DatastoreIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastore/DatastoreServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/userdatastore/UserDatastoreEntryStoreTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractUserDatastoreControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreOrderControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreFieldsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreFilterControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreOrderControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreSuperuserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractDatastoreController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DatastoreController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserDatastoreController.java
Updates the `/api/userDataStore` to support the same `fields` and `filter` parameters as `/api/dataStore` API. 
In this context the other methods in the endpoint were lined up so they behave equally in both APIs (following how `/dataStore` did behave). 
Also renamed some methods to line up better and used the feedback exceptions.
New tests were added based on the existing tests for the `/dataStore` API just now for the `/userDataStore` API.
Existing tests were adjusted to expect the common messages.
> feat: user datastore query API [DHIS2-15723]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/metadata/metadata_with_visualization.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/VisualizationController.java
backport https://github.com/dhis2/dhis2-core/pull/14949
> fix: VisualizationController getEntityList not show nested filters [DHIS2-15322] 2.40

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/metadata/metadata_with_visualization.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/VisualizationController.java
backport https://github.com/dhis2/dhis2-core/pull/14949
> fix: VisualizationController getEntityList not show nested filters [DHIS2-15322] 2.39

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/metadata/metadata_with_visualization.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/VisualizationController.java
backport https://github.com/dhis2/dhis2-core/pull/14949
> fix: VisualizationController getEntityList not show nested filters [DHIS2-15322] 2.38

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/hibernate/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/hibernate/EventReport.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventvisualization/hibernate/EventVisualization.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_27__Add_skip_rounding_to_eventvisualization.sql
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
**_[Backport from master/2.41]_** #14941
Adds a new boolean flag into `EventVisualization`.
As this flag is shared with `Visualization` I decided to move this flag up in the hierarchy.
> feat: Add skipRounding flag into EV [DHIS2-15689]

- dhis-2/dhis-support/dhis-support-test/pom.xml
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/CsvUtils.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/utils/CsvUtilsTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DimensionControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java
> fix: Fix Dimensions CSV endpoint [DHIS2-15706]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
[DHIS2-15295](https://dhis2.atlassian.net/browse/DHIS2-15295)
[DHIS2-15295]: https://dhis2.atlassian.net/browse/DHIS2-15295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.40) null pointer exception while deleting image attribute[DHIS2-15295]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
[DHIS2-15295](https://dhis2.atlassian.net/browse/DHIS2-15295)
[DHIS2-15295]: https://dhis2.atlassian.net/browse/DHIS2-15295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.39) null pointer exception while deleting image attribute

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
[DHIS2-15425](https://dhis2.atlassian.net/browse/DHIS2-15425)
[DHIS2-15425]: https://dhis2.atlassian.net/browse/DHIS2-15425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: notification to parent orgUnit [DHIS2-15425]

- dhis-2/dhis-web-embedded-jetty/src/main/resources/login.html
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/about/menu.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/enrolTwoFa.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/expired.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/recovery.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/restore.vm
(cherry picked from commit dba5169a96972a20160cf257b5acbab8c5263c9e)
> fix: change links to dhis2.org using http to https (#13778)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppStorageService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/LocalAppStorageService.java
- dhis-2/dhis-web-embedded-jetty/pom.xml
backport #14977 
includes removal of unused declared dependency in embedded jetty module as this was failing the mvn build
> fix: remove previous version of an app when installing [DHIS2-15766]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreSuperuserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DatastoreController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserDatastoreController.java
- dhis-2/dhis-web-embedded-jetty/pom.xml
> fix: Update PUT in data stores to allow create or update [DHIS2-15746]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventXmlImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationSingleEventServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
Backport of: https://github.com/dhis2/dhis2-core/pull/15038
> fix: Use search scope in /events requests [TECH-1630] [2.39]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/aggregate/EnrollmentsAggregate3AutoTest.java
Pagination should not be considered in aggregated requests.
> fix: New Analytics/Enrollment API EntryPoint[2.41-DHIS2-15291_4]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
please see https://dhis2.atlassian.net/browse/DHIS2-12495
> fix: Tracker program table isn't generated[2.41-DHIS2-12495]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
please see https://dhis2.atlassian.net/browse/DHIS2-12495
> fix: Tracker program table isn't generated[2.38-DHIS2-12495-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
please see https://dhis2.atlassian.net/browse/DHIS2-12495
> fix: Tracker program table isn't generated[2.39-DHIS2-12495-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
please see https://dhis2.atlassian.net/browse/DHIS2-12495
> fix: Tracker program table isn't generated[2.40-DHIS2-12495-backport]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
backport https://github.com/dhis2/dhis2-core/pull/15094
> fix: use default Locale.ENGLISH for PdfUtils [DHIS2-13013-40]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
backport https://github.com/dhis2/dhis2-core/pull/15094
> fix: use default Locale.ENGLISH for PdfUtils [DHIS2-13013-39]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
backport https://github.com/dhis2/dhis2-core/pull/15094
> fix: use default Locale.ENGLISH for PdfUtils [DHIS2-13013-38]

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/useraccount/action/IsInviteTokenValidAction.java
Makes sure first name, surname and phone number is populated in the invite form.
Before this, the properties where not copied into the invite form from the invite registration.
The employee field is also removed form the invite form, since it does does not exist in the regular registration form.
Jira: [DHIS2-13408](https://dhis2.atlassian.net/browse/DHIS2-13408)
[DHIS2-13408]: https://dhis2.atlassian.net/browse/DHIS2-13408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Pre-fill user-invite fields and align form fields with user-app

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/IdObjectDeletionHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataelement/DataElementStoreTest.java
backport https://github.com/dhis2/dhis2-core/pull/14997
> fix: refactor query for checking references when deleting User [DHIS2-14144-40]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/MetadataHandler.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
please see https://dhis2.atlassian.net/browse/DHIS2-15791
> fix: /analytics API doesn't return the hierarchy for OUs that don't have data[2.41-DHIS2-15791]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueStatus.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/AnalyticsApiTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/EnrollmentQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/query/EventQueryTest.java
please see https://dhis2.atlassian.net/browse/DHIS2-14420
> feat: Return reserved value for non-existent event repetitions 2.40-DHIS2-15171-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueStatus.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
please see https://dhis2.atlassian.net/browse/DHIS2-14420
> feat: Return reserved value for non-existent event repetitions 2.39-DHIS2-15171-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueStatus.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
please see https://dhis2.atlassian.net/browse/DHIS2-14420
> feat: Return reserved value for non-existent event repetitions 2.38-DHIS2-15171-backport]

- .github/workflows/run-tests.yml
This reverts commit aca9e7c6557f8878e07ddf3bd468a8bf8bd728d7.
> Revert "chore(deps): bump codecov/codecov-action from 3 to 4 (#15153)"

- .github/workflows/run-tests.yml
This reverts commit 805e72d111976efa2f734a7190c030713fa90544.
> Revert "chore(deps): bump codecov/codecov-action from 3 to 4 (#15156)"

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/MetadataHandler.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
please see https://dhis2.atlassian.net/browse/DHIS2-15791
> fix: analytics API doesn't return the hierarchy for OUs that don't have data [2.40-DHIS2-17291-backport]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramStageInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/mapper/EventRowCallbackHandler.java
backport [DHIS2-14836](https://dhis2.atlassian.net/browse/DHIS2-14836)
[DHIS2-14836]: https://dhis2.atlassian.net/browse/DHIS2-14836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (2.38) fix: add timestamp to Event's executionDate, created, lastUpdated and completedDate

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/15302
> fix: TrackedEntity Get Ids : Missing group by enrolledat field [DHIS2-15658 2.38] 

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SvgUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/SvgUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SvgConversionController.java
please see https://dhis2.atlassian.net/browse/DHIS2-15372
> fix: Month names are not same as the report in the PDF [2.41-DHIS2-15372]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CodeGenerator.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OpenApi.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OpenApiControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Api.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiAnalyse.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiFinalise.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Descriptions.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/JsonGenerator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiTool.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/openapi/PropertyTest.java
Intent is the backport of #15291. 
This is a full backport of all OpenAPI related foundation files by copying the file from `master` and replacing any use of Java 17 with the Java 11 equivalent.
> feat: OpenAPI default value for parameters (and full backport) [DHIS2-15893] (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalStatus.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
(cherry picked from commit a41cdd1a6b987b267ee5942f56eab264a1e68138)
> fix: approvedOrgUnitId int -> long [TECH-1653] (#15266)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalPermissions.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataApprovalController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataApprovalControllerTest.java
* fix: dataApprovals/catOptionCombos [DHIS2-15837]
* fix formatting
* fix: code smell
(cherry picked from commit 5fd6d76e5b19af1ca3fcdac7fa0b07246efd67ed)
[DHIS2-15837]: https://dhis2.atlassian.net/browse/DHIS2-15837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: dataApprovals/catOptionCombos [DHIS2-15837] (#15267)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTrackedEntityAttributeDimensionItem.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
please see https://dhis2.atlassian.net/browse/DHIS2-13173
> fix: Param displayProperty:SHORTNAME doesn't return short name [2.38-DHIS2-13173-backport]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/attribute/DefaultAttributeValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/MetadataAttributeCheckTest.java
backport https://github.com/dhis2/dhis2-core/pull/15262
> fix: attributeValue validator should ingore empty string [DHIS2-15860-39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/attribute/DefaultAttributeValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/MetadataAttributeCheckTest.java
backport https://github.com/dhis2/dhis2-core/pull/15262
> fix: attributeValue validator should ingore empty string [DHIS2-15860-40]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SvgUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/SvgUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SvgConversionController.java
please see https://dhis2.atlassian.net/browse/DHIS2-15372
> fix: Month names are not same as the report in the PDF [2.40-DHIS2-15372-backport]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/FullUserMapper.java
[DHIS2-15724](https://dhis2.atlassian.net/browse/DHIS2-15724)
[DHIS2-15724]: https://dhis2.atlassian.net/browse/DHIS2-15724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Enrolment notification in new capture app[DHIS2-15724]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_update_datavalue_empty_value.json
- dhis-2/pom.xml
New version of rule engine is correctly assign null values.
A test was added to verify the correct behavior
> fix: Upgrade to correct rule-engine version [DHIS2-15261]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
Backport 
[DHIS2-15425](https://dhis2.atlassian.net/browse/DHIS2-15425)
[DHIS2-15425]: https://dhis2.atlassian.net/browse/DHIS2-15425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.40) notification to parent orgUnit (#14936)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
Backport
[DHIS2-15425](https://dhis2.atlassian.net/browse/DHIS2-15425)
[DHIS2-15425]: https://dhis2.atlassian.net/browse/DHIS2-15425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.39) notification to parent orgUnit (#14936)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
[DHIS2-15425](https://dhis2.atlassian.net/browse/DHIS2-15425)
[DHIS2-15425]: https://dhis2.atlassian.net/browse/DHIS2-15425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.38) notification to parent orgUnit (#14936)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/MapViewDeletionHandler.java
please see https://dhis2.atlassian.net/browse/DHIS2-15845
> fix: Add error handling for Calculation in Maps[2.41-DHIS2-15845]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_update_datavalue_empty_value.json
- dhis-2/pom.xml
Backport of https://github.com/dhis2/dhis2-core/pull/15347
> fix: Upgrade to correct rule-engine version [DHIS2-15261] (#15347)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/Constants.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/setup/tracker_metadata.json
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/teiWithEnrollmentAndEventsNested.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
see https://github.com/dhis2/dhis2-core/pull/15355
> fix: program stage field in event query select duplicate [DHIS2-15899] - 2.39

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_no_options.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_one_default_category.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_one_default_category_option.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_same_category_options.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_shared_category_options_in_combo.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/category_option_groups_excess_members.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/category_option_groups_sets_incomplete.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/category_options_no_categories.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/CategoryOptionOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/Category.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/CategoryOption.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/SpringDataValueSetStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/importer/context/AttributeOptionComboLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/trackedentity/store/DefaultEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/trackedentity/store/query/EventQuery.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/importer/context/AttributeOptionComboLoaderTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQuery.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/DefaultEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/query/EventQuery.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_30__Rename_DataElementCategoryOption_to_CategoryOption.sql
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Remove prefix dataelement from: 
- table names dataelementcategoryoption and dataelementcategory
- all sql statements
> refactor: Rename table dataelementcategoryoption to categoryoption [TECH-1636]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/Constants.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/setup/tracker_metadata.json
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/teiWithEnrollmentAndEventsNested.json
see https://github.com/dhis2/dhis2-core/pull/15355
> fix: program stage field in event query select duplicate [DHIS2-15899] - 2.38

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/15449
> fix: Allow search capture scope without org unit [TECH-1635]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/webmessage/WebMessageUtils.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/AnalyticsApiTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/NoAnalyticsTablesErrorsScenariosTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/EnrollmentQueryTest.java
- dhis-2/dhis-test-e2e/src/test/resources/junit-platform.properties
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventAnalyticsControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CrudControllerAdvice.java
**_Backport from [master/2.41]_**
(#15435)
> fix: Corner cases for missing analyt. tables [DHIS2-15184]

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/DefaultResourceTableService.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/resourcetable/DefaultResourceTableServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/analytics/AnalyticsExportSettings.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/PeriodDataProvider.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/period/PeriodDataProviderTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
Backport from [master/24.1] (#15483)
> fix: Make period gen. backward compat. [DHIS2-15573]

- jenkinsfiles/dev
Deploy all development branches on IM
> im-play/dev

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/15481
> ci: im-play/dev [2.40]

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/15481
> ci: im-play/dev [2.39]

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/15481
> ci: im-play/dev [2.38]

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/15481
> ci: im-play/dev [2.37]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/IntegrationTestConfig.java
- dhis-2/dhis-test-e2e/docker-compose.yml
see https://github.com/dhis2/dhis2-core/pull/15388
> chore: add C collation to postgres e2e and testcontainer [2.39]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/IntegrationTestConfig.java
- dhis-2/dhis-test-e2e/docker-compose.yml
see https://github.com/dhis2/dhis2-core/pull/15388
> chore: add C collation to postgres e2e and testcontainer [2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
back port of https://github.com/dhis2/dhis2-core/pull/15518
> fix: Show capture scope enrollments when mode capture [TECH-1635] [2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
back port of https://github.com/dhis2/dhis2-core/pull/15518
> fix: Show capture scope enrollments when mode capture [TECH-1635] [2.38]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/statementbuilder/AbstractStatementBuilder.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
* fix: event analytics multi-stage DEs [DHIS2-15873]
* fix more tests
* formatting
* fix: Failing tests [DHIS2-15873]
* fix: Code formatting
---------
Co-authored-by: maikelarabori <maikelarabori@gmail.com>
(cherry picked from commit c3e8ff7d2f81afecabaecb8cda92343936eef071)
[DHIS2-15873]: https://dhis2.atlassian.net/browse/DHIS2-15873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-15873]: https://dhis2.atlassian.net/browse/DHIS2-15873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: event analytics multi-stage DEs [DHIS2-15873] (#15527)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/ContinuousMetadataImportTest.java
> test: adds e2e test for continuous job execution [DHIS2-16004]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/ImportEventsTask.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/importer/events/EventsTests.java
- dhis-2/dhis-test-e2e/src/test/resources/setup/metadata.json
- dhis-2/dhis-test-e2e/src/test/resources/setup/tracker_metadata.json
- dhis-2/dhis-test-e2e/src/test/resources/tracker/events/event-with-de-optionset.csv
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
> fix: Async CSV Event import [DHIS2-12345]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/15558
> fix: Ignore order in category options test [DHIS2-16094] [2.39]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
Disable a flaky test related to EventVisualiztionController until we can find a better fix for it.
> test: Disable flaky test

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
backport of https://github.com/dhis2/dhis2-core/pull/15549
> fix: Return search scope and capture scope for events [TECH-1663] [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
backport of https://github.com/dhis2/dhis2-core/pull/15549
> fix: Return search scope and capture scope for events [TECH-1663] [2.39]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/15521
> ci:deploy nightly and stable builds on im-play (#15521)

- jenkinsfiles/canary
https://github.com/dhis2/dhis2-core/pull/15588
> ci: s/replaceAll/replace/

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/AggregationType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcSubexpressionQueryGenerator.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
* fix: subExpression bool aggregation [DHIS2-15936]
* fix formatting, Satisfy SonarCloud with EnumSet
* fix formatting
* fix AnalyticsServiceTest
* fix formatting
---------
Co-authored-by: Giuseppe Nespolino <gnespolino@users.noreply.github.com>
(cherry picked from commit 0f6b148f787df61d1890572c35a1ddde6d7fa02a)
[DHIS2-15936]: https://dhis2.atlassian.net/browse/DHIS2-15936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: subExpression bool aggregation [DHIS2-15936] (#15340)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/AggregationType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalItemObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/subexpression/SubexpressionDimensionItem.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/subexpression/SubexpressionDimenstionItemTest.java
- dhis-2/dhis-services/dhis-service-analytics/pom.xml
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcSubexpressionQueryGenerator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/SubexpressionPeriodOffsetUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/JdbcSubexpressionQueryGeneratorTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/SubexpressionPeriodOffsetUtilsTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimItemDataElementAndOperand.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramExpressionItem.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ExpressionItem.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ExpressionItemWithSql.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ParserUtils.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/PeriodOffset.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/analytics/csv/dataValues.csv
* feat: periodOffset in subExpression [DHIS2-15874]
* various small fixes
* formatting
* formatting
* formatting
* Incorporate review comments
(cherry picked from commit 61e7dbd7cfc1151ffb9bdbf3bfe31da84468548b)
[DHIS2-15874]: https://dhis2.atlassian.net/browse/DHIS2-15874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: periodOffset in subExpression [DHIS2-15874] (#15403)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/ImportEventsTask.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/importer/events/EventsTests.java
- dhis-2/dhis-test-e2e/src/test/resources/setup/metadata.json
- dhis-2/dhis-test-e2e/src/test/resources/setup/tracker_metadata.json
- dhis-2/dhis-test-e2e/src/test/resources/tracker/events/event-with-de-optionset.csv
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
back port of #15547 
- requested to back port to this patch branch for proposed patch release
- patch/2.38.5 is currently frozen
- Platform team decided this fix was important enough to go into 2.38.5 rather that the intended 2.38.6
> fix: Async CSV Event import fix [DHIS2-12345]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/CompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/tasks/ImportCompleteDataSetRegistrationsTask.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CompleteDataSetRegistrationController.java
Manual backport of #15618
Copied the `master` branch files for the service (interface +  implementation), adjusted the task calling. This then also required to change the controller to pass on dependencies to the task.
> fix: always flush the batch handler for CompleteDataSet import [DHIS2-15362] (2.39)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/security/EnrollmentSecurityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/15583
> fix: Skip validations if user is superuser [TECH-1589][2.40]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/15607
> backport: ci:update image tag

- jenkinsfiles/canary
https://github.com/dhis2/dhis2-core/pull/15624
> backport: ci:remove javadoc and move IM stage to the end

- jenkinsfiles/canary
https://github.com/dhis2/dhis2-core/pull/15624
> ci:remove javadoc and move IM stage to the end (#15624)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/TrackerNtiApiTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/setup/tracker_metadata.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
see https://github.com/dhis2/dhis2-core/pull/15657
> fix: tracker/events not returning event relationships [DHIS2-16117] [ 2.38 ] 

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/TrackerNtiApiTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/setup/tracker_metadata.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
see https://github.com/dhis2/dhis2-core/pull/15657
> fix: tracker/events not returning event relationships [DHIS2-16117] [ 2.39 ]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/JsonPotentialDuplicate.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationController.java
see https://github.com/dhis2/dhis2-core/pull/15660
> fix: Cannot retrieve IDs for Potential Duplicate Records [DHIS2-16063] [2.40]

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/datasource/DatabasePoolUtils.java
* fix: Close database connection after test statement.
> fix: Close database connection after test statement. (#15640) [2.39]

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/datasource/DatabasePoolUtils.java
* fix: Close database connection after test statement.
> fix: Close database connection after test statement. (#15640) [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
Backport of: https://github.com/dhis2/dhis2-core/pull/13768
JIRA: https://dhis2.atlassian.net/browse/DHIS2-11968
> fix: Validate user uid when creating new users

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Backport of: https://github.com/dhis2/dhis2-core/pull/13631
Jira: https://dhis2.atlassian.net/browse/DHIS2-13447
> chore: enforce username format rules in additional places

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/CompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/tasks/ImportCompleteDataSetRegistrationsTask.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CompleteDataSetRegistrationController.java
Cherry-picked from 2.39 (#15625)
> fix: always flush the batch handler for CompleteDataSet import [DHIS2-15362] (2.40)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/jdbc/batchhandler/CompleteDataSetRegistrationBatchHandlerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/jdbc/batchhandler/DataValueAuditBatchHandlerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/jdbc/batchhandler/DataValueBatchHandlerTest.java
- dhis-2/pom.xml
* Use try-with-resources to close BatchHandler
* Rework test to deal with multi-threading
* Add try-catch to Analytics table manager
> Fix: Backport try-with-resources for BatchHanlder to v40

- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHookTest.java
Applying https://github.com/dhis2/dhis2-core/pull/12786 fixes in 2.38 branch
> fix: Fix local failing test

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/datasource/DatabasePoolUtils.java
https://github.com/dhis2/dhis2-core/pull/15640
> backport: fix: Close database connection after test statement.

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplateService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationTemplateService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/HibernateDataSetNotificationTemplateStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplateStoreTest.java
backport https://github.com/dhis2/dhis2-core/pull/15752
> fix: getScheduledNotifications() should take in DataSetNotificationTrigger

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/AbstractDataIntegrityIntegrationTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityChecksControllerTest.java
> fix: only restrict set of checks when executing them [DHIS2-16256] (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/15850
> fix: Skip tmp tables check for closed programs [TECH-1671] [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/15850
> fix: Skip tmp tables check for closed programs [TECH-1671] [2.38]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of: https://github.com/dhis2/dhis2-core/pull/15850
> fix: Skip tmp tables check for closed programs [TECH-1671] [2.40]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/systemsettings/SystemSettingsTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
> fix: System settings endpoint returns expected Cache-Control header [DHIS2-15196]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/HibernateDatastoreStore.java
Extract methods for the different cases when updating a datastore entry.
> chore: datastore entry update SQL cleanup [DHIS2-16224]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataValueSetControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/15892
> fix: exception is not propagated in getDataValueSet [DHIS2-12540] (40)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataValueSetControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/15892
> fix: exception is not propagated in getDataValueSet() [DHIS2-12540](39)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataValueSetControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/15892
> fix: exception is not propagated in getDataValueSet() [DHIS2-12540](38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/metadata/export/MetadataExportWithDependenciesTest.java
https://dhis2.atlassian.net/browse/DHIS2-13663
- Add function to export ProgramSection when exporting Program with dependencies.
> fix: include ProgramSection in getMetadataWithDependencies

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/aggregate/DataImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
> fix: Unchanged imported data values show as ignored in summary [DHIS2-15254]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/JdbcEventStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/EventRequestToSearchParamsMapperTest.java
This continues from https://github.com/dhis2/dhis2-core/pull/15776
Fixing remaining date filters that were not considering time
> fix: Do not consider the day after for date comparisons [DHIS2-10613]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
cherry-picked from #15913 (2.39)
> fix: job configurations keep enabled state for update [DHIS2-12017] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/jsonpatch/JsonPatchManager.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/RemoveOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/jackson/RemoveOperationTest.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/jackson/ReplaceOperationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/jsonpatch/JsonPatchManagerTest.java
https://github.com/dhis2/dhis2-core/pull/15904
> fix: json patch throw error when remove null property [DHIS2-16299] (40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/jsonpatch/JsonPatchManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/jsonpatch/JsonPatchManagerTest.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/jackson/RemoveOperationTest.java
https://github.com/dhis2/dhis2-core/pull/15904
> fix: json patch throw error when remove null property [DHIS2-16299] (38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/metadata/export/MetadataExportWithDependenciesTest.java
backport https://github.com/dhis2/dhis2-core/pull/15903
> fix: include ProgramSection in getMetadataWithDependencies (#15903)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/11423
> fix: missing optionGroup when export program with dependencies [DHIS2-6183](38)

- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/EventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
see https://github.com/dhis2/dhis2-core/pull/15793
> fix: Investigate simultaneous updates of data values is not updating at all [ DHIS2-16080 ] [ 2.38 ]

- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/EventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
see https://github.com/dhis2/dhis2-core/pull/15793
> fix: Investigate simultaneous updates of data values is not updating at all [ DHIS2-16080 ] [ 2.39 ] 

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceImportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
cherry-pick backport of #15942
> fix: data value import with completion - use today for any future date [DHIS2-16290] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceImportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
> fix: data value import with completion - use today for any future date [DHIS2-16290] (2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
> fix: data value import with completion - use today for any future date [DHIS2-16290] (2.38)

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/collection/ListUtils.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/collection/ListUtilsTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AuthoritiesControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthoritiesController.java
https://dhis2.atlassian.net/browse/DHIS2-10843
> fix: sort authorities list case insensitive [DHIS2-10843]

- .github/workflows/run-api-analytics-tests.yml
- .github/workflows/run-api-tests.yml
- .github/workflows/run-tests.yml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/aggregate/DataImportTest.java
> fix: Ensure task summary available on empty file import [DHIS2-7881]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
Adding tests to validate ordering in `/tracker/enrollments`
Ticket: https://dhis2.atlassian.net/browse/TECH-1651
> fix: Add test to validate enrollments order by attributes [TECH-1651] [2.40]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/15989
> fix: Add test to validate enrollments order by attributes [TECH-1651] [2.39]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/15989
> fix: Add test to validate enrollments order by attributes [TECH-1651] [2.38]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/MapViewDeletionHandler.java
[Backport from master/2.41] (#15377)
> fix: Add error handling for Calculation in Maps [DHIS2-15845]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsConfigurationManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/DefaultGatewayAdministrationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/DefaultSmsConfigurationManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/config/GatewayAdministrationServiceTest.java
[DHIS2-13001](https://dhis2.atlassian.net/browse/DHIS2-13001)
[DHIS2-13001]: https://dhis2.atlassian.net/browse/DHIS2-13001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add more than one gateway for same type[DHIS2-13001]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ConfigurationController.java
> feat: adds corsAllowlist alias [DHIS2-16388]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/calendar/DefaultCalendarService.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
> fix: do not open a transation to read settings (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/calendar/DefaultCalendarService.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
cherry-pick backport of #16060
> fix: do not open a transation to read settings (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/calendar/DefaultCalendarService.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
cherry-pick backport of #16060
> fix: do not open a transation to read settings (2.37)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
some time back we moved all order and pagination related tests into this test class. The tests I moved were added in https://github.com/dhis2/dhis2-core/pull/15384
> test: move relationship order tests into OrderAndPaginationExporterTest DHIS2-15666

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/reservedvalue/hibernate/ReservedValue.hbm.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStoreTest.java
During https://github.com/dhis2/dhis2-core/pull/14626, some issues with transactionality in testing have been found for the Reserved Values. Also, some cleanup is done based on previous comments.
> clean : Reserved values clean up [ 2.40 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingAndSortingCriteriaAdapter.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationship.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/StringToOrderCriteriaListConverter.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidatorTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16097
> fix: /tracker/relationships?order=createdAt TECH-1652 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingAndSortingCriteriaAdapter.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonRelationship.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/StringToOrderCriteriaListConverter.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidatorTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16097
> fix: /tracker/relationships?order=createdAt TECH-1652 [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/csv/DefaultCsvEventService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventExportTestConfiguration.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerByIdTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/CompressionUtil.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvTrackedEntityService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/CompressionUtilTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvEventServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvTrackedEntityServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/15994
> task: Support the zip/gzip format in tracker exporter endpoints [ DHIS2-16165 ]  [ 2.40 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/csv/DefaultCsvEventService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventExportTestConfiguration.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerByIdTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/CompressionUtil.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/CompressionUtilTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvEventServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/15994
2.39 backward, there is no such support for tracked entities
> task: Support the zip/gzip format in tracker exporter endpoints [ DHIS2-16165 ] [ 2.39 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/csv/DefaultCsvEventService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventExportTestConfiguration.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerByIdTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/CompressionUtil.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/CompressionUtilTest.java
see https://github.com/dhis2/dhis2-core/pull/15994
2.39 backward, there is no such support for tracked entities
> task: Support the zip/gzip format in tracker exporter endpoints [ DHIS2-16165 ] [ 2.38 ] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/AuditType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceAuditStore.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_28__Fix_Audit_Type_Case_Sensitive.sql.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceAuditStoreTest.java
see https://github.com/dhis2/dhis2-core/pull/14632
> fix: AuditType failing enum conversion when get tracked entity audits [DHIS2-15805] [ 2.40 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/AuditType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceAuditStoreTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_52__Fix_Audit_Type_Case_Sensitive.sql.sql
see https://github.com/dhis2/dhis2-core/pull/14632
> fix: AuditType failing enum conversion when get tracked entity audits [DHIS2-15805] [ 2.38 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/calendar/DefaultCalendarService.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
cherry-pick from #16060 / #16061
> fix: do not open a transation to read settings (2.40.2.1)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/calendar/DefaultCalendarService.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
cherry-pick backport of #16060 / #16062
> fix: do not open a transation to read settings (2.39.4.1)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/calendar/DefaultCalendarService.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
cherry-pick backport of #16060 / #16063
> fix: do not open a transation to read settings (2.38.5.1)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/EmailMessageSender.java
backport https://github.com/dhis2/dhis2-core/pull/14166
> fix: utf-8 encoding in email sender (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/EmailMessageSender.java
backport https://github.com/dhis2/dhis2-core/pull/14166
> fix: utf-8 encoding in email sender (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/EmailMessageSender.java
backport https://github.com/dhis2/dhis2-core/pull/14166
> fix: utf-8 encoding in email sender (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/mapper/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/16113
> fix: validation of /tracker/trackedEntities?order TECH-1648 [2.38]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/csv/CsvEventDataValue.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/csv/DefaultCsvEventService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/csv/CsvEventDataValue.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvEventServiceTest.java
- dhis-2/dhis-web-api/src/test/resources/controller/tracker/csv/event.csv
Backport of https://github.com/dhis2/dhis2-core/pull/15641
> fix: Include AOC during event csv export [DHIS2-16107] (#15641)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreFieldsControllerTest.java
> fix: do not remove pager wrapper without paging [DHIS2-16422] (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreFieldsControllerTest.java
> fix: do not remove pager wrapper without paging [DHIS2-16422] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreFieldsControllerTest.java
> fix: do not remove pager wrapper without paging [DHIS2-16422] (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/VisualizationType.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
Simply add a new type (`OUTLIER_TABLE`) into `Visualization`.
The new type is being added as part of the `VisualizationType` Enum, where all other types live.
> feat: Add new type into Visualization [DHIS2-16461]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16165
> fix: Remove disabled test [DHIS2-16464] [2.39]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramInstanceServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16165
> fix: Remove disabled test [DHIS2-16464] [2.38]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/validation/EventBaseCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/shared/validation/EventBaseCheckTest.java
see https://github.com/dhis2/dhis2-core/pull/16177
> fix: Event import using CSV cannot have empty "Due Date"Column [DHIS2-12352] [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/validation/EventBaseCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/shared/validation/EventBaseCheckTest.java
see https://github.com/dhis2/dhis2-core/pull/16177
> fix: Event import using CSV cannot have empty "Due Date"Column [DHIS2-12352] [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/validation/EventBaseCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/shared/validation/EventBaseCheckTest.java
see https://github.com/dhis2/dhis2-core/pull/16177
> fix: Event import using CSV cannot have empty "Due Date"Column [DHIS2-12352] [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
* chore: enforce username format rules in additional places
> chore: enforce username format rules in additional places (#15703)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/expired.vm
Backport of: [16186](https://github.com/dhis2/dhis2-core/pull/16186)
> fix: Password expired form not working 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/apikey/ApiTokenServiceImpl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/apikey/HibernateApiTokenStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/ApiTokenDeletionHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/apikey/ApiTokenServiceImplTest.java
Backport of: [13854](https://github.com/dhis2/dhis2-core/pull/13854)
> fix: Remove PAT tokens when user is deleted

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/EmailMessageSender.java
backport missing codes from https://github.com/dhis2/dhis2-core/pull/14166
> fix: utf-8 encoding in email sender (2.38.6)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/DefaultOrganisationUnitService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
> fix: prevent a user change access to a higher organisation unit

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
backport, please see https://dhis2.atlassian.net/browse/DHIS2-15278
> fix: Program Indicators returned with too many decimal places

- .github/dependabot.yml
we will have to put in more work in https://dhis2.atlassian.net/browse/DHIS2-16504
> ci: ignore major slf4j update

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
This is an attempt to fix the issue based on symptom observations and reasoning what might be the root cause. 
It has not be tested in any way so far.
> fix: exclude leader election from remote sync [DHIS2-16497]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/CommonParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/MetadataParamsHandler.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
This PR aims to add full dimension UID in metaData items
It will also add labels into metadata for enrollmentdate, incidentdate and executiondate, using their full dimension identifier (prefixed) as metaData item key.
> feat: added full dimension key to meta [DHIS2-16379]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
This adds missing tests to validate the events sorting feature works as expected.
Ticket: https://dhis2.atlassian.net/browse/TECH-1650
> fix: Add tests to validate events sorting feature [TECH-1650]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/expired.vm
Backport: https://github.com/dhis2/dhis2-core/pull/16186
> fix: Password expired form not working  (#16190)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/16216
> fix: Add tests to validate events sorting feature [TECH-1650] [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreNamespaceProtection.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/AndroidSettingsApp.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DefaultDatastoreService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DefaultMetadataDatastoreService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/HibernateDatastoreStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/orgunitprofile/impl/DefaultOrgUnitProfileService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/KeyJsonValueSchemaDescriptor.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datastore/DatastoreEntriesTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datastore/DatastoreKeysTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastore/DatastoreIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastore/DatastoreSharingTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreControllerTest.java
backport of datastore sharing feature, includes PRs:
- #15754
- #15777
- #15595
- #16230
> feat: Datastore sharing backport [DHIS2-16530]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/LoginConfigResponse.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/LoginConfigControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/LoginControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/LoginConfigController.java
Add a system config variable called "loginPopup" for storing HTML that will be used inside a pop-up on the login page if present.
Jira: https://dhis2.atlassian.net/browse/DHIS2-16267
> feat: Add system setting to allow pop-up message on login page

- dhis-2/dhis-services/dhis-service-field-filtering/pom.xml
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldPathHelperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/fieldfiltering/FieldPathHelperTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
> fix: Exporting users should include expected fields when skipSharing [DHIS2-16512]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
Backport: https://github.com/dhis2/dhis2-core/pull/16311
> fix: Pre-fill user-invite fields and align form fields with user-app form

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
Reverts changes in the `RedisLeaderManager` that happened since the last version that did not have the reported problem.
> fix: revert leader manager changes [DHIS2-16497]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/EmbeddedObjectObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/EmbeddedObjectBundleHookTest.java
> fix: import event viz with null embedded collection [DHIS2-16501]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
Co-authored-by: Giuseppe Nespolino <gnespolino@users.noreply.github.com>
(cherry picked from commit 343233d318829d133c002757fdcb52ab2ace58e1)
> fix: nested indicator w/periodOffset [DHIS2-15434] (#16342)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/SoftDeleteHibernateObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityInstance.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackedEntityTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EnrollmentImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracked_entity_basic_data_for_deletion.json
see https://github.com/dhis2/dhis2-core/pull/16367
> fix: Ensure lastUpdated field reflects deletion for event and enrollment [ DHIS2-16320] [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/SoftDeleteHibernateObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityInstance.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EnrollmentImportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackedEntityTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracked_entity_basic_data_for_deletion.json
- dhis-2/pom.xml
see https://github.com/dhis2/dhis2-core/pull/16367
> fix: Ensure lastUpdated field reflects deletion for event and enrollment [ DHIS2-16320] [2.38] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/common/CommonQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/AnalyticsDateFilter.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionParamType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/CommonQueryRequestValidator.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/params/dimension/DimensionParamTypeTest.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/helpers/config/Config.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/helpers/extensions/AnalyticsSetupExtension.java
Switched several date param in TEI/CPL analytics to use collection instead of string, to allow multiple params
> fix: request param of type dates can be repeated [DHIS2-16708]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/16351
> fix: skip reference check createdBy when create new object (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/16351
> fix: skip reference check createdBy when create new object (2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/16351
> fix: skip reference check createdBy when create new object (2.38)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/RelationshipControllerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16382
In 2.38, relationships are not soft deletable, therefore we only add MVC tests
> fix: Relationships are not filtered by deleted in tracker/relationships endpoint [2.38] 

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
see https://github.com/dhis2/dhis2-core/pull/16436
> fix: Getting internal server when trying to fetch a deleted enrollment [2.39] 

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
see https://github.com/dhis2/dhis2-core/pull/16436
> fix: Getting internal server when trying to fetch a deleted enrollment [2.38]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/AnalyticsQueryOperator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/query/BinaryConditionRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/query/NullValueAwareConditionRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/query/OrCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/query/RootConditionRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/OrganisationUnitCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/query/OrConditionTest.java
This PR aims at supporting NIEQ operator properly in CPL endpoint.
It also feature a small refactoring on the OrCondition
cheers
> fix: handles NIEQ [DHIS2-16459]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/CommonQueryRequestMapper.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
This PR aims at disabling support for Program Indicators in Cross Program Linelisting API (Tei reports) until properly implemented
> feat: disabled PI in TEI [DHIS2-16732]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/LoginConfigResponse.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/LoginConfigControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/LoginConfigController.java
Adds translation and some new fields to previous PR: #16229
`LoginControllerTest.java`
Jira: [DHIS2-14681](https://dhis2.atlassian.net/browse/DHIS2-14681)
[DHIS2-14681]: https://dhis2.atlassian.net/browse/DHIS2-14681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: public endpoint for retrieving system appearance, part2

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventvisualization/SimpleDimension.java
Just adds missing dimensions to the Enumeration.
> fix: Add missing dim. to enum [DHIS2-14956] (#16450)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstageworkinglist/ProgramStageQueryCriteria.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/programstageworkinglist/JsonDatePeriod.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/programstageworkinglist/JsonProgramStageQueryCriteria.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/programstageworkinglist/JsonWorkingList.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/programstageworkinglist/ProgramStageWorkingListControllerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16463
> fix: FollowUp is not persisted in programStageWorkingListFilters [2.40]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/datasource/DatabasePoolUtils.java
- dhis-2/dhis-support/dhis-support-hibernate/src/test/java/org/hisp/dhis/datasource/DatabasePoolUtilsTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/test/java/org/hisp/dhis/datasource/StubDriver.java
- dhis-2/dhis-support/dhis-support-hibernate/src/test/resources/log4j2-test.xml
See: https://github.com/dhis2/dhis2-docs/pull/1323
> DHIS2-16396: backport #283addb to add support for unpooled DB pool type

- .github/dependabot.yml
- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/pom.xml
backport https://github.com/dhis2/dhis2-core/pull/16495 & https://github.com/dhis2/dhis2-core/pull/16506
> fix: JasperReport failed to export pdf with arabic characters (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/EventManagerTest.java
> fix:(2.40) tracker not able to trigger program rule notifications[DHIS2-12614]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/EventManagerTest.java
> fix:(2.39) tracker not able to trigger program rule notifications[DHIS2-12614]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobConfigurationTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/scheduling/hibernate/JobConfiguration.hbm.xml
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobSchedulerController.java
Continue reverting leader manager changes started in https://github.com/dhis2/dhis2-core/pull/16333
> fix: revert more leader changes [DHIS2-16497]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
A fix to leader manager changes started in https://github.com/dhis2/dhis2-core/pull/16333
> fix: another change fix [DHIS2-16497]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingWrapper.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingWrapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/16545
> fix: page incorrect /api/tracker/{trackedEntities,relationships} DHIS2-16715 [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingWrapper.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingWrapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/16545
> fix: page incorrect /api/tracker/{trackedEntities,relationships} DHIS2-16715 [2.38]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/TeiQueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/TeiSqlQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
This pull request introduces the addition of Organization Unit Group Sets to enhance the TEI Cross Program Linelisting Analytics.
> fix: added org unit group sets to TEI CPL [DHIS2-16749]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionParamItem.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
This PR parses correctly multiple items separated by (;)
> fix: fixed parsing of multiple items in queryItems [DHIS2-16743]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
> fix: updateNoAcl should update lastUpdatedBy [DHIS2-15543]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
The fix is twofold:
* always execute a "in-memory" job independent of leader status (a job submitted to a node for immediate execution that is not persisted)
* only synchronize the "runningRemotely" for job types that should only be run by the leader
> fix: run in memory jobs on any node [DHIS2-16497] (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
> fix: run in memory jobs on any node [DHIS2-16497] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
cherry-pick backport of #16577
> fix: run in memory jobs on any node [DHIS2-16497] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
Make sure user is created with system user, since we don't have a logged-in user during user account creation.
1. Enable account creation.
2. Navigate to the create account page. 
3. Observe, the field's values are not the variable names.
> fix: make sure account creation is done by system user

- .github/dependabot.yml
- dhis-2/pom.xml
backport https://github.com/dhis2/dhis2-core/pull/16495 & https://github.com/dhis2/dhis2-core/pull/16506
> fix: JasperReport failed to export pdf with arabic characters (2.38)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v41/V2_41_46__add_data_sharing_for_aggregate_data_exchange.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/LocaleControllerTest.java
- adding a web test checking the Indonesian locale codes returned
- this will help with fixes required in older versions (dev / v41 has the correct behaviour which this test confirms)
> fix: Add web test for Indonesian locales [DHIS2-13358]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v41/V2_41_46__add_data_sharing_for_aggregate_data_exchange.java
Fix the format error which has been bypassed in https://github.com/dhis2/dhis2-core/pull/16558.
> fix: code format

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/RenderableDataValueIndicator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/DataElementQueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/SqlQueryHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/SqlQueryHelperTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
The TEI implementation of repeatable stages did not handle offsets and sort directions properly. Additionally, the reliability of data origin indication was compromised. As a result, there was inconsistency between the content in analytics and the analytics TEI API.
> fix: Different results in repeatable events[DHIS2-16709]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/16612
> backport: ci: update IM play instance restart command [skip ci]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/Page.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventChangeLog.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventChangeLogStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonEventChangeLog.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerPostgresTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/ChangeLogRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/view/Page.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/view/PageTest.java
* return changelog `type` = `CREATE`, `UPLOAD`, `DELETE`
* validate changelog pagination parameters are >= 1
* use same assertion style in changelog controller tests. Create helpers extending `JsonObject`
> chore: return changelog type DHIS2-16856

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonWebLocale.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/LocaleControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/webdomain/WebLocaleTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/LocaleController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/WebLocale.java
> fix: Handle Indonesian locale codes [DHIS2-13358]

- dhis-2/build-docker-image.sh
- docker/DOCKERHUB.md
- jenkinsfiles/dev
- jenkinsfiles/rebuild-image
- jenkinsfiles/stable
- jib.yaml
Backport of https://github.com/dhis2/dhis2-core/pull/15611
> ci: add script and pipeline for rebuilding images [skip ci] [DEVOPS-294] [2.40]

- dhis-2/build-docker-image.sh
- docker/DOCKERHUB.md
- jenkinsfiles/dev
- jenkinsfiles/rebuild-image
- jenkinsfiles/stable
- jib.yaml
Backport of https://github.com/dhis2/dhis2-core/pull/15611
> ci: add script and pipeline for rebuilding images [skip ci] [DEVOPS-294] [2.39]

- dhis-2/build-docker-image.sh
- docker/DOCKERHUB.md
- jenkinsfiles/dev
- jenkinsfiles/rebuild-image
- jenkinsfiles/stable
- jib.yaml
Backport of https://github.com/dhis2/dhis2-core/pull/15611
> ci: add script and pipeline for rebuilding images [skip ci] [DEVOPS-294] [2.38]

- dhis-2/build-docker-image.sh
- docker/DOCKERHUB.md
- jenkinsfiles/dev
- jenkinsfiles/rebuild-image
- jenkinsfiles/stable
- jib.yaml
Backport of https://github.com/dhis2/dhis2-core/pull/15611
> ci: add script and pipeline for rebuilding images [skip ci] [DEVOPS-294] [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/LoginPageLayout.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/LoginConfigControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/LoginConfigController.java
https://dhis2.atlassian.net/browse/DHIS2-16941
- Adding two news SystemSetting for supporting customization of the new Login Page.
- The System Settings App need to add those two new settings to the UI.
> feat: add login page layout config

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/cache/HibernateCacheBaseTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/cache/HibernateQueryCacheTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16721
> test: cleanup admin user after HibernateQueryCacheTest [2.41]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
Reverts dhis2/dhis2-core#16750
did't resolve the issue
> Revert "Update wait time before generating analytics tables in test"

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/pom.xml
Fixes wrong app link in the invite and password reset emails.
> fix: wrong invite and password reset email link
