- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/scheduling/HtmlPushAnalyticsJob.java
On request of Hendrik we call the PA service in parallel, trying 8 at a time for the time being.
> feat: call push analytics in parallel [DHIS2-16451]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserSettingService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/PdfFormFontSettings.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/PdfFormControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PdfFormController.java
backport https://github.com/dhis2/dhis2-core/pull/16717
> fix: api/pdfForm return error 500 if db_locale is null (40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserSettingService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/PdfFormFontSettings.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/PdfFormControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PdfFormController.java
backport https://github.com/dhis2/dhis2-core/pull/16717
> fix: api/pdfForm return error 500 if db_locale is null (39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UserContext.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserSettingService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/PdfFormFontSettings.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/PdfFormControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PdfFormController.java
backport https://github.com/dhis2/dhis2-core/pull/16717
> fix: api/pdfForm return error 500 if db_locale is null (38)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
Hand-merged from [pull/16788](https://github.com/dhis2/dhis2-core/pull/16788).
> fix: Hand-Cherry-picked from DHIS2-17041

- dhis-2/.gitignore
while trying out Visual Studio, git is not ignoring the configuration files
> fix: ignore visual studio code files

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/icon/DefaultIcon.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/icon/IconStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/icon/DefaultIconService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/HousekeepingJob.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/icon/IconTest.java
Renames only as suggested in #16798
> chore: more clear names for icon key composition [DHIS2-16872]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-embedded-jetty/src/test/java/org/hisp/dhis/auth/AuthTest.java
Includes the query string in the redirect URL.
> fix: include query string in redirect

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
Make requests to `service-worker.js.map` and `service-worker.js` and by doing that avoid the login to redirect to this after login.
> fix: ignore service worker requests

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/oidc/btn_azure_login.svg
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/oidc/btn_google_light_normal_ios.svg
Updates OIDC provider icons to consistent size to be used in new login app.
> fix: update OIDC icons [DHIS2-17079]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/SqlQueryHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/SqlQueryHelperTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/EnrollmentQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery2AutoTest.java
(cherry picked from commit a2c3124dee7decff7e12fb5cf179af9dad0c54e3)
> fix: Order by occurreddate and created[2.42-DHIS-16709] (#16809)

- dhis-2/dhis-web-api/src/main/resources/openapi/EventsExportController.md
backport of https://github.com/dhis2/dhis2-core/pull/16821
> docs: add missing order property to tracker OpenAPI

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/TokenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CrudControllerIntegrationTest.java
backport https://github.com/dhis2/dhis2-core/pull/16844
> fix: fallback to name if translation is null for token search (41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/GridAdaptor.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/TeiListGrid.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/CommonParams.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery1AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
This PR adds support for `skipRounding` parameter in TE analytics endpoint
> fix: skipRounding implemented for TE [DHIS2-17105]

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/oidc/btn_azure_login.svg
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/oidc/btn_google_light_normal_ios.svg
(cherry picked from commit c13316a3281fb21a9da05314b462177aae87afbe)
> fix: update OIDC icons [DHIS2-17079] (#16812)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/GridAdaptor.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/TeiListGrid.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/CommonParams.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery1AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
* fix: skipRounding implemented for TE [DHIS2-17105]
* fix: javadocs [DHIS2-17105]
* fix: .0 when number [DHIS2-17105]
* fix: returns .0 anyway when skipRounding is true [DHIS2-17105]
* fix: e2e [DHIS2-17105]
* fix: e2e [DHIS2-17105]
---------
Co-authored-by: Dusan Bernat <mail@it-bernat.de>
(cherry picked from commit 9bbc1c7b11e5e1c60aedd709942498b8d3837591)
[DHIS2-17105]: https://dhis2.atlassian.net/browse/DHIS2-17105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17105]: https://dhis2.atlassian.net/browse/DHIS2-17105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17105]: https://dhis2.atlassian.net/browse/DHIS2-17105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
> fix: skipRounding implemented for TE [DHIS2-17105] (#16853)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionParam.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery2AutoTest.java
Changes the valueType of some dates, so it's aligned with other analytics endpoints.
> fix: Change the valueType of some dates [DHIS2-17104]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOrgUnitTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManager.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/TextUtils.java
backport https://github.com/dhis2/dhis2-core/pull/16755
> chore: replace string concat with java text blocks [DHIS2-16705] (41)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/ValueTypeMapping.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/query/ConstantValuesRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/RenderableDataValue.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/query/ConstantValuesRendererTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/RenderableDataValueTest.java
(cherry picked from commit 585134a52c013ff422f0b82cdf3d16499f91069d)
> fix: adds proper support for TIME in TE [DHIS2-17140] [2.41](#16932)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
The handling of repeatable stages, data type organization unit coordinate, and organization unit contains a bug. The row context handler is generating invalid SQL statements.
> fix: SQL error in enrollment request when using E2E - Coordinate and E2E - Organisation Unit [2.41-DHIS2-17139-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/ValueTypeMapping.java
This PR changes the way a `ValueType` is mapped into `ValueTypeMapping`, in a way that, instead of having a direct relation, it is inferred based on the Java type.
> fix: refactor ValueTypeMapping so that types are inferred dynamically [DHIS2-17147]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/tracker/imports/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/RelationshipMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/RelationshipTypeMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/RelationshipImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
Backport of https://github.com/dhis2/dhis2-core/pull/16880
> fix: Validate user has access to relationship type [DHIS2-17082] [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TransactionMode.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/DefaultSqlViewService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStoreTest.java
> fix: Use correct JDBC template with read replicas [DHIS2-17062]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerByIdTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerUnitTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerUnitTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/FileResourceRequestHandler.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
backport of https://github.com/dhis2/dhis2-core/pull/16943
> fix: set CSP header with script-src in tracker file/image endpoints [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/resourcetable/ResourceTableService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableGenerator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/DefaultResourceTableService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/DataApprovalMinLevelResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/DefaultResourceTableServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/resourcetable/ResourceTableServiceTest.java
(cherry picked from commit b09dd288a71ecbf5e6ddd36efafd96fcd586c126)
> refactor: Uniform generation of resource tables [DHIS2-16705] [41]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityImportRequestParamsMapperTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/17006
> fix: Validate event parameters together in TE endpoint [DHIS2-16927](2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/17006
> fix: Validate event parameters together in TE endpoint [DHIS2-16927] (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TransactionMode.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/DefaultSqlViewService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStoreTest.java
backport of #16882.
Approval confirmation received from Stian to backport to this branch .
> fix: Use appropriate JDBC template with read replicas [DHIS2-17062]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/ValueTypeMapping.java
> [2.41] fix: refactor ValueTypeMapping so that types are inferred dynamically [DHIS2-17147]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/RelationshipMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/relationship/RelationshipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/relationship/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/relationship/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/RelationshipImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
Backport of https://github.com/dhis2/dhis2-core/pull/16880
> fix: Validate user has access to relationship type [DHIS2-17082][2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/17006
> fix: Validate event parameters together in TE endpoint [DHIS2-16927](2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/tracker/imports/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/RelationshipMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/RelationshipTypeMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/RelationshipImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
Backport of https://github.com/dhis2/dhis2-core/pull/16880
This has been approved by the board.
> fix: Validate user has access to relationship type [DHIS2-17082][patch_2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TransactionMode.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/DefaultSqlViewService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStoreTest.java
> fix: Use appropriate JDBC template for read replica [DHIS-17062]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/ValueTypeMapping.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery2AutoTest.java
CPL does not support the 'dhis' data format 'mmmm-YY-DDT.hh.mm.ss'. The fix improves the parsing of this format.
> fix: Analytics TE query API - error comparing datetime [DHIS2-17182]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/model/AnalyticsTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/model/Table.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManagerTest.java
backport https://github.com/dhis2/dhis2-core/pull/16973
> fix: AbstractJdbcTableManager.swapTable method does not swap object [DHIS2-17194]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobSchedulerLoopService.java
Cherry-pick backport of #17038
> fix: avoid resetting housekeeping job when it is alive (2.41)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/ValueTypeMapping.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
(cherry picked from commit f239dcee06ab63c8a72c1baa013b9d836414bbb2)
> [2.41.0] refactor: ValueTypeMapping so that types are inferred dynamically [DHIS2-17147]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementWithLegendSetCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementWithStaticValuesCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/DataElementConditionTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
> fix: DataValues with legendset are now filtered properly in TE analytics [DHIS2-17145] [2.41.0] 

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/model/AnalyticsTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/model/Table.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManagerTest.java
**[DO NOT MERGE!]
NEEDS APPROVAL FROM RCB.**
backport https://github.com/dhis2/dhis2-core/pull/16973
> fix: AbstractJdbcTableManager.swapTable method doesn't swap object [DHIS2-17194]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/ValueTypeMapping.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery2AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
**NEED RCB APPROVAL**
**Backport**
CPL does not support the 'dhis' data format 'mmmm-YY-DDT.hh.mm.ss'. The fix improves the parsing of this format.
> fix: Analytics TE query API - error comparing datetime [2.41.0-DHIS2-17182-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionIdentifier.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/RenderableDataValue.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/DataElementQueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/DataElementConditionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/RenderableDataValueTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/17105
> fix: Data Values will return the legend label when LegendSet is specified [DHIS2-17145]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/DataElementQueryBuilder.java
backport of https://github.com/dhis2/dhis2-core/pull/17108
> fix: OrgUnits Data Values defaults to idScheme.name [DHIS2-17146]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/pom.xml
Backport of https://github.com/dhis2/dhis2-core/pull/17116
> chore: Upgrade rule-engine version [2.41]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/pom.xml
Backport of https://github.com/dhis2/dhis2-core/pull/17116
> chore: Upgrade rule-engine version [2.41.0]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionIdentifier.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/RenderableDataValue.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/DataElementQueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/DataElementConditionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/RenderableDataValueTest.java
This is a fix to complement the previous change already merged - DHIS2-17145 (merged in PR https://github.com/dhis2/dhis2-core/pull/17028)
> fix: DataValues to return Label when legendSet is passed [DHIS2-17145] [2.41.0]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
see https://github.com/dhis2/dhis2-core/pull/16959
> fix: Tracker - Default Json response to browser only html requests [DHIS2-13014] [2.41]

- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/16959
> fix: Tracker - Default Json response to browser only html requests [DHIS2-13014] [2.38] 

- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/16959
> fix: Tracker - Default Json response to browser only html requests [DHIS2-13014] [2.39] 

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
see https://github.com/dhis2/dhis2-core/pull/16959
> fix: Tracker - Default Json response to browser only html requests [DHIS2-13014] [2.41] [patch]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerByIdTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerUnitTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerUnitTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/FileResourceRequestHandler.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
backport of https://github.com/dhis2/dhis2-core/pull/16943
RCB approved ✅
> fix: set CSP header with script-src in tracker file/image endpoints [2.41.0]

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/jclouds/JCloudsStore.java
- dhis-2/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/17150
> chore: enable jclouds logging DHIS2-17232 [2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
cherry-pick backport of #17140
> fix: resolve objects by ID identifier (UID alias) [DHIS2-17186] (2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
cherry-pick backport of #17140
> fix: resolve objects by ID identifier (UID alias) [DHIS2-17186] (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/HibernateJobConfigurationStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/cache/HibernateQueryCacheTest.java
backport https://github.com/dhis2/dhis2-core/pull/17164
> fix: Hibernate nativeQuery clear all Hibernate caches (41.0)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MapControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
[Backport from master/2.42] (#17199)
> fix: Return ok() in Maps PUT method [DHIS2-15978] (#17199)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MapControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
[Backport from master/2.42] (#17199)
> fix: Return ok() in Maps PUT method [DHIS2-15978]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
Cherry picked from: https://github.com/dhis2/dhis2-core/pull/17224
> fix: only one concurrent user allowed [DHIS2-17225]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
Cherry picked from: https://github.com/dhis2/dhis2-core/pull/17224
> fix: only one concurrent user allowed

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
[Backport from master / 2.42] (#17241)
> fix: Min/max limits in analytics rep. rates [DHIS2-15892]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventProgramsDataSynchronizationJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/SyncUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJobParametersTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/EventSynchronizationTest.java
> fix: Event Sync job throws NPE [DHIS2-17233]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/log4j2-test.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceSupportService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceSupportServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16783
> fix: Validate acl access depending on program param [DHIS2-17070][2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/ProgramStageValidationStrategyTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipMapper.java
see https://github.com/dhis2/dhis2-core/pull/17189
> fix: tracker/relationships emits inaccessible program attributes [ Dhis2-17090 ] [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceSupportService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceSupportServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/16783
> fix: Validate acl access depending on program param [DHIS2-17070][patch_2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJobParametersTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJobTest.java
> fix: Metadata Sync job lastExecutedStatus status [DHIS2-17292]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionParam.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery1AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery2AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery3AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/query/EventQueryTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/query/EventsQuery1AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/query/EventsQuery2AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery2AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
**[Backport from master/2.42]** (#17273)
> fix: Change DATE columns to DATETIME [DHIS2-17299]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/ProgramStageValidationStrategyTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipMapper.java
see https://github.com/dhis2/dhis2-core/pull/17189
> fix: tracker/relationships emits inaccessible program attributes [ Dhis2-17090 ] [patch/2.41]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/postprocess/ProgramNotificationPostProcessor.java
backport [DHIS2-17168](https://dhis2.atlassian.net/browse/DHIS2-17168)
[DHIS2-17168]: https://dhis2.atlassian.net/browse/DHIS2-17168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Send webhook notification at stage completion [DHIS2-17168]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/postprocess/ProgramNotificationPostProcessor.java
Backport[ DHIS2-17168](https://dhis2.atlassian.net/browse/DHIS2-17168)
> fix: Send webhook notification at stage completion [DHIS2-17168] 

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
**[Backport from master/2.42]** (#17273)
> fix: Merge conflicts with 2.39 [DHIS2-17299]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/OperationsParamsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/OperationsParamsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17278
> fix: Validate user TE access [DHIS2-17236][2.41]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
backport of https://github.com/dhis2/dhis2-core/pull/16965
> fix: Tracker event query is slow [2.38]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
backport of https://github.com/dhis2/dhis2-core/pull/16965
> fix: Tracker event query is slow [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
backport of https://github.com/dhis2/dhis2-core/pull/16965
> fix: Tracker event query is slow [2.40]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
see https://github.com/dhis2/dhis2-core/pull/16965
> fix: Tracker event query is slow [patch 2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/17289
> fix: visualizations api returns incorrect  relativePeriods[17303](41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/OperationsParamsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/OperationsParamsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17278
> fix: Validate user TE access [DHIS2-17236][patch/2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/tracker/imports/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/Users.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/enrollments_te_enrollments-data_2.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/enrollments_te_te-data.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/te-transferred-data-delete.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/te-transferred-data-update.json
Backport of https://github.com/dhis2/dhis2-core/pull/17274 and https://github.com/dhis2/dhis2-core/pull/17205
> fix: Fix TE ownership validation in Tracker importer [DHIS2-17251] (2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DefaultCompleteDataSetRegistrationService.java
v40 backport of https://github.com/dhis2/dhis2-core/pull/13680
> fix: completion lastUpdatedBy v40 [TECH-1440]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/relationship/AbstractRelationshipService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/RelationshipServiceTest.java
missing cherry-pick of https://github.com/dhis2/dhis2-core/pull/17189 in https://github.com/dhis2/dhis2-core/pull/17281
> fix: tracker/relationships emits inaccessible program attributes [ Dhis2-17090 ] [patch/2.41] [1]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
backport of https://github.com/dhis2/dhis2-core/pull/16783
> fix: Validate acl access depending on program param [DHIS2-17070][2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/hibernate/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/hibernate/EventReport.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventvisualization/hibernate/EventVisualization.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/report/hibernate/Report.hbm.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/metadata/map_new.json
Applying same fix as in https://github.com/dhis2/dhis2-core/pull/17292 to all analytic objects which have `relativePeriods` property.
> fix: analytic relativePeriods has incorrect values

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
The creation of persistent sessions during HTTP Basic authentication is broken, resulting in clients relying on reuse of the session cookie to fail. Stateless session with HTTP basic auth is the default Spring security behaviour, this is overridden with a special  `addObjectPostProcessor` directive to only apply to the basic auth filter, rather than to the global config, since we don't want this behaviour in the deprecated OAuth2 sessions, which uses bearer tokens.
This PR restores previous behaviour before this regression. During migration away from Struts and the deprecated security config format, the order of the `addObjectPostProcessor` method in the config chain was changed and would silently not be invoked.
Due to the lack of automated tests regarding this feature, it resulted in …
> fix: broken session persistence with basic auth

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/tracker/imports/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/Users.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/enrollments_te_enrollments-data_2.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/enrollments_te_te-data.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/te-transferred-data-delete.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/te-transferred-data-update.json
Backport of https://github.com/dhis2/dhis2-core/pull/17274 and https://github.com/dhis2/dhis2-core/pull/17205
> fix: Fix TE ownership validation in Tracker importer [DHIS2-17251](2.41.0)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/hibernate/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/hibernate/EventReport.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventvisualization/hibernate/EventVisualization.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/report/hibernate/Report.hbm.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/metadata/map_new.json
backport https://github.com/dhis2/dhis2-core/pull/17332
> fix: analytic relativePeriods has incorrect values[BETA-164](41)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java
backport https://github.com/dhis2/dhis2-core/pull/16873
> fix: clear stale jobNotification in redis[DHIS2-17179](41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/Stats.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/orgunits/OrgUnitsRemovalTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/16280
> fix: don't throw DeleteNotAllowException during metadata import[DHIS2-15772] (40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/Stats.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/orgunits/OrgUnitsRemovalTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/16280
> fix: don't throw DeleteNotAllowException during metadata import[DHIS2-15772](39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryLimitTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackedEntityInstanceControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
"backport" of https://github.com/dhis2/dhis2-core/pull/17343#issue-2281622652
> fix: Update validation when no program specified [DHIS2-17236][2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
backport of https://github.com/dhis2/dhis2-core/pull/17370
> fix: Compare TET by UID [DHIS2-17251][2.41]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/action/validation/HideOptionProgramRuleActionValidator.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/ProgramRuleActionValidatorTest.java
backport https://github.com/dhis2/dhis2-core/pull/17306
> fix: validation error when HideOptionProgramRuleAction contain DataElement[BETA-165](41)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/action/validation/HideOptionProgramRuleActionValidator.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/ProgramRuleActionValidatorTest.java
backport https://github.com/dhis2/dhis2-core/pull/17306
> fix: validation error when HideOptionProgramRuleAction contain DataElement[BETA-165](41.0)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/hibernate/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/hibernate/EventReport.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventvisualization/hibernate/EventVisualization.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/report/hibernate/Report.hbm.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/metadata/map_new.json
Applying same fix as in https://github.com/dhis2/dhis2-core/pull/17292 to all analytic objects which have relativePeriods property.
> fix: analytic relativePeriods has incorrect values[BETA-164](41.0)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerByIdTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17370
> fix: Compare TET by UID [DHIS2-17251][2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportControllerByIdTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17370
> fix: Compare TET by UID [DHIS2-17251][2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
backport of https://github.com/dhis2/dhis2-core/pull/17370
> fix: Compare TET by UID [DHIS2-17251][patch/2.41]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17372
> fix: Validate unenrolled TE before importing [DHIS2-17280] [2.41]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/enrollment/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/enrollment/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17372
> fix: Validate unenrolled TE before importing [DHIS2-17280][patch-2.40]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17372
> fix: Validate unenrolled TE before importing [DHIS2-17280] [patch-2.41] 

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/ImpersonateUserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ImpersonateUserController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
Adjusts some tests and minor controller refactoring related to impersonation. Also removes unused URL permissions in the security config.
Original PR: [#17342](https://github.com/dhis2/dhis2-core/pull/17342)
> chore: adjust tests and previous filter endpoint permission

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
* fix: custom format for integer types [DHIS2-15841]
* fix: code style [DHIS2-15841]
(cherry picked from commit 4895702b69f70c265f3ab7127ec483393751f1af)
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: custom format for integer types [DHIS2-15841][2.38] (#17405)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
* fix: custom format for integer types [DHIS2-15841]
* fix: code style [DHIS2-15841]
(cherry picked from commit 4895702b69f70c265f3ab7127ec483393751f1af)
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: custom format for integer types [DHIS2-15841] [2.40](#17405)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
* fix: custom format for integer types [DHIS2-15841]
* fix: code style [DHIS2-15841]
(cherry picked from commit 4895702b69f70c265f3ab7127ec483393751f1af)
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: custom format for integer types [DHIS2-15841] [2.39](#17405)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
* fix: custom format for integer types [DHIS2-15841]
* fix: code style [DHIS2-15841]
(cherry picked from commit 4895702b69f70c265f3ab7127ec483393751f1af)
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-15841]: https://dhis2.atlassian.net/browse/DHIS2-15841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: custom format for integer types [DHIS2-15841] [2.41](#17405)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/ImpersonateUserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ImpersonateUserController.java
Changes the error code when trying to exit a user that is not impersonating.
ImpersonateUserControllerTest#testImpersonateExitNotImpersonating
> chore: change exit error codes

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
* fix: Enrollment dim. restriction SQL [DHIS2-16349]
(cherry picked from commit 232cd91a0006b48c3b518c25b5bd326b7264ac06)
[DHIS2-16349]: https://dhis2.atlassian.net/browse/DHIS2-16349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Enrollment dim. restriction SQL [DHIS2-16349] (#17393)

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParser.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldFilterParserTest.java
cherry-pick backport of #17422
> fix: field filter parsing exist block [DHIS2-17391] (2.41)

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParser.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldFilterParserTest.java
cherry-pick backport of #17422
> fix: field filter parsing exist block [DHIS2-17391] (2.39)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
- dhis-2/pom.xml
- Backport https://github.com/dhis2/dhis2-core/pull/17382
- Changes in dependabot.yml is removed because only the config in master branch is utilized.
> fix: Report App got 500 error due to jasperreport lib upgraded[DHIS2-17378](40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportSummary.java
as we just removed the old tracker endpoints, sync and dxf2 services
> chore: remove old tracker fields in ImportSummary DHIS2-16564

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
The last [ACL fix](https://github.com/dhis2/dhis2-core/pull/17357/files#diff-f960125887353fe285946328173a4e612632e40c0bca283e9d30c824348764dbR560) broke one of the methods used by the metadata sync. This PR contains a fix for it and it introduces a couple of tests to make sure it won't happen again
> fix: Add programs param if no program requested [DHIS2-17410][2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
Forward port of https://github.com/dhis2/dhis2-core/pull/17441
> fix: Add programs param if no program requested [DHIS2-17410][2.40]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
* fix: Enrollment dim. restriction SQL [DHIS2-16349] (#17393)
* fix: Enrollment dim. restriction SQL [DHIS2-16349]
(cherry picked from commit 232cd91a0006b48c3b518c25b5bd326b7264ac06)
* spotless fix
* Replace missing isAttributeCategory method
* fix testEnrollmentWithCategoryDimensionRestriction
(cherry picked from commit 05d6b7be828fb324df2bd5f43a65afc3673987a3)
[DHIS2-16349]: https://dhis2.atlassian.net/browse/DHIS2-16349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-16349]: https://dhis2.atlassian.net/browse/DHIS2-16349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Enrollment dim. restriction SQL [DHIS2-16349] (#17393) (#17411)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/AclEventExporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17446
> fix: Add org unit mode to event async method  [DHIS2-17296][patch/2.41]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/scheduling/HtmlPushAnalyticsJob.java
cherry-pick backport of #17445
> feat: send user locale in push analytics service call [DHIS2-17408] (2.41)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOrgUnitTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/model/AnalyticsTableColumn.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/AnalyticsTableServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/model/AnalyticsTableColumnTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/model/AnalyticsTablePartitionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/model/AnalyticsTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsIndexHelperTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsTableAsserter.java
The AnalyticsTableColumn class currently has nine overloaded constructors, making maintenance challenging and costly. To improve this, we decided to implement the Builder pattern.
> feat: AnalyticsTableColumn refactoring[2.42-DHIS2-17422]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17431
> fix: Validate TE relationship items [DHIS2-16460][2.41]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/17512
> fix: Validate enrollment in relationships [DHIS2-16460][patch/2.41]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17518
> fix: Validate event in relationships [DHIS2-16460][2.41] 

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17518
> fix: Validate event in relationships [DHIS2-16460] [patch/2.41]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserAccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/UserAccountController.java
backport https://github.com/dhis2/dhis2-core/pull/17507
> fix: use serverBaseUrl for recovery email[17317](41)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
backport https://github.com/dhis2/dhis2-core/pull/17507
> fix: use serverBaseUrl for recovery email[17317](40)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
backport https://github.com/dhis2/dhis2-core/pull/17507
> fix: use serverBaseUrl for recovery email[17317](39)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/grid/GridUtilsTest.java
This PR backports commit 98b6fb1276f42e361729e22d676fe85f50699eb4.
> fix: GridUtils throw duplicate sheet error[DHIS2-17415-41]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/grid/GridUtilsTest.java
This PR backports commit 98b6fb1276f42e361729e22d676fe85f50699eb4.
> fix: GridUtils throw duplicate sheet error[DHIS2-17415-40]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/grid/GridUtilsTest.java
This PR backports commit bab433fd2311010ab3fc26ccb32fc5e39375c6a0.
> fix: GridUtils throw duplicate sheet error[DHIS2-17415-39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
[DHIS2-15898](https://dhis2.atlassian.net/browse/DHIS2-15898)
[DHIS2-15898]: https://dhis2.atlassian.net/browse/DHIS2-15898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.40) Ordering when using psi.attributeOptionCombo[DHIS2-15898]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
[DHIS2-17414](https://dhis2.atlassian.net/browse/DHIS2-17414)
[DHIS2-17414]: https://dhis2.atlassian.net/browse/DHIS2-17414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:Incorrect rule actions while rule-engine context loading[DHIS2-17414]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
cherry pick of https://github.com/dhis2/dhis2-core/pull/17526
> fix: Not able to clear a data element value [2.39] 

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
cherry pick of https://github.com/dhis2/dhis2-core/pull/17526
> fix: Not able to clear a data element value [2.38]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
https://dhis2.atlassian.net/browse/DHIS2-17307
Add delete case missed in https://github.com/dhis2/dhis2-core/pull/15793. Before that PR, the data values were replaced in the update and the null values were automatically handled
> fix: Not able to clear a data element value [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/EventImportTest.java
cherry pick of https://github.com/dhis2/dhis2-core/pull/17526
> fix: Not able to clear a data element value [2.41]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/EventImportTest.java
cherry pick of https://github.com/dhis2/dhis2-core/pull/17526
> fix: Not able to clear a data element value [2.41] [patch]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/RecordingJobProgress.java
I realised that the method added in #17555 would not be called with a `JobConfiguration` instance so I removed the parameter and handled the null case where needed.
> feat: a lean JobProgress for synchonous execution - take 2

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/MetadataItem.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryTest.java
**[Backport from master/2.42]** (#17548)
> fix: ValueType in metadata [DHIS2-15194]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
[DHIS2-17414](https://dhis2.atlassian.net/browse/DHIS2-17414)
[DHIS2-17414]: https://dhis2.atlassian.net/browse/DHIS2-17414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.41.0)Incorrect rule actions while rule-engine context loading[DHIS2-17414]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
This PR partially reverts https://github.com/dhis2/dhis2-core/pull/17455
> revert: reverts cache period deletion [DHIS2-17405]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
This PR backports commit 9e137356ed8d16fc06891d47cf314dac0c146928.
> fix: rootJunction OR return empty result[DHIS2-17449-41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
This PR backports commit 9e137356ed8d16fc06891d47cf314dac0c146928.
> fix: rootJunction OR return empty result[DHIS2-17449-39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
This PR backports commit 9e137356ed8d16fc06891d47cf314dac0c146928.
> fix: rootJunction OR return empty result[DHIS2-17449-40]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
Backport 
[DHIS2-17414](https://dhis2.atlassian.net/browse/DHIS2-17414)
[DHIS2-17414]: https://dhis2.atlassian.net/browse/DHIS2-17414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:(2.41)Incorrect rule actions while rule-engine context loading[DHIS2-17414]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/DateField.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/RelativePeriods.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
This PR will add a DateField along the path into building/getting from PERIOD_CACHE, which was previously ambiguous under some circumstances and caused unexpected results.
> fix: added DateField to track dateField where necessary (PERIOD_CACHE) [DHIS2-17405]

- dhis-2/dhis-api/pom.xml
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OpenApi.java
- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java
- dhis-2/pom.xml
I added a few `@Language` hints
> chore: add various @Language hints

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/17599
> backport: ci: send all Jenkins build failure notifications to backend channel [2.41]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/17599
> backport: ci: send all Jenkins build failure notifications to backend channel [2.39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/TrackedEntityAggregate.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/17516
> fix: /tracker/trackedEntites?order=enrolledAt returns wrong order [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventchart/EventChart.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventreport/EventReport.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventvisualization/EventVisualization.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapView.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/CommonQueryRequestProcessor.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityQueryParams.java
Just renames internal references without changing what's exposed by APIs.
This is part of a major renaming task related to ProgramStatus and EnrollmentStatus.
> chore: Rename programStatus to enrollmentStatus in analytics [DHIS2-17471]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/ObjectUtils.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionScheduleMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTest.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/EndDateTime.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StartDateTime.java
- dhis-2/dhis-web-api/src/main/resources/openapi/EnrollmentsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/EventsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/common/UIDBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatesBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/OrderBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SpringBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentImportRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventImportRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityImportRequestParamsMapperTest.java
Backport of all PRs for https://dhis2.atlassian.net/browse/DHIS2-16019
> fix: Use new start and end date types in tracker exporter [DHIS2-16019] (2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/ObjectUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/EndDateTime.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StartDateTime.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatesBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/OrderBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SpringBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
Backport of all PRs for https://dhis2.atlassian.net/browse/DHIS2-16019
> fix: Use new start and end date types in tracker exporter [DHIS2-16019] (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/ObjectUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/TrackedEntityInstanceCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerEnrollmentCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerTrackedEntityCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/EndDateTime.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StartDateTime.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatesBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
Backport of all PRs for https://dhis2.atlassian.net/browse/DHIS2-16019
> fix: Use new start and end date types in tracker exporter [DHIS2-16019] (2.39)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17572
> fix: Return TEA from specified program only [DHIS2-14300][2.41]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/17526
> fix: Not able to clear a data element value [DHIS2-17307](2.40.3.2)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastatistics/DataStatisticsEventType.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/hibernate/HibernateDataStatisticsEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastatistics/DataStatisticsEventStoreTest.java
* Adjust how active users are calculated in statistics snapshot
* Adjust integration test
* Remove code smell
---------
> fix: Adjust how active users are calculated in statistics snapshot (#16154) (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastatistics/DataStatisticsEventType.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/hibernate/HibernateDataStatisticsEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastatistics/DataStatisticsEventStoreTest.java
* Adjust how active users are calculated in statistics snapshot
* Adjust integration test
* Remove code smell
---------
> fix: Adjust how active users are calculated in statistics snapshot (#16154) (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/collection/ListUtilsTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataSetMetadataControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/dataset/data_element_and_dataset_with_catcombo.json
- dhis-2/dhis-test-web-api/src/test/resources/dataset/data_element_with_catcombo.json
- dhis-2/dhis-test-web-api/src/test/resources/dataset/dataset_and_data_element_with_no_catcombo.json
- dhis-2/dhis-test-web-api/src/test/resources/dataset/dataset_with_catcombo.json
back port of fix #15847 and tests #17665
> fix: Default cat combo returned when expected [DHIS2-16129]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17660
> fix: TEXT and LONG_TEXT with single quote (') [DHIS2-17129] [2.39]

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/history.vm
cherry-pick backport of #17710
> fix: data entry audit history audit type column lookup [DHIS2-16887] (2.40)

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/history.vm
cherry-pick backport of #17710
> fix: data entry audit history audit type column lookup [DHIS2-16887] (2.39)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datastore/DatastoreKeysTest.java
> chore: Update flaky datastore test

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/appmanager/AppManagerTest.java
> fix: Filter App by plugin type [DHIS2-17492]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionKey.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionScheduleMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/TrackerIdentifierCollector.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
Backport for https://github.com/dhis2/dhis2-core/pull/17683 and https://github.com/dhis2/dhis2-core/pull/17735
> fix: Load PR with all PRA and filter later [DHIS2-17470](2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/17683 and https://github.com/dhis2/dhis2-core/pull/17735
> fix: Load PR with all PRA and filter later [DHIS2-17470](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
https://dhis2.atlassian.net/browse/DHIS2-17312
- Use SQL parameter in order to avoid SQL injection attack as the filter parameter value are passed directly from url parameter.
- There are unit tests covered in `EventExporterTest` such as  [EventExporterTest#testEnrollmentFilterAttributes()](https://github.com/dhis2/dhis2-core/blob/dd4451c19307dc3a6146b0e3d49f2727967537d2/dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java#L935)
> fix: use sql parameter in JdbcEventStore

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
(cherry picked from commit 00c351bd665f97037bc78e70ef54d97c04ab8cd8)
> fix: oulevels are now dynamic in TE export [DHIS2-17549] (#17747)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery4AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery5AutoTest.java
> test: more consistent TE e2e [DHIS2-14884]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntity.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_3__Alter_trackedentity_inactive_not_null.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
https://dhis2.atlassian.net/browse/DHIS2-16442
modiffy trackedentity `inactive` to not null constraint and default
> fix: trackedentities DB column inactive allows nulls

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstance.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstance.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_29__Alter_trackedentity_inactive_not_null.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/17749
> fix: trackedentities DB column inactive allows nulls [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstance.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstance.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_29__Alter_trackedentity_inactive_not_null.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/17749
> fix: trackedentities DB column inactive allows nulls [2.40] 

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
Backport: https://github.com/dhis2/dhis2-core/pull/16582
> fix: make sure user create form don't render variable names

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
(cherry picked from commit 6eafbbf816ba4d284f0927075abcecc7bc6910c2)
> fix: can not update users after OpenID field is set (#16723)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
backport of https://github.com/dhis2/dhis2-core/pull/17572 + https://github.com/dhis2/dhis2-core/pull/17566
> fix: Return requested program attributes only [DHIS2-14300][2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
backport of https://github.com/dhis2/dhis2-core/pull/17572 + https://github.com/dhis2/dhis2-core/pull/17566
> fix: Return requested program attributes only [DHIS2-14300][2.39]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
Backport: [DHIS2-14977](https://github.com/dhis2/dhis2-core/pull/17067)
[DHIS2-14977]: https://dhis2.atlassian.net/browse/DHIS2-14977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
JIRA: https://dhis2.atlassian.net/browse/DHIS2-17191
Separate JIRA for backport: https://dhis2.atlassian.net/browse/DHIS2-17581
> chore: make serviceworker.js non-public

- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/mapgeneration/InternalMapObject.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapgeneration/GeoToolsMapObjectTest.java
- dhis-2/pom.xml
This PR backports commit 636c4862a209885c527d7cbda5ea96619119780e.
> fix: api/maps/uid/data return error 500[DHIS2-12003-40]

- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/mapgeneration/InternalMapObject.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapgeneration/GeoToolsMapObjectTest.java
- dhis-2/pom.xml
This PR backports commit 4e85c6404e4aa94d37920eab31b49f7613098f19.
> fix: api/maps/uid/data return error 500[DHIS2-12003-41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/tracker/imports/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/BundlePreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/DefaultTrackerPreprocessService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/StrategyPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/PersistablesFilter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/PersistablesFilterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/non_existent_enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationships_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationships_existent_and_not_existent_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_with_inaccessible_relationship_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_data_before_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_data_for_deletion.json
Backport of https://github.com/dhis2/dhis2-core/pull/17784 and https://github.com/dhis2/dhis2-core/pull/17773
> fix: Remove unused check on delete persistables [DHIS2-17402] (2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/BundlePreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DefaultTrackerPreprocessService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/StrategyPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/PersistablesFilter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/PersistablesFilterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/non_existent_enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationships_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationships_existent_and_not_existent_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_with_inaccessible_relationship_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_data_before_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_data_for_deletion.json
Backport of https://github.com/dhis2/dhis2-core/pull/17784 and https://github.com/dhis2/dhis2-core/pull/17773
> fix: Remove unused check on delete persistables [DHIS2-17402] (2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17840
> fix: Check owner when getting TE with superuser [DHIS2-16981][2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17840
> fix: Check owner when getting TE with superuser [DHIS2-16981][2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17840
> fix: Check owner when getting TE with superuser [DHIS2-16981][2.39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/SideEffectTrigger.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerNotificationThread.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerSideEffectDataBundle.java
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
Backport 
[DHIS2-17180](https://dhis2.atlassian.net/browse/DHIS2-17180)
> fix: (2.40) Indiscriminately sending program notifications [DHIS2-17180]

- dhis-2/pom.xml
The main feature I wanted is https://github.com/dhis2/json-tree/pull/59 and then there is some other stuff in there I did a while back as well as some fundamentals for support of JSON patch, which will be the big feature of 1.2 (I hope)
> chore: Use json-tree v1.1

- jenkinsfiles/stable
The goal of this PR is to add the missing definition of the variable `isHotfix`
> chore: fix/stable im deploy

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/job/SideEffectTrigger.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/job/TrackerNotificationThread.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/job/TrackerSideEffectDataBundle.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerSideEffectHandlerServiceTest.java
backport 
[DHIS2-17180](https://dhis2.atlassian.net/browse/DHIS2-17180)
> fix: (2.41) Indiscriminately sending program notifications [DHIS2-17180]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/SideEffectTrigger.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerNotificationThread.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerSideEffectDataBundle.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
[DHIS2-17180](https://dhis2.atlassian.net/browse/DHIS2-17180)
> fix: (2.39) Indiscriminately sending program notifications [DHIS2-17180]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Type.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EmptyOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/GreaterEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/GreaterThanOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/LessEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/LessThanOperator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/OperatorTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/17949
> fix: api filter support sharing object [DHIS2-17688-41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidator.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/17953
> fix: Return specific message if user can break glass [DHIS2-17477][2.41]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleIssue.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/executor/enrollment/AssignAttributeExecutor.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/te_enrollment_update_attribute_same_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
Backport of https://github.com/dhis2/dhis2-core/pull/17969
> fix: Use correct attributes for rule-engine context [DHIS2-17681](2.41)

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/17855
> backport: ci: add stage for updating stable.json [skip ci] [2.40]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/17855
> backport: ci: add stage for updating stable.json [skip ci] [2.39]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/17855
> backport: ci: add stage for updating stable.json [skip ci] [2.38]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_9__Remove_legendset_tables.sql
It seems that the tables legend, legendset and legendsetindicators are not used nor referenced anywhere in the codebase.
They are being removed.
> fix: Remove legend, legendset and legendsetindicators tables [DHIS2-17606]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreNamespaceProtection.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DefaultDatastoreService.java
cherry-pick backport of #18036
> feat: datastore namespace protection - independent read and write authorities

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/i18n/I18nFormat.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/i18n/I18nFormatTest.java
> fix: supports proper translation for more weekly period types [DHIS2-16762] [2.39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/executor/event/SetMandatoryFieldExecutorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/event/DataValuesValidatorTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18068
> fix: Validate mandatory data values also on UPDATE [DHIS2-17560](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/StatusUpdateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/executor/event/SetMandatoryFieldExecutorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/event/DataValuesValidatorTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18068
> fix: Validate mandatory data values also on UPDATE [DHIS2-17560](2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/implementers/SetMandatoryFieldValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18068
> fix: Validate mandatory data values also on UPDATE [DHIS2-17560])(2.39)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/TeiListGrid.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionIdentifier.java
(cherry picked from commit b7278924499ef6226909d235cce24259e376d605)
> fix: skip rounding when dimension has option set [DHIS2-17257] (#17348)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUsersWithInvalidUsernameControllerTest.java
test related helpers moved to a `.test` package
* https://github.com/dhis2/dhis2-core/pull/18126
* https://github.com/dhis2/dhis2-core/pull/18124
* https://github.com/dhis2/dhis2-core/pull/18125
> test: fix test package DHIS2-16557

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/query/Field.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/TeiQueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/sql/RenderableSqlQuery.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/sql/SqlQueryBuilders.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/context/sql/RenderableSqlQueryTest.java
This PR addresses fields that are sometimes repeated in TE analytics queries.
Moreover, it fixes the JSON aggregation query in TE analytics queries, which unnecessarily uses non-analytics tables.
> fix: repeated fields in TE query [DHIS2-17745]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/EnrollmentMapper.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerSideEffectHandlerServiceTest.java
Backport [[DHIS2-17180]](https://dhis2.atlassian.net/browse/DHIS2-17180)
[PR
](https://github.com/dhis2/dhis2-core/pull/18159)
> fix:(2.41) notification trigger when status is changed to completed [DHIS2-17180]

- .github/workflows/deploy-instance.yml
- .github/workflows/destroy-instance.yml
Backporting the Deploy and Destroy instance workflows to `2.39`
> ci: backport deploy/destroy workflows [skip ci] [2.39]

- .github/workflows/deploy-instance.yml
- .github/workflows/destroy-instance.yml
Backporting the Deploy and Destroy instance workflows to `2.38`
> ci: backport deploy/destroy workflows [skip ci] [2.38]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/IntegrationH2Test.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/IntegrationTest.java
as you cannot mix unit and integration tests in a test class
> test: test annotations should not be put on methods DHIS2-16557

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
(cherry picked from commit 6b9460a2c795e4610c94d9636b98bdfb21de917e)
> fix: Don't find disabled openId user [DHIS2-17784] (#18208)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/NotOwnerReferencesCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/18242
> fix: resetNonOwnerProperties must use getPersistedProperties [DHIS2-17798](41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/NotOwnerReferencesCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/18242
> fix: resetNonOwnerProperties must use getPersistedProperties[DHIS2-17798](39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/NotOwnerReferencesCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/18242
> fix: resetNonOwnerProperties must use getPersistedProperties [DHIS2-17798](40)

- dhis-2/dhis-services/dhis-service-data-exchange/src/main/java/org/hisp/dhis/dataexchange/aggregate/AggregateDataExchangeService.java
- dhis-2/dhis-services/dhis-service-data-exchange/src/test/java/org/hisp/dhis/dataexchange/aggregate/AggregateDataExchangeServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AggregateDataExchangeController.java
https://github.com/dhis2/dhis2-core/pull/17645
> feat: add data read check for api/aggregateDataExchanges [DHIS2-16814](41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/CaptureApp.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/DefaultAdminUserPopulator.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
Add the capture namespace protection to the datastore.
> fix: Add capture namespace protection [DHIS2-17718] (2.39)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramControllerIntegrationTest.java
This PR adds the missing test as suggested in the [back port](https://github.com/dhis2/dhis2-core/pull/18317)
> chore: Add missing test on copy program enrollments [DHIS2-17712]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/DataQueryServiceTest.java
The user analysis org set up in user management is not used in data analysis app.
> fix: User analysis org is refered to user capturing org (event, enrollment api) [2.42-DHIS2-17870]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18322
> backport: ci: increase IM play instances memory requests and probes timeouts [2.41]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18322
> ci: increase IM play instances memory requests and probes timeouts [skip ci] [2.40]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18322
> ci: increase IM play instances memory requests and probes timeouts [skip ci] [2.39]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18322
> ci: increase IM play instances memory requests and probes timeouts [skip ci] [2.38]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DataSetDeletionHandler.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/metadata/MetadataActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/legendset/LegendSetTest.java
> fix: Delete LegendSet with ref in DataSet [DHIS2-6011]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/security/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/OwnershipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackerOwnershipController.java
Backport of https://github.com/dhis2/dhis2-core/pull/18345
> fix: Validate transfer program/orgUnit combo [DHIS2-17880][2.40]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/OwnershipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackerOwnershipController.java
backport of https://github.com/dhis2/dhis2-core/pull/18345
> fix: Validate transfer program/orgUnit combo [DHIS2-17880][2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/RequestTypeAware.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsManagerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
**BACKPORT**
We are seeing discrepancies between the outputs of enrollments in pivot tables vs line listing in the event reports.
> fix: Event Report Enrollments not returning correct data[2.40-DHIS2-15291]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
(cherry picked from commit 4e4e5f1275cb502c9449fa5e65bc85e0600703a2)
> fix: Don't find un-logged-in openId [DHIS2-17784] (#18333)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2RelationshipCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
**_[Backport from master/2.42]_**
(#18423)
> fix: Column name in PI function [DHIS2-17942]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OrganisationUnitControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapViewController.java
cherry-pick backport of #18442
> fix: only run generic search query if no result list present yet [DHIS2-17952] (2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/common/identifiableProperties.hbm
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/metadata/MetadataActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportTest.java
- dhis-2/dhis-test-e2e/src/test/resources/metadata/dataElements/dataElementCreate.csv
- dhis-2/dhis-test-e2e/src/test/resources/metadata/dataElements/dataElementUpdate.csv
> fix: Created property value should not change [DHIS2-15976]

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceMetadataTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceReportingRateTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DimensionalObjectProducerTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/DataItemServiceFacadeTest.java
Another chore to fix tests failing only in Jenkins after merge of https://github.com/dhis2/dhis2-core/pull/18362
> chore: fix broken tests from DHIS2-17906

- dhis-2/build-docker-image.sh
https://github.com/dhis2/dhis2-core/pull/18483
> backport: ci: refactor docker rolling tags logic [skip ci] [2.41]

- dhis-2/build-docker-image.sh
https://github.com/dhis2/dhis2-core/pull/18483
> backport: ci: refactor docker rolling tags logic [skip ci] [2.40]

- dhis-2/build-docker-image.sh
https://github.com/dhis2/dhis2-core/pull/18483
> backport: ci: refactor docker rolling tags logic [skip ci] [2.39]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/ProgramRuleActionDeletionHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationTemplateServiceTest.java
backport 
[DHIS2-17515](https://dhis2.atlassian.net/browse/DHIS2-17515)
[DHIS2-17515]: https://dhis2.atlassian.net/browse/DHIS2-17515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.41) Veto when deleting notification template associated with program rule [DHIS2-17515]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/ProgramRuleActionDeletionHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationTemplateServiceTest.java
backport 
https://dhis2.atlassian.net/browse/DHIS2-17515
> fix: (2.40) Veto when deleting notification template associated with program rule [DHIS2-17515] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleActionService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleActionStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleActionService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/ProgramRuleActionDeletionHandler.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleActionStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationTemplateServiceTest.java
backport 
https://dhis2.atlassian.net/browse/DHIS2-17515
> fix: (2.39) Veto when deleting notification template associated with program rule [DHIS2-17515] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/scheduling/ContinuousAnalyticsTableJob.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/scheduling/ContinuousAnalyticsTableJobTest.java
> fix: Run full update for cont analytics table job if first time [DHIS2-16986]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
cherry-pick backport of #18504
after trouble with the test I excluded the change in the test class
> fix: disallow filtering on some value types [DHIS2-17313] (2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
One more case to consider in handling of value types when building Gist filters.
> fix: disallow filtering on some value types [DHIS2-17313]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipController.java
Move `TrackerOwnershipController` and related test to `tracker` package
> chore: Move ownership controller into tracker package

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
cherry-pick backport of #18504
after trouble with the test I excluded the change in the test class
> fix: disallow filtering on some value types [DHIS2-17313] (2.40)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiController.java
Make sure the cache fields are only used when the request parameters are such that describe the full OpenAPI in its default mode.
* use `/api/openapi/openapi.json?expandedRefs=true`
* or use `/api/openapi/openapi.json?expandedRefs=true` to verify visually
* check e.g. that in the schema for `DataElement` the collection of `CategoryCombo`s are referred to as such and not as `BaseIdentifiableObject`
> fix: OpenAPI - only cache the full default response [DHIS2-17684]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultUserDetailsService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/ldap/authentication/CustomLdapAuthenticationProvider.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/ldap/authentication/DhisBindAuthenticator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/GenericOidcProviderConfigParser.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
Backport of: https://github.com/dhis2/dhis2-core/pull/16794
> fix: broken ldap 2.40

- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
backport of
* https://github.com/dhis2/dhis2-core/pull/18612
* https://github.com/dhis2/dhis2-core/pull/18617
> ci: use existing node installation on CI [2.41]

- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
backport of
* https://github.com/dhis2/dhis2-core/pull/18612
* https://github.com/dhis2/dhis2-core/pull/18617
> ci: use existing node installation on CI [2.40]

- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
This reverts commit 449f0400cf4667170f900f4804da23b8dd3a0a18.
see https://github.com/dhis2/dhis2-core/pull/18624
> ci: revert to using the frontend plugin to bundle apps [2.40]

- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
This reverts commit 19b7539987a71ed4b260751196c9ef4675cbe76f.
see https://github.com/dhis2/dhis2-core/pull/18624
> ci: revert to using the frontend plugin to bundle apps [2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationTemplateStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationTemplateServiceTest.java
backport 
[DHIS2-17834](https://dhis2.atlassian.net/browse/DHIS2-17834)
[DHIS2-17834]: https://dhis2.atlassian.net/browse/DHIS2-17834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:(2.41) Pagination for program notification template[DHIS2-17834]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/BaseNotificationParam.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationTemplateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/HibernateProgramNotificationInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationTemplateServiceTest.java
backport
https://dhis2.atlassian.net/browse/DHIS2-17834
> fix:(2.40) Pagination for program notification template [DHIS2-17834]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18539
> fix: Clean up completed data when status is not completed [DHIS2-16122](2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18539
> fix: Clean up completed data when status is not completed [DHIS2-16122](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18539
> fix: Clean up completed data when status is not completed [DHIS2-16122](2.39)

- .github/workflows/run-api-analytics-tests.yml
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/AnalyticsApiTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/helpers/extensions/AnalyticsSetupExtension.java
Update/fix the version of the analytics e2e DB.
> fix: Analytics test DB version

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerProgramRuleBundleServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerSideEffectHandlerServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleEngineDescriptionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_with_data_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/three_events_with_different_dates.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerPostgresTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18508
> fix: Load events to fix program rule variables calculation [DHIS2-17951](2.41)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/pom.xml
Backport of https://github.com/dhis2/dhis2-core/pull/18568
> fix: Test nullable org unit code for new rule-engine version [DHIS2-17715](2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/report/ImportReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/report/PersistenceReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/DeleteEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/RelationshipSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SimpleEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/TrackerEventSMSListener.java
to debug e2e test that only fails on Jenkins. Right now we cannot return proper errors to users via sms. This is why we don't have much information if our tests fail. For now log the error until we implement DHIS2-18003
> chore: log sms processing errors DHIS2-17729

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
I can reproduce the test failure in our custom branch pipeline on Jenkins https://ci.dhis2.org/job/dhis2-core-custom-branch
I'll disable the test for now on master so other failures are noticed.
> test: temporarily disable test DHIS2-17729

- dhis-2/dhis-test-e2e/README.md
Small fixes in README file, in the analytics section.
> fix: Steps in analytics e2e readme

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterSimpleBeanPropertyFilter.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/Defaults.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonCategoryCombo.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonDataElement.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryComboControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionComboControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataElementControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/StreamingJsonRootMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StreamingJsonRoot.java
> fix: Exclude defaults fix [DHIS2-17564](2.41)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterSimpleBeanPropertyFilter.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/Defaults.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonCategoryCombo.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonDataElement.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryComboControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionComboControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataElementControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/StreamingJsonRootMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StreamingJsonRoot.java
> fix: Exclude defaults fix [DHIS2-17564](2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datavalue/DataValueStoreTest.java
This PR backports commit f559e7b9ecfef1b21ff440e5ea92813e92e3056c.
> chore: use native sql in dataValueStore.getSoftDeletedDataValue[DHIS2-16754-40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datavalue/DataValueStoreTest.java
This PR backports commit f559e7b9ecfef1b21ff440e5ea92813e92e3056c.
> chore: use native sql in dataValueStore.getSoftDeletedDataValue[DHIS2-16754-39]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_without_date.json
- dhis-2/pom.xml
Backport of https://github.com/dhis2/dhis2-core/pull/18736
> fix: Use createdAt as secondary sorting param [DHIS2-18093] (2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18807 fixing https://dhis2.atlassian.net/browse/DHIS2-18225
> fix: Fix status update logic for enrollment [DHIS2-18225](2.39)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18807 fixing https://dhis2.atlassian.net/browse/DHIS2-18225
> fix: Fix status update logic for enrollment [DHIS2-18225](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/converter/EnrollmentTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18807 fixing https://dhis2.atlassian.net/browse/DHIS2-18225
> fix: Fix status update logic for enrollment [DHIS2-18225](2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18807 fixing https://dhis2.atlassian.net/browse/DHIS2-18226
> fix: Set lastUpdatedBy when creating relationships [DHIS2-18226](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/RelationshipTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/converter/RelationshipTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18807 fixing https://dhis2.atlassian.net/browse/DHIS2-18226
> fix: Set lastUpdatedBy when creating relationships [DHIS2-18226](2.41)

- .github/workflows/run-api-analytics-tests.yml
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18834
https://github.com/dhis2/dhis2-core/pull/18837
> backport: ci: migrate to docker compose v2 CLI in stable and dev pipelines [skip ci] [2.40]

- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18834
https://github.com/dhis2/dhis2-core/pull/18837
> backport: ci: migrate to docker compose v2 CLI in stable and dev pipelines [skip ci] [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityfilter/EntityQueryCriteria.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilterServiceTest.java
Backport 
https://dhis2.atlassian.net/browse/DHIS2-18206
> fix: (2.39) Incorrect follow-up value while saving working list[DHIS2-18206]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityfilter/EntityQueryCriteria.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilterServiceTest.java
Backport https://dhis2.atlassian.net/browse/DHIS2-18206
> fix: (2.40) Incorrect follow-up value while saving working list[DHIS2-18206]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityfilter/EntityQueryCriteria.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityFilterServiceTest.java
Backport https://dhis2.atlassian.net/browse/DHIS2-18206
> fix: (2.41) Incorrect follow-up value while saving working list[DHIS2-18206]

- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18842
> backport: ci: add project name opt to compose when building multiple Tomcat versions [skip ci] [2.40]

- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18842
> backport: ci: add project name opt to compose when building multiple Tomcat versions [skip ci] [2.39]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManagerTest.java
* fix: TEAs marked as Confidential are now skipped [DHIS2-18230]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
* fix: TEAs marked as Confidential are now skipped [DHIS2-18230]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
* fix: fixed peer review comments [DHIS2-18230]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
---------
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
(cherry picked from commit 7f1d789c2ab6c9cefe1c93471808209df4e85c9a)
[DHIS2-18230]: https://dhis2.atlassian.net/browse/DHIS2-18230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18230]: https://dhis2.atlassian.net/browse/DHIS2-18230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> fix: TEAs marked as Confidential are now skipped [DHIS2-18230] [2.41] (#18831)

- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18851
> backport: ci: set compose project name as env variable [skip ci] [2.40]

- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18851
> backport: ci: set compose project name as env variable [skip ci]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/EnrollmentMapper.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/EnrollmentImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_enrollment_event.json
Backport of https://github.com/dhis2/dhis2-core/pull/18850
> fix: Map completed data in preheat for enrollment [DHIS2-18225](2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/TrackedEntityInstanceSupportService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceControllerTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/service/TrackedEntityInstanceSupportServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18859
> fix: Add program param in attribute image endpoint [DHIS2-17173][2.40]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/events/events.json
Backport of https://github.com/dhis2/dhis2-core/pull/18871 to fix https://dhis2.atlassian.net/browse/DHIS2-18252
> fix: Always use system time for createdAt in events [DHIS2-18252](2.40)

- dhis-2/build-docker-image.sh
- jenkinsfiles/rebuild-image
https://github.com/dhis2/dhis2-core/pull/18832
> ci: set base image in rebuild pipeline, not script [skip ci] [2.41]

- dhis-2/build-docker-image.sh
- jenkinsfiles/rebuild-image
https://github.com/dhis2/dhis2-core/pull/18832
> ci: set base image in rebuild pipeline, not script [skip ci] [2.40]

- dhis-2/build-docker-image.sh
- jenkinsfiles/rebuild-image
https://github.com/dhis2/dhis2-core/pull/18832
> ci: set base image in rebuild pipeline, not script [skip ci] [2.39]

- docker-compose.yml
that is already the case on other branches
https://github.com/dhis2/dhis2-core/blob/3edb93abb60e14ac9824ab2a748f2da35229cc3b/docker-compose.yml#L50
https://github.com/dhis2/dhis2-core/blob/c0304f62a2026274c9bfa412958e1f7122eb8e1b/docker-compose.yml#L50
https://github.com/dhis2/dhis2-core/blob/900f13110659948b2a3e5a502bd3b938d43e3599/docker-compose.yml#L55
> fix: use correct DB version in docker-compose.yml

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceBlocklist.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
* feat: add max upload file size validation
(cherry picked from commit eae98479b776e6edbbd3ff9a92c8a79109590521)
> feat: add max upload file size validation (#18113)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceBlocklist.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
* feat: add more validation to file upload
(cherry picked from commit dcbe1dda45cd39de19bd0163fa831ce032e5a9a8)
> feat: add more validation to file upload (#18112)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TwoFactorControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/TwoFactorController.java
(cherry picked from commit 405f4881db73c424dba5299d3ad05ab6cb5f4330)
> feat: add a brute force protection on the 2fa/disable endpoint (#18155)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/SqlBuilderProvider.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/jdbc/JdbcResourceTableStore.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
Adds a Doris implementation of `SqlBuilder` and corresponding unit test. The main purpose of this PR is to merge non-invasive changes from the main feature branch for DHIS2-16705 to avoid the branch from growing and have merge conflicts.
> fix: Add DorisSqlBuilder class and test [DHIS2-16705]

- dhis-2/dhis-web/dhis-web-portal/pom.xml
- jenkinsfiles/dev
- jenkinsfiles/rebuild-image
- jenkinsfiles/stable
Backport of https://github.com/dhis2/dhis2-core/pull/18899
Requested review from everyone that has been involved in discussing this one way or another, mostly for visibility.
> ci: remove building/testing with tomcat 8.5 [2.41]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/category_option_combos_same_category_options.yaml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityCategoryOptionComboDuplicatedTest.java
Modify SQL to only identify COCs which are duplicated within the same category combo
> Dhis2 18258

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
cherry-pick of #19063 
test had conflicts so I removed it
> fix: consider all attribute flag properties as persisted and writable [DHIS2-18297] (2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
cherry-pick of #19063
test had conflicts so I removed it
> fix: consider all attribute flag properties as persisted and writable [DHIS2-18297] (2.40)

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_dimensions_no_visualizations.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityCategoryDimensionNoFavoritesControllerTest.java
squashed from #18901 because of commit signing
> feat: Integrity check for categories which are dimensions but which have no visualizations

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractGistControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistCsvControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
> fix: flaky test setup gist filters (2.41)

- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
https://dhis2.atlassian.net/browse/DHIS2-18383
> fix: Ensure that the names of data integrity checks can be translated

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultAnalyticsServiceTest.java
> perf: improves CSV exports when too many dimensions combinations exists [DHIS2-18377][2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultAnalyticsServiceTest.java
> perf: improves CSV exports when too many dimensions combinations exists [DHIS2-18377][2.39]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
Backports of functionality in https://dhis2.atlassian.net/browse/DHIS2-17329
> feat: add more validation to file upload

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/configuration/DefaultConfigurationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/DefaultMessageService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/DhisControllerTestBase.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MessageConversationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
* fix: add more access control to message conversations
(cherry picked from commit 30b72e34267153b34d926a8d023fb8b38df31213)
> fix: add more access control to message conversations

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/trackedentity/store/query/EnrollmentQuery.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/query/EnrollmentQuery.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19130
> fix: Fix enrollment query to get correct orgUnit [DHIS2-14829] (2.41)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/query/EnrollmentQuery.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19130
> fix: Fix enrollment query to get correct orgUnit [DHIS2-14829] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/query/EnrollmentQuery.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
Backports of https://github.com/dhis2/dhis2-core/pull/19130
> fix: Fix enrollment query to get correct orgUnit [DHIS2-14829] (2.39)

- jenkinsfiles/stable
Backport of https://github.com/dhis2/dhis2-core/pull/19194
> ci: push test/dev images to dhis2/core-dev [skip ci]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/19114
> fix: endpoint api/options causes too many DB queries [DHIS2-18135] (41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/19114
> fix: endpoint api/options causes too many DB queries (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/19114
> fix: endpoint api/options causes too many DB queries (2.39)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/preheat/TrackerPreheatIdentifiersTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/preheat/TrackerPreheatServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_events.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/identifier_metadata.json
Partially related to new import restrictions on alternative default category/options/combos
> fix: Remove custom COC defaults

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/report/Report.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/report/ReportTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DefaultDimensionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/hibernate/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/hibernate/EventReport.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventvisualization/hibernate/EventVisualization.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/report/hibernate/Report.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultAnalyticalObjectImportHandler.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v40/V2_40_30__Add_new_column_into_visualization_and_migrate_relative_periods.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dimension/DimensionServiceTest.java
**_[Backport from master/2.42]_**
(#18691)
> fix: Order of relative periods in analytics models [DHIS2-18020]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserOrgUnitProperty.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/split/orgunit/OrgUnitSplitServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
> fix: Org unit split assinged to correct users [DHIS2-18423](2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserOrgUnitProperty.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/split/orgunit/OrgUnitSplitServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
> fix: Org unit split assigned to correct users [DHIS2-18423](2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserOrgUnitProperty.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/split/orgunit/OrgUnitSplitServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
> fix: Org unit split assigned to correct users [DHIS2-18423](2.39)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/DisplayNameUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/PostgreSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/SqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilderTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/db/sql/PostgreSqlBuilderTest.java
* Removes redundant JSON method from `SqlBuilder`.
* Improves clarity of parameter names.
* Adds unit tests.
> refactor: Simplify and add unit tests for SqlBuilder [DHIS2-16705]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/DateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/DateValidatorTest.java
Backport 
https://dhis2.atlassian.net/browse/DHIS2-15683
> fix: (2.41) Fix Date Validation to Fail for Future Enrollment Dates (Including Tomorrow)[DHIS2-15683]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Adding missing `/` for fix in [here](https://github.com/dhis2/dhis2-core/pull/19307)
> fix: Remove doubled api string in location header [DHIS2-12536](2.40)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Adding missing `/` for fix in [here](https://github.com/dhis2/dhis2-core/pull/19306)
> fix: Remove doubled api string in location header [DHIS2-12536](2.39)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceController.java
Adding missing `/` for fix in [here](https://github.com/dhis2/dhis2-core/pull/19308)
> fix: Remove doubled api string in location header [DHIS2-12536](2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/19122
> fix: NPE when delete eventVisualization [DHIS2-18330-41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
This PR backports commit c2c075887b64c5a181ea0ca9bd566c7bce075d2f.
> fix: NPE when delete eventVisualization[DHIS2-18330-40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
This PR backports commit e50b24b383489b87982ebda757e167bd5eb7ef69.
> fix: NPE when delete eventVisualization[DHIS2-18330-39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/validator/event/DateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/validator/event/DateValidatorTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19297
> fix: [DHIS2-15272] Fix program expiryDays check with periodType for events (2.40)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/IdSchemeExportControllerTest.java
I initially thought I would need to also assert on nested relationship objects. This is why I tried to make generic assertions that could be reused for fields like dataValues on the event and on a relationships event. Since we do not need that make the assertions less complicated.
> test: simplify metadata assertions DHIS2-14968

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/TokenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/TokenOperatorTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CrudControllerIntegrationTest.java
This PR backports commit cba4eff4c00cf20b02052f55914939c96b65e4f9.
> fix: not apply identifiable token filter to uid length < 4[DHIS2-17098-41]

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
forward port from https://github.com/dhis2/dhis2-core/pull/19220
> fix: use default schema validate if config value is invalid

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/TokenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/TokenOperatorTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CrudControllerIntegrationTest.java
This PR backports commit 4d57a88034f4295a055662963c678bf16f682dd9.
> fix: not apply identifiable token filter to uid length < 4[DHIS2-17098-40]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
Hotfix PR based on https://github.com/dhis2/dhis2-core/pull/19372
> fix: [DHIS2-18551] (2.39.7.1) Fix access check when registering TEI (#19372)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
Forward port of https://github.com/dhis2/dhis2-core/pull/19372
> fix: [DHIS2-18551] (2.40) Fix access check when registering TEI (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/TrackedEntityServiceTest.java
Forward Port of https://github.com/dhis2/dhis2-core/pull/19372
> fix: [DHIS2-18551] (2.41) Fix access check when registering TEI

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19397
> fix: [DHIS2-18527] (2.39) Fix deleted relationship getting returned in event

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
This reverts commit 832094e87b34370fee1c734172dbdd40bbd21c28.
> fix: revert endpoint api/options causes too many DB queries (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
This reverts commit deb026a826cf39998aea244bfd11077defd77a44.
> fix: revert endpoint api/options causes too many DB queries (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
This reverts commit 832094e87b34370fee1c734172dbdd40bbd21c28.
> fix: revert endpoint api/options causes too many DB queries (#19421)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterService.java
Backport of https://github.com/dhis2/dhis2-core/pull/19363
> fix: Only use occurreddate to filter events in exporter [DHIS2-17732](2.41)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
Backport of https://github.com/dhis2/dhis2-core/pull/19363
> fix: Only use occurreddate to filter events in exporter [DHIS2-17732](2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
Backport of https://github.com/dhis2/dhis2-core/pull/19363
> fix: Only use occurreddate to filter events in exporter [DHIS2-17732](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19423
This issue does not occur in <= 2.40.
> fix: Validate data sharing on program stage [DHIS2-17594][2.41]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/CategoryOptionMergeTest.java
Re-enable recently-disabled E2E CategoryOption merge test that started failing on GitHub only strangely.
The test setup, importing metadata, now excludes category option combos.
Category option combos should not be imported like this I think.
They are generated programmatically (test now calls maintenance endpoint which triggers category option combo generation)
> chore: Fix e2e disabled tests

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/events-scheduled-with-registration.json
Backport of https://github.com/dhis2/dhis2-core/pull/19457
> fix: Validate search scope when scheduled event [DHIS2-17335][2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
* feat: implement special logout url for linked accounts feature
(cherry picked from commit 2c6105d01e8a29b0dd419c451b959ecbb8735096)
> feat: implement special logout url for linked accounts feature (#19435)

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19401
> backport: ci: sign commit when updating stable json file [skip ci]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/tracked-entity-query.json
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/trackedentity/TrackedEntityQuery8AutoTest.java
Fixing flaky e2e analytics test.
> fix: Flaky e2e test [DHIS2-18650]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
> fix: Broken test in master [DHIS2-18665]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19524
> backport: ci: remove boolean type from var definition [skip ci]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
fix: ou item names in visualization [DHIS2-18337] (#19523)
* fix: ou item names in visualization [DHIS2-18337]
* fix: formatting [DHIS2-18337]
---------
(cherry picked from commit 476cb6efdd95f7f35ae456c7cdef9f07f93fc7c5)
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ou item names in visualization [DHIS2-18337] (2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
* fix: ou item names in visualization [DHIS2-18337]
* fix: formatting [DHIS2-18337]
---------
(cherry picked from commit 476cb6efdd95f7f35ae456c7cdef9f07f93fc7c5)
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ou item names in visualization [DHIS2-18337] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
fix: ou item names in visualization [DHIS2-18337] (#19523)
* fix: ou item names in visualization [DHIS2-18337]
* fix: formatting [DHIS2-18337]
---------
(cherry picked from commit 476cb6efdd95f7f35ae456c7cdef9f07f93fc7c5)
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18337]: https://dhis2.atlassian.net/browse/DHIS2-18337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ou item names in visualization [DHIS2-18337] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/TrackerCrudTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19544
> fix: [DHIS2-18599] Respect dryRun in old TEI Import (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
Backport of: https://github.com/dhis2/dhis2-core/pull/19565
> fix: broken linked account feature

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
Adds the old login URL as an alternative for the fallback static login page.
> feat: add old login endpoint URL as fallback

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19590
> fix: [DHIS2-18459] Re-use obtained maxTeLimit (2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramNotificationMessageRenderer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramStageNotificationMessageRenderer.java
backport 
[DHIS2-18633](https://dhis2.atlassian.net/browse/DHIS2-18633)
[DHIS2-18633]: https://dhis2.atlassian.net/browse/DHIS2-18633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: (2.39) Enrollment/Event notification in tracker app (#19531)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MandatoryAttributesCheck.java
cherry-pick of #19643 but with the test removed as it had too many conflicts
> fix: mandatory attributes cannot have empty value [DHIS2-18365] (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MandatoryAttributesCheck.java
cherry-picked the entire file from 2.40 after #19645
> fix: mandatory attributes cannot have empty value [DHIS2-18365] (2.39)

- dhis-2/dhis-web-api/src/main/resources/openapi/EventsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
Add Open API doc regarding assigned user mode
> fix: Adapt open api docs to assigned user modes [DHIS2-13960]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/CategoryOptionComboMergeTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/CategoryOptionMergeTest.java
1 existing e2e test failed on Jenkins only (locally passing and on GitHub also)
Trying to tweak a test setup with this PR. If this PR fails on Jenkins, I'll disable & investigate further.
> chore: update cat opt merge e2e test

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/CategoryOptionMergeTest.java
> chore: Disable cat opt merge e2e test

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
https://dhis2.atlassian.net/browse/DHIS2-18584
> fix:(2.40) Capture app sending multiple notifications when stage appear along with enrollment

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserRoleBundleHook.java
Backport: https://github.com/dhis2/dhis2-core/pull/19703
> fix: don't use getAllPrincipals

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackerOwnershipController.java
backport of https://github.com/dhis2/dhis2-core/pull/19670
> fix: Grant temp access only if user in search scope [DHIS2-18784] [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackerOwnershipController.java
backport of https://github.com/dhis2/dhis2-core/pull/19670
> fix: Grant temp access only if user in search scope [DHIS2-18784] [2.40]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
Backport: https://github.com/dhis2/dhis2-core/pull/18730
> fix: add back attribute values at /me endpoint

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/calendar/impl/NepaliCalendar.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodType.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/calendar/impl/NepaliCalendarTest.java
- ISO period names should match Nepali calendar. Baisakh 2081 is 208101 not 202404
- Fix to weekly periods start and end dates
> fix: Nepali calendar support [DHIS2-18268]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
Backport from master/2.42 (#19439)
>  fix: Backport Org. Unit bug fixed in PR #19439 [DHIS2-18882] 

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportControllerTest.java
- Fix review comments from https://github.com/dhis2/dhis2-core/pull/19705
- Add test cases for multiple enrollments endpoint in `EnrollmentsExportControllerTest`
- Add assertions on `shouldGetEnrollmentWithRelationshipsFields` to check all the requested entities are part of the relationship and there are not cycles (no entity has a `relationship` field)
> chore: Clean up tests [DHIS2-18791]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/InQueryFilterTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/query/EventQueryTest.java
…#19727)
* fix: quotes ouIds for IN filter, resolve ou uids [DHIS2-18845]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
* test: added e2e test [DHIS2-18845]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
* fix: quotes ouIds for IN filter, resolve ou uids [DHIS2-18845]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
* test: added e2e test [DHIS2-18845]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
* test: added e2e test [DHIS2-18845]
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
---------
Signed-off-by: Giuseppe Nespolino <g.nespolino@gmail.com>
(cherry picked from commit d2c87f654c6ffcd0e8957ca4f89ca875ee70b257)
[DHIS2-18845]: https://dhis2.atlassian.net/browse/DHIS2-18845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> fix: IN filter now works with org units data elements [DHIS2-18845] [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapViewStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MappingService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/DefaultMappingService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/MapViewDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/hibernate/HibernateMapViewStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/19686 and https://github.com/dhis2/dhis2-core/pull/19747
> fix: remove Program fk when deleting MapView [DHIS2-18702] (41)

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/webapi/json/domain/JsonMeDto.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
Exposes the user's 2FA type in the /me endpoint.
> feat: expose the 2FA type in the /me endpoint

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventQueryParamsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/19760
> feat: Sort events when filter contains DE UID only [DHIS2-15954][2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/LoginConfigResponse.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/LoginConfigControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/LoginConfigController.java
Removes the password validation regular expression from the system settings.
> feat: remove the regexp in the system config

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
Properly replaces analytics completeness SQL query.
> fix: Properly replace completeness SQL query [DHIS2-18957]

- dhis-2/dhis-web-api/src/main/resources/openapi/EnrollmentsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
TE part is taken from https://github.com/dhis2/dhis2-core/pull/16782 + clarifying its a tracker program
> docs: clarify program is a tracker program in OpenAPI spec

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19788
> backport: ci: set public property for IM instances [2.41]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19788
> backport: ci: set public property for IM instances [2.40]

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19788
> backport: ci: set public property for IM instances [2.39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/DefaultTrackerSideEffectConverterService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
backporting 
https://dhis2.atlassian.net/browse/DHIS2-18517
> fix:(2.39) Schedule notification while using system variable[DHIS2-18517]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryLimitTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
- docker-compose.yml
> fix: no access to tracker programs or no tracker programs DHIS2-17959 [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobSchedulerLoopService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
cherry-picked from #19949 with some manual conflict resolving
> fix: use error only notifier logging for frequent jobs [DHIS2-17998] (2.41)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultAnalyticalObjectImportHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/favorites/event_visualizations.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/favorites/metadata_with_legendSet.json
This PR backports commit 6d3ddc4fd27ab5c0308af3a0fec091b6be89928c.
> fix: TransientObjectException on LegendSet during import EventVisualization[DHIS2-17445-41]

- dhis-2/pom.xml
https://dhis2.atlassian.net/browse/DHIS2-18621
> fix: bump rule-engine version to address DHIS2-18621

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/option_sets/option_sets_wrong_sort_order.yaml
https://github.com/dhis2/dhis2-core/pull/20005
> backport: fix: Adjust option set sort order check

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/Page.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/HibernateEventChangeLogStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityChangeLogStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/ExportControllerPaginationTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportChangeLogsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesChangeLogsControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
following https://github.com/dhis2/dhis2-core/pull/20027
* and reuse new `Page` constructor in change log stores
> feat: add prev/nextPage to /tracker/relationships DHIS2-19021

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/AnalyticalObject.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultAnalyticalObjectImportHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/favorites/event_visualizations.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/favorites/metadata_with_legendSet.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/19938
> fix: TransientObjectException on LegendSet during import EventVisualization [DHIS2-17445-40]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventCoordinateService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
Back-port from https://github.com/dhis2/dhis2-core/pull/20034
> fix: Append geo suffix to OU Data Element fields [DHIS2-19010] [2.40]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventCoordinateService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
Back-port from https://github.com/dhis2/dhis2-core/pull/20034
> fix: Append geo suffix to OU Data Element fields [DHIS2-19010] [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv14AutoTest.java
Back-port from https://github.com/dhis2/dhis2-core/pull/19986
> fix: do not ignore measure criteria in aggregated analytics query [DHIS2-18788] [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
Back-port from https://github.com/dhis2/dhis2-core/pull/19986
> fix: do not ignore measure criteria in aggregated analytics query [DHIS2-18788] [2.39]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19988
> backport: ci: upload IM db from stable pipeline if one is missing [skip ci] [2.41]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19988
> backport: ci: upload IM db from stable pipeline if one is missing [skip ci] [2.40]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19988
> backport: ci: upload IM db from stable pipeline if one is missing [skip ci] [2.39]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/19988
> backport: ci: upload IM db from stable pipeline if one is missing [skip ci] [patch/2.39.9]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/Section.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/indicator/IndicatorMergeProcessorTest.java
> fix: Add indicator to section if not present [DHIS2-18666](2.41)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/tei_enrollment_completed_event.json
Backport 
https://dhis2.atlassian.net/browse/DHIS2-18621
> fix: (2.40) do not use null attributes to rule-engine[DHIS2-18621]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
> feat: adds configuration for primary leader node [DHIS2-16878] (2.41)

- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
Copy pasted the file from another [PR](https://github.com/dhis2/dhis2-core/pull/16782) (due to requiring signed commits)
> chore: Add TE export API open api spec

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/orgunit/handler/MetadataOrgUnitMergeHandler.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/orgunit/OrgUnitMergeServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
> fix: Org Unit merge assigns correct users to merged units [DHIS2-19020](2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UID.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/orgunit/handler/MetadataOrgUnitMergeHandler.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/orgunit/OrgUnitMergeServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
> fix: Org Unit merge assigns correct users to merged units [DHIS2-19020](2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UID.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/orgunit/handler/MetadataOrgUnitMergeHandler.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/orgunit/OrgUnitMergeServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
> fix: Org Unit merge assigns correct users to merged units [DHIS2-19020](2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleServiceTest.java
Forward port of https://github.com/dhis2/dhis2-core/pull/20197
> fix: [DHIS2-19155] Check if program is without registration for rule engine (2.39)

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/20208
> backport: ci: remove implement.io integration from dev pipeline [2.39]

- jenkinsfiles/dev
https://github.com/dhis2/dhis2-core/pull/20208
> backport: ci: remove implement.io integration from dev pipeline [2.41]

- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/hibernate/HibernateValidationResultStore.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/validation/ValidationResultController.java
Manual backport of #20229 by copying the essential lines.
> fix: validation results paging [DHIS2-19173] (2.40)

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/web/WebClient.java
backport of https://github.com/dhis2/dhis2-core/pull/20237
> test: fix wrong HTTP header Content-Type [2.41]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/web/WebClient.java
backport of https://github.com/dhis2/dhis2-core/pull/20237
> test: fix wrong HTTP header Content-Type [2.40]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/web/WebClient.java
backport of https://github.com/dhis2/dhis2-core/pull/20237
> test: fix wrong HTTP header Content-Type [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-17933 
Backport
> fix:(2.40) fix search scope breaks trackedEntities endpoint[DHIS2-17933]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-17933
> fix:(2.39) fix search scope breaks trackedEntities endpoint[DHIS2-17933]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20160
> fix: use max limit correctly to avoid NPE  [DHIS2-19050][2.41]

- dhis-2/pom.xml
> fix: Bump rule-engine version [DHIS2-19199]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/another_single_te.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationshipTEtoTE.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportReportTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20192 and https://github.com/dhis2/dhis2-core/pull/20253
> fix: Update TE updatedAt when creating a relationship [DHIS2-9767] (2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/another_single_te.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationshipTEtoTE.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportReportTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20192 and https://github.com/dhis2/dhis2-core/pull/20253
> fix: Update TE updatedAt when creating a relationship [DHIS2-9767] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityType.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_42__make_shortname_in_trackedentitytype_unique.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityTypeServiceTest.java
Continue on [this PR](https://github.com/dhis2/dhis2-core/pull/20199), `TrackedEntityType.shortname` should be unique
> fix: make trackedEntityType.shortname unique

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/deduplication/merge/PotentialDuplicatesRelationshipTests.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/imports/relationships/RelationshipsTests.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerPostgresTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20212
> fix: Unidirectional relationships only consider from end when exporting [DHIS2-19169] (2.41)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
Reverts dhis2/dhis2-core#20350
> Revert "fix: Missing OU in metadata items [DHIS2-18884]"

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionGroup.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionGroupSet.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionGroupStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/DefaultOptionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/hibernate/HibernateOptionGroupStore.java
> chore: remove unused methods around options [DHIS2-18135]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/20219
> backport: ci: use merge flag when merging stable.json PR [2.41]

- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/20219
> backport: ci: use merge flag when merging stable.json PR [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DashboardCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataElementControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
> fix: Correct ignored stats when import validation fails [DHIS2-15604](2.42)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DashboardCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataElementControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
> fix: Correct ignored stats when import validation [DHIS2-15604](2.41)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/PostgreSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/SqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilderTest.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
Backport from https://github.com/dhis2/dhis2-core/pull/20349
> feat: add SQL functions for standard deviation and variance (Clickhouse)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/mapper/TrackedEntityRowCallbackHandler.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/query/TrackedEntityQuery.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20357
> fix: Fetch org unit path when getting TE [DHIS2-19282_patch_2.42.0]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/OperationsParamsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/OperationsParamsValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20360
> fix: Remove unnecessary TET and program validations [DHIS2-19286_2.42]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/OperationsParamsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/OperationsParamsValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20360
> fix: Remove unnecessary TET and program validations [DHIS2-19286_patch_2.42.0]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/literal/SqlLiteral.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/20162
> fix: cast numeric type in SqlLiteral [DHIS2-13925] (41)

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/literal/SqlLiteral.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/20162
> fix: cast numeric type in SqlLiteral [DHIS2-13925] (40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20300
> fix: Validate user access when breaking glass [DHIS2-18877_2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20300
> fix: Validate user access when breaking glass [DHIS2-18877_2.40]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramStageInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitydatavalue/DefaultTrackedEntityDataValueAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManagerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeValueAuditTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityDataValueAuditTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20249 and https://github.com/dhis2/dhis2-core/pull/20251
> fix: Log changes when change log flag enabled [DHIS2-19227_2.39]

- .gitignore
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/message/ProgramMessageRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationInstanceRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationTemplateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/PotentialDuplicateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/ChangeLogRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/MappingErrors.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/ImportRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/CsvEventServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/CsvTrackedEntityServiceTest.java
- dhis-2/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/20450
> chore: update google formatter version [2.42]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ServerSideImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_31__create_index_program_rule.sql
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20375
> fix: Remove program rules cache [DHIS2-18848] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ServerSideImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_53__create_index_program_rule.sql
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20375
> fix: Remove program rules cache [DHIS2-18848] (2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ServerSideImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_31__create_index_program_rule.sql
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20375
> fix: Remove program rules cache [DHIS2-18848] (2.40)

- .gitignore
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/CsvEventServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/CsvTrackedEntityServiceTest.java
- dhis-2/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/20450
> chore: update google formatter version [2.41]

- .gitignore
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/message/ProgramMessageRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationInstanceRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationTemplateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/PotentialDuplicateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/ChangeLogRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/MappingErrors.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/ImportRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/CsvEventServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/CsvTrackedEntityServiceTest.java
- dhis-2/pom.xml
backport of https://github.com/dhis2/dhis2-core/pull/20450
> chore: update google formatter version [2.42.0]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/configuration/NotifierConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/DefaultNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/FakeRedis.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/InMemoryNotifierTest.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
> fix: read most recent settings in notifier queue worker [DHIS2-19317] (2.42)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataElementControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
port of https://github.com/dhis2/dhis2-core/pull/20373
The specific Dashboard check & tests are not in earlier versions (omitted from this change)
> fix: Correct ignored stats when import validation has errors [DHIS2-15604](2.39)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/oauth2/OAuth2Test.java
Forward port of: https://github.com/dhis2/dhis2-core/pull/20443
> fix: flaky OAuth2 E2E Selenium test

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_45__rename_index_typo_openid_userinfo.sql
Backport: https://github.com/dhis2/dhis2-core/pull/20341
> fix: userinfo table index on openid typo

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserAccountService.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/EmailVerificationTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserAccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
Backport: https://github.com/dhis2/dhis2-core/pull/20382
> feat: automatically verify email when accepting invite

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
Backport: https://github.com/dhis2/dhis2-core/pull/20425
> fix: change wrong 401 response format from html to json

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/aggregated.json
Backport from [master/2.43] (#20501)
> Analytics flaky test 2.42

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/aggregated.json
> fix: Analytics e2e tests

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventQueryParamsTest.java
> chore: improve error message for invalid value type on /tracker/events filter DHIS2-19347 [2.42]

- dhis-2/dhis-web-server/apps-to-bundle.json
This has been approved by RCB
Capture: [DHIS2-19336](https://dhis2.atlassian.net/browse/DHIS2-19336)
[DHIS2-19336]: https://dhis2.atlassian.net/browse/DHIS2-19336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump capture version

- docker-compose.doris.yml
Missing commit for [this](https://github.com/dhis2/dhis2-core/pull/20399) PR.
> chore: remove symlink and mount under different name

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventVisualizationController.java
Backport from https://github.com/dhis2/dhis2-core/pull/20322
> fix: Fix missing keys in parentGraph of EventVisualization [DHIS-19249] [2.42]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/RuleActionEventMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/executor/event/AssignDataValueExecutor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/executor/event/AssignDataValueExecutorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20510
> fix: Assign null to data element representing option set [DHIS2-19396] (2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/RuleActionEventMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/executor/event/AssignDataValueExecutor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/executor/event/AssignDataValueExecutorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20510
> fix: Assign null to data element representing option set [DHIS2-19396] (2.42)

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/EhCacheMetricsConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/HibernateMetricsConfig.java
- dhis-2/dhis-web-api/pom.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PrometheusScrapeEndpointController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcMetricsConfig.java
- dhis-2/pom.xml
* fix: metrics
Backport of: b935a9b07f43610f553233755dac40744eda103e
> Backport: fix: server when starting with metrics enabled  (#20398)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
Just for the sake of completeness, I'm adding the change log test I added in https://github.com/dhis2/dhis2-core/pull/20526
> fix: Test change is logged when DV deleted and created [DHIS2-19092]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/ehcache.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/hibernate-default.properties
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/PostgresDhisConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/PostgresTestConfigOverride.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/junit/MinIOTestExtension.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/postgresTestDhis.conf
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/audit/AuditIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/cache/HibernateQueryCacheTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/RouteControllerTest.java
* fix: migrate old ehcache 2 config to 3
Backport of: 177bf323702fedccaefba2e6d06cc1c1a1546bc1
JIRA: https://dhis2.atlassian.net/browse/DHIS2-19394
Approved by RCB
> Backport: fix: migrate old ehcache 2 config to 3 (#20507)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/20389
> fix: exception when order idesc with none text property (42)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datasummary/DataSummary.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataSummaryControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datasummary/DataSummaryController.java
Small PR which adds enrollments to the data summary API JSON and metrics output.
> feat: Add enrollment count metrics

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistLogic.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryParser.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Filters.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotEmptyOperator.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramControllerIntegrationTest.java
cherry-picked from #20577 and #20585
> feat: filter for empty and not-empty on JSONB column backed collections [DHIS2-19439] (2.42)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
> fix: correctly return apps in the order set in menu management [DHIS2-19124] (master)

- dhis-2/dhis-web-server/apps-to-bundle.json
https://github.com/dhis2/data-visualizer-app/pull/3379
> fix: relative period names (data-visualizer-app#v101.1.3)

- dhis-2/dhis-web-server/apps-to-bundle.json
Bumps settings app to change prefix for setting default app: https://dhis2.atlassian.net/browse/DHIS2-19308
> fix: update-settings-app [DHIS2-19308]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/CategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/util/ColumnNameUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/BaseResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/CategoryResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/util/ColumnNameUtilsTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
Backport from https://github.com/dhis2/dhis2-core/pull/20602
> fix: invalid column names in rs* table and Doris [patch/2.42.0]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/CategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/resourcetable/util/ColumnNameUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/BaseResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/CategoryResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/resourcetable/util/ColumnNameUtilsTest.java
Backport from https://github.com/dhis2/dhis2-core/pull/20602
> fix: invalid column names in rs* table and Doris [2.42]

- dhis-2/dhis-web-server/apps-to-bundle.json
bumps settings app version to pick up changes with default app prefix logic: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-19308
> fix: settings app version [DHIS2-19308]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityAttributeStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/TrackedEntityAggregate.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/TrackedEntityStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeStoreTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20688
> task: Get TEAs by program in tracker aggregate [DHIS2-19482][2.42]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SqlUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/base_data.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/FilterExporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20705
> fix: escape default escape in like based operator input DHIS2-19347 [42]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AggregationLevelsHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/AggregationLevelsHelperTest.java
Backport from https://github.com/dhis2/dhis2-core/pull/20651
> fix: aggregation level query with Doris [DHIS2-19476] (patch/2.42.0)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceCacheTest.java
Reverts dhis2/dhis2-core#20680
> chore: Revert "chore: reenable possible stalling test"

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/AbstractOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/DatastoreQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SqlUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/SqlUtilsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/20672
> fix: /tracker/events?filterAttributes operator in and like based ones DHIS2-19478 [39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/AbstractOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/DatastoreQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SqlUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/SqlUtilsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/20672
> fix: /tracker/events?filterAttributes operator in and like based ones DHIS2-19478 [40]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
- Adding missing value types validations
- Update unit tests
This is the smallest change to fix the bug that can be backported.
> fix: Add missing validations for value type [DHIS2-17679]

- docker-compose.doris.yml
Fix a typo that breaks Apache Doris BE connection to PostgreSQL.
> deploy: typo

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/webmodules/WebModule.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IndexController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
Forward port of: https://github.com/dhis2/dhis2-core/pull/20721
> feat: return bundled apps with new app names (#20721)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20717
> fix: Add missing validations for value type [DHIS2-17679] (2.42)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20717
> fix: Add missing validations for value type [DHIS2-17679] (2.41)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20717
> fix: Add missing validations for value type [DHIS2-17679] (2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHookTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20717
> fix: Add missing validations for value type [DHIS2-17679] (2.39)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/SingleSetupIntegrationTestBase.java
backport of https://github.com/dhis2/dhis2-core/pull/20762
> test: increase timeout for 2 analytics tests [39] (#20762)

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/SingleSetupIntegrationTestBase.java
backport of https://github.com/dhis2/dhis2-core/pull/20762
> test: increase timeout for 2 analytics tests [40] (#20762)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/QueryOperatorTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/FilterParser.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/FilterParserTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidatorTest.java
backport of https://github.com/dhis2/dhis2-core/pull/20437
> fix: validation of filter parser DHIS2-19331 [42]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/StaticContentControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/StaticContentController.java
> fix: Add staticContent path segment back into response URL [DHIS2-19516](2.42)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipItemMapper.java
in all relationship service methods
> chore: use the same relationship item mapper DHIS2-19137

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/StaticContentControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/StaticContentController.java
backport of #20784 
Approved by RCB - see https://dhis2.atlassian.net/browse/DHIS2-19516
> fix: Add staticContent path segment back [DHIS2-19516]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/programindicator/disag/PiDisagInfoInitializer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/programindicator/disag/PiDisagQueryGenerator.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-test-e2e/src/test/resources/junit-platform.properties
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/disag/AbstractPiDisagTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/disag/PiDisagDataHandlerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/disag/PiDisagInfoInitializerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/disag/PiDisagQueryGeneratorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/disag/PiDisagRecommendedDimensionsTest.java
* fix: PI Disag non-DataValueSet [DHIS2-18745]
* fix: rename PIDisag -> PiDisag test files
* fix: rename PIDisag -> PiDisag test files
* fix: rename PIDisag -> PiDisag test files
* set flyway.skip_migration=false
* SonarCloud fix
* SonarCloud fix
* fix: Broken analytics tests
---------
(cherry picked from commit 2bf4966a50046edf0beeae0e3072772c15c5e91e)
[DHIS2-18745]: https://dhis2.atlassian.net/browse/DHIS2-18745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: PI Disag non-DataValueSet [DHIS2-18745] (#20785)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IndexController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/GlobalShellFilter.java
Backport of #20822 
[DHIS2-19527](https://dhis2.atlassian.net/browse/DHIS2-19527)
NOT YET APPROVED BY RCB
[DHIS2-19527]: https://dhis2.atlassian.net/browse/DHIS2-19527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: support any installed or bundled app as start module (DHIS2-19527) [42.0]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspConstants.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/BundledAppStorageService.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/filter/RequestIdentifierFilterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/AppOverrideFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/CspFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/RequestIdentifierFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
Backport of: https://github.com/dhis2/dhis2-core/pull/20706
(cherry picked from commit db35c09ed8e904ff9648f449eda723ca74470249)
APPROVED BY RCB!
> fix: prevent session creation before login (#20706)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/TrackedEntityAggregate.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
* and remove some unused fields from `EventQueryParams`: they were never written to so we remove them and the SQL snippets they would add to the event query
> chore: only fetch TEA if returned to user on /trackedEntities DHIS2-19137

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/EmailVerificationTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IndexController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/GlobalShellFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
This PR reverts changes introduced in DHIS2-19508 while also fixing redirection issues in the index controller and related components. 
* Revert default start module name pattern, aka. dashboard
* Updating saved request matching patterns
* Adjusting redirection URLs index controllers
> chore: revert DHIS2-19508 and fix redirection in index controller

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/AggregateDataExchangeJobParameters.java
- dhis-2/dhis-services/dhis-service-data-exchange/src/main/java/org/hisp/dhis/dataexchange/aggregate/AggregateDataExchangeJob.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
- dhis-2/dhis-test-e2e/src/test/resources/metadata/adex-metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerIntegrationTest.java
> fix: Aggregate Data Exchange job creator as job executor [DHIS2-18324](2.42)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
Backport: https://github.com/dhis2/dhis2-core/pull/20809
> fix: make the hasCurrentUser more strict

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/EmailVerificationTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IndexController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/GlobalShellFilter.java
Forwardport of: https://github.com/dhis2/dhis2-core/pull/20824
> fix: support any installed or bundled app as start module 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspConstants.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/EmailVerificationTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/filter/RequestIdentifierFilterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/AppOverrideFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/CspFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/RequestIdentifierFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
> fix: prevent session creation before login

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
Backport from master [2.43] (#20856)
> fix: Prevent NPE [DHIS2-19548] (#20856)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/DefaultNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notifier.java
cherry-pick backport of #20923
> fix: system settings notifierGistOverview method naming [DHIS2-19128] (2.42)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
A recently-added E2E test was added for the aggregate data exchange job in #20850.
It failed (once) on the GH CI with the message:
```json
{
"message": "Job is already running.",
"errorCode": "E1004"
}
```
This seems like it could be a rare occurrence where the scheduler has already started the job before we try to execute it manually.
This is still fine as we still should be able to check for a valid result once the job is completed.
This change allows the test to be a little bit more resilient when this scenario occurs. If the job is already running, we just continue with the rest of the test, otherwise fail the test.
If the test becomes a bit of a nuisance, it can be reviewed for removal.
> chore: Make e2e job test more resilient

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datavalueset/DataValueSetTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
> fix: Ensure exporting DataValueSet xml zip and gzip format results in valid zip file [DHIS2-11925](2.42)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datavalueset/DataValueSetTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
> fix: Ensure exporting DataValueSet xml zip and gzip format results in valid zip file [DHIS2-11925](2.41)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datavalueset/DataValueSetTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
> fix: Ensure exporting DataValueSet xml zip and gzip format results in valid zip file [DHIS2-11925](2.39)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/ExportControllerPaginationTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20943
> fix: Fix pagination for TE enrolled in more programs [DHIS2-19595] (2.42)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerPostgresTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/20943
> fix: Fix pagination for TE enrolled in more programs [DHIS2-19595] (2.41)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
Backport of https://github.com/dhis2/dhis2-core/pull/20943
> fix: Fix pagination for TE enrolled in more programs [DHIS2-19595](2.40)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
> fix: null boolean value normalisation [DHIS2-19597] (2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistPagerControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
> fix: Gist API link URLs [DHIS2-19531] (2.42)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/orgunit/OrgUnitMergeValidator.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/orgunit/OrgUnitMergeValidatorTest.java
https://github.com/dhis2/dhis2-core/pull/20438
> backport: fix(merge-orgunits): remove two sources restriction

- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/tomcat/Main.java
Adds an environment variable to the Main.class embedded Tomcat starter class, "SERVER_SERVLET_CONTEXT_PATH" that sets the Tomcat's context path when starting the server.
The context path value must start with a "/".
> feat: add context path as parameter to embedded Tomcat

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DefaultCompleteDataSetRegistrationService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataSetCompletionControllerTest.java
> fix: Check compulsory data when completing a DataSet [DHIS2-18295](2.42)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DefaultCompleteDataSetRegistrationService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataSetCompletionControllerTest.java
port of #21008 
1 test omitted as not suitable for backport (batch handler flush issue). Manually tested and works as expected.
> fix: Check compulsory data when completing a DataSet [DHIS2-18295](2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DefaultCompleteDataSetRegistrationService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataSetCompletionControllerTest.java
port of #21008 
1 test omitted as not suitable for backport (batch handler flush issue). Manually tested and works as expected.
> fix: Check compulsory data when completing a DataSet [DHIS2-18295](2.40)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DefaultCompleteDataSetRegistrationService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataSetCompletionControllerTest.java
port of https://github.com/dhis2/dhis2-core/pull/21008
1 test omitted as not suitable for backport (batch handler flush issue). Manually tested and works as expected.
> fix: Check compulsory data when completing a DataSet [DHIS2-18295](2.39)

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/LoginFallbackServlet.java
Backport of: https://github.com/dhis2/dhis2-core/pull/21009
(cherry picked from commit 5be6e5bafd053c0d5b17e633a7b702084d9bcaae)
> fix: login fallback page (#21009)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramCategoryOptionMapping.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/DisplayNameUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHookTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-sql/pom.xml
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/AbstractSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/PostgreSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/SqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilderTest.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/PostgreSqlBuilderTest.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/test/e2e/actions/metadata/ProgramActions.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/test/e2e/helpers/JsonObjectBuilder.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/ValidationHelper.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsPiDisaggregationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/disag/PiDisagQueryGeneratorTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryControllerTest.java
* fix: PI Disaggregation scaling bugs [DHIS2-19663]
* fix: tests [DHIS2-19663]
* remove olor=auto
---------
(cherry picked from commit 9e5150adc5ddcac56b4714a2f32a709fd9298f49)
[DHIS2-19663]: https://dhis2.atlassian.net/browse/DHIS2-19663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19663]: https://dhis2.atlassian.net/browse/DHIS2-19663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: PI Disaggregation scaling bugs [DHIS2-19663] (#21040)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/ownership/TrackerOwnershipManagerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/21088
> fix: Check temp access on events when TE provided [DHIS2-19684][2.42]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-services/dhis-service-data-exchange/src/main/java/org/hisp/dhis/dataexchange/aggregate/AggregateDataExchangeJob.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
- dhis-2/dhis-test-e2e/src/test/resources/metadata/adex-metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerIntegrationTest.java
> fix: Aggregate Data Exchange job creator as job executor [DHIS2-18324](2.41)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_46__create_lastupdated_index_event_and_enrollment.sql
> Perf/data summary db indices 2.42

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/aggregated.json
**Backport from master [2.43]** (#21061)
> fix: Table layout headers order [DHIS2-19028]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/datasource/DatabasePoolUtils.java
https://github.com/dhis2/dhis2-core/pull/20904
> backport: feat: Enable HikariCP database pool leak detection

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataset/notifications/DataSetNotificationServiceTest.java
Backport of: https://github.com/dhis2/dhis2-core/pull/21122
> fix: don't send notification emails to disabled users

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/email/EmailService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserDetails.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/email/DefaultEmailService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataset/notifications/DataSetNotificationServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/scheduling/HtmlPushAnalyticsJob.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
(cherry picked from commit d794f6b980822375dcf3aa0f1176ae19ee0267c7)
> fix: don't send notification emails to disabled users (#21122)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/period/RelativePeriodsTest.java
**Backport from master [2.43]** (#21119)
> fix: Missing periods + clean-up [DHIS2-19548]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerIntegrationTest.java
> fix: Keep executedBy value for isValidUserRequiredForJob jobs [DHIS2-18324](2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/period/RelativePeriodsTest.java
**Backport from master [2.43]** (#21119)
> fix: Missing periods + clean-up [DHIS2-19548] (#21155)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/document/Document.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/orgunitprofile/impl/OrgUnitProfileDeletionHandler.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/FileResourceStream.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AuditController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DocumentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExternalFileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/icon/IconController.java
Centralize file resource error messages which were replicated across many classes.
> chore: Centralize error message

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/orgunits/orgunits_excess_group_memberships.yaml
https://github.com/dhis2/dhis2-core/pull/21211
> backport: fix: Improve output of integrity check for OUGS with multiple groups

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
Backport https://dhis2.atlassian.net/browse/DHIS2-19685
> fix: (2.39.10) ensure program rule notifications correctly resolve dataElement [DHIS2-19685]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/BundledAppStorageService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
This fixes an issue where installed apps manifest translations were not loaded on discovery (only on install) - this brings it inline with bundled apps.
> fix: discover installed apps manifest translations

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/PasswordValidationError.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/PasswordValidationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/RecaptchaResponse.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/RestoreType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserAccountExpiryInfo.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserOrgUnitProperty.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserSetting.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserSettingStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserSettingsService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/ObjectUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/ObjectUtilsTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultPasswordValidationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DigitPatternValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/LowerCasePatternValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/PasswordDictionaryValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/PasswordHistoryValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/PasswordLengthValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/SpecialCharacterValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UpperCasePatternValidationRule.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/validation/DefaultSchemaValidatorTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/DhisConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/datasource/ReadOnlyDataSourceManager.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/init/AnalyticsDatabaseInit.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilder.java
A bit of maintenance in user related code. Adds util methods for empty/null checks. Replaces repetitive code with Lombok. Adds Javadocs.
> refactor: Use util methods for null checks

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ResourceTableControllerTest.java
Backport from master/2.43 (#21357)
> test: Remove redundant test

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/statistics/jdbc/JdbcStatisticsProvider.java
https://github.com/dhis2/dhis2-core/pull/21411
> backport: fix: Fix negative data statistics (2.42)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/statistics/jdbc/JdbcStatisticsProvider.java
https://github.com/dhis2/dhis2-core/pull/21411
> backport: fix: Fix negative data statistics (2.41)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/statistics/jdbc/JdbcStatisticsProvider.java
https://github.com/dhis2/dhis2-core/pull/21411
> backport: fix: Fix negative data statistics (2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/metadata/export/MetadataExportWithDependenciesTest.java
backport https://github.com/dhis2/dhis2-core/pull/21345
> fix: remove programTEA and programStageDE from root level in metadataexport

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/AnalyticsStringUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/EventAnalyticsColumn.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerDorisTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
Backport of: 
- f4b6e0e9f0309173b773bdb80f1887b06e55825f
- https://github.com/dhis2/dhis2-core/pull/21520
> feat: use Centroid function for DE/TEI OU Values [DHIS2-19681]

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/config/ServiceConfig.java
Backport: https://github.com/dhis2/dhis2-core/pull/21442
> fix: remove duplicate flag of denmark

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldPathHelperTest.java
> fix: Field filter - handle nested field exclusion [DHIS2-19883](2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserDetailsImpl.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/oauth2/OAuth2Test.java
Re-enabled test and fixes serialization issue in the previous failing tests.
> fix disabled oauth2 test

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/SystemUser.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserDetails.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserDetailsImpl.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcUser.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/PostgresDhisConfigurationProvider.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/SessionController.java
* chore: use userdetails in user query params
Backport of: 973f89dd1e1ab1d76eb011667b15f10c6e16551d
> chore: use UserDetails in user query params

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/Preheat.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/PreheatIdentifier.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/PreheatParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserDetails.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundle.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ExpressionDimensionItemObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OrganisationUnitObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DashboardCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleHooksTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHookTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceProgramTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/TestSetup.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TestSetup.java
* chore: use userdetails in preheat
(cherry picked from commit 29431056af1902259051ea168dac2903129e7a90)
> chore: use userdetails in preheat (#21440)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/CategoryComboObjectBundleHook.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerIntegrationTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryComboController.java
> feat: Prevent updating CategoryCombo's categories when assoc. data exists [DHIS2-19942](2.41)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/DataItemQueryController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/DataItemServiceFacade.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/ResponseHandler.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/helper/FilteringHelper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/DataItemQueryControllerTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/DataItemServiceFacadeTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/ResponseHandlerTest.java
Backport: https://github.com/dhis2/dhis2-core/pull/21515
(cherry picked from commit cdba84d3147aacb051051e16e92518b0bfb0c131)
> chore: refactor and migrate from User to UserDetails (#21515)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/security/ApiTokenControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ApiTokenController.java
Add HEAD HTTP method as available HTTP method for personal access tokens.
> feat: add HEAD method to allowed PAT http methods

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultAnalyticalObjectImportHandler.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/VisualizationWithExpressionDimensionTest.java
- dhis-2/dhis-test-e2e/src/test/resources/metadata/metadata_viz_expr_dim_item.json
- dhis-2/dhis-test-e2e/src/test/resources/metadata/metadata_viz_expr_ref.json
> fix: Handle Visualization expression dimension item on import [DHIS2-19725](2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultAnalyticalObjectImportHandler.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/VisualizationWithExpressionDimensionTest.java
- dhis-2/dhis-test-e2e/src/test/resources/metadata/metadata_viz_expr_dim_item.json
- dhis-2/dhis-test-e2e/src/test/resources/metadata/metadata_viz_expr_ref.json
> fix: Handle Visualization expression dimension item on import [DHIS2-19725](2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/SystemUpdateNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
* fix: don't send notification emails to disabled users
(cherry picked from commit e469f4b3d7b5c25cc2973c2c3633155960c4f26f)
> fix: don't send notification to disabled users (#21144)

- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/DefaultPdfDataEntryFormService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/PdfDataEntryFormUtil.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/PdfFieldCell.java
- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-web-api/pom.xml
- dhis-2/pom.xml
* fix: upgrade itext to openpdf
(cherry picked from commit c4a2bdf151ef1fcf39a2f50041098f31116c8bce)
> fix: upgrade itext to openpdf (#21262)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataExportServiceTest.java
> fix: metadata export of visualization relative periods [DHIS2-19584]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserRole.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
Backport of: 39dc97d22b4acda5e16ff9a74b25f162f019f27d
> fix: don't serialize to full user objects from UserRole members (#21598)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserRole.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
Backport of: 39dc97d22b4acda5e16ff9a74b25f162f019f27d
> fix: don't serialize to full user objects from UserRole's members (#21598)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OrganisationUnitControllerTest.java
> fix: don't serialize full user objects from OrgUnit's users

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/programs/tracker_geometry_invalid_srid.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityTrackerEntitiesInvalidSRIDControllerTest.java
backport https://dhis2.atlassian.net/browse/DHIS2-12547
> fix: (2.41) Add integrity check to detect geometry columns with incorrect SRID (not 4326) [DHIS2-12547]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
* fix: program notification recipients disabled check
Backport of: fc7168c03fff1bcc441dc6a339b1b345cf694a81
> fix: program notification recipients disabled check (#21665)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/job/TrackerRuleEngineThread.java
Backport of https://github.com/dhis2/dhis2-core/pull/21728
> chore: Move rule engine notification logs to debug level (2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/executor/ValidationExecutor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/executor/ValidationRuleAction.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/executor/event/ValidationExecutorTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/21760
> fix: Accept null message in ValidationEffect [DHIS2-20037](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/executor/ValidationExecutor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/executor/ValidationRuleAction.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/executor/event/ValidationExecutorTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/21760
> fix: Accept null message in ValidationEffect [DHIS2-20037](2.41)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_21__split_event_table.sql
A single event only allows 2 statuses, `ACTIVE` and `COMPLETED`.
- Migrate status in `singleevent` table:
- Events with not allowed status and without value in `completeddate` column are set to `ACTIVE`
- Events with not allowed status and with a value in `completeddate` column are set to `COMPLETED`
- Fail migration if there are null values in `occurreddate` column in `singleevent` table and provide info to the user on how to solve the issue.
- Create `inconsistentevent` table only if needed.
***We will create integrity checks in previous versions to look for single events without occurred data***
>  fix: Migrate singleevent status

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/EnrollmentQueryHelper.java
Backport from master [2.43] (#21571)
> fix: Skip filters as columns

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/HibernateTrackedEntityProgramOwnerStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/OwnershipCacheUtils.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityCacheTest.java
backport of https://github.com/dhis2/dhis2-core/pull/21812
> fix: Invalidate program owner cache [DHIS2-18338][2.42]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/programs/program_stages_no_programs.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityProgramStagesNoPrograms.java
Backport of https://github.com/dhis2/dhis2-core/pull/21280
> feat: Program stages with no programs integrity check (2.42)

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/programs/single_events_null_occurred_date.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegritySingleEventNullOccurredDateTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/21801
> chore: Add integrity check for null occurred date for single events [DHIS2-19614](2.41)

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonAttributeValueBinaryType.java
Avoids nullpointer vulnerability when serializing JSON attribute values.
> fix: Safely serialize JSON map [DHIS2-18253] [41]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManagerTest.java
Backport from https://github.com/dhis2/dhis2-core/pull/21898
Note that the Unit Test has to be changed in order to accommodate the target class difference.
> fix: specify columns for AnalyticsTable constructor [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
Back-port from https://github.com/dhis2/dhis2-core/pull/21875
> fix: Enrollment Aggregate Analytics default period fix [2.42]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/HibernateJobConfigurationStore.java
port of https://github.com/dhis2/dhis2-core/pull/21962
> perf: Improve HouseKeepingJob update resource table [DHIS2-20143](2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
backport of https://github.com/dhis2/dhis2-core/pull/21934
> fix: Check write permission to TET when importing TE [DHIS2-20132][2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
backport of https://github.com/dhis2/dhis2-core/pull/21934
> fix: Check write permission to TET when importing TE [DHIS2-20132][2.40]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResource.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceCleanUpJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/hibernate/HibernateFileResourceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/fileresource/FileResourceStoreTest.java
backport of https://github.com/dhis2/dhis2-core/pull/21979
> fix: Update FileResourceCleanupJob to delete job data resources [DHIS2-20157](2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationRule.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/notification/ValidationNotificationTemplate.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ValidationNotificationTemplateControllerTest.java
port of https://github.com/dhis2/dhis2-core/pull/21935
> fix: Patching ValidationNotificationTemplate should succeed [DHIS2-20099](2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/event/SecurityOwnershipValidatorTest.java
backport of https://github.com/dhis2/dhis2-core/pull/22016
> fix: Validate payload org unit when update single event [DHIS2-20173][2.41]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
Backport from master [2.43] (#21693)
> fix: Event query with dimensions of type coordinate [DHIS2-19989]

- dhis-2/dhis-test-web-api/src/test/resources/contracts/README.md
Add the contracts directory which will store the API contracts
> chore: Add API contracts resource directory

- .github/workflows/check-formatting.yml
- dhis-2/dhis-test-performance/src/test/org/hisp/dhis/test/tracker/TrackerTest.java
First performance test covering the single events scenario.
> perf: Create single event scenario

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/BaseAnalyticalObjectTest.java
Backport from [master/2.43] (#22055)
> fix: NPE in relative periods handling

- dhis-2/dhis-test-e2e/docker-compose.e2e.yml
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-e2e/src/main/resources/log4j2.xml
- dhis-2/dhis-test-e2e/src/main/resources/reportportal.properties
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/ApiTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/BaseE2ETest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- jenkinsfiles/dev
- jenkinsfiles/stable
as we do not use report portal anymore
> chore: remove report portal dependency

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/events/ImageFileSavedEvent.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultImageProcessingService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceEventListener.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/fileresource/FileResourceEventListenerTest.java
> fix: FileResource - save extra image files in async process [DHIS2-20269](2.41)

- dhis-2/dhis-test-e2e/docker-compose.e2e.yml
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-e2e/src/main/resources/log4j2.xml
- dhis-2/dhis-test-e2e/src/main/resources/reportportal.properties
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/ApiTest.java
- jenkinsfiles/dev
- jenkinsfiles/stable
as we do not use report portal anymore
> chore: remove report portal dependency [40]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/events/ImageFileSavedEvent.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultImageProcessingService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceEventListener.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/fileresource/FileResourceEventListenerTest.java
port of #22155 
approved by RCB (via Stian)
> perf: FileResource - create extra images in async flow [DHIS2-20269](2.41.6)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
See https://dhis2.atlassian.net/issues/DHIS2-19438
> fix: add programStage param to EventQueryParams getKey
