dhis2/dhis2-core

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
The handling of repeatable stages, data type organization unit coordinate, and organization unit contains a bug. The row context handler is generating invalid SQL statements.
> fix: SQL error in enrollment request when using E2E - Coordinate and E2E - Organisation Unit [2.42-DHIS2-17139]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TransactionMode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TransactionType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sqlview/SqlViewStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/DefaultSqlViewService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStoreTest.java
When DHIS2 is set up using a Postgres read replica DB, any SQL view (which has an underlying write) will be retrieved using the `readOnlyJdbcTemplate`, which causes an error `cannot execute ... in a read-only transaction`.
The method `HibernateSqlViewStore#populateSqlViewGrid` always only ever used the `readOnlyJdbcTemplate`. This never causes any issues when DHIS2 is set up to only use a primary Postgres DB (no read replica DBs) as the `readOnlyJdbcTemplate` falls back to using the normal `jdbcTemplate` when no read replica DBs are found at startup.
If a read replica DB is detected at startup, then the `readOnlyJdbcTemplate` would be used and would target the read replica DB, wherever it is used in the code.
This is only an issue when sql views perform writes underneath (e.g. a select …
> fix: Use appropriate JDBC template with read replicas [DHIS2-17062]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/icon/IconControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/icon/IconController.java
Set the `content-length` via the `contentLength` stored for the `FileResource` in the DB. We were using the `FileResourceService` to fetch the `contentLength` and the actual content. If the icons are stored in some cloud storage this would mean making an extra network request to get something we already have.
* Add test for downloading an icon to the IconControllerTest
* Cleanup IconControllerTest a bit: remove unneeded calls to `fmt.Sprintf` when making requests, improve helper for icon creation, fail instead of printing the stack trace
> chore: set content-length via FileResource in DB DHIS2-16872

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerByIdTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerUnitTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerUnitTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/FileResourceRequestHandler.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java
Set headers as in https://github.com/dhis2/dhis2-core/blob/b759d3993995aa5456d7ac52ba261921909b20b5/dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/HeaderUtils.java#L33 which file/image download endpoints do:
https://github.com/search?q=repo%3Adhis2%2Fdhis2-core%20%20%20%20%20%20%20%20%20response%2C%20dhisConfig.getProperty(ConfigurationKey.CSP_HEADER_VALUE))%3B&type=code
Ideally we would do this in a central place. So no one would ever forget. We plan a refactoring of file resource download code for version 42. We might be able to extract the repeated logic you can see in the above search to a central handler like `FileResourceRequestHandler`. `FileResourceRequestHandler` is currently used only inside of tracker but its logic is not tracker specific.
> fix: set CSP header with script-src in tracker file/image endpoints DHIS2-17154

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsUtilsTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/MathUtils.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
**_[Backport from master/2.42]_** (#16777)
The issue was pinpointed to the event report date in the repeatable stage. The capture app allowed users to add new events in the repeatable stage. The report date (found in the occurreddate column of the event table in the tracker database) is treated as a date without a time section. When analytics queries for repeatable stage events using an position index, the occurreddate is crucial for ensuring the correct outcome, as it serves as the sorting criteria. Sorting on non-unique data can yield inconsistent results. This is the scenario described in the ticket. Report dates of events within the repeatable stage are not unique, and sorting may yield different outcomes.
The skipRounding and rounding on two decimals were fixed/introduced as well.
> fix: Backport skipRounding/rounding in enrollments [DHIS2-17027]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsPeriodCriteriaUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsPeriodCriteriaUtilsTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/EnrollmentQueryTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
BACKPORT
The analytics API supports the period dimension, and the related query parameter is mandatory. New feature implementation removes this restriction for the enrollment/query entry point. When the period dimension is not included in the parameter set, the default rules are applied, wherein the start date and end date are equal to the maximum interval used for analytics export.
> fix: Analytics enrollment endpoint: remove the use of default period for empty enrollment/incident date[2.41-DHIS2-17103-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementWithLegendSetCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementWithStaticValuesCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/DataElementConditionTest.java
When a Data Value has a LegendSet, the condition needs to consider the range of values in the legend. This PR aims to implement this behavior
> fix: DataValues with legendset are now filtered properly in TE analytics [DHIS2-17145]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementWithLegendSetCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementWithStaticValuesCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/DataElementConditionTest.java
* fix: DataValues with legendset are now filtered properly in TE analytics [DHIS2-17145]
* fix: restrictedImports [DHIS2-17145]
(cherry picked from commit c903108b8e0a9152ec9ac4532e27a037e1853113)
[DHIS2-17145]: https://dhis2.atlassian.net/browse/DHIS2-17145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17145]: https://dhis2.atlassian.net/browse/DHIS2-17145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [2.41] fix: DataValues with legendset are now filtered properly in TE analytics [DHIS2-17145] (#17020)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobSchedulerLoopService.java
When the housekeeping job would take longer than 20sec it would potentially be cancelled (as it is wrongly identified as stale /dead; phantom `RUNNING`) as part of resetting it to a `SCHEDULED` state.
When this happens there also is a chance that more than one worker thread runs the housekeeping job as the a new one is started 40 sec after the previous one. If that is still running after 40sec there would be 2, after 80sec there would be 3 and so on.
This could happen now when default icon insert was particularly slow due to network reasons. Each icon would take 500ms in the test setup causing the insert to run for several minutes. When this spawned more than one housekeeping job the jobs would run concurrently and compete with each other when it comes to inserting default icons making …
> fix: avoid resetting housekeeping job when it is alive

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
The outliers pre-calculation query performance  were suboptimal. The optimization should significantly improve the population of data values (local database tests show a ratio of 16 seconds to 8 seconds in favor of the refactored query)
> fix: Analytics outliers: table export seems slower than expected [DHIS2-17181]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/HibernateJobConfigurationStore.java
All jobs (including run once) should be reset but run once jobs move to `enabled=false` which then also transitions their `jobstatus` to `DISABLED` (another housekeeping transition). From there they are cleared after 1 day. 
Scenario 1 - scheduled job:
* create a analytics table job that would run daily 1h ago from now
* run it manually
* stop the server while it is running
* start the server again
* wait 10 minutes
* check that the job is back to scheduled but did not run again
Scenario 2 - run once job:
* goto the data administration app
* select analytics tables
* click execute
* stop the server while it is running
* start the server again
* wait 10 minutes
* check the job created from clicking the button is now disabled
> fix: reset all jobs stuck in running

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/AuthConfigProviderConfiguration.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
Removes the non-public URL request matchers for the service-worker.js and .map files.
> chore: make serviceworker.js non-public

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/model/AnalyticsTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/model/Table.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManagerTest.java
- Currently if User run Analytic with number of years != All then below error will be thrown
```
drop table if exists "analytics_2023" cascade; alter table "analytics_2023_temp" rename to "analytics_2023";
alter table "analytics_2023_temp" no inherit "analytics_temp"; alter table "analytics_2023_temp" inherit "analytics";
ERROR: relation "analytics_2023_temp" does not exist
```
- Issue is the table name in database is changed but the name of the Table object is not changed in method `AbstractJdbcTableManager.swapTable()`. Hence, the method `swapInheritance` takes in the old table name.
> fix: AbstractJdbcTableManager.swapTable  does not swap object Table name

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobSchedulerService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobSchedulingControllerTest.java
The operation end in a 500 as a `Map.of()` does not support the `clear()` operation. To avoid this the errors are now removed in an immutable fashion using `withoutErrors()` wither.
> fix: job progress without errors as immutable wither

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/ValueTypeMapping.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TeiQuery2AutoTest.java
**Backport**
CPL does not support the 'dhis' data format 'mmmm-YY-DDT.hh.mm.ss'. The fix improves the parsing of this format.
> fix: Analytics TE query API - error comparing datetime [2.41-DHIS2-17182-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
**Backport**
The outliers pre-calculation query performance were suboptimal. The optimization should significantly improve the population of data values (local database tests show a ratio of 16 seconds to 8 seconds in favor of the refactored query)
> fix: Analytics outliers: table export seems slower than expected [2.41-DHIS2-17181-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobSchedulerService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobSchedulingControllerTest.java
cherry-pick backport of #17056
> fix: job progress without errors as immutable wither (2.41)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionParam.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/CommonQueryRequestMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/SuffixedRenderableDataValue.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/DataElementQueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/GridAdaptorTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/handler/SchemeIdResponseMapperTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/OrganisationUnitConditionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/StatusConditionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/TeiAttributeConditionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/TeiSqlQueryTest.java
* feat: the name of orgunit is exported into the json for DE of type orgunit [DHIS2-17146]
* fix: propagate idScheme up to DimensionParam [DHIS2-17146]
(cherry picked from commit 9eddf04ff051936aa50800173701188410850fd3)
[DHIS2-17146]: https://dhis2.atlassian.net/browse/DHIS2-17146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17146]: https://dhis2.atlassian.net/browse/DHIS2-17146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: allow displaying and sorting by OU name on TE data elements [DHIS2-17146] (#17031)[2.41]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionIdentifier.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/RenderableDataValue.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/DataElementQueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/DataElementConditionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/RenderableDataValueTest.java
When a Data Value specifies the legendSet in the query, the backend will now return the label of the legend rather than the value.
> fix: Data Values will return the legend label when LegendSet is specified [DHIS2-17145]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/querybuilder/DataElementQueryBuilder.java
In TE Analytics, When a DV of type ORG_UNIT is passed, if no idScheme is specified, then idScheme.name is used
> fix: OrgUnits Data Values defaults to idScheme.name [DHIS2-17146]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/InQueryFilterTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery3AutoTest.java
**Backport**
There was an issue with IN:NV (seeking genuine null values within the data elements, program indicators, etc.). When utilizing a nested SQL statement to retrieve the value and compare it with null, the null representation becomes ambiguous. It can signify either an empty SQL cursor or a genuine null value. To address this concern, the "where" clause of the SQL statement needed enhancement, utilizing the "exists" SQL function. By combining equality to null with the "exists" function, the origin of the value can be accurately determined.
> fix:Filter using "IN:NV", in analytics enrollments query should not return "ND" values[2.40-DHIS2-16418-backport]

- .tx/config
- CONTRIBUTING.md
- README.md
- jib.yaml
There are some leftover references to the old `/dhis-2/dhis-web` path (from https://github.com/dhis2/dhis2-core/pull/17040), some of them in the `jib.yaml` file, which breaks building a docker image with the Jib CLI.
> chore: remove all references to old dhis-web path

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobSchedulerLoopService.java
cherry-pick backport of #17038
RCB approved
> fix: avoid resetting housekeeping job when it is alive (2.41.0)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/pom.xml
Upgrade rule-engine version to last stable snapshot and fix build issue using last stable snapshot of expression-parser from rule-engine library.
This PR is also fixing some program-rule-related enums that were broken by last change in rule-engine library.
> chore: Upgrade rule-engine version

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
https://dhis2.atlassian.net/browse/DHIS2-13014
Currently, if we make a rest request to a tracker endpoint that supports multiple content types, such as events or tracked entities, the request doesn't default to JSON when it comes from a browser with a generic path like `/tracker/events`. It appears to consume the CSV endpoint, which is totally random; it could also be the gzip or zip endpoint. The need for defaulting to JSON is that other endpoints like CSV do not support pagination and could potentially run heavy requests to the server.
This issue happens because a browser uses an `Accept` header related to HTML and a null `Content-Type`.
We can see this using the `@RequestHeader("Accept")` in an endpoint. Here is an example of the `Accept` header from Chrome or Brave:
``` …
```
> fix: Tracker - Default Json response to browser only html requests [DHIS2-13014]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
Ideally it is not possible to enable a job configuration that cannot run due to lack of schedule setup.
This is the state a job is in after no longer being part of a queue.
Added a integration test scenario
* create 2 jobs
* make a queue with the 2 jobs
* delete the queue again
* verify the job(s) cannot be enabled 
* edit the job and set a schedule
* verify the job can be enabled again
> fix: reject job config enable when no schedule is set [DHIS2-16408]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
cherry-pick backport of #17119
> fix: reject job config enable when no schedule is set [DHIS2-16408] (2.41)

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/jclouds/JCloudsStore.java
- dhis-2/pom.xml
as described in https://jclouds.apache.org/reference/logging/
Adding
```xml
<Logger name="org.jclouds" level="debug" additivity="false">
<AppenderRef ref="console"/>
</Logger>
<Logger name="jclouds.wire" level="debug" additivity="false">
<AppenderRef ref="console"/>
</Logger>
<Logger name="jclouds.headers" level="debug" additivity="false">
<AppenderRef ref="console"/>
</Logger>
```
to a log4j2 config like https://github.com/dhis2/dhis2-core/blob/d3eb8fec4b6fe10d554ca88d53f00fea29e8cc27/docker/log4j2.xml#L20 would show what requests jclouds is making.
You then see logs like
```
DEBUG org.jclouds.rest.internal.InvokeHttpMethod [main] >> invoking CreateBucket
DEBUG org.jclouds.http.internal.JavaUrlHttpCommandExecutorService [main] Sending request -229704820: PUT http://minio:9000/dhis2 …
```
> chore: allow users to enable jclouds logging DHIS2-17232

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
As mentioned in the meeting I opted not to write a test for this fix as it feels like a bad time trade-off.
It is unlikely this will break (be changed/removed) but an integration test would require much effort in relation and a unit test would only be possible with mock setup increasing the maintenance burden for little benefit.
> fix: resolve objects by ID identifier (UID alias) [DHIS2-17186]

- docker-compose.yml
We updated the Postgres version in
https://github.com/dhis2/dhis2-core/pull/16879/files\#diff-9dc8ad3056e3d02e42c728bd90bf151ecc5a4add6fb497b2618386613b3a2459R21
due to a flyway update. We forgot to also update it in the `docker-compose.yml` which some use for development and others to get started with DHIS2.
Aligns with
https://github.com/dhis2/dhis2-core/blob/991eab1f76641a8f6398c911c39039646688a392/dhis-2/dhis-test-e2e/docker-compose.yml#L23
Note we are using the https://github.com/baosystems/docker-postgis instead of the official image to get ARM64 support. See https://github.com/postgis/docker-postgis/issues/216
> ci(deps): use same DB version in docker-compose.yml as in other scenarios

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/SystemUser.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/user/SystemUserTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/DefaultMessageService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/message/DefaultMessageServiceTest.java
The `SystemUser` (which implements `UserDetails`) currently returns `false` from these methods:
- `public boolean hasAnyAuthority(Collection<String> auths)`
- `public boolean isAuthorized(String auth)`
The `SystemUser` should always have authorization by default. This change corrects this.
Return `true` from both methods
- 2 unit tests added for `SystemUser`
- 1 unit test added for `DefaultMessageService#hasAccessToManageFeedbackMessages ` which actually does call the `isAuthorized` method for `SuperUser` (most checks usually make a call to `isSuper` but this one doesn't so it's a perfect test for this new behaviour)
Can't really manually test this as it's more of an internal behaviour (can't trigger as a normal user).
We're aware of no instances where this has actually caused any issues, …
> fix: System user should be authorized by default

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/SystemUser.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/user/SystemUserTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/message/DefaultMessageServiceTest.java
backport of #17156 
`SystemUser` introduced in `2.41` so not required to backport to any other previous versions.
> fix: System user should have auth by default

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcUser.java
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserRoleTest.java
Adds a missing implementation of the `isAuthorized` and `hasAnyAuthority` on the OidcUser.
UserRoleTest#testOidcUserIsAuthorizedCheck
> fix: make oidcuser use parent isAuthorized method

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/HibernateJobConfigurationStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/cache/HibernateQueryCacheTest.java
https://dhis2.atlassian.net/browse/DHIS2-16934
- `HouseKeepingJob` use `org.hibernate.query.NativeQuery` to update/delete records in `jobconfiguration` table.
- That causes Hibernate to invalidate all caches in `SessionFactory`. Which in result trigger multiple `select` queries to database when lazy collection are loaded. This is the default Hibernate behavior, more details [here](https://vladmihalcea.com/how-does-hibernate-query-cache-work/rl).
- The job runs every 20s, so basically there are no cache entry available for whole application.
- In order to avoid cache from being invalidated we must use method `NativeQuery.addSynchronizedEntityClass(class)`. Hibernate will then only invalidate cached entries of specified class.
- Added new integration test in `HibernateQueryCacheTest`
- Look …
> fix: Hibernate nativeQuery clear all Hibernate caches[DHIS2-16934]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery3AutoTest.java
There is the problem with sorting of the repeatable stages. The issue was pinpointed to the event report date in the repeatable stage. The capture app allowed users to add new events in the repeatable stage. The report date (found in the executiondate column of the event table in the tracker database) is treated as a date without a time section. When analytics queries for repeatable stage events using an position index, the executiondate is crucial for ensuring the correct outcome, as it serves as the sorting criteria. Sorting on non-unique data can yield inconsistent results. This is the scenario described in the ticket. Report dates of events within the repeatable stage are not unique, and sorting may yield different outcomes.
> fix: Investigate the reason of differences in events x enrollments in analytics query[2.40-DHIS2-16227]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
> fix: Analytics events query API: 500 error when dimension is not present in the query[2.42-DHIS2-17231]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
> fix: Analytics events query API: 500 error when dimension is not present in the query[2.39-DHIS2-17231-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
> fix:Analytics events query API: 500 error when dimension is not present in the query[2.40-DHIS2-17231-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapView.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_1__Add_name_column_into_mapview.sql
Adds a `name` column to the MapView entity/table.
Currently, it does not exist, and the `name` is evaluated based on some logic around `uid`.
> feat: Support name in MapView [DHIS2-16088]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IndexController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/system/SystemUpdateNotifyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/XmlPathMappingJackson2XmlHttpMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
Fixes an issue with redirection and Tomcat, causing the lack of a `/` in the end of the base mapping to redirect to `/api/resources`.
This was caused by the `IndexController` not being updated after the migration from `/api` to `/` root servlet mapping, and the manual `RedirectRootServlet` not working similar on Tomcat as on Jetty.
> chore: fix redirection issue with / and non slash root paths

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MapControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
Returns the regular `ok()`, for the PUT method, instead of `null`.
> fix: Return ok() in Maps PUT method [DHIS2-15978]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/ProgramStageValidationStrategyTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipMapper.java
https://dhis2.atlassian.net/browse/DHIS2-17090
1) Apply the configurable relationship constraints for a relationship type. As discussed with @JoakimSM, the UI only shows program attributes as a constraint.
In the code, this is done in the mapper as an @AfterMapping operation. This way, it is more maintainable and follows the model logic directly in the mapper. The alternative to this is to seek every place where we fetch relationships (directly or indirectly) and apply the filter. 
2) Apply the logic done by @muilpp for the `canRead` method of tracked entity in the `DefaultTrackerAccessManager`. This is now valid for every check in place and consistent across the tracker ( therefore, also for relationships ).
@muilpp `canRead` for enrollment and event still validates the tracked entity. …
> fix: tracker/relationships emits inaccessible program attributes  [ Dhis2-17090 ]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryValidator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
The issue was pinpointed through query parameter validation, specifically within the period dimension. When the parameters are found to be invalid, the error message sent to the client should appear as follows:
{
"message": "Start and end dates or at least one period must be specified",
"errorCode": "E7205"
}
The instantiation of the error message was incorrectly implemented, resulting in certain special cases overwriting existing instances of the error message. This issue has now been rectified.
> fix: Bad SQL syntax exception in /analytics/Event/aggregate[2.42-DHIS2-16235]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryValidator.java
**Backport**
The issue was pinpointed through query parameter validation, specifically within the period dimension. When the parameters are found to be invalid, the error message sent to the client should appear as follows:
{
"message": "Start and end dates or at least one period must be specified",
"errorCode": "E7205"
}
The instantiation of the error message was incorrectly implemented, resulting in certain special cases overwriting existing instances of the error message. This issue has now been rectified.
> fix: Bad SQL syntax exception in /analytics/Event/aggregate[2.40-DHIS2-16235-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryValidator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
**Backport**
The issue was pinpointed through query parameter validation, specifically within the period dimension. When the parameters are found to be invalid, the error message sent to the client should appear as follows:
{
"message": "Start and end dates or at least one period must be specified",
"errorCode": "E7205"
}
The instantiation of the error message was incorrectly implemented, resulting in certain special cases overwriting existing instances of the error message. This issue has now been rectified.
> fix: Bad SQL syntax exception in /analytics/Event/aggregate[2.42-DHIS2-16235-backport]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
> perf: Fix load programs query in old tracker [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
> perf: Fix load programs query in old tracker [2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/importer/context/ProgramSupplier.java
> perf: Fix load programs query in old tracker [2.41]

- dhis-2/pom.xml
Use `@RequiresAuthority` instead
- discussed & agreed in backend meeting on 2024-04-18
> chore: Ban Spring PreAuthorize annotation

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-acl/pom.xml
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/AclService.java
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/InternalHibernateGenericStoreImpl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserGroupService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserGroupController.java
- dhis-2/dhis-web-embedded-jetty/pom.xml
- Sharing ACL check requires database query which joins User and UserGroup table. 
- In 2.40 and previous versions, the result of that query was cached for performance purpose.
- However the cache has been removed in 2.41 as a part for the CurrentUserService refactoring.
- Add back the cache, make sure to invalidate it when userGroup or User is updated.
- We already have many sharing ACL test in `SharingControllerTest` and `AbstractCrudControllerTest`.
> fix: add back CurrentUserGroupInfo cache

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
Fixes bug, only allowing one concurrent user session.
Caused by new login controller not setting the max session per user from the dhis.conf
N/A now, requires an E2E test.
[DHIS2-17225](https://github.com/dhis2/dhis2-core/pull/17225)
[DHIS2-17225]: https://dhis2.atlassian.net/browse/DHIS2-17225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: only one concurrent user allowed

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-acl/pom.xml
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/AclService.java
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/InternalHibernateGenericStoreImpl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserGroupService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserGroupController.java
- dhis-2/dhis-web-embedded-jetty/pom.xml
backport https://github.com/dhis2/dhis2-core/pull/17183
https://dhis2.atlassian.net/browse/DHIS2-16934
- Sharing ACL check requires database query which joins User and UserGroup table.
- In 2.40 and previous versions, the result of that query was cached for performance purpose.
- However the cache has been removed in 2.41 as a part for the CurrentUserService refactoring.
- Add back the cache, make sure to invalidate it when userGroup or User is updated.
- We already have many sharing ACL test in SharingControllerTest and AbstractCrudControllerTest.
> fix: add back CurrentUserGroupInfo cache (41.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/EnrollmentsAnalyticsQueryCriteriaTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteriaTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
> Analytics events query API: 500 error when dimension is not present in the query[2.40-DHIS2-17231_2-backport] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/PeriodCriteriaUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/EnrollmentsAnalyticsQueryCriteriaTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteriaTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/PeriodCriteriaUtilsTest.java
> Analytics events query API: 500 error when dimension is not present in the query[2.41-DHIS2-17231_2-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/tracker/imports/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/Users.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/enrollments_te_te-data.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/te-transferred-data-delete.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/te-transferred-data-update.json
In the importer we need to validate access to Tracked Entity the same way we are now doing in the exporter.
We have 3 different cases in the importer:
- CREATE: Check capture scope of the user using registration unit
- UPDATE or DELETE: Check if the user has access to any TE/program pair, by first matching by the owner, or the registering org unit if no owner is found
> fix: Fix TE ownership validation in Tracker importer [DHIS2-17251]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryTest.java
The `measureCriteria` parameter was not working for reporting rates (`dimension=dx:PLq9sJluXvc.REPORTING_RATE`).
This PR fixes this issue. Now it's possible to use the `measureCriteria` with its respective operands, like: `EQ`, `GT`, etc.
During my tests, I found an additional scenario not supported by the operands: numbers with decimal digits. This issue was also fixed as part of these changes.
I also added new e2e tests covering many situations, including decimals, negative numbers, and rounding scenarios.
> fix: Min/max limits in analytics rep. rates [DHIS2-15892]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/importer/context/ProgramSupplier.java
> perf: Fix load programs query in old tracker [2.41.0]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
> perf: Fix load programs query in old tracker [2.40.3.1]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRendererTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery3AutoTest.java
At the request of the reporter, the dates (for example, enrollment and incident date) should be linked by an "AND" relation. This was implemented by changing the previous "OR" relation to an "AND" one.
> fix: Analytics enrollments query API using OR instead of AND[2.42-DHIS2-17419]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRendererTest.java
**Backport**
At the request of the reporter, the dates (for example, enrollment and incident date) should be linked by an "AND" relation. This was implemented by changing the previous "OR" relation to an "AND" one.
> fix: Analytics enrollments query API using OR instead of AND[2.39-DHIS2-17149-backport]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJobParametersTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJobTest.java
The `lastExecutedStatus` shows as `FAILED` even after a successful `MetadataSyncJob` run.
- only in versions `39` & `40`
The `MetadataSyncJob` has several processes and some of them are not started and completed (some of them only start and run a stage). The `AbstractSchedulingManager` sees the job run as a failure if all of the `JobProgress` processes are not in a `SUCCESS` state.
Start and complete these 2 processes in the `MetadataSyncJob` so a successful job run is seen as `COMPLETED`:
1. set up metadata job process
2. metadata sync process
Automated tests added confirming the correct state for a successful `MetadataSyncJob`
Unit tests added for the newly-extracted method `AbstractSchedulingManager#checkWasSuccessfulRun`
Tested through Instance Manager using [this …
> fix: Fix Metadata Sync job lastExecutedStatus [DHIS2-17292]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
When requesting multiple tracked entities without specifying a program, we need to validate whether the user has access to any TE/program combination. If they have access to at least one, the user will be able to see the tracked entity attributes.
To do that, I refactored the query that fetches tracked entities, so now I join the program table and then, one by one, I retrieve the owner of each entity to further narrow it down depending on the requested parameters. If there's at least one result, it means the user has access to see the attributes of that particular TE.
> fix: Validate user TE access [DHIS2-17236]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/trackedentity/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/enrollments_te_enrollments-data_2.json
In the importer, we need to validate access to the Tracked Entity in the same way we are now doing in the exporter.
We have 3 different cases in the importer:
- CREATE: Check the capture scope of the user using the registration unit and validate Tracked Entity Type write access
- UPDATE: Check if the user has access to any TE/program pair, by first matching by the owner, or the registering org unit if no owner is found
- DELETE: Check the capture scope of the user using the registration unit and check if the user has access to any TE/program pair, by first matching by the owner, or the registering org unit if no owner is found
For CREATE and DELETE, we need to check that the registration org unit is in the capture scope.
For UPDATE, we are not changing the current behavior but we will …
> fix: Fix TE ACL to check capture scope on register OU [DHIS2-17251]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-17303
- `api/visualizations/{uid}` api return object with all relativePeriods set to `false` although database has `true` value.
- The Visualization entity retrieved from database with a hibernate lazy proxy of `RelativePeriods` object. The proxy has all incorrect values of `periods`.  When entity is deserialized by Jackson, the proxy doesn't trigger database query, instead it just return a default `RelativePeriods` object which has all boolean values default to `false`.
- Adding `Hibernate5Module` to JacksonObjectMapper could solve the issue, however it is a risky solution as there could be side effect because objectMapper is used in many other places.
- I couldn't find out why this suddenly become a problem in 2.41, not sure which code …
> fix: visualizations api returns incorrect  relativePeriods

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/tracker/imports/validation/ValidationCode.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/RelationshipMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/TrackedEntityMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/RelationshipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preheat/supplier/EnrollmentSupplierTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/RelationshipImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/RelationshipSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/Users.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/relationship_parent_child.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/relationship_siblings.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/te_relationship.json
Relationships were not validating write access for `from` and `to` items.
Now when importing a relationship, the rules are the following:
- Create bidirectional relationship: `from` and `to` must have write access
- Create unidirectional relationship: `from` must have write access and `to` must have write access
- Delete bidirectional relationship: `from` and `to` must have write access
- Delete unidirectional relationship: `from` must have write access `to`doesn't need any access
Relationships cannot be updated.
As the `SecurityOwnershipValidator` is accessing the `from` and `to` items, it must be moved after the constraint validator that checks the existence and validity of items.
> fix: Add write access validation for relationships in Tracker Importer [DHIS2-17252]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/ProgramStageValidationStrategyTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/security/TrackerAccessManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RelationshipMapper.java
backport of https://github.com/dhis2/dhis2-core/pull/17281
@muilpp i am not doing a clean-up of `getTrackedEntityInstance` here so if you are backporting that, any TODO or comments related to `initializeTrackedEntityOrgUnitParents` can be discarded
> fix: tracker/relationships emits inaccessible program attributes [ Dhis2-17090 ] [2.40] 

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-17303
- `api/visualizations/{uid}` api return object with all relativePeriods set to `false` although database has `true` value.
- The Visualization entity retrieved from database with a hibernate lazy proxy of `RelativePeriods` object. The proxy has all incorrect values of `periods`.  When entity is deserialized by Jackson, the proxy doesn't trigger database query, instead it just return a default `RelativePeriods` object which has all boolean values default to `false`.
- Adding `Hibernate5Module` to JacksonObjectMapper could solve the issue, however it is a risky solution as there could be side effect because objectMapper is used in many other places.
- I couldn't find out why this suddenly become a problem in 2.41, not sure which code …
> fix: visualizations api returns incorrect  relativePeriods[17303](41.0)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
There is a bug in the JdbcCompletnessTableManager. The hasUpdatedLatestData method is failing to replace placeholders in the sql statement, which is obstructing the successful execution of continuous analytics job.
> fix: Bug in continuous analytics job [2.42-DHIS2-17339]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/action/validation/HideOptionProgramRuleActionValidator.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/ProgramRuleActionValidatorTest.java
https://dhis2.atlassian.net/issues/BETA-165
- Currently the backend validation throws error if the `HIDEOPTION`  programRule contains reference to a `DataElement`.  This is incorrect, as it can contains : DataElement, Option, TrackedEntityAttribute.
- Update the `HideOptionProgramRuleActionValidator` to reflect correct validation rule.
> fix: validation error when HideOptionProgramRuleAction contain DataElement[BETA-165]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryLimitTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackedEntityInstanceControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
"backport" of https://github.com/dhis2/dhis2-core/pull/17343#issue-2281622652
> fix: Update validation when no program specified [DHIS2-17236][2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
Comparing the object type of the tracked entity with that of the program's tracked entity type object isn't always reliable. I've observed instances where they differ; for example, one may have a description set while the other doesn't. Using their UID for comparison should be enough to determine their equality.
> fix: Compare TET by UID [DHIS2-17251]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/TrackedEntityImportValidationTest.java
When importing a new enrollment with the CREATE strategy, it's possible that there's no owner of the enrollment TE/program pair if the TE is also imported at the same time. Previously, we were not handling this case correctly because we were not validating the ownership. 
With this fix, we will retrieve the registering unit and validate whether the user has access to it.
> fix: Validate unenrolled TE before importing [DHIS2-17280]

- .github/dependabot.yml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
- dhis-2/pom.xml
https://dhis2.atlassian.net/browse/DHIS2-17378
- The library `jasperreport` should be kept at version 6.20.0, however `dependabot` has updated it which cause a 500 error for the Report App. https://github.com/dhis2/dhis2-core/pull/17036
- I have added `net.sf.jasperreports:jasperreports` to dependabot ignore list but `net.sf.jasperreports:jasperreports-fonts` is missing.
- Add `net.sf.jasperreports:jasperreports-fonts` to ignore list.
> fix: Report App got 500 error due to jasperreport lib upgraded

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/imports/tei/TeiImportTests.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/tesWithEnrollmentsEventsAndRelationships.json
TeiImportTests fails as its trying to create a relationship that TrackerExportTest already created. Tracker e2e tests do not clean up after themselves. We will fix that issue later.
Decouple TeiImportTests from TrackerExportTest by creating different TEs.
> test: tracker e2e test fails due to interdependence DHIS2-16564

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/TeiListGrid.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/dimension/DimensionIdentifier.java
This pull request addresses a problem where numeric codes associated with data element option sets were being rounded in the response. The fix ensures an accurate representation of numeric codes, enhancing data integrity.
> fix: skip rounding when dimension has option set [DHIS2-17257]

- .github/dependabot.yml
- Follow up on https://github.com/dhis2/dhis2-core/pull/17382, ignore ` jasperreports-fonts` in 2.41 and older versions
> ci: dependabot.yml to ignore jasperreports-fonts

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
Previously, when exporting a data visualizer table containing columns with integer values, the output would display numbers ending with a comma or dot. This issue arose from the usage of a custom number format in Excel, which works well for numbers with decimals but caused the issue.
This PR introduces a specific formatting mechanism for integer values so that the decimal part is skipped when the type of the numeric value is an integer.
> fix: custom format for integer types [DHIS2-15841]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
See [DHIS2-16349](https://dhis2.atlassian.net/browse/DHIS2-16349).
The problem was:
- Enrollments don't use attribute option combos. "Attribute" Category columns (and Category Option Group Set columns) are not present in the analytics enrollment tables
- When an analytics WebAPI query is processed for a dimension-restricted user, `DefaultAnalyticsSecurityManager.applyDimensionConstraints` adds the user's dimension constraints as filters if the dimensions aren't already specified (Category constraints and/or Category Option Group Set constraints). Note that these constraints are added to the entire WebAPI query which could possibly contain many different items (indicators, data elements, event PIs, enrollment PIs, etc.) This is efficient because the constrains are added once for the entire …
> fix: Enrollment dim. restriction SQL [DHIS2-16349]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/Authorities.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/ImpersonateUserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ImpersonateUserController.java
Fixes previous PR making the impersonateExit endpoint too strict. This change make sure the impersonated user is able to exit, without having to have either ALL or F_IMPERSONATE_USER authority. A special F_PREVIOUS_IMPERSONATOR_AUTHORITY is added to the impersonated user, making it possible to exit the impersonating mode.
ImpersonateUserControllerTest#testImpersonateUserOKAndExit
> fix: change exit roles on impersonation

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
* fix: Enrollment dim. restriction SQL [DHIS2-16349] (#17393)
* fix: Enrollment dim. restriction SQL [DHIS2-16349]
(cherry picked from commit 232cd91a0006b48c3b518c25b5bd326b7264ac06)
* spotless fix
* Replace missing isAttributeCategory method
* fix testEnrollmentWithCategoryDimensionRestriction
(cherry picked from commit 05d6b7be828fb324df2bd5f43a65afc3673987a3)
[DHIS2-16349]: https://dhis2.atlassian.net/browse/DHIS2-16349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-16349]: https://dhis2.atlassian.net/browse/DHIS2-16349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Enrollment dim. restriction SQL [DHIS2-16349] (#17393) (#17411)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
I assume the "mi" value was meant to match "admin" and that some other test leaves another user with that work in the name behind. 
Since the next assert tests the same scenario just with a more unique value "urnameuserA" matching "SurnameuserA" which is the value for the test user created in the setup I just removed the flaky assert.
> fix: flaky gist filter test

- .github/dependabot.yml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
- dhis-2/pom.xml
- Backport https://github.com/dhis2/dhis2-core/pull/17382
- Changes in dependabot.yml is removed because only the config in master branch is utilized.
> fix: Report App got 500 error due to jasperreport lib upgraded[DHIS2-17378](41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageDataElementService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageDataElementStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTempOwnershipAuditService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTempOwnershipAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramStageDataElementService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramTempOwnershipAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramStageDataElementStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramTempOwnershipAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preheat/supplier/strategy/TrackerEntityStrategyTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/relationship/LinkValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EventSecurityImportValidationTest.java
follow up after https://github.com/dhis2/dhis2-core/pull/17368
We have deleted the old tracker controllers, sync and dxf2 services and stores. This PR now removes the unused code that was previously used by the tracker dxf2 services. This mostly means interfaces in the module dhis-api and implementations in the module dhis-service-core.
> chore: cleanup dhis-api/dhis-service-core DHIS2-16564

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParser.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/test/java/org/hisp/dhis/fieldfiltering/FieldFilterParserTest.java
The issue in the parser is that `]` did not exit the parsing loop that was reading the transformation.
It seemed reasonable that a transformation name would end in a similar way when another level of block nesting opened so I added a corresponding condition to the existing case which appears to solve the issue.
With the way the parser works it is hard to tell if it is correct or where cases are missing. 
I kept the fix minimal for less impact for the release and easier backport but long term we should rewrite the parser using PEG technique (simple version with Java methods).
A test case was added for the field filter that failed according to the reported ticket.
* try `/api/dataElements?fields=id,categoryCombo[categoryOptionCombos~size],displayName`
* try …
> fix: field filter parsing exits block [DHIS2-17391]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/AclEventExporterTest.java
The methods used to synchronize metadata are not using the event mapper, thus are skipping all validations.
Since they are using the old API, I added the necessary params to keep them working.
> fix: Add org unit mode to event async method  [DHIS2-17296][2.41]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/scheduling/HtmlPushAnalyticsJob.java
As requested by @HendrikThePendric this PR adds the users DB locale to the URL used to call the push analytics service.
Precondition is that the URL template contains a placeholder `{locale}` similar to the already existing placeholders `{dashboard}` and `{username}`. If no such placeholder is added no locale information is inserted.
> feat: send user locale in push analytics service call [DHIS2-17408]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityProgramOwnerService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityProgramOwnerStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityChangeLogService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityProgramOwnerService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityProgramOwnerStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityQueryTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityFilterServiceTest.java
Removed unused tracker tracked entity code in module dhis-api/dhis-service-core.
Some of the code was only used in tests which is why you see me removing tests.
Many fields in `TrackedEntityQueryParams` were never used. This means that in all the client code you need to think of the field being initialized to their default value like `null` for the `lastUpdatedStartDate` or `false` for a `boolean`.
Also fixed many linting issues like typos, missing javadoc descriptions, ...
> chore: remove unused tracker tracked entity code DHIS2-16564

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/CommonQueryRequestMapper.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
Period cache seems to not improve performance noticeably, especially since its use shouldn't be that extensive.
Moreover, from time to time, issues arise because of this period cache, due to the lack of the dateField as a member of the cache key and the difficulty of adding it properly.
Some internal test showed no noticeable performance degradation after this cache got removed.
> fix: period cache removed [DHIS2-17405]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJobTest.java
port of https://github.com/dhis2/dhis2-core/pull/17275 (fix for `v39`) with less changes as Job Scheduling was overhauled in `v41`
- same principle applies, start & complete processes instead of stages for jobs to show as `COMPLETED`
> fix: lastExecuted status should be COMPLETED [DHIS2-17292]

- dhis-2/dhis-test-e2e/src/main/resources/junit-platform.properties
- dhis-2/dhis-test-e2e/src/test/resources/junit-platform.properties
```
May 16, 2024 1:02:32 PM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
WARNING: Discovered 2 'junit-platform.properties' configuration files in the classpath; only the first will be used.
```
moving the config from src/test/resources to src/main/resources as this is where all other test related config is
> test: fix junit warning about 2 properties files

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserAccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/UserAccountController.java
https://dhis2.atlassian.net/browse/DHIS2-17317
- The endpoint `/api/forgotPassword` in `UserAccountController` use the `HttpRequest.hostName` to build the email message.  It is vulnerable to host header injection
- Replace request host header with the config `server.base.url` in dhis.conf file.
- Added a test to `UserAccountControllerTest`
- Manual test can be done by 
1. Set up email server in DHIS2 instance
2. Send a recover password request as below
```
curl -X POST http://localhost:8080/api/auth/forgotPassword -H "Host: attacker.com"  -H "Content-Type: application/json" -d '{"emailOrUsername":"admin"}'
```
3. Verify the sent email content, make sure the url "attacker.com" is not included.
Screenshot
> fix: use serverBaseUrl for recovery email[DHIS2-17317]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/grid/GridUtilsTest.java
https://dhis2.atlassian.net/browse/DHIS2-17415
- In `GridUtils.toXls` should only create new `Sheet` if couldn't find a sheet with same sheet name in `WorkBook`
> fix: GridUtils throw duplicate sheet error [17415]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOrgUnitTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/model/AnalyticsTableColumn.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/AnalyticsTableServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/model/AnalyticsTableColumnTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/model/AnalyticsTablePartitionTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/model/AnalyticsTableTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsIndexHelperTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsTableAsserter.java
**Backport**
The AnalyticsTableColumn class currently has nine overloaded constructors, making maintenance challenging and costly. To improve this, we decided to implement the Builder pattern.
> AnalyticsTableColumn refactoring[2.41-DHIS2-17422-backport]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Same as we did for relationships with TEs, we also don't want to raise an exception in case on of the items of a relationship is an event which is not accessible to the logged in user.
https://dhis2.atlassian.net/browse/DHIS2-16460
> fix: Validate events in relationships [DHIS2-16460]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionScheduleMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
Some classes in `dhis-service-program-rule` were declaring `EnrollmentService` and `EventService` and never using them
> fix: Remove unused tracker services from program-rule module

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/model/AnalyticsColumnType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/model/AnalyticsTableColumn.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsIndexHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/model/Index.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/PostgreSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/db/sql/PostgreSqlBuilderTest.java
**Backport**
In PostgreSQL, creating an index in descending sort order can improve the performance of queries that request results in descending order. In analytics, non-default sort orders are often used to find the last value by date of incident, enrollment, etc. By default, indexes are created with ascending (ASC) sort order. This means that if there is an ORDER BY DESC clause in use, the ascending index can be ignored, resulting in poor performance.
> Analytics events/enrollments/trackedEntities query APIs: boost sort by dates index performance [2.41-DHIS2-17409-backport]

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/hibernate/HibernateDataIntegrityStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateAnalyticalObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datadimensionitem/hibernate/HibernateDataDimensionItemStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/hibernate/HibernateLockExceptionStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/hibernate/HibernateSectionStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/HibernateDatastoreStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/hibernate/HibernateFileResourceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/hibernate/HibernateMessageConversationStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/note/hibernate/HibernateNoteStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationTemplateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/HibernateJobConfigurationStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityChangeLogStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/userdatastore/hibernate/HibernateUserDatastoreStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java
When mixing hibernate DB usage with native SQL (via hibernate) the native queries have to specify which tables they are working with using `addSynchronizedEntityClass` to avoid unwanted flushes or updates being triggered.
As far as I understand it `addSynchronizedEntityClass` needs to be called with each table type that is involved in the native SQL. Since there (often) is no corresponding class for mapping tables I would assume these are implicitly included when they are mapped as a collection.
There are now two new methods
* `nativeSynchronizedQuery(String)`
* `nativeSynchronizedTypedQuery(String)`
Both add the object type of the store, but the typed one also maps the result to the store object type.
There were only two usages of the existing `getSqlQuery` method which I moved to …
> fix: use addSynchronizedEntityClass when using native SQL via hibernate

- CONTRIBUTING.md
- README.md
- jib.yaml
Not sure if the wording in the CONTRIBUTING.md doc is relevant at this point.
> chore: remove references to old dhis-web-portal path

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTest.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/teis/teisWithEnrollmentsAndEvents.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatesBindingTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentImportRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventImportRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityImportRequestParamsMapperTest.java
- Make all relevant date parameters use new `StartDateTime` and `EndDateTime` types
- Format dates in queries using `yyyy-MM-dd HH:mm:ss.SSS` format including milliseconds
- Modified a simple e2e test to prove that the `EndDateTime` default time is set to end of the day
**Next PR**
- Update OpenApi
> fix: Use new start and end date types in tracker exporter [DHIS2-16019]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/MetadataItem.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryTest.java
Some metadata items were returned with ValueType NUMBER, even though they were of TEXT type.
This happened because the default ValueType, for some reason, has been NUMBER by default AND we did not have specific handling for `ProgramTrackedEntityAttributeDimensionItem`.
A new condition for `ProgramTrackedEntityAttributeDimensionItem` was added, so we get the respective ValuType from this object, where applicable. The default type will remain NUMBER, to not affect existing features. I extracted the logic into a smaller method to make it more readable and isolated.
A new e2e test to cover this scenario was added.
> fix: ValueType in metadata [DHIS2-15194]

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
Bumping Capture app version to a version that includes fixes approved by RCB.
> chore: bump bundled version of Capture app

- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/tomcat/Main.java
- When run tomcat using `org.hisp.dhis.web.tomcat.Main` , the api request `api/dataElements?fields=id,categoryCombo[cateogoryOptionCombo~size],displayName` got below error
```
HTTP Status 400 
java.lang.IllegalArgumentException: Invalid character found in the request target [/api/dataElements?fields=id,categoryCombo[cateogoryOptionCombo~size],displayName ]. The valid characters are defined in RFC 7230 and RFC 3986
org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:482)
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
```
- Currently there is no test use this tomcat.
- Below is screenshot after fix successfully in local.
> fix: add relaxedQueryChars to tomcat Main class

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
https://dhis2.atlassian.net/issues/DHIS2-17449
- For api request `api/dataElements?fields=id,code,name&filter=dataElementGroups.id:in:[h9cuJOkOwY2]&rootJunction=OR` the filter is included in the memory query, which leads to a database query with empty `Predicate`.
-  In database query, the `rootJunction=OR` will be converted to an empty `disjunction`. [As per java doc](https://docs.oracle.com/javaee/6/api/javax/persistence/criteria/CriteriaBuilder.html#disjunction()), the empty disjunction will return false, hence, query returns empty result.
- If the database query has empty `criterions` then just build a default `conjunction`.
- Can manual test by access `api/dataElements?fields=id,code,name&filter=dataElementGroups.id:in:[h9cuJOkOwY2]&rootJunction=OR`. The response …
> fix: rootJunction OR return empty result

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Previously, when requesting a single TE in the context of a program, we returned all TEA regardless of the specific program. With this PR, we will now return only the attributes of the specified program + the attributes of the tracked entity type. If no program is specified, only attributes of that particular TET will be returned.
Ticket: https://dhis2.atlassian.net/browse/DHIS2-14300
> fix: Return TEA from specified program only [DHIS2-14300]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
backport
[DHIS2-15898](https://dhis2.atlassian.net/browse/DHIS2-15898)
[DHIS2-15898]: https://dhis2.atlassian.net/browse/DHIS2-15898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.38) Ordering when using psi.attributeOptionCombo[DHIS2-15898]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
Backport 
[DHIS2-15898](https://dhis2.atlassian.net/browse/DHIS2-15898)
[DHIS2-15898]: https://dhis2.atlassian.net/browse/DHIS2-15898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.39) Ordering when using psi.attributeOptionCombo[DHIS2-15898]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Previously, when requesting a single TE in the context of a program, we returned all TE enrollments regardless of the specific program. With this PR, we will now return only the enrollments for the specified program. If no program is specified, all enrollments will be returned.
Ticket: https://dhis2.atlassian.net/browse/DHIS2-14300
> fix: Return enrollments from specified program only [DHIS2-14300]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/orgunit/handler/TrackerOrgUnitMergeHandlerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SchemaBasedControllerTest.java
Rename remaining programInstance/PROGRAM_INSTANCE/pi(s) to enrollment/en.
There are still a few usages of programInstance in analytics code which the analytics team will handle. There are also some deprecated parameters for which we need to create separate issues so our clients move over to the new names first before we remove the deprecated parameters.
> chore: rename pi to enrollment/en DHIS2-16563

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/DateAndField.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/DateField.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/RelativePeriods.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
This PR adds a `DateAndField` class to bring `dateField` around along with the date when building periods cache and checking cache keys.
This is needed to properly use the `PERIOD_CACHE`, which would otherwise sometimes randomly fail.
This fixes the usage of relative periods under some circumstances (see https://dhis2.atlassian.net/browse/DHIS2-17405 for details).
> fix: added DateAndField to track dateField where necessary [DHIS2-17405]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdSchemes.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetQueryParams.java
Old tracker endpoints `/trackedEntities`, `/enrollments`, `/events`, `/relationships` have been removed. Tracker data does not support idSchemes other than UID.
> chore: remove unused tracker data idSchemes DHIS2-16564

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/TrackedEntityAggregate.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
https://dhis2.atlassian.net/browse/DHIS2-16446
Add to the join with the enrollment the program ID if it is present in the request, so we exclude from ordering the enrollments that are not required
There might be more cleanup to do, so I've created another issue https://dhis2.atlassian.net/browse/DHIS2-17447
> fix: /tracker/trackedEntites?order=enrolledAt returns wrong order

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/hibernate/HibernateCategoryOptionComboStore.java
Static analysis found the `if` condition for `counter` is always `true`. We concluded that the code missed increasing the counter and that we would still need this so the inc is added now.
> fix: only flush every 400 items when providing default COC names

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
Issue originally found during QA testing of metadata sync job. The following exception was being thrown:
```
PersistentObjectException: detached entity passed to persist: org.hisp.dhis.organisationunit.OrganisationUnitGroupSetDimension 
```
All `BaseAnalyticalObject`s have the property:
```
protected List<OrganisationUnitGroupSetDimension> organisationUnitGroupSetDimensions;
```
The root cause was eventually found after many dead ends. It was observed during debugging that `EventChart` objects were triggering the issue after a session flush. This seemed strange though, as the database being used did not have any `EventChart` data in it. It turned out that the central instance was saving a metadata snapshot which included `EventChart`s and `EventReport`s.
The reason for this was because …
> fix: Remove EventChart and EventReport schemas from metadata export flow [BETA-177]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/17516
> fix: /tracker/trackedEntites?order=enrolledAt returns wrong order [2.39] 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
backport of https://github.com/dhis2/dhis2-core/pull/17516
> fix: /tracker/trackedEntites?order=enrolledAt returns wrong order [2.40] 

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/resources/openapi/EnrollmentsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/EventsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapperTest.java
Add
- `/tracker/enrollment?status`
- `/tracker/trackedEntities?enrollmentStatus`
- `/tracker/events?enrollmentStatus`
in favor of the `programStatus` request parameter which we deprecate. Note that we choose `/tracker/enrollments?status` as the query parameter filters on a field on the enrollment which is called `status` in the JSON. We also follow the same approach with the `event.status` which has query parameter `/tracker/events?status`.
* for some reason the test classes had `Import` in their name 🤷🏻 
* remove odd newlines and trailing spaces from OpenAPI markdown. format with textwidth=100
> chore: Add query parameter enrollmentStatus to /tracker in favor of programStatus DHIS2-17484

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OpenApi.java
- dhis-2/dhis-web-api/pom.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiDescriptions.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiExtractor.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiIntegrator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/DirectType.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/EndDateTime.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StartDateTime.java
A feature that was missed when introducing `@OpenApi.Description` was to make use of such annotations on types to propagate the description to all type usages. 
This is mostly relevant for parameters where the type used to model the parameter might be helpful to give information on the parameter. 
With annotation based description being generally available a new difficulty arises from two possible sources, annotations and markdown files. A parameter might have a description originating from the parameter type as well as a description on the specific parameter originating from a markdown file. Ideally these can be combined. However, this is challenging as the options are limited by the fact that descriptions from annotations become the initial description value when building the `Api` …
> feat: OpenAPI descriptions from annotations and markdown files

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
Reverts dhis2/dhis2-core#17618, as `2.38` is out of support now.
> Revert "backport: ci: send all Jenkins build failure notifications to backend channel [2.38]"

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OpenApi.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiDescriptions.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiExtractor.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/DirectType.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/EndDateTime.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StartDateTime.java
After today's meeting I got an idea on how to avoid the need of knowing or using the placeholder `{md}` directly and instead have additional properties in the `@OpenApi.Description` annotation.
The key is that internally this still uses the placeholder but users don't have to use it to compose the text from multiple sources. Instead, by default, the text is always composed from all possible sources:
1. annotation on a specific element (e.g. a parameter)
2. annotation on the type of the element
3. a markdown file 
User then can opt-out of this automatic composition using two new properties in the `@OpenApi.Description` annotation:
* `ignoreTypeDescription`
* `ignoreFileDescription` 
As this internally is still based on the placeholder to combine annotation based and file based sources …
> feat: OpenAPI ignore type and file description sources

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
This PR will prevent an index from being created on the jsonb column `eventdatavalues`, in the TE event table.
> fix: skip index for eventdatavalues [DHIS2-17508]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
This PR will prevent an index from being created on the jsonb column `eventdatavalues`, in the TE event table.
> fix: skip index for eventdatavalues [DHIS2-17508] [2.41]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/scheduling/HtmlPushAnalyticsJob.java
DB locale can be undefined, therefore we fallback to the UI locale with has a default so it should always be defined.
Giving the DB locale a default might have unintended side effects so this more local solution seems the better way to make sure that we always send a locale.
> fix: push analytics job locale fallback to UI locale [DHIS2-17408]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/EventImportTest.java
https://dhis2.atlassian.net/browse/DHIS2-17129
In the old tracker, it is possible to update the data element value using the put request for _/events/{uid}/{dataElementUid}_ and send a payload with the new data values, for example:
```json
{
"event": "ce2BE0tNVYJ",
"dataValues": [
{
"dataElement": "aRz66hGQRnQ",
"value": "no",
"providedElsewhere": false
}
]
}
```
The endpoint had a concurrent issue fixed in https://github.com/dhis2/dhis2-core/pull/15793. That PR replaces the whole event's record update with an SQL statement using a Postgres native function to update only the data elements in the `eventdatavalues` column, so we no longer have concurrency issues.
However, the SQL statement happens to use single quotes to delimit the data element's JSON replacement, and if the data element …
> fix: TEXT and LONG_TEXT with single quote (') [DHIS2-17129] [2.41]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataSetMetadataControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/dataset/data_element_and_dataset_with_catcombo.json
- dhis-2/dhis-test-web-api/src/test/resources/dataset/data_element_with_catcombo.json
- dhis-2/dhis-test-web-api/src/test/resources/dataset/dataset_and_data_element_with_no_catcombo.json
- dhis-2/dhis-test-web-api/src/test/resources/dataset/dataset_with_catcombo.json
port of #17665 
`v41` already contains the fix from #15847 
`v40` and `v39` will have the tests and the fix backported.
> fix: Add tests confirming default cat combo behavior [DHIS2-16129]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/ide-entity-mapping.xml
- file added purely to provide a link for the IDE to see Entities
- provides value when writing HQL
- Entity detection
- Entity property auto completion
- warning for incorrect Entity / property name
This file is usually called `hibernate.cfg.xml` if the datasource if wired and started from xml config. We do not do this. We load the datastore config programmatically.
This file should not interfere with our datasource config as it is not referenced anywhere and the attributes required to actually start up a session factory are excluded from the file.
[Guide](https://github.com/dhis2/wow-backend/blob/master/guides/idea_hql_autodetection.md) for local setup
> chore: Add entity mapping xml for HQL Entity detection in IDE

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datastore/DatastoreKeysTest.java
Update tests to assert on value being contained in collection as opposed to expecting specific element order (not guaranteed)
> chore: Update flaky datastore tests

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRule.hbm.xml
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionKey.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionScheduleMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
We were retrieving ProgramRules and filtering the linked ProgramRuleActions based on the type needed for the server. This was causing trouble as Hibernate was updating ProgramRules and deleting some of the filtered ProgramRuleActions.
In this PR we are not filtering out ProgramRuleActions anymore, we are retrieving the needed ProgramRules with all the ProgramRuleActions associated and then mapping only the required actions.
Clean up:
- Remove all the unnecessary `@Transactional` in `dhis-service-program-rule` module
- Remove the unused `RuleActionKey`s
- Remove the mapping to actions not used in Tracker
> fix: Load PR with all PRA and filter later [DHIS2-17470]

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/history.vm
In the history velocity script a wrong path was used. `.autitType` returns an `enum` value. The `.getValue()` does not exist for the type and apparently this then computed to `null`. Instead the `.name().toLowerCase()` is used to get what `getValue()` originally returned (before it was removed a while back) so that the i18n lookup ends up with the same outcome.
Issue was introduced by https://github.com/dhis2/dhis2-core/commit/756f98b38ceb8b7b0155d68215f632699bd9f604
* open data entry app (old)
* select data set "Emergency Response"
* select Period "January 2024"
* select Target vs Result "Result"
* fill in a value in the top left cell
* change that value
* double click into the cell
* check you get a history popup (not an error)
Note the _Modification_ column stating _Update_ (not …
> fix: data entry audit history audit type column lookup [DHIS2-16887]

- .github/CODEOWNERS
Initial [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners) that specifies the DevOps team as owners of a list of files that can cause CI/build related failures. Owners of a given file/directory will be automatically added as reviewers to PRs that are ready for review (not draft PRs).
As mentioned in the docs, in order to automatically assign an owner as a reviewer to a PR, the CODEOWNERS file must exist in the base branch that the PR is going to be merged in. In this case the CODEOWNERS file doesn't exist in the `master` branch yet, so here's [a mock PR](https://github.com/dhis2/dhis2-core/compare/DEVOPS-405-v2...DEVOPS-405-v2-test?expand=1) where the base branch is the …
> chore: add CODEOWNERS file with initial configuration

- dhis-2/dhis-web-server/src/main/resources/log4j2.xml
During the transition to use Tomcat embedded and some module restructuring, 2 log4j files were effectively merged:
- log4j file used in production
- log4j file used in embedded Jetty (local dev)
This resulted in the formatting looking like this during local dev now:
To allow a developer to choose which appender to use, a system var (JVM arg) (`log4j.appender`) has been added to the log4j file. If the system var is found, it will try to use the value provided. The current options for appenders are:
- `console` (default, used in production)
- `console_color` (nice formatting for local dev)
If the system var is not found, it will fall back to using the default `console` appender
Now, we can pass a system var (JVM arg) in the run config like so:
This will result in the formatting like this …
> chore: Add system var (JVM arg) to be able to choose log appender

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/datastore/DatastoreKeysTest.java
> chore: Update flaky datastore test

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/appmanager/AppManagerTest.java
This is a fix to avoid null pointer exceptions when filtering on pluginType in api/apps (see [DHIS2-17492](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-17492)). I'm open to better ideas for how to do this 😄
I think there are some more things we might want to improve in terms of these filters (including why the url filter is `pluginType`, but the property is `plugin_type`), but I'm just addressing the immediate issue in the ticket here for now to be able to test UI updates in the app management app ([DHIS2-17490](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-17490)).
[DHIS2-17492]: https://dhis2.atlassian.net/browse/DHIS2-17492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17490]: …
> fix: filter out null pluginTypes [DHIS2-17492]

- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/pom.xml
**This PR will upgrade Velocity to the latest version.**
1. `commons-lang` is a forbidden dependency (we should use `commons-lang3` instead).
2. The currently used Velocity version (from 2010) still relies on `commons-lang`.
3. It would be safer to upgrade Velocity (and Velocity-Tools) to the latest version to ensure we have the most recent (and secure) version and to eliminate `commons-lang` from the classpath.
It would be helpful if someone from @dhis2/platform-backend could investigate any potential regressions.
Cheers
> chore: velocity and velocity-tools upgraded to latest version

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/DataElementWithLegendSetCondition.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/context/sql/SqlQueryCreatorService.java
* fix: multiple option set in TE filter [DHIS2-17258]
* fix: formatting [DHIS2-17258]
* fix: removed unnecessary method [DHIS2-17258]
(cherry picked from commit 202a91f3451222d8e6e58e6a7e63d1c26ffac711)
[DHIS2-17258]: https://dhis2.atlassian.net/browse/DHIS2-17258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17258]: https://dhis2.atlassian.net/browse/DHIS2-17258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17258]: https://dhis2.atlassian.net/browse/DHIS2-17258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: multiple option set in TE filter [DHIS2-17258] [2.41] (#17311)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AuthoritiesControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthoritiesController.java
After removal of Struts in 2.42, the app and schema authority listing system was also removed. This PR replaces the Struts pre-removal listing system with a new much simpler one, that directly lists the app authorities from the app manager and the schema service.
AuthoritiesControllerTest#testGetAllAuthorities() 
1. Navigate to the user admin app
2. Validate that all metadata authorities is listed
3. Validate that all installed app authorities is listed
4. Validate that all bundled app authorities is listed
5. Validate that all system authorities is listed
[DHIS2-17441](https://dhis2.atlassian.net/browse/DHIS2-17441)
[DHIS2-17441]: https://dhis2.atlassian.net/browse/DHIS2-17441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: broken authority listing in the user admin

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
**Backport**
There is the problem with sorting of the repeatable stages. The issue was pinpointed to the event report date in the repeatable stage. The capture app allowed users to add new events in the repeatable stage. The report date (found in the executiondate column of the event table in the tracker database) is treated as a date without a time section. When analytics queries for repeatable stage events using an position index, the executiondate is crucial for ensuring the correct outcome, as it serves as the sorting criteria. Sorting on non-unique data can yield inconsistent results. This is the scenario described in the ticket. Report dates of events within the repeatable stage are not unique, and sorting may yield different outcomes.
> fix: Investigate the reason of differences in events x enrollments in analytics query[2.39-DHIS2-16227-backport]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/BundlePreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/DefaultTrackerPreprocessService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/StrategyPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/non_existent_enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_data_for_deletion.json
First step to fix https://dhis2.atlassian.net/browse/DHIS2-17402 was to clean up integration test json files used to delete entities and remove all the fields except the entity uid.
This step revealed a potential NPE in the [preprocessor](https://github.com/dhis2/dhis2-core/blob/6be24e962adb654e354bd0a8c77857a91e2097c7/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/EventProgramPreProcessor.java#L54) and showed that we do not really need to run most of the preprocessor when the `importStrategy` is `DELETE`
> fix: Run most preprocessors only for CREATE and UPDATE [DHIS2-17402]

- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/mapgeneration/InternalMapObject.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapgeneration/GeoToolsMapObjectTest.java
- dhis-2/pom.xml
https://dhis2.atlassian.net/browse/DHIS2-12003
- Moves from the deprecated `EPSG 3785` to `EPSG 3857`  [https://epsg.io/3785](https://epsg.io/3785)
- Added unit test to verify that the error is not thrown.
```
Caused by: org.opengis.referencing.NoSuchAuthorityCodeException: No code "EPSG:3857" from authority "EPSG" found for object of type "EngineeringCRS".
```
> fix: api/maps/uid/data return error 500

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
(cherry picked from commit 6eafbbf816ba4d284f0927075abcecc7bc6910c2)
> fix: can not update users after OpenID field is set (#16723)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
Before this PR, a request containing an invalid date could pass through and get processed anyway.
This PR changes this behavior, returning an error when an invalid date is passed.
> fix: throws exception for invalid dates [DHIS2-17539]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/LoginTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
Regression in OAuth configuration is resulting in non functional deprecated OAuth functionality.
During reversion of the Struts removal and Spring 6 updated security config before 2.41 release, the deprecated OAuth functionality configuration was not properly reverted.   
JIRA: [DHIS2-17612](https://dhis2.atlassian.net/browse/DHIS2-17612)
[DHIS2-17612]: https://dhis2.atlassian.net/browse/DHIS2-17612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: revert deprecated OAuth security config

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/NoopJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/RecordingJobProgress.java
Adds `@Nonnull` and `@CheckForNull` annotations to the `JobProgress` API. 
Some return values were intentionally left out as their nullness depends on arguments which usually would be non-null so forcing null-checking upon the caller seems a bad trade-off.
Note that the use of `@CheckForNul` parameters in this API is intentional to allow "optional" parameters; This is because there are groups of methods of same name that are delegate to a single implementation method for each group. This method has all possible parameters but allows to leave some undefined to "skip" or "ignore" that aspect of the functionality.
> chore: nullness annotations for job progress API

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/jetty/JettyStartupTimerSpringConfiguration.java
- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/jetty/Main.java
- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/jetty/StartupFinishedRoutine.java
- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/tomcat/Main.java
- dhis-2/dhis-web-server/src/test/java/org/hisp/dhis/auth/AuthTest.java
Renames the embedded Jetty main class to Main, same as the embedded Tomcat main class to unify the naming.
Also removed unused code that was necessary for embedded Jetty before the transition to a Struts less server.
> chore: refactor embedded Jetty main class, remove deprecated features

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/RecordingJobProgress.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/tasks/ImportCompleteDataSetRegistrationsJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/tasks/DataValueSetImportJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/DefaultTrackerImportService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataImportJob.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportJob.java
The `runStage` method that would run a `Callable` could return `null` either from that `Callable` or from the `errorValue` given.
This potential NPE was not handled in many places. Often enough it also wasn't an issue as the usage of the returned value was below the next `startingStage` which would fail if the `null` was due to an error so the code would never proceed to use the variable. 
With the `JobProgress` not having nullness annotations the nullness analysis would warn about potential NPEs from the return values of `runStage`. To transition the value into a known non-null while keeping the error behaviour of throwing a cancellation exception on next use of progress after a failed stage a new method was added to confirm post run assumptions:
The `nonNullStagePostCondition` method …
> fix: runStage null to non-null or cancel via exception

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/history.vm
cherry-pick backport of #17710 / #17712
> fix: data entry audit history audit type column lookup [DHIS2-16887] (2.38.7)

- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/mapgeneration/InternalMapObject.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapgeneration/GeoToolsMapObjectTest.java
- dhis-2/pom.xml
This PR backports commit 636c4862a209885c527d7cbda5ea96619119780e.
> fix: api/maps/uid/data return error 500[DHIS2-12003-39]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/tei/TrackedEntityQueryTest.java
* fix: throws exception for invalid dates [DHIS2-17539]
* fix: throws exception for invalid dates [DHIS2-17539]
* fix: throws exception for invalid dates [DHIS2-17539]
(cherry picked from commit e1ef2a6b3e498d35400a6726c673cbb2c157a63b)
[DHIS2-17539]: https://dhis2.atlassian.net/browse/DHIS2-17539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17539]: https://dhis2.atlassian.net/browse/DHIS2-17539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-17539]: https://dhis2.atlassian.net/browse/DHIS2-17539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: throws exception for invalid dates [DHIS2-17539] [2.41] (#17823)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/BundlePreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DefaultTrackerPreprocessService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/StrategyPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/PersistablesFilter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/PersistablesFilterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/non_existent_enrollment_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationships_basic_data_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/relationships_existent_and_not_existent_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_with_inaccessible_relationship_for_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_data_before_deletion.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/tracker_data_for_deletion.json
Backport of https://github.com/dhis2/dhis2-core/pull/17784 and https://github.com/dhis2/dhis2-core/pull/17773
> fix: Remove unused check on delete persistables [DHIS2-17402] (2.39)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChangeLogController.java
Following up on the work done in [change logs](https://github.com/dhis2/dhis2-core/pull/16628), we need to deprecate the old endpoints in favor of the new ones.
> fix: Deprecate old change log endpoints [DHIS2-16741]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
I am asking @dhis2/platform-backend review because I am changing a store method and using `nativeSynchronizedQuery`
> fix: Filter pra types to get DE and TEA [DHIS2-17243]

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/ehcache.xml
- This is to fix hibernate warnings like below
```
core-web-1      | WARN  org.hibernate.orm.cache [main] HHH90001007: Using legacy cache name [org.hibernate.cache.spi.UpdateTimestampsCache] because configuration could not be found for cache [default-update-timestamps-region]. Update your configuration to rename cache [org.hibernate.cache.spi.UpdateTimestampsCache] to [default-update-timestamps-region].
core-web-1      | WARN  org.hibernate.orm.cache [main] HHH90001007: Using legacy cache name [org.hibernate.cache.internal.StandardQueryCache] because configuration could not be found for cache [default-query-results-region]. Update your configuration to rename cache [org.hibernate.cache.internal.StandardQueryCache] to [default-query-results-region].
core-web-1      | WARN …
```
> fix: add name for default ehcache

- .github/dependabot.yml
as these contain breaking changes even though its a minor version update. See https://github.com/dhis2/dhis2-core/pull/17754
> chore: ignore micrometer updates for supported releases

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/MetadataDimensionsHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/MetadataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/outlier/service/AnalyticsOutlierService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DimensionalObjectProducerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
This PR enforces the order of period dimensions to be the same as the request.
> fix: respect same order of periods in the requests for meta.dimensions.pe [DHIS2-16265]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EventServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
> chore: remove dhis-api EventService.get(id) DHIS2-17677

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/EventPredictionServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/validation/AnalyticsValidationServiceTest.java
follow up after https://github.com/dhis2/dhis2-core/pull/17873
This is a **big** task that …
> chore: remove dhis-api EventService.createEvent DHIS2-17677

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/orgunit/handler/TrackerOrgUnitMergeHandlerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/notification/ProgramNotificationMessageRendererTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EventServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramMessageStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityDataValueChangeLogStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramMessageControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramNotificationInstanceControllerTest.java
Follow up to https://github.com/dhis2/dhis2-core/pull/17916
This is a **big** task that we …
> chore: remove dhis-api EventService.addEvent DHIS2-17677

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
> chore: compute event statistics using IdentifiableObjectManager DHIS2-17638

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
We inadvertently introduced a but that causes a request to fetch a single tracked entity will return only tracked entity type attributes even if the program is provided.
This fix aims to solve the issue by returning program attributes too.
> fix: Return PAs when TE found [DHIS2-14300][2.40] (#17954)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Type.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EmptyOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/GreaterEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/GreaterThanOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/LessEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/LessThanOperator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/OperatorTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
[DHIS2-17688-42](https://dhis2.atlassian.net/browse/DHIS2-17688)
- The api request api/dataSets?filter=userAccesses:empty doesn’t work in 2.41 because the legacy accesses object have been removed.
- User should be able to use sharing like below, but currently this is also not working.
```
api/dataSets?filter=sharing.users:empty 
api/dataSets?filter=sharing.userGroups:empty
```
- This PR add supports for handling sharing property in API filter.
> fix: api filter support sharing object[DHIS2-17688-42]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/enrollment/SecurityOwnershipValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/SecurityOwnershipValidator.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
When there's a request to an inaccessible TE and the program is protected, we always return `OWNERSHIP_ACCESS_DENIED`, regardless of whether the owner is in the user search scope. This PR aims to fix that by verifying if the owner is in the correct scope and returning a different error message if they are not. It's important to get this error message right because it's the one used to determine on the FE side if the user can break the glass or not.
While I am at it, I'm also fixing a couple of typos and two errors that arose after the transition from `User` to `UserDetails`. They validate the user access by comparing to the data org units when they should be using the capture scope org units.
Ticket: https://dhis2.atlassian.net/browse/DHIS2-17477
> fix: Return specific message when user can break glass [DHIS2-17477]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/supplier/strategy/EventStrategy.java
`getIncludingDeleted` is only used in the `EventStrategy`.
Soft-deletion is only present so Android can tell what was deleted. Soft-deleted entities should otherwise not be exposed. We want to find a more reliable synching mechanism for Android. Its therefore important that we do not expose this in our public API service unless we absolutely have to. This will then make it easier to move to another mechanism.
So this is a pragmatic change that violates our usual layered architecture in service of the above.
> chore: remove dhis-api EventStore getIncludingDeleted DHIS2-17701

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/AggregateDataSetSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CompressionSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/pom.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/DeleteEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EventSavingSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/RegisterSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/RelationshipSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SimpleEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SingleEventListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/TrackedEntityRegistrationSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/TrackerEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/CompressionSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/DeleteEventSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/RelationshipSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/SimpleEventSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/TrackedEntityRegistrationListenerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/TrackerEventSMSListenerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
follow up to https://github.com/dhis2/dhis2-core/pull/17970 and https://github.com/dhis2/dhis2-core/pull/17952
Move tracker specific SMS classes into the `tracker.imports.sms` package in the `dhis-service-tracker` as these classes import tracker data. As discussed we will revisit the internal tracker package structure once we have finished the epic and consolidated to one maven module.
Some of the SMS classes still depend on `org.hisp.dhis.program.EventService` for CRUD operations. This will be fixed in the next PRs.
We need to run operations in the context of the user sending the SMS. The tracker event exporter therefore gets `getEvent` methods for passing in a `UserDetails`.
> chore: remove dhis-api EventService.get by UID part 2 DHIS2-17638-7

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
Another goal is that code that provides tracker functionality and is thus owned by the tracker team lives in ideally one maven module (We can settle on a name later on maybe dhis-service-tracker or dhis-tracker).
This is a big task that we are going to implement in many small steps.
Finding an enrollment by …
> chore: remove dhis-api EnrollmentService.get(id) [DHIS2-17712]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageDataElementStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerEventBundleServiceTest.java
As in https://github.com/dhis2/dhis2-core/pull/17992 this is a pragmatic change that violates our usual layered architecture in service of the achieving one tracker event exporter service. Inlined the code used in one place.
How notifications are sent will change soon as the platform team is working on it. So we will get an opportunity to refactor this code.
> chore: remove dhis-api EventStore.getWithScheduledNotifications DHIS2-17638

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppType.java
now that tracker capture app has been removed from v42.
@eirikhaugstulen pointed out that this removal should be safe. There are no apps on the app hub with this type https://apps.dhis2.org/?page=1&types=TRACKER_DASHBOARD_WIDGET. Furthermore, tracker capture is not supported from v42 forward.
> chore: remove unused AppType.TRACKER_DASHBOARD_WIDGET DHIS2-17723

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/params/CommonParamsDelegator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/processing/MetadataDimensionsHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/MetadataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/outlier/service/AnalyticsOutlierService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DimensionalObjectProducerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
fix: fixes period order in TE endpoint [DHIS2-16265] (#17915)
(cherry picked from commit 85d2d4938ae2d92c6c811f50fdbf2fa41cc3ac0f)
fix: respect same order of periods in the requests for meta.dimensions.pe [DHIS2-16265] (#17902)
* fix: respect same order of periods in the requests for meta.dimensions.pe [DHIS2-16265]
* fix: fixes NPE in integration test [DHIS2-16265]
(cherry picked from commit 6bcb4bcd951bd00ec722433fe95654efba8e2f59)
[DHIS2-16265]: https://dhis2.atlassian.net/browse/DHIS2-16265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-16265]: https://dhis2.atlassian.net/browse/DHIS2-16265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-16265]: …
> fix: respect same order of periods in the requests for meta.dimensions.pe [DHIS2-16265] [2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
> fix: getOptionCodePropertyMap now returns translated value if necessary [DHIS2-16208][2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
> fix: getOptionCodePropertyMap now returns translated value if necessary [DHIS2-16208][2.40]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
> fix: getOptionCodePropertyMap now returns translated value if necessary [DHIS2-16208][2.41]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/users_with_no_user_role.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUsersWithNoRoleControllerTest.java
The API actively forces users to have a role and should prevent removing roles which are associated with a user. When looking at some old databases, it was observed however that there are users with no roles. Likely this resulted from changes in the API over time, and at some point, users were left abandoned without roles. This integrity check will help to identify them.
> feat: Add integrity check for users with no user roles

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
This PR will replace `getPropertyValue()` with `getDisplayPropertyValue()` to allow proper translations in given conditions.
> fix: getOptionCodePropertyMap now returns translated value if necessary [DHIS2-16208]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListenerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentStoreTest.java
Another goal is that code that provides tracker functionality and is thus owned by the tracker team lives in ideally one maven module (We can settle on a name later on maybe dhis-service-tracker or dhis-tracker).
This is a big task that we are going to implement in many small steps.
Removes the method …
> chore: Remove enrollmentService.enrollmentExists [DHIS2-17712-3]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/user_roles_no_authorities.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/user_roles_with_no_users.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUserRolesNoAuthorities.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUserRolesNoUsers.java
User roles should normally have some authority associated with them. This integrity check identifies user roles with no authorities. 
We also add a check for user roles with no users.
> feat: Add integrity check for user roles with no authorities/users

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/user_roles_no_authorities.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/user_roles_with_no_users.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/users_capture_ou_not_in_data_view_ou.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/users_capture_ou_not_in_tei_search_ou.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/users_with_no_user_role.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUserRolesNoAuthorities.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUserRolesNoUsers.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUsersCaptureOrgUnitNotInTeiSearchHierarchy.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUsersCaptureOrgunitNotInDataView.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUsersWithNoRoleControllerTest.java
Adding the following integrity checks to this version: 
-Users capture OU within data view OU
-Users capture OU within TEI search OU
-Users with no roles
-User roles with no users
-User roles with no authorities
> chore: Backport new data integrity checks from master

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/StatusUpdateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/executor/event/SetMandatoryFieldExecutorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/event/DataValuesValidatorTest.java
We were validating mandatory data values when creating or when transitioning from a status that does not allow to define data values to one that allows it. This is an issue in some cases:
- When a program rule is evaluated to true based on some temporal factor. A data value could then be not mandatory at the moment of creation/transition, but become mandatory at a later stage.
- When metadata is changed. A DataElement is now mandatory.
- When the programStage validation strategy is `ON_COMPLETE` and the status was `ACTIVE` and become `COMPLETE`. Becasue it is not a `CREATE` we were skipping validation here. This is a really common use case that we were missing.
The solution is to not consider anymore if the import is a CREATE or an UPDATE but always validate mandatory data values (when …
> fix: Validate mandatory data values also on UPDATE [DHIS2-17560]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
Another goal is that code that provides tracker functionality and is thus owned by the tracker team lives in ideally one maven module (We can settle on a name later on maybe dhis-service-tracker or dhis-tracker).
This is a big task that we are going to implement in many small steps.
Removes the method …
> chore: Remove method enrollmentExistIncludingDeleted [DHIS2-17712]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateStoreRelationshipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateStoreTEAVTest.java
This makes the deduplication store private and moves some integration tests, that were still outside of the tracker package, into it.
Next step will be to remove the `PotentialDuplicateStore` interface and inject `HibernatePotentialDuplicateStore` directly in the service.
> chore: Make deduplication store private [DHIS2-17744]

- dhis-2/dhis-support/dhis-support-test/pom.xml
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/BaseSpringTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2-test.xml
- dhis-2/dhis-test-integration/src/test/resources/log4j2-test.xml
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/DhisControllerIntegrationTest.java
These configs are responsible for configuring log4j2 during test execution
- https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-test-integration/src/test/resources/log4j2-test.xml
- https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2-test.xml
For example if you add
```xml
<Logger name="org.hisp.dhis.datasource" level="debug" additivity="false">
<AppenderRef ref="console"/>
</Logger>
```
into https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-test-integration/src/test/resources/log4j2-test.xml
and run an integration test in `dhis-test-integration` you will see debug logs like
```
12:56:24.642 [main] INFO  org.hisp.dhis.datasource.DatabasePoolUtils - Database pool type value is 'C3P0'
12:57:14.670 [main] ERROR …
```
> test: log4j2 is configured via xml DHIS2-16557

- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/metadata/MetadataActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/DataElementMergeTest.java
[This test](https://github.com/dhis2/dhis2-core/blob/2b1b76cfe10a053a20db38a5b0ba8f26d5fae08d/dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/DataElementMergeTest.java#L183) in [this PR](https://github.com/dhis2/dhis2-core/pull/17288) introduced a potential scenario whereby unrelated existing tests could fail depending on the order in which the tests were run (it was observed that tests were passing in GitHub but failing in Jenkins).
The newly-added test creates a `Program` which is never cleaned-up by the E2E test framework after the test is finished. This `Program` then causes `NullPointerException`s when Tracker logic is invoked to check write  permissions here `org.hisp.dhis.trackedentity.DefaultTrackerAccessManager.canWrite`.  
If the `Progam` does not have a `TrackedEntity` …
> chore: Re-enable disabled test and use existing metadata import method in E2E test

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/copy/CopyService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/copy/CopyServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/RegisterSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SimpleEventSMSListener.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/orgunit/handler/TrackerOrgUnitMergeHandlerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/EventPredictionServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramMessageServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityQueryLimitTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/validation/AnalyticsValidationServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramMessageControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramNotificationInstanceControllerTest.java
Continuing with the work on removing the enrollment service from the API module, this PR removes the addEnrollment() method. Instead, the manager will handle enrollments until the importer is ready for use.
> chore: Remove addEnrollment(Enrollment enrollment) [DHIS2-17712]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/notification/ProgramNotificationMessageRendererTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
Continuing with the work on removing the enrollment service from the API module, this PR removes the `updateEnrollment()` method. Instead, the manager will handle enrollment updates until the importer is ready for use.
> chore: Remove updateEnrollment(Enrollment) [DHIS2-17712]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/network/PortUtil.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/jetty/Main.java
- dhis-2/dhis-web-server/src/test/java/org/hisp/dhis/auth/AuthTest.java
Fixes a regression that caused the embedded Jetty to fail during startup.
A profile is applied when starting Jetty to selectively add the request event listener.
AuthTest (will start embedded Jetty on an available port and run login tests)
* Start the embedded Jetty server
* Observe you can log in
> fix: embedded Jetty failing to start

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationController.java
Another goal is that code that provides tracker functionality and is thus owned by the tracker team lives in ideally one maven module (We can settle on a name later on maybe dhis-service-tracker or dhis-tracker).
This is a big task that we are going to implement in many small steps.
Moves the method …
> chore: Remove getEnrollments(List<String>) [DHIS2-17712]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceBlocklist.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
Adds more file upload validation to the orgunit file domain. This adds the same validation logic as avatar and icon file uploads.
FileResourceControllerTest
* Try to upload a "fake" image file, take any other type of file and change it's extension to .jpg/.png/.gif and try to upload it.
* Observe you are not allowed to upload that file.
> feat: add more validation to file upload

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
This PR adds a upload file size hard limit. There is a 2MB limit enforced in the UI, this adds the limit check to the back-end too. The new limit can be configured in dhis.conf with the `max.file_upload_size` setting. The default is 10MB.
FileResourceControllerTest
* Try to upload a file bigger than 3MB
* Observe you are not allowed to upload
> feat: add max upload file size validation

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
> chore: Remove delete relationship from service [DHIS2-17713]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/NoOpFlywayConfiguration.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/test/webapi/WebTestConfiguration.java
so we do not include it into the dhis.war and risk using it in production.
No need to specify the bean name if the method has the expected name.
> test: move NoOpFlywayConfiguration into dhis-support-test DHIS2-16557

- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
We were missing a few translations for some data integrity checks which have been added recently
> fix: Adds missing translations for new integrity checks

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/TrackerObjectDeletionService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateStoreRelationshipTest.java
> chore: Remove getters from RelationshipService [DHIS2-17713]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
> chore: Remove getters by entity from RelationshipService [DHIS2-17713]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
> chore: Remove get by uids from RelationshipService [DHIS2-17713]

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SmsCommandControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SmsInboundControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SmsOutboundControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsInboundController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsOutboundController.java
Adds more ACL checks to inbound and outbound SMS messages.
SmsCommandControllerTest
SmsOutboundControllerTest
SmsInboundControllerTest
1. Create a guest user account, with no authorities
2. Call GET /api/sms/outbound, observe 403 response
3. Call GET /api/sms/inbound, observe 403 response
4. Call GET /api/smsCommands, observe 403 response
> feat: add more ACL checks to SMS inbound/outbound

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TwoFactorControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/TwoFactorController.java
Adds a simple brute force protection on the 2fa/disable endpoint.
After 4 failed attempts the endpoint will be disabled for the next 15 minutes.
TwoFactorControllerTest#testDisable2FaTooManyTimes()
1. Log in and go to account app.
2. Enable 2FA as instructed.
3. Try to disable the 2FA on the same page with a random code
4. Observe that on the 5th attempt with a wrong code you get this response: `Too many failed disable attempts. Please try again later`
> feat: add a brute force protection on the 2fa/disable endpoint

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/supplier/strategy/EnrollmentStrategy.java
This PR continues the work of moving tracker-related code out of the API module. Specifically, it:
- Removes the `getIncludingDeleted` method from `EnrollmentStore`. It's used just in `EnrollmentStrategy`, and a sql query will be triggered directly from there.
> chore: Remove getIncludingDeleted [DHIS-17712]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/supplier/strategy/RelationshipStrategy.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/RelationshipImportTest.java
> chore: Remove getIncludingDeleted from RelationshipStore [DHIS2-17713]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/EnrollmentDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEnrollmentStore.java
This PR continues the work of moving tracker-related code out of the API module. Specifically, it:
- Removes the hardDeleteEnrollment method from EnrollmentService and EnrollmentStore.
- Removes the ceremony around deleting an event program enrollment.
> chore: Remove method hardDeleteEnrollment [DHIS2-17721]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventProgramEnrollmentService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventProgramEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/copy/CopyService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventProgramEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventProgramEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/copy/CopyServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EventProgramEnrollmentServiceTest.java
This PR continues the work of moving tracker-related code out of the API module. Specifically, it:
- Removes the getEnrollments(Program) method from the `EnrollmentService`.
- Creates a new service and store to deal with event programs enrollments. These two are meant to be used as a temporary solution until event programs are completely separated from tracker programs. At that point, both classes should be removed.
As a side note, we've found out the `CopyService` is actually copying enrollments from tracker programs. For now, we don't change its logic, but that's something worth of a discussion when the appropriate people are back from holidays.
> chore: Remove getEnrollments(Program) [DHIS2-17712]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapper.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
Backport 
[DHIS2-17180](https://dhis2.atlassian.net/browse/DHIS2-17180)
> fix:(2.39) Notification trigger when status is changed to completed [DHIS2-17180]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EnrollmentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEnrollmentStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentStoreTest.java
This PR continues the work of moving tracker-related code out of the API module. Specifically, it:
- Removes the `getEnrollments(Program)` from the api module `enrollmentStore`, which is just used in one test, and this test is already covered in `EventProgramEnrollmentServiceTest`
> chore: Remove getEnrollments(Program) from store [DHIS2-17712]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserAccountControllerTest.java
2 recaptcha tests started failing. They actually call out to a google API and get the response, which is what is causing the tests to fail. The response has changed from google.
Response changed from `invalid-input-secret` to `invalid-input-response`
Initial fix is to keep the assertion more vague. 
Next: Will look to move these 2 tests so we can mock the response from google.
> test: Update recaptcha test assertions

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserAccountServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserAccountControllerTest.java
Change 2 recaptcha web API tests to unit tests.
This is required so we don't rely on any external calls in our tests.
The 2 API tests were calling Google to verify the recaptcha string.
> test: Change recaptcha API tests to unit tests

- jenkinsfiles/dev
The debug option for the maven build was [added 3 years ago](https://github.com/dhis2/dhis2-core/pull/8476) to debug an issue. It was never removed.
This PR removes the debug log option in the dev build to reduce unnecessary noise in the build logs.
If debugging the build is necessary, it would be nice to have a `build with parameters` option in Jenkins to request a debug build on demand (without needing a code change).
> chore: Remove maven debug logs in pipeline dev build

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/jdbc/JdbcOrgUnitAssociationStoreConfiguration.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/config/ServiceConfig.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/config/JacksonObjectMapperConfig.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/config/ServiceConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateEncryptionConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/DefaultSessionConfiguration.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
* `@DependsOn` is not needed if the dependency is explicit via the code like a parameter to a bean annotated method
* Setting the bean name is not necessary if the method has the same name
* Use one mechanism to wire up the bean: either parameters (which I prefer) or fields
> chore: remove unneeded code DHIS2-17821

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationTemplateService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationTemplateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationTemplateService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationTemplateStore.java
[DHIS2-17827](https://dhis2.atlassian.net/browse/DHIS2-17827)
- Removes unused methods of `ProgramNotificationService` and `ProgramNotificationTemplateStore`
[DHIS2-17827]: https://dhis2.atlassian.net/browse/DHIS2-17827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: remove unused notification service methods [DHIS2-17827]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SMSEnrollmentService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/notification/ProgramNotificationMessageRendererTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/EventPredictionServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateStoreRelationshipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/validation/AnalyticsValidationServiceTest.java
> chore: Remove updateTrackedEntity [DHIS2-17714]

- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/CacheInvalidationConfig.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/CacheInvalidationListener.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/CacheInvalidationSubscriptionService.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/PostCacheEventPublisher.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/PostCollectionCacheEventPublisher.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/RedisMessagePublisher.java
the Conditional already excludes these beans from use during testing. We are also going to replace the use of profiles soon (https://github.com/dhis2/dhis2-core/pull/18270).
> chore: don't use Profile and Conditional DHIS2-17821

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
The names of the geometry columns have been updated. This change is not backward compatible, and some front-end applications are still using the old column names.
> fix: The coordinate fields are not backward compatible with some front end applications[2.42-DHIS2-17842]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/dataelement/DataElementMergeProcessorTest.java
I've seen these tests fail sometimes in PRs, never locally tough.
Transient exception when Period not saved, even though they are saved!
This change uses the period service to save them to see if it improves.
> chore: Change how Period is saved in some tests

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/EventProgramEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/copy/CopyService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventProgramEnrollmentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateEventProgramEnrollmentStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EventProgramEnrollmentServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramControllerIntegrationTest.java
The `CopyService` should only replicate metadata when copying a program, never the actual data. 
This means it should copy enrollments in event programs, where the enrollment serves as a placeholder, but should not copy enrollments in tracker programs, as these are considered data.
> chore: Return enrollments of event programs only [DHIS2-17712]

- dhis-2/pom.xml
It looks like the new rule-engine workflows might have some gaps in terms of properly handling the snapshot versions vs release versions and the availability of the same in maven. The timestamped snapshot version was missing in sonatype snapshot repo and v41 builds were failing. 
Maybe sonatype cleans up snapshot dependencies when the corresponding release version is published? Or maybe it cleansup after a while anyway? There could be some sort of cleanup configuration done in the rule-engine repository.
Assuming all our dhis2  releases (major/minor/patch) should ideally use only release versions of rule-engine and not snapshot versions. The workflow/releases for rule-engine and corresponding linking in dhis2-core probably needs some looking into. Will follow this up with Enrico once he …
> fix: Change rule-engine snapshot version to release version 3.0.0

- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/stable
Increasing the IM Play intances Memory Resource Requests to 2500Mi, to avoid getting DHIS2 pods evicted due to higher memory consumption than requested. Also increasing the Readiness and Liveness probes timeouts, to avoid DHIS2 pods getting restarted due to timing out on their health checks while generating analytics.
> ci: increase IM play instances memory requests and probes timeouts

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityQueryLimitTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityServiceTest.java
> chore: Remove getTrackedEntityIds method [DHIS2-17714]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DataSetDeletionHandler.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/legendset/LegendSetTest.java
Deleting a `LegendSet`, which is referenced in a `DataSet`, fails and a `ConcurrentModificationException` is thrown internally. `409` response returned (sample below).
Endpoint: `DELETE` `/api/legendSet/{uid}`
The implementation used to remove a `LegendSet` from a `DataSet` in `DataSetDeletionHandler` was using an enhanced for loop (iterator) and then trying to update the collection inside the loop.
Use an iterator to iterate over the items and use the iterator to remove the item from the collection.
Added e2e test
```json
{
"status": "WARNING",
"message": "One or more errors occurred, please see full details in import report.",
"response": {
"responseType": "ObjectReport",
"klass": "org.hisp.dhis.legend.LegendSet",
"uid": "k1JHPfXsJND", …
```
> fix: Delete legend set with ref in data set [DHIS2-6011]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/RequestTypeAware.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsManagerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
**BACKPORT**
We are seeing discrepancies between the outputs of enrollments in pivot tables vs line listing in the event reports.
> fix: Event Report Enrollments not returning correct data[2.39-DHIS2-15291-backport]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/user/hibernate/User.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
Fixes broken OpenID value update with linked accounts. 
Linked accounts works by having multiple accounts set with the same OpenID mapping value, effectively making multiple DHIS2 accounts/users sharing one external managed identity.
UserControllerTest.testSetOpenIdThenUpdate()
UserControllerTest.testSetOpenIdThenUpdateWithLinkedAccountsEnabled()
UserControllerTest.testSetOpenIdThenUpdateWithLinkedAccountsDisabled()
1. Enable linked accounts in the dhis.conf. Property is: `linked_accounts.enabled`
2. Create two accounts, set both account's OpenID property to the same value.
3. Observe on second user that you get no error response when saving/updating the user.
> fix: broken OpenID value update with linked accounts

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login_mobile.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/interceptor/SystemSettingInterceptor.java
See [DHIS2-17630](https://dhis2.atlassian.net/browse/DHIS2-17630).
This is a hook needed by PEPFAR (and conceivably others) to put custom HTML/JavaScript into the v40 mobile login page. They've moved their v40 implementation to a single sign-on system and they use system setting `keyApplicationNotification` to redirect non-mobile users to the sign-on system. The problem is that the login page for mobile users can't also redirect mobile users to the sign-on system, so mobile users effectively cannot log in. This feature/fix allows PEPFAR (or anyone else) to supply custom HTML/JavaScript for the mobile login page.
Note that this is only needed for v40, since v41 and following use a login app.
[DHIS2-17630]: https://dhis2.atlassian.net/browse/DHIS2-17630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> feat: mobileApplicationNotification [DHIS2-17630]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
Previously, it was mistakenly marked as a struts app and understandably removed: [commit](https://github.com/dhis2/dhis2-core/commit/bf75a859efc44c158827b6870dd92e71785e55ae#diff-51f2d46ebede0a2c8d46f862af94d08c1255a79d1eab1eaeff60571f3b23635e)
Local server to verify the fix:
> fix: rebundle approval app

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/predictor/hibernate/Predictor.hbm.xml
[Discussed](https://dhis2.slack.com/archives/G4513PWGY/p1724399823926379) whether `Predictor` is intentionally not shareable or not. Seems that it was designed to not be shareable.
Adding comment in the `.hbm` file advising of this so it's clear for future viewers of this file.
> fix: Predictor not shareable comment [DHIS2-11553]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_12__Remove_attribute_from_attributeValues.sql
- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonAttributeValueBinaryType.java
Eliminates the unnecessary repetition of the shallow attribute within each attribute value.
From
```json
{"<attrid1>": {"value": "<val>", "attribute": {"id":"<attrid1>"}}
```
To
```json
{"<attrid1>": {"value": "<val>"}}
```
I also considered taking it one step further to 
```json
{"<attrid1>": "<val>"}
```
but this would need adjustments in all SQL queries related to this which feels quite risky to identify all of them.
I also decided to use `json-tree` for the object - JSON conversion to be more lenient without having to pay for any additional content in the JSON that isn't mapped. In addition this mapping should perform better as it creates very few intermediate objects.
> refactor: no attribute property in attributevalues JSONB objects [DHIS2-17482]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/user/hibernate/User.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
(cherry picked from commit 8ca70a35974d0e43204a43fde2ebb7e0b9e25a24)
> fix: broken OpenID value update with linked accounts (#18353)

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceImportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJobTest.java
Attempts to fix tests that broke after merge of https://github.com/dhis2/dhis2-core/pull/18362
The errors showed up after merge, hence GitHub actions pipeline did not catch them. However Jenkins did.
[DHIS2-17906]: https://dhis2.atlassian.net/browse/DHIS2-17906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: fix broken tests from DHIS2-17906

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/i18n/I18nFormat.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv11AutoTest.java
**BACKPORT**
For the short names of the weekly period dimension, we were displaying a less meaningful version, such as "2024SunW1." To improve clarity, we are now updating the short name format to "W1 2023-12-31 - 2024-01-06" when the DHIS2 instance is set to display short names.
> feat: Improve Data Visualizer with fixed period "Weekly (Start Sunday)" labels [2.40-DHIS2-17955-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/i18n/I18nFormat.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
**BACKPORT**
For the short names of the weekly period dimension, we were displaying a less meaningful version, such as "2024SunW1." To improve clarity, we are now updating the short name format to "W1 2023-12-31 - 2024-01-06" when the DHIS2 instance is set to display short names.
> feat: Improve Data Visualizer with fixed period "Weekly (Start Sunday)" labels [2.39-DHIS2-17955-backport]

- dhis-2/build-docker-image.sh
The logic in the `build-docker-image.sh` script (added with https://github.com/dhis2/dhis2-core/pull/15611) was relying on having the version being released in the `stable.json`.  However, in the [stable pipeline](https://github.com/dhis2/dhis2-core/blob/master/jenkinsfiles/stable) the `stable.json` is updated with the new version after the WAR and Docker image artefacts are already built.
> ci: refactor docker rolling tags logic [skip ci]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/webapi/json/domain/JsonMetadataVersion.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataVersionControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/version/MetadataVersionController.java
Endpoint `/api/metadata/versions` broken, returning `404`
During some web context mapping feature [here](https://github.com/dhis2/dhis2-core/pull/17122/files#diff-342cc97cf1e3e0f776113d93e2631ef08affdf66a0df902fd2cc5a147fd1e91cR78), the mapping `/metadata/version` was put at the class level. The `versions` endpoint was missed, leaving the endpoint available on `/api/metadata/version/metadata/versions`
- Strip back the top-level path mapping from `/metadata/version` to just `/metadata`
- fix broken endpoint
- ensure other endpoints have the appropriate mapping
There were no specific tests for any of these endpoints it seems
Added a test for each of the endpoints:
- `/api/metadata/versions`
- `/api/metadata/version`
- `/api/metadata/version?versionName={versionName}`
- …
> fix: Metadata versions endpoint should return valid data [DHIS2-17973]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
Adds a new configuration `node.primary_leader` that when set to true/on the node will unconditionally set itself as the leader (as opposed to only setting its ID when no other value is present). This means (eventually) the node should always take over the leader role in a cluster as all other nodes will only set their ID in case no ID is set. This way other nodes only take over the leader role if the primary leader is in fact not able to renew (maintain) its leader role by setting its ID.
> feat: adds configuration for primary leader node [DHIS2-16878]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserAccountControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
The FakeMessageSender (and any other Spring component) will be shared by tests that share the same ApplicationContext https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/ctx-management/caching.html So we have to cleanup any state produced by tests. Otherwise, a change in order will cause tests to fail only on Jenkins, GitHub, ...
> test: clear fake message sender to isolate tests DHIS2-17729

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/Section.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SchemaBasedControllerTest.java
refactors the schema based controller tests so that the one test case that was testing it all now became 448 dynamically generated tests.
I added some more tests as well, for each schema we now also test:
* patching an object `PATCH /api/{object-type}/{id}`
* reading the object (single) metadata API, `GET /api/{object-type}/{id}`
* reading the object list metadata API `GET /api/{object-type}/`
That found a bug in the JSON mapping that I fixed.
> test: schema based tests as individual tests

- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/DataSourcePoolMetricsConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/AbstractPoolMetadata.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/CompositePoolMetadataProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/HikariMetadataProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/HikariPoolMetadataAccessor.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/PoolMetadata.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/PoolMetadataProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/PoolMetadataProviders.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/PoolMetrics.java
* fix: add support for Hikari pool metrics
(cherry picked from commit 94e33c8e90e6a72c6a98c54777211c13791b436f)
Backport of: https://github.com/dhis2/dhis2-core/pull/15623
> fix: add support for Hikari pool metrics [DHIS2-15419] (#15623)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/RouteController.java
Fixes a endpoint ambiguity issue with the Collection API and Route API. Since the Route API does not support Collection API anyways this fix will disable the endpoint mapping that is causing the issue.
[DHIS2-17593](https://dhis2.atlassian.net/browse/DHIS2-17593)
[DHIS2-17593]: https://dhis2.atlassian.net/browse/DHIS2-17593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Route API endpoint ambiguity

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/app/AppManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AppControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AppHubControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreControllerAppAdditionalNamespacesTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreControllerAppTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DatastoreControllerIntegrationTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppHubController.java
implements [DHIS2-18027](https://dhis2.atlassian.net/browse/DHIS2-18027). 
needed for the fix for [DHIS2-13294](https://dhis2.atlassian.net/browse/DHIS2-13294) 
After manually installing an app (`POST /apps`), we wanted to be able to redirect the user to the app just installed. But since the API only returned an empty 204, the FE had no way to know the ID and other info of the installed App. This backend change exposes this information for the frontend return a 200 with the App object.
The ticket is relevant mainly when manually installing, but I also updated the install from AppHub to return the App object for consistency (and because we can make use of that info to avoid having an extra call to get the list of apps as we do now)
[DHIS2-13294]: …
> fix(DHIS2-13294): return app details from Apps install endpoint

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_16__Remove_config_setting_row.sql
Removes the `Configuration` as a system setting.
Reasons
* `Configuration` type is not a system setting but the system configuration that has its own API
* it is one of currently two settings with a complex value (which both are not proper settings; settings contract should be simplified to always be about simple values)
* it is not actually used in the code, which should mean it is never written or updated and thus should always be undefined (default)
As settings map to enum `SettingKey` a potentially existing row needs to be removed via script. 
https://github.com/dhis2/dhis2-docs/pull/1430
> chore: remove config system settins [DHIS2-18024]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GatewayAdministrationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsConfigurationManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DefaultDatastoreService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/DefaultGatewayAdministrationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/DefaultSmsConfigurationManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/config/GatewayAdministrationServiceTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_17__Move_sms_config_to_datastore.sql
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsGatewayController.java
Changes the persistence of the SMS gateway configuration to use the datastore.
To be safe a new protected namespace `sms-config` is used.
Both reads and writes are protected with the existing authority `F_MOBILE_SENDSMS` that was already checked for most related controller methods.
A flyway script moves any existing configuration into the datastore.
The system setting `keySmsSetting` got removed.
Existing controller and component tests were adjusted slightly.
Testing the migration:
* create a environment with a server version before this change that has a SMS gateway configuration
* save the DB
* create a new environment with a server version containing this change that uses the saved DB
* after server startup goto SMS configuration app and check the old configuration is shown
Testing …
> refactor: sms gateway configuration stored in protected datastore ns [DHIS2-18025]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/pom.xml
Bump `rule-engine` version.
New `rule-engine` allows to create an event or an enrollment with a `null` organisation unit code.
In this PR I added the related tests and refactor the whole test class.
> fix: Test nullable org unit code for new rule-engine version [DHIS2-17715]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseDimensionalItemObject.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/common/BaseDimensionalItemObjectTest.java
**BACKPORT**
The Analytics API is returning an incorrect TotalAggregationType. It doesn't align with the AggregationType set to NONE. The fix involves ensuring that both values are set to NONE.
> fix: Analytics API returns invalid totalAggregationType [2.39-DHIS2-18045-backport] 

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-server/src/test/java/org/hisp/dhis/auth/AuthTest.java
This PR introduces a simple URL filter method, to make sure redirects (saved requests) after login, never redirects to a resource file, like .css, .js etc.
The filter will only allow redirects to URLs ending in `.html`, `/` or nothing (i.e. contains no `.`).
org.hisp.dhis.auth.AuthTest()#testRedirectToResource
org.hisp.dhis.auth.AuthTest()#testRedirectToResourceWorker
org.hisp.dhis.auth.AuthTest()#testRedirectToCssResourceWorker
1. Make sure you are logged out.
2. Manually write in a URL, like this: http://localhost:8080/dhis-web-dashboard/mstile-150x150.png
3. Observe you get redirected to login page.
4. Log in and observe you get redirected to the dashboard.
[DHIS2-17851](https://dhis2.atlassian.net/browse/DHIS2-17851)
[DHIS2-17851]: …
> fix: filter redirect URLs after login

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.41/V2_41_49__Update_api_token_tokentype.sql
The personal access tokens was updated in 2.41, and the type names was changed, making existing tokens made before this change, incompatible. This PR adds a .sql Flyway migration script that updates the existing PATs to use the new enum type names.
1. Start a 2.40 server with an empty DB
2. Create some PATs
3. Upgrade and start a 2.41 server on the same DB
4. Observe the tokens has gotten the new type names in the DB (api_tokens)
[DHIS2-17496](https://dhis2.atlassian.net/browse/DHIS2-17496)
[DHIS2-17496]: https://dhis2.atlassian.net/browse/DHIS2-17496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: make sure API tokens are backward compatible

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
As a side effect of adding attributes to the user, we end up with the user deserializer trying to fetch the user settings before the user is logged in. This is caused by tight coupling of the user settings into the domain model.
This PR patches the methods called and allow for null and default values when deserialization before user is logged in occurs.
N/A
1. Open the [version 41 play instance](https://play.im.dhis2.org/stable-2-41-1)
2. Navigate to Maintenance > Others > Attribute > Add attribute
3. Set value 'FCM Token' to name, shortName, and code
4. Add a description
5. Select value type as Text
7. Check 'User' field
8. Save
9. Navigate to the users app
10. Select your current user to edit
11. Add a value to the attribute field
12. Save changes
13. Log out
14. Log in with correct …
> fix: login fails when there is attribute values assigned to the user

- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/pom.xml
Adds dependency on `log4j-layout-template-json` which allows template based json layout to be applied to logs coming out of log4j. This won’t affect any existing system but its very useful when you are using a custom `log4j2.xml` file.
Backport from V42.
[DHIS2-18063](https://dhis2.atlassian.net/browse/DHIS2-18063)
[DHIS2-18063]: https://dhis2.atlassian.net/browse/DHIS2-18063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: adds log4j-layout-template-json for json based logs

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/interceptor/TrailingSlashInterceptor.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
- dhis-2/dhis-web-server/src/test/java/org/hisp/dhis/auth/AuthTest.java
After the removal of Struts and restructuring of how resources are served in 2.42, the server's ability to redirect a resource URL without ending slash to one with, is no longer present.
This PR adds an interceptor to make sure resource URLs/apps are redirected properly with an appending slash.
AuthTest#testRedirectMissingEndingSlash()
1. Log in as normal
2. Manually enter a URL like this: http://localhost:8080/dhis-web-dashboard
3. Observe you get redirected to: http://localhost:8080/dhis-web-dashboard/
[DHIS2-17493](https://dhis2.atlassian.net/browse/DHIS2-17493)
[DHIS2-17493]: https://dhis2.atlassian.net/browse/DHIS2-17493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix broken redirect when missing trailing slash

- dhis-2/dhis-web-apps/pom.xml
- dhis-2/pom.xml
GitHub and Jenkins builds fail often because of
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-npm (install node and npm) on project 
dhis-web-apps: Could not download Node.js: Could not download https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.gz: 
Premature end of Content-Length delimited message body (expected: 32,399,497; received: 2,269,184) -> [Help 1]
```
We are using [Node.js to `git clone`](https://github.com/dhis2/dhis2-core/blob/cb0dad1ff6d886c2a8ab1f6c5e6028cac60af5de/dhis-2/dhis-web-apps/scripts/bundle-apps.js#L35) the [bundled web apps](https://github.com/dhis2/dhis2-core/blob/cb0dad1ff6d886c2a8ab1f6c5e6028cac60af5de/dhis-2/dhis-web-apps/apps-to-bundle.json#L2).
Node.js is already installed on …
> ci: use existing node installation on CI

- dhis-2/dhis-web-apps/pom.xml
follow up to https://github.com/dhis2/dhis2-core/pull/18612
Only `CI=false` activated the local profile but not setting the `CI` env explicitly did not. So `./dhis-2/build-dev.sh` did not bundle the apps no my machine. This change fixes that.
> ci: activate the local profile when CI env and absent

- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
backport of
* https://github.com/dhis2/dhis2-core/pull/18612
* https://github.com/dhis2/dhis2-core/pull/18617
> ci: use existing node installation on CI [2.39]

- dhis-2/dhis-web-apps/pom.xml
- dhis-2/pom.xml
temporary revert
- https://github.com/dhis2/dhis2-core/pull/18612
- https://github.com/dhis2/dhis2-core/pull/18617
for now. For some reason the webapps are cloned but not packaged into the `dhis.war` in CI.
> ci: revert to using the frontend plugin to bundle apps

- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
This reverts commit 82e8e07dd313c0ace6d0d08a97dc750b4e58e781.
see https://github.com/dhis2/dhis2-core/pull/18624
> ci: revert to using the frontend plugin to bundle apps [2.39]

- .github/CODEOWNERS
to changes in code that is clearly owned by the tracker team. I do not want to invest much time in making this an exhaustive list. When we reduced the number of modules we should cover most of our code with one or two lines.
> chore: automatically add tracker-backend as reviewers

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/EventWithoutRegistrationPreProcessor.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerCreateRelationshipSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
We see
```
Error:  Failures: 
Error:    TrackerEventSMSTest.shouldCreateEventInEventProgram:532 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <PROCESSED> but was: <FAILED>
```
only on Jenkins. It is due to an NPE at [EventWithoutRegistrationPreProcessor](https://github.com/dhis2/dhis2-core/blob/cc7c00e285e44f52c772a6b38bf2b54d68760f6c/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preprocess/EventWithoutRegistrationPreProcessor.java#L48
) because the `event.programStage` is null.
The reason we see the NPE on Jenkins and not on GH is the different order of preprocessors. I can make the test fail consistently on GH and Jenkins using Springs `@Order` making `EventWithoutRegistrationPreProcessor` run before …
> test: fix test failure on Jenkins

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CommandSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DataValueSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DhisMessageAlertListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/J2MEDataValueSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/UnregisteredSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SingleEventListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SmsImportMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/TrackedEntityRegistrationSMSListener.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/utils/Assertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/SmsTestUtils.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerCreateRelationshipSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
As a reference [this is](https://github.com/dhis2/dhis2-core/blob/998f7cc3c5a1271fd7742adf1253521f8e66e234/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/SingleEventListener.java#L112) the `SingleEventListener` processing logic before we made our changes to sms processing. You can see that users were able to create an event in an event program. The logic of creating the dummy enrollment into the event program is done by the metadata importer.
This is how an sms for an sms command can look like
```
{
"text": "visit s=yes|c=no|h=14|",
"originator": "+233223232"
}
```
The exact details of the format depend on how you configure the command you create
* https://docs.dhis2.org/en/use/user-guides/dhis-core-version-241/maintaining-the-system/mobile.html?h=sms+2.41# …
> fix: use tracker importer in SingleEventListener DHIS2-17729

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
Remove username validation on login to allow for pre 2.38 style username. Stricter username constraint was introduced in 2.38 and was only enforced on user creation and update. In 2.41 we introduced a new login page that utilize a new back-end controller and logic to validate the username before it is looked up in the database. This fix just removes this check as it is not really necessary.
AuthenticationControllerTest#testSuccessfulLoginWithOldUsername()
1. Start a new 2.37 instance.
2. Create a user with a username that is not allowed in 2.38+, for example "Üsername".
3. Upgrade the instance to 2.41.
4. Try to log in with the "Üsername" username.
5. Observe you get logged in.
> fix: remove username validation to allow old usernames on login

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
Reintroduces attributeValues at the /me endpoint. This value was removed from the response some time in 2.38.
Value is now deserialized in the payload as in any other BaseIndentifiableObejcts.
MyControllerTest#testGetCurrentUserAttributeValues()
1. Create an attribute on the User object.
2. Set an attribute value on your (logged in user).
3. Check endpoint /me return a JSON with the attributeValues field, and that it contains the value you set in step 2.
> fix: add back attribute values at /me endpoint

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterSimpleBeanPropertyFilter.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/Defaults.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonCategoryCombo.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonDataElement.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryComboControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionComboControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataElementControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/StreamingJsonRootMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/StreamingJsonRoot.java
> fix: Exclude defaults fix [DHIS2-17564](2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/command/SMSCommand.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/incoming/IncomingSmsListener.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/job/InboundSmsProcessingJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/AggregateDataSetSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CommandSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CompressionSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DataValueSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DhisMessageAlertListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/J2MEDataValueSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/UnregisteredSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/AggregateDataSetSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/DataValueListenerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/DeleteEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/RelationshipSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SimpleEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SingleEventListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SmsImportMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/TrackedEntityRegistrationSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/TrackerEventSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/package-info.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SmsUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/SmsUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsInboundController.java
Minor changes:
* remove unused code
* `SmsInboundController`: move vars close to usage for clarity, remove null check if return values are guaranteed to be `@Nonnull`
* remove unnecessary code in command listeners as `getSuccessMessage`/`getMoreThanOneOrgUnitMessage` never returns `null`
Use of `UserDetails`:
Most SMS processing code uses the `username` to set a `storedBy` field. Some code interested in whether a user has one or multiple `orgUnits`. Pass in the `UserDetails` of the `InboundSmsProcessingJob`.
* ensure that `IncomingSms.createdBy` = `CurrentUser` running the `InboundSmsProcessingJob` as that is what the listeners now assume. Validate that at the beginning of the job. Right now only the `SmsInboundController` is the only place where such sms jobs are created.
* …
> chore: finish up sms move to importer DHIS2-17729

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceProgramDataElementTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerImporterServiceTest.java
Failing tests were missing the authenticated user and `CurrentUserUtil.getCurrentUserDetails` was throwing an exception.
They are flaky tests because depending on the order of tests, some setup was setting the user and not cleaning up the context.
> fix: Fix flaky unit tests missing authenticated user

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/SmsConsumerThread.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/SmsPublisher.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CommandSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/ProgramStageDataEntrySMSListener.java
The UserDetails [refactoring](https://github.com/dhis2/dhis2-core/pull/15727) in 41 broke incoming SMS processing.
The sms processing code 
* https://github.com/dhis2/dhis2-core/blob/db185d69bef00986903510c156860f07e051fcdd/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CommandSMSListener.java#L241
* and any code then using hibernate to update the `IncomingSms` state https://github.com/dhis2/dhis2-core/blob/db185d69bef00986903510c156860f07e051fcdd/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java#L173-L175
* Set the system user in the sms consumer thread.
* Use `stream` instead of `parallelStream` as we would need to set the user on those threads as well. We used the same strategy on …
> fix: set sms.createdBy consumer thread DHIS2-18187 [2.41]

- .github/workflows/run-tests.yml
- dhis-2/dhis-support/dhis-support-jdbc/pom.xml
- dhis-2/dhis-web-server/pom.xml
- dhis-2/dhis-web-server/src/test/java/org/hisp/dhis/auth/AuthTest.java
- dhis-2/pom.xml
- dhis-2/run-api.sh
- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
Before we had to add `--activate-profiles -default` which excludes the `default` profile to run all tests. That is confusing. The default is now that we run all types of tests by default. This way we cannot miss any tests in a pipeline due to forgetting to remove the default profile. So with these changes
* `mvn test` - runs all tests
* `mvn test --activate-profiles unit-test` - only runs unit tests
* `mvn test --activate-profiles integration-test` - only runs postgres integration tests annotated with `@Integration`
* `mvn test --activate-profiles integration-h2-test` - only runs H2 integration tests annotated with `@IntegrationH2`
On Jenkins we simply do `mvn clean install` which runs all tests and creates the war. We can do that since the machines running Jenkins have more resources …
> ci: run all test on mvn test by default

- dhis-2/dhis-web-server/src/test/java/org/hisp/dhis/auth/AuthTest.java
In https://github.com/dhis2/dhis2-core/pull/18669 I correctly tagged [AuthTest](https://github.com/dhis2/dhis2-core/blob/3347ce79cff50bbd9d3ff06f70077e7ffe21a4e0/dhis-2/dhis-web-server/src/test/java/org/hisp/dhis/auth/AuthTest.java#L69-L71) as an integration test and included its project in our workflows so it actually runs. For some reason we see the following after merging the PR
```
2024-10-10T04:27:59.6850220Z INFO: Initializing ProtocolHandler ["http-nio-63829"]
2024-10-10T04:27:59.7106439Z Oct 10, 2024 4:27:59 AM org.apache.catalina.core.StandardService startInternal
2024-10-10T04:27:59.7107966Z INFO: Starting service [Tomcat]
2024-10-10T04:27:59.7109425Z Oct 10, 2024 4:27:59 AM org.apache.catalina.core.StandardEngine startInternal
2024-10-10T04:27:59.7239881Z INFO: Starting Servlet …
```
> test: disable dhis-web-server AuthTest

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
(cherry picked from commit 3f202cc74b9ceb72b17beb257fc7fb3d34bd55fa)
> fix: remove username validation to allow old usernames on login (#18718)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
**BACKPORT**
The Analytics API is not returning data for DataElementOperand dimensions passed in the filter parameter. The missing functionality needs to be added to the codebase.
> fix: No data returned for data element details/operands as filter [2.39-DHIS2-18182-backport]

- dhis-2/pom.xml
When using sonar and maven, this "projectKey" is usually extracted automatically. However, since it seems the check is failing, I am adding this explicitly to attempt to fix the issue.
> chore: Add property projectKey to sonar

- dhis-2/build-docker-image.sh
The major version of the version to be built was incorrectly compared to the latest major version we have in the `stable.json` file even if the version to be built was not the latest major version.
This was tested locally by the following command and with modifying the script to exit early without actually building anything, but just listing the rolling and immutable tags that would be created:
```
$ echo "42.0.0 41.2.0 41.1.0 40.5.0 40.4.2 40.4.0 39.5.1" | xargs -n 1 -I {} ./dhis-2/build-docker-image.sh -t "{}"
New major, new minor or new/existing patch for the latest minor version, creating M.m and M tags.
Immutable tag:
42.0.0-20240919T143148Z
Rolling tags:
42.0.0 2.42.0.0 42.0 42 2.42.0 2.42
New major, new minor or new/existing patch for the latest minor version, creating M.m and M …
```
> ci: fix build docker image script for non-latest major versions [skip ci]

- dhis-2/build-docker-image.sh
https://github.com/dhis2/dhis2-core/pull/18622
> backport: ci: fix build docker image script for non-latest major versions [skip ci] [2.40]

- dhis-2/build-docker-image.sh
https://github.com/dhis2/dhis2-core/pull/18622
> backport: ci: fix build docker image script for non-latest major versions [skip ci] [2.39]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/DataElementMergeTest.java
- disable DB constraint test during data element merge for min max elements
- test started failing in GitHub only (setup stage, posting metadata - 409 response)
- not failing locally when run in isolation nor when whole suite run
- possible that some other test state is not being cleaned up correctly, impacting this test
- tried removing some metadata UIDs in setup where possible and changing others, but still failed in GitHub only
> chore: disable e2e test which started failing on GitHub for no obvious reason

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18807 fixing https://dhis2.atlassian.net/browse/DHIS2-18226
> fix: Set lastUpdatedBy when creating relationships [DHIS2-18226](2.39)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManagerTest.java
This pull request improves the readability of `JdbcTrackedEntityAnalyticsTableManager` class and ensures confidential attributes are not exported.
> fix: TEAs marked as Confidential are now skipped [DHIS2-18230]

- jenkinsfiles/dev
- jenkinsfiles/stable
https://github.com/dhis2/dhis2-core/pull/18834
The pipeline build is failing after the PR above because the value we pass to the Compose `--project-name` option is not valid, as it contains a `.`, but given that we only run tests for a single Tomcat version now, we can remove the project name altogether.
> ci: remove compose project name option after migrating to v2 [skip ci]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityfilter/EntityQueryCriteria.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityFilterServiceTest.java
This PR addresses an issue with the CustomWorkingList feature where the backend consistently set `followup = false` during saving. The problem occurred because the client did not send any followup information, and the backend had `Boolean followup = false` as a default value. Fixed it by removing default value allowing the backend to correctly handle values provided by the client.
> fix: Incorrect follow-up value while saving working list[DHIS2-18206]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_update_datavalue_same_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_with_data_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_without_date.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/three_events_with_different_dates.json
- dhis-2/pom.xml
Backport of https://github.com/dhis2/dhis2-core/pull/18508 and https://github.com/dhis2/dhis2-core/pull/18736
> chore: Load all events for rule-engine context [DHIS2-18089](2.40)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_update_datavalue_same_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_with_data_value.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_without_date.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/three_events_with_different_dates.json
- dhis-2/pom.xml
Backport of https://github.com/dhis2/dhis2-core/pull/18508 and https://github.com/dhis2/dhis2-core/pull/18736
> chore: Load all events for rule-engine context [DHIS2-18089](2.39)

- jenkinsfiles/dev
- jenkinsfiles/stable
The project name option for compose is needed in versions 41, 40 and 39, because we still build and test with two Tomcat versions there (9.0 and 8.5).
> ci: add project name opt to compose when building multiple Tomcat versions [skip ci]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/EnrollmentMapper.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/EnrollmentImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_enrollment_event.json
Complete data (`completedDate` and `completedBy`) were set to null if an enrollment was updated without changing the status.
Mappers work under the implicit assumption that the preheat object is populated with all the necessary fields that were calculated by the system in previous imports (`created`, `createdBy`...).
That wasn't true for complete data for enrollment.
Integration tests are needed in this case to ensure that the preheat mapping and the bundle mapping work fine together.
I also created a task to review preheat mappers for tracker objects https://dhis2.atlassian.net/browse/DHIS2-18245
> fix: Map completed data in preheat for enrollment [DHIS2-18225]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapper.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/EnrollmentImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_enrollment_event.json
Backport of https://github.com/dhis2/dhis2-core/pull/18850
> fix: Map completed data in preheat for enrollment [DHIS2-18225](2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceSupportService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityControllerTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceSupportServiceTest.java
As reported in https://dhis2.atlassian.net/browse/DHIS2-17173, using the old API, it's possible to retrieve attributes the user shouldn't have access to. This occurs because that endpoint returns PAs as long as the user has access to at least one program, even if the accessible program does not contain those specific PAs.
To resolve this issue, I am applying the approach we are using in the new API, where:
- If the program is supplied in the request, we return the requested attribute if it's present in the given program.
- If the program is not supplied in the request, we return the requested attribute if it's present in the tracked entity type attributes.
> fix: Add program param in attribute image endpoint [DHIS2-17173][2.41]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/TrackedEntityInstanceSupportService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceControllerTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/service/TrackedEntityInstanceSupportServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/18859
> fix: Add program param in attribute image endpoint [DHIS2-17173][2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/event/EventManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackedEntityDataValueChangeLogTest.java
One of the deprecated APIs (`EventController @PutMapping(value = "/{uid}/{dataElementUid}"`) was used in such a way to update a single event data value (add,update or delete) within an event. This was used in the old Tracker Capture app which invoked the endpoint whenever the event data value field got onBlurred. 
This pathway did not add Audit/ChangeLog entries in the `trackedentitydatavalueaudit` table. This PR adds the required change log entries by calling the relevant method rightafter the event changes are persisted.
Although the test classes are outdated (no more in master), I refactored it a bit to move an assertion helper on a TrackedEntityDataValueChangeLog into the tracker/Assertions class which is then reused in 2 Test Classes.
> fix: (2.41) Add change logs when updating event data value individually [DHIS2-18138]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/EventManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityDataValueAuditTest.java
Backport of [DHIS2-18138](https://dhis2.atlassian.net/browse/DHIS2-18138)
[DHIS2-18138]: https://dhis2.atlassian.net/browse/DHIS2-18138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (2.40) Add audit change logs when updating event data value individually [DHIS2-18138]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterService.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/events/events.json
Backport of https://github.com/dhis2/dhis2-core/pull/18871 to fix https://dhis2.atlassian.net/browse/DHIS2-18252
> fix: Always use system time for createdAt in events [DHIS2-18252](2.41)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-test-e2e/src/test/resources/tracker/importer/events/events.json
Backport of https://github.com/dhis2/dhis2-core/pull/18871 to fix https://dhis2.atlassian.net/browse/DHIS2-18252
> fix: Always use system time for createdAt in events [DHIS2-18252](2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/EventManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityDataValueAuditTest.java
> fix: (2.39) Add audit change logs when updating event data value individually [DHIS2-18138]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OpenApi.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OpenApiControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Api.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiExtractor.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiIntegrator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiObject.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiRenderer.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
`@JsonProperty` has the `access` attribute which can specify read-only or write-only special cases.
OpenAPI can express a read-only schema property by marking it `readOnly:true`. 
These two needed to be connected.
In addition, to the obvious connection when generating input params schemas from output schemas the access needs to act as a filter removing all _read-only_ properties. 
To allow overrides access and specify it in added properties the `@OpenApi.Property` annotation also got an `Access` attribute.
The `/api/openapi/openapi.html?domain=JobConfiguration` is a good example. 
* compare  `/api/openapi/openapi.html?domain=JobConfiguration#JobConfiguration` and it's input version `/api/openapi/openapi.html?domain=JobConfiguration#JobConfigurationParams` and note that the that has much …
> feat: OpenAPI considers property access [DHIS2-18265]

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonAttributeValueBinaryType.java
This PR makes the `JsonAttributeValueBinaryType` more reliable against bad data in the `attributevalues` JSONB column in metadata tables like `organisationunit`.
A null key in the JSONB column will lead to an exception from Jackson.
```
com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON
```
> fix: Safely serialize JSON map [DHIS2-18253] [2.40]

- .github/workflows/run-api-tests.yml
- .github/workflows/run-tests.yml
- dhis-2/dhis-test-coverage/pom.xml
- dhis-2/dhis-web-server/pom.xml
- dhis-2/pom.xml
These are the [maven lifecycles](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#default-lifecycle) which we can execute. We can also bind 
maven plugins (or some of their commands aka goals) to a phase, some are bound to a phase by default.
| Phase                   | Description                                                                                       |
|-------------------------|---------------------------------------------------------------------------------------------------|
| validate                 | Validate the project is correct and all necessary information is available.                       |
| initialize               | Initialize build state, e.g., set properties or create directories.                               |
| …
> ci: don't download webapps when only running tests

- .github/workflows/codeql-analysis.yml
- .github/workflows/run-tests.yml
- CONTRIBUTING.md
- dhis-2/build-nocompr.sh
- dhis-2/dhis-test-coverage/pom.xml
- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
- dhis-2/run-api.sh
- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
backport of
* https://github.com/dhis2/dhis2-core/pull/18632 only the part of expecting Node.js to be present on the machine building DHIS2 to bundle the webapps
* https://github.com/dhis2/dhis2-core/pull/18669
* https://github.com/dhis2/dhis2-core/pull/18801
manual tests
* `./dhis-2/build-dev.sh && docker compose up` locally and check apps are bundled
* deploy PR to instance manager and check apps are bundled
* run `mvn clean test` and `mvn clean test` with individual profiles and double-check sum of tests is equal
> ci: run all test on mvn test by default [2.41]

- dhis-2/build-docker-image.sh
- jenkinsfiles/rebuild-image
When we rebuild images with [the rebuild-image pipeline](https://github.com/dhis2/dhis2-core/blob/112bd6fb4102b07d3a737528e48711503b3d10c7/jenkinsfiles/rebuild-image), we’re checking out `master` and using the latest version of the `build-docker-image.sh` script that is now defaulting to building with Tomcat 10 as base image (updated with the recent [Spring upgrade PR](https://github.com/dhis2/dhis2-core/pull/18314)) , which isn’t going to work for any version but `master` (future `42`). This is different to building in the `dev` or `stable` pipelines, because we set the `BASE_IMAGE` variable there https://github.com/dhis2/dhis2-core/blob/112bd6fb4102b07d3a737528e48711503b3d10c7/jenkinsfiles/dev#L138 and run the pipeline from the respective version branch, not just from `master`.
* Remove …
> ci: set base image in rebuild pipeline, not script [skip ci]

- .github/workflows/codeql-analysis.yml
- .github/workflows/run-tests.yml
- CONTRIBUTING.md
- dhis-2/build-nocompr.sh
- dhis-2/dhis-test-coverage/pom.xml
- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
- dhis-2/run-api.sh
- docker-compose.yml
- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
backport of
* https://github.com/dhis2/dhis2-core/pull/18632 only the part of expecting Node.js to be present on the machine building DHIS2 to bundle the webapps
* https://github.com/dhis2/dhis2-core/pull/18669
* https://github.com/dhis2/dhis2-core/pull/18801
manual tests
* `./dhis-2/build-dev.sh && docker compose up` locally and check apps are bundled
* deploy PR to instance manager and check apps are bundled
* run `mvn clean test` and `mvn clean test` with individual profiles and double-check sum of tests is equal
> ci: expect node.js on build machine [2.40]

- .github/workflows/codeql-analysis.yml
- .github/workflows/run-tests.yml
- CONTRIBUTING.md
- dhis-2/build-nocompr.sh
- dhis-2/dhis-test-coverage/pom.xml
- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/pom.xml
- dhis-2/run-api.sh
- docker-compose.yml
- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
- jenkinsfiles/stable
backport of
* https://github.com/dhis2/dhis2-core/pull/18632 only the part of expecting Node.js to be present on the machine building DHIS2 to bundle the webapps
* https://github.com/dhis2/dhis2-core/pull/18669
* https://github.com/dhis2/dhis2-core/pull/18801
manual tests
* `./dhis-2/build-dev.sh && docker compose up` locally and check apps are bundled
* deploy PR to instance manager and check apps are bundled
* run `mvn clean test` and `mvn clean test` with individual profiles and double-check sum of tests is equal
> ci: expect node.js on build machine [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OpenApi.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/BadRequestException.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ConflictException.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ForbiddenException.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/HiddenNotFoundException.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/NotFoundException.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webmessage/WebResponse.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/webmessage/WebMessage.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/JsonPatchException.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OpenApiControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Api.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiClassification.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiExtractor.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiAnnotations.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiObject.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiRenderer.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiTool.java
Provides scopes as a universal concept for global navigation.
The PR mainly provides the machinery behind the menu shown below
The main new concept are scopes. Each controller class is associated with a key-value set of classifiers. 
The `@OpenAPI.Document.classifiers()` annotation is used to add more classifiers to a controller class.
Based on these users can then compose a scope by specifying the classifiers to include. 
In the URL this is now given as a single parameter `scope`. A scope value has a classifier name and value; for example, `scope=entity.DataElement`. The `.` is used as separator as most other symbols are URL escaped making it hard to read if added to the parameters using JS.
While the scope entirely depends on the classifiers some classifiers are pre-filled from other …
> feat: scope based global navigation [DHIS2-18266]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/AssignedUserQueryParam.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UID.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/AssignedUserQueryParamTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/indicator/IndicatorMergeProcessorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapperTest.java
Use UID in EventService and propagate the change until the generic stores.
Use UID in EventOperationParams and propagate until the generic stores and until tracker stores when building the queries.
EventRequestParams are already using UIDs.
EventOperationParams are now using UIDs. `dataElementFilters` and `attributeFilters` are going to be changed in next PR.
EventQueryParams is using hibernate object to build the query. A few fields are using UID and they are passed to the store and the value is used to build the query.
There is a quick fix in `UID` object to make tests work with `SystemUser`. It will be fix soon in https://dhis2.atlassian.net/browse/DHIS2-18296
Next steps*
Harmonize UID in Filters
Harmonize UID in …
> chore: Use UID in event exporter [DHIS2-17790]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
Small fix for a check that checks if an email server is properly configured. Recent changes to the SystemSettings inverted one part of the if condition.
SystemSettingTest#testEmailIsConfigured()
1. Go to the "System Settings" app
2. Go to "Email" settings in the left pane meny
3. Enter any valid hostname (we don't need an actual one, just need to have valid syntax) and same with the username.
4. Press "Send me a test email"
5. This should result in an error saying: "Could not send test email, no email configured for current user" if you are using the default admin user which do not have an email configured. The error should NOT say: "SMTP server not configured", as described in the Jira. If you configure a real SMTP server and add a real email to the user you are testing with, it should …
> fix: system setting check for email configured

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidatorTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapperTest.java
Use UIDs in EventOperationParams for  `dataElementFilters` and `attributeFilters` fields.
Next steps*
Harmonize UID in Relationship
Harmonize UID in TrackedEntity
Harmonize UID in OperationsParamsValidator
> chore: Use UID in event filters [DHIS2-17790]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerCreateRelationshipSMSTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
Use UID in RelationshipService and propagate the change until the generic stores.
Next steps*
Harmonize UID in TrackedEntity
Harmonize UID in OperationsParamsValidator
> chore: Use UID in relationship exporter [DHIS2-17790]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ForbiddenException.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapperTest.java
Use UID in TrackedEntityService and propagate the change until the generic stores.
Use UID in TrackedEntityOperationParams and propagate until the generic stores and until tracker stores when building the queries.
TrackedEntityarams are already using UIDs.
TrackedEntityOperationParams are now using UIDs. Enhance the API to make the builder accept UID and UidObject types.
TrackedEntityQueryParams is using hibernate object to build the query. A few fields are using UID and they are passed to the store and the value is used to build the query.
Next steps*
Harmonize UID in OperationsParamsValidator
> chore: Use UID in trackedEntity exporter [DHIS2-17790]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstageworkinglist/ProgramStageQueryCriteria.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/programstageworkinglist/JsonProgramStageQueryCriteria.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/programstageworkinglist/ProgramStageWorkingListControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-18279
This PR refactors the `ProgramStageQueryCriteria` class to change the `followUp` field from a `boolean` primitive to the `Boolean` wrapper type. This update allows `followUp` to hold three possible states: true, false, and null.
> fix: (2.40) Incorrect follow-up value while saving program working list[DHIS2-18279]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UID.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/message/ProgramMessageOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/notification/ProgramNotificationTemplateOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/OperationsParamsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/OperationsParamsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/message/ProgramMessageRequestParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/notification/ProgramNotificationTemplateRequestParamsMapperTest.java
Use UID in OperationsParamsValidator.
Add a new static method in UID object to generate a UID.
Next steps*
> chore: Use UID in OperationParamsValidator [DHIS2-17790]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerPostgresTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
Syntatic sugar to make operationParams APIs easier to use.
Next steps*
> chore: Clean up operation params APIs [DHIS2-17790]

- dhis-2/dhis-web-server/pom.xml
- dhis-2/pom.xml
- jenkinsfiles/dev
- jenkinsfiles/rebuild-image
- jenkinsfiles/stable
We are only building/testing against one version of Tomcat on master since https://github.com/dhis2/dhis2-core/pull/18787
* remove the Tomcat matrix remnants from the jenkins pipeline (used before https://github.com/dhis2/dhis2-core/pull/18787)
* undo move of jib/tomcat version related properties done in https://github.com/dhis2/dhis2-core/pull/17040 back to the dhis-web-server/pom.xml. Like any other var its best to keep its scope minimal. These properties are not used anywhere else. Having them in the root makes it complex to override and understand where the actual values are coming from in the build of the war/Docker image.
* remove unused plugin `cargo-maven2-plugin`
* keep version of our embedded tomcat and Docker base image in sync by reusing the `tomcat.version` property
Tests
* …
> ci: keep war/Docker image Tomcat version in sync

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserServiceTest.java
* fix: don't expose password in logs on invalid input
(cherry picked from commit 3f53d8a4c3f951158c75d955ed0a76a5b03f8316)
> fix: don't expose password in logs on invalid input (#18156)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UID.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/SystemUser.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserDetails.java
This PR is making interface `UserDetails` extending the `UidObject` interface and making `SystemUser` return a valid uid string for method `getUid`.
I choose the string `XXXXXSystem` as uid for `SystemUser` but I am open to suggestions.
I just remove from `UID` object the quick fix I introduced in a previous [PR](https://github.com/dhis2/dhis2-core/pull/18902) to make tests pass.
> chore: Make SystemUser return valid uid [DHIS2-18296]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UID.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/deduplication/hibernate/PotentialDuplicate.hbm.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/MergeObject.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicate.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateCriteria.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/supplier/UniqueAttributesSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/UIDUserType.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateStoreRelationshipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateStoreTEAVTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/JsonPotentialDuplicate.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationMvcTest.java
Use UID in DeduplicationService and propagate the change.
Use UID in PotentialDuplicateCriteria.
Use UID in PotentialDuplicate. This is a Hibernate object so in order to be persisted a new `UIDUserType` was created.
Add @JsonValue annotation on `UID` `toString` method in order to be serialized as a String.
Next steps*
> chore: Use UID in Deduplication [DHIS2-17790]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
Found the issue while working on https://github.com/dhis2/dhis2-core/pull/18943. It's already fixed on master.
Added assertion to existing test test. Example failure before the fix
```sh
[ERROR] Failures:
[ERROR]   EventExporterTest.shouldReturnEventsWithNotes:195->assertNotes:1267 note assertions (2 failures)
org.opentest4j.MultipleFailuresError: note assertions DRKO4xUVrpr (2 failures)
org.opentest4j.AssertionFailedError: created ==> expected: <2024-10-30T15:13:56.318> but was: <2024-10-30T00:00:00.000>
org.opentest4j.AssertionFailedError: lastUpdated ==> expected: <Wed Oct 30 15:13:56 CET 2024> but was: <2024-10-30>
org.opentest4j.MultipleFailuresError: note assertions SGuCABkhpgn (2 failures)
org.opentest4j.AssertionFailedError: created ==> expected: <2024-10-30T15:13:56.318> but was: …
```
> fix: /tracker/events exports notes with timestamps instead of dates [2.39]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
Found the issue while working on https://github.com/dhis2/dhis2-core/pull/18943. It's already fixed on master.
Added assertion to existing test test. Example failure before the fix
```sh
[ERROR] Failures:
[ERROR]   EventExporterTest.shouldReturnEventsWithNotes:192->assertNotes:1190 note assertions (2 failures)
org.opentest4j.MultipleFailuresError: note assertions DRKO4xUVrpr (2 failures)
org.opentest4j.AssertionFailedError: created ==> expected: <2024-10-30T14:54:18.037> but was: <2024-10-30T00:00:00.000>
org.opentest4j.AssertionFailedError: lastUpdated ==> expected: <Wed Oct 30 14:54:18 CET 2024> but was: <2024-10-30>
org.opentest4j.MultipleFailuresError: note assertions SGuCABkhpgn (2 failures)
org.opentest4j.AssertionFailedError: created ==> expected: <2024-10-30T14:54:18.037> but was: …
```
> fix: /tracker/events exports notes with timestamps instead of dates [2.40]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
the fix for the issue came in
https://github.com/dhis2/dhis2-core/pull/18943
I tested it in part by asserting the /events/{uid} body is equal to /events?events={uid}. The test could hide a regression if we were to not return notes at all in both bodies.
Cherry-picking the assertion from the backport
https://github.com/dhis2/dhis2-core/pull/18949
as this test does not suffer from the above test issue and it points us directly to the root cause.
> test: improve test for exporting tracker event notes DHIS2-18319

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/dataelement/handler/MetadataDataElementMergeHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/dataelement/DataElementMergeProcessorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/dataelement/MetadataDataElementMergeHandlerTest.java
Caught in QA testing.
Updating the `DataSetElement` refs was resulting in inconsistent behaviour and could be different for each merge.
Sometimes the target `DataElement` wasn't showing in the updated `DataSet` in the UI and sometimes it was.
The `DataSetElement` was being updated correctly, but the source `DataElement` still held a reference to it in its collection. And if the source `DataElement` was being deleted as part of the merge, the `DataSetDeletionHandler` was removing all `DataSetElement`s for the source `DataElement`, thus resulting in the already updated `DataSetElement` being removed from the `DatsSet`.
This model (`DataElement`, `DataSetElement` & `DataSet`) is multidirectional so it has to be handled in a very specific way.
Was eventually able to recreate the condition in …
> fix: Fix data element merging of data set elements [DHIS2-14429]

- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/RegexUtilsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManagerTest.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/TextUtils.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/util/TextUtilsTest.java
This PR makes the `replaceAndQualify` method better, but removing the unnecessary requirement of specifying the names of variables to be qualified. Instead, the method looks at the specified variable name/value mapping, and then qualifies remaining variables. This will simplify the handling of SQL statements for populating the analytics database tables. See DHIS2-16705.
Removes unused method.
Adds unit tests.
> refactor: Replace without specifying variables to qualify [DHIS2-16705]

- .github/workflows/analyse-pr.yml
- .github/workflows/codeql-analysis.yml
Save GH compute/quota. We don't expect any different results when running these workflows on dependabot PR.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
Dependabot does [not have access to org/repo secrets by default](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#adding-an-organization-secret-for-dependabot). This caused the sonar workflow to fail.
Our options were
1. add the secrets
2. don't run workflows that are not necessary for dependabot PRs
https://github.com/dhis2/dhis2-core/blob/master/.github/workflows/analyse-pr.yml is a required workflow. Not sure if we can make an exception to not require the sonar workflow on …
> ci: don't run analysis workflows for dependabot

- dhis-2/dhis-web/dhis-web-portal/pom.xml
- jenkinsfiles/dev
- jenkinsfiles/rebuild-image
- jenkinsfiles/stable
Backport of https://github.com/dhis2/dhis2-core/pull/18899
Requested review from everyone that has been involved in discussing this one way or another, mostly for visibility.
> ci: remove building/testing with tomcat 8.5 [2.39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobRunErrors.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/IdSchemesTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/db/sql/PostgreSqlBuilderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/icon/JdbcIconStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/JdbcTrackedEntityChangeLogStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/StatusUpdateValidator.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryComboModificationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SchemaBasedControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SmsGatewayControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/pom.xml
https://github.com/google/google-java-format/releases
`google-java-format` was set to the default version of https://github.com/google/google-java-format/releases/tag/google-java-format-1.8 from May 2020.
https://github.com/diffplug/spotless/tree/main/plugin-maven#google-java-format
They do fix bugs and add support for new language features. They also stop supporting running on old JDKs at some point
https://github.com/google/google-java-format/releases
> This is the last planned release of google-java-format that will support running on JDK 11
So I don't think we can never update it and have to accept some formatting changes once in a while.
It looks like text block formatting is still under debate
https://github.com/google/google-java-format/issues/1087#issuecomment-2016582504
> ci(deps): update google-java-format

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/Dashboard.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/embedded/EmbeddedDashboard.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/embedded/EmbeddedOptions.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/embedded/EmbeddedProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/embedded/FilterOptions.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dashboard/hibernate/Dashboard.hbm.xml
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSetting.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_23__Add_embedded_to_dashboard.sql
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/org/hisp/dhis/usertype/UserTypes.hbm.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dashboard/DashboardServiceTest.java
This PR adds a object EmbeddedDashboard properties to the Dashboard entity meant to represent an embedded dashboard.
* provider refers to the provider of embedded dashboards, and can be extended to Power BI, Tableau and the like later.
* id refers to the identifier of the embedded dashboard defined by the external provider.
* options refers to customization options from the embedded dashboard provider, and can be extended later.
Adds a system setting for enabling Superset embedded dashboards.
> feat: Add embedded dashboard [DHIS2-18239]

- dhis-2/pom.xml
As discussed in the backend meeting: do not apply
https://sonarcloud.io/organizations/dhis2/rules?open=java%3AS1117&rule_key=java%3AS1117
in tests.
> ci: ignore java:S1117 for tests

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DataQueryServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/DataQueryServiceTest.java
For analytics operations the authenticated user must have permission to export and analyze data for the designated organization units. If no organization unit permissions  are explicitly granted, data capture and maintenance rights will be applied instead.
> feat: Fallback for User analysis org is referred to user capturing org [2.42-DHIS2-13498_2]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SchemaControllerTest.java
Using `Boolean` instead of `boolean` in the setters somehow made the properties in question non-persisted and non-writable. 
Likely the issue was that getter and setter were using different types (boolean vs Boolean) resulting in not finding the setter and from that concluding that the property isn't writable or persisted.
Adds a test that makes sure all boolean `*Attribute` properties are persisted and writable. 
* goto `/api/schemas/attribute` 
* check the JSON for `"properties"` and make sure all booleans with a suffix name of "Attribute" are considered both `"writable"` and `"persisted"`.
> fix: consider all attribute flag properties as persisted and writable [DHIS2-18297]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/TrackerObjectsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/domain/Note.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/supplier/strategy/NoteStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerIdentifierCollectorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerObjectsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/EachTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/NoteMapper.java
***Big Picture***
At the moment, tracker objects uids are represented as strings because the are validated in the importer and they can represent an invalid UID.
We are now changing this and tracker objects are going to use UID object instead so the validation of UIDs is happening when binding the body object in the API.
This allows the importer to not worry anymore on the UIDs for tracker objects as they now are valid and not null (this is guaranteed by the `BodyConverter` that is initializing all the UIDs).
***What is in this PR***
This PR is changing the importer domain for `Note`.
***What is next***
- Change API view model
- Handle TODO left in `Event` PR
> chore: Use UID for notes in tracker importer [DHIS2-17790]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultAnalyticsServiceTest.java
This PR improves the CSV Export when the combinations of dimensions explode into huge numbers.
Before this change, when exporting a CSV, all possible rows would be generated, just to check if they had a value in the query result. While the result is correct, the approach seemed to not consider performance implications when the cartesian product of all dimensionalItems is big.
This PR improves it by generating only the rows that exist in the query result.
> perf: improves CSV exports when too many dimensions combinations exists [DHIS2-18377]

- dhis-2/run-api.sh
Fixes a check for the `DHIS2_HOME` environment variable in the bash script `run_api.sh`.
The script was using `-v` when it should have been using `-n`, `-v` means to check if a variable is set, but can not be used with the `[[` syntax, `-n` should be used instead, this checks if a variable is not empty.
> fix: broken run-api.sh environment variable check

- dhis-2/dhis-services/dhis-service-tracker/pom.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/utils/Assertions.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/IdSchemeExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/MetadataMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventMapper.java
support `/tracker/events?categoryOptionIdScheme`
This does not yet deal with the default category option in any special way. Default category options are automatically created [by DHIS2 itself](https://github.com/dhis2/dhis2-core/blob/88f29f8ea1547c14b6b0230f0b902c9fb916bf1c/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/DefaultCategoryService.java#L555-L556). They don't have `attributeValues` and users can also not add any.
This means that we will have to either
* treat them as not having the requested idScheme as part of the error handling we will soon add
* or create an exception and for example show their metadata attribute values as `default`
Category option combos represent the combination of one or more category options. For example
Category option …
> feat: support /tracker/event?categoryOptionIdScheme DHIS2-14968

- .github/workflows/run-api-tests.yml
API-TEST sometimes are not run automatically, even though they are required (it happens quite frequently with dependabot PRs) and it is needed to add the run-api-tests label in order to unblock the PR.
This PR aims to remove the dependency of the api-tests github action on the label
> ci: Do not require label to run api tests (2.40)

- .github/workflows/run-api-tests.yml
API-TEST sometimes are not run automatically, even though they are required (it happens quite frequently with dependabot PRs) and it is needed to add the run-api-tests label in order to unblock the PR.
This PR aims to remove the dependency of the api-tests github action on the label
> ci: Do not require label to run api tests (2.39)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
We allow ordering by `trackedEntity` (UID) and therefore add a left join on the TE. (There might be another reason see below).
https://github.com/dhis2/dhis2-core/blob/8b61e44d959a0d9c90386c10fcd62e6d53f4dc91/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java#L213
We do not use the TE orgUnit for anything AFAIK. Remove the left join on the TE orgUnit.
Not sure if anyone using the `EventService` needs the `enrollment.trackedEntity.uid` which is what we set using the left join on the TE. If not we could also only add that join if users order by `trackedEntity`.
> chore: remove unnecessary join on TE orgUnit DHIS2-14968

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/query/EnrollmentQuery.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
The query collecting enrollments in tracked entity store was joining with the tracked entity organisation unit instead of the enrollment one.
> fix: Fix enrollment queyr to get correct orgUnit [DHIS2-14829]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-18330
- Use got NPE when trying to delete an EventVisualization in Line Listing App.
- During metadata import preheat, Java Reflection is used to add properties to collections without null check.
- Added null check and also unit test
> fix: NPE when delete eventVisualization

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEventsAnalyticsTableManager.java
Add the `year` column to the list of columns for Tracked Entity, Tracked Entity Enrollment and Tracked Events analytics table.
The column is only added if the underlying analytics database supports declarative partitioning (like Doris), so it does not impact the Postgres generation.
> feat: add year column to allow Doris partitioning [DHIS2-16705]

- jenkinsfiles/stable
An issue was introduced with https://github.com/dhis2/dhis2-core/pull/18899 - development/test images built during the API test stage should be pushed to the `dhis2/core-dev` repo, not `dhis2/core`.
The error was spotted in this build - https://ci.dhis2.org/view/dhis2-core/job/dhis2-core-stable/job/patch%252F2.40.6/1/pipeline-console/
The fix was tested with a "Replay" of the build above and making the changes from this PR inline - https://ci.dhis2.org/view/dhis2-core/job/dhis2-core-stable/job/patch%252F2.40.6/2/replay/diff
> ci: push test/dev images to dhis2/core-dev [skip ci]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/OrgUnitField.java
The `OrgUnitField` can now use a `SqlBuilder` to generate correctly quoted SQL. 
Set  `OrgUnitField` to use a default `PostgresSqlBuilder` to avoid NPE whenever the class is used without `SqlBuilder`.
> fix: defaults to PostgresBuilder on OrgUnitField [16705]

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- We have the config `connection.schema` and default value is `validate` which means hibernate will throw an error on startup if a new property doesn’t exist in database.   For example: 
```Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [test] in table [organisationunit]```
- However currently this is not working because the property is not set correctly.
- When value is `update` then hibernate will auto generate tables. This is only used in H2 test.
- Note that you will also get a postgresql exception for insert/select non exist column in database.
- This only affects 2.41 and 2.42. Before that we didn't use the `HibernateJpaAdapter` and set the property directly to Hibernate Session Factory.
- Set the property …
> fix: hibernate schema validate config is not set

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/mapper/NoteRowCallbackHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Some fix done [here](https://github.com/dhis2/dhis2-core/pull/18949) but for the tracked entity endpoint.
In the `assertNotes` method the `assertEquals` on `lastUpdated` was removed as we are not mapping it to our tracker objects and its value was always null, but when saving a note using `IdentifiableObjectManager` `lastUpdated` field must be not null.
> fix: Map created date of notes as a timestamp [DHIS2-17864]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v42/V2_42_21__Add_new_column_into_visualization_and_migrate_relative_periods.java
We got a decison to backport this Jira, which has a Flyway migration.
For this reason we need to ensure this migration is not executed twice from one version to another.
The check added to this migration should ensure it runs only once.
> fix: Add check, so it can be backported [DHIS2-18020]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdSchemeParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/webapi/json/domain/JsonWebMessage.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/IdSchemeExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/MappingErrors.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/MetadataMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/MappingErrorsTest.java
Report any metadata that does not have an identifier for the requested `idScheme`.
For example
`GET http://localhost:8080/api/tracker/events/FV4JCI73wO2?idScheme=ATTRIBUTE:Y1LUDU8sWBR`
gets response
```http
HTTP/1.1 422 
{
"httpStatus": "Unprocessable Entity",
"httpStatusCode": 422,
"message": "Not all metadata has an identifier for the requested idScheme. Either change the requested idScheme or add the missing identifiers to the metadata.",
"devMessage": "Following metadata listed using their UIDs is missing identifiers for the requested idScheme:\nProgramStage[ATTRIBUTE:Y1LUDU8sWBR]=A03MvHHogjR\nCategoryOptionCombo[ATTRIBUTE:Y1LUDU8sWBR]=HllvX50cXC0\nCategoryOption[ATTRIBUTE:Y1LUDU8sWBR]=xYerKDKCefk\nProgram[ATTRIBUTE:Y1LUDU8sWBR]=IpHINAT79UW\nOrganisationUnit[ATTRIBUT …
```
> feat: report metadata without identifier for idScheme DHIS2-14968

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/cache/Region.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/event/CacheInvalidationEvent.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/cache/DefaultCacheProviderTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
- Added a new Publishable event object ( `CacheInvalidationEvent extends ApplicationEvent` ) which can be used to publish event to invalidate either specific cache regions completely or a specific key in that cache region.
- Added a new listener method in `DefaultCacheProvider` that listens to  `CacheInvalidationEvent`'s and invalidates cache regions (or specific key in that region)
- Moved the `Region` enum from dhis-support-system into dhis-api as it would need to be used across modules to be able to publish a cache invalidation event. 
- Cleaned up unused methods from `DefaultCacheProvider` and corresponding cache `Region` enums 
- Published a CacheInvalidationEvent for the Region.canDataWriteCocCache whenever Sharing settings are updated for any CategoryOption (this would fix [this …
> feat: [DHIS2-18388] Add listener for specific cache invalidation

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventChangeLogOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/HibernateEventChangeLogStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/OrderEventChangeLogTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportChangeLogsControllerTest.java
This PR introduces sorting change logs by creation date, username, data element, or event property.
Unlike other endpoints, this one allows sorting by only one element at a time. If the chosen element is not the creation date, a secondary sort will be applied by creation date to ensure the change logs are presented in a timely order.
> feat: Implement sorting on event change logs [DHIS2-18012]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserOrgUnitProperty.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/split/orgunit/OrgUnitSplitServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
Org Unit split feature is assigning the split org units to incorrect users (sometimes all the users in the DB in certain circumstances)
After creating the `UserQueryParams` with the source `OrganisationUnit`, that `OrganisationUnit` was being overridden to use the `User`'s `OrganisationUnit`s carrying out the split.
In cases where the `User` either had no `organisationUnits`, `dataViewOrganisationUnits`, or `teiSearchOrganisationUnits`, then all the `User`s in the DB would be returned from the query, resulting in all `User`s getting the split `OrganisationUnit`s.
Fix avoids using:
- `UserService#handleUserQueryParams` which was overriding the source `OrganisationUnit` already set
-  `UserStore#getUsers` which tries to generate a handcrafted SQL query taking into consideration a multitude …
> fix: Org Unit split being assigned to incorrect users [DHIS2-18423]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/utils/Assertions.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/MappingErrors.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/MappingErrorsTest.java
Make it clear that default category option (combo) cannot be exported using `idScheme=ATTRIBUTE`
```sh
curl -s 'http://localhost:8080/api/tracker/events/FV4JCI73wO2?categoryOptionComboIdScheme=ATTRIBUTE:Y1LUDU8sWBR' | jq -r .devMessage
```
```sh
Following metadata listed using their UIDs is missing identifiers for the requested idScheme:
CategoryOptionCombo[ATTRIBUTE:Y1LUDU8sWBR]=HllvX50cXC0(default)
Data linked to default category option (combo)s cannot be exported using idScheme=ATTRIBUTE as they cannot have any attribute values.
```
```sh
curl -s 'http://localhost:8080/api/tracker/events/FV4JCI73wO2?categoryOptionIdScheme=ATTRIBUTE:Y1LUDU8sWBR' | jq -r .devMessage
```
```sh
Following metadata listed using their UIDs is missing identifiers for the requested idScheme: …
```
> chore: highlight default category option (combo) in idScheme error DHIS2-14968

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/utils/Assertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/IdSchemeExportControllerTest.java
`dataElementIdScheme!=UID` filters out events without a data value while it should not.
I don't remember exactly at what stage I needed the `where`, maybe when I tried approach https://github.com/dhis2/dhis2-core/pull/19123.
`dataElementIdScheme` was introduced in
https://github.com/dhis2/dhis2-core/pull/19153
`dataElementIdScheme!=UID` adds a join from the JSONB dataValues keys on dataelement in the parent query. There cannot be an empty JSON key. The JSON key is a data element UID that is validated on import.
> fix: dataElementIdScheme should not filter events DHIS2-14968

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/TokenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/TokenOperatorTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CrudControllerIntegrationTest.java
https://dhis2.atlassian.net/browse/DHIS2-17098
- `identifiable:token:aaa` check for `name`, `code` and `uid`.
- If the token value is too short, it might be contained by a `uid` which isn't what user wants.
- Add a check to skip `uid` filter if token value is < 4
- Manual test by send GET to [api/dataElements?fields=:identifiable&filter=identifiable:token:ER](https://debug.dhis2.org/2.40dev/api/dataElements?fields=:identifiable&filter=identifiable:token:ER)
> fix: not apply identifiable token filter to uid length < 4

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventChangeLogOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/HibernateEventChangeLogStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/OrderAndFilterEventChangeLogTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportChangeLogsControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/ChangeLogRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/ChangeLogRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidatorTest.java
This PR introduces filtering for change logs. These filters differ slightly from the ones we currently use:
- They accept only one field at a time.
- They support only the equals operator.
- Filtering is limited to username, data element, or property.
Another key difference is that while our current filters are [UID based](https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java#L112), these new filters are string based.
Although the only supported operator is `eq`, I’ve retained the filter format [field]:[operator]:[filter] used in other endpoints. This way, if we need to support additional operators in the future, it won’t require a breaking change.
`validateFilter(String, …
> feat: Add filtering capabilities in events change log [DHIS2-18012]

- .github/workflows/run-tests.yml
My noob attempt to add a extra step after the junit test run to check maven dependencies.
> chore: add explicit dependency:analyze-only after unit tests

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/utils/Assertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/IdSchemeExportControllerTest.java
added in https://github.com/dhis2/dhis2-core/pull/19153
The issue was that if two events like `blZxytttTqq` and `ehxNi0D67uQ` in the SL DB have `dataValues` for the same data element only one of the events would be exported with that dataValue/element.
Example DB `eventdatavalues` JSONB column for `blZxytttTqq` and `ehxNi0D67uQ`
```json
{
"D7m8vpzxHDJ": {
"value": "P+"
},
"HmkXnHJxcD1": {
"value": "Relapse"
}
}
```
```json
{
"D7m8vpzxHDJ": {
"value": "PE"
},
"HmkXnHJxcD1": {
"value": "Relapse"
}
}
```
I made the mistake of assuming I can aggregate event `dataValues` like we do notes in the `ResultSetExtractor` of the `JdbcEventStore`. 
https://github.com/dhis2/dhis2-core/blob/34c2cff315fe04208c9241cf7dd0175ab8ac7be6/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/trac …
> fix: /events?dataElementIdScheme!=UID for shared data elements DHIS2-14968

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEventsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/AnalyticsSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/AnalyticsSqlBuilderProvider.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/ClickhouseAnalyticsSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/DorisAnalyticsSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/db/sql/PostgresAnalyticsSqlBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEventsAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/SqlComparisonUtils.java
Remaining fixes for Tracked Entity analytics table population for Apache Doris.
- removed `getPartitionColumn` from `AbstractJdbcTableManager`
- add `year` partition column to `JdbcTrackedEntityAnalyticsTableManager`
- dynamic column creation for `JdbcTrackedEntityEnrollmentsAnalyticsTableManager`
- add `year` partition column to `JdbcTrackedEntityEnrollmentsAnalyticsTableManager`
- dynamic column creation for `JdbcTrackedEntityEventsAnalyticsTableManager`
- remove json subquery for `JdbcTrackedEntityEventsAnalyticsTableManager` that is used when the datatype is `ORG_UNIT` (only for Doris)
- introduce a `AnalyticsSqlBuilder` interface and implementations to deal with the cases where platform-specific SQL has to be emitted and the standard `SqlBuilder` is too "generic" to resolve it
> Tracked Entity Analytics table population fixes for Doris (DHIS2-16705)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
`headers.location` in old tracker importer was wrong for tracked entity and enrollment.
> fix: Remove doubled api string in location header [DHIS2-12536](2.39)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deprecated/tracker/TrackedEntityInstanceController.java
`headers.location` in old tracker importer was wrong for tracked entity and enrollment.
> fix: Remove doubled api string in location header [DHIS2-12536](2.41)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
`headers.location` in old tracker importer was wrong for tracked entity and enrollment.
> fix: Remove doubled api string in location header [DHIS2-12536](2.40)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonDataValue.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/IdSchemeExportControllerTest.java
Event `dataValue.storedBy` is set on import
https://github.com/dhis2/dhis2-core/blob/9b6d958cd3c5c179ae95b3e2b59246b88c1d9381/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EventPersister.java#L229
This might not always have been the case. At least in SL DB there are `dataValues` without that property in the JSONB.
`event.eventdatavalues` being JSONB leads to a different query when `dataElementIdScheme!=UID` see  https://github.com/dhis2/dhis2-core/pull/19153. This then requires different code to aggregate the rows into the event and its `dataValues`.
I defaulted to the empty string using `dataValueJson.getString("storedBy").string("")` which meant it was exported as such. This was different than when requesting `idScheme=UID` where …
> fix: EventDataValue mapping with idScheme!=UID DHIS2-14968

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Restrictions.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/user/hibernate/User.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_32__User_name_as_generated_column.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/fieldfiltering/FieldPathHelperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractGistControllerPostgresTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistControllerPostgresTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SchemaControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
Makes the `User` `name` property a generated column that is auto-composed from `firstName` and `surname` in/by the DB.
This makes `name` a persisted property whereby `query=Xyz` also is a pure DB filter for `User`s. 
This is important to avoid the different terms in the OR clause generated from it to be split up between JPA and in-memory query because splitting would not result in the correct result as a filter like (A OR B OR C) AND X changes to (A OR B) AND X AND C (the OR bracket being created from the `query` parameter).
As a bonus this also means `name` is now a usable property in `filter` when using the Gist API.
This PR also corrects the HBM mapping where `firstName` and `surname`. They were incorrectly marked as nullable when they always have been `not null` in the DB. That means …
> fix: use generated user name column for make query DB only [DHIS2-17200]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/users/users_capture_ou_not_in_data_view_ou.yaml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityUsersCaptureOrgunitNotInDataView.java
This check was intended to identify users who can enter data in certain orgunits, but which not been given the privilege to view the data in the analysis modules. The query was not working as it should and has been adjusted.
> Fix:Data integrity check for data capture orgunits within data view orgunits

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/DateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/event/DateValidatorTest.java
Additional handling for the final expiring day.
If expiryPeriodType is Monthly. And expiryPeriodDays is 10. 
For an event occured in October 20th (for example), we would want to be able to edit the event upto and including November 10th. 
Since the period end date of the event is calculated as 202X-10-31 00:00:00 and adding 10 days will take it to 202X-11-10 00:00:00. If now() is after this, we say the event is locked to edit. But this means the event will be locked during the daytime of 10th November while user expectation is to be able to edit it even during the final day (until 23:59:59). To include the final 24 hours, we add one more day to the expiry check logic.
> fix: [DHIS2-15272] Handle final expiring day for expiryPeriodType and expiryDays

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/DateValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/event/DateValidatorTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19297
> fix: [DHIS2-15272] Fix program expiryDays check with periodType for events (2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnitService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/DefaultOrganisationUnitService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/GetObjectListParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/GetObjectParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OpenApiControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserRoleController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/validation/ValidationRuleController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiExtractor.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiObject.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
The CRUD `getObjectList` method has 2 major complications for the OpenAPI analysis
* it uses a type variable as parameter object
* it has a "virtual" response type that gets substituted based in the current value of `@EntityType`
Type variable parameter objects were not supported before so a simple version was added that only supports this particular case.
The response broke due to too many properties escaping the parameter type analysis as it would pick up a property from the annotated field (which was renamed) and another one from the getter (which lacked the renaming annotation and therefore wasn't ignored). Therefore the de-duplication is now based on the Java property name, not the name the property gets after considering potential renames from an annotation.
I also added OpenAPI …
> fix: OpenAPI - object list extraction [DHIS2-17200]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/category_option_combinations_no_names.yaml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityCategoryOptionCombosNoNamesControllerTest.java
This check identifies COCs without names, but in the user interface, we use the name (which is of course blank). This creates issues with seeing anything useful in the UI. 
The SQL has been adjusted so that we use the string array of category options instead. This should hopefully be more reliable, but if the category options also have blank names, then it will still of course be a problem. We may need to consider some fallback in the UI?
> fix:Adjust SQL for data integrity check of COCs without names

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SmsInboundControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SmsOutboundControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsInboundController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsOutboundController.java
In PR #19046 I mistakenly called the method itself instead of `super` causing an endless loop until stack overflow.
I added naive tests that ensure this particular issue is no longer present.
> fix: SMS inbound and outbound lists stack overflow [DHIS2-18542]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/TokenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/TokenOperatorTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CrudControllerIntegrationTest.java
This PR backports commit 14f53952ec5c136e02af63624674757b237bd33d.
> fix: not apply identifiable token filter to uid length < 4[DHIS2-17098-39]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ExpressionMapBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramExpressionItem.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/pom.xml
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/statement/DefaultStatementBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/PostgreSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/SqlBuilder.java
This PR attempts at propagating the `SqlBuilder` into the Antlr parser, so that parser can generate SQL expression compatible with the underlying analytics database.
- ~~Configure the `ExpressionService` Spring Bean into a `ServiceConfig`, so that the `SqlBuilder` can be injected explicitly.~~
- Modified `DefaultProgramIndicatorService` so that the expression map is now built externally (see `ExpressionMapBuilder`). This allow to use the new `withSqlBuilder` method on the expressions in the map and pass the `SqlBuilder` to each expression.
- Add a "fluent" `withSqlBuilder` method to `ProgramExpressionItem`.
- Use a custom builder for `CommonExpressionVisitor` to make possible to initialize the existing `DefaultStatementBuilder` with `SqlBuilder`
- Add a new `cast` function to `SqlBuilder` …
> chore: propagate SqlBuilder to Antlr Expression visitor [DHIS-16705]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SqlExceptionUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsUtilsTest.java
Apache Doris and the MySQL JDBC drivers do not throw the same exceptions when certain error occurs when querying the database.
Doris seems to throw mostly `UncategorizedSQLException` therefore the error handler logic from `AnalyticsUtils.withExceptionHandling` no longer works as expected.
Modify `AnalyticsUtils.withExceptionHandling` to handle `UncategorizedSQLException` and replicate the pre-existing logic.
> feat: handle Doris JDBC exceptions same as Postgres errors

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_updated_datavalues.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/tei_enrollment_with_event_and_no_datavalues.json
This PR fixes an issue where events linked to an enrollment were being merged from both the database and the tracker bundle payload without prioritizing the payload events. This caused outdated or incorrect events from the database to potentially overwrite the more relavant payload events.
- Added logic to prioritize events from the tracker bundle payload over events fetched from the database.
- Combined events efficiently using maps to ensure uniqueness and prioritize payload events when UIDs conflict.
> Fix: Prioritise payload/bundled events over database events for enrolment[DHIS2-17806]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOrgUnitTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEventsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/setting/AnalyticsTableSettings.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerDorisTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEventsAnalyticsTableManagerTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/DhisConfigurationProvider.java
Centralizes the `isGeospatial` logic. Removes the non-final geospatial class-level property which is prone to race conditions and unintended consequences in the case where the property is changed by application code.
> refactor: Centralize isGeoSpatial property logic [DHIS2-16705]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchangelog.hiberante/EventChangeLog.hbm.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventChangeLog.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/HibernateEventChangeLogStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EventPersister.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_33__Rename_event_change_log_property_to_field.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/OrderAndFilterEventChangeLogTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonEventChangeLog.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportChangeLogsControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventChangeLogMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/view/EventChangeLog.java
As agreed on slack, I'm renaming `eventProperty` to `eventField`, to align with our current behavior in the API.
> task: Rename eventProperty to eventField [DHIS2-18549]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
When registering a new TEI, there is no context of a program. But the old Tracker API goes ahead and checks program ownership for “all the programs in the system”. This itself was only part of the problem.
There is a cache used to store programOwnerOu for a TEI-Program combination. For TE creation, when the TE is yet to be created, it will not have an id (the primary key column which is obtained after a TE is persisted). So during the time of TE creation, the entity object will always have an id of 0. This 0 is used as part of the key to cache programOwners. This means any subsequent TEI registration will also have 0 as the id and will pick up the  "wrong owner OU" from the cache(the first one that got into the cache).
So irrelevant access checks + incorrect cache hits was the root cause …
> fix: [DHIS2-18551] (2.39) Fix access check when registering TEI

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
Just switches from sequential to continuous execution. That means the delay between one job done and next job of the same type started is now zero as opposed to up to 30sec in the worst case. This is so multiple small GeoJSON imports do finish quicker. 
* goto import/export app and perform a GeoJSON import
* check the import works as before
The real difference in behaviour can only be observed when issuing multiple imports in quick succession. This maybe can be done using multiple tabs prepared with different imports and then pressing the button to import around the same time. Then one could check that one of them started right when the other one was finished. The job progress API can be used to see the timestamps.
> feat: enable continuous execution for GeoJSON imports [DHIS2-16702]

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
This PR addresses an issue where the deletion functionality for events and enrollments does not remove references from all associated tables
> fix: Complete cleanup of event and enrollment references across all associated tables during deletion

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
In event fetching API ( `api/tracker/event/{uid}` ) , when `includeRelationship` is set to true. The service fetches all relationships without respecting the `deleted` flag. 
This PR corrects this.
In collection event fetching API ( `api/tracker/events=event={uid}` ) this issue does not exist.
> fix: [DHIS2-18527] (2.40) Fix deleted relationship getting returned in event

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/AbstractEventService.java
Forward porting the fix from https://github.com/dhis2/dhis2-core/pull/19397 
But this is Deprecated in v41. Still fixing it anyway.
The Test Classes for this Deprecated area has already been removed in v41. Hence not spending anytime to write new Test Classes for this Deprecated area for v41.
> fix: [DHIS2-18527] (2.41) Fix deleted relationship getting returned in event

- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
System settings use local server zone when formatting the date string so one cannot expect a UTC (neutral) date and time therefore this is compared against a local date time which also uses the system default time zone.
> fix: make system-settings test time-zone independent

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
This reverts commit e8b586f6a96b4934d58c5adb23605cd59cfabd10.
> fix: revert endpoint api/options causes too many DB queries (2.41)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/icon/DefaultIconService.java
If a default icon is missing in the `icon` table there might still be a `fileresource` entry for that icon. In such case that `FileResource` is now reused but the content is restored to make sure the icon exists.
This is a similar but different issue to the "phantom" icons where the `fileresource` did exist but the content is gone whereas here the content might still exist.
> fix: auto-repair default icons when there is a orphan file resource [DHIS2-18606]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
In my previous refactoring in #19046 I missed that `MessageService#getMessageConversations()` did not return all messages but just the current user's conversations. So this list needs to be the stating point.
But there is an exception to that. When `query=` was used the starting point are all conversations matching the query. This can be combined with `filter` but not with `queryString` and `queryOperator` which are a different kind of "fuzzy" search for the user's conversions (which also can be combined with `filter`).
> fix: message conversation list based on user messages [DHIS2-18605]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
Implements a new special linked account logout URL as a system configuration variable.
When all the config is set and logout is called, this user gets forwarded to this URL, but only if the logout is not called with the special 'switch' parameter used for switching users with linked accounts.
1. Enable `'oidc.oauth2.login.enabled'` and `'linked_accounts.enabled'`
2. Set the wanted logout URL as `'linked_accounts.logout_url'` in dhis.conf
3. Start the server
4. Log in
5. Log out
6. Observe you get redirected to the URL set in `'linked_accounts.logout_url'`
> feat: implement special logout url for linked accounts feature

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/note/hibernate/Note.hbm.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/TrackerObjectsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/note/DefaultNoteService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/note/JdbcNoteStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/note/NoteService.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_34__Create_sequence_for_note_table.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/note/NoteServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EventImportValidationTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportNoteControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/NoteMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
Added endpoint to create a `note` for `enrollments` and `events`:
- `POST tracker/enrollments/{uid}/note`
- `POST tracker/events/{uid}/note`
A new service and a new store using JDBC are created.
The validation applied are:
- Verify that event/enrollment exists
- Verify that user has read access to event/enrollment
- Verify that field `value` for the `note` is not empty
- Verify that a `note` with the same `uid` does not already exist
***Inconsistency between the 2 endpoints***
To check that the event/enrollment exists and that the user has all the right permissions we are using services (`EnrollmentService.getEnrollment(uid)` and `EventService.getEvent(uid)`) but they do behave differently when an entity without the right permission is accessed:
- `EnrollmentService` throws a 403
- …
> feat: Create note endpoints in tracker [DHIS2-17579]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/DataElementMergeTest.java
Re-enable a data element merge test for DB constraints.
The test setup was originally explicitly creating category option combos but this is not correct. They should be auto generated.
The test now creates the category metadata & then triggers generating the category option combos through the maintenance API.
> chore: Fix e2e test setup and re-enable test

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/SecurityOwnershipValidator.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/validations/events-scheduled-with-registration.json
Backport of https://github.com/dhis2/dhis2-core/pull/19457
> fix: Validate search scope when scheduled event [DHIS2-17335][2.41]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/importer/shared/postprocess/EventFileResourcePostProcessor.java
https://dhis2.atlassian.net/browse/DHIS2-14139
**Problem:** When trying to delete a file (data element of type `FILE_RESOURCE`) in Tracker Capture, the event PUT request fails with a `NullPointerException`. 
**Solution:** Check if the object is `null` before accessing it.
> fix: [DHIS2-14139] check fileResource null reference (2.41)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/postprocess/EventFileResourcePostProcessor.java
https://dhis2.atlassian.net/browse/DHIS2-14139
**Problem:** When trying to delete a file (data element of type `FILE_RESOURCE`) in Tracker Capture, the event PUT request fails with a `NullPointerException`. 
**Solution:** Check if the object is `null` before accessing it.
> fix: [DHIS2-14139] check fileResource null reference (2.40)

- jenkinsfiles/stable
Tested with this pipeline run - https://ci.dhis2.org/view/dhis2-core/job/dhis2-core-stable/job/DEVOPS-481/5/
> ci: sign commit when updating stable json file [skip ci]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
* feat: implement special logout url for linked accounts feature
(cherry picked from commit 2c6105d01e8a29b0dd419c451b959ecbb8735096)
> feat: implement special logout url for linked accounts feature (#19435)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
This pull request enhances the output of the visualization endpoint for cases where the items are organizational units.
Specifically, it introduces the return of user-friendly names and display names for the following:  
- `USER_ORGUNIT`  
- `USER_ORGUNIT_CHILDREN`  
- `USER_ORGUNIT_GRANDCHILDREN`
> fix: ou item names in visualization [DHIS2-18337]

- jenkinsfiles/stable
Using a type like `boolean` in the variable definition scopes it to a stage, like `def` would, but we need `isHotfix` in multiple stages.
Could not find any documentation confirming this (Jenkins is using a flavoured version of Groovy), but I confirmed it with this [test pipeline job](https://ci.dhis2.org/job/dhis2-core-stable/view/tags/job/test-stable-pipeline). 
[Build #1](https://ci.dhis2.org/job/dhis2-core-stable/view/tags/job/test-stable-pipeline/1) shows the issue with the `boolean` type in the declaration and [build #2](https://ci.dhis2.org/job/dhis2-core-stable/view/tags/job/test-stable-pipeline/2) confirms that removing the type fixes it.
> ci: remove boolean type from var definition [skip ci]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/HibernateEventChangeLogStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/OrderAndFilterEventChangeLogTest.java
When it comes to sorting event change logs, we need to treat data elements and event fields as a single entity, filtering stays the same.
Sort data elements by form name instead of UID, as that's how the UI shows them.
Still need to take care of translations, I'll do that in a separate ticket.
> feat: Sort data elements and event fields as single unit [DHIS2-18012]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DataDimensionItem.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OptionSetItem.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
We need to return a default “optionSetItem” object to keep the new option set item object backward compatible with existing Visualization and allow clients to distinguish between elements that contain an option set from elements that do not.
To achieve it we have to return something like the snippet below:
```
columns: [{
dimension: 'dx',
items: [{
name: "Data element with option set",
optionSetItem: { // Always return below by default, if optionSetItem or aggregation is not set
aggregation: "AGGREGATED",
},
}],
}]
```
> feat: Add defaults to optionSetItem [DHIS2-18643]

- .github/dependabot.yml
- dhis-2/pom.xml
Rule-engine doesn't have circular dependency anymore and it can be managed by dependabot as any other dependency
> chore: Make dependabot upgrade rule-engine library

- .github/workflows/generate-merge-boms.yml
- dhis-2/pom.xml
Integrate Dependency-Track into core
by running analysis as a nightly job
> feat: integrate dependency track

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramNotificationMessageRenderer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramStageNotificationMessageRenderer.java
**Fix for Notification Templates in the Old Tracker API**
**Issue:** 
When OptionSet was used in TrackedEntityAttributes, and these attributes were part of a notification template, the notification template failed to populate the attribute's value correctly during notification delivery. 
**Fix:**
Fixed it by explicitly fetching `option` using `OptionService`
> Fix: (2.40 )Enrollment/Event notification in tracker app[DHIS2-18633]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
Always add default order as a last order parameter to have a consistent order between results.
> fix: Always add default order as last order param in tracker exporters [DHIS2-18659]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/enrollment/query/EnrollmentsQuery5AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/query/EventsQuery4AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/enroll-query.json
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/event-query.json
Add a few new e2e tests using more complex PIs on top of events/enrollments analytics queries.
> test: New ev/en analytics query tests [DHIS2-18695]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramNotificationMessageRenderer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramStageNotificationMessageRenderer.java
Forward Port 
https://dhis2.atlassian.net/browse/DHIS2-18633
> Fix: (2.41) Enrollment/Event notification in tracker app [DHIS2-18633]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
Users could not switch between linked account users.
When the log out handler `(DhisOidcLogoutSuccessHandler)`, was called and tried to set the user we want to switch to with the method `setActiveLinkedAccounts()`, nothing happened because the there was no transaction involved, because it called the UserStore directly, instead of going through the service layer.
So when it tried to persist the updated `lastLogin` field, nothing happened.
Add the `setActiveLinkedAccounts() `method to the UserService and annotate it with @Transactional and make the log out handler call the new method.
Automatic tests not available, because it needs a full setup with an external IDP and tests with E2E.
1. Enable a OIDC provider. (See documentation for setting up with Google for example).
2. Enable linked …
> fix: broken linked account feature

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/Authorities.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
Reverts the original PR, because the new authority was not needed.
> fix: remove F_MAP_EXTERNAL_LAYER_ADD authorities

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityStore.java
Fixing another fix https://github.com/dhis2/dhis2-core/pull/19240 (which does fix the nullPointer issue, but does not consider a small functional gap)
The mentioned PR does not consider if the maxTeLimit is obtained from TrackedEntityType. And proceeds to fetch it from Program again. (Ignores the maxTeLimit could also have been obtained from the TET)
Since the obtained maxTeLimit is injected into the Params, it makes sense to simply re-use that. There already exists a unit test case to check the NPE from the previous PR.
> fix: [DHIS2-18459] Re-use obtained maxTeLimit (2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/LazyAttributeValues.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MandatoryAttributesCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
The main issue was that an empty string value was considered as being present.
Secondary issue was that the attribute value parsing in 2.42 did not accept any other JSON values than a JSON string.
While this is strictly correct the app apparently does use JSON boolean so the parsing was adjusted to handle other JSON types.
For better visibility in case of errors the `JobProgress` tracking for synchronous metadata imports was changed to use `RecordingJobProgress.transitory` which behaves like a persistent tracking except that it discards completed nodes in the progress tree.
See Jira description
2 new test scenarios where added testing that adding a user either with an empty value for the mandatory attribute or entirely without the attribute results in a CONFLICT response.
> fix: mandatory attributes cannot have empty value [DHIS2-18365]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
When using the `query` parameter with `User` this should not run the standard implementation. 
Therefore `query` needs to be considered a "special filter" and excluded for users.
This got overlooked when reworking the special filters in #19046 since the `query` parameter basically has a name clash.
Using it to find `system` user by `username` once with other special filters and once without
* `/api/users?userOrgUnits=true&includeChildren=true&query=system`
* `/api/users?query=system`
* check both URLs result in a list containing the system user (in SL this is the only match)
Added a controller test scenario that searches with `query=system` to match on the `username`.
> fix: user query parameter must include username [DHIS2-18748]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseLinkableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseNameableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Sortable.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/webapi/json/domain/JsonProperty.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SchemaControllerTest.java
Adds a `sortable` property to schema `Property` that indicates if a property can be used in the `order` parameter.
By default only simple non-collections properties are sortable. Exceptions can be made by annotating the property getter with `@Sortable(true)` or `@Sortable(false)`.
As far as I could tell we do not have any actual validation for the `order` parameter apart from simply ignoring collections and non-simple properties should they be present. Therefore that logic was used as the fall-back if no `@Sortable` annotation is present.
IDE supported refactoring to 
* use `@Setter` and some `@Getter` instead of explicitly stating the method
* use `final`
* add nullable annotations to overridden method
Manual changes
* mark some computed properties as `access = READ_ONLY` for jackson …
> feat: adds sortable schema property [DHIS2-18749]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java
The `getPath` method is currently setting the state of the `path` property. Having a get method set state is bad practice. It may also have unintended consequences. Hibernate will manage the state of the `path` property value and there should be no need to additionally set it in the get method. A new method `updatePath` has been added which can be used in tests if necessary.
> fix: Avoid setting path state in get method [DHIS2-18234]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/utils/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
This change is necessary for https://github.com/dhis2/dhis2-core/pull/19377 and should make changes in behavior easier to see/discuss.
We have two methods for getting a single TE. They were implemented independently with convoluted logic. Let one reuse the other. Separate fetching, ACL, mapping to make the flow easier to follow. Move the TETAV logic in one place. This is the only way we can ensure the behavior is the same across different code paths.
Add an `assertContainsOnly` variant that lets us map both collection before making the actual assertion. This makes the assertion error easier to read.
```java
assertContainsOnly(
Set.of(tetavA, tetavB),
trackedEntity.getTrackedEntityAttributeValues(),
TrackedEntityAttributeValue::getValue);
```
gives you
``` …
```
> chore: simplify TrackedEntityService.getTrackedEntity(UID, ...) logic DHIS2-18541

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/HibernateJobConfigurationStore.java
The goal of this PR was to increase the chance of preventing to `revert` a job that is actually running.
After considering all kinds of more sophisticated options we arrived at a very simple solution. 
That solution is to reject the request to revert if the job row has been updated (`lastAlive`) during the last minute. Usually a running and alive job would update that column about every 10sec. While this time is cooperative and can be longer when a single tracked step (like a long running DB query) exceeds 10sec it usually is not and thereby prevents accidental revert is most cases. 
I considered how to test it but I don't think the benefit of having a test justifies the effort that would be needed to test this
as there are hard timings and asynchronous execution involved.
* run analytics …
> fix: prevent accidental job revert of a RUNNING job [DHIS2-18752]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/mapper/NoteRowCallbackHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
Backport of https://github.com/dhis2/dhis2-core/pull/19236
> fix: Map created date of notes as a timestamp [DHIS2-17864](2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/mapper/NoteRowCallbackHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
Backport of https://github.com/dhis2/dhis2-core/pull/19236
> fix: Map created date of notes as a timestamp [DHIS2-17864](2.40)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/trackedentity/store/mapper/NoteRowCallbackHandler.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/mapper/NoteRowCallbackHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Backport of https://github.com/dhis2/dhis2-core/pull/19236
> fix: Map created date of notes as a timestamp [DHIS2-17864](2.41)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
In the `getDataYears` function, the goal is to retrieve all years for all periods built in the `analytics_rs_periodstructure` table. Currently, the year is determined based on the calendar year of the period's start date. However, this approach has limitations, particularly for Weekly periods, where the calendar year of the start date might not match the designated year of the period. This happens because Weekly periods can span across two calendar years (e.g., starting in late December and ending in early January).
This PR updates the behavior to use the `year` column in the `analytics_rs_periodstructure` table instead of deriving the year from the start date. The year column provides a more reliable and accurate representation of the period's year, resolving inconsistencies and …
> fix: uses "year" column in rs_periodstructure instead of extracting the year from "startdate" [DHIS2-18738]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
> fix: uses "year" column in rs_periodstructure instead of extracting the year from "startdate" [DHIS2-18738][2.39]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
> fix: uses "year" column in rs_periodstructure instead of extracting the year from "startdate" [DHIS2-18738][2.40]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
> fix: uses "year" column in rs_periodstructure instead of extracting the year from "startdate" [DHIS2-18738] [2.41]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
continuing https://github.com/dhis2/dhis2-core/pull/19647
Align the `/tracker/relationships?trackedEntity=uid` attributes response
with https://github.com/dhis2/dhis2-core/pull/17572.
> chore: align /tracker/relationships?trackedEntity= attributes DHIS2-18541

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParams.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/utils/Assertions.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityFieldsParamMapperTest.java
- dhis-2/dhis-test-web-api/src/test/resources/tracker/event_and_enrollment.json
* Make controller test a postgres one. The controller test using H2 could only test the `/tracker/trackedEntities/{uid}` and not `/tracker/trackedEntities` (due to JSONB features not present in H2).
* Set the default `orgUnitMode` in `OperationParams` to `ACCESSIBLE` as this is the safest/least surprising/mostly what we want value. `null` is not a valid value and makes the `OperationParams` harder to use.
* improve Assertions
The bug was fixed in PR https://github.com/dhis2/dhis2-core/pull/19647 but is now testable via the changes in this PR. We only test the `/tracker/trackedEntities/{uid}` using controller tests so far. That code path is **extremely** complicated 😢 (aggregate). We'll replace the aggregate code soon enough by using the enrollment/event service.
```http
GET …
```
> test: move TrackedEntitiesExportControllerTest to postgres DHIS2-18541

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapViewStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MappingService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/DefaultMappingService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/MapViewDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/hibernate/HibernateMapViewStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/ProgramServiceTest.java
https://dhis2.atlassian.net/browse/DHIS2-18702
- Database throw FK constraint violation when deleting a Program which is referenced by MapView.
- Remove the program reference from MapView.
- The MapView table also has ProgramStage foreign key, so it also needed to be removed.
- After deleting the Program, user might see an error when viewing the Map. If that happens, user can delete the Map in the Maps app.
- Added unit test.
- Manual test steps are described in [DHIS2-18702](https://dhis2.atlassian.net/browse/DHIS2-18702)
[DHIS2-18702]: https://dhis2.atlassian.net/browse/DHIS2-18702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FK constraint error when delete Program with MapView

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/CategoryOptionComboMergeTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/CategoryOptionMergeTest.java
After the recent category option combo merge addition, there was some test data clashing, only in certain conditions, in Jenkins.
I was able to reproduce this locally by using `@Order` and running both tests together.
Cleaned up test UIDs so they are unique for each test.
Hardcoding UIDs is usually not good in tests but when importing big chunks of related metadata it is hard to avoid.
> chore: Re-enable cat opt merge e2e test

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
The session registry getAllPrincipals() is not compatible with the Redis backed session store, since it does not store session by principal.
Create the principal from the user instead of iterating through the list obtained via the session store.
[DHIS2-18460]: https://dhis2.atlassian.net/browse/DHIS2-18460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: don't use getAllPrincipals

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/indicator/IndicatorStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/category/optioncombo/CategoryOptionComboMergeService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/category/optioncombo/MetadataCategoryOptionComboMergeHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/HibernateExpressionStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/indicator/hibernate/HibernateIndicatorStore.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/CategoryOptionComboMergeTest.java
The requirements for the category option combo merge keep coming in :)
These 2 new scenarios are places in the DB where COC refs can be held within plain string values, which explains why they were originally missed (domain knowledge).
This PR includes handling the refs for these types and their properties:
- `Indicator`
- `numerator` (plain string)
- `denominator` (plain string)
- `Expression`
- `expression` (plain string)
The merge executes an sql update using the postgres function `replace` which replaces all occurrences of a string with another string.
E2E tests added for each scenario.
> feat: Handle Indicators and Expressions [DHIS-18321]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackerOwnershipControllerTest.java
backport of https://github.com/dhis2/dhis2-core/pull/19670
> fix: Grant temp access only if user in search scope [DHIS2-18784] [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/mapping/MapViewDeletionHandler.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramControllerTest.java
- Disable `testDeleteWithMapView` which  only fails on jenkins. Will need to investigate before enabling it again.
```
Referential integrity constraint violation: "fk_mapview_programstageid: public.mapview FOREIGN KEY(programstageid) REFERENCES public.programstage(programstageid) (CAST(38 AS BIGINT))"; SQL statement:
delete from programstage where programstageid=? [23503-232] ==> expected: <OK> but was: <CONFLICT>
```
> fix: disable failing test on jenkins

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
Use `https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java#L242` to get the events from the enrollment instead of getting them through the Hibernate proxy.
Getting the events we can safely catch the `BadRequestException` as we are building `EventOperationParams`.
We can also catch `ForbiddenException`. This is less intuitive but this exception is thrown only in the process of mapping the `EventOperationParams` to `EventQueryParams` and we are not using any of the parameters that could thrown this exception.
**Other changes**
- Assign `ACCESSIBLE` as default value to `orgUnitMode` in `EventOperationParams`.
- Remove `EnrollmentParams` from `getEnrollmentInRelationshipItem` …
> chore: Use EventService in EnrollmentService [DHIS2-18791]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
Backport https://dhis2.atlassian.net/browse/DHIS2-17806
This PR addresses an issue where the `SendMessage` rule action would fail when used in combination with `HideOption`. The failure was caused by the handling of unsupported `ProgramRuleActionType` values.
> fix: (2.39) notification when SendMessage action is used with HideOption [DHIS2-17806]

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
https://dhis2.atlassian.net/browse/DHIS2-17806
This PR addresses an issue where the `SendMessage` rule action would fail when used in combination with `HideOption`. The failure was caused by the handling of unsupported `ProgramRuleActionType` values.
> fix: (2.40) notifications when SendMessage action is used with HideOption [DHIS2-17806]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/HibernateEventChangeLogStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/OrderAndFilterEventChangeLogTest.java
Adding data element name as a fallback in case form name is not set when sorting data elements change logs
> feat: Add data element name as a fallback when sorting [DHIS2-18871]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserAccountControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
Tests that are testing the password length rule fails, because some test change the length.
Tests are modifying the password length rule, and the variable is not reset to the default. Test order is random, and the problem can manifest, when new tests are added.
Reset password length config to the default.
> fix: set maxPasswordLength in password tests

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/InQueryFilterTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProvider.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/event/query/EventQueryTest.java
- dhis-2/pom.xml
This pull request will fix a small bug with IN query operator, making it properly quotes values when needed (it was only quoting `TEXT` value types before).
Moreover, it will properly support Data Elements of type ORG_UNIT, by replacing the filter values with org unit UIDs when needed
> fix: IN filter now works with org units data elements [DHIS2-18845]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2Zpvc.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vValueCount.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vZeroPosValueCount.java
Make sure that when casting to `double` in a Program Indicator function, the correct db-specific syntax is used.
> fix: PI functions and program to handle Doris/CH double type

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/tracker/event_and_enrollment.json
When retrieving an enrollment for a relationship item the events were always excluded.
This PR changes the fields that need to be retrieved for enrollment inside a relationship and ensures that the enrollment and the underneath events are not showing their relationships to avoid any possible cycle.
> fix: Return all requested fields in relationships and prevent cycles [DHIS2-18791]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/TestBase.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/api/TestCategoryMetadata.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datavalue/DataValueStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/merge/category/CategoryOptionMergeServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionComboControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionControllerTest.java
- The base test setup allows creation of a valid `CategoryOptionCombo`s
- `CategoryOptionCombo`s are autogenerated in actual PRD code (never generated in isolation, like other resources)
- In order to create a genuine `CategoryOptionCombo`, it needs the full category model setup (`Category`, `CategoryOption`, `CategoryCombo`)
- A call is then made to auto generate `CategoryOptionCombo`s, mirroring actual PRD code
- This should provide more realistic state in tests, which should help catch relationship issues while developing
- The test setup creates 4 `CategoryOptionCombo`s
- All related category metadata is accessible through the returned record
> chore: Allow custom test category metadata setup

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventQueryParamsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
Requesting events with a filter like `filter={DE_UID}` doesn't work as expected, events are returned regardless of the DEs they contain. This PR aims to fix this issue.
The DEs are stored in a map that uses the UID as the key and a `List<QueryFilter>` as the value. In this case, the value list is always empty. The issue is that this map is also used when sorting. Even though the DEs are present in the order list, we are still using the DE map to add fields to the select clause.
I am changing this in favor of the same approach we use when sorting TEAs, using the order list to add any DE to the select statement.
This fix will allow users to filter for events containing a value in a given DE.
The next PR will enable filtering for events not containing a value in a given DE.
> feat: Filter events by existing data element [DHIS2-15954]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/CteContext.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/EventQueryParamsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/sql/SelectBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/EventQueryParamsUtilsTest.java
This PR addresses an issue with Enrollment Aggregated SQL queries that utilize Common Table Expressions (CTEs) in the context of filtering. The existing query structure was not compatible with Apache Doris  when filters were applied, such as `pTo4uMt3xur.oZg33kd9taw:IN:Female`.
- Refactored the `enrollment_aggr_base` CTE to move the subquery into a separate dedicated CTE, ensuring compatibility with the Doris database.
- Introduced a new CTE, `latest_event`, to handle the subquery logic independently, which is then referenced by `enrollment_aggr_base`.
```sql
WITH latest_event AS (
SELECT 
enrollment,
`oZg33kd9taw`
FROM (
SELECT
enrollment,
`oZg33kd9taw`,
ROW_NUMBER() OVER (
PARTITION BY enrollment 
ORDER BY occurreddate DESC, created DESC
) AS rn
FROM analytics_event_VBqh0ynB2wv
WHERE …
```
> Fix Enrollment aggregate CTE with Query Item filter

- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/AbstractSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
This PR resolves compatibility issues with the `concat` function in Apache Doris, which differs from PostgreSQL in handling `NULL` values. In Doris (and MySQL), if any argument in `CONCAT()` is `NULL`, the entire result is `NULL`. 
To address this, dynamic column expressions are now wrapped with `TRIM(NULLIF(...))`, ensuring identical behavior across both databases.
> Make `concat` function in Doris to work like Postgres

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerCteTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsManagerTest.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/AnalyticsSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/ClickhouseAnalyticsSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/DorisAnalyticsSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/PostgreSqlAnalyticsSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/DorisAnalyticsSqlBuilderTest.java
This PR addresses inconsistencies in datetime rendering between MySql/Apache Doris and Postgres JDBC drivers, ensuring uniform output across analytics databases.
- Standardized the conversion and rendering of `datetime` columns when fetched via the JDBC driver.
- Aligned the format for datetime representation with `2021-11-13 00:00:00.000` across different databases.
> fix: Add format Datetime method for Doris [DHIS2-16705]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/twofa/TwoFactorAuthService.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-test-e2e/config/dhis2_home/dhis.conf
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TwoFactorControllerTest.java
* Move 2FA settings (`email2FAEnabled` & `totp2FAEnabled)` from system settings into system configuration.
* Make it possible to disable the user's 2FA, even if the 2FA type they enrolled in is disabled.
* If the 2FA type the user was enrolled in is disabled in the configuration, the user will not be prompted for 2FA when logging in.
See: TwoFactorControllerTest
1. Edit dhis.conf, add `login.security.totp_2fa.enabled = true` and `login.security.email_2fa.enabled = false`
2. Enroll a user in TOTP 2FA
3. Edit dhis.conf, add `login.security.totp_2fa.enabled = false`
4. Restart the server
5. Observe you are not prompted for 2FA on login
6. Disable the user's 2FA
7. Observe it is disabled
1. Start (in step 1) with: `login.security.totp_2fa.enabled = false` and `login.security.email_2fa.enabled …
> feat: move 2FA settings from system settings to configuration

- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
`getNotificationsByJobType` only contains values for jobs that have data. In this test there was a race condition where the map could be empty when trying to read it. Instead the test now uses `getNotificationsByJobId` which always gives a non-null result.
> fix: NPE in notifier test (race condition)

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/datasets/datasets_same_name.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityDatasetsSameNameControllerTest.java
Adds an integrity check for datasets with the same name or short name. The shortname was made unique and not null [here](https://github.com/dhis2/dhis2-core/commit/ecf7d9990ec39aaeded74cd287633022c7769493) in 2023, but otherwise has been both nullable and non-unique since around 2013. I could not find a corresponding flyway migration script to enforce the uniqueness constraint @jbee , but maybe its there? Anyway, we could have situations where both the name and/or shortname are non-unique. The current thinking is that we should not change the name to being unique for the time being, but at least warn people that this may not be best practice.
> feat: Add integrity check for datasets with same name or shortname

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/DefaultTrackerSideEffectConverterService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleTest.java
https://dhis2.atlassian.net/browse/DHIS2-18517
PR fix scheduling of notifications using capture app when date at which notification needs to be sent is provided through system variable for example `V{current_date}`
> fix: (2.40)Schedule notification in capture app while using system variable

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipOperationParamsMapperTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/tracker/event_and_enrollment.json
Our goal is to have every entity service depending only on its child services and always consider relationships as leaves in the dependency tree.
First step is to remove the dependency on `TrackedEntityService`, `EnrollmentService` and `EventService` that was present in `RelationshipOperationParamsMapper` and create methods in `RelationshipStore` to retrieve a single entity of any type using Hibernate.
***Next steps***
- Migrate and fix commented tests in `RelationshipsExportControllerTest`
- Move relationship handling into `RelationshipService` (Remove all `getRelationshiItems` methods from entity service and centralize them in `RelationshipService`)
- Pass field params to `RelationshipService` in order to only retrieve from the DB what is needed
- Check how we should deal with `deleted` …
> chore: Remove entities service dependency from relationship service [DHIS2-18883]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/LazySettings.java
When validating and parsing setting values for properties that use an `enum` first it tries the exact case input. If that fails it tries the UPPER_CASE of the input. This allow input that is case insensitive as long as it has the right letters. Note that this will not turn _camelCase_ or _snake-case_ into _UPPER_CASE_ with the `_` magically appearing. 
Note that this must be tested manually as part of working full circle is also that the app can handle the value as it is defined in the enum as that will become the new value even if the parsing allows to input the name in a different case.
* login and goto user settings
* change the _Property to display in analysis modules_ between _Name_ and _Short name_
* confirm the change is applied successful
> fix: match setting enum names with UPPER_CASE as fallback [DHIS2-18962]

- dhis-2/dhis-services/dhis-service-tracker/pom.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipItemMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/simple_metadata.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/resources/tracker/event_and_enrollment.json
Move relationship handling into `RelationshipService` (Remove all `getRelationshiItems` methods from entity service and centralize them in `RelationshipService`).
Now, all entity services depend on `RelationshipService` to retrieve relationships, and `RelationshipService` itself does not depend on any other entity service.
***Test***
In `TrackedEntitiesExportControllerTest` we are now using `TrackerObjects` to make assertions instead of Hibernate Objects. This way we do not have any issues with the session and we can never experience `LazyLoadInitialization` issues (and we also removed unnecessary DB calls to retrieve Hibernate Objects).
***Next steps***
- Continue to migrate and fix commented tests in `RelationshipsExportControllerTest`.
- Remove `RelationshipStore` interface.
- Pass …
> chore:Move relationship handling into RelationshipService [DHIS2-18883]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CodeGenerator.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/CodeGeneratorTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/DefaultNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notification.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifierStore.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationTest.java
The UID in a `Notification` has no functional relevance. It cannot be used anywhere in the API to select or filter or do anything with. It simply is a unique string given to each notification but there never was a use case for it as far as I can tell.
However, the UID is shown in the app so removing it entirely seems tricky. Therefore this PR generates the UID on the fly from the timestamp of the notification using an algorithm that results in the same UID for the same timestamp and which generates vastly different UIDs for very similar timestamps.
This means, most messages in Redis will now only consist of a `time` and the `message` itself, for example:
```json
{"time":1738772120198,"message":"Run data set validation"}
```
The same message in the API looks like this (and in old version …
> chore: notifications generate UIDs from timestamps [DHIS2-18885]

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/H2TestConfig.java
found this line in the logs during startup
`WARN  org.hibernate.boot.internal.SessionFactoryOptionsBuilder [main] class org.hibernate.tool.schema.Action cannot be cast to class java.lang.String (org.hibernate.tool.schema.Action is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @73a2e526; java.lang.String is in module java.base of loader 'bootstrap') Ignoring`
Not sure why H2 tests and the validation works in postgres tests when using an enum in https://github.com/dhis2/dhis2-core/pull/19856
I now also tested that DHIS2 fails to start outside of tests as I did during tests in https://github.com/dhis2/dhis2-core/pull/19856
by for example setting the column name in the hibernate mapping for enrollment to a wrong name
```
09:04:43.460 [main] ERROR …
```
> fix: set hibernate.hbm2ddl.auto to string DHIS2-18961

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/TwoFactoryAuthenticationUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/TwoFactorController.java
- dhis-2/pom.xml
Use of non ASCII characters in the TOTP URI fails.
This makes in impossible to use 2FA with instances that has non ASCII characters in the application title. 
The QR code encoder does not support non ASCII characters. 
Remove non ASCII characters from the URI.
> fix: make totp url ascii only

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ConfigurationController.java
Expose the allowed/enabled 2FA methods in the ConfigurationController (api/configuration/twoFactorMethods)
Return a JSON object with two boolean fields:
`email2faEnabled`: Whether email-based 2FA is enabled
`totp2faEnabled`: Whether TOTP-based 2FA is enabled
> feat: expose allowed 2FA types in the configuration endpoint

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationException.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginResponse.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/LoginResponse.java
Implement a way to differentiate between TOTP 2FA and Email 2FA.
Currently, when you are logging in, and you are required to enter 2FA, the server will respond with `INCORRECT_TWO_FACTOR_CODE`. To make it possible for the FE to respond to the user if the user needs to check their email or use an authenticator app, we need to have two different response codes, one for each 2FA type.
The new response codes are:
- `INCORRECT_TWO_FACTOR_CODE_EMAIL`
- `INCORRECT_TWO_FACTOR_CODE_TOTP`
> feat: add 2FA type in authentication error message

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
Both start and end dates of periods in DHIS2 are returned with a time portion of their date as 00:00:00. In order to account for this, we adjust the timely days by one day, so that we effectively start the timeliness calculation at midnight of the day after the period end date. If the period is "Jan 2025", the end date would be reported as "Jan 31 2025 00:00:00". If the timeliness is 0.5, that means that all reports for Jan 31 2025 would be considered timely if they are submitted up until 12:00:00 on Feb 1st.
> Dhis2 9507: Begin timeliness calculation at correct time

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/session/RedisSpringSessionConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
Make the session cookie SameSite attribute configurable, via dhis.conf
Call the variable: `session.cookie.samesite`, possible values are: 'none','strict' and 'lax'
The default value is: 'lax'
> feat: make session cookie SameSite attribute configurable

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/DataElementQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/DataSetQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ExpressionDimensionItemQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/IndicatorQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramAttributeOptionQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramAttributeQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramDataElementOptionQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramStageDataElementQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/QueryableDataItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ResultProcessor.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/FilteringStatement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/NameTranslationStatement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/StatementUtil.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/dataitems/DataItemsAnalyticsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/DataItemServiceFacade.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/DataItemServiceFacadeTest.java
The endpoint needs to support new objects as part of the support for Option in analytics.
New objects introduced:
PROGRAM_DATA_ELEMENT_OPTION (PDEO)
PROGRAM_ATTRIBUTE_OPTION (PAO)
Those objects will only be returned on /dataItems when "dimensionItemType" and "programDataElementId"/"programAttributeId" filters are specified:
`dimensionItemType:in:[PROGRAM_DATA_ELEMENT_OPTION,PROGRAM_ATTRIBUTE_OPTION]`
`programDataElementId:eq:eBAyeGv0exc.fWIAEtYVEGk`
When these filters are not specified, we don't want PDEO and PAO to be returned in a global search, as there could be many of them.
PDEO and PAO objects will have a property that holds the `id` of the associated program data element or program attribute. Example:
```
{
"valueType": "TEXT",
"simplifiedValueType": "TEXT",
"displayName": …
```
> feat: Support for Options in /dataItems API [DHIS2-18956]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/mapgeneration/Legend.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapgeneration/MapUtilsTest.java
- `Legend.draw()` throw NPE when its `MapLayer.name` is null.
- `MapLayer` has  two properties `name` and `layer` which seems to be the same depends on user input.
- Added safety get method to avoid NPE.
- Manual test by sending GET request to `api/maps/zDP78aJU8nX/data.png` and expected to get below map
> fix: NullPointerException in Legend.draw()

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/Page.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/TrackedEntityAggregate.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/TrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
cherry-pick of https://github.com/dhis2/dhis2-core/pull/19918
https://dhis2.atlassian.net/browse/DHIS2-18991 is the same bug as https://dhis2.atlassian.net/browse/DHIS2-17959 except it manifests only in tracker exporter as tracker is not part of metadata sync in 42.
So a user requesting TEs
* with no access to any tracker program
* or on a system without tracker programs
would get a 500 due to invalid SQL.
> fix: cannot get TE if there are no tracker programs DHIS2-18991

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
Propagate `includeDeleted` params from any entity service to `RelationshipService` to include soft-deleted `relationshipItems` when `includeDeleted` is `true`.
***Next steps***
- Fix `isDeleted` check in `OperationsParamsValidator`
- Check if we can remove `isDeleted` check from `RelationshipService`
- Serve multiple and single tracked entities using the same path
- Pass field params to `RelationshipService` in order to only retrieve from the DB what is needed.
- Changing the test input to use the `view` model in relationship tests
> chore: Propagate includeDeleted through relationships [DHIS2-18883]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobSchedulerLoopService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
I noticed that with the changes made to the notifier where all jobs do forward at least the first and the last message (procress start/end) to the notifier jobs that do run frequently (like the housekeeping job) basically spam the log with 1 line per run through the notifier logging.  
To prevent it the notifier log level is set to ERROR if a job should use non-verbose logging. This means for the first and last message where the notification is still always send the message is blanked which also prevents logging.
There is no good way of testing it and I don't think it is worth making a complicated setup to verify.
* start the server
* check the logs for not showing a line from the `DefaultNotifier` once every 30 sec
> fix: use error only notifier logging for frequent jobs [DHIS2-17998]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/groups/group_size_category_option_group_sets.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
It was possible to have two separate integrity checks with the same description. We already checked for duplicate codes and names. This PR fixes a defect and adds a unit test to ensure we do not duplicate the description.
> fix: Prevent duplicate descriptions in data integrity checks

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/OperationsParamsValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/OperationsParamsValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonAssertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/JsonEnrollment.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
Propagate `includeDeleted` from `TrackedEntityService` to `EnrollmentService` and fix `validateTrackedEntity` method: this was a bug only and it was only present in master. Getting `/tracker/trackedEntities?trackedEntity={te_uid}&includeDeleted=true&fields=* when TE is deleted  return a 500 because it was trying to get enrollments filtering by a soft-deleted `trackedEntity` that was throwing the error [here](https://github.com/dhis2/dhis2-core/blob/68ffdfbcb8bc9ac8013c620be76c045c54ae2b64/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/EnrollmentAggregate.java#L77).
Now the behavior of `validateTrackedEntity` changed and a deleted `trackedEntity` is a valid parameter if the `includeDeleted` parameter is `true`.
Additionally, …
> fix: Propagate includeDeleted from TEs to Enrollments services [DHIS2-18883]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultJpaQueryParser.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistAttributeControllerTest.java
A filter like `attributeValues.attribute.id:eq:{uid}` (which no longer works in 2.40) is internally rewritten to the equivalent filter `{uid}:!null` (which works). 
Added an assert to an existing test 
* try `/api/organisationUnits?fields=name,id,attributeValues&filter=attributeValues.attribute.id:eq:ihn1wb9eho8`
* check the filter has results on SL demo and does not end up with an error
> fix: metadata API filter for objects that have a value for a given attribute [DHIS2-18970]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultAnalyticalObjectImportHandler.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/favorites/event_visualizations.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/favorites/metadata_with_legendSet.json
https://dhis2.atlassian.net/browse/DHIS2-17445
- When importing, `EventVisualization.legendDefinitions.legendSet` is not picked up by `AnalyticalObjectImportHandler`. Hence, the  referenced `LegendSet` object is in detached state.
- Update `AnalyticalObjectImportHandler` to handle all objects extend `BaseAnalyticObject`
- Added integration test
> fix: TransientObjectException on LegendSet during import EventVisualization

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/groups/group_size_category_option_group_sets.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
https://github.com/dhis2/dhis2-core/pull/19911
> backport: fix: Prevent duplicate descriptions in data integrity checks

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/utils/CspConstants.java
the old tracker endpoints have been removed https://dhis2.atlassian.net/browse/DHIS2-16564
New tracker endpoints that serve files/images
- `/{event}/dataValues/{dataElement}/file`
- `/{event}/dataValues/{dataElement}/image`
- `/{trackedEntity}/attributes/{attribute}/file`
- `/{trackedEntity}/attributes/{attribute}/image`
get their headers via https://github.com/dhis2/dhis2-core/blob/2097f7e16fd8808f05c80eaa4490d4da00b79feb/dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/FileResourceRequestHandler.java#L67-L75
> chore: remove csp constants for removed tracker endpoints DHIS2-16564

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/mapgeneration/Legend.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapgeneration/MapUtilsTest.java
This PR backports commit 69050430787cce7af18303166239cf67393cd21e.
> fix: NullPointerException in Legend.draw()[DHIS2-12003-40]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/mapgeneration/Legend.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapgeneration/MapUtilsTest.java
This PR backports commit 69050430787cce7af18303166239cf67393cd21e.
> fix: NullPointerException in Legend.draw()[DHIS2-12003-39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/preheat/mappers/RelationshipTypeMapper.java
This PR is fixing some mapping problems in tracker importer that were sometimes causing failures when validating relationships.
Hopefully it will also fix Jenkins e2e tests failures.
> fix: Correctly map RelationshipType to avoid Lazy exception

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/imports/relationships/RelationshipsTests.java
Jenkins tests fail due to a timeout
```
test-1   | [ERROR]   RelationshipsTests.shouldNotImportDuplicateRelationships:517 » ConditionTimeout Condition with Lambda expression in org.hisp.dhis.test.e2e.actions.tracker.TrackerImportExportActions was not fulfilled within 21 seconds.
test-1   | [ERROR]   RelationshipsTests.shouldNotImportDuplicateRelationships:517 » ConditionTimeout Condition with Lambda expression in org.hisp.dhis.test.e2e.actions.tracker.TrackerImportExportActions was not fulfilled within 21 seconds.
```
We don't have visibility into why. We cannot reproduce it locally.
I switched the tracker import for these two tests to sync. I ran these changes on Jenkins and the tests passed.
> test: see if sync gives us an error message

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipController.java
We renamed `ouMode` to `orgUnitMode` and all other organisation unit related parameters in `/tracker` endpoints are either called `orgUnit` if they only accept one like in `/tracker/events` or `orgUnits` if they accept multiple.
* use `UID` type so parameters are validated
> chore: add query parameter orgUnit to /tracker/ownership/transfer in favor of ou DHIS2-19037

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/imports/relationships/RelationshipsTests.java
The failing test was a combination of `IdSchemeTest` not cleaning up data properly and [this PR](https://github.com/dhis2/dhis2-core/pull/19865) that somehow changed the order of the tests and was running `IdSchemeTest` before `RelationshipsTest`.
The solution involves developing more effective filters to obtain the required `RelationshipType` necessary for executing the test.
> fix: Fix Relationship e2e test

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorCodeSentException.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginResponse.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthenticationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/LoginResponse.java
This PR adds a new login response status 'EMAIL_TWO_FACTOR_CODE_SENT' to 
indicate when a user with email 2FA enabled attempts to log in and the 
verification code has been sent to their email. This improves the authentication 
flow by providing clear feedback about the 2FA email verification state.
The new status allows the client to:
- Distinguish between sent 2FA code and incorrect or empty 2FA code provided
- Confirm to users that a verification code has been sent
> feat: Add email 2FA code sent status to login response

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/option_sets/option_sets_wrong_sort_order.yaml
This data integrity check was incorrectly flagging option sets whose index started with 0, but which were otherwise valid. This PR attempts to fix this, by only flagging option sets which have a gap in their sort order.
> fix: Adjust option set sort order check

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/AppOverrideFilter.java
- dhis-2/dhis-web-server/src/main/java/org/hisp/dhis/web/tomcat/Main.java
The `AppOverrideFilter` was incorrectly handling paths containing URL encoded characters (like spaces encoded as %20) by extracting the "raw" encoded URL with the `request.getRequestURI()` method. This caused issues with file paths containing spaces, such as font files (e.g. "Open Sans Regular").
The fix simplifies the path handling by using `request.getPathInfo()` which provides the correct decoded path after the servlet mapping part of the URL. This ensures proper handling of paths containing spaces and other URL encoded characters, while also being more maintainable by using the standard Servlet API as intended.
1. Try to access the URL: `http://localhost:8080/dhis-web-maps/fonts/Open Sans Bold/6144-6399.pbf` (double check on the file system that this path actually exist in the …
> fix: handle URL encoded paths in AppOverrideFilter

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
- dhis-2/pom.xml
The actual fix is incorporated in rule-engine library. But the test is added in dhis2-core to make sure it fixes the problem.
Once [this](https://github.com/dhis2/dhis2-rule-engine/pull/157) is merged then i can bump rule-engine version so this PR points to release version of rule-engine.
> fix: add test in dhis2-core for DHIS2-19001

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventCoordinateService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
Fix a [bug](https://dhis2.atlassian.net/browse/DHIS2-19010) that caused an Analytics Event API request to fail if the selected Data Element for the Program is type `OU`.
When composing the Select statement for the query against `analytics_event_*` table, the wrong column is selected if the Data Element is of type OU.
```
-- Assuming n1rtSHYf6O6 is a OU DE
select .. from ..
ST_AsGeoJSON(coalesce(ax."n1rtSHYf6O6"),6) as geometry,
```
The column `n1rtSHYf6O6` on the `analytics_event_*` table **is not** a geometry column, therefore the SQL statement fails.
When collecting the coordinate fields (`DefaultEventDataQueryService.getCoordinateFields`), append the `_geom` suffix to the column name, so that it can be correctly passed to the `ST_AsGeoJSON` function.
> DHIS-19010 Append geo suffix to OU Data Element fields

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipController.java
* remove deprecated setting with TEI in its name
* fix `since` version which I put the wrong one into. I just deprecated the param in master so v42 not v41 https://github.com/dhis2/dhis2-core/pull/19983
> chore: remove deprecated setting DHIS2-16564

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/CompleteDataSetRegistrationsTest.java
Update the assert string check which might be more reliable than checking with escaped chars
> chore: Update flaky CDSR e2e test

- jenkinsfiles/stable
With this PR the stable pipeline will upload a DB to the IM for the new released version, if one is missing.
The `stable.json` update PR will also be merged directly from the pipeline.
Related to https://github.com/dhis2/jenkins-pipeline-library/pull/24
Tested with the following build - https://ci.dhis2.org/view/dhis2-core/job/dhis2-core-stable/view/tags/job/2.55.5/7/
> ci: upload IM db from stable pipeline if one is missing [skip ci]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/HibernateEventChangeLogStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityChangeLogStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesChangeLogsControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/message/ProgramMessageRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationTemplateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/FieldsRequestParam.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/PotentialDuplicateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/ChangeLogRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParams.java
* implement common tracker paging interface `PageRequestParams` in changeLog parameters
* this ensures they work like other tracker endpoints
* lets us reuse the type
* ignore request parameter `totalPages` in endpoints that do not support it and use `PageRequestParams`. Also exclude it from the OpenAPI spec.
* `/potentialDuplicates`
* `/tracker/trackedEntities/{id}/changeLogs`
* `/tracker/events/{id}/changeLogs`
* ignore request parameter `paging` in changeLog endpoints as they are always paginated
* `throw new UnsupportedOperationException("pageTotal is not supported")` in stores of endpoints that don't support it. This is for the service layer where `PageParams.isPageTotal()` could be true if a dev does not remember its not supported.
* `/potentialDuplicates?fields=` change code to …
> chore: add OpenAPI spec and ignore totalPages DHIS2-19021

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/InMemoryQueryEngine.java
Refactors the matching within the in-memory query engine to run the matching in 2 steps
1. compute a `Predicate` matcher function for each `Filter`
2. test each object candidate using the `Predicate`
This is an important performance improvement because...
1. the 1st step which contains multiple lookups is only done once (as compared to before where is was done for each object candidate).
2. the matching itself does not create temporary collections. The algorithm before the refactoring would matrix multiply nested paths with collections and then test each result. For example, a path like `x.y.z` with `x` and `y` being collections of size `N` and `M` would result in a intermediate collection of size `N * M` if `z` objects. These then each would be tested against the filter. This would …
> perf: query in-memory filtering as predicate [DHIS2-18041]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
Wondering why the query planner would always filter OR root junction entirely via in-memory processing I found that this was a way of masking a bug in the DB query engine which would add the sharing filters directly to the root junction. This is of course wrong. 
For example, when using `?filter=...&filter=...&rootJunction=OR` the DB filter should not be 
```sql
where (<query-filter1> OR <query-filter2> OR <sharing-filter1> OR <sharing-filter2>)
```
but rather
```sql
where (<query-filter1> OR <query-filter2>) AND (<sharing-filter1> AND <sharing-filter2>)
```
With that corrected the odd exception to splitting any query with OR and more than 1 filter to do all filters in memory can be removed. Instead OR can be used if there are only DB filters.
The overall query service would give the …
> perf: use DB query filters for OR root junction when possible [DHIS2-18041]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/HibernateProgramNotificationInstanceStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/Page.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/PageParams.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramNotificationInstanceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationInstanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationInstanceRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationTemplateController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationTemplateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationTemplateRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/PageRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/view/Page.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/view/PageTest.java
* simplify our types so they integrate well
`controller.tracker.PageRequestParams` -> `tracker.PageParams` -> `tracker.Page` -> `controller.tracker.view/Page`
-----^ input to controller ------------------------------^ input to service/store --- ^ output from service/store -- ^ output from controller
Tracker endpoints that got `pager.prev/nextPage` in https://dhis2.atlassian.net/browse/DHIS2-19021. It also shows the feature support.
| endpoint | get counts via `totalPages=true` | turn off pagination via `paging=false` | has `pager.prev/nextPage` |
|----------|----------------------------------|-----------------------------------|--------------------------|
| `/tracker/trackedEntities` | yes | yes | yes |
| `/tracker/trackedEntities/{uid}/changeLogs` | no | no | yes |
| …
> chore: simplify pager types DHIS2-19021

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/audit/AuditRepositoryTest.java
we don't care what id the saved entity gets
> test: fix flaky test

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/HibernateTrackedEntityProgramOwnerStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/ownership/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipController.java
In this PR we are starting to change tracker ownership service and controller to use the new and correct `getNewTrackedEntity` method.
- `getNewTrackedEntity` method is returning a detached entity (that has no `id` set). This is in order to avoid unwanted changes on this object and by consequence unwanted field changes in the DB. Services that expect a managed entity are retrieving one using the `IdentifiableObjectManager` class using `TrackedEntity` uid.
- `TrackedEntityOperationParamsMapper` was throwing a `BadRequestException` when the user had no access to any tracked …
> fix: Use correct get single TE for ownhership feature [DHIS2-18541]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/mapper/TrackedEntityRowCallbackHandler.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/query/TrackedEntityQuery.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityChangeLogServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesChangeLogsControllerTest.java
In this PR we are starting to change tracker ownership service and controller to use the new and correct `getNewTrackedEntity` method.
- Use `getNewTrackedEntity` method in `DefaultTrackedEntityChangeLogService`.
- Map `trackedEntityType` id in order to be used in other services that need managed metadata to work properly. Should we formalize that tracker data are always detached and metadata are always managed, even if they are coming from a tracker service?
`TrackedEntityAggregate` is loading data in new threads so they have their own …
> fix: Use correct get single TE for changelog feature [DHIS2-18541]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityChangeLogService.java
- Remove duplicated validations that are now performed in `getNewTrackedEntity` method.
***Common misconfigurations in tests***
- Create tracked entity and enrollment but do not create an ownership.
- Create a tracker program without a tracked entity type
***Next Steps***
- Move new …
> fix: Remove duplicated validations in changelog service [DHIS2-18541]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackerAccessManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- Use `getNewTrackedEntity` method in `EnrollmentSMSListener`.
- Use `getNewTrackedEntity` method in `TrackerAccessManagerTest` and `MaintenanceServiceTest`.
***Common misconfigurations in tests***
- Create tracked entity and enrollment but do not create an ownership.
- Create a tracker …
> fix: Use correct get single TE for sms feature [DHIS2-18541]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/TestSetup.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/OrderAndFilterEventChangeLogTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/AtomicModeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/EnrollmentImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/EventDataValueTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/EventImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/LastUpdateImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/OwnershipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/RelationshipImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/ReportSummaryIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackedEntityAttributeTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackedEntityProgramAttributeEncryptionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackedEntityProgramAttributeFileResourceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackedEntityProgramAttributeTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerEventBundleServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/programstageworkinglist/ProgramStageWorkingListControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TestSetup.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
following https://github.com/dhis2/dhis2-core/pull/20125
I changed a couple of tests but not all. Some tests are dedicated to testing the import report so they should keep on using the `importService` directly. There are probably other cases where this is true as well. We can transition any other tests we see when we change them.
* reuse assertions
* `base_data` depends on `base_metadata`: so create metadata directly via `setupTrackerData()`?
* can we automatically set the admin user? or should we return a custom record or so with the objectBundle, trackerObjects, admin, ...
* make common assertions reusable we still have some duplicate code here for asserting an import was successful
* reuse `base_data.json` like we did for `base_metadata.json` via the `dhis-support-test` module
* settle …
> test: allow passing tracker ImportParams to TestSetup DHIS2-19095

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/tei_completed_enrollment_event.json
Backport
https://dhis2.atlassian.net/browse/DHIS2-18621
> fix: (2.41) do not use null attributes to rule-engine[DHIS2-18621]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapperTest.java
The last PR, that introduces unary operators for attribute filters in the event endpoint.
As in the tracked entities endpoint, I'm performing a left join to `trackedentityattributevalue`, which is used for both ordering and filtering. The `where` clause is then built using the user provided attribute filters.
Following the approach in `TrackedEntityQueryParams`, I refactored `EventOperationParamsMapper` to expose `filterByDataElement` and `filterByAttribute` in the service API, so users no longer have to deal with a Map structure.
> feat: Filter by unary operators on attributes in events [DHIS2-15954]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/CompleteDataSetRegistrationsTest.java
Remove flaky assert which isn't actually needed as the line before only succeeds if the task is seen as completed. No need to double check the response.
> chore: Remove unnecessary flaky assert in CDSR e2e test

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/EnrollmentSMSListener.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/acl/TrackerAccessManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/ownership/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapperTest.java
- Rename `getNewTrackedEntity` to `getTrackedEntity`.
***Common misconfigurations in tests***
- Create tracked entity and enrollment but do not create an ownership.
- Create a tracker program without a tracked entity type
***Next Steps***
- Add `Optional<T> find(UID)` to our services
- …
> docs: Rename getTrackedEntity methods [DHIS2-18541]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- Create `findTrackedEntity` method and use it when needed.
***Common misconfigurations in tests***
- Create tracked entity and enrollment but do not create an ownership.
- Create a tracker program without a tracked entity type
***Next Steps***
- Add `Optional<T> find(UID)` to our …
> chore: Create findTrackedEntity method [DHIS2-18541]

- dhis-2/dhis-test-web-api/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/test/webapi/Assertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/test/webapi/AssertionsTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/Assertions.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/ExportControllerPaginationTest.java
- dhis-2/pom.xml
An example of how `JsonValue.diff` can be used to write asserts that
* do structural matching
* are more readable
* fail with helpful details
Mainly this allows to ignore details like order of properties or presence of other properties the test does not care about while still allowing comparing the result to a JSON value.
> chore: use JSON diff to assert pager

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/note/DefaultNoteService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- Create `findEnrollment` method and use it when needed.
- Catch `ForbiddenException` in `getEnrollment` as it can only be thrown when mapping `EnrollmentOperationParams` so if falls into the case here 
`throw new IllegalArgumentException(
"this must be a bug in how the EnrollmentOperationParams are built");`
`TrackedEntityAggregate` is loading data in new threads so they have their own transaction and not committed data are not visible in those threads, that is why we cannot use `@Transactional` annotation when we are importing data and reading …
> chore: Create findEnrollment method [DHIS2-18541]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
***Last PR*** 🎉 
- Change back test in `TrackedEntityControllerTest`. The support method `addProgramAttributeValue` was throwing an exception when creating an attribute without a valid file attached. Now we are correctly creating the attribute and after deleting the file.
***Common …
> chore: Fix TrackedEntityControllerTest [DHIS2-18541]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/OrderAndPaginationExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/AclEventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/relationship/RelationshipServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/LastUpdateImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/ownership/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerH2Test.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportController.java
I already did most of the job [here](https://dhis2.atlassian.net/browse/DHIS2-18541).
Now I am just make all the service consistent with each other:
- Rename from `get` to `find` also for the methods in the exporters returning a `Collection` or a `Page`
- Make sure all the `find` and `get` methods are annotated with `Nonnull`
> chore: Tidy up find and get methods in tracker exporters [DHIS2-18145]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiRenderer.java
The initial color scheme and coloring was mostly inspired by the swagger rendering.
But it seemed very overloaded with color. Recently I saw a IDE that gave me an idea of how to keep the color coding but tone it way down to read more like a documentation. 
The result looks like this:
Since the new coloring does not use transparency on large areas I also feel the usability is better when viewing the entire API.
> chore: OpenAPI HTML - more toned colors, higher contrast

- dhis-2/dhis-web-api/src/main/resources/openapi/EventsExportController.md
- dhis-2/dhis-web-api/src/main/resources/openapi/TrackedEntitiesExportController.md
This PR updates `EventExportController.md` and `TrackedEntitiesExportController.md` to align the `dataElement` and `attribute` filters with the expected behavior. It introduces unary operators and fixes some inconsistencies in the existing explanation.
The long-term plan is to move this logic into annotations within the codebase, but for now, this update ensures consistency with the current documentation.
> feat: document filter operators in open api readme [DHIS2-15954]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityChangeLogService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityChangeLogServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/base_data.json
After the recent refactor of the `trackedEntityService`, we were no longer fetching program attributes in the tracked entity change logs, even if a program was specified.
This issue was not detected earlier because the test that validates this behavior used a tracked entity attribute that, although defined as a program attribute, was also defined as a tracked entity type attribute. As a result, it was still present in the output.
I'm also removing `getAllUserReadableTrackedEntityAttributes` because it was not used anywhere.
> fix: Return program attributes in change log [DHIS2-19141]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleServiceTest.java
When calculating program rule effects for events belonging to an Event Program, the code flowed through logics for Tracker Program instead. 
The preProcessing of entities in bundle filled enrollment for single events as well. 
Fixed it by adding an extra check for program of the enrollment obtained.
> fix: [DHIS2-19155] Check if program is without registration for rule engine (2.39.9)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/event_updated_datavalues.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/programrule/tei_enrollment_with_event_and_no_datavalues.json
https://dhis2.atlassian.net/browse/DHIS2-19156
This PR fixes rule engine notifications by prioritizing event data values from the payload over those retrieved from the database.
> fix: (2.39) Prioritise payload event data to trigger rule-engine notifications [DHIS2-19156]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
backport of https://github.com/dhis2/dhis2-core/pull/16965
The backport to the 2.41 branch was forgotten in https://github.com/dhis2/dhis2-core/pull/16965. It was only backported to the 2.41.0 patch branch.
> fix: missing backport of Tracker event query is slow [2.41]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/GlobalShellFilter.java
This updates the redirects sent in the GlobalShellFilter.  In particular:
1. Only redirect from legacy apps to the global shell when receiving a top-level navigation request (header `Sec-Fetch-Mode=navigate`) https://dhis2.atlassian.net/browse/DHIS2-18454
2. Redirect from global app shell paths `/apps/<appName>` back to the original path (i.e. `/dhis-web-<appName>` or `/api/apps/<appName>`), in case someone has started with Global Shell enabled and later disabled it. [DHIS2-19166](https://dhis2.atlassian.net/browse/DHIS2-19166)
Will follow up with integration tests for all global shell cases in separate PR, since that will be quite helpful here but the infrastructure doesn't exist yet
[DHIS2-19166]: https://dhis2.atlassian.net/browse/DHIS2-19166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
> fix: correct redirects for global shell

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/comparator/ValidationResultQuery.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/hibernate/HibernateValidationResultStore.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/validation/ValidationResultController.java
Fixes the paging of validation results.
The main issue was that the `getPager()` on the query was implemented wrongly making the pager based on the `total` before it is computed. The `total` had no reason to exist in the query in the first place.
Bonus fixes for the OpenAPI declarations.
Would require running validation result analysis which in turn requires lots of data and metadata. 
I neither know enough about this nor do I think the effort would be worth the benefit.
On SL demo DB
* data quality app
* run Validation Rule Analysis
* Select Sierra Leone
* Leave the default period
* Check “Persist new results”
* Click on “Validate”
* compare `/api/validationResults.json?pageSize=20&page=1` with `/api/validationResults.json?pageSize=20&page=2` - these should not be the same
> fix: validation results paging [DHIS2-19173]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/http/HttpClientAdapter.java
fix bug in `HttpClientAdapter.ContentType`: wrong [HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) lead to the header not actually being set in https://github.com/dhis2/dhis2-core/blob/5f32ce23c66a2b75018a2cba07529f58e998710e/dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/test/webapi/ControllerIntegrationTestBase.java#L205
> test: fix wrong HTTP header Content-Type

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/TestBase.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/base_metadata.json
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/deduplication/merge/PotentialDuplicatesRelationshipTests.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/imports/relationships/RelationshipsTests.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/LastUpdateImportTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
***How relationships should work***
Relationships are entities that connect 2 tracker objects (tracked entity, enrollment and event) and they can be of 2 types: unidirectional or bidirectional.
A unidirectional relationship from A to C connects A to C, but does not connect C to A.
A bidirectional relationship from A to B connects A to B and connects B to A.
`/tracker/trackedEntities/{TrackedEntityA}?fields=relationships` returns `{relationshipA, relationshipB}`
`/tracker/trackedEntities/{TrackedEntityB}?fields=relationships` returns `{relationshipA}`
`/tracker/trackedEntities/{TrackedEntityC}?fields=relationships` returns `{}`
What does it mean "connects"?
It means that retrieving entity A, we can retrieve the relationships for A (`{relationshipA, relationshipB}`) and retrieve the other …
> fix: Unidirectional relationships only consider from end when exporting [DHIS2-19169]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
Backport
https://dhis2.atlassian.net/browse/DHIS2-17933
> fix: (2.41) fix search scope breaks trackedEntities endpoint[DHIS2-17933]

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/PageTest.java
Added test `commonAndTrackerPagerShouldAlign` with our new `assertNoDiff` to ensure the JSON
produced by `tracker/view/Page` stays consistent with the `common.Pager`. For example if you change
a field name the test will err with something like
```sh
org.opentest4j.AssertionFailedError: JSON has 2 structural differences:
++ $.pageCounts: ? <> 7
-- $.pageCount: 7 <> ?
[-- missing, ++ unexpected, >> out-of-order, != value-not-equal]
==>
```
I had to move the test class from `dhis-web-api` to `dhis-test-webapi` to get access to
`assertNoDiff`.
> test: ensure common and tracker Pager stay aligned DHIS2-19021

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/DefaultTrackerObjectsDeletionService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/LastUpdateImportTest.java
I missed one case from this [PR](https://github.com/dhis2/dhis2-core/pull/20192)
We need to update `updatedAt` field for tracked entity when a relationship originated from such tracked entity is deleted.
I moved the logic to get the tracked entities to be updated inside `Relationship` class in `getTrackedEntityOrigins` method.
> fix: Update updatedAt field for tracked entity when deleting relationship [DHIS2-9767]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/acl/DefaultTrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportChangeLogsControllerTest.java
- As done for [tracked entity attributes](https://github.com/dhis2/dhis2-core/pull/20249), we will log changes in data values only when the `CHANGELOG_TRACKER` config is enabled.
- On the other side, we'll only log that a user breaks the glass if the tracked entity type is configured to allow logs. I've created a unit test to validate such behavior because `programTempOwnershipAuditService` can create new entries but doesn't have a method to fetch them.
> fix: Log event DE changes only when enabled by config [DHIS2-19200]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
When requesting a single tracked entity, we were not validating the user access to the TE/program combination when the program was specified in the request.
This PR fixes the issue.
> fix: Throw 404 when owner outside of capture scope [DHIS2-19210]

- README.md
- docker-compose.yml
- docker/dhis-sync.conf
allowing to test 
https://github.com/dhis2/wow-backend/blob/master/guides/testing/metadata_sync_testing.md
using docker-compose.
We now have a base config for db and web. The base config is then used and adapted for diverging things like ports and volumes.
There is no heredoc syntax we can use to for example inline the `dhis.conf`. There are hacky workarounds. I sticked to creating a separate `dhis-sync.conf` for the `web-sync` container.
> chore: allow testing sync using docker-compose

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerationParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiRenderingParams.java
The HTML rendering options were not considered for the HTML document cache key so the first option combination that ended up in cache was served for all possible option combinations. Note that this only affected the rendering options, not the document scope or analysis options.
* open `/api/openapi.html?scope=controller:ProgramMessageController&source=true`
* open `/api/openapi.html?scope=controller:ProgramMessageController&source=false`
* check that one has sources, the other does not
> fix: OpenAPI - consider rendering choices for HTML cache

- docker-compose.yml
- docker/dhis-sync.conf
the second instance `web-sync` needs to connect to its own DB `db-sync`. The easiest way is to use a separate `dhis.conf`. Other solutions are really hacky like only being able to inline the config into the `docker-compose.yml` if we override the command that starts DHIS2 with a shell script that adds the config as heredoc.
Backport of fix from https://github.com/dhis2/dhis2-core/pull/19931
> chore: allow testing sync using docker-compose DHIS2-18991 [2.41]

- docker-compose.yml
- docker/dhis-sync.conf
the second instance `web-sync` needs to connect to its own DB `db-sync`. The easiest way is to use a separate `dhis.conf`. Other solutions are really hacky like only being able to inline the config into the `docker-compose.yml` if we override the command that starts DHIS2 with a shell script that adds the config as heredoc.
> chore: allow testing sync using docker-compose DHIS2-18991 [2.39]

- docker-compose.yml
- docker/dhis-sync.conf
the second instance `web-sync` needs to connect to its own DB `db-sync`. The easiest way is to use a separate `dhis.conf`. Other solutions are really hacky like only being able to inline the config into the `docker-compose.yml` if we override the command that starts DHIS2 with a shell script that adds the config as heredoc.
Backport of fix from https://github.com/dhis2/dhis2-core/pull/19931
> chore: allow testing sync using docker-compose DHIS2-18991 [2.40]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/acl/DefaultTrackerOwnershipManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/ownership/TrackerOwnershipManagerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/ownership/TrackerOwnershipController.java
When breaking the glass, we can't use the regular flow and call `trackedEntityService.getTrackedEntity()` , because it validates whether the user has access to the owner of the TE/program couple.
That means, if the program is protected, it will check the user has capture scope access to that owner, and it in this case it won't, as that's the whole point of breaking the glass.
For this reason, we will get the TE from the manager and run a separate set of validations just for the case when the user breaks the glass. Some of them were already in place, the ones I added are:
- TE not null
- Data access to program
- Data access to TET
- program TET is equal to TE TET
> fix: Use different TE validation flow when breaking the glass [DHIS2-18877]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
The code is not a change in behaviour. It only prevents accessing `OptionSet options = dataElement.getOptionSet();` if the `options` variable is not needed. This is based on the assumption that this validation is called for each data value and this might be the cause of fetching options every single time.
This is by no means a comprehensive solution. A proper validation would not use the object model but pre-fetch all required options for the entire import in one query. But as so often for that to be possible we do need to know the scope of the import upfront. The current import still allows to put arbitrary data values in the same import and so fetching all required options is difficult and only possible if the input is processed 2 times, once to analyse the data values and a second time …
> perf: avoid accessing DE options if not needed [DHIS2-18135]

- .github/workflows/deploy-instance.yml
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/apps/AppResourceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/GlobalShellFilter.java
Fix an issue when deployed to non-root context paths.
If you have previously experienced an issue with your instance you may need to clear the cache storage in your browser (Dev Tools -> Application tab -> Cache Storage -> "Delete" each one) and unregister all service workers.
For testing incognito mode also works
> fix: correct context path handling for global shell

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/BundledAppStorageService.java
This fixes [an issue](https://dhis2.atlassian.net/browse/DHIS2-19247) where apps discovery fails when running dhis2-core without it being packaged first. 
The problem is that Spring's ResourcePatternResolver is too clever - in a WAR file, it returns a Classpath Resource, which works fine when trying to get the path using ` String path = ((ClassPathResource) resource).getPath();` . But outside of a package, it then returns a FileResource which fails to be cast into a ClassPathResource in that line causing an exception on discovery.
The class path URL works though for loading the apps, in both packaged and non-packaged cases, as we are using ResourceLoader and Resource (rather than FileResource or ClassPathResource)  [here](https://vscode.dev/github/dhis2/dhis2-core/blob/fix/load-apps-outsid …
> fix: make sure apps properly are loaded outside war files [DHIS2-19247]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_1__rename_index_typo_openid_userinfo.sql
Fixes a simple typo on the index name in the userinfo table on the field openid
> fix: userinfo table index on openid typo

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
This solves an issue with caching headers used to determine if a 304 Not Modified response should be returned by the server (or by an intermediate cache)
Prior to this change, only the lastModified header was set.  For bundled apps the lastModified date of the file was indeterminate so this was always set to Jan 1, 1970.  
This was the behavior before 2.42 as well for installed apps.  Bundled apps were served natively by spring and correctly set some of these headers.
Before this change (missing headers - left: 2.41, right: before)
After this change (left: 2.41, right: after)
> fix: correctly set caching etag and lastModified headers when serving app resources [DHIS2-19245]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
Adding missed code during backport.
It was causing the absence of organization units in the `metaData` object.
> fix: Missing OU in metadata items [DHIS2-18884]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/mapper/TrackedEntityRowCallbackHandler.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/aggregates/query/TrackedEntityQuery.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
Get the TE org unit path from the DB, so we can use it when checking the access to a TE/program owner.
Currently we don't set the path value, so access to a TE is always rejected.
Note that this only happens when there's no owner to a TE/program pair and we default to the registering org unit.
> fix: Fetch org unit path when getting TE [DHIS2-19282]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/DefaultOptionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/hibernate/HibernateOptionStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/DefaultPdfDataEntryFormService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/option/OptionServiceTest.java
Looking into option validation I noticed that there are `long` IDs being used in the options SPI so I updated that to use `String`/`UID` instead.
> chore: avoid long ids in option SPI

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OpenApiControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CompleteDataSetRegistrationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationInstanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Api.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiClassifications.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiDescriptions.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiExtractor.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/ApiIntegrator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/DirectType.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/OpenApiGenerator.java
The main change is to use collections that maintain a defined order to avoid having the order of operations vary between runs and between JDKs. This mainly means to use `TreeSet` and `TreeMap` where possible, use `toCollection` instead of `toSet` when collecting streams to a set, and avoid `Set.copyOf`. This is either to eliminate the issue or to make it reproducible.
The second change is how schema usages are tracked before schemas considered unused are removed (see `OpenApiGenerator.addPathSchemaRefs`). I am not sure the old code did miss to follow (expand) a type in some cases but in any case the new code is more clear on that.
Overall I am not sure this really fixed the flakiness. I could reproduce the issue about 1/10 runs locally at the start. After doing the main work I failed to …
> fix: OpenAPI generation flakiness where sometimes a referenced schema is not included 

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/GeoJsonImportTest.java
Remove unnecessary assert check on payload. The previous line already checks if the task is completed or not.
> chore: Improve e2e test, remove redundant assert

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/Stats.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/TypeReport.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/feedback/StatsTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/feedback/TypeReportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/DefaultCollectionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/NotOwnerReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ObjectValidationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationFactory.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/user/UserControllerTest.java
Rename the increment and decrement methods in `Stats` & `TypeReport` for:
- created
- updated
- deleted
- ignored
The increment method by amount _n_ is required for collection sizes, so all have been kept looking consistent.
> refactor: Rename methods for stats and type report

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/PostgreSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/SqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/ClickHouseSqlBuilderTest.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
Make sure that the SQL functions `stddev` and `variance` can run in Clickhouse: add the functions to `SqlBuilder`.
- Set `clickhouse` as analytics db
- Run this query on latest SL db:
- `/api/43/analytics?dimension=dx:BOSZApCrBni;Cm4XUw6VAxv;CxlYcbqio4v;F53rTVTmSuF;FHD3wiSM7Sn;GMd99K8gVut;I5MLuG16arn;Jtf34kNZhzP;LVaUdM3CERi;NJnhOzjaLYk;RF4VFVGdFRO;XTqOHygxDj5;aIJZ2d2QgVV;cYeuwXTCPkU;dGdeotKpRed;eRwOwCpMzyP;fbfJHSPpUQD;hfdmMSPBgLG;iKGjnOOaPlE;kVOiLDV4OC6;oLfWYAJhZb2;rNEpbBxSyu7;wfKKFhBn0Q0;zYkwbCBALhn,pe:LAST_12_MONTHS&filter=ou:USER_ORGUNIT&aggregationType=STDDEV&displayProperty=NAME&includeNumDen=true&skipMeta=true&skipData=false`
> feat: add SQL functions for standard deviation and variance (Clickhouse) [DHIS2-19280]

- dhis-2/dhis-web-server/apps-to-bundle.json
This has been approved by RCB
App management: [DHIS2-19253](https://dhis2.atlassian.net/browse/DHIS2-19253)
Global shell: [DHIS2-19260](https://dhis2.atlassian.net/browse/DHIS2-19260)
[DHIS2-19253]: https://dhis2.atlassian.net/browse/DHIS2-19253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19260]: https://dhis2.atlassian.net/browse/DHIS2-19260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump bundled global shell and app management versions

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramDataElementOptionDimensionItem.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTrackedEntityAttributeOptionDimensionItem.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/aggregated.json
**_Backport from master (2.43)_**
When we set `displayProperty` to **_SHORTNAME_** (in the URL) the API returns `null` when no short name is defined.
We should default to the regular name, instead. ie:
`https://play.im.dhis2.org/dev/api/analytics?dimension=dx:qDkgAbB5Jlk.XCMLePzaZiL.vak9GKjzzAP;qDkgAbB5Jlk.XCMLePzaZiL.zPVS0EAEwia,pe:LAST_12_MONTHS&filter=ou:USER_ORGUNIT&displayProperty=SHORTNAME&includeNumDen=true&skipMeta=false&skipData=true&includeMetadataDetails=true`
This fix forces the use of the overridden version of the `getDisplayProperty` method, which takes care of printing the correct name based on the given `DisplayProperty` object
> fix: null shortname in metadata [DHIS2-19248] (#20326)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
- Try to sort a metadata resource with order=lastUpdated:iasc or order=lastUpdated:idesc and got below exception
```
"httpStatus": "Conflict","httpStatusCode": 409,"status": "ERROR","message": "ERROR: function lower(timestamp without time zone) does not exist\n  Hint: No function matches the given name and argument types. You might need to add explicit type casts.\n  Position: 1100"
```
- Add check for non-text property and return order without `lower()` function
- Added controller test.
> fix: exception when order idesc with non-text property

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/BundledAppStorageService.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/oauth2/OAuth2Test.java
Flaky behavior in OAuth2Test where Selenium driver.getCurrentUrl() occasionally returns an empty string (observed in ~10% of test runs).
Guessing timing and communication issues between DHIS2 Java test code and external Selenium service.
When getCurrentUrl() is called, sometimes it returns an empty string instead of the expected URL.
This causes test assertions to fail unpredictably.
Added retry mechanism when retrieving URLs from Selenium.
The second attempt consistently succeeds when first attempt fails.
Successfully tested with multiple consecutive runs locally.
This should resolve the intermittent failures observed in GitHub CI and Jenkins CI.
> fix: flaky OAuth2 E2E Selenium test

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/EventVisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/VisualizationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/deduplication/DeduplicationControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEnrollmentSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/message/ProgramMessageRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationInstanceRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/notification/ProgramNotificationTemplateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/deduplication/PotentialDuplicateRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/ChangeLogRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/MappingErrors.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/ImportRequestParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/CsvEventServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/CsvTrackedEntityServiceTest.java
- dhis-2/pom.xml
to benefit from improved textblock handling
see
https://github.com/google/google-java-format/releases/tag/v1.26.0
```java
private static final String yes =
"""
hello
""";
```
turns to
```java
private static final String yes =
"""
hello
""";
```
while this is left alone
```java
private static final String no =
"""
hello
""";
```
> chore: update google formatter version

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/QueryOperatorTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/RequestParamsValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/FilterParser.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntityRequestParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/FilterParserTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamsValidatorTest.java
This change is to the parsing of the tracker `filter` request parameter `filter=qrur9Dvnyt5:gt:10:lt:20:!null` used on `/tracker/trackedEntities?filter=` and `/tracker/events?filter=...&filterAttributes=...`.
The previous implementation relied on a mix of string replaces (due to escaped separator characters like `/:`, `/,`), regular expression matching and string splitting into individual filters and segments (uid, operator and value). The previous implementation also used multiple passes over the input string. The addition of unary operators `null`, `!null` made the implementation more complex. I also found a bug in the validation of unary operators having a value. I believe that bug is due to the complexity of the implementation.
This implementation is iterating over the input once*. We …
> fix: validation of filter parser DHIS2-19331

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ResultProcessor.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/dataitems/DataItemsAnalyticsTest.java
**_[Backport from master/2.43]_**
The shortname in `dataItems` API returns the regular `name` in cases where it should return the `shortname`.
This PR fixes this issue and returns the `shortname` as expected.
> fix: Shortname in dataItems API [DHIS2-19323] (#20444)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ResultProcessor.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/dataitems/DataItemsAnalyticsTest.java
The shortname in `dataItems` API returns the regular `name` in cases where it should return the `shortname`.
This can also cause `null` name to be returned, depending on the setting.
This PR fixes this issue and returns the `shortname` as expected.
> fix: Shortname (null) in dataItems API [DHIS2-19248] (#20444)

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerDorisTest.java
- dhis-2/dhis-support/dhis-support-sql/src/main/java/org/hisp/dhis/db/sql/DorisSqlBuilder.java
- dhis-2/dhis-support/dhis-support-sql/src/test/java/org/hisp/dhis/db/sql/DorisSqlBuilderTest.java
This PR updates the Doris SQL dialect to define `DATETIME` columns with a precision of 3 decimal places (i.e., `DATETIME(3)`) instead of the default `DATETIME(0)`.
Doris stores `DATETIME` values with no fractional seconds by default (`DATETIME` is treated as `DATETIME(0)`), causing the loss of millisecond information even when present in the source data.
By explicitly setting the precision to 3:
- Milliseconds are correctly stored and retrieved via JDBC.
- Modified `DorisSqlBuilder.dataTypeTimestamp()` and `dataTypeTimestampTz()` to return `datetime(3)` instead of `datetime`.
- This change ensures that when analytics tables are generated, timestamp columns preserve millisecond precision.
> fix: use DATETIME(3) for Doris analytics table columns to preserve milliseconds [DHIS2-19531]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/configuration/NotifierConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/DefaultNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/FakeRedis.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/InMemoryNotifierTest.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
When using the `notifierMaxMessagesPerJob` setting to limit the number of messages per job the change had no effect.
The cause was that settings were read in a worker thread and so the settings would effectively never expire. The worker itself has to call `clearCurrentSettings()` to invalidate the settings for the thread.
* `POST` to `/api/43/systemSettings/notifierMaxMessagesPerJob?value=6` to limit to 6 messages
* run the resource table generation in the data administration app
* check the message count `/api/system/tasks/RESOURCE_TABLE?gist=false`
* maybe change the setting to another value, like 4 and repeat the other steps and check the 2nd run now has that number of messages (note: a table generation usually has at most 8 messages ATM)
> fix: read most recent settings in notifier queue worker [DHIS2-19317]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerCteTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
See https://dhis2.atlassian.net/browse/DHIS2-19352 for a detailed description of the problem fixed in this PR.
Use `getColumnLabel` instead of `getColumnName` when calculating the row context offset in Enrollment queries.
> fix: invalid offset calculation for rowcontext [DHIS2-19352]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataElementControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
port of #20373 
The specific Dashboard check & tests are not in earlier versions (omitted from this change)
> fix: Correct ignored stats when import validation [DHIS2-15604](2.40)

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AuthoritiesControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthoritiesController.java
* fix: duplicate authorities in the authority endpoint
Backport of: dbd85b6ea75da652adc0b6020531e97af3676977
> fix: duplicate entries in the authorities endpoint (#20324)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventOperationParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/event/EventQueryParamsTest.java
```http
GET {{PROTOCOL}}://{{AUTH}}@{{HOST}}/api/tracker/events?
program=VBqh0ynB2wv&
fields=dataValues[dataElement,value]&
filter=qrur9Dvnyt5:gt:foo
```
lead to `409 Query failed because of a syntax error (SqlState: 07006)` if the data element value type is numeric. We did cast the user provided value for data elements to numeric in the SQL. This lead to
```sh
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [...]
...
Caused by: org.postgresql.util.PSQLException: Cannot convert an instance of java.lang.String to type BigDecimal
at org.postgresql.jdbc.PgPreparedStatement.cannotCastException(PgPreparedStatement.java:980) ~[postgresql-42.7.5.jar:42.7.5]
at org.postgresql.jdbc.PgPreparedStatement.castToBigDecimal(PgPreparedStatement.java:952) …
```
> chore: improve error message for invalid value type on /tracker/events filter DHIS2-19347

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/ehcache.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/hibernate-default.properties
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/PostgresDhisConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/PostgresTestConfig.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/config/PostgresTestConfigOverride.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/junit/MinIOTestExtension.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/postgresTestDhis.conf
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/audit/AuditIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/cache/HibernateQueryCacheTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/RouteControllerTest.java
This PR addresses an issue where the Hibernate L2 cache was not being configured correctly after the upgrade to Ehcache 3. Although the necessary dependencies (`ehcache`, `hibernate-jcache`) were present, the cache was operating with Ehcache's internal default settings instead of the intended project-specific configuration.
**Problem:**
*   The `hibernate-default.properties` file contained outdated settings pointing to the Ehcache 2 region factory (`org.hibernate.cache.ehcache.EhCacheRegionFactory`).
*   The actual Hibernate configuration was being applied programmatically in `HibernateConfig.java`, correctly setting the JSR-107 factory (`org.hibernate.cache.jcache.JCacheRegionFactory`).
*   However, the programmatic configuration was missing the crucial `hibernate.javax.cache.uri` …
> fix: migrate old ehcache 2 config to 3

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/RuleActionEventMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/programrule/executor/event/AssignDataValueExecutor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/executor/event/AssignDataValueExecutorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/programrule/ProgramRuleAssignActionTest.java
This PR is fixing a NPE that was introduced in this PR https://github.com/dhis2/dhis2-core/pull/20396. When trying to assign a `null` value to an option set using a program rule, a 500 is returned by the importer.
While at it, I noticed that we needed to check if the option was valid in the action executor only because `rule-engine` library was not able to assign `null`. 
Last version of `rule-engine` allows to assign `null`, so we do not need any special treatment for option sets, we can assign any value, and if it is invalid it will be caught by the validators.
To resume:
- Fixing NPE when assigning `null` to an option set.
- Do not transform an invalid option to `null` as implemented [here](https://dhis2.atlassian.net/browse/DHIS2-14190)
> fix: Assign null to data element representing option set [DHIS2-19396]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/OutliersCache.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/TableInfoReader.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProvider.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/outlier/data/OutlierQueryParser.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/outlier/data/OutlierRequestValidator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/outlier/service/AnalyticsOutlierService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/outlier/service/AnalyticsZScoreOutlierDetector.java
Adding read-only transactional annotations, so we can avoid the overhead of unnecessary commits, causing slower response times for the outliers API.
> fix: transactional scopes/slower response [DHIS2-19359]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/icon/IconController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
* Metadata icons is not showing, but giving a 404. 
* URLs looking like this: `http://localhost:8080/api/icons/medicines_positive/icon.svg` will be redirected to `http://localhost:8080/icons/medicines_positive/icon.svg`
The `getIconData()` in the `IconController.java` was missing the `api` part in the redirect.
This was a regression from the big refactoring of all endpoints base path. 
Add the `api` part to the URL
* E2E test in LoginTest.testRedirectIcon()
> fix: metadata icons now showing due to broken redirect

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/icon/IconController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
* fix: metadata icons now showing due to broken redirect
Backport of: 429d00e0ecf6f15e28fc67ba6b4cbe75c94e695f
> Backport: fix: metadata icons now showing due to broken redirect (#20515)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitydatavalue/hibernate/HibernateTrackedEntityDataValueChangeLogStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
When an event data value was created in an existing event, we were persisting those values to the database before computing the change logs. 
This was a problem because, at the moment we had to validate whether or not to log changes, the event data value in the payload and the one in the database were the same, so we didn't log anything. 
Now, we will persist the event data values after logging the changes, so we can keep track of them.
However, when it comes to the rule engine, we still need to persist the data values in order to calculate the rule effects correctly. That's why I've created the method `getPayloadDataValues`, which gets all data values from the payload, as it did in the mapper before this fix.
> fix: Save event data value after logging change [DHIS2-19092][2.41]

- dhis-2/dhis-web-server/apps-to-bundle.json
Bumps login app to pick up change in login app whereby app will use standard login page HTML if `loginPageLayout ` is `CUSTOM` but `loginPageTemplate` is an empty string (`""`) (as returned by api/loginConfig).
See ticket: https://dhis2.atlassian.net/browse/DHIS2-19395
> fix: bump login version to handle empty templates [DHIS2-19395]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitydatavalue/hibernate/HibernateTrackedEntityDataValueChangeLogStore.java
Reverting Sonar's suggestion of using try with resources when getting the Session.
It should be Hibernate the one who manages it. Manually closing it could lead to undesired issues.
> fix: Revert try/resources hibernate session [DHIS2-19092][2.41]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
Prior to Struts removal the `getModules.action` endpoint returned apps in the order set in the Menu Management app (see https://github.com/dhis2/dhis2-core/blob/2.41/dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/menu/action/GetModulesAction.java#L61-L74)
This ordering wasn't supported in the `/api/apps/menu` endpoint, which is now serving the `getModules.action` path.
Ordering is preserved in the User object in the database, however if someone tries to re-order their favorite apps without this fix in place, then new order will be preserved (just not shown in the menu until this fix in merged)
Candidate for 2.42.0 but not yet approved by RCB
> fix: correctly return apps in the order set in menu management [DHIS2-19124]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistLogic.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/ProgramControllerIntegrationTest.java
When a collection property is backed by a JSONB column instead of a separate database table the filters need a dedicated implementation to take that into account. 
This PR adds support for 4 filters for JSONB backed collections: `empty` and `!empty`.
Added a new test case for the filter case that spawned the issue
* check `/api/programs/gist?filter=categoryMappings:empty` works
* check `/api/programs/gist?filter=categoryMappings:!empty` works
> feat: Gist API DB filters on JSONB backed collections [DHIS2-19439]

- dhis-2/dhis-web-server/apps-to-bundle.json
This has been approved by RCB
Capture: [DHIS2-19415](https://dhis2.atlassian.net/browse/DHIS2-19415)
[DHIS2-19415]: https://dhis2.atlassian.net/browse/DHIS2-19415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump capture version 101.33.3

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
Backport of #20394 
(cherry picked from commit d14db5e2c6aaa8209136c0cfb6521007bd9af57e)
> fix: correctly fall back to installed app display name if no bundled translation found

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/acl/TrackerProgramServiceTest.java
Fixes the flaky test `shouldReturnAllAccessiblePrograms`.
Now it will check the resulting list contains the expected elements regardless of their order.
> fix: Fix flaky test [DHIS2-19437]

- dhis-2/dhis-web-server/apps-to-bundle.json
bump global shell in RC to include the fixes for: https://dhis2.atlassian.net/browse/DHIS2-19285 and https://dhis2.atlassian.net/browse/DHIS2-19404 (approved by RCB)
> chore: update global-shell in apps-to-bundle.json (DHIS2-19404) (DHIS2-19285)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/BundledAppStorageService.java
this is a backport of https://github.com/dhis2/dhis2-core/pull/20320 to v42 to make sure that the backend runs in development mode (outside of a WAR file)
> fix: make sure apps are loaded outside war files

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistLogic.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistValidator.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/RelativePropertyContext.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
HQL allows to write filters on relations in object notation, e.g. `root.groups.id = id`. However, such filter would result in a `cross join`. Some manual testing has shown that using sub-selects can be beneficial making it 1-10x faster but never worse. 
With that in mind we use sub-selects for filters on relations. In a simple case that would translate to `root.groups.fk = (select fk from Groups g where g.id = id)`. But even better is to also use `exists` making it `exists (select 1 from root.groups g where g.id = id)`. This will result in the equivalent SQL exists query.
I added a query with some basic asserts to make sure that an exists type query is at least triggered. There is a very high chance that lots of other tests indirectly cover similar scenarios but I don't know of any …
> perf: Gist API - use sub-select exists for filter when possible [DHIS2-19410]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/CustomRequestMappingHandlerMapping.java
Revert a condition check in the custom request mapping that was recently changed in #20523.
If a mapping doesn't contain `/api`, it should still get through to have its base mapping added.
Versioned mappings are only added if they contain `/api/`.
This change should be pushed through even while we look at implementing a servlet filter instead of using these custom mappings.
> chore: Revert custom request mapping condition

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardItem.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/schema/SchemaServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
https://dhis2.atlassian.net/browse/DHIS2-12012
This PR makes `text` property in `DashboardItem` class translatable.
> feat: enable translation for DashboardItem.text

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcSubexpressionQueryGenerator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/AbstractOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/DatastoreQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vAnalyticsPeriodEnd.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vAnalyticsPeriodStart.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vCurrentDate.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityChangeLogStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/deprecated/tracker/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SqlUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/SqlUtilsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
This is the simplest way to fix the issues. We are not going to bring in all the improvements 
from https://dhis2.atlassian.net/browse/DHIS2-19347.
```http
GET {{PROTOCOL}}://{{AUTH}}@{{HOST}}/api/tracker/events?
program=uy2gU8kT1jF&
fields=event,enrollment,trackedEntity&
pageSize=15&
filterAttributes=lw1SqmMlnfh:in:167.0;168
{
"httpStatus": "Bad Request",
"httpStatusCode": 400,
"message": "For input string: \"167.7;168\""
}
```
failed for numeric value types as we did not split the input `167.0;168` on `;` (which we do for non-numeric value types).
Like wildcards were not escaped (https://github.com/dhis2/dhis2-core/pull/20586, https://github.com/dhis2/dhis2-core/pull/20705) for `filterAttributes`.
```json
{
"attribute": "w75KJ2mc4zz",
"displayName": "First name", …
```
> fix: /tracker/events?filterAttributes operator in and like based ones [41]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SqlUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/base_data.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/FilterExporterTest.java
We [previously fixed](https://github.com/dhis2/dhis2-core/pull/20586) escaping `like` wildcards `%` and `_` with `\` but did not escape the escape itself 😬
Users could not find TE/EV using attribute/data values with `\` using like based DHIS2 filter operators `like`, `sw` and `ew`.
For example
```json
{
"dataElement": "Da03a96443r",
"value": "Mixed' \\ %Case"
}
```
could be found using `eq`
```http
GET {{PROTOCOL}}://{{AUTH}}@{{HOST}}/api/tracker/events?
program=q04UBOqq3rp&
fields=dataValues[dataElement,value]&
filter=Da03a96443r:eq:miXed' \ %case
```
since `\` has no special meaning outside of `like`.
```http
GET {{PROTOCOL}}://{{AUTH}}@{{HOST}}/api/tracker/events?
program=q04UBOqq3rp&
fields=dataValues[dataElement,value]&
filter=Da03a96443r:ew:' \ %case
```
did not return any result. …
> fix: escape default escape in like based operator input DHIS2-19347

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
The new data entry app no longer supports `multiOrganisationUnitForms` so the setting is obsolete and therefore gets removed.
> chore: remove unused setting multiOrganisationUnitForms [DHIS2-19399]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_4__create_ou_index_for_ou_program_mapping.sql
A query like https://play.im.dhis2.org/dev/api/organisationUnits/gist?filter=programs:gt:5 wants to find programs belonging to an OU. A similar query would happen when selecting OUs and accessing their `Program`s. ATM there is no index on the mapping table causing this having to use the PK/UNIQUE index of the mapping table which is sorted by program first, OU second. Thus to find all programs of an OU it has to look in each of the OU groups within a program to see if the OU is contained. That is far from optimal. To cover both directions another index is needed which is added by this PR.
> perf: adds index used to find programs by OU [DHIS2-11105]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/app/AppManagerMinIOTest.java
Reports of some failing PRs. Disabling these tests seem to help.
No obvious reason visible at all. Passes locally & also on GH, sometimes!! Has just started happening in last day.
There is a DB error which is the last error in the tests before the long timeout:
```text
Exception in thread "C3P0PooledConnectionPoolManager[identityToken->2rxcizbasim1zvxccwmt|40fbb852]-HelperThread-#2" java.lang.AssertionError
2025-04-24T07:59:57.9271762Z 07:59:57.905 [main] ERROR org.hisp.dhis.datasource.DatabasePoolUtils - Connections could not be acquired from the underlying database!
2025-04-24T07:59:57.9273117Z 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1299)
2025-04-24T07:59:57.9274687Z 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPending …
```
> Check minio test

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/junit/MinIOTestExtension.java
Update the docker image for MinIO used in the integration tests.
We don't use the latest tag, to avoid potentially unstable behaviour.
> Update minio image version

- dhis-2/dhis-test-e2e/src/test/resources/junit-platform.properties
- dhis-2/dhis-test-integration/src/test/resources/junit-platform.properties
- dhis-2/dhis-test-web-api/src/test/resources/junit-platform.properties
Adding this into the properties was so we could easily remember how to debug test order issues often causing flaky tests. I did comment the config again in the backports for the test timeout https://github.com/dhis2/dhis2-core/pull/20758 apart from the integration test module. That is blocked by analytics tests see below.
https://junit.org/junit5/docs/current/user-guide/index.html#writing-tests-test-execution-order
@dhis2/analytics-backend please have a look at this test. Also investigate the tests mentioned in the test section of PR description https://github.com/dhis2/dhis2-core/pull/20762.
`EventAnalyticsServiceTest` fails if we comment
`junit.jupiter.testclass.order.default=org.junit.jupiter.api.ClassOrderer$OrderAnnotation` in …
> test: do not promote test order annotations

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/StaticContentControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/StaticContentController.java
When calling the endpoint `GET` `/api/staticContent/logo_banner` with an Accept header of `*/*` or `application/json` it returns the following response:
```json
{
"images": {
"png": "https://play.im.dhis2.org/dev-2-42/api/logo_banner"
}
}
```
The returned URL (`https://play.im.dhis2.org/dev-2-42/api/logo_banner`) is invalid. It should be:
`https://play.im.dhis2.org/dev-2-42/api/staticContent/logo_banner`
[This change](https://github.com/dhis2/dhis2-core/commit/503eaa0e87e65082df97a5bbade5bf64c94d5be8#diff-7b37f48590eee0829b3e859f0af7e133a80eaf4a38005d8d0ce1ea463f986b6e) removed the `staticContent` string value which results in an invalid URL being returned.
Add back in the `/staticContent` path segment so a valid URL is returned.
This assumes that the frontend then calls the endpoint …
> fix: Add path segment back into response URL [DHIS2-19516]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/webmodules/WebModule.java
Reverts the new recently introduced WebModule output format, trying to unify the legacy bundled app format with the normal app format.
> chore: revert new webmodule format

- dhis-2/dhis-test-e2e/src/test/resources/junit-platform.properties
A few e2e Analytics tests need “Order”. So, we need to add the configuration back. See:
NoAnalyticsTablesErrorsScenariosTest
DataItemsAnalyticsTest
This setting has been removed as part of this PR:
https://github.com/dhis2/dhis2-core/pull/20759 
It should be reverted, as it causes our Analytics tests to fail.
> fix: Analytics e2e tests require Order

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
The hasCurrentUser() in CurrentUserUtil should do the same checks as the getCurrentUser() method does, to avoid potential situations where the current user principal is set to a string.
A test for icon lookup/redirection was failing sometimes, since it is not the purpose of the LoginTest to deal with icons, that has its own life cycle, I removed it.
> fix: make the hasCurrentUser more strict

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IndexController.java
This updates the logic for start module redirects to always look up the configured module in the AppManager cache and return the absolute launch URL for that app.  This means that the redirect will never point to a non-existent URL.  It also is backwards-compatible with older versions of the settings app which set `dhis-web-` or `app:` prefixes.  It does NOT support `apps/` prefix, but could be updated to do so if needed.
> fix: support any installed or bundled app as start module

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentFields.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/DefaultEventService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventFields.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipFields.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipItemFields.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipItemMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipOperationParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/relationship/RelationshipService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/DefaultTrackedEntityService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityFields.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityFieldsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/enrollment/EnrollmentsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerUnitTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackedentity/TrackedEntitiesExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerCreateRelationshipSMSTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipRequestParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipRequestParamsMapperTest.java
Add `RelationshipFields` and `RelationshipItemFields` to avoid fetching relationship related data that is not going to be returned to the user as per their `fields` request parameter. This will affect
* `/tracker/trackedEntities`
* `/tracker/enrollments`
* `/tracker/events`
* `/tracker/relationships` - did not have its `fields` request parameter wired through into the service/store
This means that a request like `/trackedEntity?fields=relationships[relationship]` will not need to get the TE relationships `from` and `to` items with its nested entities.
There is one caveat which is the `RelationshipItem.trackedEntity/enrollment/event` which we currently always fetch. The `RelationshipService.findRelationshipItems` returns all items for a given entity. That item then has a relationship with …
> chore: only map/fetch fields the user wanted DHIS2-19137

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerIntegrationTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerTest.java
The revert test needed to be moved to postgres since it otherwise would log an error. This is because the `cancel` column is (intentionally) not mapped in the `JobConfiguration` class and so it is missing in H2's view of the table.
Thanks to J.P. for pointing it out.
> chore: remove error log for job controller tests

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/GistPagerControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
The change to have `/api` be explicit must have broken the URL composition. 
I added the `/api` to the base URL used for `apiEndpoints`.
For prev/next I decided it would be more robust to simply use the current URL and add/change the `page=x` parameter.
The `absoluteUrls` parameter already was documented on just affecting referenced to other objects. I just made that more clear. So the prev/next in the pager are now never relative. This is also more consistent with the normal metadata API pager.
Existing tests got adjusted. Maybe the expectation wasn't correct or outdated with the changes made to /api.
* browse to a gist API list, e.g. `/api/options/gist`
* check that the pager links and `absoluteUrls` links work
* check again for `/api/options/gist?absoluteUrls=true`
* also check that …
> fix: Gist API link URLs [DHIS2-19531]

- dhis-2/dhis-web-server/apps-to-bundle.json
Part of [DHIS2-19527](https://dhis2.atlassian.net/browse/DHIS2-19527) -- see global shell changes here: https://github.com/dhis2/global-shell-app/pull/49
Relates to #20824 
[DHIS2-19527]: https://dhis2.atlassian.net/browse/DHIS2-19527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use global shell v1.7.7 for startModule fix

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityQueryParams.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SqlUtils.java
Use named parameters in `HibernateTrackedEntityStore`. There are more places we should use them though. The `orgUnit` logic is quite complex. I'll try to follow up.
Remember that the JDBC driver will escape single quotes for us. Spring handles collections and different data types for us in its named parameters.
Please use lowercase when writing SQL! No need to scream 🙀 😂 
I suggest we structure our SQL generation into composable functions with signatures like
```java
private void addEventQuery(
StringBuilder sql, MapSqlParameterSource sqlParameters, TrackedEntityQueryParams params) {
```
The convention being to **pass in these parameters in that order** in all our JDBC stores SQL generating functions. Any additionally needed parameters should come after them.
These functions follow the …
> chore: use named parameters in HibernateTrackedEntityStore DHIS2-19474

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/data_elements/aggregate_des_cannot_aggregate_operator_not_none.yaml
Adds "COORDINATE" to the list of invalid aggregate data element value types for metadata integrity checks.
> update: include COORDINATE valuetype in check

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/JdbcPredicate.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/JdbcPredicateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
following up on https://github.com/dhis2/dhis2-core/pull/20849
* fix passing `enrollmentStatus` parameter: we cannot pass an enum to the JDBC parameters but need to pass its `name()` which is a String. Primitives or their boxed types are supported. We are doing this correctly for the event status but did not for the enrollmentStatus
* fix passing `followUp` parameter: I think Spring converts Boolean to some numeric type. The error message is not clear but it looks as if that is what's happening. So instead of `is true` which is valid it would likely ask for something like `is 0`
* lowercase SQL
* spread the pattern of the SQL building functions to use signature `(StringBuilder, MapSqlParameterSource, ...)`
* `getQueryOrderBy` parameter `boolean innerOrder` is not needed as the inner and …
> fix: expand adoption of (StringBuilder, MapSqlParameterSource, ...) pattern in TE store DHIS2-19474

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/DefaultNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notifier.java
The default method for `notifierGistOverview` was not starting with `get` and thus wasn't recognized as setting with meant it was not possible to read or write the setting.
The confusion was likely created because convenience methods that merely call other settings can start with `is` since they are not a setting themselves. Therefore I reorganized the methods again so such methods are listed at the end. I also updated the comments leading the sections to be more clear.
I also checked that no other settings are affected by a similar issue.
Added an assert that checks that `notifierGistOverview` is a recognized setting.
* read ` GET api/systemSettings/notifierGistOverview`
* update `POST api/systemSettings/notifierGistOverview?value=true`
> fix: system settings notifierGistOverview method naming [DHIS2-19128]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/AzureAdProvider.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/oidc/provider/AzureProviderTest.java
Backport: https://github.com/dhis2/dhis2-core/pull/20906
> fix: Set issuer URI for Azure AD provider to resolve login failures

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerDorisTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
**Context**
When DHIS2 is configured to use **Apache Doris** for analytics, the SQL generated to populate the `analytics_event_*` temporary tables attempts to cast date-time values pulled from the `eventdatavalues` JSON blob. The `CASE` expression relies on a regular expression containing the shorthand `\d` (digit). Doris’ regexp engine treats the back-slash differently, so the check always fails and the casted column (e.g. `msodh3rEMJa`) is written as **`NULL`**.
**Fix**
Replaced every `\d` in the date-matching pattern with the explicit character class `[0-9]`. Using a fully expanded class avoids Doris’ escaping quirks while remaining fully compatible with PostgreSQL.
**Result**
* Date attributes matching any of the supported formats (e.g. `1999-12-12`, `2021-12-14T11:45:00.000Z`, etc.) …
> fix: use  explicit character class in Analytics regexp

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
When mapping possible values for `true` or `false` to a boolean value the normalisation did not handle null since the collections used do not allow checking `contains` with a `null` value and would throw a NPE.
> fix: null boolean value normalisation [DHIS2-19597]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/webapi/json/domain/JsonMeDto.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SystemSettingsControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserSettingsControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
When listing settings or user settings it should be possible to limit the response to one or more specific keys using the `key` parameter one or more times. 
In addition, when getting the the `/me` user information the settings can now be filtered using field filtering, for example: `fields=name,settings[keyStyle]`. This is a new feature but was requested and not very hard to do.
New tests where added for all added use cases.
Things I tried...
```bash
curl -u "admin:district" -X GET "http://localhost:8080/api/systemSettings"
curl -u "admin:district" -X GET "http://localhost:8080/api/systemSettings?key=keyInstanceBaseUrl"
curl -u "admin:district" -X GET "http://localhost:8080/api/systemSettings?key=keyInstanceBaseUrl&key=keyRequireAddToView"
curl -u "admin:district" -X GET …
```
> fix: allow filtering settings by key [DHIS2-19606]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/JdbcEventStore.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportFileTest.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/tracker/export/TrackerExportTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/ExportControllerPaginationTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/IdSchemeExportControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerH2Test.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventRequestParamsMapperTest.java
Make `program` field mandatory in `GET /tracker/events` endpoint.
***IMPORTANT NOTE***
This change is required to make it possible to separate the flows for different type of events at the service level.
This change could be overseeded when we manage to have completely separate APIs for the 2 types of events.
I am not documenting it and create release notes for this change right away, I will create a new task to document breaking changes for this whole epic so we can re-evaluate this kind of changes when we have a better understanding of our API and how it should work.
> chore: Make program field mandatory for event exporter [DHIS2-19578]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/GridHeader.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/MathUtils.java
Doris and Postgres are returning different number types from the JDBC result set, depending on the situation.
This PR aims to refactor/clean up and adjust the code so that Doris and Postgres can use the same logic/flow transparently.
> Adjust Number grid values for Doris/PG - [DHIS2-19620]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/login/LoginTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/LoginFallbackServlet.java
Login fallback page/servlet was broken due to: https://github.com/dhis2/dhis2-core/pull/20706
Since after this PR, a session is not always created, but only when needed.
The fallback servlet does not take this into account and will always assume there is a session, hence causing a NP when it's not a session.
When navigating to /login.html, a 500 error was shown.
Check session is not NULL.
An E2E test was added: LoginTest.testLoginFallback()
1. Go to /login.html
2. Make sure you see the login page.
> fix: login fallback page

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/csv/CSV.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/csv/LineBuffer.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ImportSuccessResponse.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxDataElementService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxDataElementStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxValue.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxValueDeleteRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxValueId.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxValueKey.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxValueUpsertRequest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/csv/CSVTest.java
- dhis-2/dhis-services/dhis-service-validation/pom.xml
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/minmax/DefaultMinMaxDataElementService.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/minmax/hibernate/HibernateMinMaxDataElementStore.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.42/V2_42_47__alter_primary_key_min_max_dataelement.sql
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/HibernateNativeStore.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/hibernate-default.properties
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/webapi/json/domain/JsonImportSuccessResponse.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/merge/DataElementMergeTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataanalysis/MinMaxOutlierAnalysisServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/outlierdetection/service/OutlierDetectionServiceMinMaxTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/AbstractDataValueControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MinMaxDataElementControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MinMaxValueControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MinMaxValueImportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MinMaxDataElementController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataentry/MinMaxValueController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/datavalue/DataValueDtoMapper.java
Backport based on the changes made in #20747, #20876 and #21003 for min-max bulk operations.
The modified files were copied entirely from `master` using `git checkout master <file>`. 
The DB script was copied and renamed. I tested that all statements in the script are safe to rerun.
> feat: min-max bulk import and delete [DHIS2-19208]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/acl/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/DefaultEnrollmentService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentQueryParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/HibernateEnrollmentStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/JdbcEnrollmentStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/note/NoteServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportNoteControllerTest.java
This PR adds a new enrollment store, which will be our default, using JDBC instead of Hibernate.
I've tested it on an environment with 73k enrollments, here are the results:
**1. Get enrollment by TE and Program**
This query is frequently triggered in the Capture app. [Query plan](https://explain.dalibo.com/plan/043ef0c88bc7e1c8)
- Uses indexes effectively.
- Returns a single row.
- Exec time: ~0.19 ms.
**2. Get all enrollments for a given TE** [Query plan](https://explain.dalibo.com/plan/63953g4b4a8512ah#raw)
- Similar efficiency as above.
- Uses indexes well.
- Returns a single row.
- Exec time: ~0.23 ms.
**3. Worst case: Get all enrollments and all fields (no filters, no pagination)** [Query plan](https://explain.dalibo.com/plan/2fc7c1dd0d3271h9#raw)
- Joins with notes and …
> task: use jdbc in enrollment store [DHIS2-19543]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/log/TimeExecution.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/minmax/MinMaxValueDeleteRequest.java
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StaticAnnotationPointcut.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/log/TimeExecutionInterceptor.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/minmax/DefaultMinMaxDataElementService.java
- dhis-2/pom.xml
Adds an annotation `@TimeExecution` that can be put on `@Service` implementation class methods to add logging of the method's execution time. 
The logging can be customized using the properties of the annotation:
* override `logger()` to not write to the log of the annotated class but a different `Class`
* override `name()` to change logging the time with the method's name as the "identifier" for the operation
* override `level()` to log on a different level than `DEBUG`
* override `threshold()` with a positive time in millis to only log executions longer than this time
In addition if the annotated method is called with a parameter `record` class (has to be 1st parameter) the components of the class can be annotated with `@TimeExecution.Include` to add the actual value of that parameter …
> feat: annotation based service method time logging

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/singleevent/DefaultSingleEventChangeLogService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/singleevent/JdbcSingleEventStore.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/singleevent/SingleEventsExportControllerH2Test.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/trackerevent/TrackerEventsExportControllerH2Test.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/event/EventsExportController.java
***Big picture***
The final goal of this ticket is to have separate services and stores for single events and tracker events.
To achieve this we will need an intermediate phase where some endpoints will use the correct services and others that will still use the current event service that is serving both types of events.
As a final step, we will remove the generic event service and store and we will only have the ones for single and tracker events separated.
***Implemented in this PR***
- Use the right services in `getEventsAsJsonGzip` in `EventExportController`.  
- Use the right services in `getEventsAsJsonZip` in `EventExportController`.
- Remove from `SingleEventJdbcStore` any reference to `trackedEntity`, `enrollment` and `scheduledDate`.
***Next steps***
- Use the right services in …
> chore: Use event services for get compressed events [DHIS2-19578]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dxf2/metadata/feedback/ImportReport.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dxf2/webmessage/responses/ImportReportWebMessageResponse.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/CsvMetadataImportIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/CsvMetadataImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataImportJob.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/user/UserControllerTest.java
When retrieving a task summary for Metadata Import, the `stats` object is no longer present. `accumulatedStats` is present instead. This causes issues in the UI.
During [this fix](#20373), the `Stats` object was made immutable and had some changes. We have the concept of having multiple nested `stats` objects, an outer `stats` object which shows totals & inner `stats` object per object type.
The method name was renamed to `getAccumulatedStats` (trying to be more meaningful) which is the cause of this issue.
This only occurs on the task summary endpoint it seems. An import report returned synchronously through metadata import returns the expected format (difference in serialization mechanisms between sync/async)
Rename the method in ImportReport to `getStats`.
Existing E2E test updated to …
> fix: Correct Task Summary Import Report stats field name [DHIS2-19660]

- dhis-2/dhis-test-e2e/config/dhis2_home/dhis.conf
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/oauth2/OAuth2Test.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthorizationServerConfig.java
**Problem:**
1. When DHIS2 is deployed behind a reverse proxy that terminates SSL, the OAuth2 authorization server (enabled via `oauth2.server.enabled`) generates JWTs with an `iss` (issuer) claim starting with `http://` instead of `https://`. This is because the issuer URI is inferred from the internal request to Tomcat, which is HTTP.
2. The `AuthorizationServerConfig.java` was not conditionally loaded based on the `OAUTH2_SERVER_ENABLED` setting, meaning its beans might be initialized even if the feature was disabled.
**Impact:**
1. The incorrect issuer URI can cause issues with token validation for clients and resource servers that expect the issuer URI to match the public-facing HTTPS URL.
2. Unnecessary initialization of OAuth2 server components if the feature is disabled. …
> fix: use server.base.url for OAuth2 issuer URI

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-data-exchange/pom.xml
- dhis-2/dhis-services/dhis-service-data-exchange/src/main/java/org/hisp/dhis/dataexchange/aggregate/AggregateDataExchangeJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/SystemActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
- dhis-2/dhis-test-e2e/src/test/resources/metadata/adex-metadata.json
port of #20850 
This port needed extra work due to the very big differences between the job scheduling in older versions.
The issue is having no user associated with an async job (on a new thread). There is no easy way to automatically set the job creator as the user to be used when executing the job (A valid user is required for this job).
This fix uses the `lastUpdatedBy` field to set & retrieve the creator of the job. It's not nice but without making even more larger changes (DB migration for job config table) there is no other way to store and retrieve a user for jobs, without also requiring changes in clients.
> fix: Aggregate Data Exchange job creator as job executor [DHIS2-18324](2.40)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-data-exchange/pom.xml
- dhis-2/dhis-services/dhis-service-data-exchange/src/main/java/org/hisp/dhis/dataexchange/aggregate/AggregateDataExchangeJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
- dhis-2/dhis-test-e2e/src/main/java/org/hisp/dhis/actions/SystemActions.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
- dhis-2/dhis-test-e2e/src/test/resources/metadata/adex-metadata.json
port of https://github.com/dhis2/dhis2-core/pull/20850
This port needed extra work due to the very big differences between the job scheduling in older versions.
The issue is having no user associated with an async job (on a new thread). There is no easy way to automatically set the job creator as the user to be used when executing the job (A valid user is required for this job).
This fix uses the `lastUpdatedBy` field to set & retrieve the creator of the job. It's not nice but without making even more larger changes (DB migration for job config table) there is no other way to store and retrieve a user for jobs, without also requiring changes in clients.
> fix: Aggregate Data Exchange job creator as job executor [DHIS2-18324](2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcUser.java
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserRoleTest.java
Backport: https://github.com/dhis2/dhis2-core/pull/17153
(cherry picked from commit 478f6026dc06b23edb64b9d69bbd5969fd058ebb)
> fix: make oidcuser use parent isAuthorized method (#17153)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/OrgUnitQueryBuilder.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/HibernateTrackedEntityStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackerevent/JdbcTrackerEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/OrgUnitQueryBuilderTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/OrgUnitQueryBuilderTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/ownership/TrackerOwnershipTransferManagerTest.java
After the ACL refactor to fix pagination for `/trackedEntities`, we didn't account for temporary access. As a result, even though the user could still break the glass, they weren't granted access to the tracked entity when requested. This PR addresses that issue by adding an extra clause to the SQL to check whether the user has temporary access.
While at it, I'm also adding the same clause to the tracker event store, as it was missing there too. For events, this is just a temporary fix, since we'll soon be using the `OrgUnitQueryBuilder`. However, because this fix also needs to be applied to version 42, I decided to include it here as well.
> fix: TE, enrollment and event visible after breaking glass [DHIS2-19684]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseDimensionalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObjectUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/PrefixedDimension.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/BaseAnalyticalObjectTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/BaseDimensionalObjectTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/DimensionalObjectTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/DimensionalObjectUtilsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProvider.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcSubexpressionQueryGenerator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/outlier/data/OutlierQueryParser.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/GridAdaptorTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/processing/CommonRequestParamsMapperTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DimensionalObjectProviderTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryPlannerGroupByAggregationTypeTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/outlier/data/OutlierQueryParserTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DefaultDimensionService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dimension/DimensionServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/dimension/mappers/BaseDimensionalObjectMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/AnalyticsControllerTest.java
Uses `DimensionalObject` instead of `BaseDimensionalObject` where possible.
There are plenty of usages of `BaseDimensionalObject` left but most of them are `new BaseDimensionalObject` calls in tests and in places where these are used as transient objects.
> chore: use DimensionalObject interface where possible

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/AzureAdProvider.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/oidc/provider/AzureProviderTest.java
Backport of: https://github.com/dhis2/dhis2-core/pull/20906
* fix: Set issuer URI for Azure AD provider to resolve login failures (#20906)
> fix: Set issuer URI for Azure AD provider

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/ParamsConverter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/domain/SingleEvent.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerBundleTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackerImporterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preprocess/AssignedUserPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preprocess/EventStatusPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preprocess/EventWithoutRegistrationPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/preprocess/StrategyPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/programrule/RuleEngineMapperTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/base_data.json
- dhis-2/dhis-support/dhis-support-test/src/main/resources/tracker/base_metadata.json
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/EventChangeLogServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/event/OrderAndFilterEventChangeLogTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/preheat/TrackerPreheatServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/relationship/RelationshipsExportControllerTest.java
***Big picture***
The goal of this ticket is to have separate domain objects for single events and tracker events that will be generated in the preprocess phase.
This will allow us to have separate flows for validation, rule-engine and persistence (even though for now we will use the same DB table).
***Implemented in this PR***
- Remove `events` field from `TrackerBundle` and add `trackerEvents` and `singleEvents` fields.
- `trackerEvents` and `singleEvents` fields are created after preheat phase and any ambiguous event (without valid program and programStage) is mapped to a tracker event.
- We are maintaining (maybe only temporary) getter and setter for events.
- For now, `Event` interface contains fields that only belong to tracker events and `SingleEvent` class is implementing them. …
> chore: Separate event types in TrackerBundle [DHIS2-19701]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/app/AppManagerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
https://dhis2.atlassian.net/browse/DHIS2-19708
- The check condition for `manifest.webapp` return false because the input argument was `/manifest.webapp`. 
* Changed the condition so it will return true even if the input contains `/` in the beginning.
* Move the related code to service layer so I can add test for it.
* Refactored the `AppController` to delegate the handling of `manifest.webapp` to the `AppManager`'s `handlingManifest` method, removing duplicate logic from the controller.
* Added a new unit test, `handlingManifestTest`, to verify the behavior of the `handlingManifest` method, ensuring that the `href` is correctly updated when it is set to `*`.
> fix: wrong manifest returned by app controller

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/SqlQueryExecutor.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTrackedEntityEventsAnalyticsTableManager.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/AnalyticsDataSourceConfig.java
This PR updates the Tracked Entity Analytics (TEA) logic to always use the PostgreSQL datasource for both table population and query execution, regardless of whether Doris or ClickHouse is selected as the analytics engine.
As discussed in the analysis document
[analysis document](https://github.com/user-attachments/files/20709157/Analytics.TEA.Queries.with.Doris.pdf), the effort required to adapt TEA query generation to Doris is currently too high. Additionally, TEA query performance on PostgreSQL is already sufficient.
To avoid unnecessary complexity and risk of regression, TEA queries are now explicitly routed through a dedicated PostgreSQL datasource.
- initialize a `postgresSqlBuilder` Bean
- initialze an `analyticsPostgresJdbcTemplate` used by the TEA table managers
- initialize an …
> DHIS2-19753 Route all TEA Analytics query to Postgres

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/program_rules/program_rules_inconsistent_program_program_stage.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegrityProgramRulesInconsistentlyLinkedControllerTest.java
- Program rules can be optionally linked to a program as well as a program stage. The model theoretically allows program rules to be linked to a program stage which does not exist in the associated program. 
- This check identifies program rules which are linked to both a program as well as a program stage, but the program stage is not part of the linked program.
> feat: Program rules linked to an inconsistent program stage

- dhis-2/pom.xml
This PR updates the snapshots url. The migration from the deprecated OSSRH service to the new Central Portal has made that the snapshots are available in a different repository.
> chore: Update Maven snapshots url

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/ArtemisManager.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/config/ArtemisConfig.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/config/ArtemisConfigData.java
For a long time (over 1 year at least), the integration tests (postgres & h2) have thrown the following exception:
```text
ERROR org.apache.activemq.artemis.core.server - AMQ224104: Error starting the Acceptor in-vm {serverId=0}
ERROR org.apache.activemq.artemis.core.server - AMQ224000: Failure in initialisation
java.lang.IllegalArgumentException: AMQ229062: Acceptor with id 0 already registered
```
Currently, it occurs 14 times, which:
- pollutes the test logs
- makes it harder to see genuine issues
- potentially slows the impacted tests
This seems to happen when a test uses a custom context config. The `embeddedActiveMQ` instance tries to be started again with the same acceptor ID (this has always been hardcoded as `0`, which seems fine for the embedded broker as it should only ever …
> chore: Clean up Integration test exceptions - Artemis startup exceptions

- dhis-2/pom.xml
This PR updates the snapshots url. The migration from the deprecated OSSRH service to the new Central Portal has made that the snapshots are available in a different repository.
> chore: Update Maven snapshots url (2.40)

- dhis-2/pom.xml
This PR updates the snapshots url. The migration from the deprecated OSSRH service to the new Central Portal has made that the snapshots are available in a different repository.
> chore: Update Maven snapshots url (2.41)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/metadata/export/MetadataExportWithDependenciesTest.java
https://dhis2.atlassian.net/browse/DHIS2-19762
- This issue is about the backend and the metadata dependency export feature. This feature is accessible from Apps > Import-export > Metadata dependency export.
When exporting metadata for a program with dependencies, then:
- ProgramTrackedEntityAttributes are nested with Program.
- ProgramStageDataElements are nested within ProgramStages.
- Now the export also include the arrays of ProgramTrackedEntityAttributes and ProgramStageDataElements again at the JSON root level. These appear to be redundant, have no effect on the import and should be removed from the overall JSON export file.
* [`MetadataExportWithDependenciesTest.java`](diffhunk://#diff-f44c09e7747291807f4ccf90452b4d5ff219c2e5a594c25b1d3e1b2c2721a53dR74-R123): Added a new test, …
> fix: remove programTEA and programStageDE from root level in metadata export

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/category/CategoryServiceTest.java
The test setup <42 is more fragile and needs a little nudge in some cases.
> chore: Update integration test

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
Fixes [DHIS2-19708](https://dhis2.atlassian.net/browse/DHIS2-19708)
The check for `handlingManifest` worked only the first time, when the `App` instance passed to it has the `href` value set to `*` - when that's the case, the condition here is `true` which means the `App` is updated (which in turn updates the cache since it's the same reference) - and  when the check is `true`, the `AppController` [writes](https://github.com/dhis2/dhis2-core/blob/2.41/dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java#L247) the value of the `App` instance (containing the correct `href`) directly to the response stream.
The next time  a request comes, the check is false because the `App` returned from the Cache already has the `href` value set to something else other than …
> fix(DHIS-19708): ensure manifest activities field is always populated

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
Remove the expected response code from the API call. The call alone will suffice.
The line in question tries to manually trigger a job, but the job may already have been started (which returns a 409) when it was created earlier.
> chore: Update flaky e2e test

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
Remove the expected response code from the API call. The call alone will suffice.
The line in question tries to manually trigger a job, but the job may already have been started (which returns a 409) when it was created earlier.
> chore: Update flaky e2e test 2.41

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
https://dhis2.atlassian.net/browse/DHIS2-19607
**Problem**: The dataentry app attemps to preload all available `optionSets` at startup. It first retrieves the complete list  via a `getMetadata.action` call, and then fetches each individually.
However, for some users, it is trying to get unrelated optionSets (from other datasets) for which they lack permissions. This results in unhandled 404 errors, preventing all optionSets in the form from rendering properly.
**Solution**: Catch and handle these 404 errors. Instead of letting them propagate and break the rendering of valid optionSets, log a warning to the console.
This is a workaround to ensure the form remains usable even when certain optionSets are inaccessible.
> fix: [DHIS2-19607] Handle optionSets error responses in dataentry app (2.41)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/app/AppManagerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
[DHIS2-19708](https://dhis2.atlassian.net/browse/DHIS2-19708)
[DHIS2-19708]: https://dhis2.atlassian.net/browse/DHIS2-19708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  fix(DHIS-19708): ensure manifest activities field is always populated [v41]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
Disable failing test in GH - passing locally when run locally (alone & whole suite)
Most likely a test order issue.
> chore: Disable e2e test 2.39

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
backport of (#21388)
fixes https://dhis2.atlassian.net/browse/DHIS2-19708
> fix(DHIS-19708): ensure manifest activities field is always populated [v39]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityAttribute.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/TrackedEntityAttributeObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityOperationParamsMapperTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_11__add_tea_preferred_operator.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/imports/bundle/TrackedEntityAttributeTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/te_with_tea_metadata.json
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/TrackedEntityAttributeControllerTest.java
This PR introduces the preferred search operator field on a TEA.
It's an optional field that's added to the TEA to define the recommended operator for search or comparison. 
This is merely a suggestion for the end user and will not be enforced.
Ticket: https://dhis2.atlassian.net/browse/DHIS2-12183
> feat: Introduce preferred search operators on TEA [DHIS2-12183]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiKeyTokenGenerator.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiToken.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/apikey/ApiTokenServiceImplTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/security/ApiTokenAuthenticationTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ApiTokenController.java
backport of https://github.com/dhis2/dhis2-core/pull/21435
`code` field works  pre-41 (pre refactoring to to use the builder pattern) so just backporting to 42 and 41.
> fix(DHIS2-19863): expose code field in ApiToken

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/SystemControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java
The flag of Denmark was listed twice in the SystemController, causing UI issues.
A test was added to check for duplicates.
[DHIS2-19878]: https://dhis2.atlassian.net/browse/DHIS2-19878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove duplicate flag of denmark

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/EventChangeLogDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchangelog.hiberante/SingleEventChangeLog.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchangelog.hiberante/TrackerEventChangeLog.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_18__separate_eventchangelog_table.sql
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Split `eventchangelog` table into `trackereventchangelog` and `singleeventchangelog`
***In this PR***
- Update `SingleEventChangeLog` hibernate mapping: point to the correct table and update foreign key constraint name.
- Update `TrackerEventChangeLog` hibernate object: point to the correct table and update foreign key constraint name.
- Update deletion handler and maintenance store.
***Migration plan***
In order to make the transition reviewable and understand what is happening, we are separating column in tables with foreign keys one by one. With this approach we are going to have a lot of different migration scripts and we leave the DB in an intermediate state that should be avoided.
The solution that we thought of is to create one complete migration at the end of development that will …
> chore: Split eventchangelog table [DHIS2-19913]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataExportServiceTest.java
Fixes an issue with metadata export no longer exporting the Visualization's relative periods. The relative periods are now exported as `rawPeriods`.
```json
"visualizations":[
{
"name":"ANC: ANC 1 coverage year over year",
"created":"2018-12-03T12:47:50.052",
"lastUpdated":"2025-07-28T14:15:29.048",
...
"rawPeriods":[
"MONTHS_THIS_YEAR"
],
...
},
```
> fix: metadata export of visualization relative periods

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
Adds a new settings key for Azure maps API keys. Bing maps API keys are being deprecated, but needs to be kept during the transition phase.
> feat: add new settings for Azure maps API key

- dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
Number of settings needs to be incremented because two commits with new settings were merged at the same time, because the total was the same in both commits.
> chore: increment settings in testKeysWithDefaults

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserRoleDeletionHandler.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
* fix: bypass acl for user role deletion handler
Backport of: d28da8c4667e599ef6a5b1d1d62e08b243e1edf2
> fix: bypass acl for user role deletion handler

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/CategoryComboObjectBundleHook.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/test/webapi/json/domain/JsonImportSummary.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/postgresTestDhis.conf
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerIntegrationTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryComboController.java
We currently prevent updating an existing `CategoryCombo`s categories if there is any existing data associated with its `CategoryOptionCombo`s. This is only implemented on the endpoint `PUT /api/categoryCombo` though.
This change adds the same validation on the `POST /api/metadata` endpoint to bring the same behaviour for this use case.
- new validation check added to `CategoryComboObjectBundleHook`
3 Integration tests added:
- allow updating `CategoryCombo` categories when it has no associated data
- allow updating `CategoryCombo` with its original categories when it has associated data
- prevent updating `CategoryCombo` categories when it has associated data
Moved the existing validation check out of the `CategoryComboController` to the `DataValueService` so it can be reused.
Originally …
> feat: Prevent updating a CategoryCombo's categories when it has associated data [DHIS2-19942]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/EnrollmentQueryHelper.java
Small fix to avoid returning `filter` as columns, in the query/response.
> fix: Skip filters as columns

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_23__set_default_value_for_dashboarditem_translations.sql
- Execute Metadata sync on SL database got below error
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.hisp.dhis.common.TranslationProperty.getTranslations()" because "this.translations" is null
at org.hisp.dhis.dashboard.DashboardItem.getTranslations(DashboardItem.java:534)
```
- Root cause is there are old records in database with `translations` value is `null`. This happens back when we first introduced the `translations` jsonb column and the migration script didn't set default value for existing records. 
- The newly saved translations have empty array as default value because in Java model object we always init an empty set.
`private Set<Translation> translations = new HashSet<>();`
- Add migration script to set correct default value in database.
- Manual test by …
> fix: set default translations value for dashboarditem

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/security/ApiTokenControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ApiTokenController.java
* feat: add HEAD method to allowed PAT http methods
Backport of: 3bfbb06cc2cc3643449199fe8dea28f8233b3706
> Backport: feat: add HEAD method to allowed PAT http methods (#21575)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerIntegrationTest.java
> fix: Use job creator to execute Metadata Sync jobs (2.42)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserRole.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
Prevents the UserRole's members to be serialized into full User obejcts, and instead serializes them in to the UserDtos, similar to UserGroup's members?
> fix: don't serialize to full user objects from UserRole's members

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/OrganisationUnitControllerTest.java
* fix: hide full user object on orgunit users
Backport of: f9d62caed698317ec03da2813668f08d16b3df59
> fix: don't serialize full user objects from OrgUnit's users (#21602)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/twofa/TwoFactorAuthUtils.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java
Fixes incompatibility with deprecated TOTP secrets, introduced after upgrade to 20 bytes secrets.
This fix allows pre 2.42.0 TOTP secrets to still be validated.
> fix: allow deprecated TOTP secrets to be verified

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataset/notifications/DataSetNotificationServiceTest.java
Fixes issue when the program notification recipients orgunit check fails due to recent change in PR #21122 
When the registration's source orgunit has multiple levels, the check fails, because it's using the wrong input for the method. The check should have used the orgunit's path and not the UID.
Use the orgunit's path as input to the `UserDetails.isInUserHierarchy()` method instead.
Updates the `DataSetNotificationServiceTest#testSendCompleteDataSetNotifications_shouldNotSendToDisabledUsers()` test to use a new registration that has an orgunit source with a parent that's in the user's orgunit list.
[DHIS2-19622]: https://dhis2.atlassian.net/browse/DHIS2-19622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: program notification recipients orgunit check

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/job/TrackerRuleEngineThread.java
As suggested by @jason-p-pickering I am moving rule engine notification logs to debug level to reduce the noise in INFO logs.
> chore: Move rule engine notification logs to debug level

- dhis-2/dhis-test-e2e/config/dhis2_home/dhis.conf
- dhis-2/pom.xml
Reverts a Prometheus library upgrade, that breaks the JVM metrics feature.
Also adds `monitoring.jvm.enabled = on`, to dhis.conf for the E2E server config, this will effectively catch this potential upgrade issue in the future by failing to start. Having it default on in the E2E server, should not affect the other tests.
> fix: revert prometheus upgrade breaking jvm metrics

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataValueMultiTextControllerTest.java
These integration tests started failing on GitHub only (which usually suggests it's a test order/data issue)
- `DataIntegrityPeriodsDistantPastControllerTest`
- `DataIntegrityPeriodsThreeYearFutureControllerTest`
It seems that this test `DataValueMultiTextControllerTest#testPostJsonDataValueSet_MultiText_NoSuchOption` leaves a `Period` in the DB after it completes.
It looks like this results in unexpected results for the Data Integrity tests (if they run after `testPostJsonDataValueSet_MultiText_NoSuchOption`).
This test (`testPostJsonDataValueSet_MultiText_NoSuchOption`) ends up calling `HibernatePeriodStore#insertIsoPeriodInStatelessSession` which inserts a `Period` in a different session to that of the Spring test. This means that Spring isn't aware of this insert and doesn't roll it …
> chore: Clean up data value import of period in test

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_26__add_default_value_for_translations.sql
- In the process of migrating Hibernate mapping from xml to annotation, I have introduced `@Embedded TranslationProperty translationProperty` to map `translations` jsonb column. It will throw a `NullPointerException` if the `translations` value in database is `null`.
- The issue only affect legacy objects which already migrated to annotation mapping, because newly created object will always have default value as in Java model with empty Set.
- Instead of adding null check in Java, i added migration script to set default translations value in database.
- In Java model we always initialize an empty Set when creating new object.
- All existing tests related to translations column should pass.
> fix: add default values for translations column

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/deduplication/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/enrollment/HibernateEnrollmentStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicateRemoveTrackedEntityTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/export/enrollment/EnrollmentServiceTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramNotificationInstanceControllerTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerEventSMSTest.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportNoteControllerTest.java
When we fetched enrollments, we were checking user access against the enrollment’s org unit. That was a mistake, since that field just shows where the enrollment came from and isn’t meant for ACL checks.
I’ve fixed it so we now use the org unit owner to validate access instead.
>  fix: Use program owner instead of enrollment org unit [DHIS2-18338][2.42]

- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/programs/single_events_null_occurred_date.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/tracker/single_events_null_occurred_date.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/DataIntegritySingleEventNullOccurredDateTest.java
Migration script in master is setting `occurreddate` in `singleevent` table as `not null`. In tracker importer there is already a validation to check that `occurredAt` for a single event (event from a program `WITHOUT_REGISTRATION`) is present but at the DB level the constraint is not there because `event` table contains both types of event and a tracker event (event from a program `WITH_REGISTRATION`) can be scheduled and can have a `null` `occurredAt`.
So, to make sure that the migration will succeed, we are creating an integrity check to make sure every single event has a value in the `occurreddate` column.
**This integrity check only makes sense in versions previous to v43 because there `event` table is present**
> chore: Add integrity check for null occurred date for single events [DHIS2-19614](2.42)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
I'm adding the ACL validation when updating events, as it was missing.
We already have it in place when creating and deleting events.
> fix: Validate ACL on event update [DHIS2-10900][2.40]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/deprecated/tracker/EventImportTest.java
I'm adding the ACL validation when updating events, as it was missing.
We already have it in place when creating and deleting events.
> fix: Validate ACL on event update [DHIS2-10900][2.41]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.43/V2_43_27__add_default_value_for_translations_cont.sql
- There are `null` value in `section` table causing NPE in Data Entry App
- In [this PR](https://github.com/dhis2/dhis2-core/pull/21792) I added default value for all `translations` with `null` value but missed the `section` table
- Add default value to `translations` column in `section` table
- Continue on [this PR](https://github.com/dhis2/dhis2-core/pull/21792) , add `not null` constraint on all tables which already have default value.
- Manually check the Data Entry App, no exception shown.
- All existing related unit tests should passes.
> fix: null translation in section table

- dhis-2/pom.xml
for now the [benchmark](https://github.com/dhis2/dhis2-core/pull/21761) is only run manually by devs. I did exclude the tag in all our maven test profiles which we use on github but forgot we also run on jenkins 😅 this excludes the tag by default. jenkins does a `mvn clean install` running all tests without the dedicated profiles. this is why this default should take effect. the profiles override the default so should also still work.
> ci: exclude benchmark from jenkins DHIS2-19910 [42]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportBasedOnSchemasTest.java
Disable e2e test while investigating below error 
```
{
"message": "One or more errors occurred, please see full details in import report.",
"response": {
"klass": "org.hisp.dhis.dataset.Section",
"errorReports": [
{
"message": "Invalid UID `85r6xhxmfwr` for property `Section`",
"args": [
"85r6xhxmfwr",
"Section"
],
"mainKlass": "org.hisp.dhis.dataset.Section",
"errorCode": "E4014",
"errorProperties": [
"85r6xhxmfwr",
"Section"
]
}
],
"uid": "85r6xhxmfwr",
"responseType": "ObjectReportWebMessageResponse"
}
}
```
> fix: disable e2e test postBasedOnSchema while investigating test failure

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/validation/validator/event/SecuritySingleEventValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/imports/validation/validator/event/SecuritySingleEventValidatorTest.java
When updating a single event, if the org unit is updated, we need to validate both the current org unit and the one in the payload. Currently, only the former is validated.
> fix: Validate payload org unit when single event update [DHIS2-20173]

- dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportBasedOnSchemasTest.java
- Added a fix but seems didn't work so I disable this `postBasedOnSchema` test again while continuing to investigate.
> fix: disable e2e test while investigating

- .github/workflows/run-performance-tests.yml
- dhis-2/dhis-test-e2e/pom.xml
- dhis-2/dhis-test-performance/README.md
- dhis-2/dhis-test-performance/docker-compose.profile.yml
- dhis-2/dhis-test-performance/pom.xml
- dhis-2/dhis-test-performance/run-simulation.sh
`run-simulation.sh` is used in our performance test comparison workflow added in https://github.com/dhis2/dhis2-core/pull/22026. The script can also be used locally to run the tests in the exact same way if we want to investigate any results in more detail. One method to get more insights is [profiling](https://github.com/async-profiler/async-profiler) which this PR adds. We could in theory profile on the GH runner. For now I suggest we only profile locally as the profiling artifact can be large depending on what you profile.
Pass `PROF_ARGS` to `run-simulation.sh` with any of https://github.com/async-profiler/async-profiler/blob/master/docs/ProfilerOptions.md and it will start/stop the profiler before/after the simulation run. The profiler results will be next to the Gatling results as …
> test: allow profiling performance tests DHIS2-20175

- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/DataValueFileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
Posting a file data value could fail storing the DV for example due to validation issues. This would leave the file resource behind. This PR fixes that by first storing the data value with a fresh UID, once that succeeds it file resource is created. This is so we avoid the complicated process of deleting an unwanted file resource. We rather delete an unwanted data value which is what is now happening should we fail to store the file resource.
See Jira
A test case was added to confirm.
> fix: make sure a failed POST of a DV with file does not leave parts behind [DHIS2-20190]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/scheduling/ContinuousAnalyticsTableJob.java
Back-port from https://github.com/dhis2/dhis2-core/pull/21959
> fix: remove analytics 0-partition tables on scheduled full update [2.42]

- .github/workflows/run-performance-tests.yml
- dhis-2/dhis-test-performance/README.md
- dhis-2/dhis-test-performance/docker-compose.profile.yml
- dhis-2/dhis-test-performance/docker-compose.yml
- dhis-2/dhis-test-performance/docker/Dockerfile.postgres
- dhis-2/dhis-test-performance/docker/dhis.conf
- dhis-2/dhis-test-performance/docker/log4j2.xml
- dhis-2/dhis-test-performance/run-simulation.sh
- dhis-2/dhis-test-performance/src/test/org/hisp/dhis/test/tracker/TrackerTest.java
* We used basic auth in our performance tests so far. This meant hashing showed up in our CPU profiles as we did that on every request. That is not how users should interact with our API though. Capture will login and use a cookie with the sessionid. Use the approach like in [AuthenticationControllerTest](https://github.com/dhis2/dhis2-core/blob/ed0fcc164296e2936bd9b9d6d7713ced6b762a46/dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/security/AuthenticationControllerTest.java#L80) and let Gatling handle the JSESSIONID cookie. Gatling detects `Set-Cookie` headers automatically in the response to login.
* Allow running specific performance tests via git tag in GitHub workflow using arg `perf_tests_git_ref`
* Allow profiling in GitHub workflow using arg `prof_args`
* …
> test: performance workflow improvements DHIS2-20175

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOption.java
- dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/CategoryOptionControllerTest.java
- During annotation migration, method `getDisplayFormName()` was missing
- Add back the method
- Add controller test to verify the change
> fix: add translation for categoryOption.displayName
