- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/entry.fileresource.js
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
Fixes bug where web-api would refuse reading 'locked' data values (should only refuse write and/or delete). Also implemented proper handling of the locket data set case for the DE file upload fields (i.e. button is disabled when dataset is locked).
> Fix bug with file upload fields and locked data sets in data entry

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/scheduling/SchedulingManager.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/scheduling/Scheduler.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/scheduling/SpringScheduler.java
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-dataadmin/src/main/java/org/hisp/dhis/dataadmin/action/scheduling/ScheduleTasksAction.java
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-dataadmin/src/main/resources/org/hisp/dhis/dataadmin/i18n_module.properties
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-dataadmin/src/main/resources/struts.xml
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-dataadmin/src/main/webapp/dhis-web-maintenance-dataadmin/javascript/scheduling.js
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-dataadmin/src/main/webapp/dhis-web-maintenance-dataadmin/viewScheduledTasks.vm
Reverts dhis2/dhis2-core#154
The reverted merge breaks the executeTask action for all other tasks by overriding and always running metadata sync. Should use executeTask.action?<metadata-sync-key> instead. Also, the code quality is just not good enough (please follow our basic Java conventions).
> Revert "Metadata sync now"

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/tasks/MetadataSyncTask.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/tasks/MetadataSyncTaskTest.java
Hi
We are from ThoughtWorks. We recently contributed 'Metadata Synchronization' feature to DHIS. This PR is continuation of those changes. Before this PR, metadata versioning was enabled by default on application startup. After this changes, it will not be so. It will be enabled only if it is explicitly enabled from settings-app or if user clicks 'sync now' button in metadata synchronization.
> Metadata versioning should not be enabled on application startup by default

- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-program/src/main/webapp/dhis-web-maintenance-program/addProgramRule.vm
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-program/src/main/webapp/dhis-web-maintenance-program/javascript/programRule.js
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-program/src/main/webapp/dhis-web-maintenance-program/updateProgramRule.vm
"programStage" : { "id": "" } is no longer a legal null value
> Updated program variable json to conform to API

- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-program/src/main/java/org/hisp/dhis/trackedentity/action/program/GetProgramAction.java
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-program/src/main/java/org/hisp/dhis/trackedentity/action/programstage/GetProgramStageSectionListAction.java
The old Struts actions GetProgramAction and GetProgramStageSectionListAction are missing i18nService translations for the return collections.
This fix apply to 2.24 only as from 2.25 I18nService is removed and replaced by new ObjectTranslation table.
> [2.24] Fix translations for ProgramStage and ProgramStageSection

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
fix bug missing JacksonXMLProperty localName attribute for dataElement.categoryCombo
> [2.25] fix bug missing JacksonXMLProperty localName attribute for DataElement.categoryCombo

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
fix bug missing localeName attribute for DataElement.categoryCombo
> fix bug missing JacksonXMLProperty localName attribute for DataElement.categoryCombo

- dhis-2/dhis-web/dhis-web-api/pom.xml
- dhis-2/dhis-web/pom.xml
- dhis-2/pom.xml
Generates necessary `rebel.xml` files under `target` when build is invoked using the `-Pdev` flag. Enables deploying the application with JRebel hotdeploy using mvn:jetty-*. (Requires JRebel to be installed and configured on the system).
> Add JRebel plugin setup to the maven 'dev' profile

- dhis-2/build.sh
- dhis-2/pom.xml
Hi,
We have run vulnerability checks on DHIS dependencies using the dependency-check maven plugin. This plugin wraps the OWASP Dependency Check utility which uses NIST’s National Vulnerability Database (NVD) to identify the vulnerable dependencies.
Changes in this PR: plugin version updated, aggregate goal added, command to run the plugin on every build.
Thanks
Aamer.
> Updated dependency check plugin version and added aggregate goal

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/Option.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTrackedEntityAttribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/Option.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramTrackedEntityAttribute.hbm.xml
Added sortOrder, as they are needed when exporting and importing the metadata objects.
(cherry picked from commit 0e835088ca801da7b71f7166c9ad0b6cd76741d5)
> Added sortOrder to Options and ProgramTrackedEntityAttribute

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/DefaultMetadataSyncService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/tasks/MetadataSyncTask.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/version/DefaultMetadataVersionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/version/MetadataVersionDelegate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/resources/META-INF/dhis/beans.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/scheduling/SchedulingManager.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/sync/MetadataSyncController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/version/MetadataVersionController.java
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-dataadmin/src/main/resources/struts.xml
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-dataadmin/src/main/webapp/dhis-web-maintenance-dataadmin/viewScheduledTasks.vm
Hi
We are from ThoughtWorks. This is regarding the metadata sync solution. Till now the create api and sync api will fail if concurrent threads are requested at single point of time. We have made the critical blocks synchronized so that no thread will fail in such case.
Thanks
> Thread safe metadata sync changes

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SmsUtils.java
This fixes two issues:
1. The check of the given month against the current month when deciding year didn't allow for the months being equal.
2. On the split of the message on space, it was taking the first element, which would be the sms command, not the date.
> Fixes for lookForDate in SmsUtils.java

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/DataSet.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryOptionComboNameResourceTable.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dataset/hibernate/DataSet.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/responseMetaData.vm
Added new set of periods for dataSets, which includes which periods data can be entered. If one or more periods exists for a dataset, all data entry must be targeting one of these periods.
Updated Data Entry app to only show open Periods in the period dropdown, if there exists one or more periods.
> Explicit open periods for data entry per data set

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DataValueSMSListener.java
Dates sent in through the DataValueSMS would get stripped out because they had a hypen (-). For example: 2016-11-29, only the 2016 would make it through, and then be rejected as an unacceptable value. Also, with comments only the first word would make it through and the rest would get stripped out. For example: "Oh my awesome comment", only the "Oh" will get taken without "my awesome comment".
> Refactor: Support dates & comments in DataValueSMS

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/configuration/ConfigurationDeletionHandler.java
Actually evaluate arguments - Previously failed as long as the config was set, regardless of its value.
> Fix ConfigurationDeletionHandler

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/DefaultMetadataSyncService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPostProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/tasks/MetadataSyncTask.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/sync/MetadataSyncController.java
Hi Morten,
These are minor changes as part of stopping metadata sync when version already exists in system. We have changed the logic to verify this scenario.
Thanks
> metadata sync log refactoring - master

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/DefaultMetadataSyncService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPostProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/tasks/MetadataSyncTask.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/sync/MetadataSyncController.java
Hi Morten,
These are minor changes as part of stopping metadata sync when version already exists in system. We have changed the logic to verify this scenario.
Thanks
> metadata sync log refactoring

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/TableAlteror.java
This commit will fix translations for categories that are not migrated properly to DHIS 2.25 from DHIS 2.23. Can you back port this commit to 2.24 branch as well?
> Fixed migration of translations for dataelement category

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/TableAlteror.java
This is backport of PR#546 for 2.25.
> Back port to fix migration of translations for dataelement category in 2.25

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationResult.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationResultService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationResultStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/validation/DefaultValidationResultService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/validation/ValidationResultDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/validation/hibernate/HibernateValidationResultStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationResult.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/validation/ValidationNotificationServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/batchhandler/ValidationResultBatchHandler.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DeletionHandler.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/validation/ValidationController.java
This _only_ adds the persisting of validations results, it does no change the way the validation rules are being analysed.
In addition a few notable changes to the validation result model:
- dayInPeriod: (int) represents when, relative to the period of the result, the analysis was done
- orgunit, period, rule, dayInPeriod and cat option combo is part of a unique constraint to the model.
> Persist validation rule violations

- dhis-2/pom.xml
Newer versions of Git 2.x change the length returned by `git rev-parse --short HEAD` from 7 characters to 8. This ensures the current behavior of 7 characters remains the same if the underlying tools are upgraded.
> Ensure build revision is always 7 characters

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DataValueSMSListener.java
Update SMSDataValueListener.java so that the SMSCodes within the SMSCommand are not converted to Upper Case, meaning the codes used in the SMSCommand can be case sensitive.
> Make SMSCodes case sensitive

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
Hi team,
We are unable to update/create some entities (`organisationUnits`, `CategoryCombos`) with matching uid's of other entities. For example If I have a `category` with uid '`abcedfghijk`' in DHIS and If I try to create/update a organisationUnit with same uid, it's throwing following error.
```
{
"httpStatus": "Internal Server Error",
"httpStatusCode": 500,
"message": "org.hisp.dhis.dataelement.DataElementCategory cannot be cast to org.hisp.dhis.organisationunit.OrganisationUnit"
}
```
If at all there was a uid collisions for existing entities in DHIS, then we are not able to edit those entities at all. This fix will identify entity store first and try find the object inside that store instead of searching in all entity stores.
> Fix to handle uid collisions across different entities during the entity create/update

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
This is back-port fix for 2.26
> [2.26] Backport fix to handle uid collisons across different entities during the entity create and update

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
This is back-port fix for 2.25
> [2.25] Backport fix to handle uid collisons across different entities during the entity create and update

- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-user/src/main/webapp/dhis-web-maintenance-user/addUserForm.vm
- dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-user/src/main/webapp/dhis-web-maintenance-user/javascript/user.js
https://jira.dhis2.org/browse/DHIS2-1439
This commit includes a fix for rawPassword validation. 
Currently in 2.27, after changing the form action from creation to invite user, the rawPassword 'remote' validation rule still effects which in result blocking the form submission.
> add encoding for email in addUserForm

- dhis-2/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-event-reports/scripts/app.js
On initial load of event reports page, both data elements and program indicators are listed on selection of program under aggregated values tab. This fix will filter program indicator on selection of program.
> [2.26] Fix in event reports page to display available items properly

- dhis-2/dhis-web/dhis-web-dashboard-integration/src/main/resources/org/hisp/dhis/dashboard/i18n_module.properties
- dhis-2/dhis-web/dhis-web-dashboard-integration/src/main/webapp/dhis-web-dashboard-integration/dashboard.vm
- dhis-2/dhis-web/dhis-web-dashboard-integration/src/main/webapp/dhis-web-dashboard-integration/javascript/dashboard.js
- dhis-2/dhis-web/dhis-web-dashboard-integration/src/main/webapp/dhis-web-dashboard-integration/style/dashboard.css
This PR implements some minor features and bug fixing regarding interpretations on the dashboard:
- Always display interpretation icon close to "Share Interpretation" text on dashboard item header.
- When clicking on interpretation/comment icon, interpretation modal will be open as usual. However, if no interpretation is found a share interpretation icon is displayed. Share interpretation link will redirect to chart or pivot app with the share interpretation dialog opened.
- If a user tries to share an interpretation for an object without permissions an error dialog will be displayed ('You don't have permissions to add an interpretation'). Before this PR, a cryptic 409 was displayed.
Not sure how to proceed about multilanguage. Please let us know if we should send a patch or create a PR …
> More interpretations improvements

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
https://jira.dhis2.org/browse/DHIS2-1596
After this fix, the below query will return only one record with event uid = WtUDEw3resf
http://localhost:8080/api/26/events/query.json?orgUnit=DiszpKrYNg8&programStage=Zj7UnCAulEk&event=WtUDEw3resf&dataElement=qrur9Dvnyt5,fWIAEtYVEGk,K6uUAvq500H
> Add matching event uid condition to events/query.json endpoint

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserCredentials.java
The attribute user is the one who created current user.. Maybe we should change this property name to "createdBy"
https://jira.dhis2.org/browse/DHIS2-1644
> Fix bug userCredential.getName() to get value from userinfo 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-web/dhis-web-importexport/src/main/webapp/dhis-web-importexport/javascript/metadataDependencyExport.js
- dhis-2/dhis-web/dhis-web-importexport/src/main/webapp/dhis-web-importexport/metadataDependencyExport.vm
Dashboard import is working fine with JSON but with XML format it failed.
This is caused by the "relativePeriods" property is missing "localName" attribute so the value is not imported.
https://jira.dhis2.org/browse/D227TEST-22
> Fix bug  import dashboard

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/view/CustomPathExtensionContentNegotiationStrategy.java
Fix bug exporting metadata is ignoring the compression settings.
This is caused by UriUtils.extractFileExtension which only support one dot character, 
which will fail if the path is dataSet.json.zip  -> return value is "zip"
https://jira.dhis2.org/browse/D227TEST-32
> Fix bug cannot download metadata with compression.

- dhis-2/dhis-web/dhis-web-dataentry/src/main/java/org/hisp/dhis/de/action/GetHistoryAction.java
https://jira.dhis2.org/browse/DHIS2-456
If user selects a period that does not exist in database, the method dataValueAuditService.getDataValueAudits() will query audit data with period = null.
While in method historyRetriever.getHistory(), it will force-add a non-existed period. 
So reorder those method calls will fix this issue.
> Fix bug auditTrails in dataEntry app show incorrect values.

- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
Not sure why but the below config  is not taking effect. All Access Voters in the list are not used for oauth2 authentication. Hence the result is always "Access denied"
```
<bean id="regularAccessDecisionVoting" class="org.springframework.security.access.vote.UnanimousBased">
<constructor-arg name="decisionVoters">
<list>
<ref bean="actionAccessVoter" />
<ref bean="moduleAccessVoter" />
<ref bean="authenticatedVoter" />
</list>
</constructor-arg>
</bean>
```
It works when I divide each AccessVoter into different AccessManager beans
Below is the result after the change
```
viet:~$ curl -X POST -H "Accept: application/json" -u test:c61535b8e-b6e2-6b49-6aa9-54a75cb9170 "http://localhost:8080/uaa/oauth/token?username=admin&password=district&grant_type=password" -v
*   Trying ::1...
* …
```
> Fix regularAccessVoting bean not taking effect in security.xml

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationResultService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationResultStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/validation/DefaultValidationResultService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/validation/hibernate/HibernateValidationResultStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/ValidationRunContext.java
ValidationRunContextBuilder now has a withInitialResults method for allowing DataValidationTask to skip validating existing results.
The final result of a DataValidation will still include old(skipped) and new violations.
> Updated ValidationRunContext to include a initial set of existing results

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/AuthenticationListener.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/DefaultAuthenticationSuccessHandler.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
Adding a listener for AuthenticationSuccessEvent which will be broadcasted for all login types. 
* WARN  2017-08-21 16:57:50,599 Authentication event AuthenticationSuccessEvent: admin; details: org.springframework.security.web.authentication.WebAuthenticationDetails@0: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: 9x3gg0gzlthqdu8rm1vdm5vl (LoggerListener.java [qtp579227762-16])
https://jira.dhis2.org/browse/DHIS2-1092
> Add AuthenticationListener

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
This modifies behaviour slightly but shouldn't break what is happening with DATIM.
When you post and use "?idScheme=CODE&categoryOptionComboIdScheme=UID" it will not require you to have codes on all your catoptcombos.  This is as it should be.  Specifying the categoryOptionComboIdScheme is necessary because the idschemes are all passed through to dxf2.
If you ARE using the categoryoptioncombos in DXF, like I have seen the use of attributeOptionCombo then you can use either the code or the uid, but if you insist on using the CODE then all your categoryoptioncombos will need codes as you have been doing.  It would be better to just use the UID for this or much better still, expand the attributeoptioncombo in adx eg. use mechanism='...'
> Adx fixes bob

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
https://jira.dhis2.org/browse/DHIS2-2199
The hideHeaderMessage() for i18n_orgunit_is_closed is also hiding data set locked message.
So use setHeaderDelayMessage instead, it will auto hide after few seconds.
TODO: backport to 2.28
> Fix DataSet Locked notification in DataEntry.

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
In the Events query, LIMIT and ORDER BY are used when paginated. Because of applying the LIMIT on a inner query and ORDER BY on the entire outer query, the inner part of the query is working as if there is no order and is giving inconsistent results.
To fix this, we have also added an ORDER BY clause to the inner query where LIMIT is applied.
Please let us know if anything else is to be done.
> Fixed Events API response inconsistency issue when paginated

- dhis-2/dhis-services/dhis-service-mobile/src/main/java/org/hisp/dhis/api/mobile/model/DataElement.java
1. Utilize the core ValueType.isNumeric() to detect if the data elemnt is numeric. This will ensure that numbers are not entered as free text on the J2ME client. 
2. Conditionally change the string that represent number type from "number" to "int" for DataElement serialize method on version 2.9 . Newer mobile client that can due with "number" will not be affected by this change.
> Update Mobile API 2.9

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/JCloudsFileResourceContentStore.java
Maybe we should make this configurable, it's possible that forcing path-style access could lead to new problems. An option for this seems a bit out of place in the config file because it's specific to s3. Ideally we would allow the users to define their own overrides, but we might want to put that on hold until we support more providers.
> bucketnames with dots

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/JCloudsFileResourceContentStore.java
- dhis-2/pom.xml
The callback would sometimes start executing before the transaction was done. Making file resource uploads non-transactional seems to have solved the problem.
> JClouds 2.0.3

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CodeGenerator.java
Makes 2 to the 64th possible UIDs rather than 2 to the 48th as with Random. Also makes generateUid() more than twice as fast.
> Replace Random with ThreadLocalRandom in generateCode

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.sharing.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/oust/oust.js
Make use of baseUrl variable in common javascript libraries 
This is for supporting convert the old core dashboard app to external one,  where it uses those common javascript libs under url path 'api/aps/..'
> Make use of dhis2.baseUrl for common javascript libs

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/schema/DefaultMergeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/CsvMetadataImportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/metadata/optionSet_add.csv
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/metadata/optionSet_update.csv
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/metadata/optionSet_update_duplicate.csv
https://jira.dhis2.org/browse/DHIS2-1322
Currently, In DedaultMergeService, target collection is always cleared and add all from sourceObject.
This patch add a merge function for collection depends on the merge mode
- If mergeMode.isMerge() : merge distinct source to target collection
- If mergeMode.isReplace() : clear target and replace by source collection
> Fix collection merge issue for metadata import.

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/VersionedObjectObjectBundleHook.java
https://jira.dhis2.org/browse/DHIS2-2747
The issue if data type of version is int, so if payload doesn't include it, the default value = 0 instead of null, so version is updated to 1.
This will add condition to check and only increase version properly.
> Fix update versionObject issue while importing metadata

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
* for queries with root-junction OR, skip criteria engine
* minor fix for persistedOnly queries
> for queries with root-junction OR, skip criteria engine (#1646)

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/ehcache-replication.xml
Added new config property to specify the remoteObjectPort for ehcache rmi peer listener factory.
> Provision to specify remoteObjectPort for ehcache 2.29

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/ehcache-replication.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/hibernate-caches.txt
Added new config property to specify the remoteObjectPort for ehcache rmi peer listener factory. Updated cache names to reflect all entitites and collection cache in 2.28
> Ehcache remote object port patch 2.28

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SettingKey.java
https://jira.dhis2.org/browse/DHIS2-1843
Test issue https://jira.dhis2.org/browse/DHIS2-3073
Issue: FileResourceRetentionStrategy SystemSetting value is saved in String, but getting as Enum value.
This fix doesn't solve the issue for existing value, need to save the setting again.
> Fix FileResourceRetentionStrategy enum casting error

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
Fixed a bug where userSettings would be saved as String not their appropriate class when using the api.
> Bug-fix: UserSettings stored as String not actual class

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/ProgramDataSynchronizationJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/SyncUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Adds logic to skip validation if it is a sync job that runs the query. Also broadens transaction over multiple methods so LazyInitializationException is avoided.
Removes event sync until issues with it are solved.
Adds more info into log message about success/failure of sync so the eventual issue can be investigated faster.
> Fixes issues with transcations and validation during sync job. - DHIS2-3080

- dhis-2/dhis-web/dhis-web-apps/pom.xml
DHIS2 master should use this artifact:
https://oss.sonatype.org/content/repositories/snapshots/org/hisp/dhis/dhis-app-maintenance/2.30-SNAPSHOT/
> Bump maintenance-app to use the 2.30-SNAPSHOT

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/pushanalysis/PushAnalysis.java
The property "schedulingdayoffrequency" is no longer used, but can not easily be removed. To solve this issue, the type of this property was changed from int to Integer to allow null values should they appear.
> PushAnalysis exception assign null to primitive type int

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/pushanalysis/PushAnalysis.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/pushanalysis/PushAnalysisService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerUpgrade.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/DefaultPushAnalysisService.java
Changed int to Integer to account for null-values (This property is not easily removed, but is not used after 2.29) for schedulingdayoffrequence
Re-added code for migrating PushAnalysis jobs to new scheduler.
> Fixed PushAnalysis upgrade from 2.28 to 2.29+

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
Considered possibility that no configuration exist at all for leader election
> Fixed leaderJobConfiguration error when redis is disabled 

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstance.java
Improves the logic how the SUCCESS/ERROR ImportSummaries are generated. Improves info/error messages.
Improves toString method (adds info about delete property)
Fixes the bug with not clearing the session when there are too few items in the collection.
>  Improves/fixes the logic for deletion of items - DHIS2-3080 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementStoreTest.java
If we have two unique attributes that have same value, getByUniqueAttributeValue() will throw error because it find 2 results.
> Fix issue with unique AttributeValue across Attributes

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java
https://jira.dhis2.org/browse/DHIS2-3612
Currently getByUid() return null if user doesn't have read access for a DE, hence it return object doesn't exists message.
=> Need to check if object exists first, then check for read access and throw appropriate error message.
> [DHIS2-3612] Handle appropriate error message for DE metadata read check.

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataExportParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataExportServiceTest.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldParser.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/FieldFilterParams.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/FieldParser.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/collection/CollectionUtils.java
The user wasn't cleared when calling MetadataExportService.getMetadata, but it seems to work fine in the api which uses getMetadataAsNode
> [DHIS2-2589] skip sharing for exporter

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/LocaleController.java
As per request from Hendrik 
> Now we have this 
>- `api/locales/ui` => UI Locales
>- `api/locales/db` => DB Locales without uuid etc
>- `api/locales/dbLocales` => DB Locales with uuid etc
>- `api/locales/{uid}` => GET/DELETE a DB Locale with uuid etc
>- `api/locales?country=VN&language=vi`  => POST a DB locale
>I feel like the distinction between UI and DB locales is somewhat lost in the last two….
>Wouldn’t it be better if it would be something like this (GET/DELETE/POST also under dbLocales):
>- `api/locales/dbLocales` => DB Locales with uuid etc
>- `api/locales/dbLocales/{uid}` => GET/DELETE a DB Locale with uuid etc
>- `api/locales/dbLocales?country=VN&language=vi`  => POST a DB locale (edited)
> Make endpoint /api/locales/dbLocales consistent for GET/ADD/DELETE.

- dhis-2/dhis-web/dhis-web-importexport/src/main/webapp/WEB-INF/web.xml
App uses _index.html_ for all inner app urls.
> remove postfix index.action from dhis-web-importexport

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/InterpretationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/NotificationType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/message/MessageService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/DefaultMessageService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/interpretation/impl/DefaultInterpretationService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/interpretation/InterpretationServiceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
If a user is subscribed to an analytical object, send a system notification message for any new interpretation, comment and like. Notifications are not sent to the current user (to avoid self-notifications)
This work has been done by @tokland and myself as part of this Jira issue https://jira.dhis2.org/browse/DHIS2-3891
> [DHIS2-3891] Send notifications to subscribers on new interpretation, comment and like

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/about/menuDashboard.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/about/action/RedirectAction.java
The dashboard now uses client-side routing using a hash. Therefore, it is no longer useful, and is in fact ugly, to include index.html in the url
> Remove index.html from url since dashboard uses hash routing now [DHIS2-3668]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
After the fix the error msg will look like below 
{"importParams":{"userOverrideMode":"NONE","importMode":"COMMIT","identifier":"UID","preheatMode":"REFERENCE","importStrategy":"UPDATE","atomicMode":"ALL","mergeMode":"REPLACE","flushMode":"AUTO","skipSharing":false,"skipValidation":false,"username":"testInter"},"status":"ERROR","stats":{"created":0,"updated":0,"deleted":0,"ignored":1,"total":1},"typeReports":[{"klass":"org.hisp.dhis.user.User","stats":{"created":0,"updated":0,"deleted":0,"ignored":1,"total":1},"objectReports":[{"klass":"org.hisp.dhis.user.User","index":0,"uid":"VjfCB52lPd1","errorReports":[{"message":"User `testInter` is not allowed to grant users access to user role `System administrator (ALL)`.","mainKlass":"org.hisp.dhis.user.UserAuthorityGroup","errorCode":"E3003"},{"m …
> [DHIS2-3871] Minor fix for ValidateUser error message E3003.

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/TableAlteror.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/commons/action/GetSystemAuthoritiesAction.java
Currently the custom app authority looks like this
{
"id": "M_See_Custom_Js_Css",
"name": "See Custom Js Css"
}
we need to remove the "See " part from both the id and the name, and then add a " app" suffix to the name (edited) so that it becomes
{
"id": "M_Custom_Js_Css",
"name": "Custom Js Css app"
}
> Minor fix for custom app authority name.

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/DefaultCategoryManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DataDimensionItemDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/EventPredictionServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/EventValidationServiceTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MaintenanceController.java
- Add DataDimensionItemDeletionHandler as below error is thrown.
- Created CategoryManager so the method deleteCategoryOptionCombo() will be called by CategoryService proxy, thus the DeletionHandlers can be triggered by Spring AOP.
ERROR 2018-07-03 21:22:38,084 ERROR: update or delete on table "categoryoptioncombo" violates foreign key constraint "fk_datadimensionitem_dataelementoperand_categoryoptioncomboid" on table "datadimensionitem"
> [DHIS2-4045] [DRC-29] Fix bug can't run update catOptionCombo in Data Admin app.

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
Fixing the problem with having wrong values in public static final field which lead to unexpected behavior (e.g. when sync job run first and then some request for the API came, the includeDeleted was set to true which was not planned)
> Fixes bug with unintentional return of deleted events. - DHIS2-4276

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
Move the below method call outside of the loop. 
Set<TrackedEntityAttribute> readableAttributes = trackedEntityAttributeService.getAllUserReadableTrackedEntityAttributes( user );
https://jira.dhis2.org/browse/DHIS2-4230
I will port this fix to other versions after it is reviewed and merged.
> [Dhis2-4230] 2.29 Performance fix for api/trackedEntityInstances

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentitydatavalue/TrackedEntityDataValue.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentitydatavalue/TrackedEntityDataValueService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentitydatavalue/TrackedEntityDataValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitydatavalue/DefaultTrackedEntityDataValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitydatavalue/hibernate/HibernateTrackedEntityDataValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentitydatavalue/TrackedEntityDataValueServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentitydatavalue/TrackedEntityDataValueStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
Backport to 2.30 - Fixes bug with not skipping synchronization of PSDEs that are marked with Skip synchronization property and so should be skipped.
Removes SupressWarnings as it is not needed anymore
> Fixes bug with not skipping PSDEs that should be skipped - DHIS2-4280

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/gml/DefaultGmlImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/gml/GmlImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataImportParams.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataImportController.java
This is to add back the csv and gml metadata import api. Before it was in MetadataImportAction, which is removed together with import/export struts module.
> Add csv and gml import functions for MetadataImportController

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataImportController.java
This is for new reactjs import/export app, to return the list of supported Metadata classes that can be imported using CSV format. 
Below is the response 
[
"ORGANISATION_UNIT_GROUP_MEMBERSHIP",
"DATA_ELEMENT_GROUP_MEMBERSHIP",
"INDICATOR_GROUP_MEMBERSHIP",
"DATA_ELEMENT",
"DATA_ELEMENT_GROUP",
"CATEGORY_OPTION",
"CATEGORY_OPTION_GROUP",
"ORGANISATION_UNIT",
"ORGANISATION_UNIT_GROUP",
"VALIDATION_RULE",
"OPTION_SET",
"TRANSLATION"
]
> Add api for returning CsvImportClass enum in MetadataImportController.

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElementCategoryOptionCombo.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
In method AbstractEventService.saveEvent(....) line 1341
All defaults object from the cache fail to load the lazy collections. This may due to the fact that this saveEvent method is a private method, and hence the @Transactional doesn't have effect, and session is lost. 
This is a quick fix for the issue 
https://jira.dhis2.org/browse/DHIS2-4480 as it's urgent.  We need to look for a better solution for this issue later
Below is screenshot in debug mode.
> [DHIS2-4480] 2.29 Fix lazy load issue for default coc cache.

- dhis-2/pom.xml
* Cobertura support has been deprecated by sonarqube some versions ago and the only supported code coverage tools is JaCoCo.
> Added JaCoCo for test coverage reporting

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/JdbcCompleteDataSetRegistrationExchangeStore.java
Fix minor issue with `Collectors.joining( " ", "ou.path LIKE '", "%' OR" )` which only add suffix (%) to the end of the final string.
Need to backport down to 2.29 
https://jira.dhis2.org/browse/DHIS2-4796
> [DHIS2-4796] Fix bug cannot query CompleteDataSetRegistration with children=true

- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/ehcache.xml
Ensure that default cache is expired less frequently than query cache to avoid single-entity queries.
> Hibernate query cache configuration update

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationAsyncTask.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
Got this error when enroll for a program in Tracker Capture app in 2.29
`Unexpected error occurred invoking async method 'public void org.hisp.dhis.program.notification.ProgramNotificationListener.onEnrollment(org.hisp.dhis.program.notification.ProgramNotificationEvent)'. (SimpleAsyncUncaughtExceptionHandler.java [taskScheduler-16])
org.hibernate.LazyInitializationException: could not initialize proxy - no Session`
In ProgramNotificationListener, methods are marked with Async annotation, so it is required to implement runnable interface which can open/close session in a new thread. 
- Add ProgramNotificationAsyncTask
- Use TransactionTemplate in DefaultProgramNotificationService so methods called is executed in a spring transaction ( Transactional annotation doesn't work maybe because of …
> 2.29  Fix no session error in ProgramNotificationService

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
https://jira.dhis2.org/browse/DHIS2-4503
When querying data values on the /events endpoint, you can sort and filter data values normally, except for option sets, where the user will filter based on the name of the options, and the underlying filter in the database will compare the data value based on option code... not name.
API request : 
http://localhost:8080/api/events?filter=K6uUAvq500H:like:exposure&program=eBAyeGv0exc&orgUnit=DiszpKrYNg8&pageSize=15&page=1&order=eventDate:desc&totalPages=true
SQL query : 
```
select * from (select psi.programstageinstanceid as psi_id, psi.uid as psi_uid, psi.code as psi_code, psi.status as psi_status, psi.executiondate as psi_executiondate, psi.duedate as psi_duedate, psi.completedby as psi_completedby, psi.storedby as psi_storedby, psi.created as …
```
> [DHIS2-4503] Fix bug query events with OptionSet filter

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/ldap/authentication/CustomLdapAuthenticationProvider.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/security.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/AuthenticationListener.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/BasicAuthenticationEntryPoint.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
- Add BasicAuthenticationEntryPoint for return auth failed message in json format ( currently returning html ) 
- Add CustomLdapAuthenticationProvider to check for Ldap Configuration in DHIS2 before delegating authentication process to LdapAuthenticationProvider. 
https://jira.dhis2.org/browse/DHIS2-4953
> [DHIS2-4953] Fix bug block failed login attempts with basic authentication.

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/DefaultPushAnalysisService.java
https://jira.dhis2.org/browse/DHIS2-1691
The method fileResourceService.saveFileResource() has already run async, so we don't need another job async to wrap outside, that will lead to the error 
`Not-null property references a transient value - transient instance must be saved before current operation : org.hisp.dhis.fileresource.ExternalFileResource.fileResource -> org.hisp.dhis.fileresource.FileResource`
> [DHIS2-1691] Fix bug cant save externalFileResource in PushAnalysisService.

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/DefaultCategoryManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
https://jira.dhis2.org/browse/DHIS2-4045
Current DeletionHandler aspect throws DeleteNotAllowedException, this will cause spring to mark the current transaction as `rollback-only` as below.
One solution is to tell spring to ignore this specific exception and not to rollback the transaction using the annotation `@Transactional( noRollbackFor = DeleteNotAllowedException.class )`, and this must be put at the delete service method where the exception is thrown.
This fix is only applied for the function in Data Admin App -> Maintenance -> Update Category Option Combinations
` WARN  2018-11-19 13:02:16,897 Could not delete category option combo: {"class":"class org.hisp.dhis.category.CategoryOptionCombo", "id":"359663", "uid":"YEmiuCcgNQI", "code":"COC_359663", "categoryCombo":{"class":"class …
> [DHIS2-4045] Fix bug TransactionRollback when deleting COC.

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
The user authority `AUTH_VIEW_EVENT_ANALYTICS` is:
- **CHECKED** for `/analytics/events/query` (in `DefaultEventAnalyticsService::getEvents` with `securityManager.decideAccessEventQuery`) 
- **NOT CHECKED** for `/analytics/events/cluster` (`DefaultEventAnalyticsService::getEventClusters`)
- **NOT CHECKED** for `/analytics/events/count` (`DefaultEventAnalyticsService::getRectangle`).
- **NOT CHECKED** for `/analytics/events/aggregate` (in `EventAnalyticsController::getAggregatedEventData`)
This permits an **unauthorized** user to view event analytics information with several /analytics/events endpoints, and to successfully add server-clustered events layers in the Maps app.
This will be back-ported to 2.31/2.30/2.29 as it exists in those releases as well.
> Permissions issue - DHIS2-5408

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/i18n/I18nFormat.java
https://jira.dhis2.org/browse/DHIS2-5562
period.getStartDate().toInstant() throw java.lang.UnsupportedOperationException() if the date doesn't include time or it's a java.sql.Date class
This need to be backported
> [DHIS2-5562] Fix bug weekly dataset report failed in Report app.

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.availability.js
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/entry.js
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
https://jira.dhis2.org/browse/DHIS2-4928
After this fix,  when user enters data 
- If session time out and server still online -> show login dialog on top of the screen and send ping request every 10s.
- If server offline -> show server offline message -> ping every 10s -> if server gone online -> show login dialog
After user logging in, stop sending ping request. 
This can be backported
> [DHIS2-4928] Remove ping request for online status from aggregate data entry.

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
See explanation given for v2.30: https://github.com/dhis2/dhis2-core/pull/2789#issue-246996173
This PR is the same but for v2.31.
> chore(messaging-app): use master-branch for dhis2-core v2.31

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
As discussed on Slack, we have introduced a "feature-toggling" mechanism in the messaging-app. This means all dhis2-core versions (starting 2.30, which is when the messaging-app was introduced) can run the master branch of the messaging-app. This will improve the maintainability of the app.
I've created a test case https://jira.dhis2.org/browse/DHIS2-5808 and Gintare has executed these tests in a staging environment (https://dhis2.vardevs.se/2.30).
So now we are ready to switch to master...
> chore(messaging-app): use master branch for dhis2-core v2.30

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
TEI payloads that included relationships with entities the user did not have view access for would reject the entire request. Relationships are now only included if the user have sufficient access to both parts of the relationship
Issue: DHIS2-5870
> Fixed an issue with TEI and relationship access

- dhis-2/dhis-web/dhis-web-apps/scripts/git.js
I was having trouble downloading the entire 1.7GB worth of web-apps from each of the 28 repositories on an unstable connection, so I added a retry mechanism to the download so it wouldn't have to start again each time.
Looking at the code this is probably one for @varl to look at
> feat: add retry to webapp download

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipType.java
Schema for RelationshipType was previously reporting the RelationshipConstraint "from" and "to" as not required, while it is in fact required. Annotations were added to the properties to report them as required in the schemas endpoint.
Issue: DHIS2-5738
> Fix missing required annotation for RelationshipConstraint

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
TrackedEntityInstance payloads currently only list relationships going out from the TrackedEntityInstance. This list should also include relationships coming in to the TrackedEntityInstance.
Issue: DHIS2-5924
> Add incoming relationships to TrackedEntityInstance payload

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalItemId.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DefaultDimensionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dimension/DimensionServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
When parsing expressions, each DimensionalItemObject (and each IdentifiableObject it contains) has been looked up individually, slowing performance when many objects are needed in an expression, and especially when sharing is checked on each object. This fix looks up all IdentifiableObjects of each type with a single call.
> DHIS2-5956 Dimension Restriction slows down pivot tables

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
This commit is fixing:
DHIS2-5456: Error in updating "Permanently remove soft deleted tracked entity instances"
> Fix Permanently remove soft deleted tracked entity instances due to FK

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipType.java
The PropertyType of RelationshipContraint was incorrectly falling back to the default TEXT, causing validation errors in the Maintenance app. It is now correctly being marked as COMPLEX.
Issue: DHIS2-6050
> Fix issue with RelationshipConstraint PropertyType

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
When updating a TrackedEntityInstance, relationships pointing to the TEI would be removed.  Only relationships pointing out form the tei is now applicable for removing during update.
Issue: DHIS2-5685
> Fix unintended removal of relationships for TrackedEntityInstances

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
Incoming relationships are now listed in the TEI payload when relationships are included. This commit additionally includes adding read access check to each relationship which had not been backported to 2.30 by mistake.
> Add read access control to and include incoming relationships

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryType.java
Fixes bug with improperly configured ObjectMapper. A different ObjectMapper with specific mapping has to be used.
DHIS2-6102
> Fixes jsonb object deserialization issue - DHIS2-6102

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/partition/JdbcPartitionManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/partition/PartitionManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
The event table manager was counting both the event and enrollment tables as its own. At the same time the enrollment table manager did not return any tables in the getExistingDatabaseTables() function.
> Fix technical weakness in event table managers

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/acl/AclService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
> [2.29] Allow access to metadata when item is not DataShareable

- dhis-2/dhis-web/dhis-web-api-test/pom.xml
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/mvc/messageconverter/AbstractRootNodeMessageConverterTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/AbstractRootNodeMessageConverter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/CsvMessageConverter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/ExcelMessageConverter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/JsonMessageConverter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/JsonPMessageConverter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/PdfMessageConverter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/XmlMessageConverter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
- Parameter download=true can be added to /api/metadata in order to request that Content-Disposition: Attachment is added to the response in order to force the browser to offer downloading the file instead of displaying it in browser window.
> DHIS2 6159: Download parameter for /api/metadata endpoint

- dhis-2/dhis-web/dhis-web-apps/pom.xml
- dhis-2/dhis-web/dhis-web-apps/scripts/bundle-apps.js
- dhis-2/dhis-web/dhis-web-apps/scripts/git.js
The size of the history of d2-ci repos have increased a lot. Cloning https://github.com/d2-ci/maintenance-app is 300MB of just history. `--depth 1 --no-single-branch` does not reduce the size a lot, due to `--no-single-branch`, probably because of the vast amount of branches. 
This commit changes the behaviour of cloning the repos. Now it first tries to do a true shallow clone. This dramatically decreases the objects downloaded. However, this comes with a small catch: we cannot use this for commit hashes (surprisingly works with tags though). So that means we have to use the old method with --no-single-branch when a commit is specified in `apps-to-bundle.json`. However this will decrease the build time in most clean-install cases tremendously. 
Results on my machine:
dhis-web-apps build …
> Optimize web apps build 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/AnalyticsPeriodBoundary.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/statementbuilder/AbstractStatementBuilder.java
When using the custom boundary targets like data elements and attributes, combining it with the one of the affected boundary types - there was an error in the underlying query:
- "After end of reporting period" gets substituted for "After start of reporting period".
- "Before start of reporting period" gets substituted for "Before end of reporting period".
> [DHIS2-6208] Fix error with custom boundary types

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.32/V2_32_10__Use_bigint_for_id_columns.sql
Add runtime config parameter setting for max_locks_per_transaction in the flyway script.
Removed unused tables and columns in the script.
> Fix bigint flyway upgrade script

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationTestConfig.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/container/DhisPostgisContainerProvider.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/container/DhisPostgreSQLContainer.java
Extended testcontainer classes to create a custom DhisPostgreSQLContainer that can be used to provide custom configurations for postgres when the postgres container starts for integration tests. max_locks_per_transaction is now set to 100 for postgres test containers.
> Fix integration test failing with out of memory postgres

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfigurationDeserializer.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobConfigurationDeserializerTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobConfigurationTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHookTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataImportController.java
- Just adding new jobs worked for JSON (updating did not work).
- New system jobs have standard UIDs in order to enable import on
different systems in future versions.
- Create and update has been fixed for JSON.
- Create and update has been excluded (as in 2.29 and due to sync
issues).
> Fixed issue with metadata import for job configurations (#5918)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/IndexedObjectContainer.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ObjectIndexProvider.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ObjectReport.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/TypedIndexedObjectContainer.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/feedback/IndexedObjectContainerTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/feedback/ObjectReportTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/feedback/TypedIndexedObjectContainerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundle.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleTest.java
- Objects are divided in persisted and non-persisted objects.
- Zero based indexes for persisted and non-persisted objects
where used for union of both (colliding indexes) when reporting
results.
- Indexes in returned results are now the indexes of the original
requested typed data.
> Fixed issues with colliding indexes in type import reports (#5937)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
Properties regressionType and hideEmptyRowItems in BaseChart was null by default which caused issues when inserting into not-null fields in database. These properties now have "NONE" as their default values.
Issue: DHIS2-6735
> Fix null-values when creating chart

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
Properties regressionType and hideEmptyRowItems in BaseChart was null by default which caused issues when inserting into not-null fields in database. These properties now have "NONE" as their default values.
Issue: DHIS2-5735
> Add default values for regressionType and HideEmptyItemStrategy in BasChart

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
Properties regressionType and hideEmptyRowItems in BaseChart was null by default which caused issues when inserting into not-null fields in database. These properties now have "NONE" as their default values.
Issue: DHIS2-5735
> Add default values for regressionType and HideEmptyItemStrategy in BaseChart

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
Method was using the same logic as AbstractCrudController, but did not return the proper response as expected. By removing the method, maps are now created similar like other metadata using AbstractCrudController and returns the appropriate response.
Issue: DHIS2-5739
> Remove overriding method for POST maps

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- Set null values to 5 when returning an analytics Grid where the request has no Dimension Indicator
> Fix number of null values added to Grid

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupAccess.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_chart_with_accesses.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_chart_with_accesses_update.json
https://jira.dhis2.org/browse/DHIS2-5504
When updating a `Chart` the persistedObject's userAccesses and userGroupAccesses were cleared out by the method
`EmbeddedObjectObjectBundleHook.clearEmbeddedObjects( persistedObject, properties );`
the list of embeddedObjectProperties is
```dataElementGroupSetDimentsions
userGroupAccesses
categoryoptionGroupSetDimensions
userAccesses
organisationUnitGroupSetDimensions
categoryDimensions```
=> So we need to remove the implementation of  the interface`EmbeddedObject` from `UserAccess` and `UserGroupAccess`
> [DHIS2-5504]  Fix bug reset sharing when update EmbeddedObject with skipSharing

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DashboardControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataSetControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/category/CategoryComboControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtilsTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryComboController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementGroupController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtils.java
- The same export parameters that are used for normal export are now
used for export with dependencies (even if just some of the options
are used). This enables future extensions.
- The download parameter can be added to all endpoints in order to
get the metadata as an attachment.
- All fields will be excluded in all skip sharing exports:
"user", "publicAccess", "userGroupAccesses", "!userAccesses",
"externalAccess" (at the moment just some of them, caused by filter).
> Added skipSharing for metadata export with dependencies (#5292)

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
@varl noticed that after the changes from https://jira.dhis2.org/browse/DHIS2-5081, we're sending a double encoded request from the data-entry app (from [here](https://github.com/dhis2/dhis2-core/blob/2.30/dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js#L1079)). It doesn't affect all browser (doesn't affect FF for example).
See also:
- https://github.com/dhis2/dhis2-core/pull/3071
- https://github.com/dhis2/dhis2-core/pull/3072
- https://github.com/dhis2/dhis2-core/pull/3073
> Fix double encoded request in data-entry-app (v30)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
userCredentials was originally not marked as required, despite being so - this has been fixed. As a result, two additional issues were discovered and fixed: NullPointerException when userCredentials is not in the payload and inserting null for userInfo in UserCredentials. The first was fixed by moving logic from the controller to the ObjectBundleHook and the second by updating UserCredentials with the correct userInfo reference before saving.
Issue: DHIS2-5732
> Fix user creation issues

- dhis-2/dhis-api/pom.xml
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/Category.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryCombo.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOption.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOptionCombo.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/SystemDefaultMetadataObject.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/category/CategoryComboTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/category/CategoryOptionComboTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/category/CategoryOptionTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/category/CategoryTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
The classes had already a method isDefault(), but no common interface that defines that method. A new interface that can be used to check if an object is a system default metadata object has been introduced and is checked when sharing settings are tried to get updated.
> Added protection of sharing settings of default objects (#4455).

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Order.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/JpaQueryUtilsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/OrderTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryUtilsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/OrderParams.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- In memory query engines does not handle null values correctly (random order).
- Sort on resulting users is based on paged result not on absolut result.
> Fixes sort issues on /api/users endpoint (#4645)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceReportingRateTest.java
- DHIS-1217
- Modified the AnalyticsService so that when a Reporting Rate has no value for a particular data set,
the returned Reporting Rate is 0 rather than null
> Update Analytics Reporting Rate logic to return 0 when null

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/DefaultPredictorService.java
Added `@Transactional` annotation to `PredictionService`.
A Docker-based integration test was failing and this fixed the broken test.
> Update PredictionService to use Transactional annotations

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstance.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- Skip time stamp update when unnecessary
- Remove unnecessary TEI update
The rule is: If event payload is received through TEI endpoint, there is no need to update TEI while processing events.
> Avoid potential circular check for tei-pi-psi

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackerOwnershipController.java
- Removed overloaded methods from `TrackerOwnershipManager` which were forcing the class to do a lookup through the `TrackedEntityInstanceService`
> Remove circular dependency between Spring beans

- .travis.yml
This PR included integration test runs into travis PR check. 
Integration tests runs in parallel with unit tests and based on my tests on travis, finishes earlier than unit tests, so it doesn't bloat travis build time.
> Included integration tests as parallel travis job

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/DefaultPushAnalysisService.java
https://jira.dhis2.org/browse/DHIS2-6559
display an error image as below if generated map is null because of no data.
> Fix bug pushAnalysis service throws error when generated map is null

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/interpretation/impl/DefaultInterpretationService.java
https://jira.dhis2.org/browse/DHIS2-4848
Use a system message (instead of a private message) to notify a user that he/she was mentioned.
> Notify mentions using system messages

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/DefaultLinkService.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/service/DefaultLinkServiceTest.java
When there are dots in the URI path (e.g. version numbers on play
environments) the resulting pager URL is invalid.
> Fixes issues with dots in URI for pager links (4896)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DashboardControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataSetControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/category/CategoryComboControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtilsTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryComboController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dashboard/DashboardControllerV2.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementGroupController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtils.java
- Backport from 2.32
- The same export parameters that are used for normal export are now
used for export with dependencies (even if just some of the options
are used). This enables future extensions.
- The download parameter can be added to all endpoints in order to
get the metadata as an attachment.
- All fields will be excluded in all skip sharing exports:
"user", "publicAccess", "userGroupAccesses", "!userAccesses",
"externalAccess" (at the moment just some of them, caused by filter).
>  Added skipSharing for metadata export with dependencies (#5292)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserCredentials.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/user/UserCredentialsTest.java
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/CategoryOption.hbm.xml
- dhis-2/dhis-services/dhis-service-schema/pom.xml
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/SchemaTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_33_3__Create_categories_categoryoptions_index.sql
- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryType.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonEventDataValueSetBinaryType.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonJobParametersType.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonListBinaryType.java
- dhis-2/dhis-support/dhis-support-hibernate/src/test/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryTypeTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/test/java/org/hisp/dhis/hibernate/jsonb/type/JsonListBinaryTypeTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/test/java/org/hisp/dhis/hibernate/jsonb/type/JsonSetBinaryTypeTest.java
- Resolves issue DHIS2-6491.
- Adds an index for category options to their categories on specific database table.
- Reduces the amount of database queries immensely by using batch association fetches for category options.
- Frequently accessed accessed user and schema data that must be calculated is cached.
- Optimized deep copying for Hibernate PostgreSQL JSONB type.
- Not all of the commits would be backported (limiting risk) and also batch sizes would be reduced.
> Resolve performance issues with large category option requests

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
- Fixes issue TECH-168
- User credentials that are stored in session must not be managed since
the managed user credentials may be changed during first request
(especially by metadata importer) which results in unwanted behaviour.
> Places detached user credentials into session.

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
Reverted code to 2.31 status to avoid generated SQL to wrap `SELECT` statement columns in `lower` function.
> [2.32] Fix lower case values in Events Analytics response

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- DHIS2-6885
- Altered INSERT query that populates the Event and Enrollment nalytics table to
fetch the OU name when the Data Element is type 'ORGANIZATIONALUNIT', instead
of the OU UID
- Added unit tests
> [2.29] Fix OU name not displayed in event report

- dhis-2/dhis-e2e-test/docker-compose.yml
#3284 seems to break our tests - application is no longer served after build. Solution stolen from https://github.com/amcgee/dhis2-backend/pull/2
> Fix docker compose after tomcat config change

- Dockerfile
Problem: Jenkins jobs on jenkins which uses docker (api tests, integration tests) fails with OOM error almost every day - https://jira.dhis2.org/browse/AUTO-34
Multi-stage docker builds create image for every stage to achieve cacheing. In our case, early stage (build) image is 5.7gb, so after several builds, if not removed, makes docker struggle with memory. Dangling images can be removed by running `docker image prune`, but on shared environments like jenkins this can cause race conditions and remove needed images. 
Solution for now is to tag intermediate images and remove old ones by running 
`docker image prune --filter label=stage=intermediate`.
> Adding label to docker build stage for cleaning up intermediate images 

- dhis-2/dhis-e2e-test/docker-compose.yml
- server.xml
As #3284 had unintended consequences I think it is prudent to revert this to allow the image to be consistent with a default DHIS2 Tomcat configuration.
> revert: use context.path if available

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-node/pom.xml
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldParser.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/AbstractNode.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/Node.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/Jackson2JsonNodeSerializer.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/transformers/PluckNodeTransformer.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/types/CollectionNode.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/types/SimpleNode.java
- dhis-2/dhis-services/dhis-service-node/src/main/resources/META-INF/dhis/beans.xml
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldParserTest.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/AbstractNodeTest.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/transformers/PluckNodeTransformerTest.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/types/CollectionNodeTest.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/types/ComplexNodeTest.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/types/SimpleNodeTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
- Issue TECH-175 (backport until 2.31)
- Performance enhancement for category options with a big amount of organisation units.
- Adds fast path for writing metadata JSON strings.
- Reduces object creation for metadata nodes.
- Removes not required contains check from Schema.getProperty().
- Adds short path for filtering ID only identifiables.
- Provides ability to transform array objects to array of specific field.
> Increases performance for category options with many assigned organisation units

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/MetadataVersionWrapper.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
Existing metadata version payloads are wrapped to preserve the order of the JSON keys before the table column is converted to JSONB data type
DHIS2-6848
> Wrap existing metadata version payloads before changing data type

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/MetadataItem.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
In analytics metadata response for items, the value type property can now be any of these:
- NUMBER
- BOOLEAN
- DATE
- FILE_RESOURCE
- COORDINATE
- TEXT
This to expose an appropriate level of detail to the client. More detailed value types such as "positive integer" are folded under NUMBER, etc.
Backport from 2.32 (DHIS2-5854)
> [2.30] Use simplified value type in analytics metadata

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
- Fixes issue DHIS2-5535 in master.
- After adding Spring annotation processing the hook was not
discovered anymore.
> Adds missing @Component to OptionObjectBundleHook.

- Jenkinsfile-publish-image
- dhis-2/dhis-e2e-test/Dockerfile
- dhis-2/dhis-e2e-test/docker-compose.e2e.yml
- dhis-2/dhis-e2e-test/docker-compose.yml
- dhis-2/dhis-e2e-test/wait-for-it.sh
This PR enables parallel test execution on CI server:
- avoiding port collisions by running tests in a docker container. This way port doesn´t have to be expose to host machine and tests can communicate with backend in isolated network;
Adds Jenkinsfile with the pipeline for publishing docker images. For testing I used my docker hub account, but as soon as everything works I will use dhis2 account - it's only a matter of configuring "$DOCKER_HUB_OWNER" variable in jenkins and changing credentials in credentials manager.
- Multibranch pipeline requires "jenkins-as-code" pipeline definition, hence the Jenkinsfile.
> AUTO-37: pipeline for pushing docker images

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/dashboard/impl/DefaultDashboardService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/dashboard/DashboardServiceTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DashboardControllerTest.java
- DHIS2-7036
- Introduced `count` and `maxCount` parameters to `/dashboard/q` endpoint
to let clients specify the number of Dashboard items returned or the max
number of Dashboard items returned when the `max` param is used
- Add tests
> Support max returned values in Dashboard endpoint

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/MetadataItem.java
In analytics metadata response for items, the value type property can now be any of these:
- NUMBER
- BOOLEAN
- DATE
- FILE_RESOURCE
- COORDINATE
- TEXT
This to expose an appropriate level of detail to the client. More detailed value types such as "positive integer" are folded under NUMBER, etc.
(cherry picked from commit 4a4d0bcda27ea5c040732d440530d6cd1909da49)
> [2.29] Use simplified value type in analytics metadata

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalKeywords.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultDataQueryServiceTest.java
- DHIS2-4890
- Fix Level metadata not returning when analytics query contains `OUGROUP-`
and `LEVEL-`
> Fix missing Level metadata info when OUGROUP and LEVEL is used

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdScheme.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdSchemes.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/leader/election/LeaderRenewalJob.java
Deserialization of ImportOptions fails due to IdSchemes and IdScheme classes. Fixed it by adding necessary annotations for jackson to use. This is only used in a horizontally scaled dhis2 using redis.
> Add jackson annotation to IdSchemes and IdScheme (master)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryItem.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
Program and tracked entity type have minimum length of attributes users are required to fill in order to search for TEIs.
Such requirements can be skipped when users are searching using unique attributes
> Skip min srch att restriction for unique atts

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
When running a predictor, and a datavalue record is encountered with a null value, the predictor aborts with a NullPointerException.
> Predictor NullPointer when datavalue is null DHIS2-7127

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- DHIS2-7263
- Fixed incorrect INSERT query for Event analytics tables generated from
Programs having one or more Tracked Entity Attributes with Value Type: Organizational Unit
> [2.29] fix: Invalid INSERT query for Event analytics tables

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- DHIS2-7279
- Only populate analytics enrollment table's latitude/longitude if the
Program Instance geometry column is of type POINT
> [2.32] fix: Handle non-POINT Geometry from ProgramInstance on table export

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- DHIS2-7100
- Fixed query returning Tracked Entity Instances, where attributes
of type OrgUnit were returned as Org Unit UID rather than Org Unit name
- backport from 2.32
> [2.31] Fix invalid value returned from TEI query when TEA is OrgUnit type

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- DHIS2-7100
- Fixed query returning Tracked Entity Instances, where attributes
of type OrgUnit were returned as Org Unit UID rather than Org Unit name
- Back-port from 2.32
> [2.30] Fix invalid value returned from TEI query when TEA is OrgUnit type

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- DHIS2-7100
- Fixed query returning Tracked Entity Instances, where attributes
of type OrgUnit were returned as Org Unit UID rather than Org Unit name
- Back-port from 2.32
> [2.29] Fix invalid value returned from TEI query when TEA is OrgUnit type

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/condition/PropertiesAwareConfigurationCondition.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/HibernateMetricsConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/MetricsEnabler.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/ProcessorMetricsConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/UptimeMetricsConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/DataSourcePoolMetadata.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/monitoring/metrics/jdbc/DataSourcePoolMetrics.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/config/WebMvcMetricsConfig.java
- dhis-2/pom.xml
- Bumped micrometer to version 1.2.0
- Added uptime and cpu metrics
- Optimized DB Pool metrics to show idle connections and use tags for datasource names
- Reverted to use deprecated constructor for `WebMvcMetricsFilter`, since the non-deprecated one
does not work
- Changed prefix of API metrics to `http_server_requests` to be in-sync with spring boot
> optimize: added new monitoring metrics and optimized db pool metrics

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/StreamingJsonDataValueSet.java
> fix: improve Jackson JSON streaming performance

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceAuditService.java
- DHIS2-7323
- Fixed by making Audit Service to run in its own TX context
(cherry picked from commit c118a4b013148ea11a0ce30d115cb0ccb5818401)
> [2.31] fix: error get Enrollments through `/api/enrollments.json` endpoint

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceAuditService.java
- DHIS2-7323
- Fixed by making Audit Service to run in its own TX context
(cherry picked from commit c118a4b013148ea11a0ce30d115cb0ccb5818401)
> [2.32] fix: error get Enrollments through `/api/enrollments.json` endpoint

- Jenkinsfile-publish-image
Jenkins agent we run docker pipelines on frequently runs out of memory, because dangling images are not removed correctly. That is because stopped containers were sometimes not removed and images were not pruned. Hopefully this will fix it - if yes, I will back-port to all versions.
> Removing stopped containers with compose down

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManagerTest.java
- Removed unused variables from unit test
- Use real `StatementBuilder` instead of Mock
> refactor: Unit test refactor for better readibility

- Jenkinsfile-publish-image
- dhis-2/dhis-e2e-test/Dockerfile
- Removed stopped containers to avoid dangling images not being cleaned up; 
- Optimized e2e image tiny bit to save more space on jenkins agent
> 2.32: removing stopped containers on jenkins

- Jenkinsfile-publish-image
- dhis-2/dhis-e2e-test/Dockerfile
- Removed stopped containers to avoid dangling images not being cleaned up;
- Optimized e2e image tiny bit to save more space on jenkins agent
> 2.31:removing stopped containers on jenkins

- Jenkinsfile-publish-image
- dhis-2/dhis-e2e-test/Dockerfile
- Removed stopped containers to avoid dangling images not being cleaned up;
- Optimized e2e image tiny bit to save more space on jenkins agent
> 2.30: removing stopped containers on jenkins

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/StreamingJsonDataValueSet.java
- DHIS2-7023
(cherry picked from commit c802b06720170cec164cda93d9903613b3dbe141)
> [2.32] Improve Jackson JSON streaming performance (#3575)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/StreamingJsonDataValueSet.java
- DHIS2-7023
(cherry picked from commit c802b06720170cec164cda93d9903613b3dbe141)
> [2.29] Improve Jackson JSON streaming performance (#3575)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/StreamingJsonDataValueSet.java
- DHIS2-7023
(cherry picked from commit c802b06720170cec164cda93d9903613b3dbe141)
> [2.31] Improve Jackson JSON streaming performance (#3575)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/StreamingJsonDataValueSet.java
- DHIS2-7023
(cherry picked from commit c802b06720170cec164cda93d9903613b3dbe141)
> [2.30] Improve Jackson JSON streaming performance (#3575)

- Dockerfile
- Jenkinsfile-publish-image
Continuing to fix out of space issues on jenkins: adding unique identifier specific to current build pipeline which will help when removing intermediate image leftovers. As this will be specific to current build, it's safe to remove time filter - docker will not remove intermediate images from other pipelines running at the same time.
> Added additional label to help to clean up intermediate stage

- docker-entrypoint.sh
When the container is restarted (not re-created) it crashes because the WAR file has already been unzipped and removed.  Only try to explode the WAR file if it exists.
Also extract some commonly-used directories and files to variables for easier editing in the future.
> fix: don't try to extract a non-existent zip file

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OrganisationUnitResolutionMode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Added a new param in TrackedEntityInstanceQueryParams named organisationUnitResolution which is used to switch between
A) filtering defined org units based on the Registration org units of tei
B) filtering defined org units based on the Ownership org units of tei + program
> feat: add ou resolution mode when querying teis to either use registration or ownership ou (master)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
https://jira.dhis2.org/browse/DHIS2-7225
- MapView was marked as both Analytic and Embedded object
- Preheat.connectReferences() will skip embedded object
- Preheat.skipConnect() return true if an object implemented EmbeddedObject interface, even if it also implement AnalyticObject. The result is MapView object's references are not connected, hence TransientObjectException is thrown when session is flushed. 
-> Fix: update skipConnect to make it return true if object only implement Embedded interface
> Fix bug TransientObjectException when import MapView

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataImportParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundle.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/DataSetObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/DefaultMetadataSyncService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/version/DefaultMetadataVersionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_all_section_removed.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_removed_section.json
https://jira.dhis2.org/browse/DHIS2-6920
Issue : Removed Section from DataSet from central instance and do metadata sync doesn't trigger delete that section in child instance because metadata sync service currently doesn't support deletion
Fix:
- Add a parameter  isMetadataSyncImport
- In DataSetObjectBundleHook, manually scan for removed Section and delete it in preUpdate. This will only apply if isMetadataSyncImport=true
- Set isMetadataSyncImport = true when importMetadata is called from metadataSyncService.
- In method for saving new metadata snapshot, add fields=:all so that DataSet's section list is included in export DataSet and saved to the metadata version snapshot ( by default only fields owner is exported ). This is for scanning deleted section when importing to child instance …
> Fix bug metadata sync deleted DataSet Section

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
A unit test using Powermock was aggressively mocking `javax.management.*` classes. Added an ignore clause to the unit test to fix that.
> fix: test not passing because of invalid Powermock linkage

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/AggregateAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultAggregateAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/ImportConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/MetaDataCaches.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/MetaDataCallables.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/utils/InputUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/CategoryOptionComboCallable.java
- DHIS-1534
- Refactored DefaultCompleteDataRegistrationExchangeService for simplifying
testing
- Add new method to fetch `CategoryOptionCombo` from `CategoryService`
(cherry picked from commit 8fc69300a11d1967f0bade5eb63c192e0dcc5012)
> [2.33] fix: Detect missing persmission for AttributeOption on DataSet submit

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/AggregateAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultAggregateAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/ImportConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/MetaDataCaches.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/MetaDataCallables.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/utils/InputUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/CategoryOptionComboCallable.java
- DHIS-1534
- Refactored DefaultCompleteDataRegistrationExchangeService for simplifying
testing
- Add new method to fetch `CategoryOptionCombo` from `CategoryService`
(cherry picked from commit 8fc69300a11d1967f0bade5eb63c192e0dcc5012)
> [2.31] fix: Detect missing persmission for AttributeOption on DataSet submit

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
> (2.33) Add username and password validation with http post

- dhis-2/pom.xml
Bumped cache2k to latest version to avoid stacktrace at application
startup (bug fixed in 1.2.4)
https://github.com/cache2k/cache2k/issues/130
> add: bump cache2k version to 1.2.4

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
This PR modifies the sql/hql when querying teis with specific org units specified. 
1. If program is specified, teis are filtered based on program owner OUs.
2. If program is not specified, teis are filtered based on the registration OUs
> fix: use program owner OU instead of registration ou when querying teis (master)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
> (2.32) Add username and password validation with http post

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
> (2.31) Add username and password validation with http post

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
> (2.30) Add username and password validation with http post

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
> (2.29) Add username and password validation with http post

- dhis-2/pom.xml
Bumped cache2k to latest version to avoid stacktrace at application
startup (bug fixed in 1.2.4)
https://github.com/cache2k/cache2k/issues/130
(cherry picked from commit 2260effa7172491a5b42594494e904dc9b5f9cd2)
> [2.33] add: bump cache2k version to 1.2.4

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- DHIS2-6885
- Altered INSERT query that populates the Event analytics table to
fetch the OU name when the Data Element is type 'ORGANIZATIONALUNIT', instead
of the OU UID
partial backport from 2.33
> [2.32] Fix OU name not displayed in event report

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- DHIS2-6885
- Altered INSERT query that populates the Event analytics table to
fetch the OU name when the Data Element is type 'ORGANIZATIONALUNIT', instead
of the OU UID
> [2.31] Fix OU name not displayed in event report

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- DHIS2-6885
- Altered INSERT query that populates the Event analytics table to
fetch the OU name when the Data Element is type 'ORGANIZATIONALUNIT', instead
of the OU UID
partial backport from 2.33
> [2.30] Fix OU name not displayed in event report

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/ExpressionResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceBaseTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceIndicatorTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolverTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/hibernate/HibernateCategoryOptionComboStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/category/CategoryOptionComboStoreTest.java
Created component `CategoryOptionGroupResolver` that "explodes" CategoryOptionGroup UID into a list of CategoryOptionCombo:
```
<de>.<cog>
->
<de.coc1> + <de.coc2> + <de.coc3> + ...
```
and replaces the Indicator expression before it is processed by the analytics engine.
Some open questions, mostly around AOC (AttributeOptionCombos)
Also, class naming needs reviewing
> Category Option Groups in indicator expressions

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/JacksonEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
When import multiple TEIs, splits out enrollments/events into its own list so that caches can still be effective.
> [DHIS2-7658] Tracker 1-1-1 performance improvements

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/JacksonEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
When import multiple TEIs, splits out enrollments/events into its own list so that caches can still be effective.
> [DHIS2-7658][2.31] Tracker 1-1-1 performance improvements

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/EnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/JacksonEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
When import multiple TEIs, splits out enrollments/events into its own list so that caches can still be effective.
> [DHIS2-7658][2.32] Tracker 1-1-1 performance improvements

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
Fixing the response result rows to match the same quantity of headers when "includeNumDen"  is set to true and there are no numerator/denominator data.
> fix: DHIS2-7676: Mismatch between headers and rows / analytics API

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/Program.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramStageInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/PreheatServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageInstanceServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JacksonEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/eventdatavalue/DefaultEventDataValueService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/repository/TrackedEntityAttributeRepository.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/repository/TrackedEntityAttributeRepositoryTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/cache/TestCache.java
Original issue: DHIS2-7336
This PR reduces the number of queries required to fetch a "page" of TEIs from ~17000 to ~700. Speed increase is around 75%.
This is the query I have been using for testing - the same query used by Android devices: 
```
/api/trackedEntityInstances?ou=DiszpKrYNg8&ouMode=DESCENDANTS&fields=trackedEntityInstance,created,lastUpdated,orgUnit,trackedEntityType,coordinates,featureType,deleted,attributes%5Battribute,value,created,lastUpdated%5D,relationships%5BtrackedEntityInstanceA,trackedEntityInstanceB,relationship,relationshipName,relationshipType,created,lastUpdated,from%5BtrackedEntityInstance%5BtrackedEntityInstance%5D,enrollment%5Benrollment%5D,event%5Bevent%5D%5D,to%5BtrackedEntityInstance%5BtrackedEntityInstance%5D,enrollment%5Benrollment%5D,event%5Bevent%5D%5D, …
```
> perf: reduced queries from ~17000 to 700 when fetching TEIs

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryUtilsTest.java
Fix to avoid NullPointer exception when no compatible parser is found for the respective filtering value/type. Throwing an exception instead of returning null.
> fix: DHIS2-7611: Metadata filtering causes null pointer exception

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/DateUtilsTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/hibernate/HibernateDataStatisticsStore.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datastatistics/DataStatisticsController.java
The endDate is being formatted to medium format and is losing the hour/time, missing valid result rows when querying the DB.
> fix: DHIS2-7629: DataStatistics doesn't include endDate when getting data

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/aggregate/DataImportTest.java
In jUni5, ignored flag seems to behave the same way as disabled. Using disabled instead.
> Fix: disabling the data import tests

- Dockerfile
- docker-entrypoint.sh
This changes the Tomcat image we use in the second phase of the build to one of the officially supported Tomcat Docker images: https://hub.docker.com/_/tomcat
This makes it easier to just change the line:
```dockerfile
FROM tomcat:8.5.46-jdk8-openjdk-slim as serve
```
This allows us to test e.g. that DHIS2 works on Tomcat 9 quite easily:
```dockerfile
FROM tomcat:9.0.26-jdk8-openjdk-slim as serve
```
⚠️ This does increase the image size to **587 MB** from **372 MB**.
Not sure what optimizations we can do though, I ran a couple of analysis tools on it to catch obvious stuff:
This Debian Slim image:
```
Total Image size: 587 MB
Potential wasted space: 6.8 MB
Image efficiency score: 99 %
```
Existing Alpine based image:
```
Total Image size: 372 MB
Potential wasted space: 1.4 MB
Image …
```
> chore: modify dockerfile to use official tomcat images

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- DHIS2-7157
- In 2.31, DataValues of type OrgUnit are persisted storing the entire
OU UID tree (abcd/efgg/ilmnd/pqrs). For Event Report we need only the
last segment of the "tree" to resolve the OU name during analytics table
population.
> [2.31] fix: display org unit in Event Report for OU DataValue

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/appstore/DefaultAppStoreService.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
We are dropping the `appstore.api.version` due to that the version cannot be controlled for all end-points through a single version. Instead, it is up to the consumer of the end-point to decide.
Even though we are adding versioned end-points to the app store, we need to stay backwards compatible with the existing app store API, so we are going to alias the unversioned `/apps` end-point to `/v1/apps`, this means we can drop the ugly checks in the core too.
> refactor(app store api): use versioned end-point from code, drop config property

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExpressionController.java
This is a 2.32-only problem. In 2.31 and prior, the endpoint GET api/expressions/description allowed all predictor functions as valid. In 2.33 and following, there are separate endpoints for indicators, validation rules, and predictors, and these endpoints are used by the front end.
In 2.32 this endpoint had been disallowing predictor functions. This patch brings it in line with previous versions of this endpoint, and recognizes predictor functions as valid.
> fix: DHIS2-7744 Fix parsing error on predictor expressions

- Jenkinsfile-publish-image
- dhis-2/dhis-e2e-test/docker-compose.e2e.yml
- dhis-2/dhis-e2e-test/docker-compose.yml
- docker/shared/wait-for-it.sh
- docker/tomcat-alpine/Dockerfile
- docker/tomcat-alpine/docker-entrypoint.sh
- docker/tomcat-debian/Dockerfile
- docker/tomcat-debian/docker-entrypoint.sh
This fixes the race condition issue we have been having on CI when db is not ready by the time web starts. 
- Introduces WAIT_FOR_DB_CONTAINER enviroment variable. 
- Reorganisies dockerfile a bit to use the cache in the better way: changes in scripts should not invalidate all the other docker layers. 
NOTE: this fixes the immediate problem, but is not ideal. I will introduce the timeout and possible extensions to the wait_for_db_container variable later
> ci:wait for db before starting web

- Dockerfile
- dhis-2/dhis-e2e-test/docker-compose.e2e.yml
- dhis-2/dhis-e2e-test/docker-compose.yml
- docker-entrypoint.sh
- docker/shared/wait-for-it.sh
backport of #4073 and includes securing docker image.
> ci:wait-for-db-before-starting-web (v32) 

- dhis-2/pom.xml
spring-security-oauth 2 2.3.7.RELEASE has a bug that prevents custom
UserCredential classes to be deserialized: [commit](https://github.com/spring-projects/spring-security-oauth/commit/b214a25fdd8eae34c8ad803e7022fd17d1c63eb6#diff-28d3f6d7939c6931299a5d3c5e632d58)
The change was actually reverted
([commit](https://github.com/spring-projects/spring-security-oauth/commit/e7c2b970000ebd298d8ad15c5347c2e8c00bad2e#diff-28d3f6d7939c6931299a5d3c5e632d58))
but has not made it into a spring-security-oauth release yet.
> Revert spring-security-oauth2 to 2.3.6.RELEASE version

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- DHIS2-7189
- When rendering `/api/33/organisationUnits.geojson` the system tries
to serialize to JSON the Geometry "Feature Type" object without declaring a serializer.
This throws an exception. The fix is simply to serialize the name of the
Feature Type name, rather than the entire object
> [2.33] fix: renders Geometry FEATURE TYPE as String

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- DHIS2-7189
- When rendering `/api/33/organisationUnits.geojson` the system tries
to serialize to JSON the Geometry "Feature Type" object without declaring a serializer.
This throws an exception. The fix is simply to serialize the nam
> [2.32] fix: renders Geometry FEATURE TYPE as String

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/Program.java
- DHIS2-7789
- Changed `equals` and `hashCode` on DataElement to only check the
"business key" for equality, and using the getId method to trigger the
proxy bypassing
> [2.33] fix: Invalid equals result on DataElement class

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Before this change, when we disabled a user in the user admin, an already logged in user would still be "active/usable" until the session expired.
Now, when we disable a user via the user admin we retrieve the users's active session from the "SessionRegistry" and expire them.
Issue: [DHIS2-7358]
> fix: Expire a user's active session when disabled

- dhis-2/dhis-services/dhis-service-analytics/pom.xml
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/NestedIndicatorCyclicDependencyInspector.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/ExpressionResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceIndicatorTest.java
- dhis-2/pom.xml
- DHIS2-6901
- Introduced Tree structure to represent nested indicators,
so that the certain edge cases can be detected
- The cyclic detection algo now traverses the tree of nested indicators,
when a new Indicator is added (e.g. IndA -> IndB -> IndC --> IndA) and
throws an Exception if the newly added indicator is found in the tree.
> fix: Improve cyclic detection algo for nested indicators

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Before this change, when we disabled a user in the user admin, an already logged in user would still be "active/usable" until the session expired.
Now, when we disable a user via the user admin we retrieve the users's active session from the "SessionRegistry" and expire them.
Issue: [DHIS2-7358]
(cherry picked from commit 9083a78099303f9b8ed5d3f4fa2884f669012f1d)
> fix: (2.32) Expire a user's active session when disabled

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Before this change, when we disabled a user in the user admin, an already logged in user would still be "active/usable" until the session expired.
Now, when we disable a user via the user admin we retrieve the users's active session from the "SessionRegistry" and expire them.
Issue: [DHIS2-7358]
(cherry picked from commit 9083a78099303f9b8ed5d3f4fa2884f669012f1d)
> fix: (2.33) Expire a user's active session when disabled

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
Before this fix, the ip was used to check if the username was locked due to too many failed login attempts, enabled via the config variable "keyLockMultipleFailedLogins" (default value is false)
This would not work since only username is added to the failed login counter cache when a failed login attempts occur.
Issue: [DHIS2-7861]
> fix: Check if username is locked in 2FA auth

- docker/shared/containers-list.sh
As support for jdk11 has been merged into master, we should have some containers to test with.
> ci: add docker options for jdk11

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
The test DefaultCompleteDataSetRegistrationExchangeServiceTest will not run without use of PowerMockIgnore on "javax.xml.*"
Without this fix running tests results in this error:
"java.lang.IllegalAccessError: Class javax/xml/stream/FactoryFinder(unnamed module 0x00000000C107C170) can not access class jdk/xml/internal/SecuritySupport(module java.xml) because module module java.xml does not export package jdk/xml/internal to module unnamed module 0x00000000C107C170"
Tested on: (Java.net) 11.0.5-open and (AdoptOpenJDK 11.0.4.j9-adpt)
> fix: Fix Powermock issue with JDK11

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
While restoring password if no user is found against provided username then request should be terminated. In other cases request should proceed with password validation.
> fix: Check null reference when restoring password

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
While restoring password if no user is found against provided username then request should be terminated. In other cases request should proceed with password validation.
> fix: [2.31] Check null reference when restoring password

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
While restoring password if no user is found against provided username then request should be terminated. In other cases request should proceed with password validation.
> fix: [2.33] Check null reference when restoring password

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
From [DHIS2-7824](https://jira.dhis2.org/browse/DHIS2-7824):
In the South African IDSR/Malaria Information System test referenced [in the issue], this [pull request] reduces the amount of time spent translating the expression into SQL on a test system from about 80% of total time to about 13% of total time. The number of predictions per minute is increased by a factor of about 4.2. The approximate breakdown of times after the fix is:
Program Indicator SQL queries: 86%
Forming the SQL for PI expressions and filters: 13%
Fetching orgUnits to traverse: 1%
Batch write of predicted values 0.5%
> perf: [DHIS2-7824] Speed predictors with PIs

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/SecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/CustomExceptionMappingAuthenticationFailureHandler.java
Adds a DefaultAuthenticationEventPublisher bean to the security config.
Remove a call to security service for failed login that becomes a duplicate after adding the DefaultAuthenticationEventPublisher, since the failed login is called in the failed login event listener instead.
Issue: DHIS2-7915
> fix: Add event publisher, remove registerFailedLogin

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManagerTest.java
Stop counting events related to the categories that users don't have access.
Porting it to 2.31. Was already reviewed and merged into 2.30.
> fix: Event count fix for not allowed categories [DHIS2-7712]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsColumnAsserter.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsTableAsserter.java
- DHIS2-7976
- Specify the `gist` column type when creating indexes for Geometry
columns
> fix: analytics table creation crash on geo columns

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceUserTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole_update.json
https://jira.dhis2.org/browse/DHIS2-7808
This is to fix the case  as described in jira
> we want them to be user managers but not be able to assign user management authorities to other users
Example 
1) User A has User Manager role
1) User A has Role B but doesn't have read access with Role B
2) User A try to update a User C that has role B
3) Role B is removed from User C
The underlying issue is that the Preheat service can't get the UserRole without read access.
So we need to add a method in UserObjectBundleHook to call getNoAcl() and then put that role to preheat map.
> fix: Role is deleted when updating without read access

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/ForwardedIpAwareWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetailsSource.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorWebAuthenticationDetails.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/AuthenticationListener.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
The org.springframework.security.authentication.event.LoggerListener should not be used in production since it leaks Session ID into the logger.
> fix: Add custom authentication logger without sensitive info

- docker/build-containers.sh
ONLY_DEFAULT=1 ./docker/build-containers.sh <image> <identifier>
The above would result in only the default core image with tomcat being built,
which is handy in local testing situations where you only need to build a single
image, and want to avoid the storage overhead of building all Tomcat images we
provide.
---
`./docker/build-containers.sh core:local localident` would run:
- build_default_container
- build_debian_containers
- build_alpine_containers
`ONLY_DEFAULT=1 ./docker/build-containers.sh core:local localident` would run:
- build_default_container
> ci(docker): add escape hatch to only build default container

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DefaultDeletionManager.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DeletionInterceptor.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DeletionManager.java
https://jira.dhis2.org/browse/DHIS2-7256
I had a different fix for 2.34 and 2.33  ( https://github.com/dhis2/dhis2-core/pull/3796 ) but it can't be backported due to utilisation of https://github.com/dhis2/dhis2-core/pull/3547
So this is to fix same issue for 2.32 and older versions
> fix: (2.32) transactionRollback for addAndPruneOptionCombos()

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/AnalyticsJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/EventProgramsDataSynchronizationJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/MetadataSyncJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/PredictorJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/SmsJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/TrackerProgramsDataSynchronizationJobParameters.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/jobs/DataIntegrityJob.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/leader/election/LeaderElectionJob.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/leader/election/LeaderRenewalJob.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sms/scheduling/SendScheduledMessageJob.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/scheduling/AnalyticsTableJob.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/scheduling/ResourceTableJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceCleanUpJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/ImageResizingJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RemoveExpiredReservedValuesJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/job/SendSmsJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/jobs/MetadataSyncJob.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DataSynchronizationJob.java
- Uses @Component annotation for all jobs.
- Using specific value for all component annotations.
- Removes prototype scope from ResourceTableJob.
> fix: Consistent bean annotations for jobs

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/servlet/filter/RequestIdentifierFilterTest.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/WEB-INF/classes/log4j.properties
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/HttpRedirectFilter.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/RequestIdentifierFilter.java
- dhis-2/dhis-web/dhis-web-portal/src/main/webapp/WEB-INF/web.xml
Logs an hashed version of the Session Id as part of a log entry.
The Session Id is placed into the log4J MDC framework (based on thread
local) and passed to the logs.
This feature is *disabled* by default. To enable set:
`monitoring.requestidlog.enabled = on` in DHIS2 configuration.
Additional parameters:
`monitoring.requestidlog.hash` : controls the default hash algorithm
(defaultL SHA-256)
`monitoring.requestidlog.maxsize`: controls the max size of the request
id (default: no max size)
> feat: Log sessionid in log4j logs [DHIS2-7963]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/ForwardedIpAwareWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetailsSource.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorWebAuthenticationDetails.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/AuthenticationListener.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
The org.springframework.security.authentication.event.LoggerListener should not be used in production since it leaks raw session ids in the logger.
The spring LoggerListener is replaced by a new custom listener, this new listener hashes the session id to prevent it from leaking into the logs.
To also be able to log auth events from http basic, the http-basic config in security.xml is extended with a new AuthenticationDetails object that capture the x-forwarded-for header if present.
(cherry picked from commit 00b7ce04d19bf8adbed780aad5dd851f520fd510)
> fix: (2.33) Add custom authentication logger without sensitive info

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/ForwardedIpAwareWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetailsSource.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorWebAuthenticationDetails.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/AuthenticationListener.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
The org.springframework.security.authentication.event.LoggerListener should not be used in production since it leaks raw session ids in the logger.
The spring LoggerListener is replaced by a new custom listener, this new listener hashes the session id to prevent it from leaking into the logs.
To also be able to log auth events from http basic, the http-basic config in security.xml is extended with a new AuthenticationDetails object that capture the x-forwarded-for header if present.
2.32 & 2.31 Also need some changes to the WebTestConfiguration.java
(cherry picked from commit 00b7ce04d19bf8adbed780aad5dd851f520fd510)
> fix: (2.32) Add custom authentication logger without sensitive info

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/ForwardedIpAwareWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetails.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/basic/HttpBasicWebAuthenticationDetailsSource.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorWebAuthenticationDetails.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/AuthenticationListener.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
The org.springframework.security.authentication.event.LoggerListener should not be used in production since it leaks raw session ids in the logger.
The spring LoggerListener is replaced by a new custom listener, this new listener hashes the session id to prevent it from leaking into the logs.
To also be able to log auth events from http basic, the http-basic config in security.xml is extended with a new AuthenticationDetails object that capture the x-forwarded-for header if present.
2.32 & 2.31 Also need some changes to the WebTestConfiguration.java
(cherry picked from commit 00b7ce04d19bf8adbed780aad5dd851f520fd510)
> fix: (2.31) Add custom authentication logger without sensitive info

- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/ValidationRuleExtended.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/Validator.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/DataValidationTaskTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceTest.java
DHIS-7966
This fix prevents a Validation Rule to run on data which is related to a
OU that is not selected by the user.
Without this fix, the rules are executed on incorrect data, which cause
the test expression to always return false.
> fix: prevent too many Validation Rules errors

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationTestBase.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationTestData.java
Introduced annotation `IntegrationTestData` that can be used on
Docker-based integration tests to inject SQL into the Dockerized
database prior to start executing the test class.
> feat: Inject data into db from integration tests

- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
Fixes broken security.xml configuration, ie. referencing a non defined bean.
Missing bean config for "HttpBasicWebAuthenticationDetailsSource" is now defined in security.xml
> fix: Fix broken security.xml config

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/EventQueryParamsTest.java
- DHIS2-7552
- When validating the `orgUnitField` value the system now takes in
consideration the event that a Program may be `null` and therefore checks for
Program Indicators. If the `EventQueryParams` object contains Program Indicators,
the system runs the same validation against all the Programs associated
to the Program Indicators. If at least one fails, the entire validation
fails.
> fix: Use Program Indicators to validate orgUnitField

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataAnalysisController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/ValidationResultView.java
To provide the OrganisationUnitPath property in the resulting ValidationResult payload in order to identify two organisation units with same name.
> fix: Add organisationUnit path in validation result

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/QueryPlannerUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultQueryPlannerGroupByAggregationTypeTest.java
- DHIS2-7797
- This fix allows the Analytics Engine to retain the original datatype
of the selected Data Element when this Data Element is used as a
filter. If more than one Data Element is placed in the filter, than the
Data Type can no longer be retained, since multiple Data Element may have
multiple Data Types
> feat: Single data element as filter retains aggregation type

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
While reviewing [PR 4647](https://github.com/dhis2/dhis2-core/pull/4647) I realized that there isn't a test to insure that program indicators D2 functions aren't removed from the grammar file, so this test checks for their presence.
@zubaira I'm not sure the functions d2:minValue and d2:maxValue are returning the correct SQL in all cases -- please check the results in the test to see if they are what you would expect. (I made these tests check for the results currently returned. If they are wrong, both the code and the test will need to be changed in a subsequent PR.)
> test: Add ProgramIndicatorServiceD2FunctionTest

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostLoadAuditListener.java
- The annotation was causing hibernate to trigger "SET SESSION
CHARACTERISTICS" thousands of times for each api call
> fix: removed @Transactional annotation from listener

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultQueryPlannerGroupByAggregationTypeTest.java
- DHIS2-7797
- This change allows an Analytics query to retain the aggregation type
when multiple Data Elements having the same data type and aggregation
type are used as **query filters**.
If the filter Data Elements have **different aggregation types** or **different data
values**, then the system will default to **SUM** aggregation type and **NULL** data
type
> feat: Analytics handles multiple filter Data Elems

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/audit/Audit.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-services/dhis-service-audit-consumer/src/main/java/org/hisp/dhis/audit/legacy/MetadataAuditConsumer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/DefaultSystemService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/MetadataAudit.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-support/dhis-support-artemis/pom.xml
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/Audit.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditManager.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditableEntity.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrix.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrixConfigurer.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/AuditObjectFactory.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostDeleteAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostInsertAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostLoadAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostUpdateAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/test/org/hisp/dhis/artemis/audit/configuration/AuditMatrixConfigurerTest.java
- dhis-2/dhis-support/dhis-support-audit/src/main/java/org/hisp/dhis/audit/JdbcAuditRepository.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- DHIS2-8122
- Created `AuditMatrix` class to control Auditing message publishing based on simple rules (Audit category and Audit action - READ, WRITE, etc)
- `AuditMatrix` is configured by setting specific properties on `dhis.conf`
- Serialization of Auditable entities now takes place in the `AuditManager`, to prevent costly early serialization
> feat: Audit Matrix to control auditing

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/QueryPlannerUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultQueryPlannerGroupByAggregationTypeTest.java
- DHIS2-7797
- This change allows an Analytics query to retain the aggregation type
when multiple Data Elements having the same data type and aggregation
type are used as query filters.
If the filter Data Elements have different aggregation types or different data
values, then the system will default to SUM aggregation type and NULL data
type
> [2.33] feat: Single data element as filter retains aggregation type

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/QueryPlannerUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultQueryPlannerGroupByAggregationTypeTest.java
- DHIS2-7797
- This change allows an Analytics query to retain the aggregation type
when multiple Data Elements having the same data type and aggregation
type are used as query filters.
If the filter Data Elements have different aggregation types or different data
values, then the system will default to SUM aggregation type and NULL data
type
> [2.32] feat: Single data element as filter retains aggregation type

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/QueryPlannerUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultQueryPlannerGroupByAggregationTypeTest.java
- DHIS2-7797
- This change allows an Analytics query to retain the aggregation type
when multiple Data Elements having the same data type and aggregation
type are used as query filters.
If the filter Data Elements have different aggregation types or different data
values, then the system will default to SUM aggregation type and NULL data
type
> [2.31] feat: Single data element as filter retains aggregation type

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/hibernate/HibernateCategoryOptionComboStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/interpretation/hibernate/HibernateInterpretationStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/hibernate/HibernateOrganisationUnitStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java
Use generics in Query declarations, which essentially centralizes the casting to `getQuery` method.
> chore: Use generics in query declarations

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java
- Use an Enum instead of hardcoded value
DHIS2-8160
> fix: (2.33) Use correct URL for completeness sync

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserTest.java
Two things were fixed in this PR:
1. Redirect was removed from the api after changing password, now resulting in a 202 (As before) status code instead of 302. The test now checks for 202 from 302.
2. Validation would return a different error message than expected. This was due to the assertions relying on the order of when validations are triggered. Assertions now have strings that should only trigger the specific validation error expected.
> fix: UserTest change password issues

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/relationship/JacksonRelationshipServiceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/BeanRandomizer.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/GeometryRandomizer.java
- DHIS2-8137
- Improves the validation check executed when adding a new relationship,
by checking the existence of a Relationship by from, to and type
This fixes the problem of checking for an existing relationship when adding a new Relationship.
Note that this fix applies to the UI (Tracker capture app) and the `POST api/relationships/` API.
When an existing relationship is detected in the Tracker Capture App, a pop-up with "unknown error" is displayed to the user. See screeshot:
> fix: Check if relationship exists on import

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
https://jira.dhis2.org/browse/DHIS2-8205
Issue: current validation of Option's name and code also check on updating same entity
Fix: skip the duplication check if the importing Option uid = checking option uid
> fix: Option validation fail on update

- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
Tests started failing today because of a static date assignment.
> fix: ContextUtilTest to use dynamic date assignment

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsColumnAsserter.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsTableAsserter.java
Specify the "gist" column type when creating indexes for Geometry.
> fix: Fix analytics table creation crash on geo columns

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorReport.java
Adds `errorProperties` field to ErrorReport, contains all parameters to error message.
> feat: Add 'errorProperties' to ErrorReport

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
FYI, this bug was caused by the fix to "DHIS2-8033 Round to Long when decimals is set to zero", because a Number is now being returned to Predictors instead of Double. I intend to fix validation rules as well.
Cheers,
Jim
> fix: DHIS2-8223 predictor run fail

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
Due to some earlier refactor of Enrollment processing, notification related to TEI enrollment stopped working. Fixed it by calling notification service in AbstractEnrollmentService.
> fix: Fix enrollment notifications

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
https://jira.dhis2.org/browse/DHIS2-7417
the code throws NullPointerException as below 
`java.lang.NullPointerException
at org.hisp.dhis.trackedentity.TrackedEntityAttribute.isValidOptionValue(TrackedEntityAttribute.java:181)
at org.hisp.dhis.trackedentity.DefaultTrackedEntityAttributeService.validateValueType(DefaultTrackedEntityAttributeService.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
at …
> fix: NPE in TrackedEntityAttribute validator

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/AggregateDataSetSMSListener.java
This PR is to ensure that when the server processes aggregate dataset submissions, if the completion status is set to not complete, it should unset any existing completion.
Fixes: https://jira.dhis2.org/browse/DHIS2-8224
> fix: ensure datasets are uncompleted in aggregate sms

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/log/Log4JLogConfigInitializer.java
Correct a typo in the package name that prevented log statements for
the syncronization process to be logged to the .dhis/logs file
Also changed addictivity to allow sync log statements to be visible in
console too
> fix: correct typo in package name used by logger

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/config/WebConfig.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/config/WebMvcMetricsConfig.java
- dhis-2/dhis-web/dhis-web-api/src/main/resources/META-INF/dhis/servlet.xml
- dhis-2/pom.xml
- DHIS2-8321
- Move the custom negotiation strategies from servlet.xml to Java Web
configuration so that `HandlerMappingIntrospector` can access DHIS2
`CustomRequestMappingHandlerMapping` and allows WebMetricsFilter to work with the custom mapping handler
- Bumped micrometer lib version to latest
> fix: Servlet config change to allow API monitoring

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
Added a warn log statement when recovery attempt is denied due to rate limiting.
[DHIS2-7406]
> fix: Rate limiting of user account recovery

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceIndicatorTest.java
@larshelge @jimgrace 
This [issue](https://jira.dhis2.org/browse/DHIS2-7862) is about allowing Indicators with static or constant values to "survive" the step in which we resolve the `DimensionalItemObject` from the query - when the "static values" indicators **are the only data dimension in the query**. 
Since an Indicator with static/constant values does not resolve to any `DimensionalItemObject`, the system exits without returning any data.
I have applied a **VERY SIMPLE** fix, which assumes that, if we have one or more Indicators in the query, the Indicators must be "correct" when it comes to numerator/denumerator. I'm not 100% sure about this solution, so please take a look.
> fix: Allow "unresolved" Indicators to survive validation

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ChartSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ReportTableSchemaDescriptor.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/commons/action/GetSystemAuthoritiesAction.java
This is required in order to avoid returning deprecate Authorization keys to the client/UI.
As the schemas are tight to other features and we still want to support the Chart and ReportTable endpoints, I cannot exclude the related schemas.
As the Authorization keys are build dynamically based on existing schemas I had to add a workaround to skip them.
> fix: Removing deprecated Chart/RT schemas [DHIS2-8148]

- dhis-2/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> fix: Use HTTPS to resolve dependencies in Maven Build

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/AbstractPropertyIntrospectorService.java
This was discovered when I tried to fix the issue https://jira.dhis2.org/browse/DHIS2-8308
> fix: Use correct minValue for PropertyIntrospectorService

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManagerTest.java
Inverting the logic so left not authorized category options are filtered out during the SQL query.
> fix: Remove non-authorized cat options from query [DHIS2-7712]

- dhis-2/dhis-web/dhis-web-apps/README.md
- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
- dhis-2/dhis-web/dhis-web-apps/scripts/write-struts-xml.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/cacheManifest.vm
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/main.vm
Fixes TECH-267.
https://jira.dhis2.org/browse/TECH-267
Needs testing, might break some Struts apps that implicitly depend on this legacy injection mechanism.
> refactor(core-resource): remove core resource app from bundle

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/SchemaToDataFetcher.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/DummyDataElement.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/SchemaToDataFetcherTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/CreationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DeletionCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DuplicateIdsCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MandatoryAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SchemaCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniqueAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniquenessCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UpdateCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationFactory.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationHooksCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceUserTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DummyCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationFactoryTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
This refactor is "born" out of an issue discovered with Pepfar db.
The `PreheatService` has a bug which causes an entire table to be loaded in memory (via Hibernate) in order to check for uniqueness.
This is the code that generates the query:
`DefaultPreheatService:242` (2.33)
```
for ( Class<? extends IdentifiableObject> klass : klasses )
{
Query query = Query.from( schemaService.getDynamicSchema( klass ) );
query.setUser( preheat.getUser() );
List<? extends IdentifiableObject> objects = queryService.query( query ); // monster query!
if ( !objects.isEmpty() )
{
uniqueCollectionMap.put( klass, new ArrayList<>( objects ) );
}
}
```
This code preloads in memory all the values of a given class/table and pass it to the validation service.
--
In this PR, I have refactored the Validation …
> 2.33 pepfar bug validation refactor

- .github/workflows/analyse-pr.yml
- .github/workflows/run-tests.yml
When new commits are pushed to the branch, the workflows are triggered again, but the old ones are still running. This PR adds additional action which will cancel running workflows before new ones are triggered.
> ci: Clean up runs

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/pom.xml
Bump spring to 5.2.4.RELEASE, and spring-security to 5.2.2.RELEASE
> chore: Bumps spring / spring-security to latest versions

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/SchemaToDataFetcher.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/DummyDataElement.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/SchemaToDataFetcherTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/CreationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DeletionCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DuplicateIdsCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MandatoryAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SchemaCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniqueAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniquenessCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UpdateCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationFactory.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationHooksCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DummyCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationFactoryTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
- DHIS2-8267
- Introduce new component that fetches only unique attributes for a
Metadata object during Metadata import pre-heat (instead of executing
something like "select * from table" now the system executes "select
column_a, column_c from table".
- Force the query to be read-only to prevent Hibernate to syncronize the
data with the database
- Refactored Metadata import validation into Validation Rules, in order
to improve testability and "code-cleaness"
- "forward-port" from 2.33 c346476902b87567ae335875745c933c2ace61c7
> fix: fetch unique values during metadata import

- dhis-2/license-header.txt
- dhis-2/pom.xml
- TECH-305
- Introducing "speedy-spotless" to automatically format Java code upon
commit (see doc:
https://docs.google.com/document/d/1kOKCSmm3vXyHKkO6mllvvdYlBK793WHG6OGWEASfHe8/edit)
- from the root dhis2 directory, execute
`mvn speedy-spotless:install-hooks`
This will install the pre-commit hook that invoke Spotless only on
modified Java files
> style: automatic code formatting on commit

- dhis-2/dhis-support/dhis-support-artemis/pom.xml
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrixConfigurer.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrixConfigurerTest.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/AnnotationUtilsTest.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/NestedTestImplementation.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/TestImplementation.java
- DHIS2-8416
- Auto-configure the Auditing sub-system to audit Tracker, Metadata and
Aggregate for CREATE, UPDATE and DELETE actions.
Configuration can be over-ridden by user.
> [2.34] fix: enable default auditing scopes

- dhis-2/dhis-support/dhis-support-artemis/pom.xml
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrixConfigurer.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrixConfigurerTest.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/AnnotationUtilsTest.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/NestedTestImplementation.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/TestImplementation.java
- DHIS2-8416
- Auto-configure the Auditing sub-system to audit Tracker, Metadata and
Aggregate for CREATE, UPDATE and DELETE actions.
Configuration can be over-ridden by user.
> fix: enable default auditing scopes

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/SchemaToDataFetcher.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/DummyDataElement.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/preheat/SchemaToDataFetcherTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/CreationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DeletionCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DuplicateIdsCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MandatoryAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SchemaCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniqueAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniquenessCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UpdateCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationFactory.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationHooksCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DummyCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationFactoryTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
- DHIS2-8267
- Introduce new component that fetches only unique attributes for a
Metadata object during Metadata import pre-heat (instead of executing
something like "select * from table" now the system executes "select
column_a, column_c from table".
- Force the query to be read-only to prevent Hibernate to syncronize the
data with the database
- Refactored Metadata import validation into Validation Rules, in order
to improve testability and "code-cleaness"
- "forward-port" from 2.33 c346476902b87567ae335875745c933c2ace61c7
> [2.34] fix: fetch unique values during metadata import

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
This PR basically fixes/changes 2 behaviours when using the tei/query endpoint
1. Attribute param was ignored when "minimum search attributes" check was performed. Only filters were considered. This has been changed so that both are considered when counting for minimum search attributes.
2. If attributes were specified in the request, only those attributes were part of the response. This has been changed so that, no matter what the attributes present in the request, all the attributes (either program attributes or tet attributes) will be returned in the response.
> fix: attribute param ignored for minSearchAttributes check (2.34)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramInstance.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditProducerSupplier.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditScheduler.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- made sure we only log basic info about the audited entity (instead of the full payload)
- fix possible NPE in `ProgramStageInstance` `toString` method
- disabled in-memory queue for auditing as default, has to be explicitely enabled
> fix: stop debug of full entity in auditing

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramInstance.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditProducerSupplier.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditScheduler.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- made sure we only log basic info about the audited entity (instead of the full payload)
- fix possible NPE in `ProgramStageInstance` `toString` method
- disabled in-memory queue for auditing as default, has to be explicitely enabled
(cherry picked from commit 5aaac6a5e153f49b425c32633e497476b9e32af8)
> [2.34] fix: stop debug of full entity in auditing

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/EventQueryParamsTest.java
* fix: use Prg. Indicators to validate orgUnitField
- DHIS2-7552
- When validating the orgUnitField value the system now takes in
consideration the event that a Program may be null and also checks for
Program Indicators. If the EventQueryParams contains Program Indicators,
the system runs the same validation against all the Programs associated
to the Program Indicators. If at least one fails, the entire validation
fails.
* chore: minor refactoring
* Update EventQueryParams.java
Co-authored-by: Lars Helge Øverland <lars@dhis2.org>
> [2.33] fix: Use Program Indicators to validate orgUnitField (#4673)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/EventQueryParamsTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
* fix: use Prg. Indicators to validate orgUnitField
- DHIS2-7552
- When validating the orgUnitField value the system now takes in
consideration the event that a Program may be null and also checks for
Program Indicators. If the EventQueryParams contains Program Indicators,
the system runs the same validation against all the Programs associated
to the Program Indicators. If at least one fails, the entire validation
fails.
* chore: minor refactoring
* Update EventQueryParams.java
Co-authored-by: Lars Helge Øverland <lars@dhis2.org>
> [2.32] fix: Use Program Indicators to validate orgUnitField 

- dhis-2/pom.xml
Due to maven compiler config issues, all compilation on Java 9+ JDKs fails.
The fix is described here: https://bugs.openjdk.java.net/browse/JDK-8212636
Added a new profile with activation by having jdk9+ to support both Java 8 and Java 9
Issue: [DHIS2-8468]
> fix: Hibernate Support fails to compile on Java 9+

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Criteria.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Pagination.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/PaginationData.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/QueryPlan.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/DefaultQueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/planner/DefaultQueryPlannerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DimensionController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramDataElementController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapViewController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FormUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
This PR:
- propagates pagination information to the `DefaultQueryService` so that it can only fetch paginated data (from .. to)
- checks if all the `filter` attributes are "persisted" fields and skip the in-memory query
- unit tests
> [2.31] Avoid "SELECT * FROM TABLE" when fetching metadata

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Pagination.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/QueryPlan.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/DefaultQueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/planner/DefaultQueryPlannerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DimensionController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramDataElementController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapViewController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FormUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- propagates pagination information to the DefaultQueryService so that it can only fetch paginated data (from .. to)
- checks if all the filter attributes are "persisted" fields and skip the in-memory query
- unit tests
forward-port from: c1b7279c49889a82c61437f234e9737902d58bdc
> fix: Use db-pagination when fetching metadata

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Pagination.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/QueryPlan.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/DefaultQueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/planner/DefaultQueryPlannerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DimensionController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramDataElementController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapViewController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FormUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- propagates pagination information to the DefaultQueryService so that it can only fetch paginated data (from .. to)
- checks if all the filter attributes are "persisted" fields and skip the in-memory query
- unit tests
forward-port from: c1b7279c49889a82c61437f234e9737902d58bdc
> [2.34] fix: use db-pagination when fetching metadata

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Pagination.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/QueryPlan.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/DefaultQueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/planner/DefaultQueryPlannerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DimensionController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramDataElementController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapViewController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FormUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- propagates pagination information to the DefaultQueryService so that it can only fetch paginated data (from .. to)
- checks if all the filter attributes are "persisted" fields and skip the in-memory query
- unit tests
forward-port from: c1b7279c49889a82c61437f234e9737902d58bdc
> [2.33] fix: use db-pagination when fetching metadata

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Pagination.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/QueryPlan.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/DefaultQueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/QueryServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/planner/DefaultQueryPlannerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DimensionController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramDataElementController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapViewController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FormUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- propagates pagination information to the DefaultQueryService so that it can only fetch paginated data (from .. to)
- checks if all the filter attributes are "persisted" fields and skip the in-memory query
- unit tests
forward-port from: c1b7279c49889a82c61437f234e9737902d58bdc
> [2.32] fix: use db-pagination when fetching metadata

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserSettingStore.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/hibernate/HibernateSystemSettingStore.java
Causes exceptions when methods are called as part of larger read-write transactions.
Causes `ERROR cannot execute UPDATE in a read-only transaction` exceptions.
> fix: Remove read-only tx at setting store level

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JacksonEventService.java
Removes costly and unnecessary call to `I18nManager` in event import. Triggered once per event and only used to i18n two dates in the response message.
> fix: Remove costly call to I18nManager in event import

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/WebOptions.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/utils/PaginationUtilsTest.java
* fix: incorrect calculation of firstResult in pagination
(cherry picked from commit 7acf9882fdc5cb77fc5dfc0ea6af18e778328e6f)
> [2.34] fix: incorrect calculation of firstResult in pagination (#5165)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/WebOptions.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/utils/PaginationUtilsTest.java
* fix: incorrect calculation of firstResult in pagination
(cherry picked from commit 7acf9882fdc5cb77fc5dfc0ea6af18e778328e6f)
> [2.31] fix: incorrect calculation of firstResult in pagination (#5165)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/WebOptions.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/utils/PaginationUtilsTest.java
* fix: incorrect calculation of firstResult in pagination
(cherry picked from commit 7acf9882fdc5cb77fc5dfc0ea6af18e778328e6f)
> [2.32] fix: incorrect calculation of firstResult in pagination (#5165)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sqlview/hibernate/HibernateSqlViewStore.java
Changes SQL view querying to read from master database instead of potentially from read replicas.
> fix: Use read-write JDBC template for SQL views

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
> fix: Prevent invalid query when using PI as sort item

- dhis-2/pom.xml
The formatter will force all files in the commit to use LF (UNIX) line ends.
In this way we are trying to avoid to have different files with different line ends.
This will result sometimes in difficult PRs, because the whole file will be changed, but github has the "Hide whitespace changes" option that will ignore line endings.
> chore: Force line ending in committed files to be LF

- dhis-2/DHISFormatter.xml
This setting allows using conditional formatting tags into the code. A conditional formatting prevents the automatic formatter to format blocks of code:
```
// @formatter:off
IN_USER_ORG_UNIT_HIERARCHY_CACHE = cacheProvider.newCacheBuilder( Boolean.class )
.forRegion( "inUserOuHierarchy" )
.expireAfterWrite( 3, TimeUnit.HOURS )
.withInitialCapacity( 1000 )
.forceInMemory()
.withMaximumSize( SystemUtils.isTestRun(env.getActiveProfiles() ) ? 0 : 20000 ).build();
// @formatter:on
```
> chore: add support for conditional format

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
* fix: Prevent invalid query when using PI as sort item
- DHIS2-8542
* chore: style
(cherry picked from commit 59232d19c6ddb4d5ad3af58ab5c5894a930c0446)
> [2.34] fix: Prevent invalid query when using PI as sort item (#5195)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
* fix: Prevent invalid query when using PI as sort item
- DHIS2-8542
* chore: style
(cherry picked from commit 59232d19c6ddb4d5ad3af58ab5c5894a930c0446)
> [2.34.0] fix: Prevent invalid query when using PI as sort item (#5195)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
* fix: Prevent invalid query when using PI as sort item
- DHIS2-8542
* chore: style
(cherry picked from commit 59232d19c6ddb4d5ad3af58ab5c5894a930c0446)
> [2.33] fix: Prevent invalid query when using PI as sort item (#5195)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
* fix: Prevent invalid query when using PI as sort item
- DHIS2-8542
* chore: style
(cherry picked from commit 59232d19c6ddb4d5ad3af58ab5c5894a930c0446)
> [2.32] fix: Prevent invalid query when using PI as sort item (#5195)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceIndicatorTest.java
- DHIS2-7862
- If an analytics query contains Indicators which contain constants or
static values (e.g. 100, 1), do not exit early and continue processing
the indicator expressions.
(cherry picked from commit 6ee1d2f1b21852302f2ea5fd137edbb5978b1767)
> [2.33] fix: analytics: retain unresolved Indicators

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceIndicatorTest.java
- DHIS2-7862
- If an analytics query contains Indicators which contain constants or
static values (e.g. 100, 1), do not exit early and continue processing
the indicator expressions.
(cherry picked from commit 6ee1d2f1b21852302f2ea5fd137edbb5978b1767)
> [2.32] fix: analytics: retain unresolved Indicators

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- DHIS2-7862
- If an analytics query contains Indicators which contain constants or
static values (e.g. 100, 1), do not exit early and continue processing
the indicator expressions.
(cherry picked from commit 6ee1d2f1b21852302f2ea5fd137edbb5978b1767)
> [2.31] fix: analytics: retain unresolved Indicators

- dhis-2/dhis-web/pom.xml
Upgrade Jetty maven plugin to prevent failure to startup with mvn jetty:run-war
Issue: [DHIS2-8566]
> fix: Upgrade Jetty to prevent startup failure

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryCombo.java
https://jira.dhis2.org/browse/DHIS2-2696
> fix: CategoryCombo w/o Option causes api/dataElementOperands 500

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v35/V2_35_2__Update_data_sync_job_parameters_with_system_setting_value.java
Davids PR was merged after 2.34 (and 2.34.0 patch) branches were branched out. So the flyway version number in the PR https://github.com/dhis2/dhis2-core/pull/4913 , should be updated to 2.35.x (2.35.2 in this case)
> fix: correct flyway version number for 2.35

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserCredentials.java
When using Jackson ObjectMapper directly  we are currently exposing the encrypted password in json/xml, for node serializers we automatically hide this field (property type is set to PASSWORD) so its not a problem when using the web-api etc normally, but since we have started using object mapper for audits this means that the encrypted password is available on the audit topic if any changes happens to a user.
This PR aligns the behavior to that of the node serializer, so that password fields can only be written to, not read from.
> fix: hide encrypted password when using Jackson ObjectMapper

- Jenkinsfile-publish-image
PR introduces matrix within 'Run api tests' stage. Tests will be executed on multiple environments, in parallel: 
- TC8 + JDK 8 (docker image alliesed with default tag)
- TC9 + JDK 11
Note: I tested the pipeline and clean up on Jenkins, but I haven't tested that the logs will be published after both parallel stages finish. Please let me know if you see anything that might go wrong with that.
> ci: Test multiple docker images

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/UidJsonSerializer.java
Backport of #5276, fixes issues with circular user serialization.
Causes crash of several functions as audit is triggered on metadata creation and updates.
> fix: Downcast user to UID when using jsonMapper

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
Adds a null-check before checking the length of a value. The code is checking all te-attributes for program/tet, regardless if a value was supplied or not, so some instances can be null.
> fix: Add null-check before checking value length

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/OptionActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/MetadataPaginationTest.java
- dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Query.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- DHIS2-8754
This fix addresses an issue introduced with this PR: https://github.com/dhis2/dhis2-core/commit/b132f0685b9040f194ee5bb932fc08317e0a6aa8
The `Pager` object requires a "total" value in order to properly calculate the number of pages. The "total" is **now** passed to the `Pager` object and it's calculated by executing a count query using the same filter and sorting criteria used for the original query.
If the Metadata Query engine requires an in-memory query (because a filter or sort field is non-persisted), then the pagination is executed in memory by the Query Engine and no longer in the controller.
> fix: calculate metadata pagination total pages

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/OptionActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/MetadataPaginationTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Query.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- DHIS2-8754
This fix addresses an issue introduced with this PR: b132f06
The `Pager` object requires a "total" value in order to properly calculate the number of pages. The "total" is **now** passed to the `Pager` object and it's calculated by executing a count query using the same filter and sorting criteria used for the original query.
If the Metadata Query engine requires an in-memory query (because a filter or sort field is non-persisted), then the pagination is executed in memory by the Query Engine and no longer in the controller.
* fix: use Restassured assertions
(cherry picked from commit e9c8211)
> [2.33]  fix: Calculates metadata pagination total pages (#5324)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CompressionSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/EnrollmentSMSListenerTest.java
This PR contains two fixes:
1. Ensure the TrackedEntityAttributeValueService is used in the SMS compression listener when processing enrolment submissions. 
2. Ensure all metadata is retrieved when initialising the Compression listener (some types were missing), for use with hashing of UIDs.
> fix: Use TrackedEntityAttributeValueService to update values in SMS submissions

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/RestApiActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/OptionActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/MetadataPaginationTest.java
- dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Query.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- DHIS2-8754
This fix addresses an issue introduced with this PR: b132f06
The `Pager` object requires a "total" value in order to properly calculate the number of pages. The "total" is **now** passed to the `Pager` object and it's calculated by executing a count query using the same filter and sorting criteria used for the original query.
If the Metadata Query engine requires an in-memory query (because a filter or sort field is non-persisted), then the pagination is executed in memory by the Query Engine and no longer in the controller.
* fix: use Restassured assertions
(cherry picked from commit e9c8211)
> [2.34] fix: Calculates metadata pagination total pages 

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/user/UserControllerTest.java
When an admin changes a user's password the user's active sessions should
be expired and the user forced to login again with the new password.
Issue: [DHIS2-8570]
I also took the liberty to refactor the update user method.
The xml and json version was 99.9% like so it was hard to resist not fixing that.
> fix: Expire user's active sessions when password is changed

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/DefaultQueryServiceTest.java
Remove deprecated Hamcrest `argThat` method and replaced with non-deprecated one.
Made inner class static.
> chore: Remove deprecated Hamcrest method from test

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryOptionComboNameResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryOptionComboResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataApprovalMinLevelResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataApprovalRemapLevelResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataElementResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataSetOrganisationUnitCategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitStructureResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/PeriodResourceTable.java
The following resource tables were using "integer" datatype for ids which should be "bigint" datatype from 2.32 onwards.
_categoryoptioncomboname
_categorystructure
_dataelementcategoryoptioncombo
_dataelementgroupsetstructure
_dataelementstructure
_datasetorganisationunitcategory
_dateperiodstructure
_indicatorgroupsetstructure
_organisationunitgroupsetstructure
_orgunitstructure
_periodstructure
__dataapprovalremaplevel
_dataapprovalminlevel
> fix: [DHIS2-8627] resource tables still using integer ids instead of bigint (master)

- Jenkinsfile-publish-image
Problem: jenkins executes 'always' stage before 'failure' stage, so when we try to attach the logs, the containers are already aborted and there are no logs. The solution is to use the 'cleanup' stage instead of 'always', so that containers are stopped after attaching logs.
> ci: fix logs not being attached after pipeline failure

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/d2HasValue.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/antlr4/org/hisp/dhis/parser/expression/antlr/Expression.g4
Previously d2:hasValue only supported DataElements and TrackedEntityAttributes. This change will extend hasValue support to include ProgramVariables so now all three formats are supported.
```
hasValue(#{ProgrmStagA.DataElmentA})
hasValue(A{Attribute0A})
hasValue(V{creation_date})
```
> Fix: (2.33) Extend d2:hasValue support for ANTLR expr

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
It also prevents a possible NPE case the Map element is null
> fix: preventing class cast exception during conversion [DHIS2-8580]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
In the ListGrid the 'headers' had the incorrect length due to the elimination of 'slots' in the rows collection in the Visuzalizaion class. (2.34)
This was causing "IndexOutOfBoundsException" in ListGrid as headers and rows' columns were not in sync.
_Adding an NPE checking for rows, columns and filters as they can be null due to the known issue with Lists and "order_id". This might render an incorrect visual element, in Push Analysis, but will avoid possible HTTP 500 errors._
> fix: Remove code that 'eliminate' headers 'slots' [DHIS2-8681]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
It also prevents a possible NPE case the Map element is null
(cherry picked from commit 6b2c082f13fc7566b4cf0c2e098731637e3ea0e7)
> [2.32] fix: preventing class cast exception during conversion [DHIS2-8580]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
It also prevents a possible NPE case the Map element is null
(cherry picked from commit 6b2c082f13fc7566b4cf0c2e098731637e3ea0e7)
> [2.33] fix: preventing class cast exception during conversion [DHIS2-8580]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
It also prevents a possible NPE case the Map element is null
(cherry picked from commit 6b2c082f13fc7566b4cf0c2e098731637e3ea0e7)
> [2.34] fix: preventing class cast exception during conversion [DHIS2-8580]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
When performing clear cache operation in data administration -> maintenance -> clear system cache, the user installed apps were disappearing. This was because appCache was not write through and clearing it without invoking reloadApps() will cause appList to always be empty. This event listener is now removed.
> fix: [DHIS2-8691] Remove appCache clearing event listener

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
Using spring application event publishers and listeners, we have started clearing certain caches (including appCache in AppManager), which empties the app list until the next reloadApps() is invoked.
> fix: [DHIS2-8691] Clearing cache from maintenance cleares appCache

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
When saving a new Map with a Layer/MapView, we were facing the DB exception.
> fix: Uid was null, causing Postgres constraint exceptions

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
When saving a new Map with a Layer/MapView, we were facing the DB exception (2.34)
> fix: Uid was null, causing Postgres constraint exceptions [DHIS2-8832]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceContentStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/JCloudsFileResourceContentStore.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
Supporting servlet spec 3.0 dependency by changing "setContentLengthLong()" into "setHeader()".
Also changing the order of method invocation. Content length is set before the inputstream is copied into outputstream.
> fix: [DHIS2-8783] Add content length for file downloads supporting 3.0 servlet spec (master 2.35)

- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.menu.ui.js
The endpoint `/api/me/profile.json` does not exist, this should be `/api/me.json`
See [DHIS2-8788](https://jira.dhis2.org/browse/DHIS2-8788) - this should probably be back-ported to 2.34 and 2.33.
Note that these core-embedded javascript libraries should almost certainly be **removed** from the core in 2.35 (see [DHIS2-8859](https://jira.dhis2.org/browse/DHIS2-8859)).
> fix: update call to removed /api/me/profile.json endpoint (DHIS2-8788)

- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrixConfigurerTest.java
Added a unit test to verify that Auditing is disabled when using the "DISABLED" string as value for any of the auditing config keys.
`audit.metadata=DISABLED`
> chore: add unit test for Auditing

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/visualization/ChartImageGenerator.java
This fix is the same done for the issue DHIS2-8590. Not all visualizations have categories
> fix: Workaround to avoid NPE during chart gen [DHIS2-8803]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/visualization/ChartImageGenerator.java
This fix is the same done for the issue DHIS2-8590. Not all visualizations have categories
> fix: Workaround to avoid NPE during chart gen. [DHIS2-8803]

- dhis-2/DHISFormatter.xml
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/config/ProgramRuleConfig.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NewImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/OldImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementerTest.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineTest.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerEventBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerProgramRuleBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/enrollment.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/event_events_and_enrollment.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/event_events_and_enrollment_link.json
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/pom.xml
This is a preliminary refactor needed on the core side when we call rule engine to evaluate program rules. 
The main goal of this PR is to remove all the duplicated code derived by the difference in the call of rule engine when the target of the evaluation is an enrollment or an event.
> refactor: Removing duplication of code in the call of rule engine [DHIS2-7310]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipItem.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/DefaultAuditObjectFactory.java
The Auditing component fails to serialize to Json self-referencing TEIs.
When a TEI (tei A) has a relationship with another TEI (tei B), and tei B
references tei A, the Jackson parser fails with a Stack Overflow Error.
Please note that the StackOverflow exception **DOES NOT block** the operation (saving the TEI): the error stack is printed in the application log and the auditing does not take place.
This fix uses a Jackson annotation on the RelationshipItem class that "forces"
the serialization to only serialize the "simple" information of the linked Tei and
avoid recursion into the "relationship" attribute.
> fix: prevent audit StackOverFlow error with Relationship

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/AggregateDataSetSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/BaseSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CompressionSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DeleteEventSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/RelationshipSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/SMSProcessingException.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/SimpleEventSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/TrackerEventSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/AggregateDataSetSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/CompressionSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/DeleteEventSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/EnrollmentSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/RelationshipSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/SimpleEventSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/TrackerEventSMSListenerTest.java
This PR simply updates all references to the change in the SMS compression library where all acronyms are written as camel case instead of upper case.
This PR needs to wait on two things:
~~1. The reference in the compression library needs to use the dhis2 version, once this PR is merged: https://github.com/dhis2/sms-compression/pull/5~~
2. The previous PR with fixes should be merged first: https://github.com/dhis2/dhis2-core/pull/5347
> Refactor: Rename acronyms to camel case in SMS library 

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/interceptor/I18nInterceptor.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/beans.xml
https://jira.dhis2.org/browse/DHIS2-4086
Spring mvc **TranslationInterceptor** doesn't apply for **Struts actions** such as  **LoadFormAction** used in DataEntry app.
Therefore  db_locale is always null ( getting from **UserContext.getUserSetting**  ) in function **BaseIdentifiableObject.getTranslation()**
So we have to set db locale in Struts interceptor
// ---------------------------------------------------------------------
// Set the current User DB Locale in UserContext
// ---------------------------------------------------------------------
User currentUser = currentUserService.getCurrentUser();
Locale dbLocale = (Locale) userSettingService.getUserSetting( UserSettingKey.DB_LOCALE, currentUser );
UserContext.setUser( currentUser );
UserContext.setUserSetting( …
> fix: Set DB Locale in UserContext for struts I18nInterceptor

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CrudControllerAdvice.java
Removed exception class from Spring exception handler annotation, to avoid error on startup.
> fix: remove class from Spring MVC exception handler

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/RequestIdentifierFilter.java
When a Program of type "WITHOUT REGISTRATION" is created through the
`/program` endopint, two Program Instances are automatically created,
instead of one.
This fix, removes the Program Instance creation from the `ProgramController`
class.
> fix: Remove Program Instance creation from controller

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
When a Program of type "WITHOUT REGISTRATION" is created through the
`/program`` end-point, two Program Instances are automatically created,
instead of one.
This fix, removes the Program Instance creation from the ``ProgramController`
class.
> [2.33] fix: Remove Program Instance creation from controller

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
HibernateIdentifiableObjectStore:getCurrentUser() wrongly uses .getUser()
method on the UserCredentials to retrieve the current user. This is wrong,
this returns the user that created the object. The correct method should
be .getUserInfo()
Issue: [DHIS2-8963]
> fix: Fix wrong use of getCurrentUser()

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/PeriodResourceTable.java
This fix corrects an error during the `_periodstructure` generation process. The process assigns the wrong year to a week Period.
Example: `2019-12-31`
The week of `2019-12-31`, according to the ISO calendar system, belongs to 2020, since 4 or more days of that week fall in 2020.
In order to handle all Weekly Period types uniformly, 3 days are added to a Weekly Period type start date.
Example:
| Weekly Type     | Example Date | Date -> Start Date -> + 3             |
|-----------------|--------------|---------------------------------------|
| Standard        | 2019-12-31   | -> 2019-12-31 +3 = 2020-01-03 = 2020  |
| Weekly Saturday | 2019-12-31   | -> 2019-12-28 + 3 = 2019-12-31 = 2019 |
| Weekly Sunday   | 2019-12-31   | -> 2019-12-29 + 3 = 2020-01-01 = 2020 |
| Weekly Thursday | …
> fix: Invalid weekly period year reference

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
When using the "query" parameter in metadata listing apis, the pagination is incorrect and always returns total count. The "query" parameter flow will now have correct pagination done in memory (not in the db). So there is no performance difference, except that the pagination numbers are now correct.
> fix: [DHIS2-9051] incorrect pagination when using query parameter in metadata list api(2.35)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapView.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/ThematicMapType.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/AnalyticalObjectStoreTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapping/MappingServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/resources/create_map.json
- dhis-2/dhis-services/dhis-service-reporting/src/test/resources/update_map.json
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_8__Add_mapview_thematicmaptype.sql
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
Adds enum `ThematicMapType` and association from `MapView`. Purpose of this enum/field is to distinguish between various thematic map visualization types like choropleth and bubble maps.
> fix: Add thematic map type to map view [DHIS2-9046]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapView.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/AnalyticalObjectStoreTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mapping/MappingServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/resources/create_map.json
- dhis-2/dhis-services/dhis-service-reporting/src/test/resources/update_map.json
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
Adds property `noDataColor` to entity `MapView`. The purpose of this property is to store the color to use for map features which have no corresponding data. The color format is in 7 character hex format.
> fix: Add MapView noDataColor property [DHIS2-9047]

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/AggregateDataSetSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/CompressionSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DeleteEventSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/RelationshipSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/SimpleEventSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/TrackerEventSMSListener.java
This PR includes a fix and refactor:
1. The calls to retrieve all TEI, event, enrolment and relationship UIDs is not made anymore.
2. The requests to get UIDs from SMS submissions is done via public methods.
> fix: reduce metadata calls for SMS

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/PeriodResourceTable.java
* fix: Invalid weekly period year reference
This fix corrects an error during the `_periodstructure` generation process. The process assigns the wrong year to a week Period.
Example: `2019-12-31`
The week of `2019-12-31`, according to the ISO calendar system, belongs to 2020, since 4 or more days of that week fall in 2020.
In order to handle all Weekly Period types uniformly, 3 days are added to a Weekly Period type start date.
Example:
| Weekly Type     | Example Date | Date -> Start Date -> + 3             |
|-----------------|--------------|---------------------------------------|
| Standard        | 2019-12-31   | -> 2019-12-31 +3 = 2020-01-03 = 2020  |
| Weekly Saturday | 2019-12-31   | -> 2019-12-28 + 3 = 2019-12-31 = 2019 |
| Weekly Sunday   | 2019-12-31   | -> 2019-12-29 + 3 = …
> [2.34] fix: Invalid weekly period year reference (#5745)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/PeriodResourceTable.java
* fix: Invalid weekly period year reference
This fix corrects an error during the `_periodstructure` generation process. The process assigns the wrong year to a week Period.
Example: `2019-12-31`
The week of `2019-12-31`, according to the ISO calendar system, belongs to 2020, since 4 or more days of that week fall in 2020.
In order to handle all Weekly Period types uniformly, 3 days are added to a Weekly Period type start date.
Example:
| Weekly Type     | Example Date | Date -> Start Date -> + 3             |
|-----------------|--------------|---------------------------------------|
| Standard        | 2019-12-31   | -> 2019-12-31 +3 = 2020-01-03 = 2020  |
| Weekly Saturday | 2019-12-31   | -> 2019-12-28 + 3 = 2019-12-31 = 2019 |
| Weekly Sunday   | 2019-12-31   | -> 2019-12-29 + 3 = …
> [2.33] fix: Invalid weekly period year reference (#5745)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
When filter values were integers, the values were left unquoted even for "LIKE" operator. An additional if construct is added to handle the LIKE operator cases.
Major refactoring to adhere to sonar quality issues. Changed almost every "sql += " statements into using StringBuilder instead. Had to refactor reused strings as constants.
> fix: [DHIS2-8730] like operator with integer values (2.35)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/PeriodResourceTable.java
* fix: Invalid weekly period year reference
This fix corrects an error during the `_periodstructure` generation process. The process assigns the wrong year to a week Period.
Example: `2019-12-31`
The week of `2019-12-31`, according to the ISO calendar system, belongs to 2020, since 4 or more days of that week fall in 2020.
In order to handle all Weekly Period types uniformly, 3 days are added to a Weekly Period type start date.
Example:
| Weekly Type     | Example Date | Date -> Start Date -> + 3             |
|-----------------|--------------|---------------------------------------|
| Standard        | 2019-12-31   | -> 2019-12-31 +3 = 2020-01-03 = 2020  |
| Weekly Saturday | 2019-12-31   | -> 2019-12-28 + 3 = 2019-12-31 = 2019 |
| Weekly Sunday   | 2019-12-31   | -> 2019-12-29 + 3 = …
> [2.32] fix: Invalid weekly period year reference (#5745)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserCredentialsStore.java
This issue happens because `getIdentifiableObjectStore` method in `DefaultIdentifiableObjectManager` returns `null` for  `UserCredentials` class. This because the `identifiableObjectStores` used in creating the `DefaultIdentifiableObjectManager` does not contain the `HibernateUserCredentialsStore`. 
The fix is to make `HibernateUserCredentialsStore` as sub-class of `HibernateIdentifiableObjectStore`.
> fix: userCredentials API endpoint not returning results [DHIS2-9024]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueService.java
- dhis-2/dhis-support/dhis-support-db-migration/pom.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v33/V2_33_26__Fix_encryption_issue_for_TEI_attributeValues.java
Issue : 
1) The encryption.password that user defined in dhis.conf was not taken by the configuration service. 
2) A default password was defined in the EncryptionConfig class and was used to encrypt TEI attribute values if no password provided.
So in 2.33.4 I have applied a fix so the encryption.password property was taken correctly from dhis.conf
However, for TEI attribute values registered from 2.33.0 to 2.33.3, they are still encrypted using that default password. Hence, the encryption service failed to decrypt those values and those TEI can't be opened on Tracker Capture app.
Fix:  Add a flyway script to reset correct password for those values.
> fix: (2.33) Encryption issue of TEI AttributeValue

- dhis-2/dhis-e2e-test/pom.xml
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/schemas/SchemaProperty.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/utils/DataGenerator.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/extensions/ConfigurationExtension.java
After changing Double.MIN_VALUE to -Double.MAX_VALUE, the API tests started failing with  `Number -Infinity can't be serialized as JSON: infinite are not allowed in JSON.` exception. This change should fix it.
> fix: changes number return type to big decimal

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java
This is a small fix for the pagination issue/missing data for the ReportTables and Charts (Favourites) API's.
> fix: Fixing pagination for RTable and Chart (Favourites) [DHIS2-9139]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
Pagination totalCount for messageConversations listing api was incorrect. The count returned every unread messages rather than the unread messages for the current user. Included the correct pager object into metadata in the overridden "getEntityList" method to fix this.
> fix: [DHIS2-9052] Incorrect unread message count in messageConversations (master)

- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/IdentifiableObjectUtilsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/PeriodOffsetUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsUtilsTest.java
- Fix exception thrown when a `pe` dimension is used as filter; fixed by skipping the new Period Offset logic when the Analytics results Grid does not contain a Period column
- Add a new `.withPeriods` method to `DataQueryParams` builder that preserves dimension name
- Fix logic to extract data from the Grid prior to passing the data to the Expression engine
ref: DHIS2-9152
> fix: Analytics error on period as filter

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
Sometimes `row.get( valueIndex )` returns `long`, so we cannot cast to `Double`. This fix will cast to `Number` and convert to `double` in order to avoid the error.
I also added some null checks, as during my tests I accidentally got an NPE when iterating through some lists. I believe they are related to the known issue related to Hibernate and null elements in Lists.
> fix: Casting to Number to avoid class cast exception [DHIS2-8631]

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/vote/ExternalAccessVoter.java
We have had externalAccess property enabled in hibernate for EventReport and EventChart for a long time, but they have now been properly added to the ExternalAccessVoter, this PR fixes that.
[DHIS2-9121](https://jira.dhis2.org/browse/DHIS2-9121)
> feat: support external access voter for eventReports, eventCharts

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/grid/GridUtilsTest.java
After the introduction of Period Offset (DHIS2-8758), the Indicator data aggregation logic needs to resolve the period
index withing the aggregated Grid. In case of a query that uses ORG UNIT GROUP SET, the resulting Grid contains multiple
dimension items for each row and the period index can shift to 2 or 3 position.
With this fix, a more robust method to identify data and period index is introduced during Indicator grid handling.
ref: DHIS2-9214
> fix: fix Indicator Grid results index resolution

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
An invalid error code was returned when calling the `/events/query` endpoint and try to retrieve a geo coordinate for a non coordinate field.
> fix: use correct error codes for coordinates query

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
When using like comparisons in event filters, pure numeric strings where not encoded properly. Added an extra if condition to handle it.
> fix: [DHIS2-8730] fix event data values 'like' filters when using numeric comparisons (2.35)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/pom.xml
This PR will add support for `completed_date` program environment variable support. Unlike ProgramIndicators this completion date will always be taken as event completed date.
> feat: Update rule engine for completed_date variable support [DHIS2-9223]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
Fix an issue during the aggregation of the Grid data in Indicator queries: if the Period is used as filter and no
Period Offset is used in the Indicator, the code generates an invalid Map key.
Fix the problem by using all the dimension item UID as key components.
// Example
Given an analytics query:
`api/32/analytics.json?dimension=dx:Uvn6LCg7dVU&dimension=ou:ImspTQPwCqd&filter=pe:LAST_12_MONTHS`
There are 2 dimensions (`dx` and `ou`) and one filter (`pe`).
If the `dx` is an Indicator, the resulting Grid will contain multiple rows (one for each Indicator item), with 3 columns
1) indicator item uiid
2) ou uid
3) value
The aggregated Map, that is returned and used by the Expression engine, should  have the following key:
`<indicator item uid>-<ou uid>`
> fix: handle Period as filter in analytics Indicator queries

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
When a Program has a Data Element or TEA of type Organisation Unit, the system was persisting the OU name in the analytics_event_* and analytics_enrollment_* tables.
This was done to fix another issue with Event/Enrollment Line List view, which was showing the Org Unit UID rather than name.
Persisting the name, rather than the UID, was causing a bug becuase the join with the Org Unit table was broken, if a user selects "Org Unit Field" in the Event table layout (Pivot App).
This fix:
- reverts the change to the JdbcTableManager, so that the Org Unit UID is used in analytics tables
- adds a new column "`<dataelement>_name`" to the Event analytics tables, containing the name of the OU
- modifies the Events query logic to use this new column when querying for events, so that the OU name is …
> fix: Use Org Unit uid on Events/Enrollment table creation

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseDimensionalItemObject.java
The `equals` function on `BaseDimensionaltemObject` was using the default equals comparison: `if ( o == null || getClass() != o.getClass() )` which, in case of Hibernate proxied objects, will not work.
This fix removes that checks and calls the `equals` on the super class (`BaseNameableObject` which uses `isAssignableFrom` to handle proxy classes.
> fix: invoke super.equals() on BaseDimensionalItemObject

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/UniqueNameVerifier.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/resourcetable/table/UniqueNameVerifierTest.java
* fix: ensure unique column names for Resource Table
- DHIS2-8684
- This fix makes sure that during Resource Table generation process, the column names are always unique.
* chore: add missing class header
* Replace Abstract class with class encapsulating logic to ensure short
names do not collide.
* chore: renamed variable
(cherry picked from commit 7e8667f33c993c831f47aa1948d65e1901105ebb)
> [2.34] fix: Ensure unique column names for Resource Tables (#5409)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/UniqueNameVerifier.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/resourcetable/table/UniqueNameVerifierTest.java
* fix: ensure unique column names for Resource Table
- DHIS2-8684
- This fix makes sure that during Resource Table generation process, the column names are always unique.
* chore: add missing class header
* Replace Abstract class with class encapsulating logic to ensure short
names do not collide.
* chore: renamed variable
(cherry picked from commit 7e8667f33c993c831f47aa1948d65e1901105ebb)
> [2.33] fix: Ensure unique column names for Resource Tables (#5409)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/CategoryResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DataElementGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/IndicatorGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitGroupSetResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/UniqueNameVerifier.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/resourcetable/table/UniqueNameVerifierTest.java
* fix: ensure unique column names for Resource Table
- DHIS2-8684
- This fix makes sure that during Resource Table generation process, the column names are always unique.
* chore: add missing class header
* Replace Abstract class with class encapsulating logic to ensure short
names do not collide.
* chore: renamed variable
(cherry picked from commit 7e8667f33c993c831f47aa1948d65e1901105ebb)
> [2.32] fix: Ensure unique column names for Resource Tables (#5409)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
- dhis-2/dhis-services/dhis-service-validation/src/test/java/org/hisp/dhis/validation/ValidationNotificationServiceTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/PeriodCallable.java
https://jira.dhis2.org/browse/DHIS2-7539
Issue in in dataValueSet api.
- If the payload includes a period that doesn't exist in DB, then we have the function `reloadAndForceAddPeriod` to handle it.
- However the newly added Period is flushed to DB *after* the `dataValuesBatchHandler.flush()` Which leads to a foreign key constraint error 
=> This  fix will create a StatelessSession for adding the new Period and sync it with DB immediately. Instead of using the current session.
> fix: Error importing data values in first time

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandControllerTest.java
The `DataElementOperand` controller doesn't use the `AbstractCrudController` and has a "custom" pagination implementation.
Pagination wasn't working because the Pagination logic was not using the "total" size of elements returned by the query.
ref: DHIS2-9182
Co-authored-by: Lars Helge Øverland <lars@dhis2.org>
(cherry picked from commit 98cead69f5f38450c82df626a31997de1869246d)
> [2.34] fix: pagination for DataElementOperands uses proper count (#5852)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodStore.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/aggregate/DataImportTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/period/PeriodServiceTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java
https://jira.dhis2.org/browse/DHIS2-7539
This is a fix for PR https://github.com/dhis2/dhis2-core/pull/5897
- Move the code for opening stateless session  from PeriodService to HibernatePeriodStore
- Update the PERIOD_CACHE after saving period in stateless session
- Add unit test and a tweak to make PeriodType works with stateless session and h2 database in PeriodServiceTest
> fix: save Period in stateless session

- .github/workflows/analyse-pr.yml
Potential workaround for the issue where sometimes sonarcloud scans the wrong PR and doesn't annotate the last commit, causing the check to appear stale. https://community.sonarsource.com/t/sonarcloud-code-analysis-expected-onoging-issues/28154/50
> ci: specifies gthub revision

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
This fix handle the case in which a Data Element operand key (e.g. <Data Element UID>.<Category Option Combo UID>)
is not matching any of the Indicator items returned from the Expression Engine.
> fix: handle DataElementOperand mismatch in Indicator evaluation

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/vote/ExternalAccessVoter.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/vote/LogicalOrAccessDecisionManager.java
This fix resolves a problem reported by @vilkg that prevents the web application to start when launched within a Docker container.
See stacktrace
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accessDecisionManager' defined in class path resource [org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig$FormLoginWebSecurityConfigurerAdapter.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.hisp.dhis.security.vote.LogicalOrAccessDecisionManager]: Factory method 'accessDecisionManager' threw exception; nested exception is java.lang.NullPointerException
web_1    |      at …
```
> fix: remove static get for `ExternalAccessVoter`

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/vote/ExternalAccessVoter.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/vote/LogicalOrAccessDecisionManager.java
(cherry picked from commit a8c567ccb12b8d3a0df2b30b9b7145f5a0e82977)
> [2.35] fix: remove static get for `ExternalAccessVoter` (#5999)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/about/action/RedirectAction.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/AppsSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/Module.java
This PR adds a filter to the `dhis-web-portal` project which implements overloading of bundled core apps (`/dhis-web-xyz`) with an installed app of the same name (`/api/apps/xyz`)
To simplify this change and prevent issues with server discovery we are NOT changing app paths here.  The core apps are still served at the same paths (`/dhis-web-dashboard` etc.) but under the hood they will serve an installed `dashboard` app if it exists.  The path consolidation should be targeted for 2.36
TODO (in this PR):
TODO (after this PR):
- Check performance - can/should we restrict the filter to a subset of routes in `web.xml` instead of `/*`?
- **security** Consider namespacing core apps or creating a new app type to prevent accidental overrides
- **security** Consider validating developer org of …
> feat: add support for application overloads (DHIS2-9092)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/Event.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationConfig.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/AssignedUserValidationHookTest.java
Adds support for the assignedUser property in the new tracker importer.
Any valid uids are filtered, then we attempt to fetch related users in the preloader. In the validation we report any invalid uids or valid uids without a valid user.
> fix: DHIS2-9268 AssignedUser in Event (New Tracker Importer)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/about/action/RedirectAction.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/AppsSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/Module.java
This PR adds a filter to the dhis-web-portal project which implements overloading of bundled core apps (/dhis-web-xyz) with an installed app of the same name (/api/apps/xyz).
Forward port of #5977 
(cherry picked from commit 5b8b47712c8d93e13d2e7164d7a037a3630fbbac)
> feat: [2.36] add support for application overloads (DHIS2-9092) 

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
* Remove explicit wiring of an AuthenticationManager into XWorkSecurityInterceptor, this seems to fix an issue of Spring failing to startup because dep. wiring instability.
> chore: remove explicit wiring of an AuthenticationManager

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
* Adds permit all rule to urls that are outside (before) authentication
* Add missing service to DefaultSelectionTreeManager
* Add null check for user details on AuthenticationLoggerListener.java (happens when you register user and login automatically, and then try to log out)
> chore: add missing permitall to urls

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
* The setting of 2fa property in the account view is not working because the /me controller is not properly setting the user credentials property when PUT is called.
Issue: [DHIS2-9392]
> fix: add missing set 2fa on usercredentials in me controller

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
Corrected hql snippet to use the correct object structure instead of sql
> fix: [DHIS2-9411] assigned user related filters in hql formation (2.35)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorReport.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
Added an try catch block around the new tracker import service flow, to catch any unhandled exceptions. 
In case of exceptions, the import report and job summary in notifier will reflect the same with exception error message in it.
> fix: [DHIS2-9286] add exception handling globally to catch any unhandled ones and notify job correctly

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramInstanceRepeatableStageCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramInstanceRepeatableStageCheckTest.java
1. Added tei id into where clause when checking for existing programstageinstace
2. Removed an extra join , and used "id" columns instead of "uid"
> fix: [DHIS2-9410] include tei parameter when searching for existing psi (2.35)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/DimensionDescriptor.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/visualization/DimensionDescriptorTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
This is just a backport from master. This fix was merged into master this morning.
> fix: Use orgunit name instead of UID for Report Table download

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerController.java
Due to the new tracker importer not working 100% yet, we have decided to block the usage of the endpoint. We add a 501 status message when trying to access the endpoint.
> fix: Add 501 NOT IMPLEMENTED to POST /tracker

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerUserService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
Introduce a `TrackerUserService` dedicated to fetching the `User` object within
a read-only Transaction: this allows to initialize the `User`'s proxied collections.
The User object can now be used safely across the different Tracker layers.
ref: DHIS2-9285
> fix: prevent Hibernate session errors with User object

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppStatus.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-apps/scripts/bundle-apps.js
- dhis-2/dhis-web/dhis-web-apps/scripts/git.js
- dhis-2/dhis-web/dhis-web-apps/scripts/lib/sanitize.js
- dhis-2/dhis-web/dhis-web-apps/scripts/write-bundle-json.js
- dhis-2/dhis-web/dhis-web-apps/scripts/write-index-html.js
- dhis-2/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-apps/template.html
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/AppsSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java
This does two things:
1. (important!) this adds a check on application install to ensure that any app which will override a bundled app has the new `core_app=true` flag set in its manifest.  This ensures that override apps are explicitly built to be served from the `/dhis-web-xyz` namespace rather than the `/api/apps/xyz` namespace, and should help prevent unintentional bundled app overrides.
2. (minor) This adds a little more information to `/dhis-web-apps/index.html` and `/dhis-web-apps/apps-bundle.json`, specifying the name of the application (which can then be used for overrides)
> feat: require bundled app overrides to be configured with the coreApp flag in the manifest

- dhis-2/dhis-web/dhis-web-apps/README.md
- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
The app has been re-written and is now supports feature toggling (although there are no features to toggle as there are no api requests).
This PR
* If this is wrong, it's a separate commit I could just drop and the force-push the branch again
(please disregard the branch name)
> feat(apps to bundle): add cache cleaner to bundled apps v35

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventCommentStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventCommentStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventSupport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventCommentStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
This PR includes some minor refactoring to help writing a cleaner test.
- Comments related methods extracted from JdbcEventStore into JdbcEventCommentStore
- Table programstageinstancecomments is only queried if there's at least one comment to store.
> perf: [DHIS-9415] avoid querying programstageinstancecomments if not necessary

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
Added a **distinct** on the dataelementcategoryoption table. Without the distinct, a "certain production database" is getting duplicated records, which in turn duplicates the rows because of the left join. Eventually there are as many "duplicate events",
If the page size is 15, we get 15 duplicated records of the same event. The implementation recognizes the duplicate event uid, and ultimately just one event is sent back to the client with incorrect pager objects. Parallely investigating if its a data issue.
> fix: [DHIS2-9295] Events missing/hidden from response due to incorrect security filter sql (2.32)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/DHIS2BasicAuthenticationEntryPoint.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
* Make sure 2.35 behaves in the same way as before xml to java config refactor.
On >=2.34 the user would be redirected to the form login if user is not authorized.
> chore: fix http basic auth to redirect to form login on 401

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/EventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- Make sure that events are sorted by UID before doing a batch update.
This prevents multiple concurrent transactions to trigger a Postgres
deadlock, when the list of events is "out of order"
- Make sure that the TEI are sorted when updating TEI after an Event
update
- Added javadoc to interfaces
- Code clean-up
ref: DHIS2-9283
> [2.35] fix: prevent db deadlock during Event update

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/EventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- Make sure that events are sorted by UID before doing a batch update.
This prevents multiple concurrent transactions to trigger a Postgres
deadlock, when the list of events is "out of order"
- Make sure that the TEI are sorted when updating TEI after an Event
update
- Added javadoc to interfaces
- Code clean-up
(cherry picked from commit 3348897beff380785f0404c57019da62ee3fba0b)
> [2.35.0] fix: prevent db deadlock during Event update (#6131)

- dhis-2/pom.xml
> fix: [DHIS2-9483] Update FOP deps

- dhis-2/pom.xml
Backporting from master (2.36).
> fix: [DHIS2-9483] Update FOP deps (2.35)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v35/V2_35_22__add_sms_authority_to_userauthoritygroups.java
For all `UserAuthorityGroups` that have the `M_dhis-web-maintenance-mobile` also add in `M_sms-configuration-app`.
[DHIS2-9514](https://jira.dhis2.org/browse/DHIS2-9514)
> feat: adds sms authority migration where mobile authority is present

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
The prop in the json output of `/api/apps` is `bundled`.  This change changes the `?filter` query to match this, from `?filter=isBundled:eq:true` to `?filter=bundled:eq:true`
This filter parameter is not currently used by any frontend apps, so this is not a breaking change.  It's important to get into 2.35.0 if possible so that we don't introduce a new API inconsistency that we have to "break" later.
> fix: match bundled filter to prop name

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/AbstractAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EventAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/ThreadPoolManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
Removes the `@Transactional` annotation from the newly added `getTrackedEntityInstances2`.
The annotation was causing the C3P0 pool to saturate with 200+
concurrent users. The first 80 threads were keeping the Transaction
open (80 is the default pool size), while executing the TEI fetching
logic. The other 120 threads were also trying to access the DB, but
could not get a connection from the pool.
This PR also:
- Makes the TEI fetching use a dedicated Executor to avoid using the default JVM ThreadPool
- Adds 3 local caches for TEI Attribute Type, TEI Attribute by Program and security context
- Adds a method to persist TEI Audit in batch, rather than executing an INSERT statement for each TEI to audit
- Uses lombok annotation to remove constuctors
- Minor code cleanup
(cherry picked from …
> [2.35.0] fix: DB pool saturation under heavy concurrency

- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramStageInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/mapper/ProgramStageInstanceMapper.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/ProgramStageInstanceUpdatePreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/pom.xml
Data Value of type File Type were making the update process to fail.
Introduced a more solid handling of mandatory data (e.g. Program Instance, Org Unit) since we can't always assume that the client will send all the required data.
Added some tests.
Added new test library to assert dates.
ref: DHIS2-9559
(cherry picked from commit 408c1e286509c0b49736791d1a1e2d86e15c2eac)
> [2.35.0] fix: allow updating an Event with File data type

- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramStageInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/mapper/ProgramStageInstanceMapper.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/ProgramStageInstanceUpdatePreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/pom.xml
Data Value of type File Type were making the update process to fail.
Introduced a more solid handling of mandatory data (e.g. Program Instance, Org Unit) since we can't always assume that the client will send all the required data.
Added some tests.
Added new test library to assert dates.
**NOTE**: this is a forward-port from a PR alreade merged for 2.35.0 (3520e1abc8768281a8747b0b03f2a5b0027bfe6c)
ref: DHIS2-9559
(cherry picked from commit: e522e985d6d4fcd5bc5d6546b9337d6ab07dcfe7)
> fix: allow updating an Event with File data type

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/AbstractAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EventAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/ThreadPoolManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
Removes the `@Transactional` annotation from the newly added `getTrackedEntityInstances2`.
The annotation was causing the C3P0 pool to saturate with 200+
concurrent users. The first 80 threads were keeping the Transaction
open (80 is the default pool size), while executing the TEI fetching
logic. The other 120 threads were also trying to access the DB, but
could not get a connection from the pool.
This PR also:
- Makes the TEI fetching use a dedicated Executor to avoid using the default JVM ThreadPool
- Adds 3 local caches for TEI Attribute Type, TEI Attribute by Program and security context
- Adds a method to persist TEI Audit in batch, rather than executing an INSERT statement for each TEI to audit
- Uses lombok annotation to remove constuctors
- Minor code cleanup
(cherry picked from …
> fix: DB pool saturation under heavy concurrency

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/AbstractAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EventAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/ThreadPoolManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
Removes the `@Transactional` annotation from the newly added `getTrackedEntityInstances2 (courtesy of @enricocolasante ).
The annotation was causing the C3P0 pool to saturate with 200+ concurrent users. The first 80 threads were keeping the Transactionopen (80 is the default pool size) while executing the TEI fetching
logic. The other 120 threads were also trying to access the DB, but
could not get a connection from the pool.
This PR also:
- Makes the TEI fetching use a dedicated Executor to avoid using the default JVM ThreadPool
- Adds 3 local caches for TEI Attribute Type, TEI Attribute by Program and security context
- Adds a method to persist TEI Audit in batch, rather than executing an `INSERT` statement for each TEI to audit
- Minor code cleanup
> [2.35] fix: DB pool saturation under heavy concurrency

- dhis-2/pom.xml
Backporting from master (2.36).
**DO NOT merge it until this is approved by the release control board.**
> fix: [DHIS2-9483] Update FOP deps (patch/2.35.0)

- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventSupport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramStageInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/mapper/ProgramStageInstanceMapper.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/ProgramStageInstanceUpdatePreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
- dhis-2/pom.xml
Data Value of type File Type were making the update process to fail.
Introduced a more solid handling of mandatory data (e.g. Program Instance, Org Unit) since we can't always assume that the client will send all the required data.
Added some tests.
Added new test library to assert dates.
ref: DHIS2-9559
(cherry picked from commit b618019119fe87c4f0c4f24b7d2a7de313ea4006)
> [2.35] fix: allow updating an Event with File data type

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
During Event Import, the system tries to fetch a Category Option Combo by Category Combo ID
and category options, based on the input.
The SQL query for fetching the Category Option Combo was using an incorrect `join`, which in certain cases, was not returning any result.
ref: DHIS2-9565
(cherry picked from commit b61d3f6648fd3dd95481d6a877bf29c93835e9ab)
> [2.35.0] fix: SQL query to fetch category option combo

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
During event import, the query that fetches user access for programs was using an incorrect join, which
was causing no rows to return.
(cherry picked from commit 1eaad52e08503ba82b067a2b7ba02bf7e9fec6ad)
> fix: fix User Access SQL query for programs

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplierAclIntegrationTest.java
The ProgramSupplier class (used by Tracker Import for Events) spawns a number
of ACL related queries which were not covered by unit tests.
This PR adds integration tests for checking the ACL queries for user and user groups for:
- Program
- Program Stage
- Tracked Entity Type
*Note: this PR is related to JIRA DHIS2-9584 and complete the task by adding unit tests*
> test: added tests for the ACL section of the ProgramSupplier

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplierAclIntegrationTest.java
The ProgramSupplier class (used by Tracker Import for Events) spawns a number
of ACL related queries which were not covered by unit tests.
This PR adds integration tests for checking the ACL queries for user and user groups for:
- Program
- Program Stage
- Tracked Entity Type
(cherry picked from commit 97732d9b1c17dc1ccbbbd4c69cc764178ebb80f3)
*Note: this PR is related to JIRA DHIS2-9584 and complete the task by adding unit tests*
> [2.35] test: added tests for the ACL section of the ProgramSupplier

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
This change will cause 2.33dev to use the master branch of the usage analytics app, which is how things are supposed to work.
For more context, please see the Slack conversation starting [here](https://dhis2.slack.com/archives/G01BEB0AA8G/p1600180513000100). I've also ran the proposed solution past @amcgee before preparing this PR and he agreed this was the way forward.
It seems that the `2.33` branch didn't have a README with feature-toggle table so that is not included here. I will prepare another PR against master shortly that will update that readme file.
> fix(web-apps): let v33 use master branch of usage-analytics

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
Spring will create many instances of `AbstractCrudController`, since each Metadata controller is extending that abstract class.
Since the cache2k cache in `AbstractCrudController` is not declared as static, we end up with many caches which are completely wasteful.
By adding the `static` keyword we make sure that one cache is shared among controllers.
> perf: use static cache in AbstractCrudController

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java
This custom serialization causing lazy exception for audit service
It also calling `children.isEmpty()` for attribute `hasChild` which in result will fetch the whole hierarchy.
> fix: remove custom serialization for OU.getChildren()

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_14__Add_sequentialcounter_procedure.sql
A flyway script "Add sequentialcounter procedure" has been backported until 2.33, but it was not idempotent. The same has to be made idempotent in atleast 2.34 and 2.35 so that upgrades from 2.33.6 into any 2.34.2+ or 2.35.0+ versions is possible.
> fix: backported flyway script to make it idempotent (2.35.0)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_14__Add_sequentialcounter_procedure.sql
A flyway script "Add sequentialcounter procedure" has been backported until 2.33, but it was not idempotent. The same has to be made idempotent in atleast 2.34 and 2.35 so that upgrades from 2.33.6 into any 2.34.2+ or 2.35.0+ versions is possible.
On merge of this PR, there are certain development instance issues expected (with checksum) since we are changing an existing script. But since the specific script is not part of any major/patch release, we can deal with the dev checksum issues ourselves. Even on play instances depending on the db dump used we might have to fix that as well.
> fix: backported flyway script to make it idempotent (master 2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericHttpGetGatewayConfig.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v34/V2_34_6__Convert_systemsetting_value_column_from_bytea_to_string.java
Added back SimplisticHttpGetGatewayConfig, so that deserialization of an object serialized in 2.33 is possible. 
Modified a java flyway script to handle "keySmsSetting" system setting separately and convert SimplisticHttpGetGatewayConfig (2.33) into SimplisticHttpGatewayConfig(2.34+).
> fix: [DHIS2-8782] upgrade fails from 2.33 into higher versions if there is a sms gateway already configured (master) 

- dhis-2/pom.xml
New ANTLR library will provide user-friendly messages in case the expression has a syntactical error.
> chore: Bump ANTLR library version [DHIS2-9444]

- dhis-2/pom.xml
The updated ANTLR library will return a user-friendly message when there is any syntax error in expression.
> chore: (2.35) Bump ANTLR library version [DHIS2-9444]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericGatewayParameter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericHttpGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsGatewayConfig.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java
Include confidential parameters in response while fetching SMS configurations.
> fix: (2.35.0) SMS confidential values [DHIS2-9582]

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/DefaultAuditObjectFactory.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/config/JacksonObjectMapperConfig.java
* Current Hibernate5module configuration, breaks the normal deserialization usage.
The Hibernate5module is meant to be used in context when there is no open session in view, aka. no request that initiates the operation.
In DHIS2 this used for scheduled background tasks and the audit system.
> fix: broken Hibernate5module usage

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
During Event Import, the system tries to fetch a Category Option Combo by Category Combo ID
and category options, based on the input.
The SQL query for fetching the Category Option Combo was using an incorrect `join`, which in certain cases, was not returning any result.
ref: DHIS2-9565
(cherry picked from commit b61d3f6648fd3dd95481d6a877bf29c93835e9ab)
*Note: this PR was already approved and merged in 2.35.0*
> fix: SQL query to fetch category option combo

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
2 fixes here:
- Add the enrollment field in the events so they can be grouped correctly and the importSummary is correctly calculated.
- Remove duplication of ignored count when one event is invalid in a list with other valid events
> fix: [DHIS2-8872] Fix import summary count for events in enrollment

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericGatewayParameter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericHttpGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsGatewayConfig.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java
Include confidential parameters in response while fetching SMS configurations.
> fix: (2.35) SMS confidential values [DHIS2-9582]

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/DefaultAuditObjectFactory.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostDeleteAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostInsertAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostLoadAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostUpdateAuditListener.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/config/JacksonObjectMapperConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateUtils.java
https://jira.dhis2.org/browse/DHIS2-9467
- Remove Hibernate5Module in DefaultAuditObjectFactory
- Manually call HibernateUtils.initializeProxy  in Audit Listeners
- For web ui and web api requests, current session in Audit Listeners is still open  so just need to refresh the entity if needed and call HibernateUtils.initializeProxy
- In e2e test, the session is closed in Audit Listeners, so need to open new session.
> [WIP] fix: lazy exception in AuditObjectFactory

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplierAclIntegrationTest.java
The ProgramSupplier class (used by Tracker Import for Events) spawns a number
of ACL related queries which were not covered by unit tests.
This PR adds integration tests for checking the ACL queries for user and user groups for:
- Program
- Program Stage
- Tracked Entity Type
(cherry picked from commit 97732d9b1c17dc1ccbbbd4c69cc764178ebb80f3)
*Note: this PR is related to JIRA DHIS2-9584 and complete the task by adding unit tests*
> [2.35.0] test: added tests for the ACL section of the ProgramSupplier

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardItem.java
https://jira.dhis2.org/browse/DHIS2-9632
Not sure why but Jackson failed to find the custom deserializer on getter, it works with setter. 
I haven't seen this issue anywhere else.
```Level: ERROR, category: METADATA_IMPORT, time: Mon Sep 28 09:51:25 UTC 2020, message: Process failed: could not extract ResultSet] (InMemoryNotifier.java [taskScheduler-7])
com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing property 'users' (expected type: [collection type; class java.util.List, contains [simple type, class org.hisp.dhis.user.User]]; actual type: `org.hisp.dhis.user.User`), problem: java.lang.ClassCastException@53ab7d22
at [Source: (ZipInputStream); line: 19, column: 93408] (through reference chain: org.hisp.dhis.dxf2.metadata.Metadata["dashboards"]>java.util.ArrayList[ …
```
> fix: Deserialization issue of DashboardItem.users

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Count will be checked irrespective of `totalPages` param.
> fix: [DHIS2-9625] totalPages param when used ignores maxteicount setting (master 2.36)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerProgramRuleService.java
PR fixes the problem with SENDMESSAGE/SCHEDULEMESSAGE program rule action. It was caused by a lazy initialization issue and was resolved by annotating ProgramRuleEngineService class with `@Transactional `annotation.
> fix: (2.34) Add fix for program rule action [DHIS2-9489]

- .github/workflows/analyse-pr.yml
- .github/workflows/run-tests.yml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncDelegateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/version/MetadataVersionDelegateTest.java
* All DHIS2 unit tests runs successfully on Java 16
Issue:[DHIS2-9608]
> fix: make sure all tests run on Java 11+

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
* A bug was introduced under refactoring of the /api endpoint security config, resulting in reverting another fix for redirect to login page on unauthorized access to /api endpoints.
Issue:[DHIS2-9469]
> chore: fix refactoring bug in api security config affecting redirect

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageInstanceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramStageInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramStageInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageInstanceServiceTest.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- Removed all Transactional annotation from rule engine services
- Retrieve ProgramStageInstance with all fields that are required in the rule engine process (ProgramStage and OrganisationUnit)
- Removed some code duplication
> fix: Reorganizing transaction logic in calls to rule engine [DHIS2-9630]

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/DefaultAuditObjectFactory.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/config/JacksonObjectMapperConfig.java
* Remove all usage of Hibernate5Module
Current Hibernate5module configuration breaks the JSON deserialization. The Hibernate5module is meant to be used in context when there is no open session in view, like background tasks and asynchronous tasks.
In DHIS2 this used for scheduled background tasks and the audit system.
Another PR to reconfigure Hibernate5Module will come later.
Issue: [DHIS2-9451]
(cherry picked from commit 2a6af5fe3c745123be67bd3a84127d32f04761f4)
> fix: broken Hibernate5module usage [DHIS2-9451]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
This fixes the cases where we have the period set as a "pe" with relative range - like LAST_12_MONTH. (2.35)
> fix: [ DHIS2-9724] Period extraction in Indicators evaluation is wrong

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
This fixes the cases where we have the period set as a pe with relative range - like LAST_12_MONTH (2.35)
> fix: [DHIS2-9724] Period extraction in Indicators evaluation is wrong

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/Module.java
Fixes https://jira.dhis2.org/browse/DHIS2-9786
The getModules.action endpoint was appending a duplicate app name to the icon URL, causing broken app icon images
Requires release control board approval before merging
> fix: don't append duplicate app name to icon url in Module (DHIS2-9786)

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
Previously, application overrides only worked on instances deployed as ROOT.war, because the entire request URI was matched against the override regex.  This change removes the context path from the start of the request URI before performing the match.
Huge thanks to @Philip-Larsen-Donnelly for finding this and sniffing out the root cause!
> fix: support non-root deployments when matching paths for override [DHIS2-180]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java
* Make most of the db pool settings configurable. 
* Enable test connection on checkin, default value "true", this change fixes the issue making the db pool deadlock on very high concurrency load right after startup.
> fix: Make db pool connection test enabled to avoid deadlocks (#6412)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventdatavalue/EventDataValue.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeValue.java
https://jira.dhis2.org/browse/DHIS2-9441
EventDataValue doesn't have `@JsonProperty` declared so it was serialized and saved to DB as blank in audit table
Note that `@JsonIgnore` has been added to `getDataElement()` before,  there should be a reason for this... not sure if I should remove it.
sample record after this fix 
`org.hisp.dhis.program.ProgramStageInstance | y0xpS1oOBzx | {"uid": "y0xpS1oOBzx", "status": "ACTIVE", "deleted": false, "programStage": "A03MvHHogjR", "attributeValues": [], "eventDataValues": [{"value": "asdasdasd", "created": "2020-10-07T15:49:20.666", "lastUpdated": "2020-10-09T00:04:17.169"}], "programInstance": "uX36vBo3vfF", "organisationUnit": "DiszpKrYNg8", "attributeOptionCombo": "HllvX50cXC0"} | UPDATE    |`
> fix: eventDataValue is blank for audit entry

- .github/workflows/codeql-analysis.yml
* CodeQL will not understand which base branch to compare against using wildcards see:
https://bluecolibri.org/2020/10/05/github-enabling-code-scanning-for-a-repository
> chore: lock CodeQL analysis pull_request param to master branch

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
During Event Import, the system tries to fetch a Category Option Combo by Category Combo ID
and category options, based on the input.
The SQL query for fetching the Category Option Combo was using an incorrect `join`, which in certain cases, was not returning any result.
ref: DHIS2-9565
(cherry picked from commit cf7cadc05f06671c5b8a244b9d51abcf33e7adcb)
Note: this PR was already approved and merged in 2.35.0
> [2.35] fix: SQL query to fetch category option combo

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorReport.java
Added JsonCreator annotation to all arg constructor in TrackerErrorReport.java. Redis uses json deserialization for RedisNotifier.
> fix: [DHIS2-9816] When using redis TrackerErrorReport deserialization failure (2.36)

- dhis-2/pom.xml
Upgraded flyway version to 7.0.4. Official support for pg v13.
> chore: [DHIS2-9797] upgrade flyway to version 7.0.4

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
* fix: Use Org Unit uid on Events/Enrollment table creation
When a Program has a Data Element or TEA of type Organisation Unit, the system was persisting the OU name in the analytics_event_* and analytics_enrollment_* tables.
This was done to fix another issue with Event/Enrollment Line List view, which was showing the Org Unit UID rather than name.
Persisting the name, rather than the UID, was causing a bug becuase the join with the Org Unit table was broken, if a user selects "Org Unit Field" in the Event table layout (Pivot App).
This fix:
- reverts the change to the JdbcTableManager, so that the Org Unit UID is used in analytics tables
- adds a new column "<dataelement>_uid" to the event analytics tables, containing the name of the OU
- modifies the Events query logic to use this new …
> fix: Use Org Unit uid on Events/Enrollment table creation (#5892)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerImportReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerObjectReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerTypeReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleImportReportTest.java
Two issues are resolved in this PR as it was a bit tightly coupled.
1. Added exception handling within the ImportService to catch any exceptions and mark the job as completed with failure. The changes for this was already merged into 2.35 but for some reason, the forward port merge of 2.35 into master missed that change. Simply added a try catch block in DefaultTrackerImportService to catch exceptions and notify the job to be completed with failures.
2. Added support for serializing and deserializing TrackerImportReport so that no data is lost. Added necessary annotations to help Jackson serialize and deserialize TrackerImportReport.
> fix: [DHIS2-9817] [DHIS2-9825] serialization and deserialization of TrackerImportReport and excception handling (2.36)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
The importReport.status and importReport.message was not copied into the filteredImportReport which always causes the status to show as "OK" even if there are errors.
> fix: [DHIS2-9286] handled exception messages filtered out in final report (2.36)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AbstractTrackerDtoValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentDateValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventNoteValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
In order to reduce the amount of code required to generate an error report during Tracker validation, I have introduced a couple of helper methods in the validation abstract class.
> refactor: simplified calls to error reporting

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
Remove the default value for `AggregationType` in the newly introduced object
`EventsAnalyticsQueryCriteria`. The value must be null (unless specified by the client), otherwise the query validation fails.
> fix: remove default value for AggregationType in Event criteria object

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
* The AppOverrideFilter is too verbose, change log level from INFO to DEBUG
> chore: lower the log level on the AppOverrideFilter

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
I think this was omitted from `master` (2.36) because we would want to install it from App Hub, but we don't have CI set up yet so we should probably bundle this for now to make QA easier, and opt to unbundle it before cutting 2.36 if we get everything set up.
> feat: add SMS Configuration App

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentitycomment/TrackedEntityCommentService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentitycomment/TrackedEntityCommentStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitycomment/DefaultTrackedEntityCommentService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentitycomment/hibernate/HibernateTrackedEntityCommentStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentitycomment/TrackedEntityCommentServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/Note.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationContext.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentNoteValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventNoteValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/NoteValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckValidateAndGenerateUidHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/NotesConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventNoteValidationHookTest.java
Make sure that a client sending an Enrollment or Event Note with the UID set, will get a proper error message if the Note UID already exist in the database.
ref: TECH-457
> feat: improve note validation during Tracker import

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityReport.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/FlattenedDataIntegrityReport.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
This is a non-functional change.  For some reason the getter and setter for one integrity check had an extra `get` in the name:
```
private List<ProgramIndicator> getProgramIndicatorWithNoExpression; // not a getter, shouldn't start with get
public List<ProgramIndicator> getGetProgramIndicatorWithNoExpression; // extra get in getter name
public void setGetProgramIndicatorWithNoExpression; // extra get in setter name
```
The variable, getter, and setter names were also singular instead of plural (`Indicator` not `Indicators`)
This is a purely code quality and readability change - the serializable class `FlattenedDataIntegrityReport.java` correctly renamed the variable to `programIndicatorsWithNoExpression` (no prefix, plural), so there is no change in the API response.
The pre-commit style …
> chore: remove duplicate get in integrity check getter/setter

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java
Update the logic for returning null if optionSet.getOptions is empty.
Otherwise proceed to update/refresh the option.Optionset association
> fix: options are not shown on UI after import

- Jenkinsfile-publish-image
This PR enables the use of the same multibranch pipeline we use for publishing dev and release images.
The problem was, that we use the branch name as the image name. When the branch name contained `/`, like `patch/2.35.0`, docker failed to tag the image. This should eliminate the problem. Additionally, `-rc` will be appended to the image name.
Alternatively, we could have a separate channel for release candidates, eg. `dhis2/core-rc`, but I think `dhis2/core-dev` works too.
I tested this on jenkins and published `2.35.0-rc` images.
This will need to be backported to all supported branches.
> ci: enable rc docker images

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerObjectReport.java
1. Default to current date in case of DataValue.createdAt and DataValue.updatedAt is null during creation.
2. Change primitive int to wrapper Integer to support null values in ImportReport.
> fix: [DHIS2-9886] [DHIS2-9890] deserialization of primitive and null check for datavalue dates

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/DataItemServiceFacade.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/helper/FilteringHelper.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/helper/FilteringHelperTest.java
Fix introduced to allow the "usual" filtering on top of all data items. This bug is currently blocking it.
The test cases were also updated and increased to reflect this fix.
> fix: DHIS2-9914: Filtering all items in /dataItems endpoint is not working

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
This happens only when we have event data items.
Current response (mismatch):
```
{
"headers": [
{
"name": "ou",
"column": "Organisation unit",
"valueType": "TEXT",
"type": "java.lang.String",
"hidden": false,
"meta": true
},
{
"name": "pe",
"column": "Period",
"valueType": "TEXT",
"type": "java.lang.String",
"hidden": false,
"meta": true
},
{
"name": "value",
"column": "Value",
"valueType": "NUMBER",
"type": "java.lang.Double",
"hidden": false,
"meta": false
}
],
"metaData": {},
"rows": [
[
"kla3mAPgvCH.HrJmqlBqTFG",
"ImspTQPwCqd",
"202001",
"567.0"
],
[
"kla3mAPgvCH.HrJmqlBqTFG",
"ImspTQPwCqd",
"202010",
"136.0"
]
],
"height": 2,
"width": 4,
"headerWidth": 3
}
```
Response after this fix:
```
{
"headers": [
{
"name": "dy",
"column": "Data",
"valueType": "TEXT",
"type": …
```
> fix: [DHIS2-9601] Header vs rows mismatch on event data items as filter

- .github/workflows/run-tests.yml
- Dockerfile
Adds another GitHub action that will run the API tests. The job run takes around 15 minutes because we need to build a war and set up an environment, so for now, we will trigger it only for PRs that need that. 
Label `run-api-tests` will trigger an API test run. If tests fail, logs from the server will be added as a job artifact.
The tests are failing, because they are failing on master.
> ci: run api tests with github action

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/audit/AuditIntegrationTest.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditManager.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/AuditObjectFactory.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/DefaultAuditObjectFactory.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostInsertAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostUpdateAuditListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/AuditManagerTest.java
Add code to handle EmbeddedObject using same logic. That is if the embeddedObject contains IdentifiableObject, only uid of those objects will be serialized.
> fix: support serialize embeddedObject for audit

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v36/V2_36_13__Remove_skip_zeros_in_analytics_system_setting.sql
Removes the system setting `SKIP_ZERO_VALUES_IN_ANALYTICS_TABLE_EXPORT`. Instead only assumes `true`, i.e. always skips zero values in analytics tables (except for certain existing conditions).
> fix: Remove system setting for skip zeros in analytics tables [DHIS2-9902]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
The Event values `occurredAt` and `updatedAt` are no longer validated.
The client values are ignored and set by the system.
ref: DHIS2-9951
> fix: remove validation for event date fields

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceByTeiSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/BundlePreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventDefaultEnrollmentPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/RuleActionApplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/RuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/hooks/ProgramInstanceByTeiHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventDefaultEnrollmentPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/enrollments_te_te-data.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/events_tei-not-enrolled.json
Fixes an issue with validating the `trackedEntity` value of an incoming Event.
Additionally, this PR introduces a `BundlePreProcessor` interface to alter the payload prior to validation.
A new PreProcessor is created to infer the `trackedEntity` value of an Event from the parent Enrollment.
ref: DHIS2-9958
> fix: correct validation rule for Event's TEI value

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Fix no transaction exception while importing events. 
Resolved it by adding `@Transactional` annotation so it has to be tested for performance.
standard 2.34
2.34 feature branch
> fix: (2.34) No transaction error while importing Events [DHIS2-9936]

- dhis-2/dhis-support/dhis-support-commons/pom.xml
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/StreamUtils.java
- dhis-2/dhis-web/dhis-web-api/pom.xml
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IconController.java
* Close file descriptors to prevent leak for app resources that leads to unusable DHIS 2 instance.
Issue:[DHIS2-9939]
> fix: Close files used by Apps

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterService.java
Without this, the relationshipitem in db had a null reference to relationship, causing a NPE when retrieving the relationship.
> fix: Added missing reference from RelationshipItem to Relationship

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/DataItemServiceFacade.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/helper/FilteringHelper.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/helper/FilteringHelperTest.java
Backporting to 2.35, from master
> fix: DHIS2-9914: Filter all items in /dataItems endpoint not working

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackerBundleParamsConverter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/AssignedUserValidationHookTest.java
Updates the Converter to check all potential nested objects. During this process, we also assign UIDs where ever they are missing, and make sure references between nested objects remain after being flattened.
We also make sure we filter away notes with empty values. This should however be moved to a preprocessor class.
Also fixed failing tests:
Added event.event value (uid) for failing program rules test. Converter was not used here, so simlest solution was to add a uid since we are not testing the converter here.
Made sure relationshipConverter test doesnt require specific order for relationships to be returned.
> fix: Updated the Converter class; Fixed failing tests

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
If default CategoryOption is used in the payload, an error is shown because the CategoryOption is not loaded into the Preheat. DHIS2-9975
> fix: Add into Preheat also default values for CategoryOption (DHIS2-9975)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
When validation was failing and AtomicMode was ALL, not importSummary was present calling `/tracker/jobs/{jobUid}/report` endpoint
> fix: add report when validation failed

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerValidationReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationContext.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AbstractTrackerDtoValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
The Tracker import process should make sure that Relationships pointing to invalid Tracker objects are not persisted and a meaningful error is returned to the client.
Ref: DHIS2-9991
> fix: A relationship pointing to an invalid object should not be saved

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerImportReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleImportReportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerImportReportTest.java
This PR fixes several problems with the Tracker Import report and specifically with the "Stats" objects, attached to the report.
The `ignore` value is now calculated correctly on both the global stats and the Bundle Report stats.
ref: DHIS2-9991, DHIS2-9981
> fix: Import report ignore values on stats objects

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java
Few things done here:
- Validation to check if there are exactly to null entities in relationship constraint was split and moved away from mandatory validations.
- Validation to check if there is more than one entity in relationship constraint
- Validation to check if there is at least one entity in relationship constraint
> fix: Fix validations when no entities aare linked in a relationship [DHIS2-9995]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
Make sure that the an invalid Relationship is not persisted during Tracker Import.
The PR simply adds a super method to the Relationship validation that removes the failed Relationship from the payload.
ref: DHIS2-9991
> fix: relationship should not be imported when invalid

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
Removed alternate flow when specifying tei uids explicitly in params for api/trackedEntityInstances (and query) and included the functionality as part of the main flow. This means that if uids are explicitly specified, then that becomes the outer boundary for all filters additionally provided.
> fix: [DHIS2-9985] Align ownership OU check for TEI APIs even when specifying uids explicitly (2.36)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerImportService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportParamsBuilder.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportParamsBuilderTest.java
Moved the logic to map HTTP request params to the `TrackerImportParams` object
from the Service layer to the front layer.
Added unit tests
> refactor: Tracker Import params creation

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramStageInstanceStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/EventStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
Validates that a soft-deleted event cannot be Deleted or Updated.
Trying to insert an event that has a UID matching the UID of an existing, soft-deleted event, will also fail the validation.
ref: DHIS2-9888
> fix: prevent changes to a deleted event

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHook.java
A lazy exception was thrown when collecting the comments for a ProgramInstance, now that we removed the Transactional from the whole import.
The mapping of the whole object was not needed
> fix: remove Lazy Init Exception on enrollment update

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/entry.js
In the data entry app, prepends a '0' to the stored value sent to the backend if the user enters a number starting with a '.' instead of telling the user they entered an illegal number.
For example: .1 -> 0.1, .33 -> 0.33, etc.
Note: This is similar to what Excel and Google Sheets do. They add a leading zero if the user enters a number starting with a '.'
> fix: Leading decimal number data entry DHIS2-2510

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
Backport that has already been merged to 2.33 till 2.36
> fix: [DHIS2-9985] Align ownership OU check for TEI APIs even when specifying uids explicitly (2.34-ksoidc)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DefaultTrackerPreprocessService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/SetMandatoryFieldValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowErrorOnCompleteValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowErrorValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowWarningOnCompleteValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowWarningValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerTimingsStats.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerValidationReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationConfig.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/SetMandatoryFieldValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ShowErrorWarningImplementerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentAttrValidationTests.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TeTaValidationTest.java
The primary goal of this commit is moving rule engine call after bundle validation
so there are no unexpected problems building the context to call rule engine.
Other issues solved by this commit are:
- Put a default value for occuredAt date in the enrollment converter
- Remove the invalid entities from the bundle after validation, to avoid
errors in the persistence phase
> fix: [DHIS2-7310] Move rule engine call and validations after bundle validation

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
The Transactional annotation is needed to make sure all the lazy collections in the
creation of the rule engine context ar correctly loaded correctly
> fix: Adding Transactional annotation in rule engine call

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/Program.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/EnrollmentSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/SimpleEventSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/TrackedEntityRegistrationSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/EnrollmentSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/SimpleEventSMSListenerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/TrackedEntityRegistrationListenerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/configuration/AuditMatrix.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/HibernateListenerConfigurer.java
Deprecated the method `Program.hasOrganisationUnit()` and replaced with SQL method on the `ProgramService`.
All calls to `Program.hasOrganisationUnit()` have been replaced with a call to `ProgramService.hasOrgUnit`, which uses a fast JDBC-based query against the `program_organisationunits` table.
Additionally, added a check to disable the `LOAD` Hibernate listener, if ON_LOAD auditing is disabled by the user.
> perf: replace expensive "Program has OrgUnit" call with faster SQL

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/PreheatCacheService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/OrganisationUnitMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/AbstractPreheatSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/OrgUnitValueTypeSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/PeriodTypeSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/TrackedEntityTypeSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/AbstractSchemaStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/CatOptionComboStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/CatOptionStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/DataElementStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/GenericStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/OrgUnitStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/ProgramStageStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/ProgramStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/StrategyFor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/PeriodTypeSupplierTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/RelationshipTypeSupplierTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/pom.xml
This PR introduces a Cache2K-based cache for caching metadata objects accessed during the Preheat stage of the the Tracker Import process.
Notable changes:
- Introduced a `cache` property to the `@StrategyFor` annotation used to pre-load metadata. The property signals if the Metadata fetching class should cache the results
- Introduced a `PreheatCacheService` in the `preheat` package that is responsible for instantiating the caches for the metadata objects.
- Introduced a new global property `tracker.import.preheat.cache.enabled` to disable the Tracker Import cache.
- Bumped version of cache2K to `1.6.0.Final`
> feat: Tracker Import metadata cache

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramOrgUnitSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContextLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramOrgUnitCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramOrgUnitSupplierTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramOrgUnitCheckTest.java
This PR modifies the Event import code that was refactored in version 2.35 and optimmizes the check to verify if an Event's Org Unit is part of the Event's Program Org Units List.
Programs are now stored in the `WorkContext` without the "link" to Organization Units.
A new, dedicated data structure is created to map Program to Org Units - using only Org Units effectively specified in the payload.
This change is required to minimize memory allocation and SQL exec time when a Program has a very large (> 10.000) Org Units associated to it.
ref: DHIS2-10139
> perf: reduce number of Org Units fetched from DB on Tracker Import

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/outlierdetection/service/OutlierDetectionManager.java
Catches error from cast of non-numeric data during outlier detection. This approach is faster than filtering out non-numeric data with regexp matching, although might lead to error responses where the filtering approach would return a result.
> fix: Add error handling for cast of non-numeric data during outlier detection

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/config/ArtemisConfig.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
Adds a new config key `audit.inmemory-queue.enabled` that enable/disable the Audit Scheduler.
The default value is "off".
This config key already exists in 2.34 and 2.35.
> fix: add config key to disable Audit scheduler

- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/RelationshipDeletionHandler.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_17__Remove_referenced_relationships_from_soft_deleted_events_and_enrollments.sql
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Remove associated relationships when soft deleting events/enrollments to avoid constraint issues when hard deleting them. Also added a flyway script to remove historically soft deleted events/enrollments
> fix: [DHIS2-6642] delete relationships associated with soft deleted events (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramStageInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageInstanceServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/eventdatavalue/DefaultEventDataValueService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/eventdatavalue/EventDataValueService.java
This PR reverts a change that uses a static Map to cache DataValues when fetching events.
This change was already applied to the branch KSOIDC_2.34, but never ported to 2.34.
backport from: d5c4119d67638d07f8d801c781a3f7f0c525f369
> [2.34] fix: use non static cache for DataElements on Event fetching

- dhis-2/dhis-support/dhis-support-system/src/main/resources/push-analysis-main-html.vm
This prevents push analysis pivot tables from being rendered (incorrectly) as an image:
See [DHIS2-10166](https://jira.dhis2.org/browse/DHIS2-10166)
For reference, here is where the HTML generation logic splits - the first branch renders HTML while the second renders the url of a generated image https://github.com/dhis2/dhis2-core/blob/757b281ac024a43da56dc3f6b6bc477fe7f0ca82/dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/DefaultPushAnalysisService.java#L447-L450
> fix(push-analysis): [2.34] don't render pivot table visualization as img (DHIS2-10166)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessor.java
Correct the javadoc for the class that detects duplicate relationships in a Tracker import payload
> fix: amend javadoc for relationship import validation

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessorTest.java
Fixes a bug during Tracker Import relationship "deduplication", where the wrong "bidirectional" property was checked upon validation.
The correct property to check is on the `RelationshipType` object, rather than the `Relationship` object.
ref: DHIS2-9965
> fix: use 'bidirectional' property from RelationshipType on validation

- dhis-2/dhis-support/dhis-support-system/src/main/resources/push-analysis-main-html.vm
Corrected fix for #6972, the visualization type is not the same as the dashboard item type (we should definitely simplify this distinction)
After this change:
> fix(push-analysis): [2.34] correct conditional when checking visualization type (DHIS2-10166)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/service/DefaultTrackerImportAccessManager.java
Make sures that during Event write access validation, the Event's Program is correctly
extracted from the pre-heat, using the Program UID associated to the Event's declared Program Stage.
This resolves an issue with importing an Event using `programIdScheme=ATTRIBUTE`.
ref: DHIS2-9895
> fix: get Program from preheat using Program from ProgramStage

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramOrgUnitSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContext.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContextLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramOrgUnitCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramOrgUnitSupplierTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplierTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramOrgUnitCheckTest.java
This PR modifies the Event import code that was refactored in version 2.35 and optimmizes the check to verify if an Event's Org Unit is part of the Event's Program Org Units List.
Programs are now stored in the `WorkContext` without the "link" to Organization Units.
A new, dedicated data structure is created to map Program to Org Units - using only Org Units effectively specified in the payload.
This change is required to minimize memory allocation and SQL exec time when a Program has a very large (> 10.000) Org Units associated to it.
ref: DHIS2-10139
* fix: do not use immutable list if you are going to add stuff to it!
(cherry picked from commit fb390e24a39efb3e206bd995b5f9d964ede0cb33)
> [2.35] perf: reduce number of Org Units fetched from DB on Tracker Import

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
This change will allow data elements to be sorted as expected. The query below illustrates how it works.
`/api/29/analytics/enrollments/query/IpHINAT79UW.json?dimension=pe:LAST_12_MONTHS&dimension=ou:ImspTQPwCqd&dimension=ZzYYXq4fJie.sj3j9Hwc7so&dimension=ZzYYXq4fJie.lNNb3truQoi&stage=ZzYYXq4fJie&displayProperty=NAME&outputType=ENROLLMENT&desc=ZzYYXq4fJie.sj3j9Hwc7so&pageSize=100&page=1`
> fix: DHIS2-9839: Data elements sorting in event report.

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/DhisFlyway.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
Externalized config to optionally be able to run flyway repair before the migration. This is useful when you have manually fixed the db/script inconsistencies and want flyway to update the flyway_schema_history to realign the checksums. Instead of manually updating the flyway_schema_history ourselves (which is risky), simply enabling "flyway.repair_before_migration=true" in dhis.conf will initiate a flyway repair before the actual migration. [Flyway Repair](https://flywaydb.org/documentation/command/repair)
> feat: [TECH-519] add a configuration for enabling repair before flyway migration (master)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/CategoryComboMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ClassBasedSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceTest.java
Preheat defaults were retrieved from the DB and they didn't pass through the process of mapping present in the preheat.
I added the default to the TrackerIdentifierCollector, so they can go through the same process as all the other metadata and have all the needed fields correctly initialised
> fix: Fix lazy exception for default category combo

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java
NPE is raised while importing metadata. The problem seems to be with OptionSet. Only non-null options in the OptionSet will be processed.
> fix: (2.34) NPE in metadata import [DHIS2-10200]

- dhis-2/build-dev.sh
- docker/tomcat-alpine/Dockerfile
- docker/tomcat-debian/Dockerfile
This PR adds `fontconfig` to both `debian` and `alpine` Tomcat images, and also `ttf-dejavu` to `alpine`.  These packages are required for the Push Analysis feature to work.
**NB** - the `8.0-jre8-slim` image appears to be broken, we should probably remove it (in a separate PR)
> fix: add fontconfig to Tomcat Docker images [2.34]

- dhis-2/pom.xml
The fix is in dhis2-antlr-expression-parser at https://github.com/dhis2/dhis2-antlr-expression-parser/commit/0559a04ade0568c4304b9dc47e5e1fadd5a08915. This PR merely references the new version. It fixes all the test cases referenced in https://jira.dhis2.org/browse/DHIS2-10227. (See the comment there.)
> fix: ANTLR 'Expresion is empty' DHIS2-10227

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/DataValueUpdatedEvent.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationListener.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/PublishEventPostProcessor.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineListener.java
Backport JIRA #DHIS2-9935 to 2.35
PR fixes the problem with notification events. The event will be invoked in case of insert/update, previously it was only being done for updates.
The change includes the addition of fallbackExecution = true flag in @TransactionalEventListener annotation to make sure the event is invoked even if there is no transaction running.
> fix: (2.35) send message rule action when stage is part of registration

- dhis-2/pom.xml
Backporting JIRA #DHIS2-10227 to 2.34
> fix: ANTLR 'Expression is empty' DHIS2-10227

- docker/tomcat-alpine/Dockerfile
- docker/tomcat-debian/Dockerfile
Forward-port of #7052 
Error before this fix
> fix(docker): (2.35) add fontconfig to Tomcat Docker images

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ClassBasedSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/AbstractSchemaStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/EnrollmentActionRule.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/EventActionRule.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AbstractRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/SetMandatoryFieldValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationConfig.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/AssignValueImplementerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/SetMandatoryFieldValidatorTest.java
- If the assigned value is the same as the value in the payload, not error is returned
- Put in the IdentifierCollector also the uids of data elements and attributes linked to program rules
- Fix preheat cache for wildcard entities. It was always empty after the TTL
- Run data values and attribute validators after rule engine has run
> fix: fix program rule assign value implementer [DHIS2-10098]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/AttributeValueConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AbstractRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/ValidationUtils.java
- Passing the TEAs to the context to be built and sent to rule engine
- Fixing rule engine warning message
- Creating the attribute converter service
> fix: [DHIS2-10293] Fix program rules linked to tracked entity attributes

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vCompletedDate.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vCreationDate.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
PR fix this issue by providing the correct reporting end date.
> fix: Wrong result when using V{creation_date} with analytics boundaries [DHIS2-10304]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vCompletedDate.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vCreationDate.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
> fix: (2.35) Wrong result when using V{creation_date} with analytics boundaries [DHIS2-10304]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
Write a unit test for the firstname-surname/email/username query, including substring matching on firstname,space,lastname as requested by @larshelge
> test: Search users across first + last names

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
use fetch for usercredentials. one to one relation with users. so in listing its more often beneficial to prefetch them to avoid the n+1 problem.
> fix: performance improvent for users api when filtering with userCredentials.username (2.36)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/base/dhis2_base_schema.sql
Commit https://github.com/dhis2/dhis2-core/commit/cfdc0aaad13324e40e609c8f76a8e6f4b2838669 for DHIS2-9081 mistakenly added to dhis2_base_schema.sql the new column dataset.openperiodsaftercoenddate. That should not have been done because dhis2_base_schema.sql should be frozen at the 2.30 db schema. This PR is to undo the mistake.
> fix: remove column from dhis2_base_schema

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vEnrollmentStatus.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
The enrollment status column name is different in enrollment and event analytics tables. This needs to be aligned when using event analytics.
> fix: Use correct column name for enrollment_status [DHIS2-10346]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryIntegrationTest.java
The validation of "enrollment already exist" check ignores if the same enrollment is being updated. This makes it impossible to update an enrollment where only one active enrollment is allowed.
> fix: [DHIS2-10208] enrollment not updated due to validation (2.36)

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
Adds a new DHIS 2 config property `system.program_rule.server_execution` = `on | off`. Default value is `on` and there is no change in current behavior.
When facing high CPU usage in production, server-side program rules are sometimes the main cause. From a sysadmin perspective it is useful to be able to quickly disable server-side program rules without doing invasive changes to the metadata.
> feat: Config property for disabling server-side program rules [DHIS2-10380]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java
We strongly believe that a recent spring update led to more strict requirements when it comes to RESTful APIs.
As a consequence methods of type POST which do not return any value and neither set a HTTP response code where no longer completing but instead cause a redirect which usually then failed returning a 404. 
This PR fixes this situation by explicitly setting the `NO_CONTENT` HTTP status code for methods returning `void` which were not setting the code in an apparent way.
I checked all methods matching the structural pattern (which are about 150):
```
@org.springframework.web.bind.annotation.RequestMapping (method = org.springframework.web.bind.annotation.RequestMethod.POST)
void 
```
I explicitly tested the endpoint that was …
> fix: set HTTP response code for POST methods not returning anything [DHIS2-10010]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobConfigurationService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
As far as I can tell the issue was unstable update of the `jobStatus` in relation to the `enabled` property.
When testing this the outcome was unpredictable. Sometimes the updated did the expected change. Sometimes it did not.
I'd say it came done to the `refreshScheduling` method lacking the `@Transactional` annotation which made the write unreliable.
I also removed everything from `postPatchEntity` except the call to `refreshScheduling` since that method already covered the logic duplicated in `postPatchEntity`. While the removed `addJobConfiguration` call would allow this to work with so far not existing entities this should never apply to a PATCH so I deemed this unnecessary as well.
Followed the instructions given in TECH-413
1. …
> fix: update job status consistently with enabled flag [TECH-413]

- dhis-2/pom.xml
Before this fix it was not longer possible to use `"mvn clean install -DSkipTests "` due to the recent change in profiles to accommodate different profiles for jdk11 and jdk8. Instead if skipping tests it would execute tests since the default profile activated here "default" overrides the skipTest property, since it is defined as "false" in the profile properties. To fix this we make a SkipTests variable and a Maven property.
> chore: Restore the possibility to use -DSkipTests

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
First step cleanup of creating and switching users in spring based tests.
The changes remove the duplication that was present.
This is not 100% exactly the same code running since some of the copies failed to be thorough which they all will be now.
This is merely a preparation to later improve the `CurrentUserService` situation in tests which might then make use of the methods updated here.
> chore: cleanup switching users in integration tests

- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/DefaultValidationRuleService.java
As a response to #7260 and #7261.
> fix: only use read-only transactions reading access to validation rules [DHIS2-7260]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/UniqueAttributesSupplier.java
While finding unique values in the preheater, we did not consider multiple tracked entities could share the same attributes, but with different values. This fix will convert the stream to using the uid of the attributes and only get the distinct values before collection.
> fix: fixes an issue where we counted the same attribute multiple times during preheat

- dhis-2/dhis-e2e-test/docker-compose.e2e.yml
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/helpers/config/Config.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/extensions/MetadataSetupExtension.java
In order to save time, I disabled the cleanup on CI. We don't catch errors that happen during the deletion of created entities and there's no harm in leaving the test database since we dispose of the docker container.
> ci: disable cleanup on ci

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceByTeiSupplier.java
idToEventMap was mapping 1-1 between tei-program and event, but in reality you can have multiple events for the same tei and program. The mapping is now between the key, tei-program and a list of events that match the combination.
Instead of mapping the result for 1 event, all events that match the key will now map to the PI.
Updated a wrong .getUid with .getEvent. At this point, .getUid will always return null, while getEvent will always return a uid.
> fix: fixed several minor issues with preheating enrollments for events with missing reference

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/ReferenceTrackerEntity.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/TrackerEntityInstanceStrategyTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventDefaultEnrollmentPreProcessorTest.java
In the Preheat we are loading from the DB all the metadata and data linked to the payload.
In the Preheat we also need to know if an entity is linked to another entity in the payload, this information is used to perform some validations.
We were creating a `referenceTree`, with the structure of entities that are presents in the payload but not in the DB, while populating the Preheat, but this wasn't always correct depending on the order of the loading.
The solution was to create a flat reference map and at the end of the loading mount the correct structure 
TEI -> Enrollment -> Event
DHIS2-10459
> fix: [DHIS2-10459] Fix reference structure in Preheat used in the validation stage

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/EmailMessageSender.java
Add `server.base.url` in password reminder emails.
> fix: Add reference to base URL in password reminder email [DHIS2-10416]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_29__Add_indexes_in_relationshipitem_and_programinstance_tables.sql
Joining entity tables (trackedentityinstance, programinstance, programstageinstance, relationshipitem) is the most common join in our queries. Having indexes on the column used to perform the joining on these tables will improve the performance of such queries.
- trackedentityinstance table has no foreign key, so no index is needed here
- programinstance table was missing an index on trackedentityinstanceid column
- programstageinstance table already has an index on programinstanceid column
- relationshipitem table is missing indexes on all 3 foreign key columns
> perf: Add indexes on relationshipitem and programinstance tables [DHIS2-10479]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/DefaultAdminUserPopulator.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global_uk.properties
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/cluster/ClusterController.java
Add new authority "F_VIEW_SERVER_INFO" . At the moment only used for `/api/cluster/leader`  but can be used for all server/infra related APIs in the future.
> fix: [DHIS2-10257] add new authority F_VIEW_SERVER_INFO for cluster leader api

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/AppsSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java
Missed this during the 2.35 release push, forward-port of #6111 and #6175
> feat: require bundled app overrides to be configured with the coreApp flag in the manifest (DHIS2-9555)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/UnregisteredSMSListener.java
Unregistered SMS command parser fails to parse the command. The format applied to other commands cannot be applied to Unregistered parser.
> fix: (2.35) Parse unregistered SMS command with simple text [DHIS2-10502]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRule.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceProgramTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_16__Set_unique_name_property_for_program_rules.sql
Program uniqueness shouldn't be enforced throughout the whole database, rather only under the same program.
This PR reverts the hook deleted in the previous version (the one in charge validating the constraint) and deletes the database constraint.
> fix: Program rule names are unique only within the same program [TECH-531]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
Programs endpoint was not using the restrictToCaptureScope for the db level filtering.
> fix: [DHIS2-10398] program filter restrictToCapture scope

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
There was a minor bug in the implementation of DHIS2-9555 which prevented the server from checking the value of the bundled parameter against the only valid values true and false.
This has been solved in 2.36 in #7352 but needs to be backported to 2.35 and tested on 2.36
> fix: check bundled instead of isBundled when validating query [DHIS2-10497]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastatistics/AggregatedStatistics.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastatistics/DataStatistics.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastatistics/DataStatisticsEventType.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/datastatistics/hibernate/DataStatistics.hbm.xml
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/hibernate/HibernateDataStatisticsStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/datastatistics/DataStatisticsServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/datastatistics/DataStatisticsStoreTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_30__Add_passivedashboardviews_column_to_datastatistics_table.sql
[DHIS2-10447](https://jira.dhis2.org/browse/DHIS2-10447) is the backend work for [DHIS2-7016](https://jira.dhis2.org/browse/DHIS2-7016)
This is to support a new data statistics event type PASSIVE_DASHBOARD_VIEW, that is recorded from the front end when a dashboard is shown by default (because is the user's landing page). This is persisted as a separate usage statistics count in the database, and is returned to the frontend as part of the AggregatedStatistics object.
A new system setting key keyCountPassiveDashboardViewsInUsageAnalytics can tell the Usage Analytics app whether to include the passive dashboard views together with the regular dashboard views, when presenting them to the user.
So the backend work is to:
- Add a new Data Statistics Event Type called PASSIVE_DASHBOARD_VIEW
- …
> feat: Optionally report passive dashboard views

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/AnalyticsCache.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultAggregateAccessManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/DefaultOrganisationUnitService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultCurrentUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserSettingService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JacksonEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/util/InputUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheBuilderProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheBuilderProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/ExtendedCacheBuilder.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/TokenController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/ResponseHandler.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/ResponseHandlerTest.java
Based on a discussion with @larshelge this PR removes the unused value type parameter in the cache API.
As the `CacheBuilderProvider#newCacheBuilder` with two types was unused and since the type arguments got removed `CacheBuilderProvider` now only has a single method.
To lower the risk of regions being accidentally reused a `Region` enum was added.
> chore: remove unused parameters from cache API [TECH-532]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CrudControllerAdvice.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
For both the get teis api
`api/trackedEntityInstances`
`api/tracker/trackedEntities` 
when large number of teis is returned in the response then the api crashes. This happens when "skipPaging=true" in the request AND the scope is very high that it returns a high number (say in the order of 10,000s). This is because of a refactoring done to improve performance. In the refactored mechanism, we first fetch the ids first and then the actual entities using those ids. If skipPaging is not forced, then default paging is used and the number of results is always small.
The refactoring means that these 10,000 ids are first fetched and then a humongous hql query is constructed by concatenating a clause like "where id in [comma separated string of the 10000 ids] and then a further concatenation to …
> fix: [DHIS2-10375] I/O error when large number of tei is fetched from get teis APis

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/TrackerApiResponse.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/relationships/RelationshipsTests.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerImportReportFinalizer.java
1. global (root) import stats were not correct when ignoring relationships.
2. ignored relationships were added to objectReport which was wrong.
This PR fixes these 2 issues
> fix: ignored entries are also returned in global stats [DHIS2-10390]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageMapper.java
Incorrect mapping of Sharing object in Program linked to a Program Stage was throwing a LazyInitializationException when validating Ownership
> fix: [DHIS2-10522] Fix the mapping for program stage and program

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupInfoService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupInfoStore.java
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserGroupInfoService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserGroupInfoInfoStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserGroupInfoStoreTest.java
https://jira.dhis2.org/browse/DHIS2-10342
Issue: 
- in a database with userGroups have 200k members, the aclService.checkSharingPermission() is very slow.
The reason is  that we used hibernate lazy to load all userGroup.members and check if given user is in that list. 
This causes n+1 issue and also load the whole user table to memory many times. 
Fix: 
- This PR add a new class `UserGroupInfoStore` to do the userGroup is member check in database. 
We can't use `UserGroupStore` for this because it has dependency on `AclService` which in result will introduce circular dependency issue.
- A cache is also used to store the result of the check above for each combination userGroup-user
This fix need to be forward port to 2.35
a POST request to api/trackedEntityInstance take 33 seconds  to …
> fix: (2.34) acl service performance with userGroup.members()

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/CollectionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/DefaultCollectionService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
Prevents creation, update or deletion of system jobs by checking the `configuable` flag in the pre-action hooks.
Background: A system job is a a `JobConfiguration` where `configurable` property is `false`.
Changes to the abstract controller that could be considered fixes (and cleanup):
* Since collection item patch endpoints of abstract controller did not have pre-post hooks two new hooks were added:
* `preUpdateItems`: invoked before any update to a collection of a resource target object
* `postUpdateItems`: invoked after any update to a collection of a resource target object
* The `updateObjectProperty` endpoint was missing a call to `prePatchEntity` which was added.
* The `Patch` based property update return HTTP 404 in case neither JSON nor XML are send instead of failing with a NPE. …
> fix: prevent create/update/delete of system jobs [DHIS2-10505]

- dhis-2/dhis-api/pom.xml
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/pom.xml
The previous default Maven repository, "maven.java.net" is no longer working because of an expired SSL certificate.
> chore: Change central Maven repository

- dhis-2/pom.xml
The previous default Maven repo. maven.java.net has expired SSL certificates.
> chore: Change central maven repo.

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
The AppOverrideFilter incorrectly tested `request.getRequestURI()` which does not exclude a custom context path, if one is specified.  This change compares `request.getServletPath()` instead to ensure that the path tested is the same as is processed by Tomcat.
We could likely strip the context path from `getRequestURI` instead, but since these are not servlets but rather served files this appears to work well.
This issue is present in 2.35.1 and so should also be back-ported in 2.35.2 (#7421).
> fix: check servletPath instead of requestURI to support custom context paths [DHIS2-10519]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
https://jira.dhis2.org/browse/DHIS2-8262
Issue: translation is not saved in first POST request
Fix: 
- Remove the code for creating new HashSet in BaseIdentifiableObject.getTranslations()
- Set the whole input set of translations into the object instead of calling .add() method.
> fix: translation is not saved in first time

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
This allows an `app_hub_id` to be specified in an application's `webapp.manifest`, which will then be exposed through the `/api/apps` endpoint.  This allows us to uniquely identify apps on the App Hub to check for and apply updates when they are published
Demo here - https://d2.winged.tech/dev/api/apps
> feat: expose app_hub_id from application manifest in apps api [DHIS2-10565]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
https://jira.dhis2.org/browse/DHIS2-10401
This PR fix the Issue: sharing predicate check is not applied for count query in `JpaCriteriaQueryEngine`
> fix: paging issue with count query in JpaCriteriaQueryEngine

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
Backport of #7434 - this is technically a very small non-breaking feature, but it's important to support continuous delivery of applications to 2.35 servers
> feat: (2.35) expose app_hub_id from application manifest in apps api [DHIS2-10565]

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
Backport of #7420 (important for 2.35.2)
> fix: (2.35) check servletPath instead of requestURI to support custom context paths [DHIS2-10519]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/OAuth2ConfirmAccessController.java
- dhis-2/dhis-web/dhis-web-api/src/main/resources/confirm_access.vm
- dhis-2/dhis-web/dhis-web-api/src/main/resources/error.vm
This fix restores the OAuth2 authorization_code flow in DHIS2 described in the issue: [https://jira.dhis2.org/browse/DHIS2-10169](https://jira.dhis2.org/browse/DHIS2-10169)
Before this fix, when doing the authorization_code flow the server would not show the approval or deny access page after successfully logging in.
We are adding back the approval & error html pages used in 2.34.
The authorization_code should now work as described in the documentation: [https://docs.dhis2.org/master/en/developer/html/webapi_authentication.html#1.2.3.4](https://docs.dhis2.org/master/en/developer/html/webapi_authentication.html#1.2.3.4)
There exists no automatic tests for the authorization_code flow. This probably needs to be implemented as an end-to-end test due to browser based multiple page redirecting …
> fix: Repair broken OAuth2 authorization_code flow

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/sharing/SharingUserAccess.java
See [DHIS2-7396](https://jira.dhis2.org/browse/DHIS2-7396).
It was decided that the best way to implement this is to have the backend return a new field username in response to /api/sharing/search. The frontend can then display the username as it wants.
> feat: Add username to /api/sharing/search results [DHIS2-7396]

- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionAnalyticsDataFetcherTest.java
This is an additional commit from [DHIS2-9317](https://jira.dhis2.org/browse/DHIS2-9317).
The checks were run on [pull/7214](https://github.com/dhis2/dhis2-core/pull/7214) from [DHIS2-9317](https://jira.dhis2.org/browse/DHIS2-9317) (feat: Speed predictor datavalue fetching) 2 days before it was merged into trunk. During that time, commit [07369c2](https://github.com/dhis2/dhis2-core/commit/03c1ed23e1ba4ab2eb79afa4e8ce8f3d3d3d326f) changed a constructor for GridHeader to infer valueType rather than requiring it in the constructor. The DHIS2-9317 code had the obsolete GridHeader argument. This PR fixes that. (The changes weren't in the same classes, so git didn't have any conflict.)
> fix: resolve conflict w/PR 7453 DHIS2-9317

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/entry.fileresource.js
- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/entry.js
See [DHIS2-7757](https://jira.dhis2.org/browse/DHIS2-7757). This PR adds the endpoint POST `/dataValues/file` to allow the frontend to post a file data value along with its file contents in a single request. It also changes the data entry app to use this new endpoint.
This avoids the problem of a file being uploaded without the _dataValue_ if the network connection fails between the two requests. It will also allow checking in the future of file size and type if they are restricted by the data element, to avoid storing a file with disallowed properties.
The logic to save files in _FileResourceController_ was moved to _FileResourceUtils_, where it can be called from both the _FileResourceController_ and the _DataValueController_. Actually, a near-identical copy of this logic already …
> feat: Combined datavalue/file endpoint DHIS2-7757

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionAnalyticsDataFetcherTest.java
**Issue**
When using api/trackedEntityInstances. there are scenarios where the server returned less than the pageSize number of records even though totalcount was above the pageSize. The reason was when the tei has multiple enrollments or events that match the criteria/filter provided in the params, the left join results in duplicate rows for tei and these duplicates results in returning lesser actual tei objects than the pageSize.
**Fix**
Switched from using hql to sql, and used row_number() function with groupby to eliminate any duplicate teiIds along with using order by to maintain the original ordering as per the query params.
> fix: [DHIS2-10351] incorrect result pageSize in case of multiple enrollment/event match criteria (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
Quick fix for Translations app crashed if the property `translations` isn't returned in the response. 
- We already defined empty set for this `protected Set<Translation> translations = new HashSet<>();`
- I guess because this is a jsonb column, if the its null in database then jackson will ignore it while deserializes the jsonb object.
> fix: Translations app crashed if translations isn't included in response

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/DefaultReservedValueServiceTest.java
After a previous change, that somehow got through checks, a different error message would be triggered for these tests. This PR will update to the new expected error message.
> fix: Fix error message expected in integration tests

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/PasswordValidationError.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/PasswordValidationResult.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultPasswordValidationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DigitPatternValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/PasswordDictionaryValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/PasswordHistoryValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/PasswordLengthValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/PasswordMandatoryValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/SpecialCharacterValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UpperCasePatternValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserParameterValidationRule.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/PasswordValidationRuleTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/PasswordValidationServiceTest.java
Testing the Web API in #7475 I got problems testing the API since the password validation was not deterministic producing different errors on different environments in case multiple violations were present.
This PR makes the password validation deterministic.
The `PasswordValidationRule` implementations are no longer spring `@Component`s. Instead they are composed explicitly to a sequence in the constructor of `DefaultPasswordValidationService`.
With the order being deterministic rules later in the sequence no longer have to check if mandatory parameters  are present. 
On top I did a bit of code style cleanup ;)
* extracted enum for the error codes and messages
* extracted new rule `PasswordMandatoryValidationRule` to explicitly handle the mandatory input value check
* used the enum in …
> chore: make password validation deterministic [TECH-549]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/BaseIdentifiableObject_.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/Translatable.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/TranslatablePropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/AnnotationUtils.java
Issue: If an object doesn't have `translations` jsonb column in database,  properties marked with `@Translatable` have translatable = true
Fix: Add a check to make sure object doesn't mapped with `translations` column in DB won't have any properties with `translatable=true`
> fix: translatable=true  even if object doesn't have translations column

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/calendar/DefaultCalendarService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultDataElementService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramStageSectionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultCurrentUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserSettingService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceCleanUpJobTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserSettingServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceExportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceAttributesTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/dashboard/impl/DefaultDashboardService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultMergeService.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingStore.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/hibernate/HibernateSystemSettingStore.java
PR addresses sonar warnings about the consistent use of `@Transactional`.
There was an issue with one of the tests because it would load and manipulate an audit entry which hibernate lazily would update (I guess this is another thing we should look into) and this lazy update would become part of the read-only transaction started to read the system setting which would then fail to perform the update. Solution is to explicitly update the audit entry. I decided to do this via store directly so that the service layer at least would not allow to update audit entries.
> fix: consistent use of @Transactional [TECH-546]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java
This will bring back the performance and filtering to the same level as other endpoints.
This was already merged in 2.34 and 2.35. It's being "forward ported" to master.
> fix: Filtering issue for ReportTable and Chart

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/NormalizedOutlierMethod.java
The existing constant name needs to be replaced by the new name.
> fix: Rename normalized outlier enum constant

- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/json/JsonResponse.java
I skipped over https://dzone.com/articles/correct-reflective-access-to-interface-default-methods too fast and missed that the approach shown first wasn't working in some cases. This PR now uses the approach that is the working one for java 8. 
Tested locally with java 8 that the tests previously failing now pass. As the PR builder does not use java 8 it should be no surprise that it passes.
> fix: invoke default methods for proxy via method handles in java 8 [TECH-549]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/AnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/mock/MockAnalyticsService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
Clear application cache command in the Data Administration app was clearing just a very small subset of the caches that we have in the system.
Now that we have all the caches in the CacheProvider it is easy to centralise that command and clear all the caches.
> fix: Fix clear cache chore to clear all caches created in CacheProvider

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryType.java
- dhis-2/dhis-support/dhis-support-hibernate/src/test/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryTypeTest.java
Jsonb columns using generics (like `DeviceTypeRenderMap`) failed to return equals=true even when untouched, and though were marked as dirty by Hibernate even immediately after `save()`.
This caused some unwanted and unnecessary updates for each explicit or implicit `flush()`, which in some cases led to unexpected behaviors/bugs.
This patch still relies at first on `equals()`, and only as a last chance to compare the serialized json version of objects to ensure they are unchanged.
Most likely this bug also affects newer versions, so if this patch is accepted I'll port it to 2.34/2.35/2.36/dev
> fix: content-aware jsonb equals() implementation [DHIS2-10622]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/DataElementMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityAttributeMapper.java
[DHIS2-10452](https://jira.dhis2.org/browse/DHIS2-10452)
After feature has been added, during tests validation fails. Apparently hibernate is not loading options values
- Work Done
[x] Adds options to jackson mapper. Previously only optionSet was added
> fix: Validation for values with option sets [DHIS2-10452] - adds options to mapper

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonError.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/json/JsonResponse.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
The `PUT` JSON object operation in generic CRUD controller does replace (clear) the translations even when using the `skipTranslation=true` parameter.
The `skipTranslation` flag was not forwarded to `MergeParams` performing the merge between existing and update object.
This did however not fix the issue because somewhere during or because of the preheat the translations get lost for the persisted object so that at the point of the merge both the updating and the persisted object do not have translations.
I investigated but this feels like a bigger issue in the preheat, a box I did not want to open but that should be opened in a dedicated ticket.
Instead I used a workaround in the controller for the `PUT` operation. 
When translations should be skipped the persisted object is loaded and …
> fix: keep translations during PUT json object when 'skipTranslation=true' is set [DHIS2-10660]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
This issue is related to List gaps containig null elements. This was already fixed upstream. I'm bringing the same fix to 2.33
> fix: DHIS2-10646: Backport fix for known NPE

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
This PR is a first attempt to reduce the impact of the cache on the JVM Heap.
A configuration has been created to tune the size of the caches in the system. For now I am guessing a default value, I think that when we have time we should understand how much memory space on the heap the caches are actually using and having this configuration based on the size of the memory used for the JVM.
For example, if the system runs with a JVM with 10G the value would be 10 and so on.
To arrive there we will need to perform some tests that will require time that at the moment we don't have before the hard freeze of the 2.36.
Any suggestion for a better name for the configuration is appreciated.
> perf: Create a configuration to correctly size the caches [DHIS2-10629]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataitem/DataItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/DataElementQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/DataSetQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/IndicatorQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramAttributeQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramIndicatorQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramStageDataElementQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/FilteringStatement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/NameTranslationStatement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/OrderingStatement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/QueryParam.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/shared/StatementUtil.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataitem/query/shared/NameTranslationStatementTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataitem/query/shared/OrderingStatementTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/DataItemQueryController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/Filter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/Order.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/helper/FilteringHelper.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/validator/OrderValidator.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataitem/validator/OrderValidatorTest.java
Now, shortName and displayShortName are supported in the URL filtering and also returned as part of the /dataItems response.
Some front-end applications relly on those attributes, so we had to support them as well.
With these changes, we will be able to filter and order by shortName and displayShortName.
**_This is a backport from master._**
> fix: DHIS2-9934: Adding correct support for shortName and displayShortname

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserGroupAccess.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserGroupService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
This is to fix the e2e test error `[ERROR]   TrackedEntityInstanceAclReadTests.before:78->setupUser:111->setupAccessMap:137->lambda$setupAccessMap$1:144 » IllegalState`
Issue: 
Hibernate query cache doesn't support native SQL
Cache for this query throw error `aliases expected length is 0; actual length is 1`
`String sql = "select concat(firstname, ' ', surname) from userinfo where uid =:uid";`
Fixed: 
- Turn off the query cache for that for now. The result is already cached with `Cache<String> userDisplayNameCache;` in `DefaultUserService` so should be fine.
- Also added few minor fixes for the legacy access objects to make it work with the e2e tests
*** Same fix is merged to 2.36 and all e2e tests passed there. https://github.com/dhis2/dhis2-core/pull/7578
There is still an e2e test …
> fix: hibernate cache error for user.getDisplayName

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
A silly mistake on cast precedence was making all the cache to have size 1.
> fix: Correctly cast the size of the caches in the cache provider

- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java
This is an additional commit for [DHIS2-9317](https://jira.dhis2.org/browse/DHIS2-9317), extending some of the timeouts and sleep times in PredictionDataValueFetcherTest that were causing problems in slow CI environments:
- In _testTimeoutWaitingForProducer_ and _testTimeoutWaitingForConsumer_, increase the sleep time from 3 ms to 100 ms. The only requirement for this time is that the sleeping thread must sleep longer than the other thread, which is polling for a semaphore with a timeout of 2 ms. In tests on faster servers the 2 ms timeout always timed out before the 3 second sleep, but on a CI server it sometimes did not. Hopefully the 2 ms timeout will always time out before the 100 ms sleep. This will add 97 ms to each of these 2 tests.
- In _waitForTheOtherThread_, increase the sleep …
> fix: Prediction test timeouts for CI [DHIS2-9317]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonArray.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonCollection.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonDocument.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonNode.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonObject.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonResponse.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonValue.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonPath.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/JsonDocumentTest.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/JsonResponseTest.java
It dawned on me that we can now make the `JsonNode` available in `JsonValue` giving access to the actual document content during tests and also making for a nicer debugging experience. So this PR moves the `JsonNode` interface to a top level file and improves the consistency of the semantics and `toString()` as well as covering this with more tests.
This PR changes test code only and does not change any application code.
> test: make JsonNode available in JsonValue access abstraction

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/CatOptionComboStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/CatOptionStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/OrgUnitStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/ProgramStageStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/ProgramStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/RelationshipTypeStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/StrategyFor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/TrackedEntityTypeStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/AbstractSchemaStrategyCachingTest.java
After some discussion with Markus and my own evaluations, we set a specific capacity for each cache we use in the tracker importer preheat.
The default was also lowered, just so we don't end up in a bad situation down the line.
> fix: Adjust preheat caches for new tracker importer

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_34__Add_index_in_tracker_tables.sql
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
Forward port of grid query sql rewrite. 
Additional change in 2.36 is that, we use the same sql to fetch the trackedentityinstanceid (the primary key) for the api/trackedEntityInstance and the api/tracker/trackedEntity endpoints as well.
> perf: rewrite TEI get SQL for better performance (2.36)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
* Add specific cache capacity for all preheat caches. lower the default cache capacity
* fix: Increase pool-size of notifications from 100 to 500
* Revert "Add specific cache capacity for all preheat caches. lower the default cache capacity"
This reverts commit 213beb8402b1c70774f755cfc5785b4646457c12.
* fix: Fixed failing test
(cherry picked from commit 0899f347ea64fb0a7e7de130eb2e54a649329f0e)
> fix: Increase notification pool-size (#7609)

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/acl/metadata.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
Program OR TrackedEntityType OR a list of trackedEntityInstances uids has to be provided when querying for TEIs. 
Without any of the above 3, the request will fail. This is done to prevent fetching huge amounts of teis by simply providing ouMode=ACCESSIBLE.
> fix: validate whether tei query params has either program or tet specified (2.37)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
Ordering parameter was ignored if it wasnt added to the "attribute" parameter. This parameter is not required for the api/trackedEntityInstances api. Added the fix to bypass this check.
> fix: ordering param is ignored if its not provided in attribute param (2.36.0)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationMapTest.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
In the current implementation, the Notifier was not acting as a FIFO (First in First out), but when the max size was reached an almost random job was removed.
Fixing this also should have fixed the intermittent test problem.
Sometimes test testInsertingNotificationsInSameJobConcurrently in NotifierTest is failing.
The reason seems to be that copying a list is not ThreadSafe, so if elements are added while copying, it can throw an ArrayOutOfBoundException.
> fix: Fix InMemoryNotifier race condition and job deletion [DHIS2-10678]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_32__Add_index_in_tracker_tables.sql
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
this is a forward port of the tracker tei get sql rewrite from 2.34 to 2.35.2 patch version. 
The extra change from 2.34 is that, the api/trackedEntityInstance endpoint also uses the same refactored sql.
> perf: port tracker query sql rewrite to 2.35.2

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
from 2.36 we define translation property like below 
``` @JsonProperty
@JacksonXmlProperty( namespace = DxfNamespaces.DXF_2_0 )
@Translatable( propertyName = "rangeAxisLabel" )
public String getDisplayRangeAxisLabel()
{
return getTranslation( "rangeAxisLabel", getRangeAxisLabel() );
}
```
The translationKey is the same as propertyName = rangeAxisLabel;
So we need to change translations property keys to match with version 2.36+
> fix: change translation properties key same to 2.36 [2.35]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/preprocess/ProgramStagePreProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportWithMetadataTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/create_program_stages.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/csv/events_import_code.csv
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/events-5b.csv
On 2.35 in ProgramStagePreProcessor we are checking about Idscheme but on the event we are not setting a program stage based on that.
> fix: [DHIS2-10022] event import fails idScheme=code

- dhis-2/dhis-web/pom.xml
Disabling of .war file compression was accidentally committed, this commit re-enables the compression.
> chore: Re-enable .war file compression

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
We have one service that is in prototype scope using a cache which means it calls the create method more then just once.
Fixing this on the caller side had a tendency to cascade so I thought I just let the caller call the create method multiple times but the provider makes sure that for each region this is still the same `Cache` instance.
> fix: ensure each cache region is only created once

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonArray.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonCollection.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonMultiMap.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonObject.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonValue.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/JsonResponseTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithJwtTokenAuthTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebClient.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/security/JwtBearerTokenTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/WebClientUtils.java
PR adds 2 small additions to the  REST controller testing toolkit:
1. adds header support (which allowed to handle JWT tokens through standard API)
2. adds `JsonMultiMap` as a way to do `JsonMap<JsonList<E>>`
Note that this PR only changes tests and test support code. It does not change any application code.
I had an idea how to make the REST controller testing toolkit more flexible and support the JWT token case that so far was solved as an extended API. The varargs version of the HTTP methods `GET`, `POST` etcetera now allows to use a mix of arguments that should be replaced in the URL pattern and arguments that configure the HTTP request. To distinguish the two a marker interface `RequestComponent` was introduced which is implemented by `Body` and `Header` classes. This now allows …
> test: Header support for WebClient API and JsonMultiMaps

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/acl/metadata.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
Reverts the mandatory requirement of specifying **programs**  or **trackedEntityType**  when using the api/trackedEntityInstances endpoint,
> fix: revert tet program requirement for get teis api (2.36.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/CacheInfo.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/GenericSizeof.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/Sizeof.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/cache/SizeofTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CappedLocalCache.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheBuilderProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/ExtendedCacheBuilder.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/cache/CappedLocalCacheTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/CacheControllerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CacheController.java
This PR adds a heap memory cache implementation with eager invalidation and memory cap over all caches (here regions).
This implementation is an alternative to the existing `LocalCache` based on cache2k. 
The main purpose is to gain insight about cache usage and see if eager invalidation as implemented can solve the cache problems.
To provide a cap over all local caches the `CappedLocalCache` is not a single cache but a cache cluster containing all local `Cache`s. These are called `CacheRegion` as each implements a single `region`.
To only consume up to a certain size of the available heap memory of the JVM the cache has a cap setting.
Apart from the TTL and default value settings of the cache builder the cache ignores the other builder settings as it has its own strategy to manage cache …
> feat: adds a multi-region capped local heap cache

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/SystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AuthoritiesControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/AuthoritiesController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/AppsSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/CompositeSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/DetectingSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/ModuleSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/SchemaAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/authority/SimpleSystemAuthoritiesProvider.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/beans.xml
This PR adds a spring version of `GetSystemAuthoritiesAction`.
The URL `/api/authorities` provides the same data structure that old struts action returned. 
The struts action continues to exist so that frontend has a chance to switch. After that it can be deleted. 
The `SystemAuthoritiesProvider` needed to be moved to another module so it becomes available in spring controller. 
For test config a fixed list of only admin authorities is setup. 
> refactor: provide authorities via spring controller

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java
As we have to still support Chart and ReportTable, but behind the scenes, all rules and tables are tight to Visualization, we need to add a "special condition" in order to load the "access" for the Visualization associated with the legacy object returned (Chart or Visualization).
Otherwise, we end up with a different/invalid "access" for Chart and ReportTable.
This PR will ensure the "access" is consistent across all those three entities.
This code must be removed once we completely drop the support for Chart and ReportTable.
> fix: Fixing 'access' for charts and report tables [DHIS2-10674]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonDocument.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonNode.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonUserCredentials.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/JsonDocumentTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
This was done as part or outcome of an investigation into DHIS2-10717.
The PR adds two tests that show that `PUT`ing a user without `accountExpiry` in user credentials or with `"accountExpiry": null` this does not set the `accountExpiry` to any value but it stays null.
This needed a small addition to the `JsonNode` allowing to add members.
All changes only affect tests or test support code.
> test: adds spring controller tests for user account expiry [DHIS2-10717]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/PreheatCacheService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
I hope this will make some difference.
In the documentation of Cache2K the difference between clear and removeAll is that the latter is also calling the listeners, so I think that now the empty caches will be actually cleaned.
> fix: Properly invalidate LocalCache and add listener to invalidate Tracker Preheat cache [DHIS2-10726]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_20__Drop_legacy_sharing_tables.sql
> fix: drop legacy sharing tables with cascade [2.36.0]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
**api/trackedEntityInstances** and **api/tracker/trackedEntities**  are modified to avoid counting teis unless its necessary.
> perf: [DHIS2-10714] optimize get teis api to avoid count until its necessary (2.36.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/ProgramStageDataEntrySMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
api/trackedEntityInstances and api/tracker/trackedEntities are modified to avoid counting teis unless its necessary.
> perf: [DHIS2-10714] optimize get teis api to avoid count until its necessary (2.37)

- dhis-2/dhis-api/src/test/java/org/hisp/dhis/cache/SizeofTest.java
PR to address https://ci.dhis2.org/job/dhis2-dev/lastCompletedBuild/org.hisp.dhis$dhis-api/#showFailuresLink
The issue is that JDKs are differently implementing `String` resulting in different sizes for the object. 
So I relaxed the test and allowed for small deviations.
> fix: allow some deviation in sizeof tests for JDK differences

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetReportController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
Issue : https://jira.dhis2.org/browse/DHIS2-8869
- DataSetReportController return `@ResponseBody String`  for `api/dataSetReport/custom` endpoint
- We already set charset encoding in method `contextUtils.configureResponse( response, ContextUtils.CONTENT_TYPE_HTML, CacheStrategy.RESPECT_SYSTEM_SETTING );`
- However, this code doesn't have effect, charset return is `Content-Type: text/html;charset=iso-8859-1`
- This can be reproduced on play instances, but I can't reproduce the issue on my local which runs mac os. So I guess the operating system default charset is applied, or something else changes the charset before return to client.
Fix:
- I found that we define messageConverters in `WebMvcConfig`, so all controller response will need to go through those messageConverters before returning …
> fix: set default UTF_8 charset for StringHttpMessageConverter

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/config/jackson/JacksonObjectMapperConfigTest.java
Reason the 4 digit 'nanos in second' is special is that `DateTimeFormatter.ISO_LOCAL_DATE_TIME.format` uses 4 digits nanos of second. This might only be the case if the provided date has a non zero sub-second time part but its important nonetheless to make sure DHIS2 accepts dates there were formatted with java's `DateTimeFormatter.ISO_LOCAL_DATE_TIME`.
> feat: allow ISO date with 4 digits 'nanos in second' part

- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v36/V2_36_11__Migrate_sharings_to_jsonb.java
The sharing migration script `2.36.11` takes `owner` uid from `users` table instead of `userinfo` table.
This PR updates the migration script with correct value.
> fix: owner uid refer to userinfo table

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
Issue: 
- In `JpaCriteriaQueryEngine`  the sharing check by passed when query.isEmpty = true
> fix: add sharing check for empty query in JpaCriteriaQueryEngine

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
backport https://github.com/dhis2/dhis2-core/pull/7736
> fix: add sharing check for empty query in JpaCriteriaQueryEngine [2.36]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationMapTest.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
Came across the `NotificationMap` recently and noticed the implementation was doing several questionable things when it comes to choice of collection type and thread-safety. 
Trying to fix that cascaded a bit mainly because the proper contract for the list of notifications in this case was not `List` but `Deque`. Main reason is that we want add and remove from both start and end and that we want a concurrent implementation.
To ensure the max size limit in `NotificationMap` we now maintain a `Deque<String>` for the job UIDs with insert-order. If max size is reached the last (oldest) item from that deque is removed and that UID is used as key to remove the oldest map entry. This does not make sure the map never grows beyond the size limit as map and deque operations are independent but it …
> chore: proper thread-safety for Notifier implementation

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sharing/DefaultSharingService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityTypeAttribute.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_publicAccess_update.json
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
Issue:  https://jira.dhis2.org/browse/DHIS2-10464
- When user import sharing with old format, the import service didn't take the value from legacy `publicAccess` property in `BaseIdentifiableObject`
Fix:
- Fix the code to take values from legacy `publicAccess` property
- Also move the logics for copying values between new and old format to `SharingUtils` so later it would be easier to remove this legacy codes.
> fix: can't update publicAccess

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
AND was missing when adding the clauses for lastupdatedstart and end dates when querying teis.
> fix: [DHIS2-10764] add missing and clause when using lastupdateddate in tei query param (2.35)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
AND was missing when adding the clauses for lastupdatedstart and end dates when querying teis.
> fix: [DHIS2-10764] add missing and clause when using lastupdateddate in tei query param (2.37)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
AND was missing when adding the clauses for lastupdatedstart and end dates when querying teis.
> fix: [DHIS2-10764] add missing and clause when using lastupdateddate in tei query param (2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
> fix: add sharing check for empty query in JpaCriteriaQueryEngine [2.36.0]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
For `JobConfiguration` there is a concept of adding a default instance of job parameters when no parameters exist. This was not set during the validation stage, leading to validation failing for job configurations which would otherwise import well.
> fix: Set default job parameters when none exist for validation [DHIS2-10768]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
AND was missing when adding the clauses for lastupdatedstart and end dates when querying teis.
> fix: [DHIS2-10764] add missing and clause when using lastupdateddate in tei query param (2.36.0)

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_20__Drop_legacy_sharing_tables.sql
Flyway checksum mismatch error was being thrown even though the sql scripts seemed identical to each other. The new line or line feed character seems to have been different which caused for different checksum calculations.
> fix: checksum mismatch due to different linefeed characters

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/AppHubService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/DefaultAppHubService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppHubController.java
Closes https://jira.dhis2.org/browse/DHIS2-10767
Spring's [RestTemplate](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html) encodes the URL passed as a first argument to its `exchange` method if it is a `String`. This means that any URL query components that have been previously encoded are double encoded, resulting in incorrect queries.
By passing the requested App Hub API URL as a `URI`, this encoding does not occur.
> fix: don't encode proxied App Hub requests

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/create_user_without_createdBy.json
https://jira.dhis2.org/browse/DHIS2-6167
Issue : 
- After created a user, `UserCredentials.createdBy` is always null. 
- This is because the current code doesn't handle the case where payload doesn't include `UserCredentials.user` or `UserCredentials.createdBy`.
Fix:
- Update `UserCredentials.createdBy` = currentUser if its null.
- Also add code to always update `lastUpdatedBy` field.
- Add unit test
> fix: null userCredentials.createdBy when create user

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/ExternalMapLayer.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_38__Add_translations_column_into_externalmaplayer_table.sql
https://jira.dhis2.org/browse/DHIS2-1127
Add `translations` column to database table `externalmaplayer`
I add the flyway script to v2.34 so later I can cherry-pick this commit and backport down to 2.34.
> fix: add translations column for ExternalMapLayer

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/interceptor/I18nInterceptor.java
The I18nInterceptor class was wrongly annotated as deprecated.
It's still needed for setting the i18n translation lookup for Struts actions.
The redundant part, i.e. setting the logged-in user into the UserContext is now removed, this is now handled by the UserContextInterceptor
> chore: Remove redundant call to set user in UserContext

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/Translation.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_skipSharing.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_update_skipSharing.json
Issue : 
- Sharing & Translation objects are defined as `EmbeddedObject` but they are not embedded object.
- In metadata import service, embedded objects will always be cleared and re-create when update
- So removing this makes skipSharing & skipTranslations work as expected
- Added tests for both skip = false and true
> fix: skipSharing & skipTranslations not working properly

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/AxisV2.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/CompatibilityGuard.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/VisualizationFontStyle.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/visualization/CompatibilityGuardTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceFavoritesTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization.json
This is needed to avoid issues in the future. Otherwise, users will be able to save the same information on different DB columns. Making old attributes read-only will block that, and at the same time keep the compatibility during the next few releases.
I added the annotation `@JsonIgnoreProperties( ignoreUnknown = true )` just to prevent errors in case of any inconsistency, so the request will not fail. Any invalid property at the DB level will be ignored.
**Was already approved by the Release Control Committee, can go into patch/2.36.0.**
> fix: DHIS2-10177: Make old Axes elements read-only

- dhis-2/dhis-web/dhis-web-api/src/main/resources/META-INF/dhis/servlet.xml
`java.nio.charset.StandardCharsets.UTF_8` is not available in servlet.xml, have to use `UTF-8` string
> fix default charset UTF-8 [2.33]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheServiceTest.java
Disable the preheat cache in the new tracker importer.
It was not working as intended and potentially allowing breaking the ACL
> fix: Tracker preheat cache disabled

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/ValidationRuleExpressionDetails.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/PeriodTypeExtended.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/ValidationRunContext.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/AnalyticsValidationServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataAnalysisController.java
When viewing Validation Rule results (Data Quality app -> Validation Rule Analysis -> Validate -> and Results are found), there is a Details column with an info "i" icon for each result. Clicking on the icon pops up a "Validation Details" window with the name and description of the rule, and sections for "LEFT SIDE" and "RIGHT SIDE". In each section there is a column DATA ELEMENT under which is listed the data elements in the expression, and a column VALUE, which should show the value for each individual data element in the expression.
This allows the user to "drill down" to see what data values went into the validation result computation, not just the value for the entire left and right sides as shown in the original "Validation Rule Analysis" results window. This is useful when the left …
> fix: Validation details with all items DHIS2-8876

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/DataElementQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramIndicatorQuery.java
Found also an issue regarding aggregate type during the tests, which was also fixed as part of this PR. This fix aims to mimic the /dataElements endpoint.
Highly recommended being part of patch/2.36.0.
cc @Philip-Larsen-Donnelly
> fix: DHIS2-10766: Remove unnecessary 'group by' causing duplicated rows

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
When using api/trackedEntityInstances, it is possible to not give any organisationUnits or organisationUnitSelectionMode if explicit tei uids are sent in the params. This causes syntax error in the sql formed.
> fix: [DHIS2-10841] explicit tei uid causes sql syntax error (2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
When using api/trackedEntityInstances, it is possible to not give any organisationUnits or organisationUnitSelectionMode if explicit tei uids are sent in the params. This causes syntax error in the sql formed.
> fix: [DHIS2-10841] explicit tei uid causes sql syntax error (2.35)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
When using api/trackedEntityInstances, it is possible to not give any organisationUnits or organisationUnitSelectionMode if explicit tei uids are sent in the params. This causes syntax error in the sql formed.
> fix: explicit TEI UID causes SQL syntax error [DHIS2-10841] (2.36.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
When checking for "minimumAttributesForSearch", we ignore the unique parameters passed as part of the "attribute" request parameter. This change makes the change to respect unique attribute passed in "attribute" request parameter in addition to the "filter" parameter. 
Additional change is that, if atleast ONE unique attribute is present in either "filter" or "attribute" parameter, then the minimumAttributesForSearch is not needed. Earlier the behaviour was ALL attributes present in "filter" had to be unique, to be able to bypass the minimumAttributesForSearch validatiton.
> fix: [DHIS2-10870] Check unique attribute filters in attribute params in addition to filter param (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
When checking for "minimumAttributesForSearch", we ignore the unique parameters passed as part of the "attribute" request parameter. This change makes the change to respect unique attribute passed in "attribute" request parameter in addition to the "filter" parameter.
Additional change is that, if atleast ONE unique attribute is present in either "filter" or "attribute" parameter, then the minimumAttributesForSearch is not needed. Earlier the behaviour was ALL attributes present in "filter" had to be unique, to be able to bypass the minimumAttributesForSearch validation
> fix: [DHIS2-10870] Check unique attribute filters in attribute params in addition to filter param (2.36.0)

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonDocument.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonObject.java
- dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/JsonDocumentTest.java
Backport of #7850 - drops the changes to test that does not exist in 2.36.
> fix: JSON test tool bugfixes in context of [DHIS2-10740] (2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
Problem was that continues jobs could not be stopped. While one could disable it it would still run in the scheduler which after finishing a round would update the job configuration for the next due time and override the disabled state.
This would not be noticeable since the client began to use PATCH to flip the `enabled` flag. This would no longer trigger the `JobConfigurationObjectBundleHook` which had done this for POST.
I also noticed a thread-safety issue in the `DefaultSchedulingManager`.
It would do a `futures.contains(key)` followed by a `futures.put(key)`. Obviously the state could change between `contains` and `put` allowing for unintended things to happen when multiple threads are involved. This is now done via `computeIfAbsent` which makes sure only one thread will succeed and …
> fix: start/stop jobs when PATCHed [DHIS2-10890]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/BaseIdentifiableObject_.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_merge_mode.json
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultMergeService.java
https://jira.dhis2.org/browse/DHIS2-10657
Issue: 
- MergeService is merging both new sharing and legacy sharing collections so when importing, the legacy objects are being overwritten.
Fix:
- Add a sharing util method to detect if payload use legacy sharing objects then mergeService will ignore new sharing property. 
- If payload doesn't include legacy sharing objects then new sharing property will be used for updating. But it will not be affected by the mergeMode. This needs json patch service.
- Add unit tests for both case mergeMode=MERGE and REPLACE
> fix: sharing is overwritten with mergeMode=MERGE

- Jenkinsfile-publish-image
When both matrix stages run at the same time, the variable for test image is overwritten and the pipeline fails, because one stage either tries to remove a running docker container or start another one. Making the variable local scoped should fix that.
> ci: remove global variable causing race condition

- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/ProgramRuleDeletionHandler.java
NPE that keeps showing in test runs but that will not fail test since it is part of a deletion handler and as such all exceptions are caught.
> fix: NPE in ProgramRule deletion hook

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
Issues: 
- A fix for forwarding skipSharing to mergeService in MapController was not backport from 2.37
- A work around fix for sharing revert issue in AbstractCrudController always reset the value of skipSharing flag. This need to be removed in order for the fix https://github.com/dhis2/dhis2-core/pull/7898 works
> fix: remove workaround fix for sharing in AbstractCrudController [2.36]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/transformer/UserPropertyTransformer.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/Category.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroup.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroupSet.hbm.xml
- dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationRule.hbm.xml
- dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationRuleGroup.hbm.xml
https://jira.dhis2.org/browse/DHIS2-10998
- Add missing  `createdBy` field   in hbm mapping file for metadata objects which have userid column in database.
- Front-end apps request `fields=user[id,name]` got name = null, need to add ` .name( user.getName() );` in UserPropertyTransformer.
> fix: add missing createdBy field to hbm files

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistLogic.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistQueryControllerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
* allow setting translation locale via `locale` parameter
* allow `filter`s where property filtered on is a simple property of a collection property, for example `filter=organisationUnits.name:like:{name}` on `dataSets` where `organisationUnits` is a collection in the listed item type `dataSet` and the filter `name` is on items of `organisationUnits` collection (not on `dataSet` items any more).
* expansion of field presets (like `*`) skips all explicitly named fields (before and after the expanded preset). This allows now to use same column twice when mapped to different aliases using `rename` transformer
* filters on an identifiable collection is implicitly understood as filtering ids, `filter=organisationUnits:in:[...]` is same as `filter=organisationUnits.id:in:[...]`
* properties of …
> feat: Gist API missing features and bugfixes [DHIS2-10740]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportImportStrategyTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportTest.java
- dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
- dhis-2/dhis-e2e-test/src/test/resources/setup/userGroups.json
- adds a simple test for identifier=CODE and identifier UID. The test uses a setup metadata file and updates all metadata. Let me know if there's a better way to do it that would bring better code coverage. 
- another test that creates dataElementGroup and has userGroupAccesses with user group code, instead of ID. In that case, import is successful, but userGroupAccessess are not imported. I think this is a bug (wrote about it on DHIS2-9966)
> test: adds test for metadata import with code identifier (DHIS2-9966)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/AxisV2.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/CompatibilityGuard.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/VisualizationFontStyle.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/visualization/CompatibilityGuardTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceFavoritesTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization.json
This is needed to avoid issues in the future. Otherwise, users will be able to save the same information on different DB columns. Making old attributes read-only will block that, and at the same time keep the compatibility during the next few releases.
I added the annotation `@JsonIgnoreProperties( ignoreUnknown = true )` just to prevent errors in case of any inconsistency, so the request will not fail. Any invalid property at the DB level will be ignored.
Also notice that even though we had some properties removed from the Hibernate files, the DB columns are not being removed yet. As they were migrated into a new JSONB column, I want to preserve the existing columns in case a migration fails for any reason. If that happens we are able to track back the correct values and will not lose …
> fix: Make old Axes elements read-only [DHIS2-10177]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/GenericSizeof.java
Tests cause error because of reflective access to `String` fields by `sizeof` calculations.
To avoid this we provide a dedicated computation for `String`s so that no reflection is needed/used.
> fix: avoid reflective access to String for 'sizeof' calculations

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/ReportRatesHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/ReportRatesHelperTest.java
This fix adds a new and reusable tiny method to centralize and consolidate the target value used on report rates/dataSets.
Previously we had a calculation mistake that was doubling the target value causing the final result being 50% lower than the expected result.
I also extracted the calculation into a separate class making the changes unit testable.
> fix: DHIS2-10871: Fixing report rate calculation for 'single periods'

- .github/workflows/run-api-tests.yml
Until now, we ran the API tests only when label run-api-tests was added. It's easy to forget about the label, so this would sometimes lead to tests broken on master. 
This PR changes that behavior and now API tests will run on all PRs unless label [skip-api-tests] is added.  When the label is added, workflows that were already running will be canceled.
> ci: run api tests unless explicitly skipped

- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractDataValueControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueControllerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FollowupAnalysisControllerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/DataValuesFollowUpRequest.java
Upon request of Médi this PR adds a bulk update for data value followup. 
This is same as single update just that the request takes a list of `values` to update.
To set the `followup` status of multiple data values a `PUT` request is send to `/dataValues/followups` with a request object having just one field `values` each being the same as the existing single update `/dataValues/followup`.
```json
{ "values" : [
...
]}
```
Reasoning to not have all updated values share a part of the key is that this method is usually used with a set of data values that is the result of various filter combinations so we do not know what their common set of key parts is or if there even is a common set. 
Controller integration test was added testing the added endpoint.
* create data values
* change their …
> feat: adds data value followup bulk update API [DHIS2-10658]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceCleanUpJob.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceCleanUpJobTest.java
When executing the `FileResourceCleanUpJob` on the SL Demo database, the following exception was logged:
`javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.hisp.dhis.fileresource.FileResource#906799]`
This exception was generated during `HibernateGenericStore.delete` while trying to delete the first orphaned `FileResource`. The result was that no `FileResources` were deleted.
Searching StackOverflow for the error, and stepping into the Hibernate code, both revealed the same thing: this exception is generated when the item is already in the hibernate context (`session.persistenceContext.entitiesByKey`) but in a different Java object as the one requested for deletion (same database primary key but a …
> fix: FileResourceCleanUpJob aborts DHIS2-7700

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/AclService.java
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
This PR adds a variant of `getAccess` with an additional argument for the object type.
```java
<T extends IdentifiableObject> Access getAccess( T object, User user, Class<? extends T> objType );
```
It is added in preparation for a PR to allow using `Access` in the Gist API without having the actual object. Instead the gist will build an object (e.g. `BaseIndentifiableObject` around the `Sharing` value) and pass in the `Class` of the object the `Sharing` value belongs to. This way one can do the evaluations without actually having the full object.
For example when listing `DataElement`s it would do something like:
```java
IdentifiableObject obj = new BaseIdentifiableObject();
obj.setSharing(sharing);
getAccess(obj, currrentUser, DataElement.class);
```
As the `getAccess` only uses the …
> feat: create Access object for target type

- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/AclService.java
- dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistLogic.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistQueryControllerTest.java
This PR adds new synthetic field `access` to the Gist API.
It builds on the foundation work of #7951.
Since the `access` property of type `Access` is not persisted in the database it wasn't available in the Gist API until now.
Like other synthetic fields the `access` property can be computed on the basis of persisted columns, in this case the `sharing` information. This PR connects the existing ends so that users now can include `access` in the list of fields.
A controller test was added to assert it works as expected.
> feat: gist API 'access' synthetic field

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
See [DHIS2-10836](https://jira.dhis2.org/browse/DHIS2-10836).
This PR changes the default page size for /sharing/search from Integer.MAX_VALUE  (2,147,483,647) to 10.
> fix: sharing/search default page size DHIS2-10836

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
* fix: sharing/search defalut page size DHIS2-10836
* refactor: use Paging.DEFAULT_PAGE_SIZE
(cherry picked from commit 4a2fc89bc372c268104fd3ce9cce769ae709ab5f)
> fix: sharing/search default page size DHIS2-10836 (#7961)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistValidator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistQueryControllerTest.java
PR adds two new filter operators, `canRead` and `canWrite` to the list of possible filters.
Usage:
{field}:canRead:{userID}
{field}:canWrite:{userID}
{field}:canDataRead:{userID}
{field}:canDataWrite:{userID}
{field}:canAccess:[{userID},{pattern}]
There are 3 cases depending on the type of field:
* simple field: checks if the user given by ID has read/write access to the owning object
* reference field to an identifiable object field: checks if the user given by ID has read/write access to the referenced object
* collection of identifiable objects field: checks if there are elements in the collection the user given by ID has read/write access to
This is slightly different take on Metadata API filters like `access.data.read:eq:true` which has to be processed in memory while the Gist API …
> feat: Gist API canRead/canWrite filters

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/FollowupValue.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodType.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonFollowupValue.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FollowupAnalysisControllerTest.java
Upon request and in conversation with Mèdi the period ISO "ID" was added to the returned items of the followup data analysis.
The field previously named `pe` was renamed to `peType` and the property `pe` (from getter) now holds the ISO ID. 
This is also more consistent with request parameters where `pe` is usually used as the period ISO ID.
> feat: provide period ID in followup analysis API [DHIS2-10658]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
When eventStatus,eventStartDate and eventEndDate are present in the TEI queryParams including the program, then muliple "hlp.whereAnd()" call is invoked which caused unnecessary "and" in the formed sql.
> fix: [DHIS2-11073] malformed sql if tei query params has event filters (2.35)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityInstanceMapper.java
When updating an object the createdBy fields was overwritten by an empty one because we were not mapping this fields in the entities loaded into the Preheat
> fix: Map createdBy and updatedBy fields to objects loaded into Preheat [DHIS2-10885]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
When eventStatus,eventStartDate and eventEndDate are present in the TEI queryParams including the program, then muliple "hlp.whereAnd()" call is invoked which caused unnecessary "and" in the formed sql.
> fix: [DHIS2-11073] malformed sql if tei query params has event filters (2.37)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceCleanUpJobTest.java
This relates to follow-up testing of [DHIS2-7700 Fileresource Cleanup Job doesn't delete correct/any files](https://jira.dhis2.org/browse/DHIS2-7700). No errors were found in 2.37, 6, or 5. But in 2.34 the test was failing because of an orphaned `FileResource` that was being used as a user's `avatar`.
I added the check for user avatar to `UserDeletionHandler`, and included testing this to `FileResourceCleanUpJobTest`. (The new test failed before the fix, and succeeded after the fix.)
> fix: UserDeletionHandler check avatar DHIS2-7700

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalue/StreamingXmlDataValue.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetB.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetBUpdate.xml
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/batchhandler/DataValueBatchHandler.java
See [DHIS2-8379](https://jira.dhis2.org/browse/DHIS2-8379).
When data import updates an existing data value, it sets the created date to the current timestamp, instead of retaining the original data value created date. (By contrast, when data entry updates a data value, it keeps the original data value created date.)
In `DefaultDataValueSetService:1227` (new line number as of yesterday!), the created date is set to either what is specified in the import, or to the current date/time if it is not specified. This happens before it is determined if there is an existing data value to update.
`DefaultDataValueSetService` -- if there is an existing data value, and the import does not specify a created date, keep the existing created date.
`DataValueBatchHandler` -- return the created date for an …
> fix: keep data value created w/import DHIS2-8379
