dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHookTest.java

https://jira.dhis2.org/browse/DHIS2-5777

feat: Add ACL validation for programStage.DEs

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java

fix (2.32): Removed invalid code causing issues for REPLACE mergeMode

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java

fix: remove invalid code

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java

While restoring password if no user is found against provided username then request should be terminated. In other cases request should proceed with password validation.

fix: [2.32] Check null reference when restoring password

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml

fix:(2.30) Fix TransientObjectException issue by fixing Hibernate config

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml

fix:(2.31) Fix TransientObjectException issue by fixing Hibernate config

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml

fix:(2.32) Fix TransientObjectException issue by fixing Hibernate config

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml

fix:(2.33) Fix TransientObjectException issue by fixing Hibernate config

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHookTest.java

backport https://github.com/dhis2/dhis2-core/pull/4300

feat: (v33) Add ACL validation for programStage.DEs 

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHookTest.java

backport https://github.com/dhis2/dhis2-core/pull/4300

feat: (v32) Add ACL validation for programStage.DEs 

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHookTest.java

backport https://github.com/dhis2/dhis2-core/pull/4300

feat: (v31) Add ACL validation for programStage.DEs 

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManagerTest.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManagerTest.java
dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/SqlHelper.java

Stop counting events related to the categories that users don't have access.
Porting it to 2.34. Was already ported to the other versions.

fix: Event count fix for not allowed categories [DHIS2-7712]

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsColumnAsserter.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsTableAsserter.java

- DHIS2-7976
- Specify the `gist` column type when creating indexes for Geometry
columns

[2.33] fix: analytics table creation crash on geo columns

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceUserTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole_update.json

Backport https://github.com/dhis2/dhis2-core/pull/4401

fix: (2.31) Role is deleted when updating without read access

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceUserTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole_update.json

backport https://github.com/dhis2/dhis2-core/pull/4401

fix: (v33) Role is deleted when updating without read access

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceUserTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/user_userrole_update.json

Backport https://github.com/dhis2/dhis2-core/pull/4401

fix: (2.32) Role is deleted when updating without read access

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/email/EmailResponse.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/EmailMessageSender.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EmailController.java

- Reuse description message from incoming parameter if available as it is usually more descriptive
TECH-195

chore: (2.34) Reuse description message if available

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_skipSharing.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_update_skipSharing.json

backport https://github.com/dhis2/dhis2-core/pull/4136

fix: (2.31) skipSharing not effected when create object

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java

fix: (2.31) Fix NPE by adding new request parameter

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java

fix: (2.32) Fix NPE by adding new request parameter

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java

fix: (2.33) Fix NPE by adding new request parameter

---

dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DefaultDeletionManager.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DeletionInterceptor.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DeletionManager.java

backport https://github.com/dhis2/dhis2-core/pull/4603

fix: (2.31) transactionRollback for addAndPruneOptionCombos()

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/DefaultCategoryManager.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/category/CategoryServiceTest.java

https://jira.dhis2.org/browse/DHIS2-2022

fix: (2.32) addAndPruneOptionCombos doesnt update coc name

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java

DHIS2-7385
Propagate logged-in username to function that stores the Notes, during
Event creation

[2.31] fix: preserve username in comments during event capture

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroup.hbm.xml
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/CsvImportClass.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/DefaultCsvImportService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/Metadata.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/CsvMetadataImportTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/metadata/option_group_set.csv
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/metadata/option_group_set_members.csv
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/metadata/option_groups.csv
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/metadata/option_set.csv

https://jira.dhis2.org/browse/DHIS2-6104

feat: Support import OptionGroupSet using CSV [DHIS2-6104]

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/utils/DataGenerator.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/extensions/AuthFilter.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserTest.java

test: adds tests for user password reset

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/CodecUtils.java

https://jira.dhis2.org/browse/DHIS2-1439

fix: (2.34) urlEncode for user invitation email

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportTest.java

Bug: https://jira.dhis2.org/browse/DHIS2-7496

test: adds tests for skipSharing flag

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStage.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionIntegrationTest.java

* [DHIS2-8047] Delete program stage section orphans when updating program stage
* Fix integration test

fix: [DHIS2-8047] Delete program stage section orphans when updating program stage

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_11__Remove_unused_system_setting.sql

Remove unused SystemSetting
- KEY_SCHED_TASKS( "keySchedTasks" )

fix: Remove unused system setting

---

dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DefaultDataQueryServiceTest.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataset/notifications/DataSetNotificationServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/ProgramNotificationServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/SmsMessageSenderTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/config/GatewayAdministrationServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/DataValueListenerTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/TrackedEntityRegistrationListenerTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHookTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/version/MetadataVersionDelegateTest.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
dhis-2/pom.xml

- Removed Mockito warnings from Unit Test run.
- Bumped Mockito version to latest.

Remove mockito warnings

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/CodecUtils.java

backport https://github.com/dhis2/dhis2-core/pull/4624

fix: (2.31) urlEncode for user invitation email

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/CodecUtils.java

backport https://github.com/dhis2/dhis2-core/pull/4624

fix: (2.32) urlEncode for user invitation email

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/CodecUtils.java

backport https://github.com/dhis2/dhis2-core/pull/4624

fix: (2.33) urlEncode for user invitation email

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityTypeAttribute.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityAttributeStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/JacksonTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java

fix: (2.34) Test SkipSync functionality, fix Cast exception bug

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/JacksonTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java

fix: (2.33) Test SkipSync functionality, fix Cast exception bug

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/JacksonTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java

fix: (2.32) Test SkipSync functionality, fix Cast exception bug

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/AbstractDeviceRenderTypeMapDeserializer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/DeviceRenderTypeMapSerializer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/SectionRenderTypeDeserialize.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/ValueRenderTypeDeserialize.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageDataElement.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTrackedEntityAttribute.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/RenderingObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/SectionRenderingObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/SectionRenderingType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/ValueTypeRenderingObject.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramSection.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStageDataElement.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStageSection.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramTrackedEntityAttribute.hbm.xml
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstagesection_with_deps.xml
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/StAXNodeSerializer.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonDeviceRenderTypeMap.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/org/hisp/dhis/usertype/UserTypes.hbm.xml

backport https://github.com/dhis2/dhis2-core/pull/4592

feat: (2.33) Add deserializer for DeviceRenderTypeMap [DHIS2-6543]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/AbstractDeviceRenderTypeMapDeserializer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/DeviceRenderTypeMapSerializer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/SectionRenderTypeDeserialize.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/ValueRenderTypeDeserialize.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageDataElement.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTrackedEntityAttribute.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/RenderingObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/SectionRenderingObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/SectionRenderingType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/ValueTypeRenderingObject.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramSection.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStageDataElement.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStageSection.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramTrackedEntityAttribute.hbm.xml
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstagesection_with_deps.xml
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/StAXNodeSerializer.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonDeviceRenderTypeMap.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/org/hisp/dhis/usertype/UserTypes.hbm.xml

backport https://github.com/dhis2/dhis2-core/pull/4592

feat: (2.31) Add deserializer for DeviceRenderTypeMap [DHIS2-6543]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValidator.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/datavalue/DataValidatorTest.java

Adding support for multiple boolean values for the POST dataset endpoint.
Most of this PR is refactoring to isolate the main validation logic into a separate component.
The actual new feature added to allow multiple booleans is:
`final String withNormalizedBoolean = normalizeBoolean( dataValue, dataElement.getValueType() );`

feat: Multiple bool valus for data set [DHIS2-7905]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/AbstractDeviceRenderTypeMapDeserializer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/DeviceRenderTypeMapSerializer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/SectionRenderTypeDeserialize.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/ValueRenderTypeDeserialize.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageDataElement.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramTrackedEntityAttribute.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/RenderingObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/SectionRenderingObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/SectionRenderingType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/ValueTypeRenderingObject.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramSection.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStageDataElement.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStageSection.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramTrackedEntityAttribute.hbm.xml
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstagesection_with_deps.xml
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/StAXNodeSerializer.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonDeviceRenderTypeMap.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/org/hisp/dhis/usertype/UserTypes.hbm.xml

backport https://github.com/dhis2/dhis2-core/pull/4592

feat: (2.32) Add deserializer for DeviceRenderTypeMap 

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/JacksonTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java

fix: (2.31) Test SkipSync functionality, fix Cast exception bug

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java

Small fix to make re-direct after pw. change work.
Issue: [DHIS2-7355]

fix: Redirect to self after pw change/subsequent re-login

---

dhis-2/dhis-e2e-test/docker-compose.yml
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserTest.java

Added additional rules for changing password.

test: Add more cases for password validation

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserTest.java

The redirection after pw change broke this test, it was checking for 202 now it should be 302
Issue: [DHIS2-7355]

fix: Fix broken e2e test for password change.

---

dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java

Oops. Some of the test results were based on the current date (so it only worked yesterday). I've changed the test date now to a fixed date.

fix: ProgramIndicatorServiceD2FunctionTest

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java

fix: (2.32) Use correct Import Strategy

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java

fix: (2.31) Use correct Import Strategy

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java

fix: (2.30) Use correct Import Strategy

---

dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java

fix: Add encryption.password for HibernateConfigurationProvider

---

dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java

fix:(2.31) Add encryption.password for HibernateConfigurationProvider

---

dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java

fix: (2.32) add encryption.password for HibernateConfigurationProvider

---

dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java

fix: (2.33) Add encryption.password for HibernateConfigurationProvider

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/MeasureFilter.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsUtilsTest.java

This issue is being backported from 2.34 into (2.31)

fix: Fix decimal output for Indicators [DHIS2-8033]

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/LoginActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/RestApiActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/SystemSettingActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/systemsettings/SystemSettingsTests.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSetting.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/resources/org/hisp/dhis/setting/SystemSetting.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_16__Add_translations_column_into_systemsetting_table.sql
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feature: (2.34) Add translations support for SystemSettings

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/systemsettings/SystemSettingsTests.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

fix: (2.34) Fix bug with not returning default values when applicable

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

chore: (2.34) Use Optional instead of empty String

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSetting.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/resources/org/hisp/dhis/setting/SystemSetting.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_33_23__Add_translations_column_into_systemsetting_table.sql
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.33) Add translations support for SystemSettings

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java

- Use an Enum instead of hardcoded value
DHIS2-8160

fix: (2.34) Use correct URL for completeness sync

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java

fix: (2.32) Use correct URL for completeness sync

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

chore: (2.33) Use Optional instead of empty String

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSetting.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/resources/org/hisp/dhis/setting/SystemSetting.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.32/V2_32_31__Add_translations_column_into_systemsetting_table.sql
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.32) Add translations support for SystemSettings

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSetting.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
dhis-2/dhis-services/dhis-service-setting/src/main/resources/org/hisp/dhis/setting/SystemSetting.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.31/V2_31_20__Add_translations_column_into_systemsetting_table.sql
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.31) Add translations support for SystemSettings

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java
dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js

backport https://github.com/dhis2/dhis2-core/pull/3040
This allows user to enter data for an OU if the openning date range is within selected period.

fix: (2.31) Add validation for OU opening date range in DataEntry

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java
dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js

Backport https://github.com/dhis2/dhis2-core/pull/3040
This allows user to enter data for an OU if the openning date range is within selected period.

fix: (2.30) Add validation for OU opening date range in DataEntry

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java
dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js

Backport https://github.com/dhis2/dhis2-core/pull/3040
This allows user to enter data for an OU if the openning date range is within selected period.

fix: (2.29) Add validation for OU opening date range in DataEntry

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/pom.xml
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/relationship/JacksonRelationshipServiceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/BeanRandomizer.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/GeometryRandomizer.java

- DHIS2-8137
- Improves the validation check executed when adding a new relationship,
by checking the existence of a Relationship by from, to and type
(cherry picked from commit 55d7f61dc5369083d801eefbe28fe7a47b63849f)

[2.33] fix: check relationship exists

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java
dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js

https://jira.dhis2.org/browse/DHIS2-2198
This allows user to enter data for an OU if the openning date range is within selected period.

fix:(2.32) Add validation for OU's opening date range in Data Entry app

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/teis/RelationshipsTest.java

test for jira issue: DHIS2-8137

test: adds test for duplicate relationship

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java

- Add support for IdScheme.Attribute for Events export
DHIS2-7278
DHIS2-7070

fix: (2.30) Fix issue with COCs not working with idScheme=CODE

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/systemsettings/SystemSettingsTests.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

fix: (2.34) Add support for JSON accept content-type

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

fix: (2.33) Add support for JSON accept content-type

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

fix: (2.32) Add support for JSON accept content-type

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

fix: (2.31) Add support for JSON accept content-type

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java

backport https://github.com/dhis2/dhis2-core/pull/4785

fix: (2.33) Option validate fail on update

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java

backport https://github.com/dhis2/dhis2-core/pull/4785

fix: (2.32) Option validate fail on update

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java

backport https://github.com/dhis2/dhis2-core/pull/4785

fix: (2.31) Option validate fail on update

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorReport.java

[DHIS2-8149](https://jira.dhis2.org/browse/DHIS2-8149)

feat(2.31): Add 'errorProperties' to ErrorReport

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorReport.java

[DHIS2-8149](https://jira.dhis2.org/browse/DHIS2-8149)

feat(2.32): Add 'errorProperties' to ErrorReport

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorReport.java

[DHIS2-8149](https://jira.dhis2.org/browse/DHIS2-8149)

feat(2.33): Add 'errorProperties' to ErrorReport

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueAuditStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/datavalue/DataValueAuditServiceTest.java

https://jira.dhis2.org/browse/DHIS2-1678
Issue: Current data value audit query returns all data if given Period doesn't exist in database. 
Expectation: it should return no data if given Period doesn't exist. Also the query should use conjunction conditions.

fix: Use conjunction for dataValueAudit query

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.34) Return JSON array with key:value instead only a value

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.31) Return JSON array with key:value instead only a value

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.32) Return JSON array with key:value instead only a value

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.33) Return JSON array with key:value instead only a value

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueAuditStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/datavalue/DataValueAuditServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/4752

fix: (2.33) Use conjunction for dataValueAudit query

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueAuditStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/datavalue/DataValueAuditServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/4752

fix: (2.31) Use conjunction for dataValueAudit query

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueAuditStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/datavalue/DataValueAuditServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/4752

fix: (2.32) Use conjunction for dataValueAudit query

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java

Due to some earlier refactor of Enrollment processing, notification related to TEI enrollment stopped working. Fixed it by calling notification service in AbstractEnrollmentService.

fix: Fix enrollment notification

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/Chart.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/reporttable/ReportTable.java

I have other tests failing locally, which seems to be because my local DB is different from the server.
The fixes in this PR should fix the Chart and ReportTable validations. Please let me know if you find other issues.
* The expectation for Chart and ReportTable would be a 500 error, as they will not be supported in the import/export.

fix: e2e test fixes for Chart/ReportTable [DHIS2-7946]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java

fix: (2.34) Do not show href if Event UID is not present

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPreProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/DataSynchronization.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/DataValueSynchronization.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventProgramsDataSynchronizationJob.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventSynchronization.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/SyncUtils.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerProgramsDataSynchronizationJob.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java

- Clean the implementation of sync jobs
- Prepare for adding a paging feature for Completeness sync
- Prepare for adding new job parameteres for Metadata, Completeness and Data Values sync
DHIS2-6062

chore: (2.34) Refactor sync implementation

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java

fix: (2.33) Do not show href if Event UID is not present

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java

fix: (2.32) Do not show href if Event UID is not present

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java

fix: (2.31) Do not show href if Event UID is not present

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java

https://jira.dhis2.org/browse/DHIS2-8125

fix: Malformed Image on download from data entry

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java

backport https://github.com/dhis2/dhis2-core/pull/4868

fix: (2.33) NPE in TrackedEntityAttribute validator

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java

backport https://github.com/dhis2/dhis2-core/pull/4868

fix: (2.32) NPE in TrackedEntityAttribute validator

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java

backport https://github.com/dhis2/dhis2-core/pull/4868

fix: (2.31) NPE in TrackedEntityAttribute validator

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java

backport https://github.com/dhis2/dhis2-core/pull/4863

fix:(2.33) Malformed Image on download from data entry

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.34) Add support for JSON content type in POST request

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.33) Add support for JSON content type in POST request

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.32) Add support for JSON content type in POST request

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java

feat: (2.31) Add support for JSON content type in POST request

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java

backport https://github.com/dhis2/dhis2-core/pull/4863

fix: (2.32) Malformed Image on download from data entry

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java

backport https://github.com/dhis2/dhis2-core/pull/4863

fix: (2.31) Malformed Image on download from data entry

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java

https://jira.dhis2.org/browse/DHIS2-5382
Only delete YesOnly DataValue if ( value == null && followUp == null && comment == null )

fix: Incorrect follow up value for YesOnly dataValue

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventSynchronization.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/SyncUtils.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DataSynchronizationJob.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/SynchronizationManager.java
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java

fix: (2.30) Use new Event sync implementation

---

.github/workflows/analyse-pr.yml
.github/workflows/run-tests.yml

should fix "fatal:reference is not a tree" https://github.com/actions/checkout/issues/23
[reference https://github.com/actions/checkout/issues/23]

chore: use actions/checkout@v2

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValueController.java

fix: make use of response.setContentLong in DataValueController

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/SyncUtils.java

chore: (2.30) Remove unnecessary logging

---

dhis-2/dhis-support/dhis-support-antlr-expression-parser/pom.xml
dhis-2/dhis-support/dhis-support-antlr-expression-parser/src/main/antlr4/org/hisp/dhis/parser/expression/antlr/Expression.g4

- Quick fix of the grammar
- Make the project independent from dhis, it will be moved to a separate repository.

fix: Fix antlr grammar and make the project independent from dhis

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheatHook.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/hooks/FileResourceTrackerPreheatHook.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeFileResourceTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/te_program_with_tea_fileresource_data.json
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/te_program_with_tea_fileresource_metadata.json

[DHIS2-8357](https://jira.dhis2.org/browse/DHIS2-8357)

feat: Support file resource in TEAV

---

dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/AbstractPropertyIntrospectorService.java

backport https://github.com/dhis2/dhis2-core/pull/4941

fix: (2.33) use correct minValue for Property introspector

---

dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/AbstractPropertyIntrospectorService.java

backport https://github.com/dhis2/dhis2-core/pull/4941

fix: (2.32) Use correct minValue for Property introspector

---

dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/AbstractPropertyIntrospectorService.java

backport https://github.com/dhis2/dhis2-core/pull/4941

fix: (2.31) Use correct minValue for Property introspector

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/JdbcCompleteDataSetRegistrationExchangeStore.java

https://jira.dhis2.org/browse/DHIS2-8196

fix: CompleteDataSetRegistration missing complete status

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/JdbcCompleteDataSetRegistrationExchangeStore.java

backport https://github.com/dhis2/dhis2-core/pull/4883

fix: (2.33) CompleteDataSetRegistration missing complete status

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java

backport https://github.com/dhis2/dhis2-core/pull/4882

fix: (2.33) Incorrect follow up value for YesOnly dataValue

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java

backport https://github.com/dhis2/dhis2-core/pull/4882

fix:(2.32) Incorrect follow up value for YesOnly dataValue

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java

backport https://github.com/dhis2/dhis2-core/pull/4882

fix: (2.31) Incorrect follow up value for YesOnly dataValue

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManagerTest.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/security/DefaultAnalyticsSecurityManagerTest.java

Backporting fix, so users will see only events of cat-options they have access (2.32)

fix: Events counting for non-auth users [DHIS2-7712]

---

dhis-2/dhis-api/pom.xml
dhis-2/dhis-api/src/main/java/org/hisp/dhis/audit/AuditAttribute.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/MetadataObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValue.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramInstance.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageInstance.java
dhis-2/dhis-services/dhis-service-audit-consumer/src/main/java/org/hisp/dhis/audit/legacy/AggregateAuditConsumer.java
dhis-2/dhis-services/dhis-service-core/pom.xml
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/audit/AuditIntegrationTest.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditManager.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/legacy/DefaultAuditObjectFactory.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AuditEnabledCondition.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostDeleteAuditListener.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostInsertAuditListener.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostLoadAuditListener.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/PostUpdateAuditListener.java
dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/SystemUtils.java
dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/condition/PropertiesAwareConfigurationCondition.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationTestConfig.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AuditController.java
dhis-2/pom.xml

backport https://github.com/dhis2/dhis2-core/pull/5023

fix: (2.34) Redis cache issue with AuditAttributes

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
dhis-2/dhis-web/dhis-web-uaa/src/main/resources/META-INF/dhis/webapi-uaa.xml

backport https://github.com/dhis2/dhis2-core/pull/5097

fix:(2.34) Incorrect xsd schema url of spring oauth2

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
dhis-2/dhis-web/dhis-web-uaa/src/main/resources/META-INF/dhis/webapi-uaa.xml

fix: incorrect xsd schema of for spring oauth2

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

fix: Null reference of option.optionSet after import

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

fix: (2.34) Null reference of option.optionSet after import

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

fix:(2.33) Null reference of option.optionSet after import

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

fix: (2.32) Null reference of option.optionSet after import

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

fix:(2.31) Null reference of option.optionSet after import

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

fix: (2.34.0) Null reference of option.optionSet after import

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventSynchronization.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/SyncUtils.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DataSynchronizationJob.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/SynchronizationManager.java

fix: (2.32) Use new Event sync implementation

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventSynchronization.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/SyncUtils.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DataSynchronizationJob.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/DefaultSynchronizationManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/synch/SynchronizationManager.java

fix: (2.31) Use new Event sync implementation

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.31/V2_31_23_Upgrade_sequential_nuber_counter_key.sql

fix: upgradescript to handle a change in the key column

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElementOperand.java

backport https://github.com/dhis2/dhis2-core/pull/3213

fix: (2.31) add getDisplayShortName() for DataElementOperand

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElementOperand.java

backport backport https://github.com/dhis2/dhis2-core/pull/3213

fix: (2.32) Add getDisplayShortName() for DataElementOperand

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/PaginationUtils.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/WebOptions.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/utils/PaginationUtilsTest.java

* fix: incorrect calculation of firstResult in pagination
(cherry picked from commit 7acf9882fdc5cb77fc5dfc0ea6af18e778328e6f)

[2.33] fix: incorrect calculation of firstResult in pagination (#5165)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/TimeToLive.java

Fix for the failing unit test reported by @jimgrace

fix: Failling unit test in other timezones in TimeToLive tests

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vCompletedDate.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
dhis-2/dhis-support/dhis-support-expression-parser/src/main/antlr4/org/hisp/dhis/parser/expression/antlr/Expression.g4

It adds support for variable 'completed_date'.

fix: (2.33) Function hasValue to use program variables

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml

As per reported by Austin in slack https://dhis2.slack.com/archives/C1XNHEY0L/p1585734484025600

fix: disable auth for analytic static resources

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml

backport https://github.com/dhis2/dhis2-core/pull/5245

fix: (2.33) Disable auth for analytic plugin resources

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml

backport https://github.com/dhis2/dhis2-core/pull/5245

fix: (2.34) disable auth for analytic plugin resources

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml

backport https://github.com/dhis2/dhis2-core/pull/5245

fix: (2.32) Disable auth for analytic plugin resources

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml

Backport https://github.com/dhis2/dhis2-core/pull/5245

fix: (2.31) Disable auth for analytic plugin resources

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryCombo.java

backport https://github.com/dhis2/dhis2-core/pull/5200

fix: (2.34) CategoryCombo w/o Option causes api/dataElementOperands 500

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryCombo.java

backport https://github.com/dhis2/dhis2-core/pull/5200

fix: (2.33) CategoryCombo w/o Option causes api/dataElementOperands 500

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryCombo.java

backport https://github.com/dhis2/dhis2-core/pull/5200

fix: (2.31) CategoryCombo w/o Option causes api/dataElementOperands 500

---

dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml

backport https://github.com/dhis2/dhis2-core/pull/5245

fix: (2.30) Disable auth for analytic plugin resources

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryCombo.java

backport https://github.com/dhis2/dhis2-core/pull/5200

fix: (2.32) CategoryCombo w/o Option causes api/dataElementOperands 500

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleAction.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectListenerConfigurer.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostDeleteEventListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostInsertEventListener.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementStoreIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementStoreTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/organisationunit/OrganisationUnitStoreIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionIntegrationTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5187

fix: (2.34) DeletedObject constraint error when delete ProgramRule

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserService.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectListenerConfigurer.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostDeleteEventListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostInsertEventListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultCurrentUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementStoreIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementStoreTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/organisationunit/OrganisationUnitStoreIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/predictor/PredictorServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/HibernateListenerConfigurer.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockCurrentUserService.java

backport https://github.com/dhis2/dhis2-core/pull/5187

fix: (2.33) DeletedObject constraint error when delete ProgramRule

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/sms/hibernate/IncomingSms.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_33_25__Alter_column_type_in_incomingsms.sql

Alter column type in incomingsms to allow larger text.

fix: Alter column type in incomingsms to allow larger text

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java

Removes the forced lowercase in the event report query for text types (2.32)

fix: Removing lowercase of columns [DHIS2-8407]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java

backport https://github.com/dhis2/dhis2-core/pull/5271

fix: (2.33) Hibernate lazy exception in TwoFactorAuthenticationProvider

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java

backport https://github.com/dhis2/dhis2-core/pull/5271

fix: (2.34) Hibernate lazy exception in TwoFactorAuthenticationProvider

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java

backport https://github.com/dhis2/dhis2-core/pull/5271

fix: (2.32) Hibernate lazy exception in TwoFactorAuthenticationProvider

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java

backport https://github.com/dhis2/dhis2-core/pull/5271

fix: (2.31) Hibernate lazy exception in TwoFactorAuthenticationProvider

---

dhis-2/dhis-web/pom.xml

Upgrade to the latest version of the jetty-maven-plugin

chore: Upgrade jetty-maven-plugin

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

backport https://github.com/dhis2/dhis2-core/pull/5338

fix: (2.31) NPE in OptionSetObjectBundleHook

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

backport https://github.com/dhis2/dhis2-core/pull/5338

fix: (2.32) NPE in OptionSetObjectBundleHook

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

backport https://github.com/dhis2/dhis2-core/pull/5338

fix: (2.33) NPE in OptionSetObjectBundleHook

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

backport https://github.com/dhis2/dhis2-core/pull/5338

fix: (2.34) NPE in OptionSetObjectBundleHook

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

https://jira.dhis2.org/browse/DHIS2-8035

fix: NPE in OptionSetObjectBundleHook

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/programs/ProgramRemovalTest.java

Tests DHIS2-6401: relationshipTypes should be removed when program is removed

test: adds test program deletion handlers 

---

dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/chart/impl/DefaultChartService.java

Porting the NPE workaround to (2.34)

fix: NPE when Chart.category() is null [DHIS2-8590]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StoreConfig.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/visualization/VisualizationDeletionHandler.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/visualization/impl/DefaultVisualizationService.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/visualization/impl/DefaultVisualizationServiceTest.java

Adding a missing deletion handler for Visualization periods. This was causing a constraint exception during the Prune periods (2.35)

fix: Adding deletion handler checking for delete periods [DHIS2-8656]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CombinationGenerator.java

https://jira.dhis2.org/browse/DHIS2-2696

fix: (2.31) NPE in CombinationGenerator

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/hibernate/HibernateOrganisationUnitStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java

* Updates forceUpdatePaths to use flush only instead of flush+clear
* Updates tracker services to use flush only instead of flush+clear

fix: Remove usage of clearSession where not needed

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/render/DefaultRenderService.java

```* INFO  2020-04-21T09:17:31,438 Populate analytics_event_temp_q04uboqq3rp_2020 in: 0.02 seconds (AbstractJdbcTableManager.java [taskScheduler-1])
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.hisp.dhis.dxf2.metadata.Metadata["organisationUnits"]->java.util.ArrayList[3]->org.hisp.dhis.organisationunit.OrganisationUnit["geometry"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeseria …
```

fix: (2.34) NPE when import  geometry in XML format

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/render/DefaultRenderService.java

backport https://github.com/dhis2/dhis2-core/pull/5404

fix: (2.34.0) NPE when import  geometry in XML format

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramInstanceService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramInstanceStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramInstanceDeletionHandler.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHookTest.java

ProgramInstance is soft deleted when a TEi is deleted but it is hard deleted when a program is deleted.
I changed the code to make everything as it was before this PR
https://github.com/dhis2/dhis2-core/pull/5131
Anyway, it would be good to have a discussion around this soft/hard deletion for ProgramInstance

fix: hard delete ProgramInstance when deleting Program

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/PreheatService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniquenessCheck.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/org_unit_code_id.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/org_unit_code_id_update.json

* test: org unit import with code matching (create only)
* test: adds (failing) test for updating org unit by code
* fix: use identifier.getIdentifier() for building up uniquenessmap + check object uniqueness
* fix: re-use existing UID if matching by CODE and existing object exists

fix: metadata updates using CODE identifiers (#5407)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseNameableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/Option.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStage.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

https://jira.dhis2.org/browse/DHIS2-6998

fix: Add translation for formName property

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/teis/RelationshipsTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/RelationshipController.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/RelationshipControllerTest.java

* fix: [DHIS2-7740] Fix response http status for relationships controller
* Add tests
* Fix tests

fix: Response http status for relationships controller [DHIS2-7740]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceContentStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/fileresource/FileResourceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/JCloudsFileResourceContentStore.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueController.java

fix: (Revert) "fix: add contentLength header from fileresource for file downloads"

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseNameableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/Option.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStage.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5430

fix: (2.34) Add translation for formName property

---

dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/SchemaValidatorTest.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SchemaUtils.java

* fix: properly set PropertyRange min/max for collections
* fix: make inner class in SchemaValidatorTest static

fix: set/validate PropertyRange min/max for collections (#5541)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java

* Exposes parentGraphMap as read only, fixes issues with XML deserialization

fix: expose getParentGraphMap as READ_ONLY

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java

* Exposes parentGraphMap as read only, fixes issues with XML deserialization

fix: expose getParentGraph as READ_ONLY

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java

In order to prevent a **potential** issue with a cached Hibernate object (`DataElement`) and Hibernate Session, the `DataElement` is now initialized to fetch all collections before setting it
into the cache - during a get TEI operation.

fix: init DataElement proxy before caching it

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java

[TECH-377](https://jira.dhis2.org/browse/TECH-377)

fix: reuse orgunit from TEI instead of converting, then getting org unit

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml

Co-authored-by: Stian Sandvold <stiansandvold@pop-os.localdomain>
(cherry picked from commit 2e632242756bc5b968a637e85f25c7402878bbc0)

fix: Add jdbcTemplate to bean (#5555)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorFunction.java

* fix: Predictor missingValueStrategy [DHIS2-8843]
* Fix tests in PredictionServiceTest
* VectorFunction code cleanup
(cherry picked from commit 7f30b7c0d106b1f1395b27df8d92da6c1c95a2a3)

fix: Predictor missingValueStrategy [DHIS2-8843] (#5571)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/indicator/Indicator.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/indicator/IndicatorServiceTest.java

https://jira.dhis2.org/browse/DHIS2-7783

fix: Add translation for numerator/denominator description

---

dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.menu.ui.js

fix: update call to removed /api/me/profile.json endpoint (DHIS2-8788) [32]

---

dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.menu.ui.js

fix: update call to removed `/api/me/profile.json` endpoint [34]

---

dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/dhis2/dhis2.menu.ui.js

fix: update call to removed `/api/me/profile.json` endpoint [33]

---

dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java

(cherry picked from commit 6f67870924f094ee30d7d561221cc683fd5434d7)

fix: Prediction in later predictions [DHIS2-8707] (#5442)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseNameableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/Option.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStage.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5430

fix: (2.33) Add translation for formName property

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseNameableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/Option.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStage.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5430

fix: (2.32) Add translation for formName property

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/AttributeService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/AttributeObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/AttributeValueImportTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute_update.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet_update.json

https://jira.dhis2.org/browse/DHIS2-8621

fix: cant update attributeValue after change attribute name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/AttributeService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/AttributeObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/AttributeValueImportTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute_update.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet_update.json

backport https://github.com/dhis2/dhis2-core/pull/5494

fix: (2.33.4) Cant update attributeValue after change attribute name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/AttributeService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/AttributeObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/AttributeValueImportTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute_update.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet_update.json

backport https://github.com/dhis2/dhis2-core/pull/5494

fix: (2.33) Cant update attributeValue after change attribute name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/AttributeService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/AttributeObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/AttributeValueImportTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/attribute_update.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/attribute/dataSet_update.json

backport https://github.com/dhis2/dhis2-core/pull/5494

fix: (2.34) Cant update attributeValue after change attribute name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserService.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectListenerConfigurer.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostDeleteEventListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostInsertEventListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultCurrentUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementStoreIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementStoreTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/organisationunit/OrganisationUnitStoreIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/predictor/PredictorServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionIntegrationTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RegistrationMultiEventsServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/gml/GmlImportServiceTest.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockCurrentUserService.java

backport https://github.com/dhis2/dhis2-core/pull/5187

fix: (2.32) DeletedObject constraint error when delete ProgramRule

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/indicator/Indicator.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/indicator/IndicatorServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5438

fix:(2.34)Add translation for Numerator and Denominator

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/indicator/Indicator.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/indicator/IndicatorServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5438

fix:(2.33) Add translation for Numerator and Denominator

---

dhis-2/dhis-web/dhis-web-api-test/pom.xml
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerTest.java
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/mvc/messageconverter/AbstractRootNodeMessageConverterTest.java
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/AbstractRootNodeMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/CsvMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/ExcelMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/JsonMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/JsonPMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/PdfMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/XmlMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java

backport https://jira.dhis2.org/browse/DHIS2-6159

fix: (2.31) Missing file extension for MetadataExport

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/CsvMessageConverter.java
dhis-2/dhis-web/dhis-web-api/src/main/resources/META-INF/dhis/servlet.xml

backport https://github.com/dhis2/dhis2-core/pull/5641

fix: (2.31.9) Can't export metadata with csv.zip extension

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/AnalyticsCacheTtlMode.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/cache/CacheStrategy.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/AnalyticsCache.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/AnalyticsCacheSettings.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/TimeToLive.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/cache/AnalyticsCacheSettingsTest.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/cache/TimeToLiveTest.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceBaseTest.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/dashboard/impl/DefaultDashboardService.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/dashboard/DashboardServiceTest.java
dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/DefaultDhisConfigurationProvider.java
dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/DhisConfigurationProvider.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/H2DhisConfigurationProvider.java
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/WebCache.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/service/WebCacheTest.java

Backporting the analytics caching into (2.34)

feat: Backporting analytics caching [DHID2-8389]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseNameableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/Option.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStage.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStageSection.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/Relationship.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5430

fix: (2.31) Add translation for formName property

---

dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json

chore: update dv 34 branch

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/InterpretationService.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/interpretation/impl/DefaultInterpretationService.java

Fixes https://jira.dhis2.org/browse/DHIS2-8591

fix: Set lastUpdated for interpretations/comments on updateComment [DHIS2-8591]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstance.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityInstance.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstance.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackedEntityTrackerConverterService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/TrackedEntity.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_3__Add_storedBy_column_for_TEI.sql

https://jira.dhis2.org/browse/DHIS2-8746

feat: Add storedBy property for TrackedEntity

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm

https://jira.dhis2.org/browse/DHIS2-8712

fix: Missing translations for login page

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java

- DHIS2-8956
This fixes the metadata pagination issue that was supposed to be fixed by this back-port commit: 91ccf1609d82df8dc7f5cdd2261ca6849c499f46
The backport was not done correctly and some classes were not modified.

[2.32] fix: count total metadata entities for pagination object

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java

- DHIS2-8956
This fixes the metadata pagination issue that was supposed to be fixed by this back-port commit: 91ccf1609d82df8dc7f5cdd2261ca6849c499f46
The backport was not done correctly and some classes were not modified.
(cherry picked from commit 517740a961f457bf9d10d30876d6238024f88f93)

[2.31] fix: count total metadata entities for pagination object

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/interceptor/I18nInterceptor.java
dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/beans.xml

backport https://github.com/dhis2/dhis2-core/pull/5648

fix: (2.34) Set DB Locale in UserContext for struts I18nInterceptor

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/interceptor/I18nInterceptor.java
dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/beans.xml

backport https://github.com/dhis2/dhis2-core/pull/5648

fix: (2.32) Set DB Locale in UserContext for struts I18nInterceptor

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm

backport https://github.com/dhis2/dhis2-core/pull/5616

fix: (2.34) Missing translations for login page

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm

backport https://github.com/dhis2/dhis2-core/pull/5616

fix: (2.33) Missing translations for login page

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm

backport https://github.com/dhis2/dhis2-core/pull/5616

fix: (2.32) Missing translations for login page

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/GenericStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectManager.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/AttributeValueDeletionHandler.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/attribute/AttributeValueServiceTest.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java

backport https://github.com/dhis2/dhis2-core/pull/5717

fix: (2.33) Add DeletionHandler for Attribute

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/GenericStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectManager.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/AttributeValueDeletionHandler.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/attribute/AttributeValueServiceTest.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java

backport https://github.com/dhis2/dhis2-core/pull/5717

fix: (2.34) Add DeletionHandler for Attribute 

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java

https://jira.dhis2.org/browse/DHIS2-8746

fix: Add storedBy for AbstractTEIService.addTrackedEntityInstance()

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring/AbstractSpringSecurityCurrentUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultCurrentUserService.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockCurrentUserService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java

Optimize and minimize user code.
[DHIS2-9039]

fix: Remove unused code

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

https://jira.dhis2.org/browse/DHIS2-8619
Adding translations for Relationship
```
private transient String displayFormToName;
private transient String displayToFromName;
```
This need front-end update in translation dialog in maintenance app

feat: Add translations for RelationshipType From/To name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5650

feat: (2.34) Add translations for RelationshipType From/To name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5650

feat: (2.32) Add translations for RelationshipType From/To name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/5650

feat: (2.33) Add translations for RelationshipType From/To name

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DeflatedDataValue.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java

(cherry picked from commit ad46c2b7d2cd7329fb968303f2d5a15ccce2d81c)

fix: Predict w/existing deleted value [DHIS2-8192] (#5640)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring/AbstractSpringSecurityCurrentUserService.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockCurrentUserService.java

chore: Remove dead code in CurrentUserService

---

dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json

chore: update dv 32 branch

---

dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json

chore: update dv 33 branch

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_9__Add_mapview_nodatacolor.sql

Adds Flyway migration for the `MapView` property `noDataColor`.

fix: Add migration for MapView noDataColor

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DeflatedDataValue.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java

(cherry picked from commit ad46c2b7d2cd7329fb968303f2d5a15ccce2d81c)
(cherry picked from commit 3fc37a72880344669a173e3d752954adeb43bee0)

fix: Predict w/existing deleted value [DHIS2-8912] (#5640)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsController.java

* fix: remove general error message with more specific one
* Change exception message to use uppercase

fix: (2.32) Replace general error message with more specific one [DHIS2-8610]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/keyjsonvalue/KeyJsonValueService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/keyjsonvalue/DefaultKeyJsonValueService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/KeyJsonValueController.java

Add feature for admin user/ user with "ALL" authority to be able to read METADATASTORE namespace

fix: Restrict access to the METADATASTORE namespace

---

dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitStructureResourceTable.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/DataValueRowMapper.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/DeflatedDataValueNameMinMaxRowMapper.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/DeflatedDataValueRowMapper.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/OrganisationUnitRelationshipRowMapper.java

A few more gaps identified in the 2.32 conversion of "integer to long" ids.

fix: [DHIS2-9119] [DHIS2-9120] Integer out of ranges for long ids (2.32)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/keyjsonvalue/DefaultKeyJsonValueService.java

fix: add missing checks in the METADATASTORE restrictions

---

dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/OrganisationUnitStructureResourceTable.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/DataValueRowMapper.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/DeflatedDataValueNameMinMaxRowMapper.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/DeflatedDataValueRowMapper.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/objectmapper/OrganisationUnitRelationshipRowMapper.java

A few more gaps identified in the 2.32 conversion of "integer to long" ids.

fix: [DHIS2-9119] [DHIS2-9120] Integer out of ranges for long ids (2.35)

---

dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java

(cherry picked from commit 98e4d3f740590a9bbbf0a9d6ae96008d3e379579)

fix: Predictor fails inside skip test [DHIS2-9149] (#5831)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueService.java
dhis-2/dhis-support/dhis-support-db-migration/pom.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v33/V2_33_26__Fix_encryption_issue_for_TEI_attributeValues.java

port this fixing from https://github.com/dhis2/dhis2-core/pull/5801

fix:(2.33.5) Encryption issue of TEI AttributeValue

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueService.java
dhis-2/dhis-support/dhis-support-db-migration/pom.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v34/V2_34_22__Fix_encryption_issue_for_TEI_attributeValues.java

forward port from https://github.com/dhis2/dhis2-core/pull/5801

fix: (2.34) Encryption issue of TEI AttributeValue

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueService.java
dhis-2/dhis-support/dhis-support-db-migration/pom.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v34/V2_34_22__Fix_encryption_issue_for_TEI_attributeValues.java

porting from https://github.com/dhis2/dhis2-core/pull/5836

fix: (2.34.1) Encryption issue of TEI AttributeValue

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerController.java

* Remove testing features in the TrackerController. (Sync) mode and (empty call)
* Add back the correct security controls on the POST method in the controller.

chore: Revert 8879 testing features

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueService.java
dhis-2/dhis-support/dhis-support-db-migration/pom.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v32/V2_32_34__Fix_encryption_issue_for_TEI_attributeValues.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/META-INF/dhis/beans.xml

backport https://github.com/dhis2/dhis2-core/pull/5836

fix: (2.32) Encryption issue of TEI AttributeValue

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java

This is a small fix for the pagination issue/missing data for the ReportTables and Charts (Favourites) API's.

fix: Fixing pagination for RTable and Chart (Favourites) [DHIS2-9139]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
dhis-2/pom.xml

Updates Artemis and related deps (qpid, proton-j, netty)
* artemis-server 2.14.0
* qpid-jms-client 0.53.0
* proton-j 0.33.6
* netty-all 4.1.52.Final
[DHIS2-8668](https://jira.dhis2.org/browse/DHIS2-8668)

chore: update artemis/qpid deps

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java

backport https://github.com/dhis2/dhis2-core/pull/5764

fix: (2.34)AttributeValue performance issue with fields parameter

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/InterpretationService.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/interpretation/impl/DefaultInterpretationService.java

Fixes https://jira.dhis2.org/browse/DHIS2-8591, backport of #5299 for 2.34

feat: (2.34) Set lastUpdated for interpretations/comments on updateComment [DHIS2-8591]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/InterpretationService.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/interpretation/impl/DefaultInterpretationService.java

Fixes https://jira.dhis2.org/browse/DHIS2-8591, backport of #5299 for 2.33

feat: (2.33) Set lastUpdated for interpretations/comments on updateComment [DHIS2-8591]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/InterpretationService.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/interpretation/impl/DefaultInterpretationService.java

Fixes https://jira.dhis2.org/browse/DHIS2-8591, backport of #5299 for 2.32

feat: (2.32) Set lastUpdated for interpretations/comments on updateComment [DHIS2-8591]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/InterpretationService.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/interpretation/impl/DefaultInterpretationService.java

Fixes https://jira.dhis2.org/browse/DHIS2-8591, backport of #5299 for 2.31

feat: (2.31) Set lastUpdated for interpretations/comments on updateComment [DHIS2-8591]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceFavoritesTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization.json
dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/AbstractPropertyIntrospectorService.java

Backporting it to version (2.34)

fix: Allow negative values for visualization range axis [DHIS2-8896]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/attribute/DefaultAttributeService.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java

https://jira.dhis2.org/browse/DHIS2-9059

fix: (2.33)AttributeValue performance issue with fields parameter

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataImportExportController.java

Block unfiltered export of `/api/metadata` unless
* User has `ALL` authority
* User has `F_METADTA_EXPORT` authority
* User is null (for tests)
[DHIS2-7216](https://jira.dhis2.org/browse/DHIS2-7216)

feat: blocks unfiltered metadata API export unless user is super or has F_METADATA_EXPORT

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
dhis-2/dhis-services/dhis-service-validation/src/test/java/org/hisp/dhis/validation/ValidationNotificationServiceTest.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/PeriodCallable.java

backport https://github.com/dhis2/dhis2-core/pull/5897

fix: (2.33) Error importing data values in first time.

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
dhis-2/dhis-services/dhis-service-validation/src/test/java/org/hisp/dhis/validation/ValidationNotificationServiceTest.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/PeriodCallable.java

backport https://github.com/dhis2/dhis2-core/pull/5897

fix: (2.34) Error importing data values in first time.

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/META-INF/dhis/beans.xml
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
dhis-2/dhis-services/dhis-service-validation/src/test/java/org/hisp/dhis/validation/ValidationNotificationServiceTest.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/PeriodCallable.java

backport https://github.com/dhis2/dhis2-core/pull/5897

fix:(2.32) Error importing data values in first time.

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/incoming/IncomingSmsService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/incoming/IncomingSmsStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/outbound/OutboundSms.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/outbound/OutboundSmsService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/outbound/OutboundSmsStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/hibernate/HibernateIncomingSmsStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/hibernate/HibernateOutboundSmsStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/incoming/DefaultIncomingSmsService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/outbound/DefaultOutboundSmsService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramMessageController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsController.java

New API endpoints for the upcoming SMS app. This PR mostly contains new methods in SmsController class.

fix: Add API endpoints for new SMS app

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodStore.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/aggregate/DataImportTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/period/PeriodServiceTest.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java

backport https://github.com/dhis2/dhis2-core/pull/5969

fix: (2.34) save Period in stateless session

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/DefaultPeriodService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/period/PeriodServiceTest.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/DbmsUtils.java

backport https://github.com/dhis2/dhis2-core/pull/5969

fix: (2.33) save Period in stateless session

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/dataitems/DataItemQueryTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/extensions/MetadataSetupExtension.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportTest.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventImportValidationTests.java
dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json

* fix: remove static get for `ExternalAccessVoter`
* test: fix metadata import
* fix: dataitemqeury tests
* fix: contains ignores case
* test: using constants instead of duplciating id
Co-authored-by: Luciano Fiandesio <luciano@fiandes.io>
(cherry picked from commit 15fde7cae497072c3d22e96af0459e10cb3d473f)

[2.35] test: fix test failures (#6001)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java

* Tweak security headers to align with pre xml to java config refactoring

chore: (2.35) adjust security headers

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventImportTests.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/resources/dhis-web-commons.xml

* Re-enable struts security interceptor
* Disable struts dev mode

chore: add back original struts config

---

dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/WEB-INF/classes/log4j2.xml
dhis-2/dhis-web/dhis-web-commons/src/main/resources/log4j2-jetty.xml

* Reverts to pre xml to java config refactoring log4j settings.

chore: revert log4j config changes

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/handler/CustomExceptionMappingAuthenticationFailureHandler.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationListener.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java

* fix missing error message when login fail
* add back auth logging

chore: fix login error message not showing

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StartupConfig.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/PeriodTypePopulator.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/period/PeriodServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/6043

fix: (2.35) periodType integration test error

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/OidcEnabledCondition.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreIntegrationTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/resources/dhis-web-commons.xml

* Add @Lazy annotation to AuthenticationManger parameter in AuthenticationProviderConfig

chore: try to fix unstable spring dependency wiring problem

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StartupConfig.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/PeriodTypePopulator.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/period/PeriodServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/6043

fix: (2.34) periodType integration test error

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StartupConfig.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/PeriodTypePopulator.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/period/PeriodServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/6043

fix: (2.33) periodType integration test error

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java

* The DefaultOrganisationUnitSelectionManager was missing a service, causing a np

chore: set missing service to DefaultOrganisationUnitSelectionManager

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/OidcEnabledCondition.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java

* Add ifTest check in OIDC condition (config enabler) this was starting the DefaultDhisConfigurationProvider in the integrations tests

chore: add istest to oidcenabled condition

---

dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/update/validation/ExpirationDaysCheckTest.java

(cherry picked from commit 6073423954f00614d59b1a983342d2bbbb34a67c)

[2.35] fix: failing unit test due to invalid period length (#6059)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/AbstractPropertyTransformer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/PropertyTransformer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/transformer/UserPropertyTransformer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroup.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/schema/transformers/UserPropertyTransformerTest.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java

* fix: re-enable property transformer for getMembers
* minor
* fix: minor code fixes, npe checks
* fix: re-fetch schema for transformed properties
* minor fixes
* fix: support field expansion for property transformers
* fix: npe check

feat: support collections for UserPropertyTransformer (#6045)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java

* add missing TwoFactorWebAuthenticationDetailsSource to form login

chore: add missing TwoFactorWebAuthenticationDetailsSource to form login

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineDescriptionTest.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramRuleController.java

Fix program rule validation API to use program id instead of program rule id.

fix: Use program id instead of program rule id

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEngineService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineDescriptionTest.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineServiceTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramRuleController.java

Fix program rule validation API to use program id instead of program rule id.

fix: (2.35) Use program id instead of program rule id

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionItemPageHandler.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/WebOptions.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dimension/DimensionItemPageHandlerTest.java

This implementation adds pagination, to endpoint above, on top of the current queries and existing flow.
Even though the Controller seems to have suffered many changes, this is due to the code formatting style.

feat: [DHIS2-9272] Add pagination to endpoint dimensions/<uid>/items

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/reporttable/DimensionDescriptor.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/reporttable/ReportTable.java
dhis-2/dhis-api/src/test/java/org/hisp/dhis/reporttable/DimensionDescriptorTest.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java

fix: Use orgunit name instead of UID for Report Table download (2.33)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java

* The Spring MVC config lack a multipart resolver, resulting in not being able to upload files like the app management.

chore: add missing multipart resovler

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java

* Due to misconfiguration the custom DHIS2 content negotiation manager would not function as before 2.35
Issue: [DHIS2-9397]

chore: fix broken content negotiation manager config

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/AbstractProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventImporterUserService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ImportStrategyAccumulator.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ProcessingManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ServiceDelegator.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/audit/AbstractEventAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ServiceDelegatorSupplier.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContextLoader.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/postprocess/EventDeleteAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/postprocess/PostDeleteProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/preprocess/PreDeleteProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/postprocess/EventInsertAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/postprocess/PostInsertProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/EventUpdateAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/PostUpdateProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/PreUpdateProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/ImportStrategyAccumulatorTest.java
dhis-2/lombok.config

fix: explaining reason for AbstractEventAuditPostProcessor
fix: added comment to lombok.config
fix: adding @NonNull to component dependencies where explicit constructor was replaced by @RequiredArgsConstructor

fix: audit for event importer are now present

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/AbstractProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventImporterUserService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ImportStrategyAccumulator.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ProcessingManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ServiceDelegator.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/audit/AbstractEventAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ServiceDelegatorSupplier.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContextLoader.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/postprocess/EventDeleteAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/postprocess/PostDeleteProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/preprocess/PreDeleteProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/postprocess/EventInsertAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/postprocess/PostInsertProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/EventUpdateAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/PostUpdateProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/PreUpdateProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/ImportStrategyAccumulatorTest.java
dhis-2/lombok.config

- small refactoring to better accomodate feature
- invoking auditManager after insert, delete, update through Processors mechanism
This is only the implementation, an e2e test will be implemented at later stage (within same jira ticket)

[2.35.0] Tracker Importer audit feature is now present

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/AbstractProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventImporterUserService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ImportStrategyAccumulator.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ProcessingManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ServiceDelegator.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/audit/AbstractEventAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ServiceDelegatorSupplier.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/WorkContextLoader.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/postprocess/EventDeleteAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/postprocess/PostDeleteProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/preprocess/PreDeleteProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/postprocess/EventInsertAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/postprocess/PostInsertProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/EventUpdateAuditPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/PostUpdateProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/PreUpdateProcessorFactory.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/ImportStrategyAccumulatorTest.java
dhis-2/lombok.config

fix: audit for event importer are now present (#6138)
fix: explaining reason for AbstractEventAuditPostProcessor
fix: added comment to lombok.config
fix: adding @NonNull to component dependencies where explicit constructor was replaced by @RequiredArgsConstructor

fix: forward-port to master for DHIS2-9441

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/VisualizationFontStyle.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/visualization/VisualizationStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization.json

New font style configs for:
targetLineLabel
baseLineLabel
seriesAxisLabel
categoryAxisLabel

feat: [DHIS2-9487] Adding support for font style configs

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/VisualizationFontStyle.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/visualization/VisualizationStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization.json

New font style configs for:
targetLineLabel
baseLineLabel
seriesAxisLabel
categoryAxisLabel
**_This is a backport from 2.36 (master)._**

feat: [DHIS2-9487] Adding support for font style configs (2.35)

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/validation/AttributeOptionComboCheck.java

See https://jira.dhis2.org/browse/DHIS2-3602 (including comment from 5/Sep/2020).

fix: DHIS2-3602 Event import AOC error message

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/postprocess/ProgramNotificationPostProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/ProgramNotificationPostProcessor.java

fix: added ProgramNotificationPostProcessor in eventInsertPostProcessorMap
fix: now dryrun flag is considered while importing

fix: DryRun flag and ProgramNotificationPostProcessor (DHIS2-9484)

---

dhis-2/dhis-web/dhis-web-api/pom.xml
dhis-2/pom.xml

fix: [DHIS2-9483] Update FOP deps (2.33)

---

dhis-2/pom.xml

fix: [DHIS2-9483] Update FOP deps (2.34)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java

Added plain json/csv/xml support to dataValueSets api by adding content disposition headers appropriately

feat: [DHIS2-9496] Add content disposition for datavalueset file downloads (master)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/VisualizationFontStyle.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/visualization/VisualizationStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization.json

New font style configs for:
targetLineLabel
baseLineLabel
seriesAxisLabel
categoryAxisLabel
**DO NOT merge it, until approved by the decision board team.**

feat: [DHIS2-9487] Adding support for new font style configs (2.35)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardItemStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/document/DocumentService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dashboard/hibernate/HibernateDashboardItemStore.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/dashboard/DashboardItemDeletionHandler.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/dashboard/impl/DefaultDashboardService.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/document/impl/DefaultDocumentService.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/dashboard/DashboardItemDeletionHandlerTest.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/dashboard/DashboardServiceTest.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DeletionHandler.java

See https://jira.dhis2.org/browse/DHIS2-5584

feat: Cascade Delete Dashboard Items DHIS2-5584

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java

feat: [DHIS2-9496] Add content disposition for datavalueset file downloads (2.35.0)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java

fix: [2.35.0] match bundled filter name to prop

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/postprocess/ProgramNotificationPostProcessor.java

DryRun flag is now considered while importing events
ProgramNotificationPostProcessor is now invoked when inserting new events.

fix: DHIS2-9484 dryrun flag and ProgramNotificationPostProcessor

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventCommentStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventCommentStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventSupport.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/persistence/DefaultEventPersistenceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventCommentStoreTest.java

cherry pick from master of DHIS2-9415

perf: avoid querying programstageinstancecomments if not necessary

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisClientRegistrationRepository.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/AzureAdProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/DhisOidcProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/GoogleProvider.java
dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
dhis-2/pom.xml

* Add support for using Azure AD as an OIDC provider
* Add support for logout session with OIDC providers that support it
* Adjust Authmanager configurations to be explicit for each authentication endpoints
* Remove redundant Lombok dependency in the main pom.xml
* Small adjustment to comments text
Issue: [DHIS2-9346]

feat: add Azure AD OpenID Connect provider support

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java

During event import, the query that fetches user access for programs was using an incorrect join, which
was causing no rows to return.
ref: DHIS2-9584
*PLEASE NOTE: this PR does not contain tests because I wanted to get it out for Geetha to test. I'll add tests in a new PR*

[2.35.0] fix: fix User Access SQL query for programs

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java

During event import, the query that fetches user access for programs was using an incorrect join, which
was causing no rows to return.
(cherry picked from commit 1eaad52e08503ba82b067a2b7ba02bf7e9fec6ad)

[2.35] fix: fix User Access SQL query for programs

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/interceptor/UserContextInterceptor.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java

Please, @netroms , see my comment on DHIS2-9520 for more details about this PR. Thanks!

fix: [DHIS2-9520] Adding user context interceptor to the request flow

---

dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/ProgramRuleDeletionHandler.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/ProgramRuleVariableDeletionHandler.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java

[DHIS2-9023] Block programStage deletion when linked to program rule.

fix: [DHIS2-9023] Block programStage deletion for linked program rule

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java

See https://jira.dhis2.org/browse/DHIS2-9553

feat: Log dashboard favorite views DHIS2-9553

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManagerTest.java

Some data elements, which are not compulsory are returned as NULL values for this query. So, when converting to ZERO, we can face a division by ZERO error. This happens in cases when we have a division operation in the formula and the denominator is set to ZERO (for the cases when they are NULL).
See this comment for more details: https://jira.dhis2.org/browse/DHIS2-8588?focusedCommentId=35764&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-35764

fix: [DHIS2-8588] handling division by ZERO error

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/interceptor/TranslationInterceptor.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/interceptor/UserContextInterceptor.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/interceptor/I18nInterceptor.java

Backporting from master (2.36)

fix: [DHIS2-9520] Adding user DB settings into interceptor (2.35)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/AzureAdProvider.java
dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java

chore: fix typo in OIDC configuration variable

---

dhis-2/dhis-services/dhis-service-administration/pom.xml
dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/HardDeleteAuditTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/audit/AuditIntegrationTest.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditManager.java

backport https://github.com/dhis2/dhis2-core/pull/5756

fix: (2.35) Add audit for hard delete TEI

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_23__Add_sequentialcounter_procedure.sql

Changed flyway script to make it idempotent as its a backported script. Also changed flywayconfig to make it consistent with the earlier xml flyway config (group and mixed setting should ideally be true).

fix: backported flyway script to make it idempotent (2.34)

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java

Already approved and can be merged once all checks are passing.

fix: [DHIS2-9510] Adding back filter support for start/end dates (patch/2.35.0)

---

dhis-2/dhis-web/dhis-web-apps/README.md

This PR updates the feature toggle table according to the changes introduced in #6240.

chore(web-apps): update feature-toggle readme for usage-analytics

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java

backport https://github.com/dhis2/dhis2-core/pull/6268

fix: (2.35) Remove custom serialization for OU.getChildren()

---

.github/workflows/codeql-analysis.yml

* Add default code scanning with CodeQL for Java only, triggered by any pull request.

feat: add codeql-analysis.yml file to setup CodeQL code scanning

---

.github/workflows/codeql-analysis.yml

* Seems like CodeQL won't do scan on master branch properly. Changed syntax of pull req trigger and added a cron trigger (every day at 12:00 PM)

ci: update codeql-analysis.yml on field to trigger properly

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultTranslateSystemSettingManager.java
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm

https://jira.dhis2.org/browse/DHIS2-8712

fix: Missing translations in login page.

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ObjectDeletionRequestedEvent.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java

https://jira.dhis2.org/browse/DHIS2-9575

fix: Skip deletionHandler for sharing objects.

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardItem.java

backport https://github.com/dhis2/dhis2-core/pull/6305

fix: (2.35) Deserialization issue of DashboardItem.users

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardItem.java

backport https://github.com/dhis2/dhis2-core/pull/6305

fix: (2.35.0) Deserialization issue of DashboardItem.users

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericGatewayParameter.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericHttpGatewayConfig.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsGatewayConfig.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java

Include confidential parameters in response while fetching SMS configurations.

fix: SMS confidential values [DHIS2-9582]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManagerTest.java

Backporting it from the current master.

fix: [DHIS2-8588] handling division by ZERO error (2.35)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryRuntimeException.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManagerTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CrudControllerAdvice.java

Backporting it from the current master.

fix: [DHIS2-8588] handling division by ZERO error (2.33)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ObjectDeletionRequestedEvent.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java

backport https://github.com/dhis2/dhis2-core/pull/6307

fix: (2.35) Skip deletionHandler for sharing objects.

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/DHIS2BasicAuthenticationEntryPoint.java

* A small PR comment change seems to have get lost when merging/backporting changes

chore: align 2.35 and master, with missing change from 2.35

---

dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java

(cherry picked from commit 3262cbbb35cb809134f84dc98f6a7822f32db473)

Fix: Keep validating despite analytics errors DHIS2-4326 (#3661)

---

dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/popup.vm
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-mobile/src/main/webapp/dhis-web-maintenance-mobile/javascript/gateway.js
dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-mobile/src/main/webapp/dhis-web-maintenance-mobile/updateGateway.vm

Fixes DHIS2-9730, DHIS2-9731, DHIS2-9732
PR adds
-  correct URL for i18n scripts in new java based web security configurations.
- Update velocity template for generic http gateway UI

fix: (2.35.0) Add correct URL for i18n javascript to fix legacy SMS app issues

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java

Backporting from master (2.34)

fix: [DHIS2-9510] Adding back filter support for start/end dates

---

dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/popup.vm
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-mobile/src/main/webapp/dhis-web-maintenance-mobile/javascript/gateway.js
dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-mobile/src/main/webapp/dhis-web-maintenance-mobile/updateGateway.vm

Fixes DHIS2-9730, DHIS2-9731, DHIS2-9732
PR adds
- correct URL for i18n scripts in new java based web security configurations.
- Update velocity template for generic http gateway UI

fix: (2.35) Add correct URL for i18n javascript to fix legacy SMS app issues

---

dhis-2/pom.xml

chore: Upgrade Spring Core and Security to latest versions

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationRule.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceTest.java

feat: make ValidationRule instruction property translatable [DHIS2-8669]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java

Change JobStatus to DISABLED while disabling JobConfigurations.

fix: Change JobStatus while disabling JobConfiguration [DHIS2-9783]

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java

Backporting from master into (2.33)

fix: [DHIS2-9737] Default to start/end dates params for periods sum/avg

---

dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementerTest.java
dhis-2/pom.xml

This is required to bring the fix related to non-terminating decimal expansion. (2.34)
Relates to this fix:
https://github.com/dhis2/dhis2-antlr-expression-parser/pull/14/files

fix: [DHIS2-9826] Apply latest version of rules-engine/antlr-parser

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisClientRegistrationRepository.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcClientRegistration.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/AzureAdProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/GoogleProvider.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/btn_azure_login.svg
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/action/LoginAction.java

feat: Add Azure AD OIDC login button to front/login page

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/JacksonTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java

(cherry picked from commit c9402e1160a694d25d6b9c08d48f6d3b9c219374)

fix: bidirectional relationship are now saved properly (#6411)

---

dhis-2/pom.xml

(cherry picked from commit a6af8be69687a18ed17d76930fd2daaecc8129ba)

chore: Upgrade Spring Core and Security to latest versions (#6376)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleAction.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRuleAction.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_7__Add_translations_column_into_programruleaction_table.sql

feat: Add translation to ProgramRuleAction on the content field

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java

(cherry picked from commit 3fb60c0914fe4262434b72324e617e428f741c1a)

fix: DHIS2-3602 Event import AOC error message (#6097)

---

dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/StreamUtils.java
dhis-2/dhis-web/dhis-web-api/pom.xml
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IconController.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java

* Close file descriptors to prevent leak for app resources that leads to unusable DHIS 2 instance.	
Issue:[DHIS2-9939]

fix: Close files used by apps controller

---

dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java

fix the code to make handleEmbeddedObject run after the object has been initialized.

fix: handleEmbeddedObject for audit

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java

https://jira.dhis2.org/browse/DHIS2-9949

fix: Cant import dataValues with new period

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/Module.java

Forward-port of #6415 which was released in 2.35.0

fix: don't append duplicate app name to icon url in Module (DHIS2-9786) [2.36]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/6680

fix: (2.35)Cant import dataValues with new period

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/Module.java

Forward port of #6415 which was released in 2.35.0

fix: don't append duplicate app name to icon url in Module (DHIS2-9786) [2.35]

---

dhis-2/pom.xml

* Remove --illegal-access=permit from argLine property when JDK8 is in use

fix: Fix broken maven profile for intgr. test on jdk 11

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/6680

fix: (2.33) Cant import dataValues with new period

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/period/hibernate/HibernatePeriodStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/6680

fix: (2.34) Cant import dataValues with new period

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java

The generated query misses the open/close quote for each uid 
`DELETE FROM programstageinstance where uid in ( 'PS2iwSwQhkS,la9InMfolxp');`

fix: Cant delete events

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java

backport https://github.com/dhis2/dhis2-core/pull/6729

fix: (2.35) Cant delete events

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackerBundleParamsConverter.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerImportReport.java

Also fixes the Tracker Param converter to skip generation of UIDs for events and enrollments properties.
REF: DHIS2-9981

fix: add global import stats to Tracker import payload response

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AbstractTrackerDtoValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java

fix: add validation for tei type on relationship constraint

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerWarningReport.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleImportReportTest.java

Added annotations to assist Jackson into serializing and deserializing TrackerWarningReports in the TrackerImportReport. Test is updated.

fix: [DHIS2-10013] Deserializing warning reports in TrackerReport

---

dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/PeriodOffset.java

(cherry picked from commit b55195a667645da6f2c3bb0d75b5667541981a04)

refactor: periodOffset is not greatest or least (#6578)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java

Actually a backport of https://github.com/dhis2/dhis2-core/pull/6766 , but some minor changes because this piece has been refactored heavily in 2.35 and master.

fix: [DHIS2-9985] Align ownership OU check for TEI APIs even when specifying uids explicitly (2.34)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/SmsUtilsTest.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SmsUtils.java

feat: (2.34) Add support for SMS text encoding [DHIS2-10040]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/SmsUtilsTest.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SmsUtils.java

Backporting JIRA # DHIS2-10040

feat: (2.35) Add support for SMS text encoding [DHIS2-10040]

---

dhis-2/dhis-services/dhis-service-tracker/pom.xml
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramStageInstanceProgramStageMapSupplier.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationConfig.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationContext.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHookTest.java

fix: Check if there are more than one event in not repeatable Program Stages in the payload [DHIS2-10021]

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java

Currently, when we have the Periods defined as a filter and the DataSet has period type set to Daily, the calculation does not work. This change will consider multiple daily Periods as a filter and fix this issue. (2.35)
Porting from branch 2.34

fix: DHIS2-10082: Fix daily reporting rate calculation

---

dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/DefaultProgramRuleEntityMapperService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ErrorWarningImplementer.java

Improve rule engine validation error message

fix: rule engine error meessages (DHIS2-10107)

---

dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/entry.js

(cherry picked from commit 808f3f8957f4c7c1ddfb0a29eeed9f5249ed16ab)

fix: Leading decimal number data entry DHIS2-2510 (#6821)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectManager.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java

Remove clearSession/clearCache inside transaction causing audit fail.

fix: Remove clearSession/clearCache inside transaction causing audit fail

---

dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramStageInstanceProgramStageMapSupplier.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/tei_enrollment_event.json
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportParamsBuilder.java

- Fix skipRuleEngine flag in tracker import parameters
- Fix ProgramStage preheat list to validate repeated events

fix: Filter by program stage in rule engine [DHIS2-10105]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-core/pom.xml
dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/outlierdetection/OutlierDetectionService.java
dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/outlierdetection/OutlierValue.java
dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/outlierdetection/service/DefaultOutlierDetectionService.java
dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/outlierdetection/service/OutlierDetectionManager.java
dhis-2/dhis-services/dhis-service-validation/src/test/java/org/hisp/dhis/outlierdetection/service/OutlierDetectionServiceTest.java
dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/config/JacksonObjectMapperConfig.java
dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/TextUtils.java
dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/util/TextUtilsTest.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/JacksonCsvUtils.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/outlierdetection/OutlierDetectionController.java

Adds CSV format support for outlier detection API.

feat: Add CSV format support for outlier detection API

---

dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/AuditScheduler.java

The Audit system may use a queue (disabled by default) to buffer Audit messages before these are de-queued to
the Artemis broker.
This PR makes the queue bound to 200 items and lowers the de-queue delay to 5 seconds, to avoid excessive memory pressure
during large imports.

fix: made the Audit queue buffer bounded

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/AssignValueImplementer.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ErrorWarningImplementer.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/IssueType.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ProgramRuleIssue.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/RuleActionImplementer.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/RuleActionValidator.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/SetMandatoryFieldValidator.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowErrorOnCompleteValidator.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowErrorValidator.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowWarningOnCompleteValidator.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/ShowWarningValidator.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentRuleValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventRuleValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/ValidationUtils.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/SetMandatoryFieldValidatorTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ShowErrorWarningImplementerTest.java
dhis-2/pom.xml

- Unignore rule engine test
- Make it possible for rule engine validators to return warning and errors at the same time

fix: Fix rule engine tests and validators

---

dhis-2/pom.xml

chore: Upgrade Struts2 to 2.5.26

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/AttributeMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/DataValueMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/DomainMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/EnrollmentMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/EventMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/NoteMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/ProgramOwnerMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/RelationshipItemMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/RelationshipMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/TrackedEntityMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/web/PagingWrapper.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceCriteria.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerControllerSupport.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerExportController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerTrackedEntitiesExportController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/DefaultContextService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/TrackedEntityInstanceSupportService.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportControllerTest.java

Ticket includes also other endpoints, so this can be basically be considered as a WIP, but I'd like some review on this.
Also, old endpoints had an acl-based fields filtering capability which it's pretty complex to understand and to port into new endpoints. If that's a feature that is still needed we can discuss how to implement it and implement in a separate ticket

Dhis2 10093  - New Tracker Importer GET endpoints

---

dhis-2/pom.xml

chore: Upgrade Hibernate from 5.4.26 to 5.4.27

---

dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultSchemaService.java

* Bug caused by change related to Hibernate upgrade and change in Class name lookup

fix: Resolve core interfaces in getDynamicSchema

---

dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java

See Jira ticket comment from 30/Nov/2020 at https://jira.dhis2.org/browse/DHIS2-4326#comment-37706

fix: trap all validation analytics errors

---

dhis-2/dhis-api/pom.xml
dhis-2/pom.xml

chore: Upgrade Hibernate validation

---

dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/SmsUtilsTest.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SmsUtils.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsController.java

JIRA # [DHIS2-9941]
Backport for 2.33.

fix: (2.33) Process SMS when phoneNumber is not linked to originator [DHIS2-9941]

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java

Filter out null options in OptionSet to fix null exception in metadata import

fix: NPE in metadata import [DHIS2-10200]

---

dhis-2/pom.xml

* Make variables for all dependencies in the properties section of the root pom.

chore: Reorganize dependencies versions in the root pom

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/preprocess/AbstractUserInfoPreProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/preprocess/UserInfoUpdatePreProcessor.java

Before this fix all existing event DataValues were updated with current "LastUpdatedUserInfo" even if just one was passed by frontend.
Also, during update, when a DataValue already existed, the createdByUserInfo was wrongly set to null.

fix: DHIS2-8911 correct Event data values createdByUserInfo behaviour

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationListener.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineListener.java

Backporting JIRA #DHIS2-9935 to 2.34

fix: (2.34) Send message rule action when stage is part of registration

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java

See description in https://jira.dhis2.org/browse/DHIS2-10219

fix: Use regex to explode indicators DHIS2-10219

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java

(cherry picked from commit 81971d265b06d26de25f3be6be4568c35a9ee44a)

fix: Use regex to explode indicators DHIS2-10219 (#7069)

---

dhis-2/dhis-support/dhis-support-system/src/main/resources/push-analysis-main-html.vm

fix(push-analysis): (master) don't render pivot table visualization as img [DHIS2-10166]

---

dhis-2/dhis-support/dhis-support-system/src/main/resources/push-analysis-main-html.vm

fix(push-analysis): (2.35) don't render pivot table visualization as img [DHIS2-10166]

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java

This will fix the problem, however ProgramRuleVariables are at the moment only calculated on values present in the payload.
This is something that probably needs to be reviewed in the context of the merge-strategy for attributes and data values.

fix: Fix data values conversion for event [DHIS2-10173]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentityattributevalue/hibernate/TrackedEntityAttributeValue.hbm.xml
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v32/V2_32_38__Add_teav_btree_index.java

(cherry picked from commit 84b64ff819689c399480cde99df7c9f175024b27)

fix: add teav index and service check for value length

---

docker/tomcat-alpine/Dockerfile
docker/tomcat-debian/Dockerfile

Forward-port of #7052 - will tag a Jira issue when we decide where to put Docker issues
Error before this fix

fix(docker): (master) add fontconfig to Tomcat Docker images

---

dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementer.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionScheduleMessageImplementer.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java

PR will fix send/schedule messages for event programs.

fix: send/schedule message for program without registration [DHIS2-10127]

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java

fix: DHIS2-9839: Data elements sorting in event report (2.35)

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java

fix: DHIS2-9839: Data elements sorting in event report (2.34)

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java

fix: DHIS2-9839: Data elements sorting in event report (2.33)

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserPaginationTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/InMemoryQueryEngine.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java

- Add skipPaging for in memory engine. 
- `queryService.query(line 182)` in `UserController.getEntityList` should not apply paging if filter parameter is empty
- `userStore.getUserCount` should not apply paging parameters
- Add e2e api test

fix: Fix paging issue in UserController [DHIS2-10135]

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserPaginationTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/InMemoryQueryEngine.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java

backport https://github.com/dhis2/dhis2-core/pull/7105

fix:(2.34) paging issue in UserController

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserPaginationTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/InMemoryQueryEngine.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java

backport https://github.com/dhis2/dhis2-core/pull/7105

fix:(2.34.3) paging issue in UserController

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java

See https://jira.dhis2.org/browse/DHIS2-10220

fix: Search users across first + last names

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserPaginationTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/InMemoryQueryEngine.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java

backport https://github.com/dhis2/dhis2-core/pull/7105

fix: (2.35) paging issue in UserController

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java

(cherry picked from commit 43710af3e6d6c19534d282528eee23474c742435)

fix: Search users across first + last names (#7106)

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/MetadataPaginationActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserPaginationTest.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/InMemoryQueryEngine.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java

backport https://github.com/dhis2/dhis2-core/pull/7124

fix: (2.33) paging issue in UserController

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vDueDate.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java

Fetch event column `duedate` while using Enrollment type analytics.

fix: Error while using V{due_date} in Enrollment type analytics [DHIS2-9787]

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerImporterServiceTest.java

skipSideEffect flag was removed in previous refactors. This PR just re-implement it.

fix: Add skipSideEffects flag for new importer [DHIS2-9269]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java

Urgent fix to discard ou validation when explicit tei uids are specified

fix: [DHIS2-10318] explicit uids need not require ou to be specified for tei endpoint (2.36)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java

The in-memory Pagination was not taking filters into consideration.

fix: DHIS2-10319: Fixing pagination in dimension /items endpoint.

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vDueDate.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java

fix: (2.34) Error while using V{due_date} in Enrollment type analytics

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vDueDate.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java

fix: (2.35) Error while using V{due_date} in Enrollment type analytics

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java

See https://jira.dhis2.org/browse/DHIS2-10291

feat: Constrain dashboard context menu items

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/FileTypeValueOptions.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueTypeOptions.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/ValueTypeOptionsTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataelement/DataElementWithValueTypeOptionsTest.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/StAXNodeSerializer.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/BeanRandomizer.java

chore: Apply re-formatter on DHIS2-1024

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vEnrollmentStatus.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java

fix: (2.35) Use correct column name for enrollment_status in event analytics

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vEnrollmentStatus.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java

fix: (2.34) Use correct column name for enrollment_status in event analytics

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceIntegrationTest.java

See https://jira.dhis2.org/browse/DHIS2-10336

fix: Validation/dataElement/COC bug DHIS2-10336

---

dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java

backport https://github.com/dhis2/dhis2-core/pull/7224

fix: (2.34) Audit error for deleting Visualization

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java

backport https://github.com/dhis2/dhis2-core/pull/7001

fix: (2.35) Audit error when delete Visualization 

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vEnrollmentStatus.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java

fix: (2.33) Use correct column name for enrollment_status [DHIS2-10346]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vDueDate.java

fix: (2.33) Error while using V{due_date} in Enrollment type analytics [DHIS2-9787]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GatewayAdministrationService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericGatewayParameter.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/BulkSmsHttpGateway.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/ClickatellHttpGateway.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/DefaultGatewayAdministrationService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/BulkSmsGatewayTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/config/GatewayAdministrationServiceTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsGatewayController.java
dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-mobile/src/main/webapp/dhis-web-maintenance-mobile/javascript/gateway.js
dhis-2/dhis-web/dhis-web-maintenance/dhis-web-maintenance-mobile/src/main/webapp/dhis-web-maintenance-mobile/updateGateway.vm

fix: (2.34) Use encryption for SMS confidential parameters [DHIS2-10076]

---

.github/codeql/codeql-config.yml

chore: Adjust CodeQL config

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramStageInstanceProgramStageMapSupplier.java

- The query is now considering only the Enrollments present in the paylaod

fix: [DHIS2-10388] Improve query to get PI/PS map in supplier

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MessageConversationController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java

(cherry picked from commit ebe7130f94b68d606ff7ab9ee33a1616a0240cca)

BACKPORT 2.35 - fix: set HTTP response code for POST methods not returning anything [DHIS2-10010] (#7243)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceIntegrationTest.java

* fix: Validation/dataElement/COC bug DHIS2-10336
* fix: Validation/dataElement/COC bug DHIS2-10336
* fix formatting
* fix: Remove unused variable in test case
* fix: un-collapse imports
(cherry picked from commit dea3403ac74045a765d87996b83f9dc652d73b73)

fix: Validation/dataElement/COC bug DHIS2-10336 (#7173)

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRuleVariable.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_25__Add_translation_to_program_rule_variable.sql

* Adds `translations` property to `ProgramRuleVariable.hbm.xml`
* Adds flyway script to add `translations` to `programrulevariable`
Support translation of ProgramRuleVariable [DHIS2-10055](https://jira.dhis2.org/browse/DHIS2-10055)

feat: support ProgramRuleVariable translations

---

dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/configuration/NotifierConfiguration.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/configuration/RedisConfiguration.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/LeaderElectionConfiguration.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/DefaultSessionConfiguration.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/configuration/RedisSpringSessionConfiguration.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/configuration/SpringHttpSessionInitializer.java

Backport of spring session fix

fix: [TECH-528] spring sessions backed by redis (2.35)

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerBundleReportMode.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/UniqueAttributesSupplier.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleReportModeTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportController.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportControllerTest.java

[Dhis2 10381](https://jira.dhis2.org/browse/DHIS2-10381) : Tracker importer returns 200 when import failed
Work done ;

fix: Dhis2 10381

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/EmailMessageSender.java

Adds server.base.url in password reminder emails.

fix: (2.33) Add reference to base URL in password reminder email

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/DisableInactiveUsersJobParameters.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/jackson/DisableInactiveUsersJobParametersDeserializer.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/DisableInactiveUsersJob.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java

Adds a new job type to the scheduler.
The job allows to mark users disabled that have not been active for a configurable number of months.
Inactivity is evaluated based on their `lastLogin` timestamp and the current time.
A DB update statement is used to change the `disabled` flag column for matching users.
Users that have no lastLogin set (null) are not disabled. This might very well be a theoretical case that does not exist in practice.
The service layer will not perform the operation if a date is given that is not at least 1 month in the past to prevent accidentally disabling all users by passing in a data in the future or the very recent past.
A spring based test was added to verify the correct behaviour of the new `UserService#disableUsersInactiveSince` method.
In this context the …

feat: job to disable inactive users [DHIS2-6720]

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/UserGroupMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementer.java

https://jira.dhis2.org/browse/DHIS2-10431

fix: remove members from user group mapper in the Preheat

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DataValueSMSListener.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/DataValueListenerTest.java

Dataset submission through SMS command is processed but the response messages were incorrect.

fix: Send correct feedback once SMS command is processed

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/PeriodOffsetUtils.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/PeriodOffsetUtilsTest.java

See https://jira.dhis2.org/browse/DHIS2-10441

fix: Allow negative .periodOffset() offsets

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java

Backport of https://jira.dhis2.org/browse/DHIS2-10415: Cache constant map for performance

fix: Cache constant map for performance

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/outbound/GatewayResponse.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/BulkSmsHttpGateway.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SimplisticHttpGetGateWay.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SmsGateway.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/GenericSmsGatewayTest.java

fix: (2.34) Add basic authentication support to SMS gateway [DHIS2-10446]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/hibernate/HibernateOrganisationUnitGroupStore.java

Broken query found in context of #7341 .

fix: backport for broken HQL query OU with group sets [DHIS2-10408]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dimension/DimensionController.java

fix: DHIS2-10319: Fix pagination in dimension/items endpoint (2.35)

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerImportParams.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerNotificationThread.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/DefaultTrackerImportService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportReportRequest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/strategy/tracker/imports/impl/TrackerImportStrategyImpl.java
dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/strategy/tracker/imports/TrackerImportStrategyHandlerTest.java

fix: Dhis2 10432

---

dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/hibernate/HibernateDataStatisticsEventStore.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/datastatistics/DataStatisticsEventStoreTest.java

This PR continues the work for https://jira.dhis2.org/browse/DHIS2-10447, in two areas that were not yet working correctly:
1. For dataStatistics/favorites/{uid}, it was always including both DASHBOARD_VIEWs and PASSIVE_DASHBOARD_VIEWs. This has now been fixed so that it will include PASSIVE_DASHBOARD_VIEWs only if the system setting _keyCountPassiveDashboardViewsInUsageAnalytics_ says to do so.
2. For dataStatistics/favorites?eventType=... it was returning the same results for both DASHBOARD_VIEWs and PASSIVE_DASHBOARD_VIEWs. This has now been fixed so it returns the count only for the eventType specified.
Unit tests have been written for these, and they have also been tested through the Web API.

fix: Dashboard not logging first use - followup

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupInfoService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupInfoStore.java
dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserGroupInfoService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserGroupInfoInfoStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserGroupInfoStoreTest.java

forward port from https://github.com/dhis2/dhis2-core/pull/7405

fix: (2.35) acl performance with userGroup.members()

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramStageInstanceProgramStageMapSupplier.java

Checking for duplicate event in a program without registration doesn't make sense.
When a program is a registration, when the supplier runs to get the event present in a program stage for an enrollment, the enrollment field must be populated, otherwise it will be caught in the validation phase as an error.

fix: Preheat data to check multiple events only for registration progam [TECH-537]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java

Extracted from #7413 as the changes that should be back-ported.
These fixes have nothing to do with the goals of DHIS2-10407 but were defects found while working on it.

fix: explicitly set HTTP response status for methods returning void [DHIS2-10407]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java

fix: explicitly set HTTP response status for methods returning void [DHIS2-10407] (#7435)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java

Pagination is not showing the correct number of total items.

fix: DHIS2-10480: Fixing pagination

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/OAuth2ConfirmAccessController.java
dhis-2/dhis-web/dhis-web-api/src/main/resources/confirm_access.vm
dhis-2/dhis-web/dhis-web-api/src/main/resources/error.vm

Issue: [https://jira.dhis2.org/browse/DHIS2-10169](https://jira.dhis2.org/browse/DHIS2-10169)

fix: Repair broken OAuth2 authorization_code flow

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleAction.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRuleAction.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_31__Add_translations_column_into_programruleaction_table.sql

backport https://github.com/dhis2/dhis2-core/pull/6459

feat: (2.35) Add translation capability to ProgramRuleAction

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleAction.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRuleAction.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_36_33__Add_translations_column_into_programruleaction_table.sql

backport https://github.com/dhis2/dhis2-core/pull/6459

feat: (2.34) Add translation capability to ProgramRuleAction on the content

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java

backport https://github.com/dhis2/dhis2-core/pull/7416

fix: (2.35) translation is not saved in first time

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java

backport https://github.com/dhis2/dhis2-core/pull/7416

fix: (2.34) translation is not saved in first time

---

dhis-2/pom.xml

Changelog: [https://github.com/hibernate/hibernate-orm/compare/5.4.28...master](https://github.com/hibernate/hibernate-orm/compare/5.4.28...master)

chore: Upgrade Hibernate

---

dhis-2/pom.xml

chore: Upgrade Spring Security

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstagefilter/ProgramStageInstanceFilter.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilter.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programstagefilter/hibernate/ProgramStageInstanceFilter.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentityfilter/hibernate/TrackedEntityInstanceFilter.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_33__Add_translations_column_to_trackedEntityInstanceFilter_table.sql

https://jira.dhis2.org/browse/DHIS2-10556
Add translations for TrackedEntityInstanceFilter and ProgramStageInstanceFilter

feat: Add translations column for TEI and Event Filter

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstagefilter/ProgramStageInstanceFilter.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilter.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programstagefilter/hibernate/ProgramStageInstanceFilter.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentityfilter/hibernate/TrackedEntityInstanceFilter.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_30__Add_translations_column_to_trackedEntityInstanceFilter_table.sql

backport https://github.com/dhis2/dhis2-core/pull/7459

feat: (2.35) Add translations column for TEI and Event Filter

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programstagefilter/ProgramStageInstanceFilter.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilter.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programstagefilter/hibernate/ProgramStageInstanceFilter.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentityfilter/hibernate/TrackedEntityInstanceFilter.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_32__Add_translations_column_to_trackedEntityInstanceFilter_table.sql

backport https://github.com/dhis2/dhis2-core/pull/7459

feat: (2.34) Add translations column for TEI and Event Filter

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/Translatable.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/chart/impl/DefaultChartService.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/AnnotationUtils.java

backport https://github.com/dhis2/dhis2-core/pull/7476

feat: (2.36) Add translations for Chart objects

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DhisApiVersion.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java

[DHIS2-10602](https://jira.dhis2.org/browse/DHIS2-10602)

feat: expose Api version for DHIS 2.37

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java

backport https://github.com/dhis2/dhis2-core/pull/7416

fix: (2.33) translation is not saved in first time

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleAction.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRuleAction.hbm.xml
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_34_36__Add_translations_column_into_programruleaction_table.sql

backport https://github.com/dhis2/dhis2-core/pull/6459

feat: (2.33) Add translation capability to ProgramRuleAction on the content

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java

https://jira.dhis2.org/browse/DHIS2-10487
Issue: Apps name in header menu aren't updated when user changes UI locale.
Fix: add function to detect locale change and update apps displayName.

fix: Detect locale change for apps menu

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java

backport https://github.com/dhis2/dhis2-core/pull/7493

fix: (2.36) Detect locale change for apps menu

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerObjectsDeletionService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerObjectDeletionServiceTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/tracker_basic_data_before_deletion.json
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/tracker_data_for_deletion.json

PR fixes exception when deleting tracker objects specifically when deletion payload contains more than one tracker entity.

fix: (2.36) Correct error report when using DELETE ImportStrategy [DHIS2-9085]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java

This will bring back the performance and filtering to the same level as other endpoints.

fix: Filtering issue for ReportTable and Chart

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/MaintenanceActions.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/TestCleanUp.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/ImportStrategyTests.java
dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teiAndEnrollment.json
dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teiWithEnrollmentAndEventsNested.json
dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teis.json
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerObjectsDeletionService.java

fix: (2.36) Update enrollment when deleting event [DHIS2-9085]

---

dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryType.java
dhis-2/dhis-support/dhis-support-hibernate/src/test/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryTypeTest.java

* fix: content-aware jsonb equal() implementation [DHIS2-10622]
* fix: unit test and minr peer review changes [DHIS2-10622]

fix: content-aware jsonb equals() implementation [DHIS2-10622] (#7531)

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/DataElementMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityAttributeMapper.java

authored-by: luca <luca@dhis2.org>
Work done:
[x] porting of https://github.com/dhis2/dhis2-core/pull/7556 to 2.36

fix: [DHIS2-10452] porting to 2.36 fix_1 adds options to mapper (#7556)

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/RelationshipImportTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterServiceTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheServiceTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/BidirectionalRelationshipsPreProcessorTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventDefaultEnrollmentPreProcessorTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/relationshipToUpdate.json
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/relationships.json
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/simple_metadata.json
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java

Add tests to improv coverage for:
- RelationshipPersister
- BidirectionalRelationshipsPreProcessor
- DefaultPreheatCacheService

chore: Improve test coverage in tracker service project [TECH-553]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java

The endpoint GET /charts is not being post-processed as it should and a few attributes are missing in the response object.

fix: DHIS2-10648: Add post-processing for 'plural GET' endpoint.

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java

The endpoint GET /charts is not being post-processed as it should and a few attributes are missing in the response object.

fix: Add post-processing for 'plural GET' endpoint [DHIS2-10648]

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_1__Add_Deferred_Constraint_to_Interpretation_Comments_Table.sql

See the ticket for more details.
This comment explains the reason for this PR: https://jira.dhis2.org/browse/DHIS2-8256?focusedCommentId=39912&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-39912

fix: DHIS2-8256: Fixing interpretation comment deletion

---

dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java

This issue is related to List gaps containig null elements. This was already fixed upstream. I'm bringing the same fix to 2.34

fix: DHIS2-10646: Backport fix for known NPE

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/TrackerApiResponse.java
dhis-2/dhis-e2e-test/src/main/resources/config.properties
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiValidationTests.java
dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/OptionSetMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityAttributeMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AbstractTrackerDtoValidationHook.java

DHIS2-10452 porting to 2.36 - option set validation fix 3 - adds option set mapper

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserAccess.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupAccess.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserAccess.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserGroupAccess.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserGroupService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserGroupServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserStoreTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplierAclIntegrationTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/JacksonPropertyIntrospector.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java

backport https://github.com/dhis2/dhis2-core/pull/7417

fix: (2.36) Sharing section is missing in program access page

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/TrackerApiResponse.java
dhis-2/dhis-e2e-test/src/main/resources/config.properties
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiValidationTests.java
dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/OptionSetMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityAttributeMapper.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AbstractTrackerDtoValidationHook.java

fix: [DHIS2-10452] option set validation fix_3 : adds option set mapper and e2e tests

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_36__Update_VISUALIZATION_VIEW_in_datastatisticsevent_table.sql

https://jira.dhis2.org/browse/DHIS2-10642

fix: Update VISUALIZATION_VIEW records in datastatisticsevent table [2.36]

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_3__Update_VISUALIZATION_VIEW_in_datastatisticsevent_table.sql

forward port from https://github.com/dhis2/dhis2-core/pull/7602

fix: update VISUALIZATION_VIEW records in datastatisticsevent

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/CatOptionComboStrategy.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/CatOptionStrategy.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/OrgUnitStrategy.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/ProgramStageStrategy.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/ProgramStrategy.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/RelationshipTypeStrategy.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/StrategyFor.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/TrackedEntityTypeStrategy.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/AbstractSchemaStrategyCachingTest.java

* Add specific cache capacity for all preheat caches. lower the default cache capacity
* fix: typo
* fix: Fixed failing tests
(cherry picked from commit 4b36ab6a72402f0342a160fcac5688482bb54a04)

fix: Adjust preheat caches for new tracker importer (#7606)

---

dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java

(cherry picked from commit ebdc2d2d97fd1fa83df4c475946dbe93137c2ae5)

fix: Prediction test timeouts for CI DHIS2-9317 (#7593)

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/MessageConversationsActions.java
dhis-2/dhis-e2e-test/src/main/resources/config.properties
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/RuleEngineTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/SideEffectsTests.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionAssignValueImplementer.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java

fix: (2.36) Handle lazy exception for program rule notifications (#7601)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeServiceTest.java

fix: [DHIS2-10683] null pointer exception on value type validation old tracker 2.36

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeServiceTest.java

see [2.36 fix](https://github.com/dhis2/dhis2-core/pull/7623)

fix: [DHIS2-10683] null pointer exception on value type validation old tracker Master

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
dhis-2/dhis-e2e-test/src/test/resources/tracker/acl/metadata.json
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java

Revert "fix: validate whether tei query params has either program or tet specified (2.35)"

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java

Revert "fix: validate whether tei query params has either program or tet specified (2.34)"

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java

backport https://github.com/dhis2/dhis2-core/pull/7493

fix: detect locale change for apps menu [2.35]

---

dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/webportal/module/DefaultModuleManager.java

backport https://github.com/dhis2/dhis2-core/pull/7493

fix: detect locale change for apps menu [2.34]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/chart/impl/DefaultChartService.java

backport https://github.com/dhis2/dhis2-core/pull/7476

feat: enable translation for chart objects [2.34]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/chart/impl/DefaultChartService.java

backport https://github.com/dhis2/dhis2-core/pull/7476

feat: enable translation for chart objects [2.33] 

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleVariableService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/postprocess/PublishEventPostProcessor.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleVariableService.java
dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/ProgramRuleVariableServiceTest.java

fix: Cache to check if a data element has a link with program rule variable

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityAttributeService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeServiceTest.java

see https://github.com/dhis2/dhis2-core/pull/7623

fix: [DHIS2-10683] null pointer exception on value type validation old tracker 2.36.0

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/7663

fix: change translation properties key same to 2.36 [2.33]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/BaseChart.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java

backport https://github.com/dhis2/dhis2-core/pull/7663

fix: change translation properties key same to 2.36 [2.34]

---

dhis-2/pom.xml

chore: Upgrade dependencies with known security issues

---

dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java

fix: ensure each cache region is only created once [2.36]

---

dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java

fix: ensure each cache region is only created once [2.36.0]

---

dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/security/JwtBearerTokenTest.java

chore: Fix broken JWT test

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dxf2/events/event/EventContext.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityProgramOwnerIds.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityProgramOwnerService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/DefaultOrganisationUnitService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityProgramOwnerService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityProgramOwnerStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventServiceContextBuilder.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java

* perf: reduce queries performed by eventRows
fix: partitioned query to avoid errors and other minor optimizations

perf: reduce queries performed by eventRows (#7671)

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/acl/TrackedEntityInstanceAclReadTests.java
dhis-2/dhis-e2e-test/src/test/resources/tracker/acl/metadata.json
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityinstance/TrackedEntityInstanceQueryTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java

Revert "fix: validate whether tei query params has either program or tet specified (2.36)"

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/preprocess/ProgramStagePreProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportWithMetadataTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/create_program_stages.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/csv/events_import_code.csv
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/events-5b.csv

see https://github.com/dhis2/dhis2-core/pull/7666

fix: [DHIS2-10022] event import fails idScheme=code porting 2.37

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/preprocess/ProgramStagePreProcessor.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportWithMetadataTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/create_program_stages.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/csv/events_import_code.csv
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/events-5b.csv

see https://github.com/dhis2/dhis2-core/pull/7666

fix: [DHIS2-10022] event import fails idScheme=code porting 2.36

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonGrid.java
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsControllerTest.java
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/EventAnalyticsControllerTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java

Introduces a criteria parameter record `EnrollmentAnalyticsQueryCriteria` and cleans up creation of `EventQueryParams` from the criteria. 
Tests were added for the modified controllers to make sure they generally work and forwards their query parameters to the service.

chore: introduce criteria for enrollment analytics controller [TECH-551]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java

Opted to only backport the actual fix manually as the testing added depends on further additions to test utilities that would then also need backporting.

fix: backport workaround for skipSharing and skipTranslation for putJsonObject [DHIS2-10660] (2.36.0)

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_4__Update_ou_path_index.sql

https://jira.dhis2.org/browse/DHIS2-10697

fix: Update organisationunit.path index

---

dhis-2/pom.xml

Not really sure what else need doing. With this change one can use
```
mvn spotbugs:spotbugs
```

test: replace findbugs with spotbugs [DHIS2-7979]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java

Opted to only backport the actual fix manually as the testing added depends on further additions to test utilities that would then also need backporting.

fix: backport workaround for skipSharing and skipTranslation for putJsonObject [DHIS2-10660] (2.36)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/PreheatCacheService.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java

fix: Properly invalidate LocalCache and add listener to invalidate Tracker cache [DHIS2-10726]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetReportController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java

backport https://github.com/dhis2/dhis2-core/pull/7712

fix: set default UTF_8 charset for StringHttpMessageConverter [2.36]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java

fix: DHIS2-10674: Fixing 'access' for charts and report tables (2.36)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java

fix: DHIS2-10674: Fixing 'access' for chart/reportTable (2.35)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java

fix: DHIS2-10674: Fixing 'access' for chart/reportTable (2.34)

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java

Not working as intended and potentially ignoring acl

fix: Disable cache for new tracker importer. 

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v36/V2_36_11__Migrate_sharings_to_jsonb.java

backport https://github.com/dhis2/dhis2-core/pull/7698

fix: owner uid refer to userinfo table [2.36]

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v36/V2_36_11__Migrate_sharings_to_jsonb.java

backport https://github.com/dhis2/dhis2-core/pull/7698

fix: owner uid refer to userinfo table [2.36.0]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dxf2/events/event/EventContext.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStore.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityProgramOwnerIds.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityProgramOwnerService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackerOwnershipManager.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/organisationunit/DefaultOrganisationUnitService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityProgramOwnerService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityProgramOwnerStore.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventServiceContextBuilder.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JacksonEventService.java
dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/HibernateGenericStore.java

forward-port of https://github.com/dhis2/dhis2-core/pull/7671 which was already reviewed

perf: reduce queries performed by eventRows

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ChartFacadeController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ReportTableFacadeController.java

This bug was recently merged into master and is recommended to be backported to 2.36.0.
**Was already approved by the Release Control Committee.**
cc @janhenrikoverland , @Philip-Larsen-Donnelly

fix: DHIS2-10674: Fixing 'access' for chart/reportTable (patch/2.36.0)

---

dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java

Issue: [[https://jira.dhis2.org/browse/DHIS2-9353]( https://jira.dhis2.org/browse/DHIS2-9353)]

fix: Make Captcha and API key confidential

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/helper/OrderingHelper.java

For the current differences of sorting, visit this comment and find the respective images.
https://jira.dhis2.org/browse/DHIS2-9934?focusedCommentId=40404&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-40404
**Probably needs to go into 2.36.0 as well.**

fix: DHIS2-9934: Mimic sorting algorithm from existing endpoints

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sharing/DefaultSharingService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityTypeAttribute.hbm.xml
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_publicAccess_update.json
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java

backport https://github.com/dhis2/dhis2-core/pull/7724

fix: can't update publicAccess [2.36]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataitem/helper/OrderingHelper.java

fix: DHIS2-9934: Mimic sorting algorithm from existing endpoints (2.36)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniqueMultiPropertiesCheck.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_multi_property_uniqueness.json
dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramRuleVariableSchemaDescriptor.java

* feat: multi properties uniqueness check [TECH-543]
* feat: unit test added [TECH-543]
* feat: applicated peer review suggestion [TECH-543]
(cherry picked from commit ac0fcba798afe735638347b7ef731e10cfc5042c)

feat: add multi-property uniqueness check [TECH-543] (#7569)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sharing/DefaultSharingService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityTypeAttribute.hbm.xml
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_publicAccess_update.json
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java

Issue https://jira.dhis2.org/browse/DHIS2-10464
backport https://github.com/dhis2/dhis2-core/pull/7724

fix: can't update publicAccess [2.36.0] 

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/create_user_without_createdBy.json

backport https://github.com/dhis2/dhis2-core/pull/7778

fix: null userCredentials.createdBy when create user[2.35]

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/create_user_without_createdBy.json

backport https://github.com/dhis2/dhis2-core/pull/7778

fix: null userCredentials.createdBy when create user[2.34]

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/create_user_without_createdBy.json

backport https://github.com/dhis2/dhis2-core/pull/7778

fix: null userCredentials.createdBy when create user[2.36]

---

dhis-2/dhis-web/pom.xml

chore: Re-enable .war file compression

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_36__Fix_negative_sort_orders_in_visualization_rows_columns.sql

fix: DHIS2-10805: Fixing negative sort_order columns

---

dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_39__Fix_negative_sort_orders_in_visualization_rows_columns.sql

fix: DHIS2-10805: Fixing negative sort_order columns (2.36)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java

[[https://jira.dhis2.org/browse/DHIS2-10800](https://jira.dhis2.org/browse/DHIS2-10800)]

fix: Save domain type on file upload

---

dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/AppHubService.java
dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/DefaultAppHubService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppHubController.java

2.36.0 backport of https://github.com/dhis2/dhis2-core/pull/7773

fix: don't encode proxied App Hub requests (2.36.0)

---

dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/AppHubService.java
dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/DefaultAppHubService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppHubController.java

2.36 backport of https://github.com/dhis2/dhis2-core/pull/7773

fix: don't encode proxied App Hub requests (v36)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java

chore: file logging on debug level (not info)

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetReportController.java
dhis-2/dhis-web/dhis-web-api/src/main/resources/META-INF/dhis/servlet.xml

backport https://github.com/dhis2/dhis2-core/pull/7712

fix: set default UTF_8 charset for StringHttpMessageConverter[2.33]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileController.java

chore: Prevent NP on get custom script and stylesheet

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceTest.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreIntegrationTest.java

(cherry picked from commit e0a9ea64e15852b3bdb2873b931e9e6df38a3495)

fix: /api/dataApprovals/multiple error [DHIS2-10839]

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java

- Fix issue for import new object with skipTranslation=true. Expected result is the created object will have empty translations
- Add few more unit tests

fix: skipTranslation for import new object

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetReportController.java
dhis-2/dhis-web/dhis-web-api/src/main/resources/META-INF/dhis/servlet.xml

backport https://github.com/dhis2/dhis2-core/pull/7712

fix: set default UTF_8 charset for StringHttpMessageConverter[2.34]

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java

Not working as intended and potentially ignoring acl

fix: Disable cache for new tracker importer

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java

While working on #7711 I noticed 2 issues in the `SchedulingManager` that I initially fixed in that branch but decided to extract into a separate PR. Issues are:
* maps used to manage internal state were not thread-safe (state is potentially read and write by different threads)
* tasks added to the `currentTasks` map will never get removed. I added a completion stage so that they remove themselves once they are done. The state in the `currentTasks` map is only used by the class itself to recognised jobs already started so they are not started another time. It is not directly accessible to external code. Since the map holds the future of the result not clearing it from the map does hold on to the job result which I think over time must be considered a memory leak.

fix: thread-safety and memory leakage in scheduling manager

---

dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json

Adding AGGREGATE for data elements to match the new rule added to the filtering.

fix: DHIS2-10766: api test fix

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java

Sets default job parameters for validation of analytics table job. Fixes the problem where a parameter had to be set for the analytics table job to make it possible to save it. This was unfortunate as users entered 0 for "last years", which meant no data was updated in analytics tables (0 means "latest data" as part of the continuous analytics table job now).

fix: Set default job parameters for validation [DHIS2-10768]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/ValidationRuleExpressionDetails.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/PeriodTypeExtended.java
dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/ValidationRunContext.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/AnalyticsValidationServiceTest.java
dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataAnalysisController.java

* fix: Validation details with all items DHIS2-8876
* fix: Spotless fixes
* fix: SonarCloud Code Analysis
* fix: remove unused import
* refactor: respond to jbee's review
(cherry picked from commit b0bce223248371a23c2443647a82d4565133741e)

fix: Validation details with all items DHIS2-8876 (#7723)

---

dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/DataElementQuery.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ProgramIndicatorQuery.java

fix: DHIS2-10766: Remove unnecessary 'group by' causing duplicated rows

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultUserDetailsService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java

[https://jira.dhis2.org/browse/DHIS2-10853](https://jira.dhis2.org/browse/DHIS2-10853)

fix: Unable to Authenticate with LDAP [DHIS2-10853]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultUserDetailsService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java

(cherry picked from commit d851f1da41febd17922678edd79f65af832f171f)

fix: Unable to Authenticate with LDAP (#7832)

---

dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineDescriptionTest.java
dhis-2/pom.xml

fix: (2.36.0) Add support A{var-name} syntax support for d2 functions

---

dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEngineDescriptionTest.java
dhis-2/pom.xml

fix: (2.36) Add support A{var-name} syntax support for d2 functions

---

dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonDocument.java
dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/JsonObject.java
dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/JsonDocumentTest.java
dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java

A few changes I made when working on https://github.com/dhis2/dhis2-core/pull/7766 that are not directly related to the feature added in that PR (and that we might want to backport)

fix: JSON test tool bugfixes in context of [DHIS2-10740]

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/ExternalMapLayer.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_37__Add_translations_column_into_externalmaplayer_table.sql

backport https://github.com/dhis2/dhis2-core/pull/7784

fix: add translations column for ExternalMapLayer[2.35]

---

dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/ExternalMapLayer.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_39__Add_translations_column_into_externalmaplayer_table.sql

backport https://github.com/dhis2/dhis2-core/pull/7784

fix: add translations column for ExternalMapLayer [2.34]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java

fix: start/stop jobs when PATCHed [DHIS2-10890] 2.36

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java

fix: start/stop jobs when PATCHed [DHIS2-10890] 2.36.0

---

dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java

fix: (2.34) Delete associated program message while pruning enrollments, events and tei

---

dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java

fix: (2.35) Delete associated program message while pruning enrollments, events and tei

---

dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java

fix: (2.36) Delete associated program message while pruning enrollments, events and teis

---

dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationImplementableRuleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ServerSideImplementableRuleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java

Backporting JIRA #[DHIS2-10822]

fix: (2.36) Run rule engine only for associated program stages 

---

dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ImplementableRuleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/NotificationImplementableRuleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ServerSideImplementableRuleService.java
dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java

fix: (2.35) Run rule engine only for associated program stages

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java

Issue:
- If sharing record in DB doesn't have users or userGroups, then it would cause NPE in SharingController
Fix:
- Initiate new Map if those are null in getter methods

fix: NPE for sharing in SharingController

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultUserDetailsService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java

(cherry picked from commit d851f1da41febd17922678edd79f65af832f171f)

fix: Unable to Authenticate with LDAP (#7832) (#7836)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java

backport https://github.com/dhis2/dhis2-core/pull/7864

fix: NPE for sharing in SharingController [2.36]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java

backport https://github.com/dhis2/dhis2-core/pull/7879

fix: NPE for sharing in SharingController [2.36.0]

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TeTaValidationTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHookTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHookTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/tracker_basic_metadata_mandatory_attr.json
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/te-program-with-tea-mandatory-image.json
dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java

see https://github.com/dhis2/dhis2-core/pull/7880

fix: [DHIS2-10797] Fix remove null values for tracker attributes and data values 2.36

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/BaseIdentifiableObject_.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/Translation.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_merge_mode.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_skipSharing.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_update_skipSharing.json
dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultMergeService.java

backport 3 PRs that are related to sharing issues
- https://github.com/dhis2/dhis2-core/pull/7806
-  https://github.com/dhis2/dhis2-core/pull/7775
- https://github.com/dhis2/dhis2-core/pull/7824

fix: skipSharing and mergeMode not working correctly [2.36]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/BaseIdentifiableObject_.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/Translation.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java
dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_merge_mode.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_skipSharing.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_update_skipSharing.json
dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultMergeService.java

backport https://github.com/dhis2/dhis2-core/pull/7898

fix: skipSharing and mergeMode not working correctly [2.36.0]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultLdapUserDetailsService.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationProviderConfig.java

fix: Handle LDAP users authentication when password is null

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java

backport https://github.com/dhis2/dhis2-core/pull/7909

fix: remove workaround fix for sharing in AbstractCrudController [2.36.0]

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/transformer/UserPropertyTransformer.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/Category.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroup.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroupSet.hbm.xml
dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationRule.hbm.xml
dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationRuleGroup.hbm.xml

backport https://github.com/dhis2/dhis2-core/pull/7914

fix: add createdBy field to hbm files [2.36]

---

dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java

Remove the workaround fix for sharing issue in AbstractCrudController as it is now fixed by the PR https://github.com/dhis2/dhis2-core/pull/7824

fix: remove workaround fix for sharing in AbstractCrudController

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/transformer/UserPropertyTransformer.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/Category.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroup.hbm.xml
dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroupSet.hbm.xml
dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationRule.hbm.xml
dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationRuleGroup.hbm.xml

backport https://github.com/dhis2/dhis2-core/pull/7915

fix: add createdBy field to hbm files [2.36.0]

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/SecurityServiceTest.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/handler/CustomExceptionMappingAuthenticationFailureHandler.java
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/login.js
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm
dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/loginStrings.vm

Fixes issue [[DHIS2-10897]](https://jira.dhis2.org/browse/DHIS2-10897)

fix: Login page is not showing the correct message when locked

---

dhis-2/pom.xml

chore: Upgrade Spring Security 5.4.6

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/DefaultFileResourceService.java
dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceCleanUpJob.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceCleanUpJobTest.java

* fix: FileResourceCleanUpJob aborts DHIS2-7700
* refactor: Use @AllArgsConstructor DHIS2-7700
(cherry picked from commit 228c157d815ca9b3d04511a8ac7737594905dc99)

fix: FileResourceCleanUpJob aborts DHIS2-7700 (#7954)

---

dhis-2/pom.xml

chore: Upgrade Spring Core 5.3.6

---

dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java

(cherry picked from commit 439b6a2c62300155c61f544b2d678c0056360a8c)

fix: trap all analytics errors

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/Constants.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java

[DHIS2-10956](https://jira.dhis2.org/browse/DHIS2-10956)
Work done :

fix: [DHIS2-10956] Validate program rule variable names in API

---

dhis-2/dhis-services/dhis-service-acl/src/main/java/org/hisp/dhis/security/acl/DefaultAclService.java

The `Access` based on object type and `Sharing` alone introduced in #7951 wasn't executed 100% through the depth of all helper methods. This effectively caused the outcome to be wrong for the new use case only as it was the only one depending on the type argument being different from the object's actual instance type itself. 
This PR completes forwarding the object `Class` throughout the evaluation fixing the new use case for Gist API access field.
I verified this by comparing the outcome with the value shown in the regular metadata API.
Noticed the error while grabbing an example for the documentation :)

fix: access with object type

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_merge_mode.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataset_with_accesses_skipSharing.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_visualization_with_accesses.json
dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_visualization_with_accesses_update.json
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java

Backport the logic of the fix https://github.com/dhis2/dhis2-core/pull/7898
As the sharing model has been changed from 2.36, the  code of this backport is a bit different from the original fix.

fix: skipSharing not working correctly [2.35]

---

dhis-2/dhis-support/dhis-support-json-filtering/src/main/java/org/hisp/dhis/commons/jsonfiltering/web/FieldFilterCustomizer.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerDtoFieldFilterCustomizer.java
dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerFieldFilterCustomizerAdaptor.java

feature was only enabled for collections endpoint, this PR should extend to all new tracker endpoints

fix: field filtering added also to single value endpoints

---

dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/config/TrackerPreheatConfig.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/TrackedEntityProgramInstanceSupplier.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationContext.java
dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHook.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHookTest.java
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/tracker_basic_metadata.json
dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/enrollments_te_enrollments-data.json

see https://github.com/dhis2/dhis2-core/pull/7941

feat: DB access in EnrollmentInExistingValidationHook [TECH-450]

---

dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/matchers/MatchesJson.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/TrackerNtiApiTest.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/AtomicModeTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/ImportStrategyTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/RuleEngineTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/SideEffectsTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerImporterImportModeTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/enrollments/EnrollmentsTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/enrollments/EnrollmentsUpdateTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventIdSchemeTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventNotesTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventUpdateTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventValidationTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventsDataValueValidationTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventsTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/UserAssignmentTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/relationships/RelationshipsTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiImportTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiUpdateTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiValidationTests.java

- adds a base class for tracker importer tests with some helper methods used in many tests 
- adds validation tests for updating events, tracked entities, relationships, enrollmentss

test: adds NTI tests for immutable properties validation (DHIS2-10875)

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/TextMode.java

New `textMode` attribute (enum based) added to Visualization StyledObject.
Needs to support new frontend features.

feat: Support textMode for Title - Visualization

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/Constants.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java

see https://github.com/dhis2/dhis2-core/pull/7965

fix: [DHIS2-10956] Validate program rule variable names in API 2.36

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/Constants.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java

see https://github.com/dhis2/dhis2-core/pull/7965

fix: [DHIS2-10956] Validate program rule variable names in API 2.35

---

dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/Constants.java
dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java

see https://github.com/dhis2/dhis2-core/pull/7965

fix: [DHIS2-10956] Validate program rule variable names in API 2.34

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/AttributeActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramStageActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/helpers/JsonObjectBuilder.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventImportDataValueValidationTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventsDataValueValidationTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiValidationTests.java

- adds some tests to cover data value and attribute removal: https://jira.dhis2.org/browse/DHIS2-10797
- adds few tests to cover field filtering: https://jira.dhis2.org/browse/DHIS2-10756

test: adds tests for removal of data values and attributes

---

dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/AttributeActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramStageActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/helpers/JsonObjectBuilder.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/ResponseValidationHelper.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/matchers/MatchesJson.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportTest.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/TrackerNtiApiTest.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventImportDataValueValidationTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/AtomicModeTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/ImportStrategyTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/RuleEngineTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/SideEffectsTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerImporterImportModeTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/enrollments/EnrollmentsTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventIdSchemeTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventValidationTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventsDataValueValidationTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/UserAssignmentTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiImportTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiUpdateTests.java
dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiValidationTests.java
dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
dhis-2/dhis-e2e-test/src/test/resources/setup/userGroups.json
dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/enrollments/enrollment.json

This is a backport of tracker tests for DHIS2-10797. Some changes like the new base class for nti tests were backported as well.

test: tests for tracker data value and attribute removal (2.36) 

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserDeletionHandler.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceCleanUpJobTest.java

(cherry picked from commit 10370b3dbe753542916828b3db92278bbd4cbc3a)

fix: UserDeletionHandler check avatar DHIS2-7700 (#8010)

---

dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserDeletionHandler.java
dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceCleanUpJobTest.java

(cherry picked from commit 10370b3dbe753542916828b3db92278bbd4cbc3a)
(cherry picked from commit 6f55d0fdc25903e4c63c13311ec08aacc52e5df2)

fix: UserDeletionHandler check avatar DHIS2-7700 (#8010) (#8013)

---

dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java

- User report the issue with below errors.
- I can't reproduce the issue.
- The error maybe caused by the `DATA_ELEM_CACHE` in `AbstractEventService`. We put the object into cache, and by that time the object may have lazy collections.  So in method `AbstractEventService.getDataElement()` if the session is closed by the time this method is called, then `LazyInitializationException` would be thrown.
- However, I can't reproduce the case where session is closed. So this fix might not work, will need to send user the war file to test on their side.
```
: failed to lazily initialize a collection of role: org.hisp.dhis.dataelement.DataElement.userGroupAccesses, could not initialize proxy - no Session
May 06 09:48:00 covid19 tomcat9[262]:         at …
```

fix: LazyInitializationException in AbstractEventService caches [2.35]
