dhis2/dhis2-core

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/NotificationTemplateObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/notification/ValidationNotificationTemplate.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dataset/hibernate/DataSetNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/notification/BaseNotificationMessageRendererTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationNotificationTemplate.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_12__Add_translations_column_into_notification_template_tables.sql
https://jira.dhis2.org/browse/DHIS2-11030
> feat: enable translation for notificationTemplate objects

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
backport https://github.com/dhis2/dhis2-core/pull/7991
> fix: LazyInitializationException in AbstractEventService caches [2.35.4]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ResultProcessor.java
> fix: Remove programUid for PROGRAM_INDICATOR types [DHIS2-11156]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/NotificationTemplateObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/notification/ValidationNotificationTemplate.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dataset/hibernate/DataSetNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/notification/BaseNotificationMessageRendererTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationNotificationTemplate.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_42__Add_translations_column_into_notification_template_tables.sql
backport https://github.com/dhis2/dhis2-core/pull/8012
> feat: enable translation for notificationTemplate objects [2.36]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
https://jira.dhis2.org/browse/DHIS2-11055
> fix: LazyInitializationException in AbstractEventService caches [2.36]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/ImportTrackedEntitiesTask.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/JacksonTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/TrackerCrudTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/TrackerUnitTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/TrackedEntityInstanceStrategyHandler.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/impl/AbstractTrackedEntityInstanceStrategy.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/impl/TrackedEntityInstanceAsyncStrategyImpl.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/impl/TrackedEntityInstanceStrategyImpl.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/impl/TrackedEntityInstanceSyncStrategyImpl.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/request/TrackerEntityInstanceRequest.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceControllerTest.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/TrackedEntityInstanceStrategyHandlerImplTest.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/strategy/old/tracker/imports/TrackedEntityInstanceStrategyHandlerTest.java
see https://github.com/dhis2/dhis2-core/pull/8023
> fix: [DHIS2-11121] - Tracker async import only expect new entities 2.35

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
> fix: Adding paging flag [DHIS2-10742]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/ChartType.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
Backporting from master (2.37).
> fix: DHIS2-11113: Missing conversion to STACKED_AREA chart

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
New system variable requested by the analytics frontend team.
> feat: Add new system setting [DHIS2-11166]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/NotificationTemplateObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/notification/NotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/notification/ValidationNotificationTemplate.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dataset/hibernate/DataSetNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/notification/BaseNotificationMessageRendererTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationNotificationTemplate.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_39__Add_translations_column_into_notification_template_tables.sql
backport https://github.com/dhis2/dhis2-core/pull/8012
> feat: add translations for notificationTemplate objects [2.35]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalWorkflowServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/DataApprovalLevelSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/DataApprovalWorkflowSchemaDescriptor.java
https://jira.dhis2.org/browse/DHIS2-11155
> feat: add authorities for dataapproval level/workflow

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Forward-port coming from 2.33. This was already reviewed and merged in 2.33.
> fix: Fix coordinates and org. unit in event enrollments [DHIS2-10228]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/RequestToSearchParamsMapper.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingAndSortingCriteriaAdapter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingCriteria.java
* refactor: removed paging parameter, only skipPaging is considered now
* style: formatting
(cherry picked from commit adb917efe3961d528a782d8255afb852f48bc726)
> refactor: skipPaging refactoring - Backport of [dhis2-11094] (#8069)

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/FileResourceServiceTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebClient.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
https://jira.dhis2.org/browse/DHIS2-11172
> feat: add OrgUnit fileResourceDomain

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValue.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValueStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/TextPatternMethod.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/DefaultReservedValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/ValueGeneratorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/util/Constants.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/batchhandler/ReservedValueBatchHandler.java
see https://github.com/dhis2/dhis2-core/pull/8091
> feat: [DHIS2-11182] - Remove uneccesary use of reserved values and queries 2.36

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValue.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValueStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/TextPatternMethod.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/DefaultReservedValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/ValueGeneratorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/util/Constants.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/batchhandler/ReservedValueBatchHandler.java
see https://github.com/dhis2/dhis2-core/pull/8091
> feat: [DHIS2-11182] - Remove uneccesary use of reserved values and queries 2.35

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/JacksonRowDataSerializer.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/OutputFormatter.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/adapter/OutputFormatterTest.java
Backporting from master (2.37).
> fix: Avoid scientific notation for large numbers [DHIS2-10857]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/CategoryOptionActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/programs/AbstractOrgUnitAssociationTestSupport.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/programs/CategoryOptionsTest.java
- dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/AbstractOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/CategoryOptionOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/ProgramOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssiciationStoreConfiguration.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationStoreConfiguration.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/jdbc/JdbcOrgUnitAssociationsStore.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryOptionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
doc PR here: https://github.com/dhis2/dhis2-docs/pull/732
This is pretty much the same as we did in DHIS2-10509
> feat: capture scope category option endpoint [DHIS2-4417]

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/SqlViewSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/SchemaServiceTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
https://jira.dhis2.org/browse/DHIS2-11195
> feat: add schema dataWriteShareable and dataReadShareable

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/Schema.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/SqlViewSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/SchemaServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/8106
> feat: add schema dataWriteShareable and dataReadShareable [2.36]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageInstanceFilterSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageSectionSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/TrackedEntityInstanceFilterSchemaDescriptor.java
backport https://github.com/dhis2/dhis2-core/pull/8022
> fix: add authorities for ProgramStageSectionSchema [2.36] [DHIS2-11051]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/NotificationTemplateObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/notification/NotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/notification/ValidationNotificationTemplate.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dataset/hibernate/DataSetNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramNotificationTemplate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/notification/BaseNotificationMessageRendererTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/resources/org/hisp/dhis/validation/hibernate/ValidationNotificationTemplate.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_41__Add_translations_column_into_notification_template_tables.sql
backport https://github.com/dhis2/dhis2-core/pull/8074
> feat: add translations for notificationTemplate objects [2.34]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/8205
> fix: skip sharing validation when skipSharing=true [2.35]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileController.java
(cherry picked from commit 0fe6925b961fd6b7fed6efd724fa4bc95b5648fb)
> chore: Prevent NP on get custom script and style sheet (#7762)

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageInstanceFilterSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageSectionSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/TrackedEntityInstanceFilterSchemaDescriptor.java
backport https://github.com/dhis2/dhis2-core/pull/8022
> fix: add authorities for ProgramStageSectionSchema [2.34]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/8205
> fix: skip sharing validation when skipSharing=true [2.36_ks]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/8008
> fix: acl query  with owner = null [2.36_ks]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageInstanceFilterSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageSectionSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/TrackedEntityInstanceFilterSchemaDescriptor.java
backport https://github.com/dhis2/dhis2-core/pull/8022
> fix: add authorities for ProgramStageSectionSchema [2.35]

- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebClient.java
Instead of using a dedicated parameter for content mime type a `Header` is used that can be passed to the generic method as `RequestComponent`.  
If no such header is set the old defaults are in place:
* `application/json` (all but `PATCH`)
* `application/json-patch+json` (PATCH)
*  `application/json` with UTF8 explicitly set for JSON files
This defaults now can be overridden by passing a `ContentType(MediaType.APPLICATION_JSON)` header argument to any of the methods. 
Since PATCH sets the header this way as first argument any user provided `ContentType` header will override this default and thereby have the intended effect.
> chore: setting content mime type via Header in spring Mvc tests

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/CategoryOptionComboAclCallable.java
(cherry picked from commit 04ac1422da8e81625a219b72b10d991016f2e11a)
> fix: Data Import COC IdScheme ATTRIBUTE DHIS2-9313 (#8240)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/CategoryOptionComboAclCallable.java
(cherry picked from commit 04ac1422da8e81625a219b72b10d991016f2e11a)
(cherry picked from commit f0339583b34f8f865570e23db23c89448e439977)
> fix: Data Import COC IdScheme ATTRIBUTE DHIS2-9313 (#8240) (#8252)

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/ExpressionFunctions.java
> fix: comment typo

- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
https://jira.dhis2.org/browse/DHIS2-11155
> fix: add translation for dataApproval authorities

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/AdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/adx/AdxDataServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportB.adx.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportC.adx.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportD.adx.xml
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
(cherry picked from commit 04468bbf8e15e8896e416635c063a0f37c5e209f)
> fix: Add common export options for ADX [DHIS2-9313] (#8253)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/AdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/adx/AdxDataServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportB.adx.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportC.adx.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportD.adx.xml
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
(cherry picked from commit 04468bbf8e15e8896e416635c063a0f37c5e209f)
(cherry picked from commit da18db8dc0920d31d4721a5da0976189b29b7d0f)
> fix: Add common export options for ADX [DHIS2-9313] (#8253) (#8325)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
> fix: Delete associated program message while pruning enrollments, events and tei

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/DefaultReservedValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RandomGeneratorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/ValueGeneratorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/util/Constants.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/RandomGeneratorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStoreTest.java
[DHIS2-11305](https://jira.dhis2.org/browse/DHIS2-11305)
This PR aims to improve the generation of random values for those tracked entity attributes that use a random generation pattern.
The new random generation service now generate values : 
- for numbers -> random generation from 256 bit BigInteger
- for alphanumerics ->  generation of random UUID   
Basically the seed of generation now it is larger so the probability of getting same values during time should be low
Also generation now is multi thread in order to generate as much values as possibile during a single round
> feat: Improve Reserved Values generation [DHIS2-11305] [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/DefaultCsvImportService.java
> fix: CSV import lookup by code use code (2.36)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/DefaultCsvImportService.java
> fix: CSV import lookup by code use code (2.35)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationStatus.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DeduplicationControllerTest.java
For this PR we 
There is more job related to Potentail Duplicate but it'll be done with 2 separate PR:
- https://jira.dhis2.org/browse/DHIS2-11437
- https://jira.dhis2.org/browse/TECH-644
> feat: [DHIS2-11337] Deduplication: GET potential duplicates, filter by status [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicate.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateException.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/deduplication/hibernate/PotentialDuplicate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_22__Potential_Duplicate_Not_Null_teiB.sql
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DeduplicationControllerTest.java
[DHIS2-11437](https://jira.dhis2.org/browse/DHIS2-11437)
Work done :
> fix: [DHIS2-11437] - [ PotentialDuplicate ] - Not null for Pair of tracked entities [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DeduplicationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/exception/BadRequestException.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerMvcTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
[DHIS2-11338](https://jira.dhis2.org/browse/DHIS2-11338)
This feature adds an endpoint to retrieve potential duplicates by tei uid. It also has an optional status parameter (default ALL)
> feat: [DHIS2-11338] - Deduplication: GET potential duplicates, filter by tei uid [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/ImportConfig.java
Cherry pick of https://github.com/dhis2/dhis2-core/commit/eb3dae0fa366bf7d31ca508a7b05ecb24a900546 and https://github.com/dhis2/dhis2-core/commit/ce78779089280b7e875b2afa19e500272e1503ea for 2.35 backport
> fix: complete data set registrations fallback to URL ID schemes [DHIS2-11355] (2.35)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerMvcTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
[DHIS2-11336](https://jira.dhis2.org/browse/DHIS2-11336)
Work done :
> feat : [ DHIS2-11336 ] - Deduplication: Update potential duplicate [2.37]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/AdxException.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
* fix: ADX Exeption and ImportOptions DHIS2-9313
* fix: ADX LastUpdatedDuration
* fix: remove unused import
(cherry picked from commit 6b13b30d21e24d7ca60155c57239b35d1c316887)
> fix: ADX Exception and ImportOptions DHIS2-9313 (#8420)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/AdxException.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
* fix: ADX Exeption and ImportOptions DHIS2-9313
* fix: ADX LastUpdatedDuration
* fix: remove unused import
(cherry picked from commit 6b13b30d21e24d7ca60155c57239b35d1c316887)
(cherry picked from commit 79230859f920b8ada7f41cdff73f7e80585c2366)
> fix: ADX Exception and ImportOptions DHIS2-9313 (#8420) (#8421)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
(cherry picked from commit d8b718692fa690cf8e3dae581e5249e0e10a0339)
> fix: broken periodOffset function DHIS2-11515 (#8424)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
It will fetch the UIDs of all the entries to be deleted and then create an audit object for those entities.
While deleting TEI, it will also delete its associated enrollments and events. Similarly, deletion of enrollment will also include deletion of its associated events.
> fix: Add deletion audit entry when hard deleting events/enrollments [DHIS2-11577]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StoreConfig.java
> fix: Skip reportTable and chart stores [DHIS2-11575]

- Jenkinsfile-core-dev
> build: Add cve patcher script to core-dev pipeline [DEVOPS-83]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/TrackedEntityInstance.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceServiceTest.java
[DHIS2-11532](https://jira.dhis2.org/browse/DHIS2-11532)
> fix : [ DHIS2_11532 ] - Flag for potential duplicate at tei level [ old tracker ] - fix boolean getter, add tests

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/MergeObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/MergeStrategy.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DeduplicationController.java
A interim implementation for the new endpoint. This introduces the tools needed for the services like MergeObject and the endpoint for merging.
This is part 1 of DHIS2-11401; This part still requires more tests and work.
> feat: Add endpoint for merging PotentialDuplicates

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotLikeOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/Operator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/OperatorTest.java
https://jira.dhis2.org/browse/DHIS2-11383
Backport https://github.com/dhis2/dhis2-core/pull/8512
> fix: notLike filter is not working correctly [2.36]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalPermissions.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DataApprovalPermissionsEvaluator.java
https://jira.dhis2.org/browse/DHIS2-11582
Response after applying this PR
```
{
"mayApprove": false,
"mayUnapprove": false,
"mayAccept": false,
"mayUnaccept": false,
"mayReadData": true,
"state": "APPROVED_HERE",
"approvedBy": "Tom Wakiki",
"approvedAt": "2021-08-19T12:18:03.121"
}
```
> feat: add approvedBy and approvedAt to /api/dataApprovals's response

- dhis-2/dhis-web/dhis-web-apps/README.md
- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
> docs(apps): update the feature toggling apps index

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/DefaultReservedValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/PatternBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RandomGeneratorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RandomPatternBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/RandomGeneratorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceTest.java
With [DHIS2-11305 ](https://jira.dhis2.org/browse/DHIS2-11305) we are generating random digits from big integers but we are skipping zero prefixed patterns
> fix: [ DHIS2-11305 ] fix zero prefix on random digit generation

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/Dashboard.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/design/Column.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/design/ItemConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/design/Layout.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/design/Position.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/design/Spacing.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dashboard/hibernate/Dashboard.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_28__Add_Layout_And_ItemConfig_Columns_Dashboard.sql
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/org/hisp/dhis/usertype/UserTypes.hbm.xml
Adding a new layout object into Dashboard so the user can define and save custom dashboard layouts in the front-end.
> feat: Add layout settings to Dashboard [DHIS2-3600]

- dhis-2/dhis-web-api-test/pom.xml
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/pom.xml
Remove dependency on dhis-web-commons in the dhis-web-api-test module
> chore: Remove dep. on dhis-web-commons in the dhis-web-api-test

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicate.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/PotentialDuplicatesActions.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/deduplication/hibernate/PotentialDuplicate.hbm.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
Also remove sorting during merge
> refactor: Rename teiA and teiB to original and duplicate respectively

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
Co-authored-by: Lars Helge Øverland <lars@dhis2.org>
(cherry picked from commit 06999ff5e6ec329f75d2937d59d7f4d8b93e9371)
> fix: (2.36) Data Element Form Name, not show-up in the forms (#8611)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJ.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJDeleteNewValue.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJDeleteNoValue.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJDeleteZeroValue.json
> fix: data value import - delete with zero or no value [DHIS2-11624] (2.35)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceMergeIntegrationTest.java
> fix: [ DHIS2-11351 ]  - can't merge enrollments due to acl check

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
TEAV was not updated, due to changing its identifier.
enrollments was getting soft-deleted after move.
> fix: Fixed an issue with persisting merging changes.

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/hibernate/PotentialDuplicateStoreTEAVTest.java
Overwrites existing teav value if already exists in original tei.
If not, a new teav is created and attached to original tei.
> feat: overwrite teav value if already exist in original

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicate.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/deduplication/hibernate/PotentialDuplicate.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceIntegrationTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_35__Update_Potential_Duplicate.sql
[DHIS2-11738](https://jira.dhis2.org/browse/DHIS2-11738)
add username info while creating and updating potential duplicate, remove lastupdateby that was a reference on users table
> feat: Remove constraints on user, add username info [DHIS2-11738 ]

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
> chore: unbundle pivot tables app

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHookTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/program_programStage_with_sharing.json
backport https://github.com/dhis2/dhis2-core/pull/8668
> fix: sharing is not saved when create new ProgramStage [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHookTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/program_programStage_with_sharing.json
backport https://github.com/dhis2/dhis2-core/pull/8668
> fix: sharing is not saved when create new ProgramStage [2.36]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/RenderServiceMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
small revert to see if it fixes play/dev viz app
> fix: add back RenderMessageService message converters

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateStore.java
- dhis-2/dhis-e2e-test/src/main/resources/config.properties
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
Required to use setLastUpdatedByUserInfo() to update lastupdated info
> fix: Potential Duplicate update on tei and enrollments lastupdate - [ DHIS2-11563 ]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicatesApiTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicatesTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/deduplication/merge/PotentialDuplicatesEnrollmentsTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/deduplication/merge/PotentialDuplicatesMergeTests.java
pushing a failing test so that Luca can fix a bug that he can't reproduce.
> test: adds tests for last updated dates

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
Forward port 2.37 fix into master.
_This is a bug introduced in 2.37._
_It blocks the inclusion of dashboard items of type APP._
> fix: Logic for dashboard of type APP [DHIS2-11739]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DeduplicationHelper.java
> fix: Validation issues for deduplication merging

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
[DHIS2-11761](https://jira.dhis2.org/browse/DHIS2-11761)
> fix: add lastUpdated check on tei, enrollment and events if lastUpdatedStartDate exists [ DHIS2-11761 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
see [here](https://github.com/dhis2/dhis2-core/pull/8709)
> fix: add lastUpdated check on tei, enrollment and events if lastUpdatedStartDate exists [ DHIS2-11761 ] [ 2.36 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
see [here](https://github.com/dhis2/dhis2-core/pull/8709)
> fix: add lastUpdated check on tei, enrollment and events if lastUpdatedStartDate exists [ DHIS2-11761 ] [ 2.35 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipKey.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/RelationshipStrategy.java
(cherry picked from commit 043d9f3c5aee3c354292e794523319a27e8ab1c1)
> fix: Improve performance for preheating relationships

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: IN operator fix [DHIS2-11770]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerImportParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/DefaultTrackerImportService.java
[Tech 679](https://jira.dhis2.org/browse/TECH-679)
Avoid null pointer exception on jobConfiguration
> fix: NTI: unhandled null pointer exception and stack trace in logs for every import [ TECH-679 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/eventreport_with_program_indicator.json
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/EventReportSchemaDescriptor.java
backport https://github.com/dhis2/dhis2-core/pull/8737
> fix: missing programIndicator after imported EventReport [2.37]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerImportParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/DefaultTrackerImportService.java
see [here](https://github.com/dhis2/dhis2-core/pull/8740)
> fix: NTI: unhandled null pointer exception and stack trace in logs for every import [ TECH-679 ] [ 2.37 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/eventreport_with_program_indicator.json
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/EventReportSchemaDescriptor.java
backport https://github.com/dhis2/dhis2-core/pull/8737
> fix: missing programIndicator after imported EventReport [2.35]

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/eventreport_with_program_indicator.json
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/EventReportSchemaDescriptor.java
backport https://github.com/dhis2/dhis2-core/pull/8737
> fix: missing programIndicator after imported EventReport [2.34]

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/eventreport_with_program_indicator.json
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/EventReportSchemaDescriptor.java
backport https://github.com/dhis2/dhis2-core/pull/8737
> fix: missing programIndicator after imported EventReport [2.36]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/DefaultReservedValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/PatternBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RandomGeneratorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RandomPatternBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/RandomGeneratorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/8569
> fix: zero prefix on random digit generation [ DHIS2-11305 ] [ 2.36 ]

- .patches/security/advisories.json
Creating specific patch PRs on advisories
> build: correct patch PRs

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/enrollments/EnrollmentsTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventNotesTests.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/NotesConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/NotesConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
This PR adds a fix for notes in NTI made by Enrico: storedBy date will be set to current user if not provided. Also, tests for the feature.
> test: adds test for notes (DHIS2-11764) 

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/DataValue.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
> fix: lastUpdatedBy/createdBy info not stored for data values [DHIS2-11765]

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/helpers/QueryParamsBuilder.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/UserAssignmentTests.java
> test: add required ou query param to event endpoint tests 

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
This is a forward-porting from 2.37. See, below, the original PR for more details.
https://github.com/dhis2/dhis2-core/pull/8770
> fix: Reverting org. units logic in events [DHIS2-11800]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/DataValue.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
[DHIS2-11765](#8758)
* fix: lastUpdatedBy and createdBy are not stored for data values [DHIS2-11765]
* fix compilation
* add test
* add tests
> fix: (2.37) lastUpdatedBy/createdBy info not stored for data values [DHIS2-11765]

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/AuditActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/deduplication/merge/PotentialDuplicatesAttributeMergeTests.java
- dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/hibernate/HibernateTrackedEntityAttributeValueAuditStore.java
* test: adds changelog tests for merging attributes
* fix: Use correct value to create changelog entry [DHIS2-11803]
Co-authored-by: Gintare Vilkelyte <vilkelyte.gintare@gmail.com>
> fix: Use correct value to create changelog entry [DHIS2-11803] (#8769)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
see [here](https://github.com/dhis2/dhis2-core/pull/8807)
> fix: teis lastupdated update when updating events - old tracker - [ DHIS2-11761 ] [ 2.35 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
see [here](https://github.com/dhis2/dhis2-core/pull/8807)
> fix: teis lastupdated update when updating events - old tracker - [ DHIS2-11761 ]

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/enrollments/EnrollmentsTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventNotesTests.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/NotesConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/NotesConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
* fix: Add storedBy in notes in NTI [DHIS2-11764]
* test: adds test for notes (DHIS2-11764)  (#8760)
* test: adds test for notes
* fix: size assertion
* fix: Adding default value as current user for storedBy in notes [DHIS-11764]
* Fix test
* Fix test
Co-authored-by: Enrico Colasante <enrico@dhis2.org>
Co-authored-by: Stian Sandvold <stian@dhis2.org>
Co-authored-by: Gintare Vilkelyte <vilkelyte.gintare@gmail.com>
> fix: Add storedBy in notes in NTI [DHIS2-11764] (#8746)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
see [here](https://github.com/dhis2/dhis2-core/pull/8807)
> fix: teis lastupdated update when updating events - old tracker - [ DHIS2-11761 ] [ 2.36 ]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/vote/ExternalAccessVoter.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/vote/LogicalOrAccessDecisionManager.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/vote/SimpleAccessVoter.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
(cherry picked from commit f5b7954500ba008d99ef1251cd7cc3f8e665d1b5)
> fix: Fix broken public external access in /api endpoints (#8819)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/SqlViewUtils.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewUtilsTest.java
(cherry picked from commit ae51acd6ac76ea702fad91fce883caef9fb1968f)
> refactor: replaceAll -> replace in SqlUtils (#8820)

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/RelationshipTypeActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/Event.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/RelationshipItem.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/AbstractStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
> fix: (2.37.0) Event collection endpoint does not fetch relationships [DHIS2-11541]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/DataValue.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
> fix: (2.37.0) lastUpdatedBy/createdBy info not stored for data values DHIS2-11765

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
> fix: Caching inconsistency in analytics [DHIS2-11820]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AttributeValidationHook.java
* fix: Load in preheat all attributes and dataElements linked to program rules [DHIS2-11762]
* Update HibernateProgramRuleStore.java
> fix: Load in preheat all attributes and dataElements linked to program rules [DHIS2-11762]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: Line list and pivot table do not give the same total [2.37.0-DHIS2-11524-Rollback]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: Line list and pivot table do not give the same total [2.34.7-DHIS2-11524-Rollback]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: Line list and pivot table do not give the same total [2.34-DHIS2-11524-Rollback]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: Line list and pivot table do not give the same total [2.36.4-DHIS2-11524-Rollback]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/InQueryFilterTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
a small refactoring and added some unit test for InQueryFilter class
> test: Unit test for InQueryFilter [DHIS2-11786]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: Line list and pivot table do not give the same total [2.35.8-DHIS2-11524-Rollback]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: Line list and pivot table do not give the same total [2.38-DHIS2-11524-Rollback]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
* fix: Add potentialDuplicate parameter in tei/query endpoint (2.37.0)
* Add tests for potential duplicate param in api/tei/query
(cherry picked from commit bf3551090352aa2aba8dd4b5c714f9b2f1e6d03b)
> fix: Add potentialDuplicate parameter in tei/query endpoint (2.38)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
> fix: Line list and pivot table do not give the same total [2.37-DHIS2-11524 rollback]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Backport of https://jira.dhis2.org/browse/DHIS2-9477
> fix: DE type Number displaying zero instead of null value [2.34-DHIS2-9477-backport] 

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Backport of https://jira.dhis2.org/browse/DHIS2-9477
> fix: DE type Number displaying zero instead of null value [2.37-DHIS2-9477-backport]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/EmbeddedJettyBasicAuthenticationEntryPoint.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/FormLoginBasicAuthenticationEntryPoint.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
Jira: [DHIS2-9100](https://jira.dhis2.org/browse/DHIS2-9100)
> feat: Add account disabled info to 401 unauthorized errors

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityInstance.hbm.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
see [DHIS2-11824](https://github.com/dhis2/dhis2-core/pull/8878)
> fix: NTI: last updated date on TEI is not updated when underlying data changes [ DHIS2-11824 ] 2.36

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentity/hibernate/TrackedEntityInstance.hbm.xml
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
see [DHIS2-11824](https://github.com/dhis2/dhis2-core/pull/8878)
> fix: NTI: last updated date on TEI is not updated when underlying data changes [ DHIS2-11824 ] 2.38

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DefaultDataApprovalService.java
(cherry picked from commit 6607c3cf2db4b072fb5f741eef613bf008e8a5fa)
> fix: Sporadic data approvals error DHIS2-11857 (#8926)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
see [here](https://github.com/dhis2/dhis2-core/pull/8807)
> fix: teis lastupdated update when updating events - old tracker - [ DHIS2-11761 ] [ patch/2.36.4 ]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiImportTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teiWithEnrollmentAndAttributes.json
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
* fix: Retrieve attributes from service to persist/update them in NTI[DHIS2-11852]
* test: Added e2e tests adding attributes for TEI and enrollment
* Comment added in abstract persister
> fix: Retrieve attributes from service to persist/update them in NTI [DHIS2-11852](2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
Please let me know if I have to update any other translation files. The last time I did it, I think I only needed to update this one.
Thanks!
> fix: Adding translation for missing enum [DHIS2-11997]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoaderTest.java
(cherry picked from commit 0395572b6507c94db6f06f39624de7935f10bb16)
> fix: Event import catOption start/end DHIS2-12061 (#9151)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateConflictException.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateForbiddenException.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerMvcTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
Exception handling is not clear for the deduplication service and is not properly propagated to the controller.
> refactor: [ Deduplication ] - Clean Exception Hierarchy - [ TECH-792 ]

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
Backport of https://github.com/dhis2/dhis2-core/pull/9143
> feat: New system key 'startModuleEnableLightweight' [DHIS2-11993]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/pom.xml
DHIS2-12070
Boolean variables can be used in combination with 1/yes/true.
> fix: Indicator expression description when using numbers [DHIS2-12070]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/9164
> fix: superUser can't update sharing of private object (2.37)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/9164
> fix: superUser can't update sharing of private object (2.36)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
- dhis-2/dhis-web/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/9164
> fix: superUser can't update sharing of private object (2.35) 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sqlview/SqlView.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
> fix: allow non ASCII letters for SQL view var values [DHIS2-11932] (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sqlview/SqlView.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/DefaultSqlViewService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/SqlViewUtils.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
> fix: consistently require alphanumeric + dash + underscore SQL view var names [DHIS2-11946] (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/Program.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramStage.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/translation/TranslationProperty.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/6352
https://jira.dhis2.org/browse/DHIS2-8297
> feat: make labeled dates translatable in Program and Program Stage (2.35)

- jenkinsfiles/canary
- jenkinsfiles/eos
* Add Sunday to the schedule
* Change trigger time to 23:XX UTC
> build: Update canary and eos Jenkins pipelines' schedules

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/GistPreferences.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParams.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultSchemaService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/SchemaService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/JacksonPropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/PropertyPropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/SchemaFieldIntrospectorTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ReflectionUtils.java
This PR adds support for field level annotations.
[TECH-650](https://jira.dhis2.org/browse/TECH-650)
> feat: support field annotations in property introspectors

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
This PR makes the max sessions allowed at the same time per user, configurable through the dhis.conf file.
JIRA: [https://jira.dhis2.org/browse/DHIS2-11431](https://jira.dhis2.org/browse/DHIS2-11431)
> feat: Make max session per user configurable

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/predictor/hibernate/Predictor.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_44__Add_translations_column_predictor_table.sql
backport https://github.com/dhis2/dhis2-core/pull/8593
> feat: enable translations for Predictor ( 2.35 )

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TranslatableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/Expression.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/expression/hibernate/Expression.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/predictor/hibernate/Predictor.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_47__Add_translations_column_expression_table.sql
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_48__Add_translations_column_predictor_table.sql
backport https://github.com/dhis2/dhis2-core/pull/8593
> feat: add translations to Predictor and Expression (2.36)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/AnalyticsCache.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/cache/AnalyticsCacheTest.java
JUST BACKPORT(FORWARD), SEE:
https://github.com/dhis2/dhis2-core/pull/9313
> fix: [2.38-DHIS2-TECH842] - forwarded backport

- dhis-2/dhis-web/dhis-web-commons/src/main/resources/META-INF/dhis/security.xml
applying Mortens changes from 2.34 main branch
> feat: Increase max concurrent sessions to 50

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
Adding this new system variable :
`DEFAULT_BASE_MAP( "keyDefaultBaseMap" )`
> feat: Add new system variable for Maps [DHIS2-12201]

- jenkinsfiles/stable
"stable" pipeline for release candidates from `patch/*` branches and releases from `x.xx.x[-EMBARGOED]` tags.
https://ci-backup.dhis2.org/job/dhis2-core-stable/
> build: Add stable pipeline [DEVOPS-119]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
new tracker endpoint should now support version in URL.
> feat: added version to new tracker URL path [DHIS2-12255]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/FoundDimensionItemValue.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionAnalyticsDataFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionContext.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionContextGenerator.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionData.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataConsolidator.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionWriter.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionAnalyticsDataFetcherTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionContextGeneratorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataConsolidatorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java
(cherry picked from commit 845c3edd20f846711f5e9c4769fb8009fa4bb89a)
> fix: sort order for orgUnit path DHIS2-12164 (#9271)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/FoundDimensionItemValue.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionAnalyticsDataFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionContext.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionContextGenerator.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionData.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataConsolidator.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionAnalyticsDataFetcherTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionContextGeneratorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataConsolidatorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java
(cherry picked from commit 845c3ed)
> fix: sort order for orgUnit path DHIS2-12164

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ParserUtils.java
(cherry picked from commit ed844226c49c7d66e4f6fb72641703c63bb9de81)
> fix: periodOffset only in indicators DHIS2-12258 (#9533)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOptionComboStore.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupTaglessResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/ExpressionResolvers.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolverTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/hibernate/HibernateCategoryOptionComboStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/category/CategoryOptionComboStoreTest.java
* fix: coGroup: too many option combos DHIS2-12278
* fix: Reorder resolvers
(cherry picked from commit bcd20bf5fc28849b8a65aa5c51f24bb6b7e536b1)
> fix: coGroup: too many option combos DHIS2-12278 (#9548)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
> fix: Backport missing call into events request [DHIS2-11181]

- jenkinsfiles/canary
Related to https://github.com/dhis2/dhis2-core/pull/9537
> build: Add javadoc generation stage to canary pipeline [DEVOPS-114] [2.35]

- jenkinsfiles/canary
Related to https://github.com/dhis2/dhis2-core/pull/9537
> build: Add javadoc generation stage to canary pipeline [DEVOPS-114] [2.36]

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/cache/AnalyticsCacheTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsDimensionsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsDimensionsServiceTest.java
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/keyjsonvalue/KeyJsonValueQueryTest.java
- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-program-rule/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionAnalyticsDataFetcherTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionContextGeneratorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataConsolidatorTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java
- dhis-2/dhis-services/dhis-service-tracker/pom.xml
- dhis-2/dhis-support/dhis-support-audit/pom.xml
- dhis-2/dhis-support/dhis-support-test/pom.xml
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SqlViewControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/security/JwtBearerTokenTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/BaseDimensionMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/DimensionFilteringAndPagingServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/DimensionFiltersTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/mappers/BaseDimensionalItemObjectMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/mappers/BaseDimensionalObjectMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/mappers/ProgramStageDataElementMapperTest.java
- dhis-2/pom.xml
I tried to remove all dependencies for JUnit 4 but removing from testcontainers throw this bug:
https://github.com/testcontainers/testcontainers-java/issues/970
> chore: Clean up support test and other modules using it [TECH-913]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/RuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/event/ProgramRuleEnrollmentEvent.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/event/ProgramRuleStageEvent.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionAssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionScheduleMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerRuleEngineThread.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerSideEffectDataBundle.java
> fix: (2.37.0) Slow import and high memory allocation in NTI  (#9049)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TranslatableObject.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
Fix issue `getDisplayName()` return null if no translation available.
> fix: getTranslation method return null displayName

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AbstractTrackerDtoValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentDateValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckUidValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckUpdatableFieldsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
…ErrorReporter
you can see that the method need the reporter to add an error/warning and also to get the TrackerBundle which is
currently kept in the reporter.context.bundle
> chore: adding errors and warnings is responsibility of the ValidationErrorReporter TECH-880

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
Backporting from the master branch.
> fix: Expand date regex in analytics export [DHIS2-7107]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
(cherry picked from commit 1eab9e0aaa1f139809f399e1b9a854174ef6d6b8)
> fix: ADX export period on endDate DHIS2-12360 (#9623)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
(cherry picked from commit 1eab9e0aaa1f139809f399e1b9a854174ef6d6b8)
(cherry picked from commit 66140a9182853eb36772e61da776ceb4821cc983)
> fix: ADX export period on endDate DHIS2-12360 (#9623) (#9636)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportBasedOnSchemasTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/programs/ProgramStagesTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_all_section_removed.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_removed_section.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_sections.json
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/ProgramStageControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SchemaBasedControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/9382
> fix: add validation for programStage.program (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportBasedOnSchemasTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/programs/ProgramStagesTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_all_section_removed.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_removed_section.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_sections.json
backport https://github.com/dhis2/dhis2-core/pull/9382
> fix: add validation for programStage.program (2.35) 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportBasedOnSchemasTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/programs/ProgramStagesTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramStageObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_all_section_removed.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_removed_section.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/programstage_with_sections.json
backport https://github.com/dhis2/dhis2-core/pull/9382
> fix: add validation for programStage.program (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TranslatableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ObjectReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonDocument.java
- dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonNode.java
- dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonObject.java
- dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonResponse.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/9459
Also backport related codes needed for controller tests
> fix: add validation for duplicate translations (2.37)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/DimensionFilteringAndPagingService.java
> fix: paging parameters are only applicated when paging=true [DHIS2-12457]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventvisualization/SimpleDimension.java
Enabling support for new simple dimensions in EventVisualiztion, so they can be saved/retrieved through the EventVisualization API.
> feat: New simple dimensions in EventVisualization [TECH-959]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/action/validation/AssignProgramRuleActionValidator.java
> fix: assign rule action validation update [DHIS2-12033] (#9634)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/CompleteDataSetRegistrationDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DataValueDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/PredictorDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramStageInstanceDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/predictor/PredictorServiceTest.java
Added the check and confirmed it with a new unit test. 
Some general code level cleanup done as well.
> fix: veto CategoryOptionCombo deletion if used by Predictor [DHIS2-10687]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/PeriodOffsetUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/PeriodOffsetUtilsTest.java
(cherry picked from commit 8e6f48553b80bee68d30014f3fe544a995ecd438)
> fix: periodOffset misses some data [DHIS2-12496] (#9671)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ObjectReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
backport https://github.com/dhis2/dhis2-core/pull/9687
> fix: ConcurrentModificationException in translationCheck (2.37)

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramSectionSchemaDescriptor.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/ProgramSectionControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/9581
> fix: ProgramSection is not shown in Translations App (2.37)

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramSectionSchemaDescriptor.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
backport https://github.com/dhis2/dhis2-core/pull/9581
> fix: ProgramSection is not shown in Translations App (2.36)

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramSectionSchemaDescriptor.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
backport https://github.com/dhis2/dhis2-core/pull/9581
> fix: ProgramSection is not shown in Translations App(2.35)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseIdentifiableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TranslatableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataelement_duplicate_translations.json
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/9459
Replace ControllerTest with `MetadataImportServiceTest` integration test
>  fix: add validation for duplicate translations (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/dataelement_duplicate_translations.json
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/9459
Replace ControllerTest with `MetadataImportServiceTest` integration test
> fix: add validation for duplicate translations (2.35)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
* fix: DataHandler fix for dashboard 500 DHIS2-12518
(cherry picked from commit 63b688019dc7281922accd9c38b357430988cf61)
> fix: DataHandler fix for dashboard 500 DHIS2-12518 (#9705)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/PredictorDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/predictor/PredictorServiceTest.java
> fix: veto CategoryOptionCombo deletion if used by Predictor [DHIS2-10687] (2.35)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/trackedentityfilter/hibernate/TrackedEntityInstanceFilter.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_27__Add_sharing_column_to_trackedentityinstancefilter.sql
This PR adds a new column "sharing" of type jsonb to the table "trackedentityinstancefilter" table.
> feat: add sharing column to trackedentityinstancefilter [DHIS2-12373]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/DefaultCsvImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/JdbcCompleteDataSetRegistrationExchangeStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/SmsCommandObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncDelegate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncImportHandler.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncPostProcessor.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/systemsettings/DefaultMetadataSystemSettingService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/monitoring/DefaultMonitoringService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/DefaultPdfDataEntryFormService.java
Replaces auto-wiring with constructor wiring for dxf2-service.
> chore: Replace auto-wiring with constructor wiring for dxf2-service

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
* fix: DataHandler visualizations fix DHIS2-12518
* fix: Remove dataIndex from method call DHIS2-12518
(cherry picked from commit bcee596300c2371c9a7d7e75e1c074ea80dd3aaf)
> fix: DataHandler visualizations fix DHIS2-12518 (#9720)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
After demo there is an accepted suggestion to change the entry point for analytics queries analyze:
There are four new entry points:
analytics/explain
analytics/events/aggregate/{program}/explain
analytics/events/query/{program}/explain
analytics/enrollments/query/{program}/explain
> feat: As user I would like to have query time estimation feedback [2.38-DHIS2-TECH829-1]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/config/TrackerPreheatConfig.java
https://github.com/dhis2/wow-backend/blob/095890847d18d499dd772d77149f62990edc0f32/guides/spring_conventions.md\#spring-configuration
> chore: add config name as per backend-wow convention

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/mapper/EnrollmentMapper.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/9727
no merge conflicts. backport like a 💨
> fix: map followup from dxf2 to tracker domain DHIS2-12348 [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/OutputFormatter.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
> fix: Avoid scientific notation on export [DHIS2-12543]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeValueAuditTest.java
> fix: (2.36) show attribute value in deletion audit log (#9554)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
> fix: empty period dimension, which is possible in aggregate, should be considered default period [DHIS2-12585]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_42__Script_to_rename_column_programid_in_programstageusergroupaccesses_moved_to_2_36_6_and_this_script_updates_constraint_in_programstageinstance.sql
No change. Same script made idempotent for safety
> fix: make flyway script idempotent

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/DefaultAdminUserPopulator.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v38/V2_38_32__Add_new_user_role_for_analytics_explain_endpoint.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
There is a new role needed. User in the role can perform explain analyze query on analytics queries: 
http://localhost:8080/dhis/api/38/analytics/explain?dimension=dx%3ATcTRasl29wo,pe%3ALAST_12_MONTHS&filter=ou%3AUSER_ORGUNIT&includeNumDen=false&skipMeta=true&skipData=false
> feat: new role (granted to execute explain) [2.38-DHIS2-12605]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/service/DefaultTrackerImportAccessManager.java
see [here](https://github.com/dhis2/dhis2-core/pull/9775)
> fix: Organisation unit cannot be null [DHIS2-12347] [2.37] 

- dhis-2/dhis-e2e-test/docker-compose.yml
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/analytics/AnalyticsDimensionsTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/matchers/Sorted.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/DimensionFilteringAndPagingService.java
- adds displayName to the list of test cases: DHIS2-12578
- adds proper assertions for sort order
> test: improves test for sortable fields in /analytics/*/dimensions

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/command/code/SMSCode.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DataValueSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/J2MEDataValueSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/sms/hibernate/SMSCode.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/DataValueListenerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/SmsCommandObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/SMSCommandObjectBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/import/metadata_with_sms_commands.json
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_51__Add_coc_fk_in_smscode.sql
> fix: (2.36) update SMSCode data model (#9707)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/enrollments_te_enrollments-data-delete.json
see [here](https://github.com/dhis2/dhis2-core/pull/9792)
> fix: Missing errorReports when using DELETE strategy and validation fails [ DHIS2-11300 ] [ 2.37 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
I think this was a mistake during a refactoring. So I'm reverting back to UID.
> fix: Show uid instead of id in events [DHIS2-12648]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
> fix: (2.37) program rule notification lazy load exception  (#9813)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/ProgramStage.hbm.xml
> fix: Add not-null to ProgramStage.hbm to enable validation in API

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/listener/DataValueSMSListener.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/listener/DataValueListenerTest.java
> fix: (2.36) add dataset organisationUnit check  (#9784)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/type/ValueTypeRenderingType.java
add GS1 DataMatrix as text type
> feat: Add (DataMatrix) render type for data elements - [ DHIS2- 12942 ] [ 2.38 ] 

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
bug fix for literal values in repeatable stages
> fix: Repeatable stages, text values,[2.38-DHIS2-12656-2]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
just small NPE in item options
> fix: NPE in item options [23.8-DHIS2-12674]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
following the Lars suggestions the authority granted to perform is ALL as well. There is another request to change analyzeOrderId to explanOrderId
> fix: Add Authority ALL to analytics explain entry point + rename analyzeOrderId prop [2.38-DHIS2-12652]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/PredictorDeletionHandler.java
Cherry-pick of manual merge done for 2.36 in #9900
> fix: prevent category combination deletion when predictor is linked [DHIS2-10687] (2.35)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreIntegrationTest.java
(cherry picked from commit e6eec1b4d91084757079085e8fb46dcff06140a1)
> fix: approvalService.isApproved w/o writing (#9891)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreIntegrationTest.java
(cherry picked from commit e6eec1b4d91084757079085e8fb46dcff06140a1)
(cherry picked from commit 546b0b39528084398ede8d6a354227a8a587a43c)
> fix: approvalService.isApproved w/o writing (#9891) (#9906)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
"metaData": {
"items": {
"edqlbukwRfQ.vANAXwtLwcT": {
"name": "WHOMCH Hemoglobin value"
}
}
...
for repeatable stages
> feat: New item syntax - repeatable stages in meta [2.38-DHIS2-12712]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java
* Adds support for the new field filtering in `/api/system/info`.
[DHIS2-11341](https://jira.dhis2.org/browse/DHIS2-11341)
> feat: support field filtering in /api/system/info

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
dimension=edqlbukwRfQ[0].vANAXwtLwcT:GT:20&dimension=edqlbukwRfQ[-1].vANAXwtLwcT:GT:20
will return GT 20 of both repeatable stages elements using OR logical operator
> As an user I would like to use filtered repeatable stages combination as OR operation [DHIS2-12716]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdSchemes.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/SpringDataValueSetStore.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueSetControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
Backport for 2.37 based on cherry-pick of #9921 - needed manual merge in controller and controller test because of method name changes and formatting changes.
> fix: data value set export by data element group [DHIS2-12691] (2.37)

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java
(cherry picked from commit 2e8dd891d8b620d7341ec32cb6a7a9ac8426c02c)
> fix: Predictors with multiple disaggs DHIS2-12702 (#9892)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/MapView.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/AnalyticalObjectStoreTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_39__Add_organisationUnitCoordinateField_column_to_mapView_table.sql
https://jira.dhis2.org/browse/DHIS2-12734
> feat: add orgUnitField to Map View

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
Changes the date fields from String to Date in order to have consistent and correct date formatting.
> fix: Change date fields from string to Date

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/security/TrackerAccessManagerTest.java
* fix: Fix NPE checking for null org unit [DHIS2-12713]
* Code review fix
> fix: Fix NPE checking for null org unit [DHIS2-12713] (#9957)

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/TranslatablePropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
backport https://github.com/dhis2/dhis2-core/pull/9575
> fix: not persisted property should not be translatable(2.37)

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/TranslatablePropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
backport https://github.com/dhis2/dhis2-core/pull/9575
> fix: not persisted property should not be translatable(2.36)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
(cherry picked from commit 49bbd2517739406f3ee911d40ff15e7c9d6d946a)
> fix: Change date fields from string to Date (#9945)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/outbound/GatewayResponse.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SmsGateway.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SmsMessageSender.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/SmsMessageSenderTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_38__Updates_Sms_Config.sql
see https://github.com/dhis2/dhis2-core/pull/9935
> fix: Sms configuration update [ DHIS2-12590 ] [ 2.38 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
Jira: [[DHIS2-12579](https://jira.dhis2.org/browse/DHIS2-12579)]
> fix: Error message when trying to send a user invite

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/9991
> fix: can't translate program(2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/9991
> fix: can't translate program(2.36)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
https://jira.dhis2.org/browse/DHIS2-12634
forward port from https://github.com/dhis2/dhis2-core/pull/9811
> fix: event api missing dataValues when fields parameter is empty

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/9991
> fix: can't translate program(2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
forward port from https://github.com/dhis2/dhis2-core/pull/9811
> fix: event api missing dataValues when fields parameter is empty(2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/patch/Mutation.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Jira: [[DHIS2-12779](https://jira.dhis2.org/browse/DHIS2-12779)]
> fix: Fix broken user PATCH method

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/reservedvalue/hibernate/ReservedValue.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_52__Add_index_to_reserved_value.sql
see see https://github.com/dhis2/dhis2-core/pull/9983
> fix: /generateAndReserve returns duplicate values when attribute pattern contains a constant [ DHIS2-12182 ] [ 2.36.9 ]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/reservedvalue/hibernate/ReservedValue.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_44__Add_index_to_reserved_value.sql
see see https://github.com/dhis2/dhis2-core/pull/9983
> fix: /generateAndReserve returns duplicate values when attribute pattern contains a constant [ DHIS2-12182 ] [ 2.37.4 ]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
forward port from https://github.com/dhis2/dhis2-core/pull/9811
> fix: event api missing dataValues when fields parameter is empty(2.36)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
forward port from https://github.com/dhis2/dhis2-core/pull/9811
> fix: event api missing dataValues when fields parameter is empty(2.37)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
This reverts commit fe82c49659b65fd31b60b0a2378778f2f324b6b5.
> fix: [revert] added aliases for repeatable stages sub-selects [DHIS2-12761] (#10000) (#10015)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
This reverts commit ff4e978df6bcda0db12bb1922e5be3232507be54.
> fix: [revert] added aliases for repeatable stages sub-selects [DHIS2-12761] (#10000)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sharing/AccessObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserGroupAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserGroupAccess.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
* fix: set displayName on UG/UGA if requested by field filter
* fix: rename displayName => getDisplayName
* fix: adds displayName to user/userGroup sharing block
* fix: refactor apply methods into a single generic method
* fix: make AccessObject.displayName read-only
* fix: minor rename
> fix: set displayName on UG/UGA if requested by field filter (#10061)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/calendar/AbstractCalendar.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/DateUtilsTest.java
[DHIS2-12153](https://jira.dhis2.org/browse/DHIS2-12153)
Check year greater than zero
> fix: Invalid date in tracker data entry [ DHIS2-12153 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/AttributeValue.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetA.xml
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonAttributeValueBinaryType.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryType.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
> fix: support attribute value expansion in new field filter

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/AttributeValue.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetA.xml
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonAttributeValueBinaryType.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/jsonb/type/JsonBinaryType.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
* fix: support attribute value expansion in new field filter
* fix: attribute value error on start up
* fix: add attribute only when requested
* fix datavalueset unit test
Co-authored-by: Viet Nguyen <viet@dhis2.org>
> fix: support attribute value expansion in new field filter (#10070)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/calendar/AbstractCalendar.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/DateUtilsTest.java
see https://github.com/dhis2/dhis2-core/pull/10062
> fix: Invalid date in tracker data entry [ DHIS2-12153 ] [ 2.37 ] 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/jsonpatch/JsonPatchManager.java
https://jira.dhis2.org/browse/DHIS2-12805
> fix: bulk sharing update is slow

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/jsonpatch/JsonPatchManager.java
backport https://github.com/dhis2/dhis2-core/pull/10044
> fix: bulk sharing update is slow(2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/webmessage/WebMessageUtils.java
Tiny fix for a tiny typo reported by the frontend analytics team.
> fix: Typo in import error message [DHIS2-12829]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/calendar/AbstractCalendar.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/DateUtilsTest.java
see https://github.com/dhis2/dhis2-core/pull/10062
> fix: Invalid date in tracker data entry [ DHIS2-12153 ] [ 2.38 ] 

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java
(cherry picked from commit 5cf1a376615d85a822ec7e7a1e91a8bf48d3a5e5)
> fix: update media type for [DHIS2-12366] (#10112)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseDimensionalItemObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalItemObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObjectUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryModifiers.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/QueryPlannerUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceQueryModifiersTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DataDimensionExtractor.java
(cherry picked from commit 125b3a1c6ef666a9683c3e534076361754576638)
> fix: minDate/maxDate/aggregationType DHIS2-12836 (#10091)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/event-data-delete.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/te-data-delete.json
delete tracked entity and event with basic payload ( only uid )
> fix: Missing errorReports when using DELETE strategy and validation fails (event, tei) [ DHIS2-12685 ]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/event-data-delete.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/te-data-delete.json
see https://github.com/dhis2/dhis2-core/pull/10040
> fix: Missing errorReports when using DELETE strategy and validation fails (event, tei) [ DHIS2-12685 ] [ 2.38 ]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
As discussed we do want to allow manual execution of system jobs.
Requires manual testing.
> feat: allow manual execution of system jobs [DHIS2-12852] (2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
As discussed we do want to allow manual execution of system jobs.
Requires manual testing.
> feat: allow manual execution of system jobs [DHIS2-12852]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DatastoreQueryValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DatastoreController.java
> fix: datastore error handling (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHookTest.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/10146
> fix: metadata import corrupts option sort order(2.38)

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
backport https://github.com/dhis2/dhis2-core/pull/10154
> fix: change createAuditEntry error log to debug (2.38)

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/UserActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/importer/TrackerActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_export/MetadataExportTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/TrackerNtiApiTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/OwnershipTests.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
- adds a test to cover bug fix: DHIS2-12732
- reverts addUser helper creating user with ALL authority which skips some access checks and changes test logic
- records from programtempowner and programtempownershipaudit were not removed when deleting soft deleted teis, so hard deletion was crashing. This should fix that as well.
> test: adds tests for breaking the glass

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/credentials/CredentialsExpiryAlertJob.java
Uses the `JobProgress` while processing the users that soon expire.
I did use the user's email in the information which makes it visible when looking at the job progress data in the scheduler or the API for it. So far this API does not require special authority. Do we consider emails to be public?
> feat: provide job progress for credential expiry alert job [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObjectUtils.java
* fix: Indicator attributeOptionCombo DHIS2-12874
(cherry picked from commit c4d8dff05dbbe2a10d7c46dfd6a7c4bc7ade955a)
> fix: Indicator attributeOptionCombo DHIS2-12874 (#10174)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryModifiers.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataelement/DataElement.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceQueryModifiersTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimItemDataElementAndOperand.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimensionalItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/function/FunctionSubExpression.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ExpressionItem.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ExpressionState.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
(cherry picked from commit d7e21c5cfa4b18d1ca171496442610c0e7a9f3d4)
> feat: Indicator sub-expressions DHIS2-11522 (#9923)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/event-data-delete.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/te-data-delete.json
see https://github.com/dhis2/dhis2-core/pull/10040
add missing backport
> fix: Missing errorReports when using DELETE strategy and validation fails (event, tei) [ DHIS2-12685 ] [ 2.37 ] [fix_1]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
please see https://jira.dhis2.org/browse/DHIS2-12897
> fix: [C] pager in analytics response has issues [2.39-DHIS2-12897]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
(cherry picked from commit 8317266ebbc5620b432cff6b3289b36930d9507c)
> fix: update tea query delimiters for [DHIS2-12369] (#10111)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHookTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/10147
> fix: metadata import corrupts option sort order (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHookTest.java
backport https://github.com/dhis2/dhis2-core/pull/10147
> fix: metadata import corrupts option sort order(2.36)

- dhis-2/pom.xml
* Minor patch update to Jackson `2.13.2`.
> chore: update to Jackson 2.13.2

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobProgressTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/DisableInactiveUsersJob.java
Adds `JobProgress` tracking to disable inactive users job.
Again, one additional benefit is that now the steps that are turned into stages do not abort the full process should they fail but only the failing stage so that further stages will also take place.
* goto scheduler app
* create job with type disable inactive users and run it manually (example uses 1 month, 14 days)
* check http://localhost:8080/api/scheduling/completed/DISABLE_INACTIVE_USERS
Example output:
```json
[
{
"status":"SUCCESS",
"completedTime":"2022-03-17T13:52:05.224",
"startedTime":"2022-03-17T13:52:05.088",
"description":"Disable inactive users",
"stages":[
{
"summary":"Disabled 21 users with 1 months of inactivity",
"status":"SUCCESS",
"completedTime":"2022-03-17T13:52:05.166", …
```
> feat: job progress tracking for disable inactive users job [DHIS2-12858]

- dhis-2/dhis-e2e-test/pom.xml
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/TrackedEntityInstanceParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/sync/TrackerSynchronizationTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerControllerAssertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/TrackedEntityInstanceSupportService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/service/TrackedEntityInstanceSupportServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/10060
> fix: field filtering on GET /tracker/... DHIS2-12660 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/calendar/AbstractCalendar.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/DateUtilsTest.java
see https://github.com/dhis2/dhis2-core/pull/10062
> fix: Invalid date in tracker data entry [ DHIS2-12153 ] [ 2.35 ] 

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorCount.java
(cherry picked from commit 29a0dea51a4bdb09216cc1da11542916df3efaab)
> fix: Program indicator count distinct DHIS2-11327 (#9625)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeDto.java
(cherry picked from commit 8e38a45f16cd278260d8d62ccffeb8f46ba2c1f3)
> fix: Add missing fields in MeDto (#10242)

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
backport https://github.com/dhis2/dhis2-core/pull/10154
> fix: change createAuditEntry error log to debug(2.37)

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
backport https://github.com/dhis2/dhis2-core/pull/10154
> fix: change createAuditEntry error log to debug(2.36)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/10247
> fix: /trackedEntityInstances default fields DHIS2-12660 [2.38]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/10258
> chore: remove fields=** from NTI DHIS2-12660 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/leader/election/LeaderManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/leader/election/LeaderElectionJob.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/leader/election/LeaderRenewalJob.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/NoOpLeaderManager.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/leader/election/RedisLeaderManager.java
Adds `JobProgress` tracking to leader election and renewal jobs.
> feat: job progress tracking for leader election and renewal jobs [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/shared/validation/DataValueCheckTest.java
see https://github.com/dhis2/dhis2-core/pull/10271
> fix: Event import fails when data value is an option and sort_order has gaps [ DHIS2-12933 ] [ 2.38 ]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
see https://jira.dhis2.org/browse/DHIS2-12897,
this is part 3, if the pageSize > max limit, max limit is used
> fix: [C] pager in analytics response has issues [2.39-DHIS2-12897-2]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
fix registration date ( aka created ) not sorting. It is currently sorting only ascending, so a fix has been done to create a dynamic order condition
> fix: TEI sort not working in Tracker Capture app [ 2.35 ]

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/CsvNodeSerializer.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/CsvMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
https://jira.dhis2.org/browse/DHIS2-12825
> fix: add back csv for metadata export (2.38)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
backport of https://github.com/dhis2/dhis2-core/pull/10283
> fix: /tracker/trackedEntities?fields with 2 nested fields DHIS2-12660 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/credentials/CredentialsExpiryAlertJob.java
As discussed we use the username as identification in the tracking of sending user credential expiry alerts.
I also saw that I had flipped email and text arguments and broken this job which now is fixed again.
The log statements I removed are already assuming that the progress tracking itself will create equivalent log rows which I plan to add in a later PR.
Also added a general improvment for the job progress tracking so that the process error is set to the error causing the process to fail instead of using a generic error message.
* login
* list jobs http://localhost:8080/api/jobConfigurations
* find the UID of the job with name _Credentials expiry alert_ 
* set setting `credentialsExpiryAlert` to `true`: http://localhost:8080/api/systemSettings/credentialsExpiryAlert?value=true
* run …
> fix: use username for job progress tracking of user credentials expiry alerts [DHIS2-12858]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/ImageResizingJob.java
Adds `JobProgress` tracking to image resizing job.
Each image is processed as an item that can fail. 
job seems no longer in use ... hm
> feat: job progress tracking for image resize job [DHIS2-12858]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_19__Add_ValueType_column_into_programrulevariable.sql
It was approved by the RCB
(Jira [issue](https://jira.dhis2.org/browse/DHIS2-12884?focusedCommentId=49274&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-49274))
> fix: Fix program rule variable migration when a misconfiguration is present [DHIS2-12884]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/file/JsonFileReader.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/ImportStrategyTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventNotesTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/workinglists/TeiFiltersTest.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/workinglists/trackedEntityFilters.json
- adds tests for working list creation and validation DHIS2-12376
- uncomments some assertions to cover a bug fixed in DHIS2-12685
> test: adds api tests for TEI working lists

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
Cherry-pick backport of #10314
> fix: Gist API use inner join for object collection property listings [DHIS2-12972] (2.38)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
backport, see https://jira.dhis2.org/browse/DHIS2-12976
> fix: Missing metadata for weeks in the analytics API [2.38.0-dhis2-12976-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
backport, see https://jira.dhis2.org/browse/DHIS2-12976
> fix: Missing metadata for weeks in the analytics API [2.39-dhis2-12976]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationMapTest.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
Cherry-pick backport of #10330
> fix: NotificationMap capacity cap does not accidentially clear entries [DHIS2-12992] (2.38)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotificationMapTest.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
Cherry-pick backport of #10330
> fix: NotificationMap capacity cap does not accidentially clear entries [DHIS2-12992] (2.38.0)

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
https://jira.dhis2.org/browse/DHIS2-12988
The format of the response from `api/completeDataSetRegistrations` has been changed from 2.38, so need to change the ajax response handler in `form.js`
> fix: complete/incomplete button in data entry form

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
https://jira.dhis2.org/browse/DHIS2-12988
The format of the response from `api/completeDataSetRegistrations` has been changed from 2.38, so need to change the ajax response handler in `form.js`
> fix: complete/incomplete button in data entry form (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
fix join condition between teav and tei
> fix: Query parameter in calls to /api/trackedEntityInstances not working as expected [ DHIS2-11702 ]

- dhis-2/pom.xml
backport #10354 to 2.35 development branch
> fix: Upgrade to the latest Spring version (2.35) [DHIS2-13012]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/10360
> fix: Query parameter in calls to /api/trackedEntityInstances not working as expected [ DHIS2-11702 ] [ 2.38 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/10360
> fix: Query parameter in calls to /api/trackedEntityInstances not working as expected [ DHIS2-11702 ] [ 2.37 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/exception/AnalyticsPagingCriteria.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
**### Needs formal approval from the Change Control Board.**
> fix: Paging issues in event/enrollment analytics [2.38.0-dhis2-12897-backport]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
Cherry-pick from commit in PR #10391
> fix: exclude job progress items info from notifier [DHIS2-12992] (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataExportService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DashboardControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataSetControllerMockTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/category/CategoryComboControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryComboController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementGroupController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/option/OptionSetController.java
https://jira.dhis2.org/browse/DHIS2-13022
> fix: revert new field filter for metadata export with dependencies (2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/XmlPathMappingJackson2XmlHttpMessageConverter.java
**Needs formal approval from Release Control Board.**
> fix: Adding back endpoint removed by mistake [DHIS2-13006]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataExportService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DashboardControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataSetControllerMockTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/category/CategoryComboControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/ProgramControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryComboController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementGroupController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataExportControllerUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/option/OptionSetController.java
backport https://github.com/dhis2/dhis2-core/pull/10398
> fix: revert new field filter for metadata export with dependencies (2.38.0)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramOrgUnitsSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/10324
> chore: prevent mutation of TrackerPreheat.map DHIS2-12563 [2.38]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerImportParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerMessage.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerImportParamsSerdeTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatIdentifiersTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/DefaultTrackerImporter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerAsyncImporter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportRequest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerSyncImporter.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImporterImplTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImporterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/10371
> chore: reduce coupling and mutabilty DHIS2-12563 (#10371)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/ProgramIndicatorControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/ProgramIndicatorController.java
https://jira.dhis2.org/browse/DHIS2-11871
This PR makes `api/programIndicators/expression/description` and `api/programIndicators/filter/description` to support both text and json payload.
> feat: support json payload api/programIndicators

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/10325
> fix: dataValue export file name to include start and end date (2.36)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/10413
> fix: dataValue export file name to include start and end date (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sms/scheduling/SendScheduledMessageJob.java
Adds `JobProgress` tracking to the "scheduled outbound SMS" job.
> feat: job progress tracking for scheduled outbound SMS job [DHIS2-12858]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/SystemUpdateAlertJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/SystemUpdateService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/system/SystemSoftwareUpdateNotifyController.java
Previously I only had the complete job as a single stage. Now the job is split into multiple stages with items in the loops.
> feat: job progress tracking for system update notifications [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/notification/ValidationNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationJob.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/scheduling/MonitoringJob.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/notification/DefaultValidationNotificationService.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/notification/ValidationResultNotificationJob.java
- dhis-2/dhis-services/dhis-service-validation/src/test/java/org/hisp/dhis/validation/ValidationNotificationServiceTest.java
Previously I only had the complete job as a single stage. Now the job is split into multiple stages with items in the loops.
> feat: job progress tracking for result validation job [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackerdataview/TrackerDataView.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/relationshipTypes.json
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/RelationshipTypeObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/RelationshipTypeObjectBundleHookTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
some of the validations have been relaxed.
https://docs.google.com/document/d/10c8BcARHTMWz-iH2XO0UbR4L57iyUt4OStrmSWbktYU/edit
> fix: (2.38.0) tracker data view deserialisation issues [DHIS2-12249]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationLevel.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationLoggerUtil.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
Cherry-pick backport of #10425
> feat: replace certain notifier messages instead of append [DHIS2-13035] (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/StringMethodType.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
see https://github.com/dhis2/dhis2-core/pull/10451
> fix: ORG_UNIT_CODE Generation fails [ DHIS2-13032 ] [ 2.36 ] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionTask.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictorJob.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PredictionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PredictorGroupController.java
Adds `JobProgress` tracking to the `PredictorJob`.
Existing tests were adjusted.
Given the striking number of tests prediction should work correct.
* open scheduler app
* create new job of type `Predictor`, start/end can be year dates like `2021`, `2022`. Predictor and group can be empty.
* run the newly created job manually
* check http://localhost:8080/api/scheduling/running/PREDICTOR
* check http://localhost:8080/api/scheduling/completed/PREDICTOR
* check http://localhost:8080/api/system/tasks/PREDICTOR.json is not empty
```json
[
{
"status":"SUCCESS",
"completedTime":"2022-04-12T16:17:37.074",
"startedTime":"2022-04-12T16:17:36.869",
"description":"Making predictions",
"stages":[
{
"status":"SUCCESS",
"completedTime":"2022-04-12T16:17:36.873",
"startedTime":"2022-04-12T16:17:36.869", …
```
> feat: job progress tracking for predictions job [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/StringMethodType.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
see https://github.com/dhis2/dhis2-core/pull/10451
> fix: ORG_UNIT_CODE Generation fails [ DHIS2-13032 ] [ 2.37 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
Job progress tracking forwards its tracking messages to the (file) logs.
Process and stage levels are logged on `INFO`, item level is logged on `DEBUG`.
Any level failures on `ERROR` and abort an cancel information on `WARN`.
Each message contains 
* the job type (e.g. `PREDICTOR`)
* the job UID (e.g. `DEs8JtNPfvP`)
* type of item (e.g. `Process` or `Stage` or `Item`)
* type of event (e.g. `started`, `completed`, `failed`, `cancelled`)
* the description, summary or error message passed
Any event that completes a node also state the duration in human readable format, e.g. `after 0.016s`.
Small run example for predictors with 2 stages, on `INFO`, so no item level info is shown:
```
UID:DEs8JtNPfvP * INFO  2022-04-13T14:18:29,789 [PREDICTOR DEs8JtNPfvP] Process started: Making predictions …
```
> feat: log job progress [DHIS2-13100]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vValueCount.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vZeroPosValueCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
* fix: V{value_count} in PI filter DHIS2-13099
* fix: ProgramIndicatorServiceTest
(cherry picked from commit efac7618ad1f3d685c66e344ecf701040c0b4374)
> fix: V{value_count} in PI filter DHIS2-13099 (#10516)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventStatusPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidationHookTest.java
TrackerPreheat knows the idSchemes so we should not have to pass it it on put
> chore: simplify TrackerPreheat.put DHIS2-12563

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/metadata_with_program_and_program_rules_with_invalid_ruleActions.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/metadata_with_program_and_program_rules_with_valid_ruleActions.json
PR fixes program rule action validation. Rule action should pass validation even if it does not have associated DataElement or TrackedEntityAttribute.
> fix: Validate rule action WARNING/ERRORONCOMPLETE without DE/TEA [DHIS2-12863]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
https://jira.dhis2.org/browse/DHIS2-13129
> fix: data export missing file name extension

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vValueCount.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vZeroPosValueCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
* fix: V{value_count} in PI filter DHIS2-13099
* fix: ProgramIndicatorServiceTest
(cherry picked from commit efac7618ad1f3d685c66e344ecf701040c0b4374)
(cherry picked from commit a66ac229d8382af1bde7242abb5845d479bfc82b)
> fix: V{value_count} in PI filter DHIS2-13099 (#10516) (#10551)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/10556
> fix: data export missing file name extension (2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/10556
> fix: data export missing file name extension (2.37)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
backport https://github.com/dhis2/dhis2-core/pull/10556
> fix: data export missing file name extension (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/TypeReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/CollectionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/DefaultCollectionService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/10568
> fix: collection api error with additions and deletions in one payload (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/CollectionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/DefaultCollectionService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/10531
> fix: collection api error with additions and deletions in one payload (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/TypeReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/CollectionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/DefaultCollectionService.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/10531
> fix: collection api error with additions and deletions in one payload ( 2.36 )

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
* feat: adds datetime support to dataelements [DHIS2-13115]
* feat: adds datetime support to dataelements [DHIS2-13115]
* feat: adds datetime support to dataelements [DHIS2-13115]
(cherry picked from commit 59cd5fc3e0b87c270f3bd0b4e86c7d5014a39aa9)
> feat: (2.38) adds datetime support to dataelements [DHIS2-13115 DHIS2-13114] (#10538)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
* feat: adds datetime support to dataelements [DHIS2-13115]
* feat: adds datetime support to dataelements [DHIS2-13115]
* feat: adds datetime support to dataelements [DHIS2-13115]
(cherry picked from commit 59cd5fc3e0b87c270f3bd0b4e86c7d5014a39aa9)
> feat: (2.38.0) adds datetime support to dataelements [DHIS2-13115 DHIS2-13114] (#10538)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/RelationshipPreheatKeySupport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/RelationshipImportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHookTest.java
* fix: Fix error when deleting relationships [DHIS2-13146]
* Fix tests
> fix: Fix error when deleting relationships [DHIS2-13146] (#10595)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/DetachUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/UserSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/UsernameValueTypeSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/EnrollmentStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/EventStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/NoteStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/RelationshipStrategy.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/strategy/TrackerEntityInstanceStrategy.java
which is only in preheat.supplier/supplier.strategy
> chore: move DetachUtils closer to usage

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiImportTests.java
- dhis-2/dhis-e2e-test/src/test/resources/setup/tracker_metadata.json
> test: adds tests for attribute import

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/interpretation/DefaultInterpretationService.java
Incorrect URL in messaging app when mentioning interpretation in the Line Listing app.
> fix: Interpretation link for event visualization [DHIS2-13109]

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
* [DAT-263] server time delta with periodic check
* [DAT-263] truncate timezone information if present
* [DAT-263] add adjustment for expiryDays
(cherry picked from commit 4bc2afed283688af6f6d33e55b27d795f636c8a9)
> fix: check server time in data entry DHIS2-11542 (2.35)

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
* [DAT-263] server time delta with periodic check
* [DAT-263] truncate timezone information if present
* [DAT-263] add adjustment for expiryDays
(cherry picked from commit 4bc2afed283688af6f6d33e55b27d795f636c8a9)
> fix: check server time in data entry DHIS2-11542 (2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
see https://github.com/dhis2/dhis2-core/pull/10594
> fix: Performance: relationships endpoint is slow when there are many relationships [ 2.37 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
see https://github.com/dhis2/dhis2-core/pull/10594
> fix: Performance: relationships endpoint is slow when there are many relationships [ 2.35 ] 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
see https://github.com/dhis2/dhis2-core/pull/10594
> fix: Performance: relationships endpoint is slow when there are many relationships [ 2.36 ] 

- dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/form.js
* [DAT-263] server time delta with periodic check
* [DAT-263] truncate timezone information if present
* [DAT-263] add adjustment for expiryDays
(cherry picked from commit 4bc2afed283688af6f6d33e55b27d795f636c8a9)
> fix: check server time in data entry DHIS2-11542 (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/userdatastore/UserDatastoreEntry.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserDatastoreSuperuserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserDatastoreController.java
backport of #10613 with added change or wording in error message as suggested in that PR.
> feat: user data store impersonate users as superuser [DHIS2-7851] (2.38)

- .github/workflows/dependabot.yaml
- .github/workflows/run-tests.yml
the org secret looks like it is empty, so use the repo one
> ci: adapt 2nd approval token

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
see https://github.com/dhis2/dhis2-core/pull/10594
> fix: Performance: relationships endpoint is slow when there are many relationships [ 2.38 ]

- dhis-2/dhis-e2e-test/pom.xml
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/UserActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
As discussed we add this as minimal feature to extends the tools we have to our disposal in e2e testing.
> feat: POC use of json-tree lib in e2e

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Please see: https://jira.dhis2.org/browse/DHIS2-12979 description
> fix: Data items with null value give incorrect order of repeatable events in line lists [2.39-DHIS2-12979]

- .github/workflows/analyse-pr.yml
Way to go Sonar :(
https://community.sonarsource.com/t/urgent-analyzing-functions-never-stops/62775
They changed the plugin and add a new analyser that is not working for us, I have no clue why. Disabling the new analyser and everything works again as before
> fix: Fix sonar issue in github actions

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/attribute/hibernate/Attribute.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/relationship/hibernate/RelationshipType.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/relationship/hibernate/RelationshipStoreTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_9__Add_column_attributevalues_to_relationshiptype.sql
https://jira.dhis2.org/browse/DHIS2-13244
> feat: add attribute to relationshipType

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
Please see https://jira.dhis2.org/browse/DHIS2-13173
> fix: Param displayProperty:SHORTNAME doesn't return short name [2.37-…DHIS2-13173]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/LabelMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/LabelMapperTest.java
> fix: Map labels on program dates, in events [DHIS2-13212]

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/JsonPatchOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/RemoveByIdOperation.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
https://dhis2.atlassian.net/browse/TECH-1113
> feat: add json patch op remove-by-id

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipKey.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/relationship/RelationshipKeyTest.java
backport of https://github.com/dhis2/dhis2-core/pull/10772
> fix: prevent duplicate relationships from/to events DHIS2-13263 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipKey.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/relationship/RelationshipKeyTest.java
backport of https://github.com/dhis2/dhis2-core/pull/10772
> fix: prevent duplicate relationships from/to events DHIS2-13263 [2.36]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipKey.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/relationship/RelationshipKeyTest.java
backport of https://github.com/dhis2/dhis2-core/pull/10772
> fix: prevent duplicate relationships from/to events DHIS2-13263 [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/hibernate/HibernateProxyUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserUtil.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/LoginTests.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oauth2/DefaultClientDetailsUserDetailsService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationListener.java
Jira: https://jira.dhis2.org/browse/DHIS2-13256
> fix: Initialize all collections related to the current user

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
> fix: (2.38) NV in filters [DHIS2-13164]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimItemDataElementAndOperand.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimensionalItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/function/FunctionSubExpression.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ExpressionState.java
cherry picked from commit [31838dd](https://github.com/dhis2/dhis2-core/commit/31838dd72325a3156bb4e421b0e770edd8c487f6)
> fix: Indicator summing boolean values DHIS2-13227

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimensionalItem.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
* fix: Indicator summing boolean values DHIS2-13227
(cherry picked from commit 4fee39d62d4e10980f6c9aa7788a71524f55b51f)
> fix: Indicator summing boolean values DHIS2-13227 (#10795)

- dhis-2/dhis-e2e-test/pom.xml
Should fix https://github.com/reportportal/agent-java-junit5/issues/102
> chore: update report portal version

- dhis-2/dhis-e2e-test/pom.xml
> chore: update report portal junit5 lib

- jenkinsfiles/dev
default profile was activated by default and it seems that the profile skips tests on master.
> ci: enable unit tests in jenkins dev pipeline

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
Fix issue in [DHIS2-13257](https://jira.dhis2.org/browse/DHIS2-13257)
> fix: Spring security warnings on boot

- dhis-2/pom.xml
jackson databind is managed in it as well
https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom/2.13.3
see https://github.com/FasterXML/jackson-bom#usage
> chore(deps): use jackson bom to manage dependencies

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/UserMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/view/User.java
to the view.User
Mistake was introduced in
https://github.com/dhis2/dhis2-core/commit/5f63b52ac0a4f426145ae43affa58295f804812a#diff-af6eb353ca81a11eb1327dc7da64ebc6544855dd94c87ce1dee94e80ca51a77aL30-R36
> fix: export UserMapper needs to map from UserInfoSnapshot DHIS2-12563

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/CategoryOptionDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/organisationunit/OrganisationUnitServiceTest.java
backport from cherry-pick of #10615 where I reverted the test file changes back to 2.37
> fix: remove OU from category options when OU is deleted [DHIS2-13152] (2.37)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/CategoryOptionDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/organisationunit/OrganisationUnitServiceTest.java
backport from cherry-pick of #10615
> fix: remove OU from category options when OU is deleted [DHIS2-13152] (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/RelationshipActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/teis/RelationshipsTest.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/Relationship.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/relationship/JacksonRelationshipServiceTest.java
- Audit was not working for hard deleted relationships
- Soft deleted relationships were not considered when validating in the old importer
> fix: Fix audit and import error message for relationships [DHIS2-11320]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryItem.java
please see: [https://jira.dhis2.org/browse/DHIS2-12466](https://jira.dhis2.org/browse/DHIS2-12466)
> fix: Potential bug with analytics api when requesting event data from two programs that share a data element[2.39-DHIS2-12466]

- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerIdentifierCollectorTest.java
to cover some changes made here https://github.com/dhis2/dhis2-core/pull/10906 and lots of more cases 😋
> test: test collecting tracker identifiers DHIS2-12563

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/linelisting/CommonRequestMapper.java
caused by https://github.com/dhis2/dhis2-core/pull/10841
> fix: Fix H2 integration tests

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/FileResourceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/FileResourceSupplierTest.java
which should also be in an idScheme aware manner, not assuming only UIDs
> fix: FileResourceSupplier checking DataElement DHIS2-12563

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/OrgUnitValueTypeSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/OrgUnitValueTypeSupplierTest.java
which should also be in an idScheme aware manner, not assuming only UIDs
> fix: OrgUnitValueTypeSupplier checking DataElement DHIS2-12563

- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
Wording as suggested by @Philip-Larsen-Donnelly
> chore: improved wording for disable user account email subject [DHIS2-13307]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
backport https://github.com/dhis2/dhis2-core/pull/10951
> fix: revert response type for collections api ( 2.36.11 )

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/AbstractAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EventAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/AbstractTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/adx/AdxDataServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetExportAccessControlTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceExportTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateUserTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateAclTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAttributesAggregateTest.java
depends on https://github.com/dhis2/dhis2-core/pull/10964
> fix: cleanup dxf2 integration tests setting dependencies

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
(cherry picked from commit 025cc2981ede25f52f8ff5b0d35af4a52c0b9388)
> fix: Delete user with roles [DHIS2-13336] (#10900)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
please see: https://jira.dhis2.org/browse/DHIS2-12979
> fix: Data items with null value give incorrect order of repeatable events in line lists[2.38-DHIS2-12979-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/association/ProgramOrganisationUnitAssociationsQueryBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/collection/CollectionUtils.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/DataSourceConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/SqlUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/ConfigConfiguration.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/JwtConfigConfiguration.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithJwtTokenAuthTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisWebSpringTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfigurationWithJwtTokenAuth.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
- dhis-2/pom.xml
* fix: Upgrade to latest Spring version
> fix: Upgrade to latest Spring version

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/DataType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/dataanalysis/MinMaxOutlierAnalysisService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistAttributeControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
backport based on cherry-pick of #10894 that needed adjustment because `FieldFilterService` was not yet stream based and some of the changed test files did not yet exist.
> feat: render GeoJSON attribute values as JSON when individually requested [DHIS2-13323] (2.38)

- README.md
now that tests also run on master https://github.com/dhis2/dhis2-core/pull/11002
We should highlight if they are broken, so we take immediate action. The sooner new issues are identified the easier/faster they are to fix.
see it rendered https://github.com/dhis2/dhis2-core/blob/acbd0507df2a371a35bf821231e773c016016810/README.md
> ci: highlight broken tests on master

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryItem.java
Please see: https://jira.dhis2.org/browse/DHIS2-12466
> fix: Analytics api when requesting event data from two programs that share a data element [2.37-DHIS2-12466-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryItem.java
please see: https://jira.dhis2.org/browse/DHIS2-12466
> fix: Analytics API when requesting event data from two programs that share a data element [2.38-DHIS2-12466-backport]

- .github/workflows/analyse-pr.yml
- dhis-2/pom.xml
as we do not report coverage to it
> ci: no need for sonarqube profile

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
please see https://jira.dhis2.org/browse/DHIS2-13353
> feat: New handling of coordinates fallback in analytics queries [2.39-DHIS2-13353]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultSecurityService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/SecurityService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/SecurityServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/validation/DefaultSchemaValidator.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
(cherry picked from commit 63846ea30b089db64192850ec134ff7f12f43e86)
> fix: Add back feature for invites where invitee chose username (#10902)

- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/QueryItemTest.java
please see https://jira.dhis2.org/browse/DHIS2-13390
> fix: Unit test for error path - DHIS2-12466 [2.39-DHIS2-13390]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/programindicator/DefaultProgramIndicatorSubqueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/ProgramIndicatorSubqueryBuilderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramExpressionItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemAttribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemStageElement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2Condition.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2CountIfCondition.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/FunctionIf.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareNotEqual.java
* fix: Prog. Ind. boolean as bool/number DHIS2-12657
* fix: SonarCloud
(cherry picked from commit 6ed45503bea04f6e081fc6545404678dbae9b63d)
> fix: Prog. Ind. boolean as bool/number DHIS2-12657 (#10918)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Cal.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/calendar/DateTimeUnitTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobProgressTest.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/DefaultAppHubService.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/resourcetable/ResourceTableServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/security/AnalyticsSecurityManagerTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/attribute/AttributeValueServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/patch/PatchServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/InMemoryQueryEngineTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/render/DeserializeTestBean.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/render/RenderServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/PdfDataEntryFormUtil.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/importsummary/ImportConflictTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
Type of issues addressed:
* switch case coverage and fall-through
* test with no assert
* missing or incorrectly used try-with-resources
* method always returns same value (unnecessary return value)
* test POJO has name that made it be considered as test class without test
A few non blocker issues that were near the blockers addressed like adding `final` or using `append` on a string builder instead of `+` concatenation.
> chore: address sonar blocker issues

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/programindicator/DefaultProgramIndicatorSubqueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/ProgramIndicatorSubqueryBuilderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramExpressionItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemAttribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemStageElement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2Condition.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2CountIfCondition.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/FunctionIf.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareNotEqual.java
Backported from https://github.com/dhis2/dhis2-core/pull/10918
> fix: Program indicator boolean as boolean/number [DHIS2-12657]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/programindicator/DefaultProgramIndicatorSubqueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/ProgramIndicatorSubqueryBuilderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramExpressionItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemAttribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemStageElement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2Condition.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2CountIfCondition.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/FunctionIf.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareNotEqual.java
(cherry picked from commit ef8d74d882c3c07854e444ada6351d3ad5b1e5af)
> fix: Program indicator boolean as boolean/number [DHIS2-12657] (#11061)

- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/DataSourceConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/HibernateConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/DefaultHibernateConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/JwtConfigConfiguration.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/ApiTokenWebTestConfigProviderConfiguration.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithApiTokenAuthTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithJwtTokenAuthTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisWebSpringTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfigurationWithAuth.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfigurationWithJwtTokenAuth.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestDataSourceConfiguration.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
- dhis-2/pom.xml
* fix: Upgrade to latest Spring version (#10394)
> fix: Upgrade to latest Spring version (#10980)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserDatastoreController.java
Turns out the idea https://github.com/dhis2/dhis2-core/pull/10613#discussion_r862638220 wasn't that good. But I didn't forget it altogether.
> chore: better error message wording [DHIS2-7851]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
backport https://github.com/dhis2/dhis2-core/pull/11019
> fix: lazily initialize with no session for default objects (2.38) 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
backport https://github.com/dhis2/dhis2-core/pull/11019
> fix: lazily initialize with no session for default objects (2.37) 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
backport https://github.com/dhis2/dhis2-core/pull/11019
> fix: lazily initialize with no session for default objects (2.36)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/apikey/ApiTokenAuthenticationToken.java
(cherry picked from commit 5febdef74c8986c15129c38b20eaf73ff12818dc)
> fix: Broken ApiToken internal authority list (#11072)

- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/hibernate/HibernateValidationRuleStore.java
Cherry-pick backport of #11064
> fix: update validation rules via super.update (2.36)

- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/hibernate/HibernateValidationRuleStore.java
Cherry-pick backport of #11064
> fix: update validation rules via super.update (2.37)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
(cherry picked from commit e2da90f14135bdceb09302476a2e0bad12dbd714)
> fix: Account creation by invitation fails (#11110)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/account.js
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/useraccount/account.vm
(cherry picked from commit e2da90f14135bdceb09302476a2e0bad12dbd714)
> fix: Account creation by invitation fails (#11110) (#11124)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
On request of @Philip-Larsen-Donnelly the restrictions on user names get relaxed to also allow upper case letters.
> fix: allow upper case letters in user names [DHIS2-13444] (2.38)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
On request of @Philip-Larsen-Donnelly the restrictions on user names get relaxed to also allow upper case letters.
> fix: allow upper case letters in user names [DHIS2-13444] (2.38.1)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
On request of @Philip-Larsen-Donnelly the restrictions on user names get relaxed to also allow upper case letters.
> fix: allow upper case letters in user names [DHIS2-13444]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/10842
> fix: update Option.sortOrder resulted with null sortOrders (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/11130
> fix: metadata with dependencies export mapView as embeddedObject (2.38)

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
* fix: Fixes broken authority listing via Struts layer
[DHIS2-13457](https://jira.dhis2.org/browse/DHIS2-13457)
> fix: Fix broken authority listing via Struts layer (#10467)

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/AuditHibernateListenerTest.java
https://jira.dhis2.org/browse/DHIS2-13457
- Audit record is generated based on Schema but currently it's including all properties even if property.readable = false.
- Add a check for `non-readable` property in `AbstractHibernateListener.createAuditEntry()`
- Added mock test for this as the `AuditIntegrationTest` is currently disabled because of test framework limitation.
Screenshot
Text
```
* INFO  2022-06-29T19:04:34,698 {"auditType":"UPDATE","auditScope":"METADATA","createdAt":"2022-06-29T19:04:34.659335","createdBy":"system","klass":"org.hisp.dhis.user.User","uid":"IC1o0DI2iWu","attributes":{"uid":"IC1o0DI2iWu","attributeValues":[]},"data":{"passwordLastUpdated":"2021-03-18T11:52:33.352","created":"2021-03-18T11:52:18.099","invitation":false,"externalAuth":false,"selfRegistered":false," …
```
> fix: exclude non-readable property from audit record

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/AuditHibernateListenerTest.java
backport https://github.com/dhis2/dhis2-core/pull/11197
> fix: exclude non-readable property from audit record (2.38)

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/AuditHibernateListenerTest.java
backport https://github.com/dhis2/dhis2-core/pull/11197
> fix: exclude non-readable property from audit record (2.37)

- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
- dhis-2/dhis-support/dhis-support-artemis/src/test/java/org/hisp/dhis/artemis/audit/listener/AuditHibernateListenerTest.java
backport https://github.com/dhis2/dhis2-core/pull/11197
> fix: exclude non-readable property from audit record (2.36)

- dhis-2/pom.xml
Adding this to the placeholder hotfix branch so that it is included if we need to use this hotfix.
> chore: upgrade to latest Struts

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventStoreTest.java
https://jira.dhis2.org/browse/DHIS2-13306
Add sql parameter map for simple bindings e.g. = (equals).  
More complex bindings will be checked in https://jira.dhis2.org/browse/DHIS2-13455 also to break the work of using named parameters in at least 2 issues
> fix: Refactor Event SQL to use named parameters - Simple bindings [ DHIS2-13306 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/util/CollectionUtilsTest.java
Adds option sets to data entry metadata response.
> feat: Add option sets to data entry metadata [DHIS2-12522]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SqlViewController.java
The issue fixed here is unlikely the one reported for older versions. Still XML export of the view data was also broken in master. As far as I can tell this is due to not completed replacement of the `RootNode` with writing directly to the output using `GridUtils` (for XML) or returning the `Grid` (for JSON).
> fix: SQL view XML output [DHIS2-9213]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SqlViewController.java
> fix: SQL view XML output [DHIS2-9213] (2.38)

- dhis-2/dhis-web-api-test/pom.xml
- dhis-2/lombok.config
Annotate Lombok generated methods and classes with lombok.Generated so that code scanning tools like https://github.com/dhis2/dhis2-json-schema-generator can handle generated code in a better way.
> Annotate Lombok generated methods and classes with lombok.Generated

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global_id.properties
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/HibernatePropertyIntrospector.java
See https://jira.dhis2.org/browse/DHIS2-13386.
> fix: sharing returned with incorrect xml format (2.37) [DHIS2-13386]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/SchedulingController.java
backport based on #11246 with manual merge.
> fix: always propagate end of process to delegate progress trackers [DHIS2-13474]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Reference.java
Drop lombok.Generated annotation since this is now generated by Lombok itself.
> Drop lombok.Generated annotation

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SchemaControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/SchedulingController.java
> fix: always propagate end of process to delegate progress trackers [DHIS2-13474] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
> fix: auto-complete running job progress processes [DHIS2-13489] (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/BulkSmsGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/ClickatellGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/GenericHttpGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SMPPGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsGatewayConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/sms/SmsGatewayController.java
Adds field filtering capabilities to `/api/gateways` endpoint. Since `isDefault` field is messing up with field/getter/setter auto detection (`isDefault` and `setDefault` methods) we are using a `@JsonProperty` annotation to set the name to `isDefault` (if not it would be `default`).
[DHIS2-9241](https://jira.dhis2.org/browse/DHIS2-9241)
> feat: field filtering in /api/gateways

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
see https://github.com/dhis2/dhis2-core/pull/11271
> Performance optimisation when fetching events from Event Programs [ DHIS2-13443 ] [ 2.38 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
see https://github.com/dhis2/dhis2-core/pull/11271
> Performance optimisation when fetching events from Event Programs [ DHIS2-13443 ] [ 2.36 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
see https://github.com/dhis2/dhis2-core/pull/11271
> Performance optimisation when fetching events from Event Programs [ DHIS2-13443 ] [ 2.37 ]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/11332
> fix: NPE when getting tracker/events CSV DHIS2-13413 [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventServiceTest.java
backport of https://github.com/dhis2/dhis2-core/pull/11338
> fix: /api/tracker/events CSV export misses events without data values DHIS2-13519 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionGroupStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/OptionGroupDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/hibernate/HibernateOptionGroupStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/option/OptionGroupStoreTest.java
backport https://github.com/dhis2/dhis2-core/pull/11289
> fix: delete option linked with OptionGroup(2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/OptionGroupDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/hibernate/HibernateOptionGroupStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/option/OptionGroupStoreTest.java
backport https://github.com/dhis2/dhis2-core/pull/11289
> fix: delete option linked with OptionGroup (2.37) 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/OptionGroupDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/hibernate/HibernateOptionGroupStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/option/OptionGroupStoreTest.java
backport https://github.com/dhis2/dhis2-core/pull/11289
> fix: delete option linked with OptionGroup (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/attribute/DefaultAttributeValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/attribute/NumberCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/MetadataAttributeCheckTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
Follow up on https://github.com/dhis2/dhis2-core/pull/11335
> feat: add phone number validation

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
> fix: update lastUpdated field when event is deleted (#11315)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
(cherry picked from commit d903ba0e7eaa48a72eb534132c68f80f2625db35)
> fix: sorting by OUGS/COGS in query analytics [DHIS2-13286] (#10899)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
(cherry picked from commit 336a4c206938a264d27dd3eb67dc75df83483f30)
> fix: alias for coordinates [DHIS2-13225] (#10896)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/QueryItemHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryItemHelperTest.java
please see: https://jira.dhis2.org/browse/DHIS2-13538
> fix:Metadata item duplication for OptionSets in events/analytics [2.39-DHIS2-13538]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/AnalyticsTableType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEnrollmentsAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcTeiEventsAnalyticsTableManager.java
This PR aims to add the missing Period columns in the TEI analytics tables.
It's part of the Analytics table export process.
> feat: Add Missing Columns in Tracker Analytics Tables [DHIS2-13560]

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
https://jira.dhis2.org/browse/DHIS2-13580
> fix: sharing userGroup displayName is empty

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
https://jira.dhis2.org/browse/DHIS2-6183
> fix: missing optionGroup when export program with dependencies

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/option/hibernate/OptionGroup.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_21__Add_description_optiongroup.sql
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonIdentifiableObject.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/OptionGroupControllerTest.java
Adds `description` `text` column to `optiongroup` table.
> fix: add description column to option group [DHIS2-7882]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
please see: https://jira.dhis2.org/browse/DHIS2-13573
> fix: NPE in /query/events [2.39-DHIS2-13573]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
Adds attribute ID columns to metadata CSV export.
Also the CSV generation no longer makes the intermediate step of creating a `List<Map<?,?>>` for the rows.
Instead each row is filled into an array (which is reused) and then written directly to the string output via a mapped object writer.
> feat: attribute ID columns for metadata CSV [DHIS2-11867]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostDeleteEventListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deletedobject/hibernate/DeletedObjectPostInsertEventListener.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaCriteriaQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/pom.xml
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/BaseCacheEvictionService.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/DbChangeEventHandler.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/DebeziumCacheInvalidationEnabledCondition.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/DebeziumPreStartupRoutine.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/DebeziumService.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/DebeziumSpringConfiguration.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/HibernateFlushListener.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/KnownTransactionsService.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/StartupDebeziumServiceRoutine.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/debezium/TableNameToEntityMapping.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/CacheEventOperation.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/CacheInvalidationListener.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/PostCollectionEventCacheListener.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/PostEventCacheListener.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/RedisCacheInvalidationConfiguration.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/RedisCacheInvalidationEnabledCondition.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/RedisCacheInvalidationPreStartupRoutine.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/RedisCacheInvalidationSubscriptionService.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/StartupRedisCacheInvalidationServiceRoutine.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
(cherry picked from commit 6e59860aa63673df16c2298e011669082cf9294a)
> feat: redis pub/sub based cache invalidation (#11434)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithApiTokenAuthTest.java
This change fixes the test-fails locally for me. I have been unable to understand why the problem happened in the first case, but this change seem to resolve the issue.
> fix: Failing H2 tests

- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
Adds a simple letter `ValueType` validation. Any single character that is a letter of some kind is valid. That includes any unicode letter.
> fix: letter data value type validation [DHIS2-12687]

- README.md
The quality gate is passing now 😄 to keep it that way lets display it 😋
> docs: add sonarcloud quality gate badge

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/11467
> fix: NoEntityFound exception for userService.getDisplayName() (2.37)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/11467
> fix: NoEntityFound exception for userService.getDisplayName() (2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
backport https://github.com/dhis2/dhis2-core/pull/11467
> fix: NoEntityFound exception for userService.getDisplayName() (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueAuditQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueAuditService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueAuditStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeValueAuditQueryParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeValueAuditService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeValueService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueAuditService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/DefaultTrackedEntityAttributeValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/hibernate/HibernateTrackedEntityAttributeValueAuditStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/hibernate/HibernateTrackedEntityAttributeValueStore.java
- dhis-2/dhis-support/dhis-support-audit/pom.xml
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datavalue/DataValueAuditServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeValueServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeValueStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeValueAuditTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AuditController.java
- dhis-2/dhis-web/dhis-web-dataentry/src/main/java/org/hisp/dhis/de/action/GetHistoryAction.java
Introduces `DataValueAuditQueryParams` and `TrackedEntityAttributeValueAuditQueryParams` as centralized classes for audit query parameters. Avoids having many method overloads and methods with very long signatures.
Adds extra tests. Removes unused methods.
> refactor: Centralized query object for data value audit service

- jenkinsfiles/canary
[Related PR in dhis2/dhis2-server-setup.](https://github.com/dhis2/dhis2-server-setup/pull/12)
> ci: Add stage for deleting old WARs [DEVOPS-188] [skip ci]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/BaseSpringTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/IntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/SingleSetupIntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/TransactionalIntegrationTest.java
https://junit.org/junit5/docs/5.8.0/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtendWith.html
as BaseSpringTest name implies it is a good fit for declaring the use of the SpringExtension
> test: ExtendWith is inherited

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
> fix: cron expression validation [DHIS2-9768] (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
> fix: cron expression validation [DHIS2-9768] (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
> fix: cron expression validation [DHIS2-9768] (2.36)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/EnrollmentControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/EnrollmentCriteriaMapper.java
If tei doesn't exist, show the entity instead of the program uid.
Co-authored-by: Marc <marc@dhis.org>
Co-authored-by: Stian Sandvold <stian@dhis2.org>
> fix: Fix enrollment error message [DHIS2-11410] (#11468)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/MathUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockI18nFormat.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/PeriodTypeRandomizer.java
Suggestion by sonarCloud, see issue for info
> fix: reuse one instance of Random, instead of creating new each time

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/ValidationUtils.java
fixing some tracker sonar issues https://sonarcloud.io/code?id=dhis2_dhis2-core&selected=dhis2_dhis2-core%3Adhis-services%2Fdhis-service-tracker%2Fsrc%2Fmain%2Fjava%2Forg%2Fhisp%2Fdhis%2Ftracker while waiting on Jenkins/GitHub builds
> chore: fix tracker sonar issues

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/MetadataIdentifier.java
fixes https://sonarcloud.io/code?id=dhis2_dhis2-core&selected=dhis2_dhis2-core%3Adhis-services%2Fdhis-service-tracker%2Fsrc%2Fmain%2Fjava%2Forg%2Fhisp%2Fdhis%2Ftracker%2Fdomain%2FMetadataIdentifier.java
> chore: fix MetadataIdentifier linting issues

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/GridResponse.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SqlViewController.java
> fix: SqlView JSON and XML response with pager [DHIS2-9813] (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/GridResponse.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SqlViewController.java
backport of #11546
import conflict needed manual resolve
> fix: SqlView JSON and XML response with pager [DHIS2-9813] (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/GridResponse.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SqlViewController.java
backport of #11546
As in 2.37 imports needed manual merging.
As controller moved maven module the changes required manual transfer.
> fix: SqlView JSON and XML response with pager [DHIS2-9813] (2.36)

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/about/action/RedirectAction.java
> fix: add index.action suffix for data entry redirect [DHIS2-6705] (2.38)

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/about/action/RedirectAction.java
> fix: add index.action suffix for data entry redirect [DHIS2-6705] (2.37)

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/about/action/RedirectAction.java
> fix: add index.action suffix for data entry redirect [DHIS2-6705] (2.36)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
Important thing to check is if it is valid to remove the XML related annotations.
> chore: use lombok for boilerplate in ImportOptions

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
https://jira.dhis2.org/browse/DHIS2-13455
Fix after the first round of tests. 
Use tei id instead of tei object. Fix date types.
Better tests usage already started and will be merged with https://github.com/dhis2/dhis2-core/pull/11545
> fix: Refactor Event SQL to use named parameters - Complex bindings [ DHIS2-13455 ] fix 1

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
This should fix the issue of running a get request in an integration test with a super user.
> fix: Avoid checks for superuser [DHIS2-13687]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/OrderParam.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/OrderParamsHelper.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/OrderCriteria.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/program/ProgramInstanceQueryParamsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/TrackedEntityCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
Use a constructor if all fields are required. Builders are useful with lots of optional fields.
> chore: OrderParam only has 2 required fields  DHIS2-13648

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/CompleteDataSetRegistration.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DefaultCompleteDataSetRegistrationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/hibernate/HibernateCompleteDataSetRegistrationStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataset/CompleteDataSetRegistrationServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataentry/DataSetCompletionController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/dataentry/CompleteStatusDto.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/dataentry/DataEntryDtoMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/dataentry/DataSetCompletionDto.java
Adds a new API endpoint for completion of data sets. API endpoint:
```
POST /api/dataEntry/dataSetCompletion
```
Request payload format:
```
{
"dataSet": "<id>",
"period": "<iso-period>",
"orgUnit": "<id>",
"attribute": {
"combo": "<id>",
"options": ["<id>", "<id>"]
}
}
```
> feat: Add data entry data set completion endpoint [TECH-1264]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataentry/DataSetCompletionController.java
Sets completed default value for data set completion.
> fix: Set completed default value for data set completion [TECH-1264]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryItem.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
please see: [[J]Filter program indicators in event reports](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-12490&quickFilter=497)
> fix: Program indicators filter operands in event reports [DHIS2-12490]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
FYI: Master was already fixed by https://github.com/dhis2/dhis2-core/pull/11455/files#diff-ab1c17704602a3e544c36772cfa2cd73ae516e73edaea450350779a0b67bb283R122
> fix: set content type for user setting by key API [DHIS2-12782] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/CategoryOption.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_23__Add_description_column_to_category_option.sql
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/category/CategoryOptionServiceTest.java
Adds persisted category option description.
> feat: persisted category option description [DHIS2-9900]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/TwoFactoryAuthenticationUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/TwoFactorController.java
- dhis-2/pom.xml
https://dhis2.atlassian.net/browse/DHIS2-13659
- Add a new endpoint ` /api/2fa/qrCode` which returns an "image/png"
- After this is merged, need to integrate it with current UI and remove the deprecated functions/endpoint.
> feat: add backend function for generating QR code [DHIS2-13659]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/AuthenticationLoggerListener.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/TextUtils.java
Jira: [DHIS2-13497](https://dhis2.atlassian.net/browse/DHIS2-13497)
> fix: Do not strip comma and semicolon in auth logger output [DHIS2-13497]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
Sets the `Content-Type` header while any `Accept` is mapped to the method.
> fix: user settings value by key set header accept all [DHIS2-13711]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
> fix: user settings value by key set header accept all [DHIS2-13711] (2.38)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
> fix: user settings value by key set header accept all [DHIS2-13711] (2.37)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
> fix: user settings value by key set header accept all [DHIS2-13711] (2.36)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
backport of #11691
Note that the test changed in master does not exist in 2.37
> fix: only create data value audit if value changes [DHIS2-13705] (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryItem.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
Backport for https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-12490&quickFilter=497
> fix: Program indicators filter operands in event reports [2.38-DHIS2-12490-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
backport, please see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13573&quickFilter=497
> fix: NPE in /query/events [2.38-DHIS2-13573-backport]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackedEntityInstanceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
Add xml in web config regex to accept xml path extension requests
> fix: Accept xml path extension [DHIS2-13684]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
and fix 2 sonar issues of redundant call to toString()
> test: use suppliers in assertContainsOnly DHIS2-13648

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/geojson/DefaultGeoJsonService.java
On request of @turban I added support for importing files with a single GeoJSON `Feature` object as root.
> feat: GeoJSON import allow single Feature files [DHIS2-7171]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
> feat: provide default for DN driver class configuration [DHIS2-13708] (2.39)

- jenkinsfiles/canary
- jenkinsfiles/eos
- jenkinsfiles/stable
> ci: Apply maven dependency fetching opts to non-dev pipelines [skip ci] [2.38]

- jenkinsfiles/canary
- jenkinsfiles/eos
- jenkinsfiles/stable
> ci: Apply maven dependency fetching opts to non-dev pipelines [skip ci] [2.37]

- jenkinsfiles/canary
- jenkinsfiles/eos
- jenkinsfiles/stable
> ci: Apply maven dependency fetching opts to non-dev pipelines [skip ci] [2.35]

- jenkinsfiles/canary
- jenkinsfiles/eos
- jenkinsfiles/stable
> ci: Apply maven dependency fetching opts to non-dev pipelines [skip ci] [2.34]

- jenkinsfiles/eos
- jenkinsfiles/stable
> ci: Apply maven dependency fetching opts to non-dev pipelines [skip ci] [2.33]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
backport of https://github.com/dhis2/dhis2-core/pull/11775
> test: be more lenient in cache header assertion [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
> fix: only create data value audit if value changes - single update [DHIS2-13705] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
> fix: only create data value audit if value changes - single update [DHIS2-13705] (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
> fix: only create data value audit if value changes - single update [DHIS2-13705]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DateRange.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/DataQueryParamsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/EventQueryParamsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRendererTest.java
see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13694&quickFilter=497
> fix: Event Date filter not respecting individual dates selection [2.39-DHIS2-13694]

- dhis-2/DHISFormatter.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapperTest.java
- Remove some null checks for initialized order fields.
- Clean up some Sonar code smells
- Fix formatter in order to remove some formatter ignore tags
> feat: Clean up JdbcEventStore class [DHIS2-13648]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
Add test for order on multiple attributes. Check that if the first order attribute is equal then the order is based on the second one
> feat: Add test for order on multiple attributes [DHIS2-13648]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
and remove unnecessary null checks and filtering of already filtered order parameters
> chore: split transformation from instantiation DHIS2-13648

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/CrudControllerPagingTest.java
backport https://github.com/dhis2/dhis2-core/pull/11813
> fix: broken paging with order parameter (2.39)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
https://dhis2.atlassian.net/browse/DHIS2-13736
> fix: (2.38) Validate program rule when using WARNINGONCOMPLETE and ERRORONCOMPLETE

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DateRange.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/DataQueryParamsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRendererTest.java
just backport to https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13694&quickFilter=497
> fix: Event Date filter not respecting individual dates selection [2.39-DHIS2-13694-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DateRange.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/DataQueryParamsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRendererTest.java
just backport of https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13694&quickFilter=497
> fix: Event Date filter not respecting individual dates selection [2.38-DHIS2-13694-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOwnershipWriter.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcOwnershipAnalyticsTableManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcOwnershipWriterTest.java
* fix: simpler ownership analytics SElLECT TECH-1432
* fix: JdbcOwnershipAnalyticsTableManagerTest
Co-authored-by: Maikel Arabori <51713408+maikelarabori@users.noreply.github.com>
(cherry picked from commit e1a570ddaf6b291152e7df5860f9a66fe005008c)
> fix: simpler ownership analytics SELECT TECH-1432 (#11847)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodType.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/period/PeriodTypeTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/PeriodOffsetUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemPeriodBase.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemPeriodInYear.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemYearlyPeriodCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/dataitem/ItemPeriodInYearTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/dataitem/ItemYearlyPeriodCountTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
(cherry picked from commit 57c41b987b04a106161c544fbe77b5d2762f499e)
> fix: yearToDate with periodOffset DHIS2-13774 (#11841)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
just backport, see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13700&quickFilter=497
> fix: Analytics query fails for Event data item of type TEXT [2.39-DHIS2-13700-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
backport, see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13700&quickFilter=497
> fix: Analytics query fails for Event data item of type TEXT [2.38-DHIS2-13700-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
backport, see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13700&quickFilter=497
> fix: Analytics query fails for Event data item of type TEXT [2.37-DHIS2-13700-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
backport, see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13700&quickFilter=497
> fix: Analytics query fails for Event data item of type TEXT [2.36-DHIS2-13700-backport]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/JCloudsAppStorageService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/util/ZipFileUtils.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/util/ZipFileUtilsTest.java
> feat: support application zip archives with a top-level directory [DHIS2-13760] (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
backport https://github.com/dhis2/dhis2-core/pull/11667
> fix: NPE in OptionObjectBundleHook.preUpdate (2.38)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
see https://github.com/dhis2/dhis2-core/pull/11822
> fix: Slow PSQL queries when retrieving /events [ DHIS2-12039 ] [ 2.38 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-test-integration/src/test/resources/tracker/simple_metadata.json
* fix: Ensure filter valueType is applied in event query
* chore: Code style
* test: Fix integration test failure
* fix: Add tests and fix numeric attribute filter [DHIS2-13676]
* fix: Make filter attribute query to not rely on order of expression in the join
* Fix sonar code smells
* Fix sonar code smells
Co-authored-by: Enrico Colasante <enrico@dhis2.org>
> fix: Ensure filter valueType is applied in event query [DHIS2-13676]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
backport https://github.com/dhis2/dhis2-core/pull/11667
> fix: NPE in OptionObjectBundleHook.preUpdate (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/Sharing.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/sharing/UserGroupAccess.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultEventStore.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/HibernatePropertyIntrospector.java
backport https://github.com/dhis2/dhis2-core/pull/11243 and https://github.com/dhis2/dhis2-core/pull/11617
There are some unrelated code formats changes due to 2.36 branch is merged with some un-formatted code.
> fix: sharing returned with incorrect xml format (2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
see https://github.com/dhis2/dhis2-core/pull/11822
> fix: Slow PSQL queries when retrieving /events [ DHIS2-12039 ] [ 2.37 ]

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
> fix: always return text/plain content type for single user setting [DHIS2-12782] (2.36)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
> fix: always return text/plain content type for single user setting [DHIS2-12782] (2.37)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventCoordinateService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/EventCoordinateService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/DefaultEventCoordinateServiceTest.java
see: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13528&quickFilter=497
> fix: New fallback logic for geometry in analytics [2.40-DHIS2-13528-3]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
> fix: npe on identifiers map in preheat [ JENKINS BUILD ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
* fix: Force ForkJoinPool in JobProgress DHIS2-13758
* fix: remove unneeded test
(cherry picked from commit 02ddbcf3a6183c688cc9746f9e4730e611a7c10d)
> fix: Force ForkJoinPool in JobProgress DHIS2-13758 (#11929)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisCustomAuthorizationRequestResolver.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/AzureAdProvider.java
- dhis-2/dhis-support/dhis-support-cache-invalidation/src/main/java/org/hisp/dhis/cacheinvalidation/redis/RedisCacheInvalidationConfiguration.java
(cherry picked from commit 330f9d81bab487f50893e0de6ed5e1893cdbceb9)
> fix: Inconsistent boolean parsing OIDC config (#11952)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcUserService.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/TextUtils.java
(cherry picked from commit 3adab3cd18ab419926a86ad781b1ff96860dfcbf)
> fix: Honor user disabled flag on OIDC logins (#11864)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
(cherry picked from commit 204a4e901ddd94acb07c57dc593d16b94e66aa24)
> fix: Always use logout success handler (#11938)

- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/DhisWebApiWebSecurityConfig.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/security/login.vm
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/action/LoginAction.java
* fix: Show error message on failed OIDC login
Co-authored-by: Morten Hansen <morten@winterop.com>
(cherry picked from commit a005e252366027ec3bd1f7a6d4b5abccc84f42e8)
> fix: Show error message on failed OIDC login (#11869)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcLogoutSuccessHandler.java
* fix: Set default redirect URL for ended session OIDC context
(cherry picked from commit 3fb370a8b2ea4f214696a58a6c18b6ae4faaceab)
> fix: Set default redirect URL for ended session OIDC context (#11870)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisCustomAuthorizationRequestResolver.java
…(#11956)
(cherry picked from commit 78d87f1b6d8f4692b4b6d3dc9e25a0c992d9378a)
> fix: context path parsing inconsistency OIDC custom req resolver 2.39

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolverTest.java
Setup was only needed by one scenario.
> chore: avoid mockito strictness LENIENT #8 [TECH-1195]

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/TextUtils.java
related to [DHIS2-13497
](https://jira.dhis2.org/browse/DHIS2-13497)
> Fix revert overeager sanitizing of logging output 2.39

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/TeiFields.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/query/TeiFullQuery.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/TeiFieldsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/query/TeiFullQueryTest.java
see: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13778&sprint=333&quickFilter=497
> feat: Implement sorting by TEI OU in Cross Program Line listing Cpl development 13778

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/MetadataExportParams.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataSetControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/MessageConverterUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/MetadataExportParamsMessageConverter.java
backport https://github.com/dhis2/dhis2-core/pull/12029
> fix: export metadata uncompressed missing filename (2.39.0)

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
> fix: initialize contextPath before referencing app launchUrl or baseUrl [DHIS2-13837] [2.36]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
> fix: initialize contextPath before referencing app launchUrl or baseUrl [DHIS2-13837] [2.37]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
> fix: initialize contextPath before referencing app launchUrl or baseUrl [DHIS2-13837] [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/filter/AppOverrideFilter.java
> fix: initialize contextPath before referencing app launchUrl or baseUrl [DHIS2-13837] [2.39]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultJpaQueryParser.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/planner/DefaultQueryPlannerTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/metadata/CrudControllerPagingTest.java
backport https://github.com/dhis2/dhis2-core/pull/11832
> fix: QueryPlanner failed to separate persisted / non-persisted (2.36)

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
2.39.0 backport of #11969 and #11923
Approved by RCB
> fix: disallow double, starting, and ending hyphens in usernames [DHIS2-13823] [2.39.0]

- dhis-2/build-dev.sh
and allow running from any dir
> ci: fix linting in build-dev TECH-1433

- jenkinsfiles/dev
- jenkinsfiles/stable
Backport of https://github.com/dhis2/dhis2-core/pull/12066
> chore: Bump dev and stable pipelines timeout [skip ci] [2.39]

- jenkinsfiles/dev
- jenkinsfiles/stable
Backport of https://github.com/dhis2/dhis2-core/pull/12066
> chore: Bump dev and stable pipelines timeout [skip ci] [2.38]

- jenkinsfiles/dev
- jenkinsfiles/stable
Backport of https://github.com/dhis2/dhis2-core/pull/12066
> chore: Bump dev and stable pipelines timeout [skip ci] [2.37]

- jenkinsfiles/dev
- jenkinsfiles/stable
Backport of https://github.com/dhis2/dhis2-core/pull/12066
> chore: Bump dev and stable pipelines timeout [skip ci] [patch/2.39.0]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/implementers/RuleEngineErrorToTrackerWarningConverterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/implementers/SetMandatoryFieldValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/implementers/ShowErrorWarningImplementerTest.java
> fix: Check if value is numeric before parsing as double [DHIS2-13842]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
* fix: Grid order params
* chore: code style
Co-authored-by: Stian Sandvold <stian@dhis2.org>
> fix: Grid order params [2.39-DHIS2-13556] (#12016)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TwoFactorControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/TwoFactorController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/MeController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/dhis-web-commons/javascripts/useraccount/expired.js
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
Jira: [DHIS2-13918](https://dhis2.atlassian.net/browse/DHIS2-13918)
> fix: Not showing password reset on login when credentials have expired

- README.md
- docker-compose.yml
backport of https://github.com/dhis2/dhis2-core/pull/12074
> ci: download demo DB for local dev setup [2.37]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/QueryItemHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryItemHelperTest.java
please see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13872&quickFilter=497
> fix: Code is displayed instead of name for numeric option sets [2.40-DHIS2-13872]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DimensionalObjectProducer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolverTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/configuration/DefaultConfigurationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultDataElementService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DefaultDimensionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobConfigurationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/command/DefaultSMSCommandService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerNotificationThread.java
- dhis-2/dhis-support/dhis-support-audit/src/main/java/org/hisp/dhis/audit/JdbcAuditRepository.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandController.java
Addresses issues found https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=dhis2_dhis2-core
> fix: potential NPEs found by nullness analysis [TECH-1460]

- dhis-2/dhis-services/dhis-service-node/pom.xml
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/CsvNodeSerializer.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityInstanceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/CsvMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
backport https://github.com/dhis2/dhis2-core/pull/12147
> fix: add back CsvMessageConverter for tracker endpoints (2.39.0)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
backport https://github.com/dhis2/dhis2-core/pull/12155
> fix: incorrect content-type for events/query.csv (2.39)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
backport https://github.com/dhis2/dhis2-core/pull/12155
> fix: incorrect content-type for events/query.csv (2.39.0)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/12129
> fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ]  [ 2.39 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/12129
> fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.36 ] 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/12129
> fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.37 ]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
backport, please see: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13872&quickFilter=497
> fix: Code is displayed instead of name for numeric option sets [2.38-DHIS2-13872-backport]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
see https://github.com/dhis2/dhis2-core/pull/12129
> fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.38 ]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
> fix: Code is displayed instead of name for numeric option sets [2.39-DHIS2-13872-backport]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
please see https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13909&quickFilter=497
> fix: Attempting to sort org unit DE results in "No data available" message [2.40-DHIS2-13909]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
* fix: DataValueStore SQL callback handler TECH-1467
* fix: SonarCloud issues
(cherry picked from commit 8d8c05a9e2459a7aef0e98bb67b8df544de447c0)
> fix: DataValueStore SQL callback handler TECH-1467 (#12198)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
Do not reassign the input parameter and move the annotation to the parameter level.
> fix: Improve the logic around the null parameter in setSubscribers [DHIS2-14010]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/IntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/SingleSetupIntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/TransactionalIntegrationTest.java
- dhis-2/dhis-web-api-test/pom.xml
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerIntegrationTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerTestBase.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TEIControllerIntegrationTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/event/EventControllerIntegrationTest.java
- Add DhisControllerIntegrationTest for supporting writing controller tests using postgres db
> feat: add DhisControllerIntegrationTest

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/teis/TrackedEntityInstanceQueryTests.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/TrackedEntityCriteriaMapper.java
see https://github.com/dhis2/dhis2-core/pull/12218
> fix: Internal server error in /trackedEntityInstances/query when there are no filterable attributes [ DHIS2-13076 ] [ 2.39 ]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/update_user_without_createdBy.json
https://dhis2.atlassian.net/browse/DHIS2-14021
> fix: user createdBy is wrongly updated (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceProgramTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/ProgramRuleControllerTest.java
https://dhis2.atlassian.net/browse/DHIS2-13502
> fix: validate duplicate programRule name

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/MessageFormatter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/MessageFormatterTest.java
backport of https://github.com/dhis2/dhis2-core/pull/12295
> fix: remove redundant information from validation errors DHIS2-13325 [2.39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdSchemeParam.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerReportUtils.java
adapted from https://github.com/dhis2/dhis2-core/pull/12295 as the `MetadataIdentifier` was introduced in 2.39
> fix: remove redundant information from validation errors DHIS2-13325 [2.38]

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/config/ServiceConfig.java
backport https://github.com/dhis2/dhis2-core/pull/12319
> fix: getSystemSetting causes performance issue (2.39) 

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/config/ServiceConfig.java
backport https://github.com/dhis2/dhis2-core/pull/12319
> fix: getSystemSetting causes performance issue (2.38) 

- .github/workflows/dependabot.yml
backport of https://github.com/dhis2/dhis2-core/pull/10614
> ci: auto merge dependabot patch PRs [2.38]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/FilledOrganisationUnitLevelController.java
Adds field filtering to `/api/filledOrganisationUnitLevels`.
> fix: add field filtering to filledOrganisationUnitLevels

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/update_user_without_createdBy.json
backport https://github.com/dhis2/dhis2-core/pull/12282
> fix: user createdBy is wrongly updated (2.36) 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DataDimensionItem.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryValidator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/DataQueryParamsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryValidatorTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DefaultDimensionService.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/filter/FilterUtils.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
* Adds "aggregateable" validation of data element operands, which was previously missing.
* Adds unit tests.
* Renames a few variables and reformats a few unit tests.
> fix: Validate data element operand aggregateable status [DHIS2-14199]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
just backport, please see: https://dhis2.atlassian.net/browse/DHIS2-13909
> fix: Sort org unit DE results in "No data available" message [2.39-DHIS2-13909-backport]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/ObjectUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/IdentifiableObjectUtilsTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/update_category_with_different_createdBy.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/update_category_without_createdBy.json
backport https://github.com/dhis2/dhis2-core/pull/12403
> fix: update metadata without createdBy field (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/IdentifiableObjectUtilsTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/update_category_with_different_createdBy.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/update_category_without_createdBy.json
backport https://github.com/dhis2/dhis2-core/pull/12403
> fix: update metadata without createdBy field (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/IdentifiableObjectUtilsTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/update_category_with_different_createdBy.json
- dhis-2/dhis-test-integration/src/test/resources/dxf2/update_category_without_createdBy.json
backport https://github.com/dhis2/dhis2-core/pull/12403
> fix: update metadata without createdBy field (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimItemDataElementAndOperand.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
(cherry picked from commit 50b4ae59f67746ec9d298025f01a75fc053ac321)
> fix: #{deGroup:deGroupUid} bug DHIS2-13456 (#12449)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
> fix: NPE when changing avatar image without F_USER_VIEW authority [DHIS2-9761] (2.37)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
> fix: NPE when changing avatar image without F_USER_VIEW authority [DHIS2-9761] (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
Backport  [[DHIS2-11731]](https://dhis2.atlassian.net/browse/DHIS2-11731)
> fix: (2.38) Fetch nested event notes in trackedEntityInstance endpoint [DHIS2-11731]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/TrackerTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
Backport [DHIS2-11731](https://dhis2.atlassian.net/browse/DHIS2-11731)
> fix: (2.37) Fetch nested event notes in trackedEntityInstance endpoint [DHIS2-11731]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
blocking https://dhis2.atlassian.net/browse/DHIS2-14213
> fix: enrollment of event in event program not found in preheat DHIS2-14295

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
backport of https://github.com/dhis2/dhis2-core/pull/12500
> fix: enrollment of event in event program not found in preheat DHIS2-14295 [2.39]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
backport of https://github.com/dhis2/dhis2-core/pull/12500
> fix: enrollment of event in event program not found in preheat DHIS2-14295 [2.38]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
backport of https://github.com/dhis2/dhis2-core/pull/12500
> fix: enrollment of event in event program not found in preheat DHIS2-14295 [2.37]
