- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalue/StreamingXmlDataValue.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetB.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetBUpdate.xml
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/batchhandler/DataValueBatchHandler.java
When data import updates an existing data value, it sets the created date to the current timestamp, instead of retaining the original data value created date. (By contrast, when data entry updates a data value, it keeps the original data value created date.)
(cherry picked from commit f7fa94becf32359b2257ca365aaf9a4b3f2d6a24)
> fix: keep data value created w/import DHIS2-8379 (#7995)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalue/StreamingXmlDataValue.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetB.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetBUpdate.xml
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/batchhandler/DataValueBatchHandler.java
When data import updates an existing data value, it sets the created date to the current timestamp, instead of retaining the original data value created date. (By contrast, when data entry updates a data value, it keeps the original data value created date.)
(cherry picked from commit f7fa94becf32359b2257ca365aaf9a4b3f2d6a24)
(cherry picked from commit 410198f6bc23be5e93335a8e9be28711d441c064)
> fix: keep data value created w/import DHIS2-8379 (#7995) (#8014)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
This PR will enable the usage of the `paging` parameter.
Currently, this endpoint is always paging which is not useful for displaying events in Maps.
You will notice that the `paging` parameter is set to `true` (as default) to avoid performance issues.
But once the flag `paging` is set to `false` (URL param _paging=false_), the endpoint should not paginate. Instead, it should bring all elements.
**Was already approved by the Release Control Committee, can go into patch/2.36.0.**
> fix: Adding paging flag [DHIS2-10742]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/chart/ChartType.java
- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
These missing enum values were causing conversion issues and as consequence, the item cannot be read by the frontend and displayed on the Dashboard.
> fix: DHIS2-11113: Missing conversion to STACKED_AREA chart

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- Fix ACL query when object's owner is null. The correct condition for `owner` field should be : `user is null || user is owner`
- Added unit tested for both JPA API query and Native SQL in `JpaQueryUtils`
> fix: acl query with owner = null

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataitem/query/ResultProcessor.java
The `programUid` is not needed and is causing issues in the frontend. The `programUid` will not be concatenated in the `id` attribute anymore.
> fix: Remove programUid for PROGRAM_INDICATOR types [DHIS2-11156]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/TypeReport.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserCredentials.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/CreationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DeletionCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DuplicateIdsCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MandatoryAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ObjectValidationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ReferencesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SchemaCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniqueAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniqueMultiPropertiesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UniquenessCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/UpdateCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationHooksCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/DummyCheck.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/UserCredentialsSchemaDescriptor.java
Goal of this PR is to avoid creation of intermediate collections where possible while making the code more readable and easier to debug.
Changes include:
* using `emptyList()` and such where possible
* avoid creating empty `TypeReport` objects (which indirectly also create lots of other objects inclduing collections)
* avoid creating collection that we might need by changing algorithm a bit so that we only create them when we need them
* avoid creating collection copies to allow modification as part of finding out if they have a certain quality, for example by using stream `anyMatch` instead
For all but one `ValidationCheck` the newly created variant `ObjectValidationCheck` could be used.
There instead of returning `TypeReport` which are merged to a single one an extra consumer argument …
> perf: avoid intermediate collections during dxf2 import validation [TECH-547]

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultTranslateSystemSettingManager.java
https://jira.dhis2.org/browse/DHIS2-8712
locale was not used in function call for getting translation
> fix: login page translations [2.35]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/EnrollmentTest.java
There is no ownership record added when enrolling a tei into a program through the new tracker importer. This PR aims at filling that gap.
> fix: [DHIS2-11197] add ownership record when enrolling into a program for the first time (2.36)

- dhis-2/pom-full.xml
After we moved dhis-web-api to the root, the pom-full.xml need to include this.
> fix: Add dhis-web-api tot he pom-full.xml

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
As pagination is the default behaviour to most of the endpoints, we have to keep the same behaviour.
The same logic from other endpoints was added to the method `public boolean isPaging()`.
In that way, we respect the paging for Events and Enrollments.
> fix: Add back pager in metadata for enrollments [DHIS2-11159]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
This fix also includes DHIS2-10066.
With this fix, the event reports will bring results when DE of type Coordinate and OrgUnit are added as part of the columns.
* NOTE that this filter is not usable. It will be used only for display purposes, and show the actual results instead of a blank page. The org unit `uid` will be used in this case, as in 2.33 we do not have support for OrgUnit name.
**This merge is needed before the code freeze of 2.33.**
> fix: Fix coordinates and org. unit in event enrollments [DHIS2-10228]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/RelationshipPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/TrackedEntityPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/EnrollmentTest.java
There is no ownership record added when enrolling a tei into a program through the new tracker importer. This PR aims at filling that gap.
> fix: [DHIS2-11197] add ownership record when enrolling into a program for the first time (2.37)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/LabelMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/LabelMapperTest.java
Follows the same standard as the UI/frontend, which uses predefined labels defined by the user, in order to render the event report columns.
**_Backporting from master._**
> fix: Custom date labels in event reports downloads [DHIS2-9641]

- dhis-2/pom.xml
Due to random connection issues in the GitHub CI pipeline with the Geotools repo. we now host the dep. ourselves.
> chore: Add a DHIS2 controlled Maven repository

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/organisationunit/hibernate/OrganisationUnit.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/organisationunit/OrganisationUnitServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_14__Add_image_column_into_organisationunit_table.sql
This is 2nd of two PRs needed for supporting OrgUnit image upload feature in back-end https://jira.dhis2.org/browse/DHIS2-11172
Test steps:
1. Use api/fileResource to upload an image file to server as in [this doc](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-234/web-api.html#webapi_file_resources) . With request parameter `/fileResources?domain=ORG_UNIT`. Take note of the create fileResourceId from the response.
2. Send POST request to `/api/organisationUnit` to create an OrgUnit, the payload should include required properties to create new OrgUnit and a new property `"image":"fileResourceUid created from step 1"`
3. Verify if OrgUnit is created and linked with created fileResource from step 1
4. Do as step 1 but with a new image. Take note of the create …
> feat: add OrgUnit image property

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
When the notification recipient is of type USERGROUP then notification service throws NPE intermittently.
> fix: NPE while using UserGroup in tracker notifications

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
Small bug regarding org unit column selection in Enrollments query.
The is returning the org unit UID, but the correct is behaviour is returning the NAME. This code addresses this issue.
> fix: Missed sufix in enrollments query [DHIS2-11291]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
This happens when Program Indicators have decimal digits set to ZERO. In such cases, they are evaluated as Long and not Double. So, the code should be prepared to expect Long or Double.
> fix: Class cast exception in Program Indicators [DHIS2-11292]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
Small bug regarding org unit column selection in Enrollments query.
The is returning the org unit UID, but the correct is behaviour is returning the NAME. This code addresses this issue.
> fix: Missing suffix in enrollments query [DHIS2-11291]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerObjectsDeletionService.java
The backport of this issue was just removing the validation in the delete service as they are already performed in the validators
> fix: Remove validations from objects deletion service in new tracker importer [DHIS2-10789]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventValidationTests.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHookTest.java
- Fix program stage instance preheat as it was not loading the list of program stages
- Fix dependencies in DELETE strategy for events. All parameters can be loaded through preheat, there is no need to get the values from the paylaod
- Add new e2e-test to check that missing program stage is extracted from program when it is of type WITHOUT_REGISTRATION
> fix: Get correct program stage from preheated Program [DHIS2-11225]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistAccessControl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistAccessControl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/strategy/AbstractSchemaStrategyCachingTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/strategy/TrackerEntityInstanceStrategyTest.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistValidationControllerTest.java
Noticed a bug for the access filter like `canAccess`, `canRead` etcetera when looking into Gist API equivalent for DHIS2-7734.
This PR fixes the access check which no longer uses `User#canManage` is this often would not allow the filter even though the user is an admin that has read access to all involved data. 
Testing this I also noticed that in order for e.g. `canRead` to work closer to the read filter of the metadata API the current user should be the default argument if no user ID is supplied.
> fix: Gist API access filters authority check [DHIS2-11024]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/SpringDataValueSetStore.java
Remove unused variables `groupAccessCheck`, `userAccessCheck` 
Those are replaced by `JpaQueryUtils.generateSQlQueryForSharingCheck` method
> fix: remove unused code in SpringDataValueSetStore

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
Issue: 
- Import with `skipSharing=true` and no sharing data in payload will return error even though user has write permission.
- There are two sharing checks in importService: 
1)  sharing check for persistedObject ( `SecurityCheck` line 96 )
2) sharing check  for the importing payload's sharing data
- The issue caused by (ii) even if `skipSharing=true`, so if payload doesn't include sharing data, the check will return false.
Fix: 
- Skip sharing check (ii) if `skipSharing=true` , only check for `persistedObject`
- Added integration tests for the fix.
> fix: skip sharing validation when skipSharing=true

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DefaultCategoryService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/callable/CategoryOptionComboAclCallable.java
As I was writing the [DHIS2-9313](https://jira.dhis2.org/browse/DHIS2-9313) documentation for PR [fix: Standardize ADX export parameters](https://github.com/dhis2/dhis2-core/pull/8170), I realized that I should also test ADX export and import for idScheme=attribute. I did, and export worked fine, but import failed when `CategoryOptionCombo` had _idScheme=attribute_.
This is because `DefaultCategoryService.getCategoryOptionComboAcl` was fetching the COC by `IdentifiableProperty` instead of `IdScheme`, so it worked fine for URL, CODE, and NAME, but not for ATTRIBUTE. Changing it to `IdScheme` fixed everything. This was also presumably an existing problem with the other data import formats.
I also removed `CategoryService.getCategoryOptionCombo( IdentifiableProperty property, String id )` …
> fix: Data Import COC IdScheme ATTRIBUTE DHIS2-9313

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistValidator.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistTransformControllerTest.java
Just a small fix for a small issue I noticed during testing. The latest improvements to the validator had introduced a bug causing an NPE when using the `pluck` transformation without an argument (which should pluck the ID).
This PR takes care of it and adds a test to make sure this does not break again.
> fix: Gist API pluck without argument

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/report/Report.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
Small PR following up on QA feedback on Gist API where users would not include fields of user credentials by default (`*` preset).
This is particular inconvinent since user credentials have no API endpoint so that gist API would not link to a gist of the user credentials. User could manually add fields of user credentials by explicitly naming their path (such as `userCredentials.username`) in the `fields` parameter list of fields. 
The solution to this is to expand field presets to the fields of referenced entities as long as those do not have an API endpoint on their own.
For users this now means users without authority by default see users as:
```json
{
"1": {
"id": "DXyJmlo9rge",
"surname": "Barnes",
"firstName": "John",
"userCredentials": {
"username": "android"
}
}
}
```
while user …
> feat: Gist API - include fields of references without endpoint [DHIS2-11323]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/AdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/adx/AdxDataServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportB.adx.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportC.adx.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/adx/exportD.adx.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
While documenting [DHIS2-9313](https://jira.dhis2.org/browse/DHIS2-9313) for PR [fix: Standardize ADX export parameters](https://github.com/dhis2/dhis2-core/pull/8170), I realized that I could very easily support three more options for ADX data export that are already supported for the other export formats XML, JSON, and CSV:
- organisationUnitGroups
- attributeOptionCombos
- lastUpdatedDuration
It seemed better to add the small amount of code to support these options for ADX export than to write in the documentation that ADX does not support each of these options. :)
In fact, the only remaining export option that is supported by the other formats but not ADX is dataElementGroups, as an alternative to dataSets for selecting data elements. Since the ADX export format is based on dataSets …
> fix: More common export options for ADX DHIS2-9313

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserCredentials.java
Just noticed while testing myself that `userCredentials` unnecessarily has the `userInfo` back-reference to the user included in the gist. This adds the annotation to have it ignored.
> fix: ignore user back-reference in user credentials in gist API [DHIS2-11323]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java
The case that was not covered in the previous implementation was:
- existing PRV with same name/program
- object to update had a different UID (generated)
in this case, the check was failing, allowing PRV to be duplicated.
With the current implementation, in case of updates, also UIDs are checked.
> fix: program rule variable name check now also check UID to prevent duplicates [DHIS2-11330]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/CompatibilityGuard.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/LegendDefinitions.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/SeriesKey.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/visualization/CompatibilityGuardTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateAnalyticalObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceFavoritesTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_visualization_with_accesses.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_visualization_with_accesses_update.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization_periods.json
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/visualization/VisualizationDeletionHandler.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_18__New_Columns_in_Visualization.sql
- dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/org/hisp/dhis/usertype/UserTypes.hbm.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/VisualizationController.java
This change is just a regrouping of objects into a parent one (LegendDefinitions) along with the creation of a new one SeriesKey. They are used by the front-end team in order to keep the state of the respective objects in the Visualization object.
See the JIRA DHIS2-11347 for more details.
> feat: Group legend objects and add new SeriesKey object [DHIS2-11347]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApproval.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalAudit.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_19__Migrate_DataApproval_id_column_to_long.sql
Changes PK ids from `int` to `long` for `DataApproval` and `DataApprovalAudit`.
Also cleanup of their `equals` implementation using `Objects.equals` instead of if-else construct.
> chore: use long IDs for data approval [DHIS2-11370]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerMockTest.java
Issue : 
- There is a custom sharing check in FileResourceController. 
- It will only return true for `DOCUMENT` and `USER_AVATAR` ( with `F_USER_VIEW` )
- It will always false for other domains: `DATA_VALUE` `PUSH_ANALYSIS` `ORG_UNIT` `MESSAGE_ATTACHMENT` 
Fix: 
- Only return false for `DATA_VALUE` and `PUSH_ANALYSIS`
- Added mock test for the sharing check
> fix: can't get orgUnit image from FileResourceController

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundle.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OrganisationUnitObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
This PR has nothing to do directly with DHIS2-2162 but in the issue context I looked into `ObjectBundleHook`s and 
`ObjectBundle` and noticed that `getObjectsMap()` was creating intermediate collections and itself was called in loops. 
There were some unnecessary cases of iterating a map by key just to get the values out by the iterated key. If this is "disguised" by using a `forEach` sonar does not seem to recognise this anti-pattern.
Also I felt the extra level of a `Map<Boolean, ...>` for persisted and non-persisted object list made things more complicated to read and process than simply having two individual fields. 
To satisfy the needs of the prior callers of `getObjectsMap()` new methods where introduced instead which simply just read access the existing state for a dedicated use …
> perf: Avoid intermediate collections in ObjectBundle [DHIS2-2162]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramInstanceSupplier.java
The refactored bulk event importer from 2.35, uses a `workContext` to perform validations. The `ProgramInstance` objects populated into the workContext has associated trackedEntityInstance objects with empty ids (primary key). 
Here is a representation of the bug: 
1. When populating the workContext. something like this happens.
```
ProgramInstance pi = new ProgramInstance();
TrackedEntityInstance tei = new TrackedEntityInstance();
tei.setUid("a123459"); //Note that id is not explicitly set here, which means id=0 by default.
pi.setEntityInstance(tei);
```
2. When checking for ownership, this programInstance is passed onto the trackerOwnershipManager. The Manager caches, ownerOrgUnit entries into a temporary cache for 5 minutes. The key to retrieve the ownerOrgUnit from the cache is a …
> fix: TEI ID missing in event creation ownership check [DHIS2-11377] (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
JIRA: https://jira.dhis2.org/browse/DHIS2-11055
port from the hot fix #8251
Issue:
- In AbstractEventService we have a cache for DataElement.
- The cache works fine in testing environment, no error.
- However, in a busy production instance, the cache start working incorrectly. DE retrieved from cache sometime throws lazily initialize exception for the UserGroupAccesses collection although we explicitly initialize the collection before put DE into the cache.
- I guess this happen when the cache item is expired and Cache2k try to refresh the cache without hibernate session, but this theory has not been proved yet.
Fix:
- Replace the Cache<DataElement> cache with a Cache<Boolean> which stores the result of the sharing check ( user, dataElement )
- The method manager.get(DataElement.class, …
> fix: LazyInitializationException when search for TEI [2.35.6]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IndicatorTypeSerializer.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/MetadataItem.java
When an Indicator is present in the meta-data object (in the JSON response), the IndicatorType will be now available in the following format (see **indicatorType**):
```{
"headers": [],
"metaData": {
"items": {
...,
"ReUHfIn0pTQ": {
"uid": "ReUHfIn0pTQ",
"code": "IN_52462",
"name": "ANC 1-3 Dropout Rate",
"description": "Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.",
"dimensionItemType": "INDICATOR",
"valueType": "NUMBER",
"totalAggregationType": "AVERAGE",
"indicatorType": {
"name": "Per cent",
"displayName": "Per cent",
"factor": 100,
"number": false
},
...
}
}```
> feat: Add IndicatorType in analystics meta-data resp [DHIS2-7420]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/SchemaIdResponseMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsServiceTest.java
This feature will be enabled when the client sets the "outputIdScheme=NAME|CODE|UUID" in the GET request/URL.
ie.:
`http://localhost:8080/dhis/api/29/analytics/events/query/eBAyeGv0exc.json?dimension=pe:LAST_4_QUARTERS&dimension=ou:jUb8gELQApl;TEQlaapDQoK;eIQbndfxQMb;Vth0fbpFcsO;PMa2VCrupOd;O6uvpzGd5pu;bL4ooGhyHRQ;kJq2mPyFEHo;fdc6uOvgoji;at6UHUQatSo;lc3eMKXaEfw;qhqAxPSTUXp;jmIPBj66vD6&dimension=Bpx0589u8y0:MAs88nJc9nL;oRVt7g429ZO&dimension=uIuxlbV1vRT:J40PpdN4Wkk;b0EsAxm8Nge&stage=Zj7UnCAulEk&displayProperty=NAME&tableLayout=true&dataIdScheme=NAME&columns=pe;ou;Bpx0589u8y0;uIuxlbV1vRT&rows=pe;ou;Bpx0589u8y0;uIuxlbV1vRT&paging=true&outputIdScheme=NAME`
In the case above, the data elements present in the "rows" element (in the JSON response object) will render the data elements "name" …
> feat: Add outputIdScheme support for Event Analytics [DHIS2-11181]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
JIRA: https://jira.dhis2.org/browse/DHIS2-11055
port  from the hot fix https://github.com/dhis2/dhis2-core/pull/8251
Issue: 
- In `AbstractEventService` we have a cache for `DataElement`.
- The cache works fine in testing environment, no error.
- However, in a busy production instance, the cache start working incorrectly. DE retrieved from cache sometime throws ` lazily initialize exception` for  the `UserGroupAccesses` collection although we explicitly initialize the collection before put DE into the cache.
- I guess this happen when the cache item is expired and Cache2k try to refresh the cache without hibernate session, but this theory has not been proved yet.
Fix:
- Replace the `Cache<DataElement>` cache with a `Cache<Boolean>` which stores the result of the sharing check ( user, …
> fix: LazyInitializationException when search for TEI [2.37]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramInstanceSupplier.java
The refactored bulk event importer from 2.35, uses a `workContext` to perform validations. The `ProgramInstance` objects populated into the workContext has associated trackedEntityInstance objects with empty ids (primary key). 
Here is a representation of the bug: 
1. When populating the workContext. something like this happens.
```
ProgramInstance pi = new ProgramInstance();
TrackedEntityInstance tei = new TrackedEntityInstance();
tei.setUid("a123459"); //Note that id is not explicitly set here, which means id=0 by default.
pi.setEntityInstance(tei);
```
2. When checking for ownership, this programInstance is passed onto the trackerOwnershipManager. The Manager caches, ownerOrgUnit entries into a temporary cache for 5 minutes. The key to retrieve the ownerOrgUnit from the cache is a …
> fix: [DHIS2-11377] tei id missing in event creation ownership check (2.36.2)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
JIRA: https://jira.dhis2.org/browse/DHIS2-11055
port  from the hot fix https://github.com/dhis2/dhis2-core/pull/8251
Issue: 
- In `AbstractEventService` we have a cache for `DataElement`.
- The cache works fine in testing environment, no error.
- However, in a busy production instance, the cache start working incorrectly. DE retrieved from cache sometime throws ` lazily initialize exception` for  the `UserGroupAccesses` collection although we explicitly initialize the collection before put DE into the cache.
- I guess this happen when the cache item is expired and Cache2k try to refresh the cache without hibernate session, but this theory has not been proved yet.
Fix:
- Replace the `Cache<DataElement>` cache with a `Cache<Boolean>` which stores the result of the sharing check ( user, …
> fix: LazyInitializationException when search for TEI  [2.36.2]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/ImportConfig.java
There were 2 subtle issues with the complete data value registration not allowing to set ID schemes using the URL parameters:
1. options were not passed on in `saveCompleteDataSetRegistrationsJson` (used default)
2. options were not used as a fallback in case no scheme was explicitly provided as part of the request body.
> fix: complete data set registrations fallback to URL id schemes [DHIS2-11355]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/DefaultCsvImportService.java
Does a cleanup of CSV import service.
Mostly I wanted to address the `getSafe` that would generate a new unique ID for each object processed.
Such generators often involve randomness which when requested in high volumes has a tendency to become expensive.
Later decided to do a general sonar warnings cleanup of the file.
This is:
* use `Map#computeIfAbsent` instead of `CachedMap#get` (which static analysis tools report as false positive and also we don't really need an actual caching map here)
* use `parseBoolean` instead of `Boolean.valueOf`
* iterate map by `Entry` instead of key and `get(key)`
* use `Supplier` for random ID default value so that it is only generated when actually needed
Also found an actual bug where UID was used instead of code to do the lookup so it would always come …
> chore: addresses sonar warnings in CSV import service

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/QueryKey.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventQueryValidator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
This PR enable Enrollments and Analytics endpoints to accept "NV" as null value in dimension filters.
It only makes sense to use with EQ, NE and IN operators (there's no "not in" operator).
I'm not 100% sure this is exactly what the ticket asked, neither I have enough visibility to understand if it has side effects, so I'd ask @larshelge and @maikelarabori  to have a deep review.
TY
> feat: NV as "null" in Enrollments/Events analytics filters [DHIS2-1219]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractReadOnlyCrudController.java
This PR is an attempt to break the large class `AbstractCrudController` into smaller parts in a way that is useful.
The idea is that the read access methods are extracted to superclasses so that extending controller can chose to only inherit the read-only part of CRUD by not extending the `AbstractCrudController` but the `AbstractFullReadOnlyController` or the `AbstractGistReadOnlyController` depending on if they want just Gist API or both Gist API and classic/full read access API.
PR basically moves methods to newly created superclasses. 
In some cases the visibility is changed to `private` where possible and `protected` methods are made `final` when overriding makes little sense.
> chore: extracts read-only methods from generic CRUD controller

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipKey.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/classStrategy/RelationshipStrategy.java
The complicated query of fetcing existing relationships takes too long when it's fetcing relationships individually. This change gets all relationships uids in one go, and preheats all relationships using those and other uids.
> fix: Refactor Relationship fetching in tracker preheater

- Jenkinsfile-core-dev
Add a safety [timeout](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#timeout-enforce-time-limit) of 20 minutes to prevent stalled builds.
> feat: Add activity timeout to dev pipeline [DEVOPS-65]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicate.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DeduplicationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/exception/ConflictException.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerMvcTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
[DHIS2-11437](https://jira.dhis2.org/browse/DHIS2-11437)
> fix: [DHIS2-11437] - [ PotentialDuplicate ] - Not null for Pair of tracked entities FIX1 [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/ImportConfig.java
As discussed on slack for the complete data set registration import we want to treat `IdScheme.ID` as an alias for `IdScheme.UID`.
This is mainly since it does not make sense to use actual numeric IDs (they should be unknown) and because documentation states `id` as possible value but means `uid` so we decided making this an alias.
> feat: complete data set registration ID schema alias for UID [DHIS2-11355]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ObjectReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/feedback/ImportReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/feedback/ObjectBundleCommitReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/feedback/ObjectBundleValidationReport.java
Fixes 2 issues around error reports:
* when `merge`d reports do not merge with themselves (unintentional NOOP) but with the other provided report
* when setting a list of items by transfering them to an internal data structure in a loop the internal structure is cleared first so it has the effect of a setter (not an adder)
See #8353 for more context.
> fix: error reports merge with other, set items with clear (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ObjectReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/feedback/ImportReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/feedback/ObjectBundleCommitReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/feedback/ObjectBundleValidationReport.java
Fixes 2 issues around error reports:
* when `merge`d reports do not merge with themselves (unintentional NOOP) but with the other provided report
* when setting a list of items by transfering them to an internal data structure in a loop the internal structure is cleared first so it has the effect of a setter (not an adder)
See #8353 for more context.
> fix: error reports merge with other, set items with clear (2.35)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
Replaces use of `@RequestMapping` with one of the other dedicated annotations.
Sadly this was only a semi-automatic refactoring so this does need proper review of every changed line mainly to check that the correct annotation was used for the `method` property.
Oddly enough when mapping multiple HTTP methods to the same method using e.g. both `@PutMapping` and `@PostMapping` does not have the same effect as `@RequestMapping( methods = { PUT, POST } )`. Therefore those keep using `@RequestMapping`.
> chore: replace @RequestMapping with dedicated annotations - CRUD controllers

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/security/EnrollmentSecurityTest.java
It was possible to create enrollments into organisation units for which the program has not given access to. 
Program.getOrganisationUnits() if not empty, will be the list of org units to which enrollments can be created. This validation was missing.
Added the missing validation and a corresponding test case.
> fix: [DHIS2-11405] do not allow enrollments to orgunit without program access (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/OrderCriteria.java
fix: removing nonparsable orders
> fix: order direction is now optional, ASC is default [DHIS2-11429]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataanalysis/FollowupValue.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/dataanalysis/DefaultFollowupAnalysisService.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/dataanalysis/FollowupValueManager.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonFollowupValue.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FollowupAnalysisControllerTest.java
Adds period display name to the followup values. 
Since this needs the i18n service the DB level prefills the field with `null` when mapping DB fields to the all args constructor. 
In the service we then loop over the values and add the display name.
I opted to call the field `peName` to be more consistent with the other fields in `FollowupValue`.
Tests have been adopted and check a simple case.
> feat: adds period name to followup value API [DHIS2-11446]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/Property.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/TranslatablePropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
https://jira.dhis2.org/browse/DHIS2-10763
- This PR add a new property named `i18nTranslationKey` to `Schema` class
- This property will be used by `Translations` app in order to get i18n translations for all properties and display them as labels on UI.
- The app will send a `POST` request to `api/i18n` with payload is the array of `i18nTranslationKeys`.
> feat: add i18nTranslationKey to schema property

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/Cache.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/NoOpCache.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageInstanceServiceTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CappedLocalCache.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/RedisCache.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/cache/CappedLocalCacheTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/cache/TestCache.java
Trying to tick some boxes on my list of chores.
In this PR I change `Cache#getAll()` from returning a `Collection` to return a `Stream`. 
Ideally such a method would not at all exist for a cache but now that we have it best we can do is not expose too much internals of the cache implementation. A `Collection` has still lots of methods to support and either requires defensive and potentially expensive copying or implementing a view into the internal data structures of the cache. This is an unnecessary burden on the cache requirements. `Stream` fits both with the existing use cases of the method and with a more healthy pattern of giving access to all values.
In this PR I really just changed the API and "repaired" the existing usage.
This now opens up the possibilities for the redis cache …
> chore: Cache#getAll as Stream

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistAccessControl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistAccessControl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/JsonBuilder.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistDescribeControllerTest.java
This PR adds a new URL parameter `describe` to Gist API.
When set `true` the gist query is not performed but instead described a bit like a SQL describe would do.
The main use case for the description is to allow insights into how the server understood the query and which HQL query it would run as a result of it. This information is otherwise only available by live debugging the server.
A description is an object with following members:
* `unplanned`: the query as received (mapped from URL => java objects)
* `planned`: the query as modified after `GistService#plan(unplanned)`. Main difference is that the planned query holds the list of actually included fields. Those are also summarised in additional listed in `planned.summary`.
* `hql`: the HQL query used to `fetch` the listed elements, …
> feat: Gist API describe parameter [DHIS2-11496]

- dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonResponse.java
- dhis-2/dhis-support/dhis-support-test-json/src/test/java/org/hisp/dhis/webapi/json/JsonResponseTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonError.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebClient.java
Some improvements I made while working on #8414 
* JSON `null` value can become any other type when resolved (should have been that way but check was too strict)
* include HTTP status in empty message responses
* allow to access raw HTTP response content as `String` in case it not `application/json` media type
* compose a synthetic `JsonError` response from Mvc response properties for responses that do not have a body (allows easier, more uniform testing)
Note that this PR does not change any production code.
> feat: Some improvments for REST API test utility

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupTaglessResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/DataElementGroupResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/ExpressionResolvers.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolverTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/CategoryOptionResolverTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/DataElementGroupResolverTest.java
All changes in CategoryOptionGroupResolver are based on coGroup tag (#{datalement:coGroup.categoryotiongroup}) and not backward compatible. Otherwise the old CategoryOptionGroupResolver has to be added into resolver collection.
> feat: CategoryOptionGroups + DataElementGroups in indicators [2.37-DHIS2-9747]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/AdxException.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
While writing testing instructions for the ADX fixes in [DHIS2-9313](https://jira.dhis2.org/browse/DHIS2-9313), I ran across three more bugs:
**1. HibernateDataValueStore** didn't support lastUpdatedDuration, so neither did ADX Export. Now it works.
**2. AdxException** had been creating an exception with a null `object`. Subsequently `DefaultAdxDataService` was catching this exception and trying to add it as a conflict to an `ImportSummary` with:
importSummary.addConflict( ex.getObject(), ex.getMessage() );
However `ImportSummary` was throwing an exception because the object was null. This means, for example, that the return WebAPI status for not being able to find an identifiable object was:
{"httpStatus":"Internal Server Error","httpStatusCode":500,"status":"ERROR"}
The fix is to not …
> fix: ADX Exeption and ImportOptions DHIS2-9313

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
From [DHIS2-11515](https://jira.dhis2.org/browse/DHIS2-11515):
> ### Symptom
> 
> The .periodOffset indicator expression function has been broken in trunk, 2.36, and 2.35 since June 8 commit [87968f2](https://github.com/dhis2/dhis2-core/pull/8142/commits/23811a37d08d1a1e685213a878e92aa46f7033e6).
> 
> Effectively the periodOffset is ignored. The same value is returned by analytics with or without the periodOffset function.
> 
> ### Cause
> 
> `(Double) periodOffsetRow.get( valueIndex )`
> 
> was replaced with:
> 
> `((Number) row.get( valueIndex )).doubleValue()`
> 
> It should have been replaced with:
> 
> `((Number) periodOffsetRow.get( valueIndex )).doubleValue()`
> fix: broken periodOffset function DHIS2-11515

- .github/workflows/analyse-pr.yml
- .github/workflows/run-api-tests.yml
- .github/workflows/run-tests.yml
This PR replaces custom third-party action with the newly supported GH key (concurrency). PR should not change any of the workflows - when a new commit is added, checks running for old commits are still canceled, freeing up GH workers.
> ci: use concurrency key in github actions

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datasetreport/DataSetReportService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datasetreport/DataSetReportStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datasetreport/impl/DefaultDataSetReportService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datasetreport/jdbc/AnalyticsDataSetReportStore.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataSetReportController.java
- dhis-2/dhis-web/dhis-web-approval/src/main/java/org/hisp/dhis/approval/dataset/action/GenerateDataSetReportAction.java
For the requirements, see [DHIS2-11502](https://jira.dhis2.org/browse/DHIS2-11502): 
> ...
> This feature will allow the /dataSetReport endpoint to specify multiple periods instead of just one, such as:
> 
> /dataSetReport?pe=202101,202102,202103&ou=...
> 
> The data returned in the data set report will be the sum of all data for the periods requested.
Most of the changes are trivial, just replace `Period` with `List<Period>` at several places in the code. The main pieces of (small) logic are:
1. The subtitle for a report section contained the formatted period. This was changed to a comma separated list of formatted periods (in date order). See `DefaultDataSetReportService.formatPeriods`.
2. In two places, data from multiple periods needs to be summed, but set to null if data from all …
> feat: Dataset reports multiple periods DHIS2-11502

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java
QA/Ops did observe a NPE when jon tried to run. From the stacktrace I deduced that the cause must be that an in-memory job was run using `exectute(String)` which tries to load the job configuration by ID from database which would result in a `null` reference for `execute(JobConfiguration)`. This fix check when scheduling the job if it is a in-memory one and if so it is scheduled using `execute(JobConfiguration)` directly. 
This is most likely a corner case that was overlooked in #8375.
> fix: do not attempt to load in-memory job configuration from DB [TECH-592]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
This was removed in an analytics ticket since it needed to be handled in a different way.
> fix: restored query filter for "in" operator [DHIS2-11549]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
The `AccountController` would use `ContextUtils#okResponse` and `ContextUtils#badRequestResponse` as a way to write to the HTTP response directly. This was replaced with returning a `ResponseEntiry` which sets same headers and same body when serialised to JSON by jackson.
Please note that the `ContextUtils` would set `ContentType` to `text/plain` even though the content was JSON.
I chose to change the behaviour and have spring+jackson use the actual content type `application/json`.
Other than that the responses stay the same. The cache "no cache" header is now set via `ResponseEntity`.
I added some tests for the changed controller methods.
Besides the replaced methods in `ContextUtils` there were further methods that apparently are no longer used. I removed these as well.
> chore: replace ContextUtils with return + jackson [TECH-656]

- dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/Expected.java
- dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonObject.java
- dhis-2/dhis-support/dhis-support-test-json/src/test/java/org/hisp/dhis/webapi/json/JsonExpectedTest.java
- dhis-2/dhis-support/dhis-support-test-json/src/test/java/org/hisp/dhis/webapi/json/JsonResponseTest.java
PR adds two new methods to the `JsonObject` API:
* `isA(Class)`
* `asObject(Class)`
These use a new annotation `@Expected` which can be added to the getters of a subclass of `JsonObject` to express that one does expect the property accessed in the getter to be present. To then check if a given `JsonObject` conforms to the expectations the `isA` method can be used. The `asObject` can be used to "cast" a `JsonObject` to a subclass while making sure all expected values are present. If expected values are missing or of the wrong type this will throw a `NoSuchElementException`.
Both methods do work recursive. This means one can check that a JSON tree conforms to the expectations with regards to existence and type in a single method call.
Added a unit tests that checks the feature in detail. …
> test: adds JSON assertion utility

- Jenkinsfile-core-dev
Add debug option `-X` to `mvn` command in attempt to find root cause of builds getting stuck (and aborted).
> chore: add debug option to mvn command [DEVOPS-81]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StoreConfig.java
These stores should not be in usage by exposed endpoints and common features.
We are skipping their usage to all common store operations.
> fix: Skip reportTable and chart stores [DHIS2-11575]

- .patches/security/advisories.json
This file will be the reference point for build-time patching.
This initial version contains the current security advisory in DRAFT (will not be patched).
Possible status:
- DRAFT (in progress; do not apply the patches yet) 
- FIXED (CVE is complete and patches should be applied to builds)
- MERGED (CVE has been merged; vulnerability is disclosed and patch is no longer necessary)
Status can be set on individual pullRequests in order override the parent CVE status.
Note: this DRAFT CVE also has a dummy CVE number, and the PR details should be checked when updating to FIXED.
> build: create advisories reference file for build-time patches

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserKeyJsonValueController.java
- dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserKeyJsonValueControllerTest.java
This method was a bit ambiguous as it had this sequence before setting both OK and Created.
```java
response.setStatus( HttpServletResponse.SC_OK );
messageService.sendJson( WebMessageUtils.created
```
I opted for `OK` as it is the more appropriate of the two but as `Created` did win this would mean a change of the API - therefore I make a PR that switched back to `Created`.
> fix: return Created for /userDataStore PUT [DHIS2-11587]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/servlet/DhisWebCommonsWebAppInitializer.java
Move JsonFilteringRequestFilter from DhisWebCommonsWebAppInitializer to DhisWebApiWebAppInitializer.
This filter should only be applied to /api requests and should therefore not be in the commons web app initializer where only the filters that applies to the Struts pages should be.
> chore: Move JsonFilteringRequestFilter to API web initializer

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotLikeOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/Operator.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/OperatorTest.java
https://jira.dhis2.org/browse/DHIS2-11383
- Issue: NotLike operator hasn't been convert to JPA query
- Fix: implement JPA Query generation for NotLike operator
- Added unit tests and integration tests
- Manual test: use this api query `api/programIndicators?filter=name:!like:generated&fields=:owner` , it should return 117 records as on play/2.35.
> fix: notLike filter is not working correctly

- .patches/security/advisories.json
set PRs for 2.35 baseline to FIXED to allow building into patch release 
candidate
> build: update advisories file

- dhis-2/dhis-web-api-test/pom.xml
Parent was not updated when moving to a new model in #8514
> fix: parent pom of dhis-web-api-test

- dhis-2/dhis-web-api-test/pom.xml
- dhis-2/pom-full.xml
- dhis-2/pom.xml
These changes now pass locally
mvn -X -T 4 clean install -f dhis-2/pom-full.xml -Pjdk8 --update-snapshots
Might still fail in CI due to `dhis-web-commons` being under `dhis2-web` but as a quick fix this might help.
> fix: web api tests pom config

- dhis-2/pom.xml
Rule engine logs are registered in INFO level, so to show them the level of the log configuration must be change from WARN to INFO
> fix: Link core to rule engine version with logs implemented [TECH-652]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
@jbee reported that
`assertEquals( "3.5608767950073115", eval( "log(50,3)" ) );`
was failing because with the JDK he was using `log(50,3)` evaluated to `3.560876795007312`.
I've changed the logarithmic tests that might produce different values under different JDKs, so that they now compare `Double` values with a `DELTA`. The `DELTA` rounds to only two decimal places, but that should be OK for the purposes of these tests.
> refactor: ExpressionServiceTest rounding

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateStore.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicatesTests.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceIntegrationTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerMvcTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerTest.java
In potential duplicate, we don't need to filter by tei as a filter by a list of teis already exists, so can filter by a list of a single tei
> fix: [ DHIS2-11338 ] Potential duplicate remove /tei endpoint

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/jdbc/JdbcProgramOrgUnitAssociationsStore.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
Add a cache to store program org unit associations fetched via jdbc. 
At the moment this method is only used when **adding an enrollment**, to check whether the program to which enrollment is created has the enrollment org unit assigned to it.
> fix: [DHIS2-11567] add caching layer when fetching program org unit associations (2.35.7)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sharing/CascadeSharingReport.java
A feedback from front-end to change variable name from `countUpdatedDashBoardItems ` to `countUpdatedDashboardItems`
> fix: update CascadeSharingReport variable name

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserAccountExpiryInfo.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/CodeGeneratorTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/AccountExpiryAlertJob.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/job/AccountExpiryAlertJobTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
Adds a system job that sends an account expiry alert to those users that
* have an email address 
* have an expiry date set that is within the next N days
* are not disabled
The number of days can be configured through a new system setting `ACCOUNT_EXPIRES_IN_DAYS`. 
The job needs to be enabled through another new system setting `ACCOUNT_EXPIRY_ALERT`.
The database query to find affected users is tested with service level tests.
The job is tested with mock tests.
* set an expiry date within next 7 days for your test user which should have an email you receive
* enable the system job `ACCOUNT_EXPIRY_ALERT` (key `accountExpiryAlert`) to `true`
* make sure email gateway is configured
* wait 24h so the job can run over night
* check that the you got mail
For completeness one would naturally …
> feat: system job to send account expiry alert emails [DHIS2-11589]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/DisableInactiveUsersJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/DisableInactiveUsersJob.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
PR adds a job parameter to the _disable inactive users_ job. The parameter allows to specify the number of days before disabling a user a reminder email should be send to remind or make the user aware that disabling would happen unless he logs into the account.
The new parameter is optional. If it is not set no reminder emails are send.
The number of days should be between 1 and 24 days. I just chose this because minimum for inactive in month is 1. So a maximum of 4 weeks in advance seems reasonable. 1 days minimum is almost unreasonable but if someone wants it to be that close it is technically possible. 
In some sense this is an extension to #7307
The target emails to remind are selected in a single dedicated query. Users that do not have an email configured cannot get notified before …
> feat: adds automatic user account disable reminder email [DHIS2-11589]

- dhis-2/dhis-web/dhis-web-apps/README.md
The feature toggling apps index is [currently not being rendered as a table](https://github.com/dhis2/dhis2-core/blob/921becda76d4dba7b46003e227606c4b9434fbdc/dhis-2/dhis-web/dhis-web-apps/README.md) due to a missing column.
> docs(apps): fix feature toggling apps index table

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationMergeParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/DeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerMvcTest.java
- Rename DeduplicationMergeRequest to DeduplicationMergeParams (similar to other code)
- Changed from using UID of PotentialDuplicate to PotentialDuplicate in DeduplicationMergeParams (Also update method)
- Added manualMerge method
- Added dummy for hasInvalidReferences
- Minor codestyle issues with brackets fixed
- Call store directly to update PotentialDuplicate to avoid double Transaction.
- Rewrote some error messages
- Add try-catch to controller to present exceptions as 409-conflict and not 500 errors.
- Moved hasInvalidReference to Helper class and changed parameter
> DHIS2-11396 - Deduplication: Manual Merging

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/TranslatableObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/Expression.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/expression/hibernate/Expression.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/predictor/hibernate/Predictor.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/translation/TranslationServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_29__Add_translations_column_expression_table.sql
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_30__Add_translations_column_predictor_table.sql
https://jira.dhis2.org/browse/DHIS2-11574
- This PR added `translations` column to `Predictor` and `Expression` tables
- After the change, the translation dialog in Maintenance app works correctly with Predictor.
- Predictor has `Expression` fields: `generator` and `sampleSkipTest`, which are `EmbeddedObject`. Therefore, front-end code needs to be updated to in order to add a custom translation dialog for those fields.
- This PR also added a new `TranslatableObject` which contains common methods for enabling translations. This is useful if we want to enable translation for other `EmbeddedObject` in the future.
- Updating translation for `Predictor` can be done nornamlly using `api/predictors/{uid}/translations` . But for embedded object, its translations need to be included in the …
> feat: add translations to Predictor

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/MergeObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/deduplication/PotentialDuplicateStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationHelperTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/hibernate/PotentialDuplicateRemoveTrackedEntityTest.java
> feat: Implement basic logic to merge enrollments [DHIS2-11626]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/function/FunctionOrgUnitAncestor.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/function/FunctionOrgUnitGroup.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/ValidationRunContext.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/DataValidationTaskTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
- dhis-2/pom.xml
See [DHIS2-11637](https://jira.dhis2.org/browse/DHIS2-11637). This adds two new functions for predictor and validation rule expressions: orgUnit.group() and orgUnit.ancestor().
These functions allow predictors and/or validation rules to behave differently (or not at all) for organisation units depending on organisation unit subtree and organisation unit group membership.
> feat: OrgUnit.group, ancestor functs DHIS2-11637

- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/deduplication/DeduplicationControllerMvcTest.java
Comparison on creation date has been removed, so mock is no longer used
> fix: [ Deduplication ] remove mock on creation date in mvc tests

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DeduplicationHelper.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/DefaultDeduplicationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceMergeIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/deduplication/DeduplicationServiceTest.java
Not sure this is fixing the missing update on tei lastUpdated and lastUpdatedBy, but it was used the tei update service causing double transaction. 
Replaced with store. Tests seem to prove it
> fix : [ DHIS2-11563 ] missing update on lastUpdated and lastUpdatedBy

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
This is a bug introduced in 2.37.
It blocks the inclusion of dashboard items of type APP.
**This fix has to be approved by the change control team. It can be merged only after approval.**
> fix: Logic for dashboard of type APP [DHIS2-11739]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOptionGroupSet.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/indicator/IndicatorGroupSet.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/category/hibernate/CategoryOptionGroupSet.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/indicator/hibernate/IndicatorGroupSet.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v38/V2_38_2__Add_unique_shortName_to_group_sets.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_1__Add_column_shortName_to_group_sets.sql
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_3__Add_unique_and_not_null_to_group_sets_shortName.sql
Adds `shortname` column to `IndicatorGroupSet` and `CategoryOptionGroupSet` which are unique and with a max length of 50 characters.
Constructors with arguments were only used in tests. Therefore `shortName` is set to `name`.
Start server and check table `indicatorgroupset` and `categoryoptiongroupset` have a `shortname` column with unique constraint. 
Stop and start server again and check no migration issues occur during startup.
> feat: unique shortname for indicatorgroupset and categoryoptiongroupset [DHIS2-7317]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
This issue was supposed to fix a bug reported by the front-end during the chart/report table drop task.
The problem was that the snapshot endpoint, when consumed, was not updating the DB correctly. The events from "today" were missing. So I added a "fix" so it would consider the events from "today".
But later I found out that it was a mistake. All data statistics snapshot logic, actually, is based on D-1 events. So the behaviour was expected and events from "today" are not taken into consideration. It should remain like that based on the existing logic.
This fix is just a rollback, so this endpoint will behave as before.
**This fix has to be approved by the change control team. It can be merged only after approval.**
> fix: Invalid data statistics snapshot date [DHIS2-11047]

- .github/workflows/run-api-tests.yml
If there are failures, action uploads logs from web container as an artifact. I renamed logs to tomcat_logs to make it more clear what the file contains.
> ci: make the name of the log artifact more explicit

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramObjectBundleHookTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/program_programStage_with_sharing.json
https://jira.dhis2.org/browse/DHIS2-11742
- POST request to `api/metadata`  with payload contains `Program`, `ProgramStage` with sharings.
- New `Program` is created correctly with sharings.
- New `ProgramStage` is created but **without sharings**.
- In `ProgramObjectBundleHook` the method `updateProgramStage()` removes  sharing data from `ProgramStage` by calling `programStageService.saveProgramStage( ps );`
- Remove redundant  call to `saveProgramStage` and also `updateProgram` in method `updateProgramStage()`. 
- The updated objects will be flushed when `session.flush()` is called by importService.
- Added integration test.
- Manual test can be done by POST request to `api/metadata` with payload contains `Program`, `ProgramStage` with sharings.
> fix: sharing is not saved when create new ProgramStage [DHIS2-11742]

- Jenkinsfile-core-dev
Removing the CVE "Patch" stage from the dev pipeline, as it's not needed for "dev" builds.
> build: Remove CVE patch stage from dev pipeline [DEVOPS-83]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidator.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidatorTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJ.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJDeleteNewValue.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJDeleteNoValue.json
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/datavalueset/dataValueSetJDeleteZeroValue.json
cherry picked #8610
Takes care of three cases:
* delete by updating to zero should work
* delete by using strategy DELETE with no value or the old value should work
* delete by using strategy DELETE with new value different to the old one should work (did work before but now is tested as well)
> fix: data value import - delete with zero or no value [DHIS2-11624] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApproval.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DefaultDataApprovalService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/dataapproval/hibernate/DataApproval.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_4__add_columns_for_last_updated_to_data_approval.sql
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
Adds last updated date and user to `DataApproval`.
These will not be updated on any update of the object but each time the accepted state is updated. 
Added a simple tests that checks the update works with two different users approving.
> feat: adds last updated user and timestamp to data approval [DHIS2-5075]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_5__Add_indexes_to_tei_and_psi_table_to_improve_tei_querying.sql
2 indexes have been added.
One index on **trackedentityinstance** table and another one on **programstageinstance** table. These significanly improve tei fetching through the APIs when either sort order is created date or when there are event filter assignments involved.
> feat: Add index on tei and psi table to improve tei querying performance [DHIS2-11767](2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
This should go into 2.37.
Adding @Philip-Larsen-Donnelly for approval.
> fix: fixed lower case for "IN" operator in queryFilters [DHIS2-11770]

- .github/workflows/check-formatting.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/run-tests.yml
Uses `--no-transfer-progress` (requires maven >= 3.6.1) to suppress logging of downloads like this
```
Downloading: some.jar
4/2122 KB   
8/2122 KB   
12/2122 KB   
...
```
Had a look at the raw logs and can't find any of the above so I assume this did work.
> fix: do not show file transfer progress in CI builds

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserLookupControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserLookupController.java
PR makes sure a user with the same role as other users can see those users when doing a search in the `/userLookup?query` API.
The query already had an override flag to bypass the _same role_ check.
I added a controller test that setups a test scenario where all users including the user doing the lookup have a common role.
Then the user does a search for one of the users and finds the user. 
When the added `.setCanSeeOwnUserAuthorityGroups( true )` is removed (or set to `false`) this tests fails as no user is found.
Pretty much what the tests do. 
1. Create a role and add both the user doing the lookup as well as the user that should be found to it. 
2. switch to the lookup user
3. do the lookup `/userLookup?query=<name>` and check the other user with the same role is found (as well as …
> fix: userLookup API should return all users [DHIS2-11317]

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/eventreport_with_program_indicator.json
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/EventReportSchemaDescriptor.java
https://jira.dhis2.org/browse/DHIS2-11568
Issue: 
- `ProgramIndicator` is not saved when imported together with `EventReport`
- `ProgramIndicatorSchemaDescriptor` has order=1560  which is higher than `EventReportSchemaDescriptor` therefore by the time eventReport is saved, ProgramIndicator is not available for referencing. 
Fix: 
- Increase `EventReportSchemaDescriptor` order so that it will be saved after ProgramIndicator.
> fix: missing programIndicator after imported EventReport

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/ProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/DefaultProgramRuleService.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/hibernate/HibernateProgramRuleStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AttributeValidationHook.java
Attributes or a data elements linked to program rules must be loaded in the preheat because they could be assigned to a tracker entity in the payload and at the moment of validation they need to be found in the preheat.
All the attributes and data elements linked to program rules are loaded even though they could not be used. Filter more in depth in the collector phase in NTI would me to expensive, so it is better to load some more data and be sure they are in the context
> fix: Load in preheat all attributes and dataElements linked to program rules [DHIS2-11762]

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
Use release v101.0.5 to include fix for report table endpoint being
removed in 2.37.0.
Jira-key: DHIS2-11751
Jira-url: https://jira.dhis2.org/browse/DHIS2-11751
> chore(apps): bump usage-analytics release

- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/config/JdbcConfig.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/batchhandler/MockBatchHandler.java
- dhis-2/pom.xml
This PR uses the latest quick library version which accepts a connection pool backed Datasource instead of creating its own connections.
The same datasource is passed onto the quick library.
> feat: Provide datasource to quick library to avoid adhoc connection creations [DHIS2-11752] (2.37)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
This change will remove the caching for pagination. This aims to fix synchronization issues when entities are added or deleted. As the pagination is cached it does not reflect the new entity inserted or removed.
This is already in 2.37. It's just a "forward" port.
> fix: Remove pagination cache in Abstract controllers [DHIS2-11504]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
This fix reverts the latest changes we applied, with the intent of improving the org. units logic for performance gains.
Unfortunately, it changed the output expected by the underline flow.
To play on the safe side and avoid a new problem, I'm reverting the logic from the 2.36 release.
We can play around it in 2.38 if needed.
Technical notes
This query used to work in 2.36, but fails in 2.37. That's how QA found it.
api/37/analytics/events/query/VBqh0ynB2wv.json?dimension=ou:at6UHUQatSo&stage=pTo4uMt3xur&coordinatesOnly=true&startDate=2020-01-01T01:00:00.000&endDate=2021-10-01T02:00:00.000&pageSize=100000
After firing that query, at some point the org. units SQL condition differs between 2.36 and 2.37:
2.36)
where ax."executiondate" >= '2020-01-01' and ax."executiondate" <= '2021-10-01' …
> fix: Reverting org. units logic in events [DHIS2-11800]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
ouMode was made a required parameter, so this adds ouMode=ACCESSIBLE to the requests. There's a bug in /events - NPE is thrown when program query param is not provided. Two commented-out test cases will be uncommented when that bug is fixed.
> test: fix event export tests

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
> fix: Revert query to check lastupdated in events/enrollments [ DHIS2-11761 ] [ 2.37 ] 

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
> fix: Revert query to check lastupdated in events/enrollments [ DHIS2-11761 ] [ 2.36 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
> fix: Revert query to check lastupdated in events/enrollments [ DHIS2-11761 ] [ 2.35 ]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
> fix: Revert query to check lastupdated in events/enrollments [ DHIS2-11761 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/Attribute.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/attribute/AttributeStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/attribute/hibernate/Attribute.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/mapping/hibernate/Map.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/HibernatePropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/JacksonPropertyIntrospector.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_6__Add_attributes_for_analytical_objects.sql
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonAttributeValue.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AttributeControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SchemaBasedControllerTest.java
Adds 4 further object types that can have attributes:
- Visualization
- Map
- EventReport
- EventChart
The added columns in `Attribute` table are initialised with `not null default false`.
Instead of using numerous `boolean` fields, one for each table, to indicate whether or not an object type can have a certain attribute a new `enum` `ObjectType` is introduced. The set of object types is then stored as a single `EnumSet` within the `Attribute`. All getter/setters read/write the set instead of individual fields.
There is a convention that the enum constant name can be converted from its upper case to lower camel case and append `"Attribute"` to get the property name of the getter/setter responsible for the object type (and the name used in JSON etcetera).
This would fail the audit …
> feat: Metadata attributes for analytical objects [DHIS2-3789]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
Class name for Relationship in audit logs when merging potential duplicates is now correct
> fix: class name for Relationship in audit logs (2.37) [DHIS2-11802]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
Class name for Relationship in audit logs when merging potential duplicates is now correct
> fix: class name for Relationship in audit logs (2.37.0) [DHIS2-11802]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/deduplication/hibernate/HibernatePotentialDuplicateStore.java
Class name for Relationship in audit logs when merging potential duplicate is now correct
> fix: Class name for Relationship in audit logs when merging potential duplicate [DHIS2-11802]

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/SqlViewUtils.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewUtilsTest.java
SonarCloud reported a blocker vulnerability in `SqlViewUtils.substituteSqlVariable`: "Change this code to not construct the regular expression from user-controlled data." The danger is that "a small carefully-crafted input ... can trigger catastrophic backtracking" as part of a DOS attack.
The change is to use `String.replace()` instead of `replaceAll()`. The only difference between these methods is that replaceAll takes a regular expression as the first argument whereas replace just takes a String. Both methods replace all instances. In this case, a regular expression argument was not needed.
`SqlViewUtils.removeQuerySeparator` was also changed to use replace instead of replaceAll, since the first argument was not a regular expression.
> refactor: replaceAll -> replace in SqlUtils

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Instead of 0.0 (null in database, data type double precision) the NaN is displayed.
The idea is wrapping the numbers (double precision) into coalesce method. If the number is not set (null), 'NaN' (valid expression for numbers) will be used:
- For event table style:
SELECT count(ax."psi") AS value,
ax."uidlevel1",
**coalesce(ax."a3kGcGDCuk6", 'NaN') AS a3kGcGDCuk6**
FROM analytics_event_iphinat79uw AS ax
WHERE ax."executiondate" >= '2021-01-09'
AND ax."executiondate" <= '2021-01-10'
AND (ax."uidlevel1" = 'ImspTQPwCqd')
AND ax."ps" = 'A03MvHHogjR'
AND ax."yearly" in ('2021')
GROUP BY ax."uidlevel1",
ax."a3kGcGDCuk6"
LIMIT 200001
- For linelist table style:
SELECT psi,
ps,
executiondate,
storedby,
lastupdated,
enrollmentdate,
incidentdate,
tei,
pi,
ST_AsGeoJSON(psigeometry, 6) AS geometry, …
> feat: DE type Number displaying zero instead of null value [2.38-DHIS2-9477]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/EventImportTest.java
> fix: Revert query and fix teis lastupdated update when updating events [ DHIS2-11761 ] [ patch/2.35.8 ] 

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
This is a tricky one.
Removing attribute value was failing (only when importer was used in async mode) because a different attribute object with the same id was assigned to the attribute value throwing a NonUniqueObjectException
> fix: Fix the way attribute value are updated by hibernate session [DHIS2-11852]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/DefaultUserDetailsService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/spring2fa/TwoFactorAuthenticationProvider.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/AuthenticationListener.java
Remove redundant logging of authentication events.
Lower log levels from info to debug in all other authentication logging classes than AuthenticationLoggerListener.
Let AuthenticationLoggerListener the main authentication logging class.
> chore: Lower logger levels on authentication messages

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityProgramOwnerStore.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/UserActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/metadata/ProgramActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/tracker/EventActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/file/CsvFileReader.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/file/FileReader.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/file/JsonFileReader.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/file/XmlFileReader.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/programs/ProgramStagesTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/TrackerNtiApiTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/ImportStrategyTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/enrollments/EnrollmentsOwnershipTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/tei/TeiValidationTests.java
- dhis-2/dhis-e2e-test/src/test/resources/tracker/importer/teis/teiWithEnrollmentAndEventsNested.json
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerOwnershipManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityProgramOwnerStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramOwnerSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/OwnershipTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/ownership_enrollment.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/ownership_event.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/ownership_metadata.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/ownership_tei.json
When using Redis, during NTI imports, the OrganisationUnit that is cached in redis is a Hibernate proxy. When eventually fetching it back for validation, it causes a lazy init exception when trying to access its fields (getParent() for example).
Although Redis ser-deser needs a thorough check, that is a bigger task. For now, I have recursively initialized the OrganisationUnit before placing it into the cache. The changes are
Recursively initialize owner OrganisationUnit before placing into ownership cache.
Add "accessLevel" mapping for ProgramMapper as this was missing.
Fetching tracked entity program owners for all the tracked entity instance ids, irrespective of programids.
E2E tests have been updated to correct the test setup and expectations.
Even though 23 Files changed in this PR, …
> fix: Lazy init exception when ownership ou already happens to be in cache

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
Since we have removed the old Squiggly library for field filtering (and now relying on node services), some fields are not included when you field filter on `*`, this PR changes that to explicitely using `*,dataValues` if no field filter is present.
> fix: change default fields on EventController

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventChartController.java
The org. unit levels were not being considered as part of the cache key.
This was causing one issue: returning invalid results when similar requests with different org. unit levels set.
In other short words, different analytics requests were giving the same results. This PR aims to fix it.
More details in the ticket https://jira.dhis2.org/browse/DHIS2-11820
**_Needs to be approved by the Change Control Comittee_**
> fix: Caching inconsistency in analytics [DHIS2-11820]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
Added potentialduplicate column into the result of **api/trackedEntityInstances/query** API. 
Added tests to verify the column is returned when accessing **HibernateTrackedEntityInstanceStore.getGrid()**
> fix: Add potentialDuplicate parameter in tei/query endpoint (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/NotOwnerReferencesCheck.java
Updating OUs with JSON patch would fail since the `ancestors` property wrongly would be checked by the references check.
This check should have ignore the property as it is not `writable`. This PR add the condition to the filter of checked properties so only `writable` properties are checked.
> fix: ignore non-writable properties when checking owner references

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackedEntityInstanceService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
Added potentialduplicate column into the result of api/trackedEntityInstances/query API.
Added tests to verify the column is returned when accessing HibernateTrackedEntityInstanceStore.getGrid()
(cherry picked from commit bf3551090352aa2aba8dd4b5c714f9b2f1e6d03b)
> fix: Add potentialDuplicate parameter in tei/query endpoint (2.37.0) 

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/log/Log4JLogConfigInitializer.java
* Turns off `additive` logging for audits, only log to `dhis-audit.log`
* Turn off `audit.database` by default
> fix: don't log audits to stdout, only file by default

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/TimeField.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/EnrollmentTimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/EventTimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/TimeFieldSqlRenderer.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/StatementBuilder.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/statementbuilder/AbstractStatementBuilder.java
Refactored the time condition rendering a bit to accommodate enrollments.
> feat: storedby and last updated in enrollment analytics [DHIS2-11775]

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/DhisWebCommonsWebSecurityConfig.java
⋅ Change i18nJavaScript.action to use the dynamic permitAll antMatcher instead of ignoring(). Ignoring() is for static resources and not Struts actions.
> fix: Change i18nJavaScript.action to dynamic permitAll ant matcher

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/JpaQueryUtilsTest.java
See [DHIS2-11921](https://jira.dhis2.org/browse/DHIS2-11921). DataValueSet values are not returned if data has an AttributeOptionCombo with a CategoryOption that is shared by a UserGroup.
`JpaQueryUtils` generates a `jsonb_check_user_groups_access` function reference with args:
1-sharing column
2-list of userGroupIds
3-access pattern
However, the `jsonb_check_user_groups_access` function expects args:
1-sharing column
2-access pattern
3-list of userGroupIds
The fix is to change the order of args 2 and 3 in `JpaQueryUtils` to match the order expected by `jsonb_check_user_groups_access`.
> fix: JpaQueryUtils groups_access args DHIS2-11921

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/JpaQueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/JpaQueryUtilsTest.java
* fix: JpaQueryUtils groups_access args DHIS2-11921
* fix: import order
(cherry picked from commit 26676e0a3f3b0e7383aca8851f86e5d28ff2bfb8)
> fix: JpaQueryUtils groups_access args DHIS2-11921 (#8902)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/SchemaIdResponseMapper.java
The logic to org unit output schema was being only applied when we had element operands in the params. This is being fixed as the org unit schema does not depend on operands.
> fix: Moving out org unit logic [DHIS2-11769]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/DisableInactiveUsersJob.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/mock/MockUserService.java
As discussed the issue with the current implementation of the reminder email was, that it would send an email to the user daily in case the user would not log in. This is now changed. We only select users with a last login being on a single specific day dependent on the job configuration. Those users get an email. Then the number is divided by two and users being that number of days away from being disabled also get an email. This continues until (and including) 1 days to being disabled. 
As now only users being a single particular number of days away from being disabled are selected a reminded the number of days stated in the email is correct when it states the same number for all of them.
Existing unit tests were adopted and extended.
> fix: only remind users about account disable on specific days [DHIS2-11589]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DefaultDataApprovalService.java
See my comment in [DHIS2-11857](https://jira.dhis2.org/browse/DHIS2-11857). The only code change is to replace `periodService.reloadPeriod( period )` with `period`.
The other changes are just whitespace to make the code more readable while keeping within the line length limit.
> fix: Sporadic data approvals error DHIS2-11857

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/InMemoryQueryEngine.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotTokenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/Operator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/TokenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/TokenUtils.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/TokenOperatorTest.java
In  #8830 @vietnguyen pointed out that the in memory token operators were using the same regex pattern that would only allow ASCII letters for token based search restrictions.
Looking into the issue I found that there were more problems with the implementation which was confirmed by added tests.
I fixed the implementation and cleaned up some bits around it
The added unit tests now cover all combinations of left and right operand, case sensitivity and match mode.
> fix: allow non ASCII letters in token in memory restriction [DHIS2-10323]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHookTest.java
Rules are the following:
- A TEI can only have one active enrollment per Program
- If the program has onlyEnrollOnce flag to false, a TEI can be enrolled multiple times as long as just one is active
- If the program has onlyEnrollOnce flag to true, a TEI can be enrolled only once
> fix: Fix active and enrollOnce logic in enrollment validation [DHIS2-11659]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOptionCombo.java
Fix copy/paste typo in JavaDoc for `CategoryOptionCombo.getEarliestEndDate()`. Was copied from `getLatestStartDate()` but not changed.
> refactor: JavaDoc typo in CategoryOptionCombo

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/gist/GistQueryTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
Adds filter grouping to Gist API.
Before this feature was added all filters where either combined with `and` (`rootJunction=AND`; default) or with `or` (`rootJunction=OR`). To allow to only combine certain selected filters with `or` while filters in general continue to be combined with `and` the more general feature of filter groups was added.
Filter groups allow to assign each filter to a group. The group is represented by a number 0-9 which can optionally be added before the property name of the filter. Valid filter patterns now are:
<propert>:<op> 
<propert>:<op>:<value>
<group>:<propert>:<op>
<group>:<propert>:<op>:<value>
Where `:` could also be `::`, `~` or `@`.
When the `<group>` is omitted this implicitly assigns the filter to group `0`.
As the additional `<group>` is …
> feat: adds filter groups to Gist API [DHIS2-12030]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/annotation/Gist.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistValidator.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
Reason for this new feature is the lack of non-persistent fields in the Gist API. 
This is especially problematic with popular fields such as the `User.getName()` which is build from the persistent fields `firstName` and `surname`. Until now such fields simply could not be extracted using the Gist API as we directly extract properties from the database as individual values. This has led to workarounds being uses such as composing the user name on client side from first name and surname. However, this de-facto duplicates the composition logic for the user name making it a somewhat unsatisfactory solution.
Thinking about a better solution to this particular problem gave me an idea for a more general feature for the Gist API that might be useful in more situation as just the user name.
The …
> feat: Gist API extract bean properties from persistent fields [DHIS2-12038]

- jenkinsfiles/dev
Related to #9149
Temporarily enable Maven artifacts archiving for dev pipeline, to allow for comparison between Jenkins and GitHub Actions surefire XML reports.
> build: Enable dev pipeline maven artifact archiving

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoader.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/AttributeOptionComboLoaderTest.java
See [DHIS2-12061](https://jira.dhis2.org/browse/DHIS2-12061).
Importing an event should fail if the event date is not within the bounds (if any) of a CategoryOption that is part of the Attribute Option Combo for the event. The check that should do this is [here in AttributeOptionComboDateCheck](https://github.com/dhis2/dhis2-core/blob/ea76fa86409613c9766d4508d65c88ac55c413c3/dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/validation/AttributeOptionComboDateCheck.java#L77).
However, the check was always failing because the start and end dates were not fetched by SQL for category options associated with an Attribute Option Combo for event import. This fix fetches these fields, so the check is successful as intended.
This fix passes the test …
> fix: Event import catOption start/end DHIS2-12061

- jenkinsfiles/dev
Related to #9149 
The previous PR (#9161) was incorrect and the Surefire XML reports weren't archived.
This PR enables archiving only for Surefire XML reports, instead of all maven artifacts. ✅
> build: Enable surefire XML reports archiving on Jenkins

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
On play/dev, predictor runs are now reliably failing for the (only) defined predictor Malaria Outbreak Threshold. The error message is:
_getDataValues ready for /ImspTQPwCqd/O6uvpzGd5pu/YuQRtpLP10I/DiszpKrYNg8 but called with {..."Karina MCHP"...}_
This error is from an unexpected internal condition here: https://github.com/dhis2/dhis2-core/blob/d01e204421b447a35f62868af417e32a1f1b1f13/dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java#L251-L252 What's going on is this: `DefaultPredictionService` fetches a list of orgUnits to predict for and sorts them in path order. It initializes `PredictionDataValueFetcher` to fetch any aggregate data values needed for predictions from the same list of orgUnits, to be fetched in orgUnit …
> refactor: New predictor orgUnit ArrayList

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventsTests.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportControllerTest.java
Change the default value for import csv events to be `skipFirst=true` to be compatible with the default value in the export endpoint
> fix: Change default value for import csv events with header [DHIS2-10837]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/RequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToParamsMapperTest.java
If eventUids are not specified in the params but filters are. Backend only does a null check on the events list and not an "empty" check. This PR fixes the validation error thrown incorrectly by checking for both null and empty check.
> fix: EventUids validation fails for empty non null list (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sqlview/SqlView.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/DefaultSqlViewService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sqlview/SqlViewUtils.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
Makes the requirements for SQL variable names consistently require the names to only contain `a-z`, `A-Z`, `0-9` and `-` and `_` symbols. 
The validation and handling so far was inconsistent. While the variable names for the actual values provided were restricted to plain alphanumeric names the placeholders in the SQL would be restricted to any letter/digit character when extracted but not further checked. This means overall the name restrictions were slightly relaxed.
As placeholder and replacement should have a common rule I adjusted the `SqlView#isValidQueryParam` to be used by both and to allow the set of ASCII letters and digits as well as dash and underscore symbols.
The `SqlViewUtils#getVariables` in contrast does not make any limitations on the name (except it cannot contain `}`) …
> fix: consistently require alphanumeric + dash + underscore SQL view var names [DHIS2-11946]

- .github/dependabot.yml
dependabot cannot find a pom.xml in the root of our repository
> chore: fix dependabot maven directory

- .github/workflows/run-tests.yml
we are using it on https://github.com/dhis2/dhis2-core/blob/e4f16962bfcca2ec564c08787faa382c2d58d577/jenkinsfiles/dev\#L31
Jenkins where all tests (unit + integration) finish in ~10min
the specs of the machines are different
GitHub action runners
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners\#supported-runners-and-hardware-resources
for Linux have
2-core CPU, 7 GB of RAM memory, 14 GB of SSD disk space
as opposed to the EC2 instances - m6i.xlarge type - 4 vCPUs, 16GB RAM we run Jenkins on
Check the build logs to see a line like
`[INFO] Using the MultiThreadedBuilder implementation with a thread count of 2`
which tells us the actual number of threads used by maven
> chore: use maven parallel builds for integration tests TECH-784

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistDescribeControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
Upon @mediremi request I added support for case-insensitive like filters to the Gist API.
As we use HQL there is no equivalent building block to hibernate's `Restrictions.ilike` for the criteria API so we do a `lower(field) like $parameter` where the value of `$parameter` is also lower cased before passing it to query.
Adopted existing tests a bit so they use wrong case where case-insensitivity is expected to work and added some more test scenarios especially for the `ilke` and `!ilike` filters.
PR https://github.com/dhis2/dhis2-docs/pull/887
> feat: Gist API support case-insensitive like filters [DHIS2-12073]

- .github/workflows/run-tests.yml
dhis-service-analytics tests take ~50% of the time it takes to run integration tests (time reported by Surefire).
This can vary between runs. ~50% was computed from https://github.com/dhis2/dhis2-core/pull/9162
We should be able to cut down the integration test step by running
analytics integration tests in parallel. Lets find out by how much
> chore: run analytics integration tests in parallel TECH-784

- .github/workflows/run-tests.yml
- dhis-2/dhis-services/dhis-service-analytics/pom.xml
excluding the entire project from the maven build will cause a
dependency of the report service to be missing. So we have to build it
but exclude its tests from executing
> chore: build but exclude analytics tests from integration-test TECH-784

- .github/dependabot.yml
The PR title is equal to the commit title. Prefix commit messages with
chore. Lets see if the scope added by dependabot is considered valid
without having to configure
https://github.com/zeke/semantic-pull-requests
> chore: dependabot fails semantic PR check

- dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2.xml
- dhis-2/dhis-support/dhis-support-test/src/main/resources/simplelogger.properties
all modules running integraiton tests emit following warnings
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ivo/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ivo/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.14.1/log4j-slf4j-impl-2.14.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
This shows that we are actually using slf4j simplelogger in these
modules instead of log4j2. This means our log4j2 configuration has no
effect, not in tests, not in production.
We should quiet down the …
> chore: quiet down integration test logs TECH-784

- .github/workflows/analyse-pr.yml
- .github/workflows/check-formatting.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/run-api-tests.yml
- .github/workflows/run-tests.yml
Maven can be configured via env vars https://maven.apache.org/configure.html
We are already using env vars, but by renaming then we do not have to
pass them on the CLI. Moving them to the workflow level, means we will
not forget to add them on any future step using maven.
Also quiet down maven logs when it comes to progress on downloading
dependencies. This only clutters the logs.
> chore: use MAVEN_OPTS and MAVEN_CLI_OPTS

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SharingController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/SharingControllerTest.java
https://jira.dhis2.org/browse/DHIS2-12008
- SuperUser can't get or update a private dashboard in `SharingController`
- The cause is we try to get the object by calling  the method `getByUid`, which enforce sharing check for dashboard  in `HibernateIdentifiableObjectStore#forceAcl()` 
- Get the object by calling `getNoAcl()` then do the sharing check using aclService
> fix: superUser can't update sharing of private object

- dhis-2/dhis-api/pom.xml
- dhis-2/pom.xml
There are a few direct dependencies in dhis-api (most likely also in other modules) that are no explicitly declared. The build works since some direct dependencies depend on dependencies we actually need as well (transitive). It's best to be explicit about the dependencies. This ensures we are in charge of their versions and certain they will be there. Transitive dependencies can change (their versions and their existence).
You can run `mvn dependency:analyze` to see what we depend on and do not declare. Also what declare but do not depend on.
Note that after this change it will look like
```
⏵ dhis2-core git:(api-used-undeclared-dependencies) cd dhis-2/dhis-api
⏵ dhis-api git:(api-used-undeclared-dependencies) mvn dependency:analyze
[INFO] Scanning for projects...
[INFO] ...
[WARNING] …
```
> fix: explicitly declare direct dependencies in dhis-api

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sqlview/SqlView.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
Just relaxed the restrictions on the SQL view variable value pattern so that it allows for all non ASCII letter symbols.
Kept the `\\w` as the `\\p{L}` does not include digits.
Added a test scenario to confirm. 
Kept this change small as #9186 was touching same files.
> fix: allow non ASCII letters for SQL view var values [DHIS2-11932]

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
see https://github.com/dhis2/dhis2-core/pull/9179
Problem description:
Any "null" string in the systemsettings table (column value) can raise the application exception instead of set the setting value for later usage. This behavior is derived from the way, how json deserializer uses the "null" string. It is deserialized to non referenced object (null).
Workflow description:
Application tries to obtain the setting value from:
1. Cache
2. if not present, from database
3. if not present, default value will be applied
the value presence is determined by null reference to the value object
Solution description:
- modify the DefaultSystemSettingManager - value will be checked after the json deserialization instead of before this action. The deserialization is done by calling the …
> fix: Newly created Continuous Analytics Job fails [2.38-DHIS2-12094]

- .github/dependabot.yml
There is a limit of 20 concurrent jobs (I think for the entire
organization) that we can run
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration\#usage-limits
* so limit number of total open PRs
* run dependabot updates at times where most are probably not working, so
it does not take up the quota. dependabot would otherwise randomly
choose a time which can fall into our working day.
Choosing an odd time as GitHub says that high load times are at the
start of every hour.
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows\#scheduled-events
* run API tests on changes to java dependencies as we sometimes forget to do that on dependency updates. The API tests might catch some issues our other tests don't.
> chore: run dependabot outside of working hours and run e2e tests

- dhis-2/build-dev.sh
- jenkinsfiles/canary
- jenkinsfiles/dev
- jenkinsfiles/eos
We already did this in https://github.com/dhis2/dhis2-core/pull/9207 for most GitHub actions.
maven prints progress about downloading dependencies which we do not need to see. It just clutters,
increases the logs which makes finding things that one is looking for hard (errors, warnings, ...)
This should create cleaner build logs locally when using build-dev.sh,
when looking at the api test logs (which we run on GitHub) and when
looking at logs on Jenkins.
> chore: quiet down Jenkins and local build

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOption.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOptionCombo.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/Program.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/category/CategoryOptionComboTest.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/category/CategoryOptionTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/program/hibernate/Program.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplier.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/validation/AttributeOptionComboDateCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/context/ProgramSupplierTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/shared/validation/AttributeOptionComboDateCheckTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHookTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_14__Add_program_opendaysaftercoenddate.sql
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datavalue/DataValidator.java
See [DHIS2-11234](https://jira.dhis2.org/browse/DHIS2-11234). This adds `Program.openDaysAfterCoEndDate`. It allows program events to be entered for a given number of days beyond the `CategoryOption.endDate`.
This is analogous to `DataSet.openPeriodsAfterCoEndDate` which allows DataSet data to be entered for a given number of periods beyond the `CategoryOption.endDate`.
There are two places in the code where event dates are checked against the `CategoryOption.endDate`: `EventCategoryOptValidationHook` and `AttributeOptionComboDateCheck`. Both of these have been changed to check for `Program.openDaysAfterCoEndDate` as well.
Supporting methods in `CategoryOption` and `CategoryOptionCombo` were added or enhanced to facilitate these checks. These classes already checked for how a …
> feat: Program.openDaysAfterCoEndDate DHIS2-11234

- .github/dependabot.yml
- dhis-2/pom.xml
hikariCP was updated in
https://github.com/dhis2/dhis2-core/pull/9222
to 5.x which needs JDK11 at minimum
see
https://github.com/brettwooldridge/HikariCP/blob/ed2da5f1f4ef19f871fac12effc0b199706905dc/README.md#artifacts
we run using JDK8 profile on Jenkins which fails due to it.
Pin version to 4.x and update once our minimum JDK version changes
> chore: pin hikariCP to 4.x due to JDK8 support

- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobProgressTest.java
@Ivo noticed that the removed assert could fail on CI - there isn't a easy way to make sure we actually got close to the target parallelism so the assert got just removed.
> fix: flaky test job parallel runs

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
As requested by FE - GET isn't idempotent and should have been POST but I guess for backwards compatibility was kept as GET for quite some time.
> fix: use POST for execute jobs [DHIS2-12146]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sqlview/SqlView.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/sqlview/SqlViewServiceTest.java
2.35 backport of #9187 where test changes got removed as they required other changes that were never backported.
> fix: allow non ASCII letters for SQL view var values [DHIS2-11932] (2.35)

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java
On play/dev, predictor runs are still reliably failing for Malaria Outbreak Threshold, and still working just fine on my test machine. The first attempt to solve this, [pull/9174](https://github.com/dhis2/dhis2-core/pull/9174), didn't work.
This PR compiles diagnostic information to be returned on the failing error message, to gain further insight as to where the problem lies.
`DefaultPredictionService` fetches a list of orgUnits at the prediction orgUnit level using `organisationUnitService.getOrganisationUnitsAtOrgUnitLevels()`, puts these orUnits into a new ArrayList (as of [pull/9174](https://github.com/dhis2/dhis2-core/pull/9174)), sorts the array by orgUnit.path, and calls `PredictionDataValueFetcher.getDataValues()` for each orgUnit, in path order.
Meanwhile, …
> refactor: Diagnostic info for prediction error

- dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
This is not a backport of #9252 by cherry-picking that change since we keep `GET` in 2.36 for backwards compatibility.
> fix: use POST for execute jobs [DHIS2-12146] (2.36)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
Removed the paralellStream from the code. Not sure it actually made any difference, since it would be split amount any relationships, which usually is just a small portion of the payload sent in. If it becomes relevant to parallelise this process, it should include the other entities as well, not just relationships.
> fix: Test failing on jenkins due to race conditions

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceStoreTest.java
Order TEIs by create date is expensive and as the id is incremental we can just order by id to get the same result.
> fix: Order retrieved TEIs by id instead of created date [TECH-822]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistLogic.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractGistControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFilterControllerTest.java
Adds string field filters:
* `ieq` for case insensitive comparison (uses equivalent of `lower(field) = lower(value)`)
* `str-field:eq:<length>`: is length of the field equal to _length?
* `str-field:neq:<length>`: is length of the field not equal to _length?
* `str-field:gt:<length>`: is length of the field greater than _length?
* `str-field:lt:<length>`: is length of the field less than _length?
* `str-field:ge:<length>`: is length of the field greater than or equal to _length?
* `str-field:le:<length>`: is length of the field less than or equal to _length?
The length comparison for string fields is automatically identified. If the value given is a decimal number and the field is a string field this will assume this is a length comparison, not a string character comparison for the number …
> feat: Gist API string length and ieq filters [DHIS2-12168]

- dhis-2/dhis-e2e-test/pom.xml
- dhis-2/pom.xml
https://github.com/dhis2/dhis2-core/pull/9258 left it at JDK8
It was a bit confusing since we mix different ways of configuring the compiler plugin 
like the build plugins configuration and the user property
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html
I'll stick to the build plugins configuration so there is one place where we declare how to configure the compiler plugin
> fix: compile with JDK11 using maven compiler plugin

- .github/workflows/run-tests.yml
- dhis-2/pom.xml
We are running unit tests even when passing '-DskipTests'
since activating the default profile by default.
Expose a user property, ensuring we run unit tests by default
but can opt out if we want to.
https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html
A typo in the analytics job lead to compiling test code which we do not need.
> build: allow overriding skipTests in default profile

- dhis-2/dhis-web-embedded-jetty/src/main/resources/jetty-logging.properties
- dhis-2/dhis-web/pom.xml
https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/server/NCSARequestLog.html
was deprecated and subsequently removed
Jetty 10 changed quite a lot regarding logging
https://github.com/eclipse/jetty.project/issues/4572
there might be other settings we find have changed, that we need to adapt
> fix: fix running dhis war using maven jetty plugin

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
The failed event import in NTI is due to
1. no program instance in the tracker preheat
2. occasionally it is also due to a missing reference from a program stage to a program. This is happening because of the way the metadata import is implemented.
1. is fixed by putting program instances without registration into the preheat
2. is alleviated by providing an error message guiding the user to a solution for this edge
case. The root cause will be fixed in the metadata import.
After merging this change
The SQL insert error (1.) is fixed.
2. HTTP request
```sh
curl -i -u $AUTH \
-H 'content-type: application/json' \
--data @events.json \
"${HOST}/api/tracker?async=false"
```
that fails due to a program stage missing a reference to a program gets an HTTP response like
HTTP/1.1 409 Conflict …
> chore: provide meaningful error message DHIS2-12123

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/security/EnrollmentSecurityTest.java
A validation was added to block enrollments for programs added to orgUnits that does not have access to the program [11405](https://jira.dhis2.org/browse/DHIS2-11405)
However, that validation only considered ID scheme and not the other scheme. 
This PR fixes that by using the ID Schemes mentioned in the ImportOptions.
> fix: OrgUnitIdScheme not working when adding enrollment [DHIS2-12181] (2.38)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
backport of #9312
* chore: provide meaningful error message DHIS2-12123
the failed event import in NTI is due to a missing reference from a
program stage to a program. this should not happen but it does
occasionally, due to the way the metadata import is implemented.
provide an error message guiding the user to a solution for this edge
case, until the root cause is fixed.
* fix: add programs without registration to preheat DHIS2-12123
https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/new-tracker.html\#events
states that program is not required. In this case the program and then
program instance are not in the preheat. This leads to an error in
the SQL insert statement as program instance needs to be specified
on the program stage instance. Since programs without …
> chore: provide meaningful error message DHIS2-12123 (#9312) 2.37

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/StartupConfig.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/provider/Wso2Provider.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/DefaultSystemService.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/HibernateListenerConfigurer.java
- dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/config/ArtemisConfig.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/config/FlywayConfig.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/DefaultDhisConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/DhisConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-external/src/test/java/org/hisp/dhis/external/conf/DhisConfigurationProviderTest.java
- dhis-2/dhis-support/dhis-support-external/src/test/resources/dhis.conf
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/config/DataSourceConfig.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/datasource/DatabasePoolUtils.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/ExtendedCacheBuilder.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/condition/RedisDisabledCondition.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/condition/RedisEnabledCondition.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/configuration/RedisConfiguration.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/BaseSpringTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisSpringTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/H2DhisConfigurationProvider.java
There is a mix of true/false and on/off for boolean configuration properties. This is confusing, and there should only be one.
This task sets out to make/refactor code to only use the on/off, but still allow of both usage in the configuration file to maintain backward compatibility. Also, the methods used for checking and converting a property from a string to a boolean value is refactored.
The documentation should also be refactored to only show on/off as option for boolean config properties.
A new test class was made to test the new methods: DhisConfigurationProviderTest
JIRA:
> chore: Unify the boolean switch in the configuration.

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHookTest.java
Validate program stage reference to program instead of throwing a more detailed exception.
* EventProgramPreProcessor
* EventWithoutRegistrationPreProcessor
are 2 pre-processors where we discovered an NPE due to a missing
reference in the DB from program stage to program. This is an edge case
due to how the metadata import is currently implemented.
Since pre-processing is done before validation we opted for returning
before an NPE occurs. Validation will then find that a reference to a
program is missing in the DB and create an error report.
Note that the program field is not a mandatory field in the payload
according to our NTI API documentation. I therefore needed an extra
error code and return before adding E1123 which would only confuse the
user.
Reproduce:
```sql
update programstage …
```
> fix: validate program stage reference to program DHIS2-12123

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHookTest.java
instead of throwing a more detailed exception.
* EventProgramPreProcessor
* EventWithoutRegistrationPreProcessor
are 2 pre-processors where we discovered an NPE due to a missing
reference in the DB from program stage to program. This is an edge case
due to how the metadata import is currently implemented.
Since pre-processing is done before validation we opted for returning
before an NPE occurs. Validation will then find that a reference to a
program is missing in the DB and create an error report.
Note that the program field is not a mandatory field in the payload
according to our NTI API documentation. I therefore needed an extra
error code and return before adding E1123 which would only confuse the
user.
> fix: validate program stage reference to program DHIS2-12123 (#9359) 2.37

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/render/RenderFormat.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
[pull/8826](https://github.com/dhis2/dhis2-core/pull/8826) fixed a problem where the backend had added the extension twice for a compressed data export, "so attachment=data.xml.zip ends up data.xml.zip.xml.zip". That PR supported xml, json, and csv.
This PR adds support for adx+xml compressed data export. This is required so [DHIS2-4978](https://jira.dhis2.org/browse/DHIS2-4978) can be implemented.
> refactor: Support compressed ADX output

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/TranslatablePropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
https://jira.dhis2.org/browse/DHIS2-11748
This is to allow `api/schemas` consumer know whether an embedded object property is translatable.
Example:
_Predictor class_
```
class Predictor 
{
private Expression generator;
}
```
_Expression class_
```
class Expression  
implements Serializable, EmbeddedObject
{
@Translatable( propertyName = "description", key = "DESCRIPTION" )
private String description;
}
```
_api/schemas/predictor.json_
```
{
"klass": "org.hisp.dhis.predictor.Predictor",
"name": "Predictor",
"properties": [
{
"klass": "org.hisp.dhis.expression.Expression",
"propertyType": "COMPLEX",
"name": "generator",
"fieldName": "generator",
"translatable": true
}
}
```
> fix: enable translatable schema property for embedded object

- dhis-2/dhis-api/pom.xml
- dhis-2/dhis-services/dhis-service-administration/pom.xml
- dhis-2/dhis-services/dhis-service-analytics/pom.xml
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-node/pom.xml
- dhis-2/dhis-services/dhis-service-reporting/pom.xml
- dhis-2/dhis-services/dhis-service-schema/pom.xml
- dhis-2/dhis-services/dhis-service-tracker/pom.xml
- dhis-2/dhis-support/dhis-support-artemis/pom.xml
- dhis-2/dhis-support/dhis-support-cache-invalidation/pom.xml
- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-support/dhis-support-test/pom.xml
- dhis-2/dhis-web-api-test/pom.xml
- dhis-2/dhis-web-api/pom.xml
- dhis-2/pom.xml
fixes https://github.com/dhis2/dhis2-core/pull/9303
as hamcrest changed its packaging
http://hamcrest.org/JavaHamcrest/distributables
Following the documentations advice, we then see
```
mvn dependency:tree -f dhis-2/pom.xml
...
08:34:15,686 [main] [INFO] +- org.hamcrest:hamcrest:jar:2.2:test
08:34:15,686 [main] [INFO] +- org.hamcrest:hamcrest-library:jar:2.2:test
08:34:15,686 [main] [INFO] |  \- org.hamcrest:hamcrest-core:jar:2.2:test
08:34:15,686 [main] [INFO] +- junit:junit:jar:4.13.2:test
08:34:15,686 [main] [INFO] +- org.mockito:mockito-core:jar:3.4.6:test
```
that JUnit 4 does not bring in hamcrest 1.x version anymore. This is true for when a module depends on hamcrest. So declares it in its pom.
If a module does not depend on hamcrest we will still see
```
08:34:15,751 [main] …
```
> chore(deps): update hamcrest to 2.2

- dhis-2/pom.xml
we declare lombok as scope provided since its a compile time dependency that does not need
to be present at runtime. maven dependency:analyze often tells us lombok is declared but
unused because it does its work at compile time, and as such most annotations are removed after compilation.
We can tell the dependency plugin to ignore such 'declared unused' dependencies since with scope
provided it will not be shipped in our final war even if it was actually unused in one of our modules
Same with the hamcrest-library which is needed until we update to junit
5 which does not depend on hamcrest anymore. See http://hamcrest.org/JavaHamcrest/distributables#maven-upgrade-example
> fix: maven dependency:analyze declares lombok/hamcrest-library as unused

- dhis-2/dhis-services/dhis-service-acl/pom.xml
- dhis-2/dhis-services/dhis-service-schema/pom.xml
- dhis-2/dhis-services/dhis-service-setting/pom.xml
- dhis-2/dhis-services/pom.xml
- dhis-2/pom.xml
dhis-service pom declares dependencies although it does not have any dependencies. I assume it is so that its child modules all "inherit" these dependencies. Not every child module needs them. Each child module should be independent when it comes to its `<dependencies>`.
Cleanup ~15 services pom.xml files before removing it. This tackles the first 3 😅 
This is part of https://jira.dhis2.org/browse/TECH-801
I based it on https://github.com/dhis2/dhis2-core/pull/9372 as its helpful in analyzing dependencies. Please approve/merge https://github.com/dhis2/dhis2-core/pull/9372 before
> chore: clean dhis-service poms

- dhis-2/dhis-services/dhis-service-core/pom.xml
we configure the JDK11 release in the pluginManagement of our root pom
child projects inherit the config. core plugins like the compiler plugin
do not need to be declared explicitly they are activated by default
https://www.baeldung.com/maven-plugin-management
> fix: dhis-services should also target JDK11

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/PropertyType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserCredentials.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/LoginTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_export/MetadataExportTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/orgunits/OrgUnitsTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserDisableTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserPaginationTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UserTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/users/UsersRemovalTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/deduplication/PotentialDuplicatesApiTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/UserAssignmentFilterTests.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/OwnershipTests.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceUserTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/users.json
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/validation/DefaultSchemaValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/NotesConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/tracker_basic_metadata.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/tracker_basic_metadata_mandatory_attr.json
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/util/ValidationUtilsTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AccountControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/BulkPatchSharingControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AccountController.java
This PR adds regexp validation of the username.
Allowed usernames must match this regular expression: 
```
^(?=.{4,255}$)   (?![_.@])   (?!.*[_.@]{2})   [a-z0-9._@]+   (?<![_.@])$
```
1. username is 4-255 characters long
2. no _ or . or @ at the beginning
3. no __ or .. or @@ inside
4. allowed characters
5. no _ or . or @ at the end
* ValidationUtilsTest.testUsernameIsValid()
* UserControllerTest.testPostJsonObjectInvalidUsername()
Jira: [DHIS2-10886](https://jira.dhis2.org/browse/DHIS2-10886)
> feat: Add username regexp validation

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/OrganisationUnitDescendants.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataExportParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/predictor/Predictor.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/predictor/hibernate/Predictor.hbm.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/SpringDataValueSetStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/adx/AdxDataServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceExportTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_16__Add_includedescendantorgunits_to_predictor.sql
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/PredictorControllerTest.java
See [DHIS2-9833](https://jira.dhis2.org/browse/DHIS2-9833). This PR implements the predictor property includeDescendantOrgUnits, which allows the user to optionally select whether a predictor includes lower-level orgUnit data.
Until now, predictors always selected lower-level orgUnit data, so in updating the database, any existing predictors will have includeDescendantOrgUnits set to true. However it is a more useful default to have predictors not select lower-level orgUnit data. So for new predictors defined in the future, the default value for includeDescendantOrgUnits will be false.
> feat: Optional predictor lower levels DHIS2-9833

- jenkinsfiles/canary
Once in a while we get a request for canary docker images, eg when faulty migration breaks on SL db and devs are blocked. This pipeline change will publish latest docker image from core-dev to core-canary using the naming scheme that we agreed on [here](https://github.com/dhis2/notes/blob/00ae685fd3e7ecd8fcdb67ff544f7ad39101b862/minutes/2019/05/25-war-docker-schemes.md): 
eg: 
```
dhis2/core-canary:2.32
dhis2/core-canary:2.32-20190522
```
Tested on: https://ci-backup.dhis2.org/job/gintare-test/
> ci: publish canary docker images [skip-ci]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
The issue was that when using compression for XML or CSV export the exported archive was empty.
This was because the stream wasn't properly closed which is needed for compressed streams so they finalize the archive.
I could not find why this would work for JSON but it does not hurt to close the stream even for JSON. 
In general now all types are handled uniformly.
* Open Import/Export app the Data Value export http://localhost:8080/dhis-web-import-export/index.html#/export/data
* select root ourg unit
* select a data set, e.g. the first _ART Monthly Summary_
* run the export with all combinations of the radios for format and compression
* check all the downloaded files to contain the expected content
> fix: data value export all format with or without compression [DHIS2-11925]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStoreTest.java
quoting the userId parameter leads to an OR clause like
OR sharing->'users'->'''ILK8ARxOS1V'''->>'access' LIKE '__r%'
in the ACL query which does not contribute any results to the overall
query
>  fix: duplicate quotes prevent ACL users sharing to work DHIS2-11557 [2.36]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStoreTest.java
quoting the userId parameter leads to an OR clause like
OR sharing->'users'->'''ILK8ARxOS1V'''->>'access' LIKE '__r%'
in the ACL query which does not contribute any results to the overall
query
> fix: duplicate quotes prevent users sharing to work DHIS2-11557 (#9415) [2.37]

- .github/workflows/run-api-tests.yml
Seems that sometimes api-test action is not executed, although it should. This is an attempt to fix that.
> ci: trigger api-tests on [opened] event

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStoreTest.java
quoting the userId parameter leads to an OR clause like
OR sharing->'users'->'''ILK8ARxOS1V'''->>'access' LIKE '__r%'
in the ACL query which does not contribute any results to the overall
query
> fix: duplicate quotes prevent users sharing to work DHIS2-11557 (#9415)

- dhis-2/pom.xml
Bumps log4j-core from 2.14.1 to 2.15.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit d68ea622f36aa98bb04c59f554a886445fd03c27)
> chore(deps): bump log4j-core from 2.14.1 to 2.15.0 in /dhis-2 (#9431)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithApiTokenAuthTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithJwtTokenAuthTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebClient.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebSnippet.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/DhisMockMvcControllerTest.java
Makes the `WebClient` layer independent of spring Mock MVC so we can use it in e.g. e2e as a layer on top of actual web request or in container integration tests.
Th make the layer independent both request and response need a indirection so they can be adopted to different underlying layers like sping Mock MVC or real requests. 
The spring Mock MVC adoption has been moved to a new base test class `DhisMockMvcControllerTest` that contains the request and response adopters.
Special HTTP methods like multipart files or file uploads are not supported by the generic layer the support methods have been moved to the base test for Mock MVC and will just be supported there. Other implementations can go the same route of implementing special handling in their base class. From the user point of view …
> chore: extracts spring independent HTTP request test API

- dhis-2/dhis-services/dhis-service-dxf2/pom.xml
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/TrackerCrudTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidatorTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/event/JdbcEventCommentStoreTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/update/validation/ExpirationDaysCheckTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/sync/MetadataSyncDelegateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/version/MetadataVersionDelegateTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterServiceTest.java
- dhis-2/pom.xml
Since 3.4 you can mockStatic with mockito which seems to be good enough
for our use cases. Only relying on mockito makes a transition to JUnit 5
easier as well. So double bonus :yum:
https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#static_mocks
> chore(deps): update to mockito 4.x and remove powermock usage

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/Cache.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/NoOpCache.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CappedLocalCache.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/RedisCache.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/cache/TestCache.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
Implements cluster wide coordination of job execution using (redis) caches.
This affects:
* preventing same job from being started more than once at a same time
* sharing of job running and job completed information (tracking)
* cancelling of jobs
In case of a non cluster setup the the coordination still takes place just that it is stored in a local cache and that is has no actual effect that way.
The main mechanism is that a background job is running every 30 seconds to update the caches used to coordinate between nodes. These are set to become outdated after 60 seconds so that should they not be refreshed regularly they out-date quite fast and open for other nodes to run a job of the same type.
If this coordination is "transactional" in the cluster depends on the spring `RedisTemplate` …
> feat: prevent simultaneous jobs in a cluster [DHIS2-12018]

- dhis-2/pom.xml
(cherry picked from commit 4f34405c0a4c9add43375735b88ebddd98d7bddf)
> chore(deps): bump log4j-core from 2.15.0 to 2.16.0 in /dhis-2 (#9466)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/MetadataItem.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/AnalyticsCache.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/cache/AnalyticsCacheTest.java
/api/analytics/dataValueSet.json?dimension=dx:SqD0kovH0CS&dimension=ou:m5NxCAOnDg6&dimension=pe:20210902 where dx is a program indicator returns null value, when the request is issued second time and more within AnalyticsCache TTL
(typically 60sec)
first response:
``` json
{
"dataValues": [
{
"dataElement": "SqD0kovH0CS",
"period": "20210902",
"orgUnit": "m5NxCAOnDg6",
"value": "2.0",
"storedBy": "[aggregated]",
"created": "2021-11-23",
"lastUpdated": "2021-11-23",
"comment": "[aggregated]"
}
]
}
```
second one:
``` json
{
"dataValues": [
{
"dataElement": "SqD0kovH0CS",
"period": "20210902",
"orgUnit": "m5NxCAOnDg6",
"value": "null",
"storedBy": "[aggregated]",
"created": "2021-11-23",
"lastUpdated": "2021-11-23",
"comment": "[aggregated]"
}
]
}
```
The problem was identified in the …
> [2.38-DHIS2-TECH842] Grid Caching is not properly used in analytics 

- dhis-2/pom.xml
we use speedy-spotless-maven-plugin so we can remove this one
> chore(deps): remove unused formatter

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
We changed in the past the analytics  table structure and renamed level to oulevel for some reason. But there is still sql query with "where level" left, written in 2016. The problem is visible only if you have some data in dataelementaggregationslevel table => only when data element aggregation levels are present.
> fix:  DHIS2 Can’t finish the analytic in version 2.37.1 [2.38-DHIS2-TECH899]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableGenerator.java
During the refactoring the setting the stores the last successful analytics table generation runtime accidentally got stored from `getTime()` (which returns a `long`) instead of `time()` (which returns a formatted `String`).
* open scheduler app
* create a new job to generate analytics tables
* run the new job manually and wait for the job to finish, you can check `/api/scheduling/running/` and `/api/scheduling/completed/` to see when it is done
* open _About DHIS2_ info (click on your user menu)
* check the time is no longer presented in milliseconds but a formatted time period
Note that the job needs to run once in order to see the corrected formatting as the old value from last run which is stored was produced with the code that was not yet corrected.
> fix: store last analytics table runtime as formatted duration [DHIS2-12259]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventchart/EventChart.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventreport/EventReport.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/EventChartControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventChartController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventReportController.java
This PR aims to filter out items created through the new endpoint `/eventVisualizations`.
Basically, items created by `/eventVisualizations` should not be readable by the legacy endpoints `/eventReports` and `/eventCharts`.
This is done because the new EventVisualization entity contains small differences that will break the existing apps Event Reports and Event Visualization.
> feat: Isolated 'legacy' report/chart from event visualization [TECH-867]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
Limiting the response mime type is unnecessary and causes issues in the app that always wants JSON back. So we just loosen the mapping so the client can ask for any of the supported types using any of the supported ways to negotiate the response format.
* open Import/Export app
* run data value import using XML, JSON and CSV files in dry run
* check the app shows the "Job started" info followed by a result a bit later for any of the inputs
Tip: If you don't have proper input files use the data value export with uncompressed to create some.
> fix: data value import no hard coded response mime type [DHIS2-12262]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/predictor/PredictorGroup.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
(cherry picked from commit 31b080a939378ed9c2013abba9b349d463302344)
> fix: Run a group's predictors in order [DHIS2-12091] (#9525)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/ValidationErrorReporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackerValidationOrderTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackerValidationServiceReportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/AssertValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentDateValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentGeoValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentNoteValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventGeoValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventNoteValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckUidValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckUpdatableFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHookTest.java
To accomplish envisioned refactoring https://github.com/dhis2/dhis2-core/pull/9523 (removing ValidationErrorReporter and its error report merge logic) I need to make sure that we also test on error/warning codes, type, uid in tracker error reports.
Took the idea from ErrorReportContainer to add a helper in ValidationErrorReporter to ease asserting that
a particular error is present. This gives us the flexibility to assert on one or many fields. anyMatch also
keeps the test flexible in case more errors are in the error list.
The hasErrorReport/WarningReport code can be moved to TrackerValidationReport once ValidationErrorReporter is removed.
Except for ValidationErrorReporter only tests were changed and added!
> chore: assert on error/warning codes, type, uid in tracker error reports TECH-880

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ParserUtils.java
See [DHIS2-12258](https://jira.dhis2.org/browse/DHIS2-12258). The `.periodOffset()` expression function should be valid only in indicator expressions.
I also added a comment in `ParserUtils` to document `COMMON_EXPRESSION_ITEMS`, so hopefully this will reduce the chance of this type of error in the future.
> fix: periodOffset only in indicators DHIS2-12258

- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ParserUtils.java
- Expand wildcard imports
- Define a private class constructor to hide the public constructor
- change `final static` to `static final`
> refactor: fix ParserUtils coding conventions

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
This fixes a small bug introduced recently. Basically, the declaration `private IdScheme outputIdScheme` was "shadowing" the same declaration in the superclass.
So, when we invoked methods in the superclass that needed the `outputIdScheme`, it would be null depending on the situation.
_In addition I also added a missing call into a specific analytics events request._
One tiny refactoring was also included: changed the parameter `DataQueryParams` to `EventQueryParams` just to keep it aligned with the other methods in the respective class. This does not affect this fix.
> fix: OutputIdScheme rule for events [DHIS2-11181]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/Cache.java
A comment in `Cache.invalidateAll` from 4 years ago said that "If a shared cache is used, this method does not clear anything." However two years ago in [TECH-248](https://jira.dhis2.org/browse/TECH-248) `RedisCache.invalidateAll` was implemented, so this comment was overcome by events.
> docs: fix comment about invalidating shared cache

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/category/CategoryOptionComboStore.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupTaglessResolver.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/resolver/ExpressionResolvers.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/resolver/CategoryOptionGroupResolverTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/hibernate/HibernateCategoryOptionComboStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/category/CategoryOptionComboStoreTest.java
See [DHIS2-12278](https://jira.dhis2.org/browse/DHIS2-12278). Too many category option combos are returned for a data element because the choices are not restricted to the data element's category combination. The fix is to add the data element's category combination to the query, further restricting the category option combos returned.
I changed the order in which the `ExpressionResolvers` are executed, so that the data elements are resolved before the category option groups. (We had it the other way around for parsing performance, but this needed to change in order to generate the correct category option combinations.)
Also I rewrote the query using HQL instead of the JPA Criteria API. (I found this easier to read. Others might as well.)
> fix: coGroup: too many option combos DHIS2-12278

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_22__Remove_mistake_of_duplicated_FK_in_visualization_organisationunits.sql
Duplicated FK `fkvisualization_organisationunits_organisationunitid` that can be removed.
The correct one is already in place and is named: `fk_visualization_organisationunits_organisationunitid`
> fix: Remove duplicated FK [TECH-905]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
Dates stored in `eventdatavalues` column, in `programstageinstance` table (when ValueType is equal to DATETIME) are not exported into analytics tables.
This happens because the Capture application is posting the date/time using the format `2021-12-14T11:45:00.000Z`.
In order o fix it, I'm changing the date regexp so it can match the date format above.
> fix: Expand date regex in analytics export [DHIS2-7107]

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataIntegritySummaryControllerTest.java
When I did the original PR #9364 I thought that we don't have a dedicated summary for the existing checks so we don't support it but that is not going to work well with the way the frontend app will use this. It is easy enough to just derive the summary from the details as all it does is state the count of the issues found in details. So this PR is just connecting the bits to make that happen.
> feat: provide data integrity summary check for programmatic checks [DHIS2-12214]

- jenkinsfiles/canary
Related to https://github.com/dhis2/dhis2-core/pull/9536
The changes from the `master` won't be backported 1 to 1 to the supported 2.37, 2.36 and 2.35 branches.
No need for delomboking and extra changes outside of the Jenkins pipeline script here, as `JDK11` is currently only required on the `master` branch (future 2.38 version).
> build: Add javadoc generation stage to canary pipeline [DEVOPS-114] [2.37]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistLogic.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistCsvControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
Recently noticed while testing that I originally only added CSV responses for Gist API for the main list, not the object and collection property listing. This PR adds CSV for these too and covers CSV with tests.
This PR also does a small correction for the default transformation used on collection properties that could be `NONE` instead of `SIZE` which basically excluded the collection from being included.
> feat: Gist API CSV output for object and property collections

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportBasedOnSchemasTest.java
eventCharts schema returns `PIVOT_TABLE` and `LINE_LIST` as values of `type` enum, but this endpoint doesn't support them anymore, so sometimes that test fails. Removing the test to limit flakiness.
> test: blacklists eventCharts endpoint

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/RedisCache.java
Forgot to strip the region from the cache keys when these are exposed as `keys()`.
> fix: strip region from redis cache keys

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramNotificationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/programrule/engine/RuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/event/ProgramRuleEnrollmentEvent.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/event/ProgramRuleStageEvent.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionAssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionScheduleMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/RuleActionSendMessageImplementer.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/NotificationRuleActionImplementerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EnrollmentPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerRuleEngineThread.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerSideEffectDataBundle.java
This is a backport PR for [DHIS2-11979].
Main objective was to reduce database queries for fetching programstageinstance and programinstance when they are needed in rule-engine execution. Now TrackerSideEffectDataBundle contains all the information needed and there is no need to make database queries in order to run rules and also to execute rule effects.
> fix: (2.37) slow import and high memory allocation in NTI  (#9049)

- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/pom.xml
I would vote for removing the dependency (merging this PR) in favor of  updating it https://github.com/dhis2/dhis2-core/pull/9557
> chore(deps): remove unused istack-commons-runtime

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerImportService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/Timing.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerValidationReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationService.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/OwnershipTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/params/AtomicModeIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerBundleImportReportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerValidationReportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentAttrValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TeTaValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackerValidationOrderTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackerValidationServiceReportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/ValidateAndCommitTestUnit.java
* as proposed by @jbee : make the add methods of TrackerValidationReport add methods fluent
* consistently name getters like add methods so getErrors, getWarnings instead of getErrorReports, ...
* rename TrackerValidationHookTimerReport to Timing as that's enough to describe what it represents
* Timing only has 2 fields, so a required arg constructor suffices. The fields are public and exposed in the JSON. I made them final so they cannot be set to something else (at least not without really wanting it).
* added missing test for addErrors, addWarnings
> chore: make TrackerValidationReport add methods fluent and name Timing TECH-880

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/TranslatablePropertyIntrospector.java
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
https://jira.dhis2.org/browse/DHIS2-12290
Issue:
- ProgramStageSection  table doesn't have `shortname` column but from api/schemas it's translatable.
- This property is inherited from `BaseNameableObject`
Fix: add `isPersisted` check to `TranslatablePropertyIntrospector`
> fix: not persisted property should not be translatable

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramSectionSchemaDescriptor.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/ProgramSectionControllerTest.java
Issue:
- Translations App requires an object to have authority in order to be listed.
- ProgramSection doesn't have any authority defined in `ProgramSectionSchemaDescriptor`
Fix:
- Copy `F_PROGRAM_PUBLIC_ADD` from `ProgramSchemaDescriptor` to `ProgramSectionSchemaDescriptor`
- After this change, all user still can create `ProgramSection` as before. 
Test:
- Added unit test and controller test
> fix: ProgramSection is not shown in Translations App

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/InQueryFilter.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/InQueryFilterTest.java
A small fix is needed so the events IN filter takes into consideration the case sensitivity.
This is related to the JIRA DHIS2-12318 (new analytics operators).
> fix: Make events IN filter respect case [DHIS2-12334]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonErrorReport.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
Sets the correct property name in the validation errors for `username` and `whatsApp` validation.
Added/extended unit tests to verify.
> fix: refer and set to property name in user object bundle errors [DHIS2-12336]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/datavalue/DataValueServiceTest.java
See [DHIS2-12360](https://jira.dhis2.org/browse/DHIS2-12360). With an ADX data value set export specifying start/end dates, a period is not chosen if it ends on the specified end date. This is inconsistent with XML/json data value set exports.
The cause is that `HibernateDataValueStore.getDataValues` was looking for period end dates < the specified endDate, instead of <=. While other places in the code use this method, only ADX uses it with specifying start and end dates instead of specifying a set of periods.
A test was added that fails with the bug and succeeds with the fix.
> fix: ADX export period on endDate DHIS2-12360

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/VectorCount.java
See [DHIS2-11327](https://jira.dhis2.org/browse/DHIS2-11327). Allow the user to specify the keyword `distinct` inside the count function for a program indicator with custom aggregation.
> fix: Program indicator count distinct DHIS2-11327

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/TrackerTrigramIndexJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackedEntityAttributeTableManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/JdbcTrackedEntityAttributeTableManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackerTrigramIndexingJob.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/job/TrackerTrigramIndexingJobTest.java
After discussing with Gintare and Bob, we have decided to remove the vacuum and analyze functionality from the job to make it cleaner. 
This PR also add the logic of identifying obsolete trigram indexes and removing them.
> fix: Remove vacuum analyze from index creation job (2.38)

- dhis-2/dhis-e2e-test/src/test/resources/setup/tracker_metadata.json
- dhis-2/dhis-e2e-test/src/test/resources/tracker/programs_with_program_rules.json
API test metadata was wrongly updated with #9540 which also hid the bug that required valueType for all programRuleVariables, when it should only be required for **calculated_value** program rule variables.
> test: remove incorrectly added properties

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/grid/GridTest.java
This feature is about supporting a new `headers` param in _events endpoints_.
This new param will allow the clients to choose the `headers` they want back as part of the response.
The `headers` ordering in the response will match the same order of the `headers` specified as the URL parameter.
This should work for `/events/query` and `enrollments/query` endpoints.
Examples of **GET** requests using the `headers` parameter:
`http://localhost:8080/dhis/api/29/analytics/events/query/eBAyeGv0exc.json?dimension=pe:LAST_12_MONTHS&dimension=ou:jUb8gELQApl;TEQlaapDQoK;eIQbndfxQMb;Vth0fbpFcsO;PMa2VCrupOd;O6uvpzGd5pu;bL4ooGhyHRQ;kJq2mPyFEHo;fdc6uOvgoji;at6UHUQatSo;lc3eMKXaEfw;qhqAxPSTUXp;jmIPBj66vD6&stage=Zj7UnCAulEk&displayProperty=NAME&outputType=EVENT&desc=eventdate&pageSize=100&page=1&headers=oun …
> feat: Support event headers as GET param [DHIS2-12314]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/action/validation/AssignProgramRuleActionValidator.java
ASSIGN program rule action will pass the validation when any one of the parameters `(DataElement, TrackedEntityAttribute or ProgramRuleVariable) ` is given.
> fix: assign rule action validation update [DHIS2-12033]

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
Revert the [PR#9078](https://github.com/dhis2/dhis2-core/pull/9078) because it causes a regression issue [DHIS2-12468](https://jira.dhis2.org/browse/DHIS2-12468)
**PR#9078** tried to fix [DHIS2-8868](https://jira.dhis2.org/browse/DHIS2-8868), but currently I can't reproduce this issue after revert the fix.
I think we should merge this first to fix **DHIS2-12468** , then QA can check if **DHIS2-8868** still happen then I can investigate and create another PR to fix that.
> fix: attribute id is missing in api response (2.35)

- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
The integration test `testAuditEntryForDeletionOfSoftDeletedTrackedEntityInstance` is causing intermittent error.
This is maybe because it tries to query audit records from audit table and there is a delay of messages being processed by atermis. 
Need to investigate, maybe we only can support unit test here, and not integration test.
> fix: disable audit test which has intermittent error (2.35)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/LockException.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/LockExceptionControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/LockExceptionController.java
Changes the response behaviour when creating lock exceptions. 
If no OU is linked to the specified DS the response is no longer 204 but 409 with an error message so that the caller understands that nothing had happened. 
This also adds `/gist` API for  `LockException`. Helps looking for what exceptions do exist.
> fix: return conflict when no lock exception is created for OU-DS combinations [DHIS2-10901]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_26__Add_Feedback_recipients_to_configuration.sql
The specific script was accidentally first added under the 2.37 folder which was caused to already execute in the play dev db. (https://github.com/dhis2/dhis2-core/pull/9665) The script was now moved to 2.38 which caused the script to execute again and now failing in dev because it is not idempotent. Changed the script to make it idempotent to overcome this situation.
(Another option was to manually update the dev db to clear the offending constraint)
> fix: Make flyway script idempotent to avoid manual dev db changes (2.38)

- dhis-2/pom.xml
`jackson-datatype-jts` only supports jts 1.16 and down.
> fix: downgrades jts to 1.16.1 as jackson-datatype-jts does not support it

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
This issue might be limited to Windows.
The e2e tests uses Instant.now() for generating datetimes for dummy data. These datetimes include 9 digits for fractions of a second, while the most we support in the core is 7 fractions of a second.
Add support for 9 fractions of a second instead of rewriting the e2e tests, in case this is just happening on Windows.
> fix: Add support for datetime with 9 fraction of a second

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/Period.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/PeriodOffsetUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/PeriodOffsetUtilsTest.java
See [DHIS2-12496](https://jira.dhis2.org/browse/DHIS2-12496), especially the screen shots showing the problems and the fixes.
**The problem:** `DataHandler#getAggregatedDataValueMap` called `DataHandler#addItemBasedOnPeriodOffset` once for each combination of DimensionalItemObject (`dimItem`) and returned data row within the selected reporting periods. If the dimItem had a periodOffset, then this method called `PeriodOffsetUtils#getPeriodOffsetRow`. This method searched through all the returned grid data to find a row with data that matched the dimItem and the offset period. `addItemBasedOnPeriodOffset` then added to the result map a value using the key (including dimItem and period) from the original row, but the value from the offset row.
The problem was that this worked only if there …
> fix: periodOffset misses some data [DHIS2-12496]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
Adds a new system setting for including zero values in aggregate analytics tables. Default value is false/disabled. When enabled, zero values for data elements with "zero is significant" enabled will be included.
> feat: Add system setting for include zero values in analytics [DHIS2-12498]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceMetadataTest.java
Current behaviour
When a data element with an option set is requested on /analytics/events/query metadata is returned for all options in the option set. Even when only a few options are specifically requested, e.g. dimension=K6uUAvq500H:IN:A00;A000, metadata for all options are returned.
Example where a single option has been specified. Still metadata for all 14000+ options are returned:
https://play.dhis2.org/dev/api/29/analytics/events/query/eBAyeGv0exc.json?dimension=pe:LAST_3_MONTHS&dimension=ou:ImspTQPwCqd&dimension=Zj7UnCAulEk.K6uUAvq500H:IN:A00&displayProperty=SHORTNAME&outputType=EVENT&desc=eventdate&pageSize=100&page=1
Example request where no options are specified and page size is set to 100. Still metadata for all 14000+ options are returned: …
> 2.38-DHIS2-12326 Event analytics always returns metadata for all options in option set

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ObjectReport.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
Fix issue of adding `ObjectReport` inside the for loop of one object's translations which leads to `ConcurrentModificationException`.
Also shorten the translation duplication check to make it clearer.
> fix: ConcurrentModificationException in translationCheck

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
Symptom: See [DHIS2-12518](https://jira.dhis2.org/browse/DHIS2-12518). Some dashboard items aren't loading and getting a 500 error from the server.
Cause: In [pull/9671](https://github.com/dhis2/dhis2-core/pull/9671), in `DataHandler#getAggregatedDataValueMap` a test for `isPeriodInPeriods` was erroneously moved from an `if` clause to the `else` clause. It should have been removed altogether.
Testing: With this fix, all dashboard items display on all dashboards without the 500 error.
> fix: DataHandler fix for dashboard 500 DHIS2-12518

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/PredictorDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/predictor/PredictorServiceTest.java
Minimal re-implementation of #9659 in the old deletion handler tech.
> fix: veto CategoryOptionCombo deletion if used by Predictor [DHIS2-10687] (2.36)

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
when a user uses a dataElementIdScheme other than UID the NTI validation falsely said
* the payload is missing a mandatory dataElement (mandatory to the program stage)
* the payload contains a dataElement that is not part of the events programStage
This was due to the NTI validation not taking the idScheme into account in the EventDataValuesValidationHook
After the above fixes the ProgramRuleService failed to find the DataElement because it was using the UID instead of the user specified CODE idScheme.
Now the EventTrackerConverterService map EventDataValue.dataElement to UID. It does so by getting the dataElement from the preheat.
At this point EventDataValuesValidationHook already checked whether the
dataElement specified by the user exists by looking in the preheat. If
not found it …
> fix: use idScheme in event dataElement checks DHIS2-12282

- .github/workflows/analyse-pr.yml
- .github/workflows/check-formatting.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/run-api-tests.yml
- .github/workflows/run-tests.yml
Adopt OpenJDK got moved to Eclipse Temurin https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
which is now pre-installed on GitHubs ubuntu runners
https://github.com/actions/virtual-environments/issues/3859
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md\#java
by setting the actions/setup-java distribution to temurin the action will not have to download a JDK and thus
save a few seconds on every jobs 'Setup JDK 11' step
see https://github.com/dhis2/dhis2-core/runs/4919378791?check_suite_focus=true#step:3:41
> Resolved Java 11.0.13+8 from tool-cache
> chore: use GitHub runners pre-installed JDK

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
backport of  https://github.com/dhis2/dhis2-core/pull/9722
* chore: fix IDE warnings in EventDataValuesValidationHookTest
* chore: clean EventDataValuesValidationHookTest
* remove unnecessary mockito stubbings to use mockito mode strict and keep future tests
clean
* split tests that contained multiple test cases into multiple tests
* fix: use idScheme in dataElement programStage check DHIS2-12282
* fix: use idScheme in mandatory dataElement check DHIS2-12282
* chore: map EventDataValue.dataElement to UID
At this point EventDataValuesValidationHook already checked whether the
dataElement specified by the user exists by looking in the preheat. If
not found it would add error E1304 'DataElement `{0}` is not a valid
data element' and fail validation. Looking the dataElement up in the
preheat …
> fix: use idScheme in event dataElement checks DHIS2-12282 [2.37]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
Symptom: See [DHIS2-12518](https://jira.dhis2.org/browse/DHIS2-12518). Some visualizations aren't loading and getting a 500 error from the server caused by a NPE.
Cause: In [pull/9671](https://github.com/dhis2/dhis2-core/pull/9671), in `DataHandler#addItemBasedOnPeriodOffset` a test was being made to insure that the `dimensionalItemObject` UID matched the UID in the current grid row. There were two problems with this test:
1. While many common types of `DimensionalItemObject` return a UID, some do not (resulting in the NPE).
2. This test is redundant, since the code in `getAggregatedDataValueMap` that calls `addItemBasedOnPeriodOffset` already filters the dimensionalItems to include only those matching the `DimensionIdentifier` from the grid row. This is done in the construct `for ( …
> fix: DataHandler visualizations fix DHIS2-12518

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/DefaultTrackerBundleService.java
The pattern we often use of using a map of TrackerTypes to functions
introduces indirection making the code hard to read. We also rely on a
JAVA EE feature @PostConstruct to build the map once all dependencies
have been wired.
In this case the alternative code is straightforward to read. Removing
@PostConstruct makes unit testing also easier: no need for Spring doing
executing the @PostConstruct or us manually calling initMaps after the
constructor.
I've seen this pattern at least a couple of times in tracker. It feels to smart for me 😅 I always have to re-read/think whats going on even though I've seen the pattern already. I would prefer a more boring, simple style at least in this case.
> chore: reduce indirection in DefaultTrackerBundleService

- dhis-2/dhis-e2e-test/src/test/resources/setup/metadata.json
Recently the metadata files were changed, and we end-up with a set of Data Elements of `domainType` **_TRACKER_** only.
The DataItemQuery endpoint only considers Data Elements with `domainType` _**AGGREGATE**_.
This PR adds back a Data Element of type **_AGGREGATE_**, so tests will pass again.
> fix: Add back a data element with domainType=AGGREGATE

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
This was just a logic flip - the goal was to automatically use `headless` when paging is off.
> fix: headless and paging in datastore [DHIS2-12329]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/OutputFormatter.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/AnalyticsControllerTest.java
This fixes the scientific notation output for large numbers.
Instead of exporting the values using _scientific e notation_, we export numbers in the regular representation. ie:
Instead of outputting this -> `3.456E11`, we will output this -> `345600000000`
This bug shows up during the export of analytics responses.
> fix: Avoid scientific notation on export [DHIS2-12543]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
* removed param unused `TrackerIdScheme identifier`
* gave `map` and `str` more meaningful names `identifier(s)` so don't be confused in the diff. The above `TrackerIdScheme identifier` is not the same as the `String identifier` that is left.
TrackerIdScheme identifier in
`private <T> void addIdentifier( Map<Class<?>, Set<String>> identifiers, Class<T> klass, String identifier )
`
is effectively unused.
The only effect on behavior it could have is that we do not add the identifier
to the map of identifiers. That would only be the case if the parameter is null,
which it never is. All identifiers in the params have a default of UID.
Of course someone could set them to null, but that would cause all sorts of other
bugs that we will notice.
I stumbled on this piece of code when looking for …
> chore: TrackerIdScheme parameter is unused

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/BaseDimensionMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/DimensionFilteringAndPagingService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/DimensionMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/DimensionMapperService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/mappers/BaseDimensionalObjectMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/mappers/DataElementMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/mappers/ProgramStageDataElementMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EnrollmentAnalyticsController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/DimensionFilteringAndPagingServiceTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/DimensionMapperTestSupport.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/analytics/dimension/mappers/DataElementMapperTest.java
now **enrollments** dimension endpoint return dimensions of type `DATA_ELEMENT` like this:
```
{
valueType: "NUMBER",
dimensionType: "DATA_ELEMENT",
...  
id: "A03MvHHogjR.a3kGcGDCuk6",
...
}
```
while **events** one returns `DATA_ELEMENTS` like this:
```
{
valueType: "TEXT",
dimensionType: "DATA_ELEMENT",
...
id: "oZg33kd9taw",
...
}
```
This pull request formats `id`s in events dimension endpoint in the same format as enrollments, i.e. 
`{program_stage_uid}.{data_element_uid}`
> feat: data elements id in events dimension endpoints are now returned as PS_ID.DE_ID [DHIS2-12569]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeStoreIntegrationTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/job/TrackerTrigramIndexingJobTest.java
it looks like `org.junit.Test` annotated tests are not executed on GH pipeline.
This PR migrates them to use JUnit 5
> test: migrate tests to use junit 5 annotations [TECH-969]

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParams.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterParser.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterSimpleBeanPropertyFilter.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldTransformer.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/transformers/IsEmptyFieldTransformer.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/transformers/IsNotEmptyFieldTransformer.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/transformers/PluckFieldTransformer.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/transformers/RenameFieldTransformer.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/transformers/SizeFieldTransformer.java
Small fix for `FieldFilterService` that makes sure that the `FilterProvider` is set on a fresh copy of `ObjectMapper` (pre-configured for field filtering).
> fix: make local copy for object mapper filter provider

- dhis-2/pom.xml
See [DHIS2-12104](https://jira.dhis2.org/browse/DHIS2-12104). The `d2:addDays` function was returning an error when trying to get the description, because it was expecting the second argument to be a date instead of a number.
The fix is to the `dhis2-rule-engine` here in [dhis2-rule-engine/pull/80](https://github.com/dhis2/dhis2-rule-engine/pull/80). This PR just updates the rule engine version to 2.0.33 and the expression parser version to match what is used by this rule engine version.
Building with this version of the rule engine fixes the problem reported in [DHIS2-12104](https://jira.dhis2.org/browse/DHIS2-12104).
> fix: d2:addDays description parsing DHIS2-12104

- dhis-2/pom.xml
After enabling them to allow the reporting of test-coverage, the general feedback is that the check takes such a long time, it's blocking developers waiting for merge pull requests. Until we find a better automated way of reporting test coverage, the tests will be skipped again to speed up the review and merge process.
> chore: Skip tests for sonarqube check

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/events/EventExportTests.java
Event export tests didn't have enough assertions and missed a bug - https://jira.dhis2.org/browse/DHIS2-12494. A good example of how important is to get the assertions right. :)
> test: adds body size validation

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/RequestIdentifierFilter.java
When running a job, scheduled or executed ad-hoc/manually, the log with use the job ID as "session ID" in the logs. 
If the job does not have a UID the job-type is used.
Here an example from a manual test run:
UID:pCXKSlDLDkP * INFO  2022-02-08T16:44:41,827 Create SQL views (NotificationLoggerUtil.java [taskScheduler-2])
I think in some cases the job itself is created ad-hoc (in a controller) in which case it does not have an ID as it never gets stored. Therefore I added a fallback to the job type. I did not test this but this then should look like this:
TYPE:RESOURCE_TABLE * INFO  2022-02-08T16:44:41,827 Create SQL views (NotificationLoggerUtil.java [taskScheduler-2])
I decided to not use the constant defined in `RequestIdentifierFilter` to avoid the dependency consequences.
Still I did …
> feat: uid or job type as session ID in logs when running async [DHIS2-12538]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/AnalyticsCacheSettings.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableGenerator.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/cache/AnalyticsCacheSettingsTest.java
See [DHIS2-12072](https://jira.dhis2.org/browse/DHIS2-12072). This PR:
- Always flushes the analytics cache after an analytics update
- Doesn't change how the cache settings affect the browser Cache-Control
- For cache mode `FIXED`, sets the internal analytics cache time to 2 weeks unless the strategy is `NO_CACHE`
- Doesn't change how cache mode `PROGRESSIVE` works
I chose 2 weeks for a fixed cache time instead of infinite, because 2 weeks is likely to be longer than until the next analytics update, and if it isn't (such as on a static demo system) this ensures that all cache entries will eventually age out (including any unpopular ones).
I haven't made more radical changes at this point, like ripping out all the `PROGRESSIVE` caching logic. We could do that later, or we could do that …
> feat: Flush cache on analytics update DHIS2-12072

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PredictorGroupController.java
See [DHIS2-12092](https://jira.dhis2.org/browse/DHIS2-12092).
This adds a POST predictor group API endpoint `/predictorGroups/{uid}/run` to allow all predictors in a group to be run immediately.
This provides similar functionality to the API endpoint `/predictors/{uid}/run` that allows an individual predictor to be run immediately.
This code passes the test described in [DHIS2-12092](https://jira.dhis2.org/browse/DHIS2-12092) in the **Testing suggestion** comment.
> feat: Add predictorGroups/{uid}/run DHIS2-12092

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobConfigurationService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerTest.java
There were two issues here:
1. I missed to declare the parameters class for the `DATA_INTEGRITY` constant in `JobType` enum
2. I used field annotations but the processing of properties in job parameters did only consider method level annotation of `@JsonProperty`
The processing was changed so that it now considers both method and field level annotations. The `@JsonProperty` annotation was purely used as a filter to find the properties that should be included.
> fix: provide data integrity check job configuration parameters metadata [DHIS2-12286]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramStageTemplateVariable.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/notification/ProgramTemplateVariable.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramNotificationMessageRenderer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/notification/ProgramStageNotificationMessageRenderer.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultTrackerNotificationWebHookService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/notification/TrackerNotificationWebHookServiceTest.java
PR will add support for some additional template variables
```
ENROLLMENT_ORG_UNIT_NAME( "enrollment_org_unit_name" )
ENROLLMENT_ORG_UNIT_CODE( "enrollment_org_unit_code" )
```
Besides, that web request payload will now contain data elements and tracked entity attributes depending upon the object the web request was attached to i.e either `ProgramIntance` or `ProgramStageInstance`
> feat: Add DataElement/TEA support for web_hook notifications[DHIS2-12576]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
https://jira.dhis2.org/browse/DHIS2-12347
When the org unit is null for psi on DB, we do not validate the user authorization and add a warning.
> fix: Exception:OrganisationUnit can't be null - [ DHIS2-12347 ] [ 2.38 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DataValidationTask.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/AnalyticsValidationServiceTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/DataValidationTaskTest.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/validation/ValidationServiceTest.java
`ExpressionService.getExpressionValue` had 3 overloads with 2, 10, and 13 parameters, respectively.
This PR creates the class `ExpressionParams` to build the parameters for `getExpressionValue`, and reduces the three overloads to a single method `getExpressionValue( ExpressionParams exParams )`.
Mostly the callers were just mechanically refactored to use `ExpressionParams.builder()` to make the calls. However in a couple of cases parameters have been omitted in the call where they are now supplied by default.
> refactor: Create ExpressionParams

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/jwt/Dhis2JwtAuthenticationManagerResolver.java
This PR adds the ProgramStage `uid` as a prefix to the DataElement item in the response of `/analytics/enrollments/query`
GET request example:
```
http://localhost:8080/dhis/api/29/analytics/enrollments/query/IpHINAT79UW.json?dimension=pe:LAST_3_MONTHS&dimension=ou:ImspTQPwCqd&dimension=ZzYYXq4fJie.X8zyunlgUfM&dimension=A03MvHHogjR.X8zyunlgUfM&displayProperty=NAME&outputType=ENROLLMENT&desc=enrollmentdate&pageSize=100&page=1
```
Before this change the response of the request above would look like:
```
{
"name": "X8zyunlgUfM",
"column": "MCH Infant Feeding",
"valueType": "TEXT",
"type": "java.lang.String",
"hidden": false,
"meta": true,
"optionSet": "x31y45jvIQL"
},
{
"name": "X8zyunlgUfM",
"column": "MCH Infant Feeding",
"valueType": "TEXT",
"type": "java.lang.String",
"hidden": false, …
```
> feat: ProgramStage prefix to dataElement in enrol. response [TECH-972]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/jwt/Dhis2JwtAuthenticationManagerResolver.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportParamsBuilder.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportParamsBuilderTest.java
we missed passing the params for
categoryOptionComboIdScheme
categoryOptionIdScheme
to the importer. This was the reason why query params for these metadata
types had no effect on matching in the import process.
> fix: put AOC, CO specific idSchemes in params DHIS2-12282

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportParamsBuilder.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TrackerImportParamsBuilderTest.java
we missed passing the params for
categoryOptionComboIdScheme
categoryOptionIdScheme
to the importer. This was the reason why query params for these metadata
types had no effect on matching in the import process.
> fix: put AOC, CO specific idSchemes in params DHIS2-12282 [2.37]

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSectionServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityAttributeStoreIntegrationTest.java
- dhis-2/pom.xml
We only write JUnit 5 tests on master. Support for JUnit 4 has therefore been removed.
https://github.com/testcontainers/testcontainers-java/issues/970 does not allow us to easily remove
JUnit 4 entirely. Fail the build to prevent JUnit 4 tests from being added and not run without us noticing.
* fails for example when using JUnit 4 assertions with error message
```
[INFO] --- maven-enforcer-plugin:3.0.0:enforce (enforce-maven) @ dhis-service-core ---
[WARN] Rule 4: org.apache.maven.plugins.enforcer.RestrictImports failed with message:
Banned imports detected in TEST code:
Reason: Write JUnit 5 tests only; JUnit 4 cannot yet be excluded from our dependencies because of testcontainers issue https://github.com/testcontainers/testcontainers-java/issues/970
in file: …
```
> chore: prevent JUnit 4 tests & assertions being merged

- dhis-2/dhis-e2e-test/pom.xml
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/SystemActions.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/aggregate/DataImportTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadata/metadata_import/MetadataImportTest.java
Async data value import test is sometimes flaky due to taskSummaries not being available immediately after the job is completed. Since it sounds like this is well-known behavior, adding a wait for taskSummaries.
> test: adds await to task summary requests

- .github/workflows/run-api-tests.yml
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/analytics/AnalyticsDimensionsTest.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/matchers/CustomMatchers.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/mappers/BaseDimensionalItemObjectMapper.java
One analytics test has been failing on master for a while. Previously, we returned only data element ids when calling
`/analytics/events/query/dimensions?programStageId=PaOOjwLVW23&filter=dimensionType:eq:DATA_ELEMENT`. Now, we return program stage id as a prefix. 
```
AnalyticsDimensionsTest.shouldOnlyReturnDataElementsAssociatedWithProgramStage:182 1 expectation failed.
[36me2e-test_1  |[0m JSON path dimensions.id doesn't match.
[36me2e-test_1  |[0m Expected: every item is one of {"ZrqtjjveTFc", "BuZ5LGNfGET", "mB2QHw1tU96"}
[36me2e-test_1  |[0m   Actual: [PaOOjwLVW23.ZrqtjjveTFc, PaOOjwLVW23.BuZ5LGNfGET, PaOOjwLVW23.mB2QHw1tU96]
```
removed  DataElement from BaseDimensionalItemObjectMapper.java since data element now has its own mapper and several mappers supporting data element was …
> test: fix failing analytics test

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobConfigurationService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerTest.java
After communication with Birk from FE we concluded that it would be good if the job parameter info also contained the constants for enum fields similar to the schema endpoint. 
The reason this isn't already the case is that the extraction of `Property` objects for job parameters is not the same code that the `Schema` uses. It is particularly made for job parameters and just reuses the `Property` class as a container.
This PR adds constants to the `Property` info if
* the value type of the field is an `enum` `Class`, or if
* the field is a collection of `enum` values
Currently (in master) there is only one case of enums being used.
Another one will be added by #9807 for which this feature is intended.
> feat: add enum constants to job parameters info [DHIS2-12637]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/Preheat.java
- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/attribute/AttributeServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/attribute/AttributeValueServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/IdentifiableObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/GeoJsonAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/GeoJsonAttributesCheckTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/GeoUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
- dhis-2/pom.xml
https://jira.dhis2.org/browse/DHIS2-12328
- Add `ValueType.GEOJSON`
- User can create new `Attribute` in maintenance app and select valueType = `GeoJSON`
- Currently user can assign `GeoJSON` attribute to all metadata object. Maybe we should consider to validate this and allow only certain object types.
- GeoJson value will be validated by metadata import service. The validations  is based on this [GeoJson specification](https://datatracker.ietf.org/doc/html/rfc7946)
- The attributeValue will be returned from api as below
```json
{
"attributeValues":
[
{
"value": "{ \"type\": \"Polygon\", \"coordinates\":[ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ], [ [100.8, 0.8], [100.8, 0.2], [100.2, 0.2], [100.2, 0.8], [100.8, 0.8] ] ] }",
"attribute":
{
"id": …
```
> feat: add GeoJson metadata attribute value type

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
I forgot to add the 
```java
@JsonSubTypes.Type( value = DataIntegrityJobParameters.class, name = "DATA_INTEGRITY" )
```
to the getter in `JobParameters` when I added the `DataIntegrityJobParameters`.
This PR fixes this.
> fix: storage of data integrity job parameters

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/enrollments_te_enrollments-data-delete.json
When we delete enrollments, a basic payload with uid is required. All the other info should be retrieved by pre-fetched entities (program, ou, and tei).
For ou, similarly to [12347](https://jira.dhis2.org/browse/DHIS2-12347), we allow ou to be null and log a warning.
Fixed also missing mapper for sharing in program and programinstance
> fix: Missing errorReports when using DELETE strategy and validation fails [ DHIS2-11300 ]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityDetails.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegritySummary.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/DataIntegrityJobParameters.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/hibernate/HibernateDataIntegrityStore.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/jobs/DataIntegrityJob.java
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_no_options.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityServiceTest.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonDataIntegrityDetails.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonDataIntegritySummary.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataIntegrityDetailsControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataIntegrityReportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataIntegritySummaryControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataIntegrityController.java
On high level this adds caching to the data integrity checks.
But this has a number of consequences in the details.
The `GET` API now reads from the cache but does not trigger the checks.
To trigger the checks a `POST` is send to the same URL as reading cache.
As the computation triggered by a `POST` is now asynchronously performed by an ad-hoc scheduled job, calling `GET` directly after is likely not to find the results in the cache yet. Therefore a `timeout` parameter was added to the cache access API so that you can poll with some server side waiting (if wanted).
The idea here was that we could block wait on the cache and return as soon as the data is provided by the asynchronous computation. However, for now I did not implement block wait as the redis cache would not support it. …
> feat: cached data integrity checks [DHIS2-12599]

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
Revert the [PR#9078](https://github.com/dhis2/dhis2-core/pull/9078) because it causes a regression issue [DHIS2-12468](https://jira.dhis2.org/browse/DHIS2-12468) and [DHIS2-12636](https://jira.dhis2.org/browse/DHIS2-12636)
PR#9078 tried to fix [DHIS2-8868](https://jira.dhis2.org/browse/DHIS2-8868), but currently I can't reproduce this issue after revert the fix.
I think we should merge this first to fix DHIS2-12468 , then QA can check if DHIS2-8868 still happen then I can investigate and create another PR to fix that.
> fix: attribute id is missing in api response (#9651)

- dhis-2/dhis-web/dhis-web-apps/pom.xml
The old version (8.11.1) does not have an alternative for the arm64 cpu. As a result, building the dhis-web-apps module on newer laptops with these cpus, will result in a 404 error and fail.
The new version, 16.13.2, have been tested by @varl , and supports the arm64 cpus
> fix: Update nodejs version to support newer computers

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/interpretation/Interpretation.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/EventChart.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/InterpretationController.java
This is about making new Interpretations also available in deprecated entities (EventReport and EventChart)  when saved through the new EventVisualization endpoint.
The opposite should also be true. When an Interpretation is saved in EventChart or EventReport it should also be present in EventVisualization.
This is being requested to keep backward/forward compatibility between EventVisualiztion and the deprecated entities (EventReport and EventChart).
> feat: Make interpretations backward compat. [DHIS2-12645]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportCount.java
Guess I auto-completed to the wrong variable. `imported` should have been `ignored`.
> fix: total count data value set import [DHIS2-12180]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemSettingController.java
The problem here was that the endpoint path was mapped twice and depending on what a browser would send by default in its `Accept` header one or the other would win. I think the JSON returning one was given the `produces` with HTML for that reason so that it would win. But it  never actually return HTML - always JSON. 
After discussion in Slack we decided to remove the JSONP endpoint resolving the ambiguity.
Does cover the method, did not need adjustment.
* `GET /api/systemSettings` without setting any headers in a browser should get you JSON
* `GET /api/systemSettings` without setting any `Accept` header at all in a REST tool should get you JSON
https://github.com/dhis2/dhis2-releases/pull/72
> fix: system settings JSON as default [DHIS2-12516]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseDimensionalItemObject.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ParserUtils.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/FunctionAggregationType.java
See [DHIS2-4530](https://jira.dhis2.org/browse/DHIS2-4530). Add the function `.aggregationType()` to override the aggregation type of a `DataElement` or other `BaseDimensionalItemObject` when fetching values in an indicator expression.
While I was adding test cases, I added them also for recent functions `.minDate()` and `.maxDate()`, only to discover that Exceptions were not properly caught, so I fixed that too. (The code calls a method that calls `safeParseDateTime` which, as the name would not imply, does not catch Exceptions if the date format is invalid.)
In addition to the code passing the unit tests, it passes the "Testing Suggestions" from [DHIS2-4530](https://jira.dhis2.org/browse/DHIS2-4530).
> feat: Add .aggregationType() override DHIS2-4530

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
This is needed in order to enable sorting by `dataElement.programStage`.
For events and enrollments.
Request example:
```
http://localhost:8080/dhis/api/29/analytics/enrollments/query/IpHINAT79UW.json?dimension=pe:LAST_12_MONTHS
&dimension=ou:jUb8gELQApl;TEQlaapDQoK;eIQbndfxQMb;Vth0fbpFcsO;PMa2VCrupOd;O6uvpzGd5pu;bL4ooGhyHRQ;kJq2mPyFEHo;fdc6uOvgoji;at6UHUQatSo;lc3eMKXaEfw;qhqAxPSTUXp;jmIPBj66vD6&dimension=A03MvHHogjR.wQLfBvPrXqq
&dimension=A03MvHHogjR.bx6fsa0t90x
&stage=A03MvHHogjR
&displayProperty=NAME
&outputType=ENROLLMENT
&pageSize=100
&page=1
&desc=A03MvHHogjR.wQLfBvPrXqq
```
**NOTE**
_I also fixed other points of the code that could potentially cause NPE._
> feat: Sort D.Elements across P.Stages [DHIS2-12662]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/RepeatableStageParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultQueryItemLocator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/RepeatableStageParamsHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/queryItem/QueryItemLocatorTest.java
There is bug in headers, the separator had t be changed, now it is ~. Comma is not possible to use, cause we are using it for options, headers, etc separator.
> New syntax of repeatable stages in headers [2.38-DHIS2-12683]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultQueryItemLocator.java
This PR will make the `headers` and `metaData.dimensions` attributes aligned regarding elements that contain a program stage associated.
For example, the request below will produce the following response:
```
http://localhost:8080/dhis/api/29/analytics/events/query/eBAyeGv0exc.json?dimension=pe:LAST_12_MONTHS
&dimension=ou:ImspTQPwCqd
&dimension=Zj7UnCAulEk.K6uUAvq500H
&stage=Zj7UnCAulEk
&displayProperty=NAME
&outputType=EVENT
&desc=eventdate
&pageSize=100
&page=1
```
Response
```
{
"headers": [
...
{
"name": "Zj7UnCAulEk.K6uUAvq500H",
"column": "Diagnosis (ICD-10)",
"valueType": "TEXT",
"type": "java.lang.String",
"hidden": false,
"meta": true,
"optionSet": "eUZ79clX7y1"
}
],
"metaData": {
...
"dimensions": {
...
"Zj7UnCAulEk.K6uUAvq500H": [
"pLrxOwjko48",
"x3eYha2WVJW",
"mazaKtotbGR"
] …
```
> feat: Prefix p.stage in metadata element [TECH-982]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/PredictorDeletionHandler.java
Also prevent CC deletion when there is a linked COC linked to a predictor.
1. create a new CC
2. create a new DE linked to the CC
3. create a new predictor linked to the new DE and also select a _output category option combo_ after selecting the _output data element_
4. try to delete the CC => should point out it is linked to a predictor
5. delete the predictor
6. try to delete the CC => now should be possible to delete
Rerun the above test but without selecting anything in the predictors _output category option combo_ field - the attempt to delete the CC in step 4 should now succeed directly.
> fix: prevent category combination deletion when predictor is linked [DHIS2-10687]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerReportUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerReportUtilsTest.java
[DHIS2-11947](https://jira.dhis2.org/browse/DHIS2-11947) couldn't be reproduce as the date was always present but the format was not the same that it is used in the payload
> fix: Return dates in NTI report with Iso8601NoTz format [DHIS2-11947]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerRelationshipCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationships/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerRelationshipCriteriaTest.java
* add query parameter `trackedEntity` (keeping parameter `tei` for backwards compatibility) to adhere to the new tracker APIs consistent naming
* fail if more than one of the mutually exclusive parameters (`trackedEntity`, `tei`, `enrollment`, `event`) is given as described in the API docs
No parameters leads to response
```json
{
"httpStatus": "Bad Request",
"httpStatusCode": 400,
"message": "Missing required parameter 'trackedEntity', 'enrollment' or 'event'."
}
```
More than one parameter leads to response
```json
{
"httpStatus": "Bad Request",
"httpStatusCode": 400,
"message": "Only one of parameters 'trackedEntity', 'enrollment' or 'event' is allowed."
}
```
Since we already have code dealing with `trackedEntity`, `enrollment`, `event` in a …
> fix: consistent and unsurprising query param behavior tracker/relationships DHIS2-12659

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_36__Drop_users_table.sql
Update the users migration. Removes deletion statements as they are likely to fail in many instances. Sets primitive properties to default values for users which are in an invalid state due to no match in userinfo table during the merge.
> fix: Update users migration

- dhis-2/pom.xml
A while back I released version 0.2.0 of the JSON tree library. 
Mainly it rounds of some ends and introduces the JSON builder API in an accessible way. 
I just didn't switch core to the new version right away as I got distracted with other task while waiting for the artefact to become available in maven central.
> chore: use newest version of json-tree (with builder)

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/ImportStrategyAccumulatorTest.java
- dhis-2/dhis-services/dhis-service-program-rule/pom.xml
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/ProgramRuleEngine.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/SupplementaryDataProvider.java
- dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/engine/ProgramRuleEntityMapperServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/AbstractTrackerPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/persister/EventPersister.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EnrollmentTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AbstractRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentDateValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentGeoValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventGeoValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/pom.xml
I merged a previous PR and I forgot to exclude the dependencies that we talked about so I am doing it in this PR.
I managed to completely exclude `org.wildfly.common:wildfly-common`.
It is a utility library that we shouldn't use, so it make sense that is not present in the build.
I tried to do the same with `com.google.http-client:google-http-client` because we use some utils from this library as well but it turns out that we cannot really exclude it as it is in the Authentication process.
So in this case I just banned `com.google.api.client.util.**` imports
> chore: Clean up service program rule module [TECH-938]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerRelationshipCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/relationships/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerRelationshipCriteriaTest.java
backport of #9857
* fix: only allow one of the 3 query parameters
as outlined in the API documentation
* chore: create unified getter
to abstract away the specific query parameter where the identifier came
from. Ensure exactly one is set.
* fix: add query param trackedEntity
* chore: remove redundant tests
> fix: consistent and unsurprising query param behavior tracker/relationships DHIS2-12659 [2.37]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/GeoJsonAttributesCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/GeoJsonAttributesCheckTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GeoFeatureControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/GeoFeatureController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/GeoFeatureService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/service/GeoFeatureServiceMockTest.java
https://jira.dhis2.org/browse/DHIS2-12654
1. This PR add a new parameter `coordinateField` to the controller `GeoFeatureController`
- If the `coordinateField` is not provided, then coordinates will be retrieved from `geometry` property of the OrganisationUnits.
- If the `coordinateField` parameter is present, then coordinates will be retrieved from GeoJson Attribute value of the OrganisationUnits. If the attribute value is null, then it will fallback to the `geometry` property value.
2. I have moved the business logics code from `GeoFeatureController` to new service class `GeoFeatureService`
3. Also updated the validation for GeoJsonObject import, add new error code for the cases of unsupported GeoJson type.
> feat: make api geoFeatures to support GeoJsonObject

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/GeoFeatureController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/GeoFeatureService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/service/GeoFeatureServiceMockTest.java
- Add Content-type to the `ResponseEntity`
- Remove the logic of fallback to `geometry` property if GeoJSON Attribute value is null. ( feedback from Bjorn )
- Update unit test.
> fix: remove fallback geometry property for /api/geoFeatures

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
The issue addressed here was clarity of what had happened when a job process failed.
A manual cancellation would end up in state `CANCELLED` but when an item would fail causing state `ERROR` for the item the stage would automatically also abort. The control flow here was as intended but the way this aborting worked is by forcing a cancel using a `CancellationException` causing the stage and the process to end up with state `CANCELLED` not `ERROR` even though an exception had triggered this. 
While this could be identified by the item level having last item in state `ERROR` this was confusing or misleading when looking at the higher levels which would indicate `CANCELLED` instead.
The now got addressed by cancel always meaning a manual cancel while "automatic" end of processing after an …
> fix: job scheduler - distringuish between manual cancel and abort after failure [DHIS2-12704]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/PredictorDeletionHandler.java
Cherry-picked from #9870 - did require manual merge to adopt to the old way deletion handlers work.
This needs manual testing so make sure the merge produced code that does the correct thing.
> fix: prevent category combination deletion when predictor is linked [DHIS2-10687] (2.36)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/hibernate/HibernateDataApprovalStore.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreIntegrationTest.java
`DefaultDataApprovalService.isApproved` (with a read-only transaction) was calling down to `HibernateDataApprovalStore.dataApprovalExistsInternal`, which further called to `HibernatePeriodStore.reloadForceAddPeriod` -> `HibernatePeriodStore.addPeriod`. This failed if the approval status was requested for a non-existent period.
`HibernateDataApprovalStore.dataApprovalExistsInternal` has now been refactored to call `HibernatePeriodStore.reloadPeriod` instead of `DefaultPeriodService.reloadPeriod` (which did a "force" restore that tried to create the period if it didn't exist.)
A test has been added to `DataApprovalServiceTest` that fails without the fix and succeeds with it.
> fix: approvalService.isApproved w/o writing

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractEventJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
This is a request from the UI team to have different representations of the display name, depending on the values that are present in the tracker tables.
For the set of rules see TECH-996.
This will basically concatenate the `name`, `last name`, and `username` during the analytics table export. It will allow the sorting of those columns by their content/value, otherwise, it would not be possible.
The endpoints covered are: `/analytics/events/query` and `/analytics/enrollments/query`
**NOTE**
_With this solution, the user will not be able to know if he/she is seeing the name, last name or username in certain cases. Even knowing this limitation, the decision was to keep this logic/implementation._
> feat: Support display names in different forms in events [TECH-996]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdSchemes.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/SpringDataValueSetStore.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueSetControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
This was a fix for a forgotten filter feature on SQL level that turned into 3 bug-fixes.
1. The original missing filtering for data element groups. The API accepts the `dataElementGroup` parameter but it is never used in the SQL
2. When trying to use different input schema for the data element group I found the getter `getDataElementGroupIdScheme` on the schema object was using the wrong field so the property would always be `UID`
3. because of the way writing directly to the HTTP response works once you started that you cannot back out. This means the validation of the parameters needs to be done before that so we can back out and have a 409 _Conflict_ returned. This meant I needed to change the controller slightly just to give the operations the proper order
Moving the validation to be …
> fix: data value set export by data element group [DHIS2-12691]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
This fixes an issue where enrollments that have `enrollmentdate` equals "today" are being ignored.
This uses the same approach/fix in master.
> fix: Today's date enrollments are ignored [DHIS2-12677]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/PredictionDataValueFetcher.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/predictor/PredictionDataValueFetcherTest.java
See [DHIS2-12702](https://jira.dhis2.org/browse/DHIS2-12702). Data elements may appear in an expression by themselves like #{deuid}, resulting in a `DataElement` reference, or with a category option combo like #{deuid.cocuid} resulting in a `DataElementOperand` reference. The code in question needs to create a single map of `DataElement` uid -> `DataElement` from both kinds of references, to know which data elements to fetch from the database.
The bug was in the statement that streamed the data element operand references and created a map of `DataElement` uid -> the `DataElement` part of the `DataElementOperand`. The problem was that when multiple `DataElementOperands` referenced the same `DataElement`, it would get a duplicate key error when generating the map.
The solution is to first …
> fix: Predictors with multiple disaggs DHIS2-12702

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdSchemes.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/SpringDataValueSetStore.java
Backport to 2.36 based on cherry-pick of #9932
Manual merge was needed as the `dataElementGroupIdScheme` field did not exist in 2.36.
Also the updated test did not exist in 2.36 so these modifications were ignored.
>  fix: data value set export by data element group [DHIS2-12691] (2.36)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/config/SmsGatewayConfig.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/outbound/GatewayResponse.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SmsGateway.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/config/SmsMessageSender.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/sms/SmsMessageSenderTest.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_38__Updates_Sms_Config.sql
[DHIS2-12590](https://jira.dhis2.org/browse/DHIS2-12590)
Default SMS length added as system key. Also added a maxSmsLength property for the gateway that can be set, otherwise default system one is used.
Message column in outbound_sms table it now text
> fix: Sms configuration update [ DHIS2-12590 ] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
This fix deprecates `NE`, and adds `NEQ` so we can follow the same standard as others operators and allows the usage of `!EQ` by the client.
> fix: Support NEQ operator [TECH-1012]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryFilter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryOperator.java
This operator was not working properly because of a missing `!` mark.
This is now fixed.
Example of GET URL:
```
http://localhost:8080/dhis/api/28/analytics/events/query/ur1Edk5Oe2n.json?dimension=pe:LAST_12_MONTHS&dimension=ou:ImspTQPwCqd&dimension=ZkbAXlQUYJG.FO4sWYJ64LQ:!IEQ:oslo&stage=ZkbAXlQUYJG&displayProperty=NAME&outputType=EVENT&desc=eventdate&pageSize=100&page=1
```
> fix: Typo in NIEQ comparator [TECH-1018]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityAttribute.java
Small fix to prevent a NPE. Another part of the code is invoking `hasLegendSet()` and it's returning true when the list is empty, and this causes an NPE when the invoker try to access `getLegendSet().getUid()`. Ie.: `MetadataItem.java:157`
> fix: NPE because of wrong list checking [TECH-1019]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TranslationsCheck.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
https://jira.dhis2.org/browse/DHIS2-12624
- Currently the `{objectType}/translations` endpoint make use of the importService with `importMode=VALIDATE`. This approach is having issue because the importService modifies the given object although it's a validating process. As a result, we got an error like below when trying to update translations for a `Program`. The error has nothing to do with the translations being updated.
```
Caused by: org.hibernate.HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: org.hisp.dhis.program.Program.notificationTemplates
at org.hibernate.engine.internal.Collections.processDereferencedCollection(Collections.java:100)
at org.hibernate.engine.internal.Collections.processUnreachableCollectio …
```
> fix: can't translate program

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
Fixes a bug where preset expansion would overwrite field transformers.
> fix: don't let presets overwrite explicit fields

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/reservedvalue/hibernate/ReservedValue.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_1__Add_index_to_reserved_value.sql
adds lower case in query and index to reserved value table
> fix: /generateAndReserve returns duplicate values when attribute pattern contains a constant [ DHIS2-12182 ]

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/reservedvalue/hibernate/ReservedValue.hbm.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_44__Add_index_to_reserved_value.sql
see https://github.com/dhis2/dhis2-core/pull/9983
> fix: /generateAndReserve returns duplicate values when attribute pattern contains a constant [ DHIS2-12182 ] [ 2.37 ] 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Grid.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/EventDataQueryRequestTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/ListGrid.java
Calculating total number and page count is a potential performance problem in event analytics '/query' endpoints. Currently the totalPages param is not working and returns the total.
The details for what should be returned are specified in this bug report: https://jira.dhis2.org/browse/DHIS2-12530
> fix: totalPages param does not work in event analytics [DHIS2-12529]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/mapping/MapView.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MapControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/mapping/MapController.java
In https://github.com/dhis2/dhis2-core/pull/9934 we added property `orgUnitField` to `MapView` in database level, which stores an ID of an `Attribute`
Now, client also needs the `Attribute`'s name and doesn't want to send an additional request to server.
This PR add a transient property `orgUnitFieldName` to `MapView`, its value will be set in `MapController#postProcessResponseEntity`
Note that the method `attributeService.getAttribute(id)` is already using a `Cache<Attribute> attributeCache`
```json
"orgUnitFieldName": "testgeojson",
"orgUnitField": "jhqTNk3hS2N",
```
> feat: add orgUnitFieldName to mapView

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/resourcetable/ResourceTable.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/table/DatePeriodResourceTable.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
These changes aim to fix an issue/crash during the analytics tables export.
Currently, we have a limit of years allowed by the analytics table when exporting events.
As you can see below (in the PR), we are limited to dates between 1975 and 2024.
(I'm keeping this behaviour to minimize risks. Ideally, at some point in the future, we need to remove this limitation and stop using the periods' table during the analytics export.)
This fix will basically ensure that we only read events and years that belong to that interval (inclusive).
It will guarantee that no partitions with invalid years (out of that interval) will be created, avoiding joins with the table `_dateperiodstructure` on top of years that do not exist in that same table.
When we try to join using years out of the interval …
> fix: Analytics export crash with invalid dates [DHIS2-12581]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
This is a tricky bug that happens during the analytics partial export.
When the update is partial the code will target the respective partition and will skip the master table. This is the current behaviour.
The problem arises when the table has no partitions (ie. `enrollments`). In such cases, the table export does not update any table (will also skip the master).
So, to fix it, I'm adding an extra condition (`&& table.getTableType().hasLatestPartition()`).
This condition will tell if the current table actually has partitions. If it does not have partitions we need to update the master table, so the data in the analytics enrollment tables get updated.
The client reported that when running analytics export setting `Number of last years of data to include` to `1`, he could see the new …
> fix: Master table population for partial update [DHIS2-12677]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/pom.xml
I changed the version of rule engine to the latest one that fix a problem in the logs. Now we are logging the evaluation of the rules in debug mode as before it was causing a lot of noise in the logs
> fix: bump rule-engine version [DHIS2-12537]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/AnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
When adding a new column to the analytics events table, temporary partition tables are not being attached to the master table.
This happens because the master table is not being recreated if they already exist. So, when we add a new column it will fail at attachment time because the master table does not contain the new column (as it was not recreated).
When this error happens, it also leaves all temporary partitions populated, unattached and named with the "temp" suffixes. They stay in the DB as `orphan` objects.
Whit this PR, the master table will always be updated to ensure it gets any new column being added. It also prevents some SQL commands to fail when they actually could proceed.
These changes aim to fix those bugs and inconsistencies.
**_Backport from master/2.39_**
> fix: Error during partitions generation and swapping [TECH-1028]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
Skip checking event organisation unit in case of event update. Ownership org unit is only required to be checked.
> fix: Event update should only check ownership orgunit for tracker programs [DHIS2-12732] (2.39)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
Add versioning to the tracker APIs (Backport to 2.37). This is already fixed in newer versions.
> fix: Add versioning for new tracker apis

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
This is a small change to bring it back the old behaviour regarding the `metaData` element.
It means that from now on, until the "classic" Event Report table is fully removed, we will need to support both elements as part of the response:
```
...
"metaData": {
"pager": {
"page": 1,
"pageSize": 100,
"lastPage": false
},
"items": {
"A03MvHHogjR.a3kGcGDCuk6": {
"uid": "a3kGcGDCuk6",
"code": "DE_2006098",
"name": "MCH Apgar Score",
"description": "Apgar is a quick test performed on a baby at 1 and 5 minutes after birth. The 1-minute score determines how well the baby tolerated the birthing process. The 5-minute score tells the doctor how well the baby is doing outside the mother's womb.",
"dimensionItemType": "DATA_ELEMENT",
"valueType": "NUMBER",
"aggregationType": "AVERAGE", …
```
> fix: Make metaData element backward compatible [DHIS2-12712]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
This needs investigation why the test is flaky on CI.
For now we disable it so it does not fail CI.
> fix: ignore flaky gist attribute field test (2.38)

- dhis-2/pom.xml
* Excludes `slf4j-simple` from `rule-engine`
[DHIS2-12708](https://jira.dhis2.org/browse/DHIS2-12708)
> fix: exclude slf4j-simple from rule-engine

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseDimensionalItemObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalItemObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObject.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObjectUtils.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryModifiers.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/JdbcAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/QueryPlannerUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceQueryModifiersTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DataDimensionExtractor.java
This PR contains fixes to the new 2.38 indicator expression functions `minDate`, `maxDate`, and `aggregationType` as described in [DHIS2-12836](https://jira.dhis2.org/browse/DHIS2-12836). It is a subset of the code in [pull/9923](https://github.com/dhis2/dhis2-core/pull/9923) (Indicator sub-expressions), as it does not have the new feature, but contains only the fixes to existing (2.38) features.
It also contains the simple `ExpressionParams.samplePeriods` speedup as described in the **Performance** section of [pull/9923](https://github.com/dhis2/dhis2-core/pull/9923). (This speeds up _all_ indicators.)
The fix is as follows (adapted from pull/9923):
While testing subexpressions, a design flaw was discovered that affected these three functions: `DefaultQueryPlanner` correctly made …
> fix: minDate/maxDate/aggregationType DHIS2-12836

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/SystemController.java
Fix for https://jira.dhis2.org/browse/DHIS2-12366
Underlying user issue is caused by information not rendering in browser, e.g. a browser request to `api/system/tasks/ANALYTICS_TABLE` on dev currently returns:
Updating media type resolves the issue:
And will also make corresponding api/system/tasks/ANALYTICS_TABLE/:uid posts visible.
> fix: update media type for [DHIS2-12366]

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/InterpretationControllerTest.java
https://jira.dhis2.org/browse/DHIS2-12843
- Interpretation is not metadata object so its ignored by the FieldFilterService when it try to apply some handler to populate the `access` object.
- This PR replace the `isMetadata()` check with `isIdentifiableObjet()`
- Add a controller test.
> fix: interpretation missing access object from api response

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
We had
```
Repeatable QueryItem1( dataelement1, GT 5, LT 10)
Repeatable QueryItem2( dataelement2, GT 6, LT 11)
QueryItem3( dataelement3, EQ, "test")
```
it was converted into:
```
(DE1>5 OR DE1<10 OR DE2>6 OR DE2<11) and DE3="TEST"
```
now it is like this:
```
((DE1>5 AND DE1<10) OR (DE2>6 AND DE2<11)) AND DE3="TEST"
```
> fix: nested conditions are now always AND [DHIS2-12839]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/DatastoreQueryValidator.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DatastoreController.java
This was twofold:
1. lack of proper validation on the filters - now got extended
2. as we write directly to the HTTP response once that is started we have to use that writer if we want to change the body. Therefore the JSON mapper is used to write a web message to the HTTP output. 
Test with queries as outlined here https://docs.google.com/spreadsheets/d/1DIc3MgzjyQLPpNhMfvXWUbtytxrIvJQWO9ThfpRDbzk/edit#gid=1815828517
> fix: datastore error handling

- dhis-2/pom.xml
This reverts commit afbd1f1b1a63e51f33a01181c7ce8e0672ea3fc1.
Bumping the version was causing a circular dependency
> fix: Revert "chore(deps): bump spring.version from 5.3.13 to 5.3.16 in /dhis-2 (#9858)"

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageMapper.java
Program mapper within the ProgramStageMapper did not map accesslevel, which defaulted to OPEN.
> fix: PSI mapper missing program access level (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionSetObjectBundleHook.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHookTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
https://jira.dhis2.org/browse/DHIS2-12831
There are issues with `OptionObjectBundleHook` and `OptionSetObjectBundleHook`. Both seem overwrite each others.
Fixed and add some controller tests to make sure OptionSets.options imported correctly now.
Feel free to suggest more test cases if any.
> fix: metadata import corrupts option sort order

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageMapper.java
Program mapper within ProgramStageMapper was not mapping accessLevel, which default to OPEN. This created issues during acl checks.
> fix: PSI mapper missing program access level (2.39)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventvisualization/EventVisualizationStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/eventvisualization/hibernate/HibernateEventVisualizationStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/dashboard/impl/DefaultDashboardService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/dashboard/DashboardServiceTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
The `/dashboard/q` endpoint returns analytical objects including EventVisualization which is a combination of EventReport and EventChart. The intention of EventVisualization, at the current stage, is to store line lists only. So the response should contain only EventVisualizations of type LINE_LIST for now.
> feat: Return only LINE_LIST, for EVs in Dashboard search [DHIS2-12871]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datastore/hibernate/DatastoreQueryBuilder.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/JsonWriter.java
Couple of issues:
* root (`.`) path would always use text sorting
* when casting to `double` to cause numeric sorting we first need to cast jsonb to text
Bonus was adding the `nulls last` so any result always lists those matches last that do not have the property ordered by.
Remember the `fields` parameter is needed, just use `fields=.` for all tests.
* add some entries to a new namespace, one entry for each of the following values: `17`, `9`, `4`, `{"age":17}`,`{"age":9}`,`{"age":4}`.
* check `filter=.:gt:1&order=.:nasc` vs. `order=.:asc` vs. `&order=.:nasc` (no filter) => 400 error
* check `filter=.:gt:1&order=.:ndesc` vs. `order=.:desc` vs. `&order=.:ndesc` (no filter) => 400 error
* check `filter=age:gt:1&order=age:nasc` vs. `order=age:asc` vs. `&order=age:nasc` => fine as "nothing" …
> fix: datastore numeric sorting [DHIS2-12748]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
This PR fixes issues with requests to trackedEntityInstances/query when underlying tracked entity attribute values have colons or semi-colons. 
Semicolon for separating pairs of uid:tea_value has been updated to less likely ';@//@;' to avoid collisions.
Colon for separating uid and tea_value has been updated to be split once at the first occurrence.
> fix: update tea query delimiters for [DHIS2-12369]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataWorkflowController.java
There are controller tests using the API with a slash while all annotation no longer have tailing slash.
This should mean both variants work.
> fix: metadata workflow path no longer require tailing slash

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationTemplate.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/notification/SendStrategy.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DataSetNotificationJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationTemplateService.java
Uses the `JobProgress` to track sending the notifications.
While the `SendStrategy` is nullable in the DB I asked Zubair and he said it should always be set. 
Therefore I made a small improvement to set it in `setAutoFields` in case it is null.
Also did a cleanup of the main service that handles the sending which we want to track when I was adding the tracking.
I did not test this job as I have no idea how to set this up. Would be good if @zubaira can make a test run.
> feat: provide job progress for dataset notification job [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObjectUtils.java
See [DHIS2-12874](https://jira.dhis2.org/browse/DHIS2-12874). The visualizations in the ticket had indicators with attribute option combos. The AOC wasn't getting set because a _copy-paste-edit_ change in [pull/10091](https://github.com/dhis2/dhis2-core/pull/10091) missed the _edit_.
With the fix, the visualizations in the ticket work.
> fix: Indicator attributeOptionCombo DHIS2-12874

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastatistics/DataStatisticsService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DataStatisticsJob.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/datastatistics/DataStatisticsServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/datastatistics/DataStatisticsController.java
Adds the `JobProgress` tracking for data statistics job.
A nice by-effect of running the counting though the progress tracking is that should a count fail with an exception that count is just excluded (`null`) from the statistics and other counts are still provided.
* run job manually using `POST` http://localhost:8080/api/jobConfigurations/BFa3jDsbtdO/execute (UID for demo database)
* check output from http://localhost:8080/api/scheduling/completed/DATA_STATISTICS (see below)
* check a database entry was created http://localhost:8080/api/dataStatistics?startDate=2022-03-14&endDate=2023-03-17&interval=DAY (dates should just contain the current day when the new snapshort was created)
Example for tracked info:
```json
[
{
"summary": "Saved data statistics snapshot",
"status": "SUCCESS", …
```
> feat: provide job progress for data statistics job [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventvisualization/SimpleDimension.java
EventVisualization is using the wrong name for the last updated date.
Instead of `lastUpdatedDate`, it should be `lastUpdated`.
> fix: Dimension name in EventVisualization [DHIS2-12891]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceCleanUpJob.java
Adds `JobProgress` tracking to the file resources cleanup job.
* use `/api/jobConfigurations` to find UID of file resources cleanup job
* run the job using `POST` `/api/jobConfigurations/<uid>/execute`
* check http://localhost:8080/api/scheduling/completed/FILE_RESOURCE_CLEANUP output shows success (ideally tested with existing files matched by the job)
Example output
```json
[
{
"status":"SUCCESS",
"completedTime":"2022-03-17T15:20:50.465",
"startedTime":"2022-03-17T15:20:50.347",
"description":"Clean-up file resources",
"stages":[
{
"status":"SUCCESS",
"completedTime":"2022-03-17T15:20:50.448",
"startedTime":"2022-03-17T15:20:50.447",
"description":"Deleting expired file resources",
"totalItems":0,
"items":[
],
"duration":1,
"complete":true
},
{
"status":"SUCCESS", …
```
> feat: job progress tracking for file resource cleanup job [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/SlimPager.java
In the original PR (https://github.com/dhis2/dhis2-core/pull/9719) I forgot to set the name of this attribute, which should be returned as `isLastPage` to the client.
This small fix will address that mistake.
> fix: Wrong name for lastPage element [DHIS2-12895]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
If `CsvWriter` fails (if you selected a complex object that was marked with simple) return a `WebMessage` with `application/json` content type.
[DHIS2-12035](https://jira.dhis2.org/browse/DHIS2-12035)
> fix: give proper webMessage if CSV writer fails

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
Since `runStage` is overloaded the call with `null` as first parameter became ambiguous. To effectively cast the first value to `Integer` and make the call match just one method I extracted the field `errorValue`.
> fix: job progress with default value null needs cast to be unambigious

- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilterServiceTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/TrackedEntityInstanceFilterSchemaDescriptor.java
Set default access to "no access" (access string = "--------") when saving TeiFilters
> fix: Change teiFilters to default private access (2.39)

- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-web/dhis-web-commons/pom.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/encoding/velocity/EncoderVelocityContext.java
- dhis-2/pom.xml
Velocity dependency is not supported anymore and dependabot will not get it to bump the version as it is a different dependency
> chore: Replace unsupported velocity dependency with velocity-engine-core

- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-web/dhis-web-commons/pom.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/encoding/velocity/EncoderVelocityContext.java
- dhis-2/pom.xml
This reverts commit 4d159f7bc0c25baeade38e3d0a20effa8231741c.
Reverting the commit because changing the version requires some fixes on deprecated configurations
> Revert "chore: Replace unsupported velocity dependency with velocity-engine-core (#10236)"

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
https://github.com/dhis2/dhis2-core/pull/10060 changed default fields returned by /trackedEntityInstances
Reason was that the TrackedEntityInstanceSupportService was actually shared between /trackedEntityInstance and /tracker/trackedEntities
Solution: split TrackedEntityInstanceSupportService into an old and new tracker one.
> fix: /trackedEntityInstances default fields DHIS2-12660

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/DefaultSystemSettingManager.java
This fixes a known issue in analytics continuous job.
It's required because the caching layer does not deal with Optionals, so the default value should be handled at the application level (which makes more sense).
> fix: NPE in analytics continuous job [DHIS2-12094]

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEnrollmentsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerEventsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerRelationshipsExportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntitiesExportController.java
as discussed in the design meeting. fields=** was only supported in the NTI export endpoints and does not add any value
> chore: remove fields=** from NTI DHIS2-12660

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/shared/validation/DataValueCheckTest.java
https://jira.dhis2.org/browse/DHIS2-12933
filter null potential options in option set
> fix: Event import fails when data value is an option and sort_order has gaps [ DHIS2-12933 ] 

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/CsvNodeSerializer.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/CsvMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
backport https://github.com/dhis2/dhis2-core/pull/10269
- Add back the CSV metadata export
- Remove `@GetMapping( produces = "application/csv" )     public void getObjectListCsv()` . 
- Request with csv format will go through the old `public @ResponseBody RootNode getObjectList()`.
> fix: add back csv for metadata export(2.38.0)

- dhis-2/dhis-api/pom.xml
- dhis-2/dhis-support/dhis-support-artemis/pom.xml
- dhis-2/dhis-support/dhis-support-audit/pom.xml
- dhis-2/dhis-support/dhis-support-cache-invalidation/pom.xml
- dhis-2/dhis-support/dhis-support-commons/pom.xml
- dhis-2/dhis-support/dhis-support-db-migration/pom.xml
- dhis-2/dhis-support/dhis-support-expression-parser/pom.xml
- dhis-2/dhis-support/dhis-support-external/pom.xml
- dhis-2/dhis-support/dhis-support-hibernate/pom.xml
- dhis-2/dhis-support/dhis-support-jdbc/pom.xml
- dhis-2/dhis-support/dhis-support-system/pom.xml
- dhis-2/dhis-support/dhis-support-test/pom.xml
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/StaticContentControllerTest.java
- dhis-2/pom.xml
There were some leftovers from the support modules clean up. Now `mvn dependency:analyze` returns no warning for support modules.
I needed to add some ignore to make it work and there is probably some discussion in the future around that as some of those dependencies indicate bad smells and they shouldn't be there at all.
> chore: Clean up all support modules to remove all the warnings from analyze [TECH-801]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/importer/shared/validation/DataValueCheckTest.java
see https://github.com/dhis2/dhis2-core/pull/10271
> fix: Event import fails when data value is an option and sort_order has gaps [ DHIS2-12933 ] [ patch/2.38.0 ]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackerTrackedEntitiesExportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackedEntitiesSupportService.java
fixes errors when using fields filter like
/tracker/trackedEntities/PQfMcpmXeFE?fields=enrollments[ou,trackedEntity]&program=IpHINAT79UW
Springs splitting of queryParameter fields into a List<String> and requirement for a Set in the parser lead to the field path being out of order.
> fix: /tracker/trackedEntities?fields with 2 nested fields DHIS2-12660

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.38/V2_38_19__Add_ValueType_column_into_programrulevariable.sql
@zubaira Does it make sense to have `TEXT` as the default value type in case of misconfiguration?
@ameenhere I am just changing the flyway script as it is not released yet. Is that ok?
> fix: Fix program rule variable migration when a misconfiguration is present [DHIS2-12884]

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceQueryModifiersTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationTestBase.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/SingleSetupIntegrationTestBase.java
This PR creates `SingleSetupIntegrationTestBase`, a base class for integration tests that have a single setup for the entire class instead of a setup per test.
The use case for this is for tests that need a resource-intensive setup (such as building analytics tables) that is sufficient for all the tests.
As part of this PR, `AnalyticsServiceQueryModifiersTest` has been refactored to use this base class. In the future, tests such as `AnalyticsServiceTest` and `EventAnalyticsServiceTest` can also be refactored to use this base. This will greatly simplify them and make their test cases much easier to add and maintain.
> refactor: Create SingleSetupIntegrationTestBase

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/SystemUpdateService.java
The system update notification job would fail due to missing hibernate session.
This PR adds the @Transactional annotation to the service method being called in the job.
> fix: Add missing transactional annotation 

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageInstanceFilterSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/TrackedEntityInstanceFilterSchemaDescriptor.java
Implicit Private authority has to be set if the creator of the metadata object has to have the correct "Access" object with correct read/write/update/manage flags on that object.
> fix: set implicit private authority for teiFilters and eventFilters [DHIS2-12925] [DHIS2-12924] (2.39)

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
Once more got confused by HQL join names. This should have been an `inner` not a `left` join.
The issue exists for any type of metadata using gist API on a collection property.
The case that was reported and that I tested was:
* create a new empty user group
* goto `/api/userGroups/<user group ID>/users/gist?fields=name` 
* check you get an empty result (no users) as opposed to a single result of "null null"
> fix: Gist API use inner join for object collection property listings [DHIS2-12972]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
Conditions that don’t work with Time: exactly, is not, after or including, before
api requests
“Exactly”. Expected: return 1 row. Actual: no rows returned. (condition EQ:14.50)
https://debug.dhis2.org/tracker_dev/api/39/analytics/events/query/vBOHFvxlYPJ?dimension=ou%3AUSER_ORGUNIT,Xd6cKnFMO4L.v5e0tyyxNq6%3AEQ%3A14.50&headers=ouname,eventdate,Xd6cKnFMO4L.v5e0tyyxNq6&totalPages=false&eventDate=LAST_12_MONTHS&displayProperty=NAME&outputType=EVENT&pageSize=100&page=1&includeMetadataDetails=true&asc=ouname
“Is not” Expected: returns 5 rows. Actual: 6 rows returned (condition !EQ:14.50)
https://debug.dhis2.org/tracker_dev/api/39/analytics/events/query/vBOHFvxlYPJ?dimension=ou%3AUSER_ORGUNIT,Xd6cKnFMO4L.v5e0tyyxNq6%3A!EQ%3A14.50&headers=ouname,eventdate,Xd6cKnFMO4L.v5e0tyyxNq6&totalPages=false&e …
> fix: Conditions: time with "before" conditions returns values matching "before or including" [2.39-DHIS2-12985]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/analytics/dimension/mappers/BaseDimensionalItemObjectMapper.java
Small fix to bring the `optionSet` as part of the response for TrackedEntityAttribute.
> fix: Missing optionSet for TrackedEntityAttribute [DHIS2-12959]

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsTestUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
This refactor makes `AnalyticsServiceTest` easier to maintain and extend. It keeps exactly the same test cases as before. Other tests may be added in the future in a much simpler way.
There were formerly four tests. (Each caused all the analytics tables to be rebuilt):
1. `queryValidationResultTable` counted the validation results in analytics.
2. `testMappingAggregation` covered many test cases, so as not to rebuild the analytics tables for each case. It used the _dataQueryParams_ map (keyed by a string test case name) to hold parameters that could be passed to `analyticsService.getAggregatedDataValueMapping( DataQueryParams params )`. The output was compared with the _results_ map using the same key. It also used the _analyticalObjectHashMap_ map for three test cases that also tested …
> refactor: Overhaul AnalyticsServiceTest

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/Dhis2EnvCompatibilityCheck.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DisEnvCompatibilityCheck.java
Intent here is to check at startup if the java version is sufficient to run DHIS2.
The odd thing is that usually a JVM should already reject running `.class` files compiled for a target to does not support.
Not sure how anyone gets past that point but this might be early enough to detect it and end with an error message that is helpful.
Needs testing by those that have the issue. I don't know how they got to have it.
> feat: check DHIS2 is running on JDK 11+ [DHIS2-12931]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramOrgUnitsSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceTest.java
We should not expose our collections using getters that do not make copies (ideally the elements themselves would be immutable as well).
* remove `@Getter` from TrackerPreheat.map
* enable a TrackerPreheat integration test
> chore: prevent mutation of TrackerPreheat.map DHIS2-12563

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/ColumnAndAlias.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
Analytics events aggregated queries are failing because of invalid aliases.
Aggregated queries should always be treated as `group by` queries.
**_NEEDS APPROVAL FROM THE RELEASE CONTROL TEAM._**
> fix: Aggregated queries using wrong aliases [DHIS2-12947]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ParserUtils.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/FunctionRemoveZeros.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/literal/NullLiteral.java
- dhis-2/pom.xml
This PR implements the `null` expression keyword and the `removeZeros()` expression function as defined in [DHIS2-8061](https://jira.dhis2.org/browse/DHIS2-8061).
The `null` keyword is used when the user wants to show a blank result for an indicator or return a _missing value_ for a predictor or validation rule.
The `removeZeros()` function is used when the user wants to show a blank result instead of a zero for an indicator calculation, or return a _missing value_ instead of a zero for a predictor or validation rule. The expression:
```
missingValue( some calculation )
```
is equivalent to
```
if ( some calculation == 0, null, some calculation )
```
but it doesn't require that _some calculation_ be repeated in the expression.
In addition to passing the unit tests, the code has been …
> feat: add null and removeZeros() DHIS2-8061

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/indicator/IndicatorDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/indicator/IndicatorDeletionHandlerTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/DefaultValidationRuleService.java
In coordination with @jbee, this is a more complete fix for [DHIS2-11100](https://jira.dhis2.org/browse/DHIS2-11100) than the "quick fix" PR [pull/10292](https://github.com/dhis2/dhis2-core/pull/10292).
Changes:
1. In `IndicatorDeletionHandler.allowDeleteDataElement`, all that is needed is to check for the data element UID in all the indicator formulas. To accomplish this, the `ExpressionService` method `getExpressionDataElements` was changed to `getExpressionDataElementIds` so that it just returns the `DataElement` UIDs without finding the corresponding `DataElement` objects.
2. `IndicatorDeletionHandler.allowDeleteDataElement` now just checks the data element UID against those found in each indicator. The method was also simplified.
3. Other uses of the changed `ExpressionService` …
> perf: speed dataElement deletes DHIS2-11100

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/indicator/IndicatorDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/indicator/IndicatorDeletionHandlerTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/DefaultValidationRuleService.java
* perf: speed dataElement deletes DHIS2-11100
* fix: apache.commons.collections -> collections4
* fix: Remove unnecessary stubbing
* fix: Rename testGetExpressionDataElements -> testGetExpressionDataElementIds
(cherry picked from commit 8f8047d4ebfc480a961dfbaa9028751be8b0bb10)
> perf: speed dataElement deletes DHIS2-11100 (#10302)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/indicator/IndicatorDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/indicator/IndicatorDeletionHandlerTest.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/DefaultValidationRuleService.java
* perf: speed dataElement deletes DHIS2-11100 (#10302)
* perf: speed dataElement deletes DHIS2-11100
* fix: apache.commons.collections -> collections4
* fix: Remove unnecessary stubbing
* fix: Rename testGetExpressionDataElements -> testGetExpressionDataElementIds
(cherry picked from commit 8f8047d4ebfc480a961dfbaa9028751be8b0bb10)
* fix: retrofit IndicatorDeletionHandlerTest
* fix: retrofit ExpressionService2Test
(cherry picked from commit bc54ee512a0bb153fcd9813396e2a3d306342b75)
> perf: speed dataElement deletes DHIS2-11100 (#10302) (#10366)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataValueControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/DhisMockMvcControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DataValueSetController.java
https://jira.dhis2.org/browse/DHIS2-12554
- This is to bring back a part of the old feature in import/export app. Previously in the old struts import/export app we return download file with the file name format `dataValuesStartDate_EndDate_facilityName.json.zip`
- However, when moved to new react app, this function is not included in the new controller.
- This PR added back just a part of the format  which includes start date and end date. The facility name/ orgUnit name is not added back because we allow user to select multiple orgUnits for exporting. Therefore, appending all the orgUnit names to the file name seems not a good solution. 
Example : `dataValues_2022-03-01_2022-03-30.json.zip`
Test
- Added mock test and controller test.
> fix: dataValue export file name to include start and end date

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerImportParams.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/job/TrackerMessage.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerImportParamsSerdeTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatIdentifiersTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/DefaultTrackerImporter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerAsyncImporter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportRequest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerSyncImporter.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImporterImplTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImporterTest.java
* use `@Value` instead of `@Data` where possible. TrackerMessage for example represents the import defined by a user with some additional information. We do not want anyone from mutating this message once its created. Default to `@Value` for any code.
* use Builders for classes with a lot of optional values. Builders will only return the fully constructed class at the end.
* TrackerAsyncImporter and TrackerSyncImporter shared the same interface. The data they need is not exactly the same. By not implementing the interface in those two classes we can reduce this artificial coupling. Remove TrackerImportParams from the TrackerImportRequest.
> chore: reduce coupling and mutabilty DHIS2-12563

- .github/workflows/run-tests.yml
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisSpringTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/IntegrationH2Test.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithApiTokenAuthTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithJwtTokenAuthTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisWebSpringTest.java
- dhis-2/pom.xml
This is one first attempt to reduce the running time of tests in the build.
At the moment we are including tests that are using h2 as a DB in the unit tests.
The idea is to review the h2 tests (understand if they need the DB at all and how we can reduce Spring scanning of the classes to create the Context) and run the h2 tests in a separate workflow so it is easier to see if we are making progress reducing the running time.
Separating the workflow reduces the overall time to run a PR, it should be around 12 minutes now, against 15-16 minutes before but of course we have one more job that is running and consuming resources.
> chore: Create separate workflow for integration h2 tests

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
As requested the start and complete "events" for items are excluded from the messages visible in the `Notifier` to avoid "overflowing" the notifiers limited buffer with details.
> fix: exclude job progress items info from notifier [DHIS2-12992]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationLevel.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationLoggerUtil.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
Re-adds the notifications of item level that had been removed to not overflow the in-memory notifier's buffer with details forcing stage messages out. To not have the same issue a new `NotificationLevel` was added `LOOP` which is treated like `DEBUG` except that when found as the most recent notification in a buffer it is replaced by the newest message instead of append it.
Thereby the item level messages do not grow the number of notifications kept in memory. 
For users this appears as if the item level is updated while the process and stage level messages are appended.
To better give the user an orientation where in the loop we are the message is prefixed with a `[<n>/<m>]` counter.
As a consequence the limit bookkeeping needed to be adjusted.
As two or three collections of a  `Pool` …
> feat: replace certain notifier messages instead of append [DHIS2-13035]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/organisationunit/OrganisationUnit.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/schema/annotation/Property.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/query/CriteriaQueryEngineTest.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/introspection/PropertyPropertyIntrospector.java
https://jira.dhis2.org/browse/DHIS2-12541
Add annotation `@Property( persistedAs = "hierarchyLevel" )` to allow overwrite `getLevel` by `getHierarchyLevel` which is used by `JpaCriteriaQueryEngine`
This is fixed  for 2.37+  by another developer but was not back-ported.
> fix: JpaCriteriaQueryEngine query non-persisted field OrgUnit level ( 2.36 )

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RemoveUsedOrExpiredReservedValuesJob.java
Adds `JobProgress` tracking to the `RemoveUsedOrExpiredReservedValuesJob`.
As this job does run a single DB delete there is no detail that could be tracked.
> feat: job progress tracking for cleanup of reserved values job [DHIS2-12858]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramIndicator.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityServiceTest.java
The aggregation based on program indicator is now equal to aggregation based on data element.
Please take it as a first iteration, like start of discussion how this should be implemented.
see https://jira.dhis2.org/browse/DHIS2-12989
> fix: [D]"last value" aggregation type is broken in later versions for data elements and program indicators in the analytics API [2.39-dhis2-12989]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/render/DefaultRenderService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/metadata/MetadataImportExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/XmlDeprecationNoticeHttpMessageConverter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
* Logs deprecation notice whenever a direct usage of `XmlObjectMapper` happens
* Adds back support for XML in `/api/metadata`
[DHIS2-13045](https://jira.dhis2.org/browse/DHIS2-13045)
> feat: log deprecation notice when using XmlObjectMapper (#10435)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
…g "before or including" [2.36-DHIS2-12985-backport]
> fix: Conditions: time with "before" conditions returns values matching "before or including" [2.36-DHIS2-12985-backport]

- dhis-2/dhis-e2e-test/pom.xml
- dhis-2/dhis-e2e-test/src/main/resources/log4j2.xml
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/extensions/ConfigurationExtension.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/extensions/OnFailureLogAppender.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/helpers/matchers/CustomMatchers.java
- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/TrackedEntityInstanceQueryTests.java
- dhis-2/dhis-e2e-test/src/test/resources/setup/tracker_metadata.json
- added a few tests to cover the bug fixed in DHIS2-11702
- configured surefire maven plugin conf to display test report in tree view. This is especially useful for listing parametrized tests. 
Prev: 
```
org.hisp.dhis.tracker.TrackedEntityInstanceQueryTests.queryShouldReturnTeisMatchingAttributeValue(String)[1]
org.hisp.dhis.tracker.TrackedEntityInstanceQueryTests.queryShouldReturnTeisMatchingAttributeValue(String)[2]
org.hisp.dhis.tracker.TrackedEntityInstanceQueryTests.queryShouldReturnTeisMatchingAttributeValue(String)[3]
org.hisp.dhis.tracker.TrackedEntityInstanceQueryTests.queryShouldReturnTeisMatchingAttributeValue(String)[4]
```
Now: 
```
- org.hisp.dhis.tracker.TrackedEntityInstanceQueryTests
[INFO] | +-- [XX] queryShouldReturnTeisMatchingAttributeValue(String) /query with params …
```
> test: adds tests for /trackedEntityInstances/query (DHIS2-11702) 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/pushanalysis/PushAnalysisService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/DefaultPushAnalysisService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/scheduling/PushAnalysisJob.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PushAnalysisController.java
Adds `JobProgress` tracking for push analysis job.
Because of the way tracking loops works I had to reduce the level of detail of logging done previously for the generation itself. The  `generateHtmlReport` could also be called directly from the controller in which case it now only logs errors to log files. The task scheduling that was sort of abused earlier so messages would end up in the `Notifier` is now only part of an actual job run when called via `runPushAnalysis`. I think the intention here never was to have `generateHtmlReport` also push to the `Notifier` but to make the code work for both entry points.
* open scheduler app
* create new job of type _Push Analysis_ (select available _Push analysis_ parameter)
* eventually setup the `server.base.url` (see documentation?)
* manually …
> feat: job progress tracking for push analysis job [DHIS2-12858]

- dhis-2/pom.xml
2.38.0-rc builds are failing on jenkins wth out-of-memory errors. It doesn't fail on master where the heap size is larger or github actions. Not sure if this setting will help, but it's worth trying. Setting maven_opts or java_opts on jenkins agent doesn't seem to increase the heap.
> build: increase heap size during tests

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/StringMethodType.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
for segments that do not have a pattern (e.g. ORG_UNIT_CODE), the pattern is serialized as null instead of an empty string
This fix adds a null safe check for those cases
> fix: ORG_UNIT_CODE Generation fails [ DHIS2-13032 ]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DatastoreControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DatastoreController.java
Cherry-pick of #10483 for 2.38 backport
> fix: datastore - keys in namespace lastUpdated can be empty [DHIS2-12602] (2.38)

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DatastoreControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DatastoreController.java
Problem was that empty `keys` collection could be due to the `lastUpdated` filtering and not because the namespace was generally empty (non existent). 
So in case the found `keys` are empty we also need to check that `!service.isUsedNamespace( namespace )`.
This was simply added.
I added a new test scenario testing that an empty list after `lastUpdated` filtering on non empty namespace does return an empty list and does not throw the exception causing the error web message.
> fix: datastore - keys in namespace lastUpdated can be empty [DHIS2-12602]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationLevel.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationLoggerUtil.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/NotificationMap.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/notification/NotifierTest.java
Cherry-pick of #10391 (which is also backported to 2.38.0 in #10393 - this was precondition for next pick)
Cherry-pick of #10425
> feat: replace certain notifier messages instead of append [DHIS2-13035] (2.38.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/SchemaIdResponseMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsServiceTest.java
This fix enables the usage of `outputIdScheme` in `/enrollments/query` endpoint. It will also take into consideration OptionSet types.
For example, the GET call (which generates an Excel file) below:
```
https://play.dhis2.org/2.37.4/api/29/analytics/enrollments/query/IpHINAT79UW.xls?dimension=pe:LAST_12_MONTHS&dimension=ou:ImspTQPwCqd&dimension=A03MvHHogjR.cejWyOfXge6&stage=A03MvHHogjR&displayProperty=NAME&outputType=ENROLLMENT&desc=enrollmentdate&pageSize=100&page=1&outputIdScheme=NAME
```
Before the fix, it would always output the code of the OptionSet.
After this fix, if the `outputIdScheme`is specified and set to `NAME`, the Excel file will be exported using the OptionSet name instead of its code.
> fix: Align OptionSet with the outputIdScheme param [DHIS2-13098]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
By mistake I changed the branching logic while I introduced the job progress tracking. Here a `return` was needed so we do not always run into the `throw` below for the success path.
> fix: tracker page sync [DHIS2-13030]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vValueCount.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/variable/vZeroPosValueCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
See [DHIS2-13099](https://jira.dhis2.org/browse/DHIS2-13099). The Program Indicator variables `V{value_count}` and `V{zero_pos_value_count}` were not working properly when used in a program indicator filter. This is because they were counting the values of data elements or attributes specified in the filter, instead of counting the values of those items specified in the program indicator main expression. This has been fixed.
(The User Manual clearly says that these functions should return the number of values "in the expression part of the event." See [here](https://docs.dhis2.org/en/full/use/user-guides/dhis-core-version-master/dhis2-user-manual.html#configure_program_indicator), under the table _Variables to use in a program indicator expression or filter_.)
A secondary problem is that …
> fix: V{value_count} in PI filter DHIS2-13099

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
Sometimes the temporary partition table are not dropped and staying in database after the analytics update. Normally the temp partitions are dropped by swapping the old for new ones. If this swap process failed (silently, there is just debug level log), the old data remaining in the partition table and new data are only in temp table. Subsequently new analytics update process will just add the more or less same data into temp table (with reindexing - time and space consuming).
On the beginning of the process we are trying to drop all remaining temp tables. The implementation did not remove (drop) partition temp tables (year handling was incorrect)
This problem was fixed (unintentionally) by Maikel in https://github.com/dhis2/dhis2-core/pull/10014/files and backported down to the 2.37 (PR …
> fix: Disk space utilization for analytics temp tables spiking in 2.37[2.39-DHIS2-13085]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/AnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
Sometimes the temporary partition table are not dropped and staying in database after the analytics update. Normally the temp partitions are dropped by swapping the old for new ones. If this swap process failed (silently, there is just debug level log), the old data remaining in the partition table. Subsequently new analytics update process will just add the more or less same data into temp table (with reindexing - time and space consuming).
On the beginning of the process we are trying to drop  all remaining temp tables. The implementation did not remove (drop) partition temp tables (year handling was incorrect)
This problem was fixed (unintentionally) by Maikel in https://github.com/dhis2/dhis2-core/pull/10014/files and backported down to the 2.37 (PR 9th of March 2022).
2.36 was not …
> fix: Disk space utilization for analytics temp tables spiking in [2.36-DHIS2-13085]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EnrollmentAnalyticsQueryCriteria.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/SchemaIdResponseMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsServiceTest.java
**[Backport from master (2.39)]**
This fix enables the usage of `outputIdScheme` in `/enrollments/query` endpoint. It will also take into consideration OptionSet types.
For example, the GET call (which generates an Excel file) below:
```
https://play.dhis2.org/2.37.4/api/29/analytics/enrollments/query/IpHINAT79UW.xls?dimension=pe:LAST_12_MONTHS&dimension=ou:ImspTQPwCqd&dimension=A03MvHHogjR.cejWyOfXge6&stage=A03MvHHogjR&displayProperty=NAME&outputType=ENROLLMENT&desc=enrollmentdate&pageSize=100&page=1&outputIdScheme=NAME
```
Before the fix, it would always output the code of the OptionSet.
After this fix, if the `outputIdScheme`is specified and set to `NAME`, the Excel file will be exported using the OptionSet name instead of its code.
>  fix: Align OptionSet with the outputIdScheme param [DHIS2-13098]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/CollectionService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/collection/DefaultCollectionService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
https://jira.dhis2.org/browse/DHIS2-12958
- User sends a `POST` request to `/api/userGroups/{groupId}/users` with payload contains both deletions and additions.
- Server returns `500` error with message `A different object with the same identifier value was already associated with the session : [org.hisp.dhis.user.UserGroup#224024`
-  Move the service calls of `collectionService.delCollectionItems()` and `collectionService.addCollectionItems()`  from the controller to service layer. By this the `@Transactional` should be able to handle the clearing session and refreshing entity correctly.
- Move the `session.clearCache()` function to controller layer. This fixes the issue of duplicate objects in session. We should only call cache clear after all changes have been flushed to database ( …
> fix: collection api error with additions and deletions in one payload 

- dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventIdSchemeTests.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/DefaultTrackerPreheatService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/DefaultPreheatCacheService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/cache/PreheatCacheService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/CategoryMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/CategoryOptionMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ClassBasedSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/DefaultsSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/EventCategoryOptionComboSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerIdentifierCollectorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatIdentifiersTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/TrackerPreheatServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ClassBasedSupplierTest.java
Relates to both https://jira.dhis2.org/browse/DHIS2-12563 and https://jira.dhis2.org/browse/DHIS2-12759
defaults for metadata like Category, CategoryOptionCombo, ... where not returned by
https://github.com/dhis2/dhis2-core/pull/10546/files#diff-8bcab5fc74e034ebd337f7c3a069adb167a1451414163c9b7938aafaab26dc11L379-L380
since imports using idScheme other than UID failed to insert the metadata into the TrackerPreheat.map. So even though `TrackerPreheat.defaults` contained the defaults `return this.get( defaultClass, uid );` (which accesses `TrackerPreheat.map`) did not.
Add default metadata into the preheat using a dedicated supplier. The logic is irrespective of the idScheme chosen during the import. Defaults can be retrieved using their name (`default`). Its important to map the metadata …
> fix: TrackerPreheat defaults support idSchemes DHIS2-12563

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectManager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataentryform/DataEntryFormService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataentryform/DefaultDataEntryFormService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataentryform/DataEntryFormServiceTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataentry/CustomDataEntryFormController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/dataentry/DataSetMetadataExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/webdomain/dataentry/CustomDataEntryFormDto.java
- dhis-2/dhis-web/dhis-web-dataentry/src/main/java/org/hisp/dhis/de/action/LoadFormAction.java
Adds a custom data entry form API endpoint at the following API path, where the `id` refers to the data set UID. The response type is JSON.
```
GET /api/dataEntry/customForms/{id}
```
Removes unused method from `DataEntryFormService`.
* Unit tests added.
* Test URL for valid form: `/api/dataEntry/customForms/lyLU2wR22tC`
* Test URL for non-custom form: `/api/dataEntry/customForms/BfMAe6Itzgt`
* Test URL for non-existing data set: `/api/dataEntry/customForms/lyLU2wR22tX`
> feat: Add custom data entry form API endpoint

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/apphub/DefaultAppHubService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AppHubControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppHubController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CrudControllerAdvice.java
The best fix here seemed to me to map the `RestClientException` to a `WebMessage` with `503` HTTP response code.
This exception was previously not mapped resulting in a HTTP 500.
Mapping all "client" (requests done by the server internally to other web services) to a 503 might be a bit broad but it surely is better than a 500 and doing very detailed error handling just seems overkill for this and similar problems.
Added some controller tests that verify the 503 by changing the configuration for the app hub API URL to some non-existing URL. This is not a timeout as encountered in the original ticket but should be a similar type of scenario.
I also added two "success" path scenarios which work with the default URL which means the test do a request to the https://apps.dhis2.org/api URL. We …
> fix: app hub returns 503 when internal app hub request fails [DHIS2-13107]

- .github/workflows/dependabot.yaml
This is a new workflow (based on [the official GitHub docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions\#enable-auto-merge-on-a-pull-request)) to automatically merge patch dependency updates.
The workflow would run a job only if the PR event is caused by the GitHub dependabot!
The workflow would
* use https://github.com/dependabot/fetch-metadata#usage-instructions to get information about the dependencies being updated
* approve the PR if the dependencies updated are only of semver patch
* enable automerge on this specific PR so that if all required checks are successful the PR would automatically be merged
For auto-merge to work a repo admin would need to enable it in the repo settings …
> ci: auto merge dependabot patch PRs

- .github/workflows/dependabot.yaml
so our dependabot workflow should also squash its commits when the PR is merged
> ci: we do not allow merge commits

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/log/Log4JLogConfigInitializer.java
- dhis-2/pom.xml
* check log4j version 2 property `log4j2.configurationFile` https://logging.apache.org/log4j/2.x/manual/configuration.html to see if a user brings their own logging configuration
* ban log4j version 1 so we do not accidentally log using log4j version 1, parse any log4j version 2 config using version 1, remove any log4j version 1 log errors like
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
--
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
* only check `locationManager.externalDirectorySet()` in case the user has not provided their own config. Only then will we need to create the directory/files for logging.
> fix: Disable builtin logging customization when given logging config by user DHIS2-13163

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobProgressTest.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/resourcetable/DefaultResourceTableService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/sms/scheduling/SendScheduledMessageJob.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableGenerator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/FileResourceCleanUpJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/ImageResizingJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/notification/DefaultProgramNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NoopJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/SystemUpdateService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentityattributevalue/TrackerTrigramIndexingJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/AccountExpiryAlertJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/DisableInactiveUsersJob.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/ControlledJobProgressTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/DataValueSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/credentials/CredentialsExpiryAlertJob.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/DefaultDataStatisticsService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/predictor/DefaultPredictionService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/pushanalysis/DefaultPushAnalysisService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/Validator.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/notification/DefaultValidationNotificationService.java
This PR adds per stage or item failure policy.
This allows to not fail the entire job process when an item or stage is failing but based on the policy chosen evaluate if the run should continue and eventually skip items in the failing stage.
The policy can be set when calling the `startingStage` or `startingWorkItem` method.
By default, the policy is to fail as before.
A policy is set on stage level is "inherited" by the item level unless it is explicitly set on that level.
The effective policy for each stage and item will be visible in the tracked information as `onFailure`.
Besides adding the general concept of custom failure policies the policies got used in the different jobs where it seemed suiting.
Possible failure policies are:
* `FAIL`: just fail (as before) by (eventually) …
> feat: job progress stage specific failure policy [DHIS2-13101]

- dhis-2/dhis-e2e-test/docker-compose.e2e.yml
The property is set on the Jenkins file, so it's not necessary
> ci: remove rp_attributes from docker command

- dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2.xml
- dhis-2/dhis-web-embedded-jetty/src/main/resources/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/WEB-INF/classes/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/log4j2-jetty.xml
The "fileLogger" defined in the xml config is never "attached" to a
logger. Not in the config or in code. Its thus unused.
Log4JLogConfigInitializer creates its own RollingFileAppenders unless a
user provides their own logging config.
Just to understand the root cause of the exception on start of DHIS2:
The "fileLogger" in the log4j2.xml config was responsible for it. The
property 'createOnDemand' controls when the RollingFileAppender creates
the log file. Since that is false by default, the "fileLogger" is trying
to create the file once log4j2 initializes. log4j2 does not have
permissions to create the dhis.log specified in "fileLogger".
> fix: remove unused RollingFileAppenders in log4j2.xml DHIS2-12986

- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/predictor/hibernate/Predictor.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v39/V2_39_6__Add_unique_shortName_to_predictors.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_5__Add_column_shortName_to_predictor_table.sql
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_7__Add_unique_and_not_null_to_predictor_shortName.sql
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/PredictorControllerTest.java
Predictors got a short name that is persistet.
DB update scripts make sure short name derived from name column is unique.
Existing tests were updated to set the short name.
* open maintenance app
* navigate to predictors list
* pick a predictor, change its short name and save the change
* check the change is persistent, e.g. return to edit after navigating to different page, check `api/predictors` or similar
> feat: persistent unique shortNames for predictors [DHIS2-10688]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultAnalyticalObjectImportHandler.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/favorites/metadata_with_visualization_and_legendSet.json
https://jira.dhis2.org/browse/DHIS2-13019
- According to [PR#8262](https://github.com/dhis2/dhis2-core/pull/8262), from 2.37 legend properties has been moved to a new `LegendDefinitions` object.  However the import service has not been updated to handle this new object.
- This leads to the error of saving a `Visualization` with an unsaved `LegendSet` object.
- Add custom logic to handle new object `LegendDefinitions` in `DefaultAnalyticalObjectImportHandler`
- Add integration tests
> fix: error importing Visualization with legendSet

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DatastoreFieldsControllerTest.java
Upon request the datastore API syntax for `fields` parameter is changed.
`(`/`)` and `[`/`]` now both can be used to indicate the nesting.
To hoist leaf properties to the top with an alias name (previously just `(alias)` after the leaf name) the new alias is now `name~hoist(alias)`.
Existing tests were adjusted and now demonstrate the 3 ways to express nesting.
https://github.com/dhis2/dhis2-docs/pull/995
> fix: datastore query API nesting and alias syntax [DHIS2-13193]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/userkeyjsonvalue/UserKeyJsonValue.java
This is a backport of the fix done in #10613 - as the datastore itself is too different in 2.37 the feature of that PR is not backported.
> fix: user datastore getValue() returns value field with priority [DHIS2-7851]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DatastoreFieldsControllerTest.java
> fix: datastore query API nesting and alias syntax [DHIS2-13193] (2.38.0)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datastore/DatastoreQuery.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DatastoreFieldsControllerTest.java
> fix: datastore query API nesting and alias syntax [DHIS2-13193] (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
Backport based on cherry-pick of #10648 with manual changes to adjust to the changes to job progress that were not backported like the per stage failure handling (#10507). This also includes the logging of tracked info added in #10501.
> fix: job progress - clean complete after cancel [DHIS2-13125] (2.38)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/CompleteDataSetRegistrationSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/DataValueSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/EventSynchronization.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/TrackerSynchronization.java
Changes policy from `SKIP_ITEM_OUTLIER` to `SKIP_ITEM`. 
Also found that the stage was mistakenly started using `startingProcess` instead of `startingStage` in one occasion.
Also want to point out that in the `EventSynchronization#synchronizePage` the page is not explicitly part of the database query but a true/false filter is used in the assumption that the last page sync has flipped this flag causing the next call to return the next page. At least this is how I understand it.
> fix: allow any page to fail during data sync [DHIS2-13206]

- dhis-2/pom.xml
dhis2-antlr-expression-parser was using different versions for the antlr plugin and the antlr library and this was throwing a warning in the logs
> fix: Remove ANTRL versions warning from logs

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/QueryItemHelper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryItemHelperTest.java
**_[Backport from master/2.39]_**
When consuming the endpoint "/analytics/events/query", and a DataElement filters by Option (from OptionSet) but no results are found (which means empty rows in the response), we should still get back the Options as part of the "metaData/items" element.
After this fix, the following GET request should return the respective option as part of `metaData/items`. Ie.:
``` 
https://play.dhis2.org/dev/api/39/analytics/events/query/eBAyeGv0exc?dimension=ou:USER_ORGUNIT,Zj7UnCAulEk.K6uUAvq500H:IN:A03&headers=ouname,eventdate,Zj7UnCAulEk.K6uUAvq500H&totalPages=false&eventDate=LAST_12_MONTHS&displayProperty=NAME&outputType=EVENT&pageSize=100&page=1&includeMetadataDetails=true&asc=ouname
```
Should return the `A03` option, even if there are no rows in the response. …
> fix: Options not returned when results rows are empty [DHIS2-13140]

- dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2.xml
- dhis-2/dhis-web-embedded-jetty/src/main/resources/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/WEB-INF/classes/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/log4j2-jetty.xml
backport of https://github.com/dhis2/dhis2-core/pull/10629
The "fileLogger" defined in the xml config is never "attached" to a
logger. Not in the config or in code. Its thus unused.
Log4JLogConfigInitializer creates its own RollingFileAppenders unless a
user provides their own logging config.
Just to understand the root cause of the exception on start of DHIS2:
The "fileLogger" in the log4j2.xml config was responsible for it. The
property 'createOnDemand' controls when the RollingFileAppender creates
the log file. Since that is false by default, the "fileLogger" is trying
to create the file once log4j2 initializes. log4j2 does not have
permissions to create the dhis.log specified in "fileLogger".
> fix: remove unused RollingFileAppenders in log4j2.xml [2.38]

- dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/WEB-INF/classes/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/log4j2-jetty.xml
backport of https://github.com/dhis2/dhis2-core/pull/10629
The "fileLogger" defined in the xml config is never "attached" to a
logger. Not in the config or in code. Its thus unused.
Log4JLogConfigInitializer creates its own RollingFileAppenders unless a
user provides their own logging config.
Just to understand the root cause of the exception on start of DHIS2:
The "fileLogger" in the log4j2.xml config was responsible for it. The
property 'createOnDemand' controls when the RollingFileAppender creates
the log file. Since that is false by default, the "fileLogger" is trying
to create the file once log4j2 initializes. log4j2 does not have
permissions to create the dhis.log specified in "fileLogger".
> fix: remove unused RollingFileAppenders in log4j2.xml [2.37]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/interpretation/DefaultInterpretationService.java
Make the URL of Event Visualization the same as Event Report during the "migration/deprecation" phase.
_**NEEDS APPROVAL FROM THE RELEASE CONTROL TEAM.**_
> fix: Interpretation URL for 2.38 patch [DHIS2-13109]

- dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/WEB-INF/classes/log4j2.xml
- dhis-2/dhis-web/dhis-web-commons/src/main/resources/log4j2-jetty.xml
backport of https://github.com/dhis2/dhis2-core/pull/10629
The "fileLogger" defined in the xml config is never "attached" to a
logger. Not in the config or in code. Its thus unused.
Log4JLogConfigInitializer creates its own RollingFileAppenders unless a
user provides their own logging config.
Just to understand the root cause of the exception on start of DHIS2:
The "fileLogger" in the log4j2.xml config was responsible for it. The
property 'createOnDemand' controls when the RollingFileAppender creates
the log file. Since that is false by default, the "fileLogger" is trying
to create the file once log4j2 initializes. log4j2 does not have
permissions to create the dhis.log specified in "fileLogger".
> fix: remove unused RollingFileAppenders in log4j2.xml [2.36]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/log/Log4JLogConfigInitializer.java
backport of https://github.com/dhis2/dhis2-core/pull/10641 except for the exclusion of log4j version 1. debezium prior to 1.9 brings in a dependency on log4j version 1. Since debezium is responsible for replication backporting an upgrade of debezium seems risky.
Log4JLogConfigInitializer will not make any config changes if the user provides
their own logging configuration. The check relies on the log4j config property.
Log4JLogConfigInitializer should check the log4j version 2 config not version 1, as
we rely on version 2.
> fix: Log4JLogConfigInitializer should check log4j version 2 config DHIS2-13163 [2.38]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/log/Log4JLogConfigInitializer.java
backport of https://github.com/dhis2/dhis2-core/pull/10641 except for the exclusion of log4j version 1. debezium prior to 1.9 brings in a dependency on log4j version 1. Since debezium is responsible for replication backporting an upgrade of debezium seems risky.
Log4JLogConfigInitializer will not make any config changes if the user provides
their own logging configuration. The check relies on the log4j config property.
Log4JLogConfigInitializer should check the log4j version 2 config not version 1, as
we rely on version 2.
> fix: Log4JLogConfigInitializer should check log4j version 2 config DHIS2-13163 [2.37]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/log/Log4JLogConfigInitializer.java
backport of https://github.com/dhis2/dhis2-core/pull/10641 except for the exclusion of log4j version 1. debezium prior to 1.9 brings in a dependency on log4j version 1. Since debezium is responsible for replication backporting an upgrade of debezium seems risky.
Log4JLogConfigInitializer will not make any config changes if the user provides
their own logging configuration. The check relies on the log4j config property.
Log4JLogConfigInitializer should check the log4j version 2 config not version 1, as
we rely on version 2.
> fix: Log4JLogConfigInitializer should check log4j version 2 config DHIS2-13163 [2.36]

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/UserActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/RelationshipItem.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/RelationshipPreheatKeySupport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/relationshipToUpdate.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/relationships.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/RelationshipItemMapper.java
Now that we have separate models for our domain and the view (JSON exposed to users) only the TEI, enrollment, event ids are needed in the tracker domain RelationshipItem.
See https://github.com/dhis2/dhis2-core/pull/9841 if you need more context why these fields where introduced before we had domain and view models.
* metadata identifier fields in org.hisp.dhis.tracker.domain will gradually be made idScheme aware.
* tracker view (JSON import/export) and domain models are split since users only specify idSchemes in the query parameters (not in the body) and only on import. The metadata identifier fields in the user-facing import/export JSON are strings containing only the identifier without idScheme.
all metadata identifiers in the tracker domain
* Attribute.attribute
* …
> chore: simplify RelationshipItem in domain DHIS2-12563

- .github/workflows/dependabot.yaml
as a security measure. So we cannot add a 2nd auto-approval this way
see https://docs.github.com/en/actions/security-guides/automatic-token-authentication
> ci: runs triggered by Dependabot PRs cant access secrets

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportParamsBuilder.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/TrackerImportParamsBuilderTest.java
when only passing query parameter `idScheme=ATTRIBUTE:someUID` metadata type specific idScheme parameters like programIdScheme got `idScheme=ATTRIBUTE` `attributeUid=null` instead of `someUID`
> fix: metadata idSchemes attribute UID null on default DHIS2-12760

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Conjunction.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Criteria.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultJpaQueryParser.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/DefaultQueryService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Disjunction.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Junction.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Pagination.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Query.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/QueryUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Restriction.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Type.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/Typed.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/BetweenOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/EqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/GreaterEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/GreaterThanOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/InOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/LessEqualOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/LessThanOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/LikeOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/NotLikeOperator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/operators/Operator.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/QueryPath.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/QueryPlan.java
This is a cleanup run through the `query` package.
* use `final` on classes and fields where possible
* use `@Getter` / `@Setter` where possible
* use lombol generated constructor 
* use `this` to delegate to all args constructor in constructors with less arguments
* use `List.of` for list that should not change
* use `@Builder` instead of hand written builders
* avoid `if else` when there is a `return` prior so a `if` is sufficient
* do instance-of tests with the `instanceof` operator
* use streams to reduce a collection to a boolean
* join identical `case` blocks
* **remove unused code**
* use `@ToString` for "value types" with only simple fields
* use `StringBuilder` instead of `+=` (automatic refactoring)
* add wildcard generics when missing
* remove unnecessary `!= null` checks (e.g. …
> chore: cleanup Metadata query [DHIS2-13158]

- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/actions/UserActions.java
- dhis-2/dhis-e2e-test/src/main/java/org/hisp/dhis/dto/ApiResponse.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistAttributeControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
This is "part1" of allowing attribute UIDs as properties. The Gist API already had this feature - this PR is only improving the test situation to make sure the feature works.
were added
> feat: attribute as property in gist API fields and filters [DHIS2-13158]

- dhis-2/dhis-web/dhis-web-apps/apps-to-bundle.json
In the next 2.38 release (2.38.1), the Capture App should be based on the master branch. This is due to the Capture App having been migrated to continuous delivery.
> fix: reference master branch for Capture app [TECH-1180]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/LabelMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/LabelMapperTest.java
This PR aims to map the date attributes to their respective header display labels.
It ensures that the dates in the headers of the grid are equally displayed in the download endpoint.
> fix: Map labels on program dates, in events [DHIS2-13212]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
Small bug fix, so the `scheduledDate` enforces the correct event status (`SCHEDULE`)
> fix: Param scheduledDate does not respect status [DHIS2-12309]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2RelationshipCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EnrollmentAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/EventAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/aggregates/TrackedEntityInstanceAggregate.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/AbstractStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/EnrollmentStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/EventStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/TrackedEntityInstanceStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
Relationship is now a soft deletable entity. Stores and other services that are using plain sql to retrieve relationships now need to be aware if the relationship is soft deleted or not.
Changes are needed:
- In the old tracker importer when retrieving TEIs and linked Relationships. We need to check `includeDeleted` param.
- In the old tracker importer when retrieving Enrollments and linked Relationships. We need to check `includeDeleted` param.
- In the old tracker importer when retrieving Events and linked Relationships. We need to check `includeDeleted` param.
- When counting relationships using `d2:relationshipCount` function for indicators. @jimgrace please have a careful look at this part
> fix: Fix SQL queries for deleted relationships [DHIS2-11320]

- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/resources/csv/dataValues.csv
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimItemDataElementAndOperand.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/DimensionalItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/function/FunctionSubExpression.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionServiceTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/ExpressionState.java
See [DHIS2-13227](https://jira.dhis2.org/browse/DHIS2-13227). Since 2.36.7, expressions can process non-numeric data elements. To support this, expressions do type-checking based on the data element's ValueType. For example, a boolean data element can be used as the true or false test in an if() function within a validation rule or predictor. However this introduced a problem because previously a boolean data data element could be used in an expression to produce a numeric value. This is because booleans are stored as numeric values (1 or 0) in the analytics tables and can be aggregated to show the count of true values (1's). The type checking broke this functionality.
The fix is to allow for boolean values that will be aggregated in an indicator to be considered to return a numeric value …
> fix: Indicator summing boolean values DHIS2-13227

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/SchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/ResourceTableControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ResourceTableController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
The endpoints in `/resourceTables` would try to execute jobs ad-hoc using the scheduler but did not consider the return value of `executeNow` always returning that the job was scheduled. This was not necessarily the case.
Now the return value is considered and the returned web message will reflect the status more consistent with what actually happened. 
Still success here only refers to adding the task for scheduling. It might still never run if it has a collision with another job running when it is due to be executed by the scheduler. The internal propagation of the difference was improved a bit but can only go as far as the point when a `Runnable` task is scheduled for execution using the underlying execution service.
To be able to test this sort of scenarios where a task is already …
> fix: /resourceTables jobs return conflict when job is already running [DHIS2-12367]

- dhis-2/pom.xml
jclouds does not ship the excluded libraries anymore.
This is a snippet of our dependency tree (including jclouds)
+- com.google.code.gson:gson:jar:2.8.9:compile
+- org.apache.jclouds:jclouds-core:jar:2.5.0:compile
|  +- com.google.inject:guice:jar:5.0.1:compile
|  |  +- javax.inject:javax.inject:jar:1:compile
|  |  \- aopalliance:aopalliance:jar:1.0:compile
|  +- com.google.inject.extensions:guice-assistedinject:jar:5.0.1:compile
|  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
|  \- com.sun.xml.bind:jaxb-impl:jar:2.3.3:compile
|     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
|     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
+- org.apache.jclouds:jclouds-blobstore:jar:2.5.0:compile
+- org.apache.jclouds.api:filesystem:jar:2.5.0:compile
+- …
> chore(deps): remove old exclusions from jclouds

- dhis-2/dhis-web-api/pom.xml
- dhis-2/pom.xml
https://jira.dhis2.org/browse/DHIS2-13251
```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Could not write PNG file because no WriteAdapter is availble
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
```
- Current version of `batik` need a `WriteAdapter` in order to generate a PNG file. 
We need to include `batik-codec` in pom file for that.
_PNGTranscoder.java_
```
PNGTranscoder.WriteAdapter adapter = this.getWriteAdapter("org.apache.batik.ext.awt.image.codec.png.PNGTranscoderInternalCodecWriteAdapter");
if (adapter == null) {
adapter = this.getWriteAdapter("org.apache.batik.transcoder.image.PNGTranscoderImageIOWrit …
```
> fix: error when download visualization as png

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/EnrollmentActionRule.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AbstractRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/SetMandatoryFieldValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/AssignValueImplementerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/SetMandatoryFieldValidatorTest.java
Therefore
* collect/preheat rule engine dataElements/attributes using UIDs (TrackerIdentifierCollector)
* get dataElements/attributes from the preheat before matching on any of
these entities in the program rule engine tracker code in each rule implementer
The previous approach did not work since EnrollmentActionRule.field will always be a UID as its coming from rule engine. If we preheat rule engine attributes in the user defined idScheme we will then not find them in the preheat using a UID.
EnrollmentActionRule.field can be `""` in some Rules, so having the rule implementers do the mapping/interpretation of what the `field` is is easier to understand and safer.
> fix: rule engine attribute identifiers are UIDs DHIS2-12563

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/OptionControllerTest.java
https://jira.dhis2.org/browse/DHIS2-12828
- By default, if we update an OptionSet with Option's sortOrder gaps then Hibernate will auto re-organizes the sortOrders. However, Hibernate can't do that if we execute the update from _Option side of the association_.  Means that we only update Option without touching its OptionSet.
- I think the best way to solve this for the metadata import service is to remove and add the updating Option again to OptionSet. 
- Then at then end of the import process when we call `session.flush()` the OptionSet will be updated and all sortOrders will be re-organized.
- This is already handled for create new Option. Currently issue only happens with updating.
Example: [1,2,null,null,null,9] will be re-organized by Hibernate to [1,2,3]
- Added controller test
> fix: update Option.sortOrder resulted with null sortOrders

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventvisualization/EventVisualization.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventvisualization.hibernate/EventVisualization.hbm.xml
- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_11__Add_LegendSet_Column_Into_EV.sql
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/VisualizationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventVisualizationController.java
This PR simply adds a new attribute to the `EventVisualization` object.
It works exactly as the existing `legend` in `Visualization`.
It relates to the API `/eventVisualizations`.
A brief example of the `legend` attribute:
```
"legend": {
"set": {
"id": "gFJUXah1uRH"
},
"showKey": false,
"style": "FILL",
"strategy": "FIXED"
}
```
> feat: Support 'legend' in EventVisualization [DHIS2-13264]

- dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.39/V2_39_7__Add_unique_and_not_null_to_predictor_shortName.sql
To be safe we need to drop the constraint should it already exist. 
The modified flyway script is not yet released so changing it only affects development in master.
> fix: predictor unique short name - drop constriant before adding it [DHIS2-10688]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/Enrollment.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/Event.java
its a field exposed in our view on export. It has also no influence on an import as orgUnits are not created within tracker
> chore: orgUnitName is unused in tracker domain DHIS2-12563

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/RelationshipTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackedEntityTrackerConverterService.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/domain/MetadataIdentifier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramStageInstanceProgramStageMapSupplier.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/BidirectionalRelationshipsPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/DuplicateRelationshipsPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessor.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHookTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/package-info.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/imports/package-info.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/view/package-info.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/imports/MetadataIdentifierMapperTest.java
cleanups like
* use higher level preheat APIs like `preheat.getOrganisationUnit( id );` instead of `preheat.get( OrganisationUnit.class, id );`
* add javadocs to MetadataIdentifier, view, import, export packages; so we know why they exist
* !MetadataIdentifier.isBlank is used often enough for us to add complement MetadataIdentifier.isNotBlank
* improve assertions in MetadataIdentifierTest (thereby also testing lombok `@EqualsAndHashCode` is setup)
> chore: docs, improve APIs DHIS2-12563

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/geojson/DefaultGeoJsonService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/geojson/GeoJsonService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GeoJsonImportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/GeoJsonImportController.java
After a chat with Björn we concluded that using JSON `null` value for the `geometry` of a GeoJSON feature node should effectively delete the geometry present. This is either setting `geometry` of the organisation unit to `null` or removes the attribute of the provided ID.
API wise deletion can also be done by using HTTP `DELETE` 
DELETE /api/organisationUnits/{uid}/geometry
New test scenarios were added to test deletion.
One scenario tests geometry property deletion, another one attribute deletion.
As these use the HTTP DELETE path this also tests single delete with `null` as body.
As single update is just turned into a bulk update with one entry internally this also tests bulk deletetion.
> feat: GeoJSON import - delete with null geometry [DHIS2-7171]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/hibernate/HibernateRelationshipStore.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeValueAuditTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityDataValueAuditTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/params/AtomicModeIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleVariableIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentAttrValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TeTaEncryptionValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TeTaValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/Users.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/te-program_with_tea_fileresource_metadata.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/te-program_with_tea_invalid_value_isnull.json
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
This PR is just cleaning up a little bit the tests in tracker module fundamentally doing 2 things:
- Removing `AbstractImportValidationTest` as it was just an indirection for `TrackerTest` injecting admin user in tracker params. Now admin user is explicitly injected in the setup using `injectAdminUser()` method.
- Make some remaining tests extends TrackerTest in order to remove redundant code
> chore: Clean up user management in tracker tests [TECH-890]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerReportUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerWarningReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerReportUtilsTest.java
which will already be in the user defined idScheme.
This way we do not have to remember calling `.getIdentifierOrAttributeValue()` when adding error/warning reports.
> fix: report ids or attribute value for MetadataIdentifiers DHIS2-12519

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdSchemeParam.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/bundle/TrackerBundle.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerReportUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerWarningReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/ValidationUtils.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerReportUtilsTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/ValidationErrorReporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationServiceConfigOrderTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/DefaultTrackerValidationServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentInExistingValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckExistenceValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityOwnershipValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckUidValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckUpdatableFieldsValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java
* TrackerErrorReport/TrackerWarningReport/ValidationErrorReporter only needs idSchemes to add a new error. Not the entire TrackerBundle. First step in decoupling ValidationErrorReporter from the TrackerBundle. Later PR will look into removing its dependency on it.
* removed unused TrackerBundle.identifier which was always UID and did not reflect the actual idSchemes set by the user. Using it in TrackerReportUtils lead to reports always being in idScheme UID instead of user defined one.
> chore: ValidationErrorReporter only needs idSchemes DHIS2-12519

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/geojson/DefaultGeoJsonService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/geojson/GeoJsonImportConflict.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GeoJsonImportControllerTest.java
Now uses same strict validation based on `Geometry` for both imports to the `geometry` field and imports to a custom `GEOJSON` attribute.
In addition now all unique names will be imported successful while only the non-unique name identifiers are ignored and reported as conflict.
Existing tests were adjusted as now the validation expectation is the same for import to geometry field or attribute.
A new test scenario was added for the unique name conflict.
> feat: GeoJson import strict validation, ignore non unique names [DHIS2-7171]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/AttributeValueMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/CategoryComboMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/CategoryMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/CategoryOptionComboMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/CategoryOptionMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/DataElementMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/OrganisationUnitMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramTrackedEntityAttributeMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/RelationshipMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/RelationshipTypeMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityAttributeMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityInstanceMapper.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/AttributeCreator.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/OrganisationUnitMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/ProgramInstanceMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/ProgramStageMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/RelationshipMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/RelationshipTypeMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityAttributeMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityInstanceMapperTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/mappers/TrackedEntityTypeMapperTest.java
When comparing metadata from the preheat to metadata in the payload like in
https://github.com/dhis2/dhis2-core/blob/336a4c206938a264d27dd3eb67dc75df83483f30/dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java#L128-L129
we need to ensure that metadata in the preheat has fields uid, code, name, attributeValues mapped. This is needed to support all 4 idSchemes for matching metadata (UID, CODE, NAME, ATTRIBUTE).
Not mapping them would lead to false `metadata not found` errors or other errors.
* add reusable mapper of Set<AttributeValue> to AttributeValueMapper
* mapping attributeValues field in preheat mappers for metadata fields that are used in the tracker domain. The best I could 😓 We might still need to add …
> fix: map all idScheme related fields DHIS2-12563

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/DataType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/ValueType.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/DefaultGistService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistQuery.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/dataanalysis/MinMaxOutlierAnalysisService.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GeoJsonImportControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistAttributeControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractGistReadOnlyController.java
When a attribute of value type `GEOJSON` (or any JSON type) is requested explicitly by its ID in the `fields` list, the value is rendered as JSON instead of being a string (which is rendered as escaped JSON string).
After having implemented this for individual attributes I opted to not also implement this in general when all attribute values are included as the overhead both on server and client side can be significant as GeoJSON data can be a quite large object graph.
Added tests for Gist API that test both extraction from the deserialised `Set<AttributeValue>` as well as the direct extraction from database using JSONB functions.
* create a new attribute of type `GEOJSON` and make it usable for e.g. user groups
* create or edit a user group and add a value for the new attribute, a …
> feat: render GeoJSON attribute values as JSON when individually requested [DHIS2-13323]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/MessageFormatter.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerWarningReport.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/ValidationErrorReporter.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/MessageFormatterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/ValidationErrorReporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RelationshipsValidationHookTest.java
* ReportUtils (now MessageFormatter) is actually responsible for formatting the report message. Thus, name it MessageFormatter (`report` context is already part of the package).
* TrackerErrorReport/WarningReport do not need builders. All their fields are required. So it should only have an all args constructor. Builders are great with lots of optional fields.
* TrackerErrorReport/WarningReport do not need to depend on idSchemes. The ValidationErrorReporter is already idScheme aware. ValidationErrorReporter can instantiate the TrackerErrorReport using a MessageFormatter formatted message.
* add docs and tests to MessageFormatter
> chore: simplify TrackerErrorReport/WarningReport DHIS2-12519

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/DisableInactiveUsersJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/user/UserServiceTest.java
Allows i18n for texts used in emails send to users whose account is soon to be disabled.
The local is joined in the database query using `UserSetting` with name `keyUiLocale`.
As a consequence the emails send have to be grouped by the language they used so that all users of a language can be send in one operations.
This slightly more complicated processing is also tracked in more detail by the job progress tracking to provide more insight into what happens in the job. The failure policy also got fine tuned so that the job effectively does a "best effort" approach skipping those attempts that fail. 
Existing test scenario for the service finding the users to notify got updated so this also tests that the local for the user is fetched from the database.
See testing instructions in #7307 and …
> feat: i18n for disable inactive users email texts [DHIS2-13307]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityCheck.java
- dhis-2/dhis-services/dhis-service-administration/pom.xml
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReader.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/dataintegrity/DefaultDataIntegrityService.java
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_no_options.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_one_default_category.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_one_default_category_combo.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_one_default_category_option.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_one_default_category_option_combo.yaml
- dhis-2/dhis-services/dhis-service-administration/src/main/resources/data-integrity-checks/categories/categories_unique_category_combo.yaml
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityServiceTest.java
- dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityYamlReaderTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonDataIntegrityCheck.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataIntegrityDetailsControllerTest.java
Adds a new field `issuesIdType` to the data integrity check information. 
The field gives the type of details `issues[*].id` values in form of their plural name, for example `categories` in case the `id` of an issue is a `Category` UID.
The proper type was added to all existing data integrity checks.
Existing tests were adjusted to also check for the new field.
Check `/api/dataIntegrity` and look for the `issuesIdType` property. It should have a value in almost all cases. It is correct that few do not have that information as they do not point to an existing object type but some scope, like for example periods with a similar start date of same type.
https://github.com/dhis2/dhis2-docs/pull/1007
> feat: data integrity checks provide issues ID type information [DHIS2-13321]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/CompleteDataSetRegistrationSynchronization.java
I opted to address this in two ways: the sync does no longer add the `SYNC` strategy parameter. That alone should fix the synchronization. 
However, the `SYNC` strategy is still a valid value for `strategy` parameter. Therefore the `isSync()` is also added to the guards for the create and update blocks in the import effectively making it equal to the `isCreateAndUpdate()` strategy. 
`isSync()` was not added to the guard of the delete block. For an object that does not have soft-deletion flag an import either create or updates its items or deletes them. Both at the same time does not make sense.
A comment in the deletion path also wonders:
// TODO Does 'delete' even make sense for CDSR?
For the `CompleteDataSetRegistration` synchronisation it surely will not as the list send to the central …
> fix: complete data set registration sync strategy [DHIS2-13249]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/dataset/DefaultCompleteDataSetRegistrationExchangeService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/sync/CompleteDataSetRegistrationSynchronization.java
backport of #10880
Not from cherry-pick as that wanted to draw in more changes and it was easier to just change the 3 lines again.
> fix: complete data set registration sync strategy [DHIS2-13249] (2.38)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/programindicator/DefaultProgramIndicatorSubqueryBuilder.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/ProgramIndicatorSubqueryBuilderTest.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramIndicatorService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramExpressionItem.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemAttribute.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/dataitem/ProgramItemStageElement.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2Condition.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/function/D2CountIfCondition.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceD2FunctionTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramIndicatorServiceVariableTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorFunctionsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorItemsTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/CommonExpressionVisitor.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/FunctionIf.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareGreaterThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThan.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareLessThanOrEqual.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/operator/OperatorCompareNotEqual.java
See [DHIS2-12657](https://jira.dhis2.org/browse/DHIS2-12657). Analytics boolean values are stored as numbers (1 = true, 0 = false). This is done for both aggregate data which can be queried by indicators and event data which can be queried by program indicators.
In the case of aggregate data, ticket [DHIS2-13227](https://jira.dhis2.org/browse/DHIS2-13227) allows boolean data to be used in indicator expressions as either numeric or boolean. It does so by considering the datatype of boolean data to be numeric. When a boolean values is used, such as in the first argument to an if() statement inside an expression, the integer value is automatically converted to boolean (zero = false, nonzero = true). This was implemented because existing indicators had relied on the fact that boolean data …
> fix: Prog. Ind. boolean as bool/number DHIS2-12657

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/log/Log4JLogConfigInitializer.java
* Updates audit cron pattern to be in correct format (adds `?` to align it with master) 
[DHIS2-13250](https://jira.dhis2.org/browse/DHIS2-13250)
(integration tests failing because of mock current user, as we have seen in other PRs)
> fix: update audit cron pattern to be correct format

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/config/JacksonObjectMapperConfig.java
Disables `DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES` (back to Jackson default). This will allow nulls (or empty strings) to be sent for primitives, and they will be set to their JVM default values.
[DHIS2-13178](https://jira.dhis2.org/browse/DHIS2-13178)
> fix: allow nulls for primitives in Jackson ObjectMapper

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
See [DHIS2-13336](https://jira.dhis2.org/browse/DHIS2-13336). Trying to delete a user with multiple roles resulted in an error. This is because `UserObjectBundleHook#removeUserFromGroups` was iterating through the Set of `userRoles` and removing each one. During the iterations it called `userRole.removeUser( user );` which removed the role from the Set being iterated through, causing the error.
The error was presumably occurring also on users with just one role, but by the time the error occurred, the role had been successfully removed.
The fix was just to make a new collection of the roles, then they could be removed from the original collection.
> fix: Delete user with multiple roles DHIS2-13336

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/linelisting/CommonRequestMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/shared/LabelMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/LabelMapperTest.java
This fix aims to apply the correct usage of the labels for each time attribute that has a custom name defined in enrollments or events.
The GET request below, for example, should not bring "Enrollment date" in the response header. It should be the user-defined value "Start of treatment date".
```
https://play.dhis2.org/dev/api/analytics/events/query/ur1Edk5Oe2n.html+css?dimension=ou:USER_ORGUNIT&outputType=EVENT&tableLayout=true&columns=ou;enrollmentDate&enrollmentDate=LAST_12_MONTHS&headers=ouname,enrollmentdate&dataIdScheme=NAME&paging=false&asc=ouname
```
For more details about the mapping rule, see DHIS2-13136.
> fix: User defined names for time attributes in headers [DHIS2-13136]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GeoJsonImportControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/GeoJsonImportController.java
GeoJSON import API now always returns HTTP status code 200 OK. 
This is to be consistent with other imports in DHIS2.
However, the import status is reflected in the `status` property of the response object.
Existing tests were adjusted to the change of behaviour.
> fix: GeoJson import - always return status OK [DHIS2-7171]

- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/DefaultSchemaService.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/AccessSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ObjectStyleSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/RelationshipConstraintSchemaDescriptor.java
- dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/RelationshipItemSchemaDescriptor.java
Adds missing `SchemaDescriptor` for:
[TECH-778](https://jira.dhis2.org/browse/TECH-778)
> feat: adds missing embedded type schema descriptors

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
forward-port of https://github.com/dhis2/dhis2-core/pull/10672 fix added to unblock the release of 2.38
currently blocked by TrackedEntityProgramAttributeEncryptionTest.testTrackedEntityProgramAttributeEncryptedValue
```
TrackedEntityProgramAttributeEncryptionTest.testTrackedEntityProgramAttributeEncryptedValue:81->TrackerTest.assertNoImportErrors:175 E1112: Attribute value: `Value To Encrypt`, is set to confidential but system is not properly configured to encrypt data. ==> expected: <OK> but was: <ERROR>
```
> fix: initialize ExpressionParams.SAMPLE_PERIODS differently

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerWithJwtTokenAuthTest.java
integrationH2 test fails since it needs JSONB while h2 does not support it.
fix is needed to unblock other fixes of failing tests at https://github.com/dhis2/dhis2-core/pull/10956
> fix: failing JWT token test

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/fileresource/JCloudsProviderTest.java
- dhis-2/pom.xml
Fix pom.xml so that it works again for aws-s3 file storage with Apache jclouds, as used by PEPFAR. It was broken in 2.38. This fix has been tested by PEPFAR and it works for them.
I also added the unit test `JCloudsProviderTest` that makes sure each of the three jclouds providers we use can be configured. This test fails with the unfixed 2.38 pom.xml and succeeds with the fix.
> fix: jclouds connection to aws-s3

- .github/workflows/analyse-pr.yml
- dhis-2/pom.xml
The artifact org.codehaus.mojo:sonar-maven-plugin:jar:3.9.1.2184 has been relocated to org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.9.1.2184: SonarQube plugin was moved to SonarSource organisation
Analysis was sent https://github.com/dhis2/dhis2-core/pull/10966/checks?check_run_id=6703670802 successfully
and warning is gone https://github.com/dhis2/dhis2-core/runs/6703593044?check_suite_focus=true#step:4:2367
> ci: fix sonarqube maven plugin warning

- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/TrackerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/EventDataValueTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/OwnershipTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/RelationshipImportTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeValueAuditTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityDataValueAuditTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeEncryptionTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeFileResourceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerEventBundleServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/params/AtomicModeIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentAttrValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TeTaEncryptionValidationTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
in case an import fails we shouldn't be left wondering why and re-run CI over and over again.
Re-use our own `assertNoImportErrors`. Adjust `assertNoImportErrors` so its message more readable.
so a test like
```java
TrackerImportReport trackerImportReport = trackerImportService.importTracker(fromJson( "tracker/validations/events-with-registration.json" ));
assertNoImportErrors( trackerImportReport );
```
not expecting any import errors would fail with for example
```
org.opentest4j.AssertionFailedError: Expected import with status OK, instead got:
E1123: Missing required event property: `orgUnit`.
E1123: Missing required event property: `programStage`.
E1123: Missing required event property: `program`.
==> 
Expected :OK
Actual   :ERROR
```
instead of just
```
Expected :OK
Actual   :ERROR …
```
> test: use assertNoImportErrors for better context

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserRoleDeletionHandler.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
@larshelge I quite agree with [your comment](https://github.com/dhis2/dhis2-core/pull/10900#issuecomment-1141995568) on the first PR for [DHIS2-13336](https://jira.dhis2.org/browse/DHIS2-13336). For consistency with the rest of the code base this is better done in the deletion handler. In fact the logic is already there in `UserRoleDeletionHandler`.
What apparently happened is that the `UserRoleDeletionHandler` logic was broken by another code refactor. Instead of fixing it, `UserObjectBundleHook#preDelete` was added to remove the user roles before deletion. However this logic was flawed because it tried to remove a Set member while iterating through the Set. My [first PR for the ticket](https://github.com/dhis2/dhis2-core/pull/10900) fixed this flaw.
But the original cause of the problem …
> fix: UserRoleDeletionHandler DHIS2-13336

- .codecov.yaml
- .github/workflows/run-tests.yml
- dhis-2/pom.xml
* adds step `Report coverage to codecov` after all types of tests we run (unit, integration, integrationH2)
* each type of test gets a flag attached https://docs.codecov.com/docs/flags so we can track coverage by type and set different targets and thresholds
If coverage has been reported you will see
`[2022-06-03T06:24:02.569Z] ['info'] {"status":"success","resultURL":"https://codecov.io/github/dhis2/dhis2-core/commit/f73c8f8a2bd5a920b81076c4e9d44b5a0ee28a45"}`
https://github.com/dhis2/dhis2-core/runs/6721138233?check_suite_focus=true#step:6:126
which takes you to the report. You can see the uploads by type (using the different flags) https://codecov.io/gh/dhis2/dhis2-core/commit/f73c8f8a2bd5a920b81076c4e9d44b5a0ee28a45/build
Right now coverage is only reported as informational and will …
> ci: show coverage in codecov TECH-1188

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/DefaultDhisConfigurationProvider.java
so DefaultDhisConfigurationProvider should be excluded. Only PostgresDhisConfigurationProvider
should be used with profile test-postgres
> fix: postgres integration tests has its own config provider

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/version/DefaultMetadataVersionServiceTest.java
DefaultMetadataVersionServiceTest.testShouldReturnTheLatestVersion has been flaky on GitHub. 
Improve assertions we can figure out why. Also remove unused mockito annotation its a pure integration test that is not using any mocks.
Instead of assertion errors like `expected true got false` we now get
in case of one of the versions being null
```
org.opentest4j.AssertionFailedError: Either both versions or none must be null. v1: null, v2: MetadataVersion{importDate=null, type=BEST_EFFORT, name='Version_2', hashCode='abcdef'}
```
in case the versions do not match
```
name must match ==> expected: <Version_1> but was: <Version_2>
Comparison Failure: 
Expected :Version_1
Actual   :Version_2
<Click to see difference>
type must match ==> expected: <ATOMIC> but was: <BEST_EFFORT>
Comparison …
```
> test: improve assertions of flaky DefaultMetadataVersionServiceTest

- .github/workflows/run-tests.yml
To get accurate coverage results for master and PRs.
To identify compilation/test errors early. master was
broken multiple times. Its not clear if that was always due to
failed checks being overridden on a PR. PRs might not always
run against latest master which could cause such issues.
> ci: run tests on master as well as PRs

- .github/workflows/run-tests.yml
we recently had a few occasions where test jobs took hours due to UnsatisfiedDependencyExceptions.
Spring keeps on retrying creating components/services until we get an out of memory error.
The first log of the exception is enough for us to investigate the root cause. Keeping such
test jobs alive takes away from our 20 concurrent jobs per org quota. The quota per repo
might even be lower. Now that we also upload failed test logs as artifacts these logs would
grow unecessarily large.
> ci: save job resources when tests take too long

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
https://jira.dhis2.org/browse/DHIS2-12958
This PR revert a part of the PR https://github.com/dhis2/dhis2-core/pull/10531
In details, PR#10531 uses response type `HttpStatus.OK` and return `WebMessage` while in 2.37 the endpoint return `HttpStatus.NO_CONTENT`. This is an api change introduced in 2.38 so it shouldn't be changed in a 2.37 patch.
> fix: revert response type for collections api (2.37)

- dhis-2/pom.xml
it assumes tests within a module only test the module itself. This is why
some changes of lets say code in dhis-api, which is tested in dhis-service-core or so
did not show up as covered
see
* https://www.eclemma.org/jacoco/trunk/doc/report-aggregate-mojo.html
* https://blog.jcore.com/2020/04/how-to-fix-a-drop-of-code-coverage-with-a-multi-module-maven-project/
> ci: jacoco does not report cross module coverage by default

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/datastatistics/hibernate/HibernateDataStatisticsEventStore.java
- dhis-2/dhis-services/dhis-service-reporting/src/test/java/org/hisp/dhis/datastatistics/DataStatisticsEventStoreTest.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Currently, the `name` DB column is always returned in the default version.
This fix will change that, so the `name` will be returned respecting the current user's locale.
So, if there is a translation for the `name` column, in the respective table, it will take priority and will be returned. Otherwise, the default value will take place.
[Backport] from master/2.39
> fix: Support i18n name in /dataStatistics/favorites [DHIS2-13370]

- dhis-2/dhis-services/dhis-service-validation/src/main/java/org/hisp/dhis/validation/hibernate/HibernateValidationRuleStore.java
Was testing out some IDE features and noticed by chance that `save` and `update` were implemented identical. I assume the `update` method should call `super.update` not `super.save` unless we had a special reason to use `super.save` in both cases.
> fix: update validation rules via super.update

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeValueAuditTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentAttributeValidationHookTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/te_program_with_tea_allow_audit_metadata.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/te_program_with_tea_data.json
- dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/te_program_with_tea_metadata.json
In NTI, program attributes can be specified as part of the Enrollment tracker Dto. Validation based on valueType for enrollment attributes was missing in the NTI. This PR fixes it by moving the `validateAttributeValue` method from `TrackedEntityAttributeValidationHook` class into its base abstract class `AttributeValidationHook`, so that the second subclass `EnrollmentAttributeValidationHook` can reuse the same method.
> fix: Validate enrollment attributes values based on valueType in NTI [DHIS2-12669] (2.39)

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/apikey/ApiTokenAuthenticationToken.java
(cherry picked from commit 5febdef74c8986c15129c38b20eaf73ff12818dc)
> fix: Broken ApiToken internal authority list (#11072)

- .codecov.yaml
https://docs.codecov.com/docs/notifications#preventing-notifications-until-after-n-builds
as comments being posted after each upload was done is confusing devs. This showed coverage as
decreasing at first.
Annotations on GitHub are to chatty. If devs want to see the coverage diff, they actively click
on the file in the file summary on the codecov PR comment
> ci: disable codecov annotations and report when done

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/geojson/GeoJsonImportParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/GeoJsonImportController.java
Issue is the `User` in the `GeoJsonImportParams` is from the thread that the async `POST` was made. When it runs asynchronously that user instance is no longer attached to a valid database session. Therefore the user is reloaded by UID.
As the comment says the better fix would be to use `CurrentUserDetails` instead. That is a bigger change that requires updates on many central internal APIs so this is left for another explicit task.
> fix: reattach user of GeoJson async import [DHIS2-7171]

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/version/DefaultMetadataVersionServiceTest.java
- This `testShouldReturnTheLatestVersion` fails occasionally  with below error 
- I couldn't reproduce it, but i guess the reason is because the query from `versionService.getCurrentVersion()` try to get the latest version by `created` date. But from the `assertEqualMetadataVersions`, we can see that both version 1 & 2 have same `created` date. 
```
[ERROR] Failures:
[ERROR]   DefaultMetadataVersionServiceTest.testShouldReturnTheLatestVersion:139->assertEqualMetadataVersions:301 Mult
res (2 failures)
org.opentest4j.AssertionFailedError: name must match ==> expected: <Version_2> but was: <Version_1>
org.opentest4j.AssertionFailedError: type must match ==> expected: <BEST_EFFORT> but was: <ATOMIC>
```
- I set `created` date explicitly when create new `Version` objects in order to avoid `new …
> fix: flaky test because of created date

- .github/workflows/run-tests.yml
we used them a while back for analyzing test duration. We are not
actively doing so right now, so 10 days is not needed. We might
use them again soon, but 5 days should be enough
> ci: keep surefire reports for 5 days

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataExportServiceTest.java
https://jira.dhis2.org/browse/DHIS2-7586
- `MapView` has been changed to be `EmbeddedObject` but `MetadataExportService.getMetadataWithDependencies()` hasn't been updated to reflect that.
- I have removed the code for generating `MapView` at the top level of the metadata export file. So it will only be included in the `Map` object as embedded objects.
- Added unit test.
> fix: metadata with dependencies export mapView as embeddedObject

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramStageInstanceDeletionHandler.java
```sql
select count(*) from programstageinstance where eventdatavalues ? :uid
```
is causing
```
org.springframework.dao.InvalidDataAccessApiUsageException: Not allowed to mix named and traditional ? placeholders. You have 1 named parameter(s) and 1 traditional placeholder(s) in statement: select count(*) from programstageinstance where eventdatavalues ? :uid
```
This error was not allowing the e2e-tests to do proper cleanup and `MetadataImportTest.shouldUpdateExistingMetadata` was failing because `TrackedEntityInstanceAclReadTests` was creating data elements that were not deleted
> fix: fix test-api issue

- .github/workflows/run-api-tests.yml
like we do with other tests. This way we can quickly identify to a
commit that broke e2e tests. Not sure what the root cause of it is when
it happens. Some PRs suddenly have failing e2e tests in a consistent
way, even though they did only move some non-e2e test files around.
> test: run api tests on master

- .github/workflows/run-tests.yml
add unit test reports so we could track test count over time.
Upload reports per test job. otherwise, some reports might be overridden
as a unit, integration test likely lead to a report for the same class.
> ci: upload surefire per test job

- dhis-2/dhis-services/dhis-service-schema/pom.xml
- dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
- dhis-2/dhis-services/dhis-service-setting/pom.xml
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/schema/RelativePropertyContextTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/schema/SchemaFieldIntrospectorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/schema/SchemaServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/schema/SchemaValidatorTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/setting/SystemSettingManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/setting/SystemSettingStoreTest.java
After some discussion with the backend team we agreed that tests that need to access the DB should use postgres if there is no strong reason to use H2. (This doesn't apply to `dhis-web-api-test` module as H2 is used to prevent mocking the whole persistence layer).
In this PR the tests that access the DB are transformed to integration tests and moved to `dhis-test-integration`.
The ones that are not accessing the DB are transformed into unit tests
> chore: Handle H2 test for schema and setting modules [TECH-1208]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
backport https://github.com/dhis2/dhis2-core/pull/10842
The controller test from the original PR has been removed as it's not applicable for 2.36
> fix: update Option.sortOrder resulted with null sortOrders (2.36)

- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
Adjusts the hard delete sequences of soft delete tables.
The adjustments are based on analysis.
I think some were in wrong order, some sequences lacked clearing a table and in one a table was done twice in same sequence.
I am waiting for a reproducer scenario to see if this solves the original issue. 
So far I could not reproduce the problem described in the jira ticket.
> fix: hard delete soft deleted instances and related objects in correct order [DHIS2-13262]

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/security/config/AuthoritiesProviderConfig.java
https://jira.dhis2.org/browse/DHIS2-13415
Got below server error when open a UserRole in Users app.
```
* ERROR 2022-07-01T15:17:18,720 Exception occurred during processing request: Unable to instantiate Action, org.hisp.dhis.commons.action.GetSystemAuthoritiesAction,  defined for 'getSystemAuthorities' in namespace '/dhis-web-commons/security'Error creating bean with name 'org.hisp.dhis.commons.action.GetSystemAuthoritiesAction' defined in URL [jar:file:/Users/viet/code/dhis2-core/dhis-2/dhis-web/dhis-web-portal/target/dhis/WEB-INF/lib/dhis-web-commons-2.37.8-SNAPSHOT.jar!/META-INF/dhis/beans.xml]: Cannot resolve reference to bean 'org.hisp.dhis.security.SystemAuthoritiesProvider' while setting bean property 'authoritiesProvider'; nested exception is …
```
> fix: error loading authorities in Users app (2.37)

- jitpack.yml
Configure JitPack to build dhis2-core on Java 11
> Configure JitPack to build dhis2-core on Java 11

- dhis-2/dhis-services/dhis-service-core/pom.xml
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/SystemInfo.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/database/DatabaseInfo.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/database/DatabaseInfoTest.java
- dhis-2/dhis-support/dhis-support-system/src/test/java/org/hisp/dhis/system/database/HibernateDatabaseInfoProviderTest.java
Removes sensitive properties from system info. Introduces Lombok annotations for get/set methods. Removes XML annotations, though XML was not supported for this endpoint anyway.
Confirmed that the About page in the UI adapts and hides null/non-existing properties.
> fix: Remove sensitive properties from system info [DHIS2-8677]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataset/SectionStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DefaultSectionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/SectionDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/hibernate/HibernateSectionStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataset/SectionStoreTest.java
This PR improves the deletion of data elements, specifically the "unlinking" for `Section`s.
Instead of iterating all sections, only those affected by the deletion are loaded and updated.
This is one of multiple improvments to reduce time it takes to delete data elements.
Added new test to make sure the SQL for the new method selection the affected methods works as intended.
> fix: Improve data element deletion performance - sections [DHIS2-5761]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/NotifierJobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SchemaControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/SchedulingController.java
The main issue was that the completing of the process (outer bracket) was not propagated in case of automatic cancellation as the `Process` record was already completed (the `process.getCompletedTime() != null` check was true).
The forwarding call `tracker.failedProcess( error );` is now simply always done first. It was placed later before to protect against wrongly calling `failedProcess` multiple times (from the outside) but that is a programming error and should not happen.
In addition I added a new controller method so the UI can query for the running types without getting the full status.
I also noticed that the `/api/jobConfigurations/{uid}/execute` endpoint does not check if the configuration exists and return a proper error code for that, instead it would cause a 500 internal …
> fix: always propagate end of process to delegate progress trackers [DHIS2-13474]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/ControlledJobProgress.java
PR brings most of the progress tracking changes up to date with most recent `master` to get similar behaviour to the state after #11284.
Differences:
* no custom failure policy 
* the `runStage` methods mostly still return `boolean` (success) instead of `void` (master)
* the processing in the scheduling manager `execute` does not yet return a `boolean` (job was running) but `void` (not always clear for caller if the job was ever attempted to run)
> fix: auto-complete running job progress processes [DHIS2-13489] (2.37)

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
See [TECH-1265](https://dhis2.atlassian.net/browse/TECH-1265). The endpoint api/dataEntry/metadata needs to include indicator factor from indicatorType, in order for the new data entry frontend code to correctly compute indicator values. Without this fix, indicators are returned like:
```
"indicators": [
{
"name": "Postnatal contact total ",
"created": "2014-10-10T17:33:20.071",
"lastUpdated": "2014-10-10T17:33:20.077",
"shortName": "Postnatal contact total ",
"dimensionItemType": "INDICATOR",
"annualized": false,
"numerator": "#{LhoRsqtRn4r}+#{k1vnEuKnRYE}",
"numeratorDescription": "Postnatal contact total",
"explodedNumerator": "#{LhoRsqtRn4r}+#{k1vnEuKnRYE}",
"denominator": "1",
"denominatorDescription": "",
"explodedDenominator": "1",
"url": "",
"displayNumeratorDescription": …
```
> fix: Indicator type: /dataEntry/metadata TECH-1266

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
See [TECH-1265](https://dhis2.atlassian.net/browse/TECH-1265). Endpoint `/dataEntry/metadata` was returning indicators within data set sections, but was not returning indicators for data sets with no sections (default forms). The problem was that in the dataSets query `indicators~pluck[id]` was present within `sections`, but was not also present within the data set as a whole. This has been added.
Now `/dataEntry/metadata` will still return indicators inside sections when they are referenced inside sections, and it will also return all indicators for a data set in the main body of the data set, whether or not the data set has sections. When indicators are listed in sections, they are also listed in the main body of the data set. This follows the pattern for data elements, which are …
> fix: DSet indicators /dataEntry/metadata TECH-1265

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
Hard to say what the original intention really was. I think the block in question:
```java
if ( process != null && process.getStatus() != JobProgress.Status.RUNNING )
{
progress.failedProcess( (String) null );
}
```
was intended to complete not-yet completed (running) process as failed (as strictly they should have been complected by the job calling `completedProcess`). So originally I think the following was the intention, just the condition was accidentally flipped:
```java
if ( process != null && process.getStatus() == JobProgress.Status.RUNNING )
{
progress.failedProcess( (String) null );
}
```
Considering the situation from a user perspective again I found that it is better not consider such a process as failed but complete it with a message hinting at the minor programming mistake …
> fix: auto-complete running job progress processes [DHIS2-13489]

- .github/workflows/run-tests.yml
so we can debug coverage issues more easily (https://docs.codecov.com/docs/unexpected-coverage-changes), see test count change over time, ... For example the coverage seems to change from the base commit to this commit even though I did not change any code. A question I would like to answer is: did we run the same amount of tests on the base then in this commit? 
Example of an HTML report for integration-h2 tests
This is easier for us humans than aggregating, sifting through all the individual xml files.
Creating a tar of the individual xml reports to speed up the upload due to limitation https://github.com/actions/upload-artifact#zipped-artifact-downloads Uploading of xml reports in unit tests could sometimes take ~50s and is now just a couple of seconds.
> ci: upload surefire aggregate report

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/DefaultIdentifiableObjectManager.java
- dhis-2/dhis-services/dhis-service-metadata-workflow/src/main/java/org/hisp/dhis/metadata/DefaultMetadataWorkflowService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datastore/DatastoreIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/acl/AclServiceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractDataValueControllerTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/DataApprovalControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/IdentifiableObjectController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/organisationunit/OrganisationUnitController.java
Noticed the get by only UID (without type) method in `IdentifiableObjectManager`
```java
<T extends IdentifiableObject> T get( String uid );
```
The implementation loops though all stores and returns the first match.
Such lookup should be limited to the few places where this is really needed which were 2 out of 10.
To better communicate the complexity of the process the method got renamed to `find` and also the overly convenient cast to any type `T` that extends `IdentifiableObject` was replaced with just `IdentifiableObject`.
All usages that knew the type of object they wanted to load instead use:
```java
<T extends IdentifiableObject> T get( Class<T> type, String uid );
```
> chore: avoid find first UID match lookup when type is known [TECH-1271]

- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/EnrollmentActionRule.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/EventActionRule.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/RuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AbstractRuleActionImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/AssignValueImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/ErrorWarningImplementer.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/implementers/SetMandatoryFieldValidator.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentRuleValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventRuleValidationHook.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/AssignValueImplementerTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/SetMandatoryFieldValidatorTest.java
- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/programrule/ShowErrorWarningImplementerTest.java
This is a refactor that needs to be done before tackling the real issue in rule-engine library.
Just removing all unneeded maps and explicitly passing the related Event/Enrollment
> refactor: Clean up program rule code in tracker module [DHIS2-13468]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/Sharing_.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserDetails.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserDetailsImpl.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/CurrentUserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/HibernateIdentifiableObjectStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/InternalHibernateGenericStoreImpl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/common/hibernate/SharingHibernateGenericStoreImpl.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/security/oidc/DhisOidcUser.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserGroupDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserGroupStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/InternalHibernateGenericStore.java
- dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/hibernate/SharingHibernateGenericStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/common/HibernateIdentifiableObjectStoreTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/common/IdentifiableObjectManagerTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserStoreTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/apikey/ApiTokenAuthenticationToken.java
This PR aims to replace the use of `currentUserService.getCurrentUser()` with `CurrentUserUtil.getCurrentUserDetails()`. This helps to avoid using the hibernate `User` object which contains lazy collections.
Some necessary  changes were made:
- Add `userGroupIds` and `isSuper` to `CurrentUserDetails` interface
- Create a new interface `SharingHibernateGenericStore` which contains methods for generating predicates which are used for validating sharing access permission. This interface will only use `CurrentUserDetails` instead of `User` object as in `InternalHibernateGenericStore`.
- The `InternalHibernateGenericStore` still contains methods accepting `User` object. Will create another PR to remove those them.
> chore: use CurrentUserDetails in HibernateIdentifiableObjectStore

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramExpressionItem.java
When setting a Program Indicator expression using a Data Element as type "Date", it does not evaluate correctly at querying time. It causes an error in the backend that propagates to the front end.
The error happens during the execution of the SQL at DB level:
```
org.springframework.dao.DataIntegrityViolationException:
StatementCallback; SQL [
select count(psi) as value,ax.“uidlevel3” from analytics_event_fxpgw6evdvb as ax where ax.“yearly” in (‘2021’, ‘2022’) and ax.“uidlevel3” in (‘JEhqFsfXxTt’,‘VSxknPhjR6o’,‘M7qFOnwmE3A’,‘Qq4jYe5tHnl’,‘mNzjvxYEHkq’,‘nFPxXeZftGm’,‘eWjt9Zl76FS’,‘HqJwxVQhfyM’,‘uqh2OI3no6W’,‘aeBwvrjdh7m’,‘hfal93WttYV’,‘qnw9ul9mgww’,‘Kts15CHhP3h’,‘Er2eXRYQ5kD’,‘mdpCE7IYau0’,‘HR8JDs4Sae5’,‘GBeQB9YNmP4’,‘L4FwAUd37Wp’,‘KlCB0HQHtbg’,‘dJssgIzIiL4’,‘TBh00t5LnBZ’,‘lpjb08mkXcY’,‘so …
```
> fix: Sql parsing issue in PI expression [DHIS2-13487]

- .github/workflows/run-tests.yml
as coverage is optional for now and just informational
> ci: do not fail build if codecov upload fails

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiTokenAttribute.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/IpAllowedList.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/MethodAllowedList.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/RefererAllowedList.java
- dhis-2/dhis-services/dhis-service-field-filtering/pom.xml
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterSimpleBeanPropertyFilter.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
* Change `ApiTokenAttribute` sub types to `EmbeddedObject`.
* Adds getter for `ApiTokenAttribute.type`.
* Update `FieldFilterSimpleBeanPropertyFilter` to always expand `@JsonTypeInfo` annotated classes as we do not allow field filtering on them.
[DHIS2-13437](https://jira.dhis2.org/browse/DHIS2-13437)
> fix: personal access token field filter

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
This PR https://github.com/dhis2/dhis2-core/pull/10775 created `analyticsdataexchange` table.
The naming of the table conflicts with the naming of analytics tables that are created at some point and can also be dropped.
Depending on the order of the tests, `analyticsdataexchange` is dropped and then other tests need it to run.
In this PR I just prevent the deletion of this specific table, maybe we will need to think of something more organic to prevent this from happening again as this kind of bugs in the tests are quite difficult to find.
> fix: Do not delete analyticsdataexchange table

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/analytics/common/CommonQueryRequest.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiTokenAttribute.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/IpAllowedList.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/MethodAllowedList.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/RefererAllowedList.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/CommonQueryRequestMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/CommonQueryRequestProcessor.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/Processor.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/Validator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsDimensionsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DimensionsServiceCommon.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/shared/GridHeaders.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/DefaultTeiAnalyticsDimensionsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/TeiAnalyticsDimensionsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/tei/TeiAnalyticsQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/AnalyticsDimensionsTestSupport.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/common/CommonQueryRequestMapperTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsDimensionsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsDimensionsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/shared/GridHeadersTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/tei/TeiAnalyticsDimensionsServiceTest.java
- dhis-2/dhis-services/dhis-service-field-filtering/pom.xml
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterSimpleBeanPropertyFilter.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tei/TeiQueryController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/dimension/TeiAnalyticsPrefixStrategy.java
This feature aims to add support for the `headers` request param.
When this param is set, the response should respect the `headers` specified, returning only the defined ones in the respective order. The main change is the code related to this class `dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/shared/GridHeaders.java`
I also did a small code clean-up as part of this PR.
_You will notice a small commit from "mortenoh", that can be ignored. This is because I merged `master` into my commit._
> feat: Add headers param support in CPL [DHIS2-13511]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/CategoryDimensionDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/category/CategoryOptionComboDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DataApprovalDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataapproval/DataApprovalLevelDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DataElementDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataelement/DataElementOperandDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/CompleteDataSetRegistrationDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/DataInputPeriodDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DataValueAuditDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DataValueDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dimension/DataDimensionItemDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/ExternalFileResourceDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/fileresource/MessageAttachmentDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/predictor/PredictorDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramInstanceDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramStageDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/ProgramStageInstanceDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/sms/command/code/SMSCodesDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/UserDeletionHandler.java
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/document/DocumentDeletionHandler.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/JdbcDeletionHandler.java
Essentially replaces
```sql
select count(*) ...
```
with
```sql
select 1 ... limit 1
```
Gain should be most notable the larger tables get.
This is hard to test so **reviewers should pay extra attention** to the changes.
> perf: use select 1 limit 1 instead of select count(*) to check existence in deletion handlers [DHIS2-13506]

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/EventDataValueTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/LastUpdateImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/OwnershipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/RelationshipImportTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityAttributeValueAuditTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityDataValueAuditTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeEncryptionTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeFileResourceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackedEntityProgramAttributeTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackerEventBundleServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/TrackerSideEffectHandlerServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/programrule/ProgramRuleIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentAttrValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/TeTaEncryptionValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
in case the expected and actual size differs, we do not get more context other than that they are not equal. Using our own `assertNoErrors` assertion we do also get the list of errors. This context is especially helpful in integration tests which take long to run and/or with flaky tests only failing in CI.
* renamed `assertNoImportErrors` with `assertNoErrors` to overload it, so we can now call it with `TrackerImportReport` and `TrackerValidationReport`
* replaced (hopefully) any `assertEquals` for `errors.size() == 0` with assertNoErrors
> test: use assertNoErrors instead of assert on size and content

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/deletion/DefaultDeletionManager.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/SchemaBasedControllerTest.java
Current behaviour is:
* if a deletion veto handler throws an exception (that is not the `DeleteNotAllowedException`) during veto phase the deletion handling is aborted effectively skipping other veto handler and certainly skipping all deletion handler (that change/remove linkage)
* if a deletion handler throws an exception (any) deletion handling is aborted and all further deletion handlers are skipped
Since no exception is re-thrown the code triggering the deletion event will continue and delete the object triggering the deletion event (unless this fails due to a FK constraint in the DB).
This can leave the DB in an inconsistent state that is mostly unpredictable and certainly undesirable. 
The target behaviour is:
* if an exception is thrown (not `DeleteNotAllowedException`) either …
> fix: abort deletion on exception in handlers [DHIS2-13499]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-support/dhis-support-jdbc/src/main/java/org/hisp/dhis/jdbc/statementbuilder/AbstractStatementBuilder.java
As part of `SCHEDULE` events support we need to make sure the current code is backwards compatible, as we never used statuses and assumed only ACTIVE/COMPLETED events. Most of the logic is based on `executiondate`.
This code fixes a missing clause to make it backwards compatible with the boundaries feature.
Basically, we are now using the `duedate` column for SCHEDULE events and `executiondate` for the rest (backwards compatible).
> fix: Backwards compatible clause in boundaries [DHIS2-12309]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventServiceTest.java
* copied WebMvcConfig over to MvcTestConfig as prod and test configs for
media types should be the same.
* fix NPE and another potential NPE
* added tests to protect us against future NPEs at least in the event itself
* added test for a happy `writeEvents` case
Note: this does not address that when navigating to https://play.dhis2.org/2.38.0/api/tracker/events using the browser the CSV endpoint is chosen. Making a curl command like `curl -u admin:district https://play.dhis2.org/2.38.1/api/tracker/events` does return JSON. More on that in https://jira.dhis2.org/browse/DHIS2-13413?focusedCommentId=51667&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-51667
> fix: NPE when getting tracker/events CSV

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/Pager.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/SlimPager.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/enrollment/AbstractEnrollmentService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/NodeUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
[Backport from 2.38]
This fixes the pager object for the cases when `totalPages=false` is set as a parameter in the GET request.
Example for events.:
```
http://localhost:8080/dhis/api/events.json?fields=enrollment&ou=ImspTQPwCqd
&page=201&pageSize=100&program=ur1Edk5Oe2n&programEndDate=2021-05-24
&programStartDate=2021-05-02&totalPages=false
```
Before this fix the page object returned was always:
```
"pager": {
"page": 1,
"total": 0,
"pageSize": 50,
"pageCount": 1
}
```
Now it will look like this:
```
"pager": {
"page": 4,
"pageSize": 50,
"isLastPage": true
}
``` 
Another example, for enrollments, could be:
```
http://localhost:8080/dhis/api/enrollments.json?fields=enrollment&ou=ImspTQPwCqd
&ouMode=DESCENDANTS&page=3&pageSize=20&program=ur1Edk5Oe2n …
```
> fix: Backport paging for events/enroll. [DHIS2-13512]

- dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/AssertTrackerValidationReport.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/Assertions.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/AssertionsTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/OwnershipTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/bundle/ReportSummaryDeleteIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentAttrValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/TeTaEncryptionValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/TeTaValidationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/validation/TrackedEntityImportValidationTest.java
in case the expected and actual size differs, we do not get more context
other than that they are not equal. We usually have such assertions
before the assertions checking for error codes within the list of errors
which will then not get executed. Add context using JUnit 5 assertAll
and some custom assertions so both the check for size and content are
executed and the full list of validation errors is printed in case of a
failing assertion.
This context is especially helpful in integration (flaky) tests which take long
to run and/or only fail in CI.
* added a AssertionsTest so we ensure the actually fail when we want to and so we can iterate on the Assertions locally especially the assertion messages.
```java
TrackerValidationReport report = new TrackerValidationReport();
report.addError( …
```
> test: add context to assertions on error and errors size

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/csv/TrackerCsvEventServiceTest.java
Since data values are stored in a Set we need to be careful using assertions that depend on order like `assertEquals`. Added a helper assertion to produce error like
```
org.opentest4j.AssertionFailedError: expected line is not in CSV:
expected line:
BuA2R2Gr4vt,ACTIVE,,,,,,,,,,,true,false,,,,,,,,,,,color,red,,true,,,
got CSV:
BuA2R2Gr4vt,ACTIVE,,,,,,,,,,,true,false,,,,,,,,,,,color,yellow,,true,,,
BuA2R2Gr4vt,ACTIVE,,,,,,,,,,,true,false,,,,,,,,,,,color,purple,,true,,,
==> 
Expected :true
Actual   :false
```
in case the expected line could not be found
> fix: /api/tracker/events CSV export misses events without data values DHIS2-13519

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ResourceTableController.java
Add support for skip flag in analytics table export.
When the flag "skipTei" is set to "true", all TEI analytics tables should be skipped during the export process.
Example of the POST endpoint with the "skipTei" flag set to "true".
```
http://localhost:8080/dhis/api/resourceTables/analytics?skipTei=true
```
> feat: Add skip flag for TEI tables in analytics export [DHIS2-13526]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
backport of https://github.com/dhis2/dhis2-core/pull/11348
> fix: /api/tracker/events CSV export missing file extension DHIS2-13529 [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionGroupStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/OptionGroupDeletionHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/option/hibernate/HibernateOptionGroupStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/option/OptionGroupStoreTest.java
https://jira.dhis2.org/browse/DHIS2-7908
- Add deletionHandler to remove `Option` from `OptionGroup` when `deleteOption()` is triggered.
- Note that `Option` is automatically removed from `OptionSet` because of cascade="all" defined in `OptionSet.hbm`. So we don't need to add deletionHandler for this association.
> fix: delete option linked with OptionGroup [DHIS2-7908-39]

- dhis-2/dhis-support/dhis-support-test/src/main/resources/log4j2-test.xml
- dhis-2/dhis-test-integration/pom.xml
- dhis-2/dhis-test-integration/src/test/resources/log4j2-test.xml
* integration tests were not logging due to https://www.slf4j.org/codes.html#noProviders
* added own log4j2-test.xml for integration tests to iterate more
quickly and customize it for integration tests
* adapt log pattern so its easier to understand where the log is coming
from
Integration tests often need debugging since they tend to be more flaky
or only fail in CI. Logging is helpful in that case. The log4j2-test.xml
config we have in the dhis-support-test module is useful so not every
module needs to bring its own. Integration tests logs might need to be
configured differently. We use different tools like testcontainers, ...
Previously, dhis-support-test module needed to be re-installed for every
change to log4j2-test.xml. This is still needed for unit tests, but not
anymore for …
> test: add own log4j2 test config for integration tests

- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldFilterService.java
- dhis-2/dhis-services/dhis-service-field-filtering/src/main/java/org/hisp/dhis/fieldfiltering/FieldPathHelper.java
Simply applies `displayName` to requests that is still using legacy sharing requests.
> fix: support displayName in sharing requests

- .github/dependabot.yml
as we always have a couple that are waiting on some devs to follow up.
While other libraries ship updates that can be merged without intervention.
> ci: allow 8 dependabot PRs

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/jdbc/batchhandler/DataValueAuditBatchHandlerTest.java
[TECH-1260](https://dhis2.atlassian.net/browse/TECH-1260)
[TECH-1261](https://dhis2.atlassian.net/browse/TECH-1261)
> fix: aggregate DataValueAudit fixes

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistBuilder.java
While testing I noticed that `PeriodType` object would render as empty objects in the Gist API. This is because none of their properties is annotated with `@JsonProperty`. I checked the metadata API which usually shows the period type as name so I added a transformer to gist API that does that transformation automatically.
`/api/dataSets/gist?fields=id,name,periodType`
Gives something like:
```json
{
"pager":{
"page":1,
"pageSize":50
},
"dataSets":[
{
"id":"QD9rA2Jh2ei",
"name":"test A",
"periodType":"Monthly"
},
{
"id":"XCFR1EgHzB2",
"name":"test B",
"periodType":"Monthly"
}
]
}
```
> fix: Gist API show PeriodType as name

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/FallbackCoordinateFieldType.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventDataQueryServiceTest.java
please see: https://jira.dhis2.org/browse/DHIS2-13528
> feat: New fallback logic for geometry in analytics [DHIS2-13528]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceReportingRateTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/QueryPlannerTest.java
This change is a complement of https://github.com/dhis2/dhis2-core/pull/11199
It will also remove decimal "zeros" from report rates and validation rules for consistency.
So, numbers like `123.0` will simply become `123`.
> fix: Remove decimals zeros in rep. rates/val. rules [DHIS2-8184]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceReportingRateTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryPlannerTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsTestUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/util/AnalyticsUtilsTest.java
**_[Backport from master/23.9]_**
The download of a Visualization is showing "0" digits for numbers like "237.0", "55.0", "13300.0" and so on.
Instead, it should remove `0` decimal digits, as they are redundant. So the numbers above would became: "237", "55", "13300".
This happens when exporting Data Elements of Value Type "Number" because the number of decimal digits is not configurable (in Indicators this option exists).
This PR aims to remove the redundant `zeros` for the Data Element results.
The GET request below can be used to reproduce the issue in master, and also to display the expected results on this branch.
```
http://localhost:8080/dhis/api/analytics.json?dimension=dx:fbfJHSPpUQD;cYeuwXTCPkU;Jtf34kNZhzP;hfdmMSPBgLG&dimension=pe:LAST_12_MONTHS&showHierarchy=false&hierarchyMeta= …
```
> fix: Visualization download to remove redundant 0 decimals [DHIS2-13460]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobConfiguration.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/CredentialsExpiryAlertJobParameters.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/jackson/CredentialsExpiryAlertJobParametersDeserializer.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/job/DisableInactiveUsersJob.java
- dhis-2/dhis-services/dhis-service-core/src/main/resources/i18n_global.properties
- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/credentials/CredentialsExpiryAlertJob.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserServiceTest.java
The existing job was functional but had unintended behaviour:
* job did process with a month setting of `0` (feature is not used)
* job did email users every day for at least 14 days 
* job would keep sending emails to already expired users (as long as they were not disabled)
The progress tracking would not be as useful as it could be because, ...
* items (sending an email) would always be considered a success independent of the `OutboundMessageResponse` status
* the days remaining was not included in the item description
* already expired passwords would show as negative "days until expiry" (now excluded)
Overall failure policy was changed from `SKIP_ITEM_OUTLIER` to `SKIP_ITEM` to try sending as much emails as possible even if some fail. This is also important now because the outcome of …
> feat: improved progress tracking of password expiry alert job [DHIS2-8150]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/resourcetable/ResourceTable.java
Historically, the analytics tables could export data until 2024.
Recently we increased it, to limit the year allowance to `current_year + 2`.
Now, we are increasing it to `current_year + 25`. So users will be able to export data 25 years in the future.
This limitation is set so we can avoid taking too much space during the analytics table export.
> feat: Increase number of years supported by analytics exp [DHIS2-13558]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/resourcetable/ResourceTable.java
**_[Backport from 2.39/master]_**
Historically, the analytics tables could export data until 2024.
Recently we increased it, to limit the year allowance to `current_year + 2`.
Now, we are increasing it to `current_year + 25`. So users will be able to export data 25 years in the future.
This limitation is set so we can avoid taking too much space during the analytics table export.
> feat: Increase number of years supported by analytics exp. [DHIS2-13558]

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/InMemoryNotifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/Notifier.java
- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/notification/RedisNotifier.java
* moves "default parameter" delegating methods from implementation to `default` methods in interface
* introduces a method generic for the summary object to enforce that the `Class` and `Object` argument passed match
> chore: Notifier API cleanup

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/preheat/Preheat.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/preheat/DefaultPreheatService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/MetadataAttributeCheck.java
- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/attribute/MetadataAttributeCheckTest.java
https://jira.dhis2.org/browse/DHIS2-13569
- When importing metadata, if the payload contains existing attribute then the `preheat.attributesByTargetObjectType` could contains duplicate attributes. 
- In details, there could be two Attributes with same `uid` but different `id`, where the object loaded from database has `id` = 10 and object from payload has `id` = 0.
- This affects the `MetadataAttributeCheck` which has just beed added to 2.39, so this fix doesn't need to be backport.
> fix: duplicate attributes from preheat.getAttributesByClass()

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
Adds a new optional `uid` parameter to the `POST` method to create a `FileResouce`.
This allows to create file resources with specific externally generated UIDs.
New test scenario was added so creation with and without `uid` parameter is now covered.
* check file resources with `uid` parameter can be created (`/fileResources?domain=ORG_UNIT&uid={uid}`) and that the resulting resource has the provided uid
* check file resources can still be created without a `uid` parameter and get assignd a new generated UID
> feat: optional uid parameter for creation of file resources [DHIS2-6288]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/DashboardController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/DashboardControllerTest.java
Adds a new endpoint `/dashboards/search` that is used with the `q` query parameter.
A new test scenario was added to existing tests.
> feat: dashboard search with q parameter [DHIS2-12284]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
When using a filter like `!EQ`, the endpoint should all results that are not equals and also bring all null values.
Currently, the null values are excluded from the results. This change will fix this problem.
Using the Debug DB, we can use this URL for testing:
```
http://localhost:8080/dhis/api/39/analytics/events/query/vBOHFvxlYPJ
?dimension=ou:USER_ORGUNIT,Xd6cKnFMO4L.sC3rTY6UiY6:!EQ:2022-01-02
&headers=ouname,Xd6cKnFMO4L.sC3rTY6UiY6,eventdate
&totalPages=false
&eventDate=THIS_YEAR
&stage=Xd6cKnFMO4L
&displayProperty=SHORTNAME
&outputType=EVENT
&pageSize=100
&page=1
&includeMetadataDetails=true 
```
> fix: Not EQ in analytics event query is filtering out null values [DHIS2-13563]

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/DhisControllerConvenienceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/AbstractCrudControllerTest.java
backport https://github.com/dhis2/dhis2-core/pull/11422
- The fix is different from https://github.com/dhis2/dhis2-core/pull/11422 because in 2.38 we still use the old `FieldFilterService`. Only the test `AbstractCrudControllerTest#testSharingDisplayName` is backport.
> fix: sharing userGroup displayName is empty (2.38)

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
**_[Backport from master/2.39]_**
This issue was introduced by my previous PR https://github.com/dhis2/dhis2-core/pull/11430
I haven't considered the `NV` filter on the previous fix.
Test URLs:
```
http://localhost:8080/dhis/api/29/analytics/events/query/IpHINAT79UW.json?dimension=pe:LAST_12_MONTHS
&dimension=ou:ImspTQPwCqd
&dimension=A03MvHHogjR.H6uSAMO5WLD:NE:NV
&stage=A03MvHHogjR
&displayProperty=NAME
&totalPages=false&
outputType=EVENT
&desc=eventdate
&pageSize=100
&page=1
```
```
http://localhost:8080/dhis/api/29/analytics/events/query/IpHINAT79UW.json?dimension=pe:LAST_12_MONTHS
&dimension=ou:ImspTQPwCqd
&dimension=A03MvHHogjR.H6uSAMO5WLD:!EQ:gates
&stage=A03MvHHogjR
&displayProperty=NAME
&totalPages=false
&outputType=EVENT
&desc=eventdate
&pageSize=100
&page=1
```
> fix: NV filter on events not working [DHIS2-13563]

- .github/workflows/dependabot.yaml
as patch update approvals have been working well for months now https://github.com/dhis2/dhis2-core/pull/10614
One additional approval by a dev will still be needed on patch and minor updates
> ci(deps): automatically add 1 of 2 approvals to dependabot minor and patch updates

- dhis-2/pom.xml
as they are released together
micrometer-spring-legacy is EOL and not released anymore https://github.com/micrometer-metrics/micrometer/issues/1662
We should investigate whether the mix of current and EOL spring-legacy actually works
> chore(deps): micrometer libraries should be kept in sync

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/AnalyticsPagingCriteria.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/common/PagingCriteriaProcessor.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryValidator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SettingKey.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
The event analytics query engine restricted the page size in the paging logic to the max limit of records from the `ANALYTICS_MAX_LIMIT` even when that value as 0. The value 0 in this case represents unlimited records, and the restriction should only happen if the max limit of records is greater than 0. Currently if the max limit is set to unlimited, no events are ever returned from the event analytics query endpoint.
> fix: Only restrict page size to max limit if greater than zero [DHIS2-13606]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/JobConfigurationObjectBundleHook.java
`CronSequenceGenerator` did not accept the valid expression `0 0 1 ? * TUE-SUN`.
As it was deprecated I tried `CronExpression.isValidExpression` instead as our scheduling is also based on `CronExpression` class. That one does accept the expression.
* create a job in the scheduler app using a cron expression like `0 0 1 ? * TUE-SUN` that has a day-of-the-week range. 
* try to safe the job successfully
> fix: cron expression validation [DHIS2-9768]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserServiceTest.java
https://jira.dhis2.org/browse/DHIS2-13607
- Fix exception `No entity found for query`  when calling `userService.getDisplayName(userId)` and the userId doesn't exist.
> fix: NoEntityFound exception for userService.getDisplayName()

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/dataset/notifications/DefaultDataSetNotificationService.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/dataset/notifications/DataSetNotificationServiceTest.java
https://jira.dhis2.org/browse/DHIS2-12566
- `CompleteDataSetRegistration.periodName` is a transient field and its value need to be set before sending it to the `BaseNotificationMessageRenderer`
> fix: null value for CompleteDataSetRegistration.periodName

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/FileResourceController.java
NPE occured because of the `currentUser.getAvatar().equals( fileResource )` where `currentUser.getAvatar()` could be null if it was never set. The NPE was indirectly prevented by the `F_USER_VIEW` authority as the condition would already be true so that the second part would never be evaluated.
With this fix in place the file itself can be uploaded but a user lacking authority might still not be able to then set the image file resource as avatar as he cannot modify its own profile (`User` object). This is a more general issue that maybe is best addressed in another PR.
> fix: NPE when changing avatar image without F_USER_VIEW authority [DHIS2-9761]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/CsvDataValueSetReader.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/datavalueset/dataValueSetWithDataSetHeader.csv
Adds possibility to add the data set ID of a data value set CSV import by adding another header column (last). 
The column header is the data set ID. It is the 12th column after the "deleted" column.
Nothing else about the CSV import changes. This is purely an additional optional feature that allows to specify the data set ID of the imported set.
Added a unit test with a CSV file that tests the scenario for success.
> feat: allow data set ID in CSV header row of data value import [DHIS2-8083]

- dhis-2/dhis-services/dhis-service-reporting/src/main/java/org/hisp/dhis/validation/DefaultValidationService.java
https://jira.dhis2.org/browse/DHIS2-13011
Error
```
Unable to instantiate Action, org.hisp.dhis.de.action.ValidationAction,  defined for 'validate' in namespace '/dhis-web-dataentry'Error creating bean with name 'org.hisp.dhis.de.action.ValidationAction' defined in URL [jar:file:/ebs1/home/instances/dev/tomcat/webapps/dev/WEB-INF/lib/dhis-web-dataentry-2.39-SNAPSHOT.jar!/META-INF/dhis/beans-dataentry.xml]: Cannot resolve reference to bean 'org.hisp.dhis.validation.ValidationService' while setting bean property 'validationService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.hisp.dhis.validation.ValidationService' available
```
- The `ValidationAction` bean tries to  inject `ValidationService`, but the bean's name defined to …
> fix: error injecting ValidationService to ValidationAction

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/webmessage/WebMessageUtils.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonWebMessage.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/FileResourceUtils.java
Mainly this should provide a nicer server response then the 500 caused by FK containt violation in case a file resource with a UID already exist when the client sends the UID.
> fix: Conflict when storing a file resource with existing UID [DHIS2-6288]

- dhis-2/dhis-services/dhis-service-setting/src/main/java/org/hisp/dhis/setting/SystemSettingManager.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/setting/SystemSettingManagerTest.java
https://jira.dhis2.org/browse/DHIS2-13592
- Below code return false for TRUE value if server uses Redis. It works fine without redis enabled.
```
getSystemSetting( key, Boolean.class ) == Boolean.TRUE
```
- Code return TRUE with the fix
> fix: boolean value from redis not comparable

- dhis-2/dhis-test-integration/src/test/resources/junit-platform.properties
Failing tests due to tests not being well isolated from each other are not uncommon. Using [setDependency](https://github.com/dhis2/dhis2-core/blob/5f143981ed88826306a39737bc8aa7b328445f08/dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java#L428) without cleaning up changes to the shared application context is a common root cause of tests depending on execution order. Tests then fail on GitHub but not locally as the order differs. Setup an empty config (disabled) where devs can easily influence test execution order https://junit.org/junit5/docs/5.5.0-RC1/user-guide/index.html#writing-tests-test-execution-order.
> test: add junit properties to debug integration test execution order

- dhis-2/dhis-support/dhis-support-test/pom.xml
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/IntegrationTestConfig.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/config/PostgresDhisConfigurationProvider.java
- dhis-2/dhis-support/dhis-support-test/src/main/resources/postgresTestConfig.conf
In https://github.com/dhis2/dhis2-core/pull/11339 we tried using the more declarative approach to setting up the integration test DB https://www.testcontainers.org/modules/databases/jdbc
Due to that we cannot connect to the test DB container anymore. This makes debugging the integration test isolation problems we are facing hard.
[This jdbc approach](https://www.testcontainers.org/modules/databases/jdbc) does not set the env vars as was done before in
https://github.com/testcontainers/testcontainers-java/blob/01ed651980558534702f6c96daeee85be05117b8/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java#L75-L77
which means the `dhis` role and DB are not created by the postgres/gis container on startup …
> test: allow connecting to test DB via psql

- dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceUnitTest.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataapproval/DataApprovalAuditServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataapproval/DataApprovalServiceCategoryOptionGroupTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataapproval/DataApprovalStoreUserTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dataset/DataSetServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/EventPredictionServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/predictor/PredictionServiceTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/validation/ValidationResultStoreTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/datavalueset/dataValueSetAUpdate.xml
* remove `setDependency` which repeatedly caused tests to only fail on GitHub due to an unclean `ApplicationContext` https://github.com/dhis2/dhis2-core/pull/11462
* replace EventPredictionServiceTest use of `setDependency` with reflection to set an AnalyticsService mock. The analytics team should revisit the test and either turn it into a unit test using mocks or an integration test without mocks. Using reflection to mutate the `ApplicationContext` can again cause the same issues as `setDependency`.
* migrate integration test for https://github.com/dhis2/dhis2-core/pull/7950 to unit test DataValueSetServiceUnitTest. We can easily check that we do not hit the DB if DataValues are updated with the same value/comment in a unit test. Asserting that in an integration test is hard.
Some …
> test: remove setDependency TECH-1194

- dhis-2/dhis-support/dhis-support-test/pom.xml
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/BaseSpringTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceMetadataTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/IntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/SingleSetupIntegrationTestBase.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/TransactionalIntegrationTest.java
Removed unused code.
DB is always emptied so no need to expose `emptyDatabaseAfterTest`. Setting it to `false` could also affect test isolation which is causing us pain already.
> test: trim base classes TECH-1194

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/TextPatternMethod.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/textpattern/TestTextPatternMethod.java
- dhis-2/dhis-services/dhis-service-program-rule/src/main/java/org/hisp/dhis/programrule/engine/SupplementaryDataProvider.java
- dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/helper/JdbcSqlFileExecutor.java
Reported by Sonarcloud as a potential problem:
When matching large strings, greedy regex can be overloaded and cause issues. By adding "+" after "*", we make the matching possesive rather than greedy.
Tested using existing unit tests (program rules, textpattern) and running a fresh db (flyway).
> fix: Update regex not to be greedy

- jenkinsfiles/dev
[Related PR in dhis2/jenkins-pipeline-library](https://github.com/dhis2/jenkins-pipeline-library/pull/12).
Note that the `Build` stage might fail for other reasons, like maven repository connectivity issues (kinda rare).  
Haven't yet found a reliable way to determine that the failure is caused by tests, but will be improved at some point.
> feat: Add test failure notification at build stage [skip ci]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/CsvDataValueSetReader.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/datavalueset/dataValueSetWithDataSetHeader.csv
Allows to provide the data set ID for a data value set import from CSV file using a new import options parameter `dataSet`.
Replaces changes in #11439
https://github.com/dhis2/dhis2-docs/pull/1034
> feat: set dataset ID for CSV data value set import via options [DHIS2-8083]

- dhis-2/dhis-web/dhis-web-commons/src/main/java/org/hisp/dhis/about/action/RedirectAction.java
This is a workaround so that the `/dhis-web-dataentry/` URL becomes `/dhis-web-dataentry/index.action` when doing the redirct 
after login. This is important so have the data entry work as start app.
* goto System settings => Appearance and select _Data Entry_ as _Start Page_
* logout
* login again, check the data entry app is displayed correctly as the first page the user sees
> fix: add index.action suffix for data entry redirect [DHIS2-6705]

- dhis-2/pom.xml
https://github.com/dhis2/dhis2-core/pull/11568 fixed potential issues
that could cause the count of tests running on Jenkins/GitHub to divert.
The actual root cause for version 2.36 is that we were using an old
version of surefire
org.apache.maven.plugins:maven-surefire-plugin:2.12.4
which you can see by running the tests without default or integration
profile. So with only jdk8 or jdk11.
When profiles default or integration are used like they are on GitHub
where unit and integration tests run in parallel we actually use
org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5
The newer plugin has support for JUnit 5 as described in https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html
which is why you also see the build log
Using the provider …
> ci: fix surefire version to run all tests on Jenkins [2.36]

- dhis-2/pom.xml
https://github.com/dhis2/dhis2-core/pull/11569 fixed potential issues
that could cause the count of tests running on Jenkins/GitHub to divert.
The actual root cause for version 2.35 is that we were using an old
version of surefire
org.apache.maven.plugins:maven-surefire-plugin:2.12.4
which you can see by running the tests without default or integration
profile. So with only jdk8 or jdk11.
When profiles default or integration are used like they are on GitHub
where unit and integration tests run in parallel we actually use
org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5
The newer plugin has support for JUnit 5 as described in https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html
which is why you also see the build log
Using the provider …
> ci: fix surefire version to run all tests on Jenkins [2.35]

- dhis-2/pom.xml
there are scenarios where we might run maven without any profile or a profile
that does not declare the surefire version in its build config. In that case maven
will resort to a default version which is rather old. This version does not
support JUnit 5 tests. So in case a JUnit 5 test would be added, it might not run.
[master/2.39](https://github.com/dhis2/dhis2-core/pull/11524)
[2.38](https://github.com/dhis2/dhis2-core/pull/11538)
[2.37 remove pom-full.xml](https://github.com/dhis2/dhis2-core/pull/11547) [2.37 surefire version](https://github.com/dhis2/dhis2-core/pull/11583)
[2.36 remove pom-full.xml](https://github.com/dhis2/dhis2-core/pull/11568) [2.36 surefire version](https://github.com/dhis2/dhis2-core/pull/11586)
[2.35 remove …
> test: ensure correct surefire version [2.33]

- dhis-2/pom.xml
to not set skipTests when we do not want to
> ci: only manage surefire and asm version in pluginManagement [2.36]

- dhis-2/pom.xml
to not set skipTests when we do not want to
> ci: only manage surefire and asm version in pluginManagement [2.34]

- dhis-2/pom.xml
to not set skipTests when we do not want to
> ci: only manage surefire and asm version in pluginManagement [2.37]

- dhis-2/pom.xml
it was needed when making DHIS2 jdk11 compatible
https://github.com/dhis2/dhis2-core/pull/4187
but is not anymore. DHIS2 itself does not depend on it.
Maven surefire for example does https://maven.apache.org/surefire/maven-surefire-plugin/dependencies.html
It will manage the version it needs itself.
> test: remove dependency on asm

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/common/ImportOptions.java
This PR adds `namespace` property to the `@JsonProperty` annotations on `ImportOptions`. This is necessary so we don't break XML `ImportSummary` returns (as the inner `importOptions` property would not have ns declared).
> fix: adds XML namespace to ImportOptions

- dhis-2/dhis-e2e-test/docker-compose.yml
whenever I restart the dhis2-e2e-db-1 keeps on being started by Docker due to
the https://docs.docker.com/config/containers/start-containers-automatically/
This is annoying as it blocks a port and is wasting resources if I do not want to run
e2e tests.
unless-stopped is 'Similar to always, except that when the container is stopped (manually or otherwise), it is not restarted even after Docker daemon restarts.'
> ci: relax docker compose restart policy on DB

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceIntegrationTest.java
DataValueSetServiceIntegrationTest failed on Jenkins in a commit with completely unrelated changes while passing on GitHub. This suggests that the order of DataValues might have been different. [DataValueService.getAllDataValues()](https://github.com/dhis2/dhis2-core/blob/4380176ede3e773fa5a4b1dd2bc733e5f782a993/dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueService.java#L163-L168) does not state that it guarantees the order of DataValues.
Our assertion should therefore not expect a certain order.
> test: fix DataValueSetServiceIntegrationTest assertions depending on order

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/test/integration/TransactionalIntegrationTest.java
Test annotated with `@Transactional` does not need to empty the DB as this is already done by Spring.
ReservedValueServiceIntegrationTest is testing code that uses
ReservedValueBatchHandler which relies on the
org.hisp.quick.batchhandler. BatchHandler get their own JDBC connection
and thus transactions. Tests that test code like this can thus not
(easily) rely on Springs test transaction management as changes in the
BatchHandler are running in different transactions then the Spring test.
Use non transactional base class IntegrationTestBase which cleans up the
DB "manually".
> test: no need to empty DB in transactional test

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/config/JacksonObjectMapperConfig.java
- dhis-2/dhis-web-api/pom.xml
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
Fixes various minor issues with the new csv field filtering.
> fix: metadata csv export

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/SharingUtils.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/fieldfilter/DefaultFieldFilterService.java
https://jira.dhis2.org/browse/DHIS2-13490
PR https://github.com/dhis2/dhis2-core/pull/11243 introduced a fix to make the metadata api return `Sharing` properties in correct xml format. However, that fix broke analytic objects.
This PR make that fix only applicable for `Sharing` properties and ignore other objects.
> fix: make FieldFilterService xml fix only applicable for sharing (2.37)

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueService.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValueStore.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/hibernate/HibernateDataValueStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/datavalue/DataValueServiceIntegrityTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/category/CategoryComboControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/category/CategoryComboController.java
Adds a validation to the category combo endpoint to prevent changing the categories of the combo if data exist.
Depends on #11618 to make the added validation be effective for all ways of updating an object. 
Added a new integration test to check basic functionality of the service method that checks for existing data values.
* find or create a category combo where data exist
* try to add or remove a category to/from the combo and check that the attempt results in an error
* find or create a category combo where no data exists
* try to add or remove a category to/from the combo and check that it is permitted
* check the above both for data values where the combo is used of category option combo and/or as attribute option combo
> feat: prevent category combo category changes if data exists [DHIS2-1786]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractCrudController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/scheduling/JobConfigurationController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ApiTokenController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
Use the `prePatchEntity(old,new)` instead of `prePatchEntity(new)` method.
In 2 places this required to make a copy of the state before the patch. I used the new patch service to copy the object by applying an empty list of operations to it.
> chore: use prePatchEntity with before and after arguments

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/AbstractNode.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/Node.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/types/CollectionNode.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/types/ComplexNode.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/types/RootNode.java
- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/types/SimpleNode.java
Since we are not removing the `Node` classes until 2.40/2.41, this PR removes the deprecation notices for now.
> fix: remove deprecation notice from Node classes for now

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/UserOrgUnitType.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserQueryParams.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/merge/orgunit/handler/MetadataOrgUnitMergeHandler.java
- dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/split/orgunit/handler/MetadataOrgUnitSplitHandler.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java
- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/webapi/json/domain/JsonUser.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/user/UserServiceTest.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserLookupControllerTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/user/UserLookupController.java
Adds `orgUnitBoundary` parameter to both `/users` and `/userLoopup` endpoints.
The parameter accepts any of the `UserOrgUnitType` enum values and restricts the search to the users that share an organisation unit with the current user for the selected boundary.
The existing parameter `&userOrgUnits=true` would be identical to `&orgUnitBoundary=DATA_CAPTURE` and is kept for backwards compatibility. If `userOrgUnits` is true it takes precedence over any `orgUnitBoundary` provided additionally.
A new controller test scenario was added.
* create a user and set its capture organisation unit to a specific unit
* create another user and set its capture organisation unit to the same unit
* login as one of those users
* use `/userLookup` search to find the users sharing a capture organisation unit …
> feat: user lookup restricted to capture units [DHIS2-12586]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/User.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/create_user_with_legacy_format.json
https://dhis2.atlassian.net/browse/DHIS2-13675
There are two fixes in this PR
1) ` User.populateUserCredentialsDtoFields` is not added to `UserObjectBundleHook`. It's only added to `MeController` and `UserController`. This is a part of the code for supporting legacy `UserCredentials`.
2) When import `User` with legacy format, the `uid` provided in the payload is changed to a new `uid`. This is caused by some utils method in `User` class which try to copy `UserCredentials` to new format but `uid` is not copied.
Added a new test for legacy format.
> fix: import user with legacy UserCredentials

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventsAnalyticsManagerTest.java
This is a small change asked by the front-end team.
They want to always have the scheduled date attribute in the response header.
> fix: Always return scheduleddate in the header [DHIS2-12309]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
so we can evolve /tracker/events without affecting the old tracker event
endpoint
* duplicated RequestToSearchParamsMapper and its test into EventRequestToSearchParamMapper (for old and new tracker)
* removed unused code in each now that they are only responsible for old/new tracker
> chore: split old/new tracker GET events param processing

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/CsvNodeSerializer.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/serializer/CsvNodeSerializerTest.java
This PR aims to fix the issue of writing tracked entity attributes into a csv file.
The attributes were not written into the file because they are not simple properties, they are complex so they were not included.
The PR pushes the fix to include them from now on, plus some unit tests.
> fix: Show attributes in csv response [DHIS2-13621] [2.38]

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/CsvNodeSerializer.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/serializer/CsvNodeSerializerTest.java
This PR aims to fix the issue of writing tracked entity attributes into a csv file.
The attributes were not written into the file because they are not simple properties, they are complex so they were not included.
The PR pushes the fix to include them from now on, plus some unit tests.
> fix: Show attributes in csv response [DHIS2-13621] [2.36]

- dhis-2/dhis-services/dhis-service-node/src/main/java/org/hisp/dhis/node/serializers/CsvNodeSerializer.java
- dhis-2/dhis-services/dhis-service-node/src/test/java/org/hisp/dhis/node/serializer/CsvNodeSerializerTest.java
This PR aims to fix the issue of writing tracked entity attributes into a csv file.
The attributes were not written into the file because they are not simple properties, they are complex so they were not included.
The PR pushes the fix to include them from now on, plus some unit tests.
> fix: Show attributes in csv response [DHIS2-13621] [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/adx/DefaultAdxDataService.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetQueryParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceExportTest.java
Adds a new parameter `dataElement` to the data value set API that can be used to provide data element IDs directly instead of using a dataset or data element group.
The parameter can be used in combination with data sets and data element groups. 
Using `inputDataElementIdScheme` in addition allows to provide CODEs or NAMEs instead of IDs.
New test scenario was added using both `dataElement` and `inputDataElementIdScheme`.
For example (demo database): 
* `/api/dataValueSets.json?dataElement=JFFUt8yR2iW&period=202203&orgUnit=mzsOsz0NwNY`
* `/api/dataValueSets.json?dataElement=DE_384&period=202203&orgUnit=mzsOsz0NwNY&inputDataElementIdScheme=CODE`
> feat: adds data element filter to data value set API [DHIS2-11966]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
/tracker/events
* filter by `enrollmentEnrolledAfter`
* order by `order=enrolledAt:desc` or `order=enrolledAt:asc`
Added validation to `order` request parameter. Previously, we were simply removing a property that we cannot order by so `/tracker/events?order=foo:desc` would turn into `/tracker/events` without the user being made aware of this. Now we fail and list the properties that are order able by.
For example requesting `/tracker/events?order=foo:desc` leads to
```
{
"message": "Order by property `foo` is not supported. Supported are `storedBy, attributeCategoryOptions, dueDate, assignedUserUsername, createdAtClient, program, lastUpdated, href, event, assignedUser, programStage, programType, created, orgUnit, …
```
> feat: filter /tracker/events by enrollmentEnrolledAfter DHIS2-13648

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/RemoveByIdOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/jackson/jsonpatch/operations/RemoveOperation.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/jackson/RemoveByIdOperationTest.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/jackson/ReplaceOperationTest.java
https://dhis2.atlassian.net/browse/TECH-1185
- The test `testRemoveInvalidKeyShouldThrowException` is currently Disabled. 
- As reported from `TECH-1185`, front-end app expect an error returned if the path is invalid.
- I have re-enabled the test and make the `RemoveOperation` to return `JsonPatchException`.
- This also affect the `ReplaceOperation`.
> fix: re-enable JsonPatchException for remove operation [DHIS2-1185]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
and order by occurredAt
* switched order of after/before fields to before/after as my brain had a hard time dealing with the former 🧠 😂
> feat: filter /tracker/events by enrollmentOccurredBefore/After DHIS2-13648

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/option/OptionSet.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OptionObjectBundleHook.java
https://dhis2.atlassian.net/browse/DHIS2-13640
- According to the bug reported, user got NPE when trying to add `Option` to an `OptionSet`.
- I couldn't reproduce it but the issue can be fixed in backend with a `null` check.
> fix: NPE in OptionObjectBundleHook.preUpdate

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableGenerator.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOrgUnitTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/PartitionUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsIndexHelper.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/util/TextUtils.java
- dhis-2/dhis-support/dhis-support-commons/src/test/java/org/hisp/dhis/commons/util/TextUtilsTest.java
_[Backport from master/2.39]_
This PR aims to restore the expected Analytics export and table _partitioning_ using `inheritance` (as release 2.36).
**Overview**
Since release 2.37, some behaviours were not correctly covered when we introduced partition tables.
Pepfar identified and raised those issues in three JIRA tickets: DHIS2-13429, DHIS2-DHIS2-13478 and DHIS2-13479. In summary, those tickets describe the following problems.
**Problems**
1) The table `analytics_0` never gets cleaned after a full export. It causes data duplication when the application hits the query below, in `JdbcAnalyticsManager.getFromSourceClause`.
```
select ap.*
from analytics_0 as ap
union all
select ap.*
from analytics_2019 as ap
union all
select ap.*
from analytics_2020 as ap
```
2) After running the Analytics …
> fix: Use inheritance instead of partitions in analytics export [DHIS2-13429] [2.38]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/QueryModifiers.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/expression/ExpressionParams.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/AnalyticsUtils.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/PeriodOffsetUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/DefaultExpressionService.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemPeriodInYear.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemYearlyPeriodCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/dataitem/ItemPeriodInYearTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/dataitem/ItemYearlyPeriodCountTest.java
- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/collection/CollectionUtils.java
- dhis-2/dhis-support/dhis-support-expression-parser/src/main/java/org/hisp/dhis/parser/expression/function/FunctionYearToDate.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
- dhis-2/pom.xml
See [DHIS2-13320](https://dhis2.atlassian.net/browse/DHIS2-13320), especially the `Expression syntax` section of the May 24, 2022 comment.
This PR implements the following expression syntax for indicators:
- yearToDate() modifier to add any previous values in the calendar year
- [periodInYear] returns the number of the period in the calendar year
- [yearlyPeriodCount] returns the total number of periods of this type in the calendar year
The two classes that do most of the heavy lifting are:
The approach is similar to periodOffset. Before the indicator database query, year-to-date processing adds periods if needed to fetch the values from previous periods within the same calendar year(s) as any requested periods. After the database query, previous calendar year data is added to the results …
> feat: Indicator .yearToDate() DHIS2-13320

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcCompletenessTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEnrollmentAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcOrgUnitTargetTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcValidationResultTableManager.java
This PR aims to restore the expected Analytics export and table _partitioning_ using `inheritance` (as release 2.36).
**Overview**
Since release 2.37, some behaviours were not correctly covered when we introduced partition tables.
Pepfar identified and raised those issues in three JIRA tickets: DHIS2-13429, DHIS2-DHIS2-13478 and DHIS2-13479. In summary, those tickets describe the following problems.
**Problems**
1) The table `analytics_0` never gets cleaned after a full export. It causes data duplication when the application hits the query below, in `JdbcAnalyticsManager.getFromSourceClause`.
```
select ap.*
from analytics_0 as ap
union all
select ap.*
from analytics_2019 as ap
union all
select ap.*
from analytics_2020 as ap
```
2) After running the Analytics job (export) for the …
> fix: Use inheritance instead of partitions in analytics export [DHIS2-13429] [2.37]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
- dhis-2/dhis-test-integration/src/test/resources/dxf2/datavalueset/dataValueSetAUpdate.xml
Only create a data value update audit when the value has changed.
From the report of the ticket I also deduced that there are pure followup updates which should mean we only want to skip the update if the followup has not changed.
> fix: only create data value audit if value changes [DHIS2-13705]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/StreamingJsonRootMessageConverter.java
The issue was caused by special behaviour of `getEntity` for `/organisationUnits/{uid}?level={level}` where this returns a list but the serialisation was assuming it is always just one entity. By providing a wrapper name in case there is more than one entity match the serialisation ends up in the path creating the wrapper object with array field. There the pager was excluded if it is `null` to match the old behaviour.
> fix: handle special case where controller getEntity returns a list [DHIS2-13709]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/LabelMapper.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/LabelMapperTest.java
The “due date” custom label for a Program Stage, in a Tracker Program, is ignored by the events/query API.
GET request example for testing it:
```
http://localhost:8080/dhis/api/29/analytics/events/query/IpHINAT79UW
?dimension=ou:USER_ORGUNIT,p2Zxg0wcPQ3&headers=scheduleddate
&totalPages=false&eventDate=LAST_12_MONTHS&stage=A03MvHHogjR
&displayProperty=NAME&outputType=EVENT&pageSize=100&page=1
&includeMetadataDetails=true&desc=scheduleddate
```
> fix: Schedule date column not displaying custom label [DHIS2-13713]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
_[Backport from master/2.39]_
When Data Elements of type Percentage contain null values in the database, they should return empty values in the response object of analytics event/enrollment requests.
Instead of getting the result as a primitive double, we get it as an object. From there, we apply the logic to apply or not `empty` values.
> fix: DEs of type Percentage returns 0.0 for null values [DHIS2-13633]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IdentifiableObjectUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/IdentifiableObjectUtilsTest.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
Adds stable ordering of first level objects in the response. Additional work is needed for `dataSets.dataSetElements`.
> fix: Stable order of data entry metadata [TECH-1310]

- dhis-2/dhis-support/dhis-support-commons/src/main/java/org/hisp/dhis/commons/collection/CollectionUtils.java
Remove obvious (and wordy) JavaDoc lines in response to @jbee's [comment on pull/11620](https://github.com/dhis2/dhis2-core/pull/11620#discussion_r966153986).
> docs: remove obvious JavaDoc for mapOf DHIS2-9832

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/App.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/appmanager/AppTest.java
- dhis-2/dhis-api/src/test/resources/manifest.webapp
Fixes [DHIS2-13710](https://dhis2.atlassian.net/DHIS2-13710)
This adds support for parsing a new `plugin_launch_path` property from web application manifests.  It then generates a fully-qualified `pluginLaunchUrl` property and exposes this in the `/api/apps` endpoint.  I added some minimal tests, but this file is largely untested so a separate change to improve test coverage would be good to explore.
> feat: expose manifest plugin launch paths in /api/apps API [DHIS2-13710]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultDataSetMetadataExportService.java
Provides stable order of data set elements in data set metadata endpoint.
The `dataSet.dataSetElements` association does not provide a stable order when retrieved through the API as it is a Set association. This should likely be improved in the data model, but it is not ideal to introduce a data model change so close to release, hence it is corrected in the data set metadata export service.
> fix: Stable order of data set elements in metadata endpoint [TECH-1310]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/mapper/OrderParam.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/OrderCriteria.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-test-integration/src/test/resources/log4j2-test.xml
- dhis-2/dhis-test-integration/src/test/resources/tracker/event_and_enrollment.json
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/view/package-info.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
* OrderParam/OrderCriteria should be immutable as they represent the users request parameter `order`
* code added to EventRequestToSearchParamsMapper is mostly a duplication of the code we use for the `filter` on `/tracker/trackedEntities`. We can try to extract it later on if we feel like that is important. I did not try to due to the time constraint of the soft freeze.
* multiple filters in `filterAttributes` for the same TEA like `filterAttribues=TvjwTPToKHO:lt:20,TvjwTPToKHO:gt:30` are not allowed
> feat: filter /tracker/events by filterAttributes DHIS2-13648

- dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/HttpUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
Updates direct usage of string `Content-Type` to use Springs `HttpHeaders.CONTENT_TYPE`. `dhis2-support-test` has not been updated as I did not want to add dependency on the web layer to it.
> fix: use HttpHeaders.CONTENT_TYPE instead of string value

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
according to our new guideline on Assertions
https://github.com/dhis2/wow-backend/blob/8e9bd4ccdfd8997b1f2f03d9e21543c902d225a6/guides/testing.md?plain=1#L93
```java
assertStartsWith("prefix",null);
org.opentest4j.AssertionFailedError: expected string to start with 'prefix', got null instead ==> expected: not <null>
```
```java
assertStartsWith("prefix", "is not contained");
org.opentest4j.AssertionFailedError: expected string to start with 'prefix', got 'is not contained' instead ==> 
Expected :true
Actual   :false
```
> test: add assertStartsWith to Assertions DHIS2-13648

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
- Added ordering by attribute for events. A new `attributeOrders` field was created in `EventSearchParams`.
- `QueryItem` with no filter is created if there is an order on an attribute that has no filter. This is needed because we need to add a join with the attribute table to be able to order
- If there is an order on an attribute, ignore the most external ordering in the query as this would override the attribute order
> feat: Add ordering on tei attributes for events [DHIS2-13648]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
_[Backport from 2.39/master]_
The initial commit broke the numeric comparison for `!EQ, !IEQ, !LIKE, !ILIKE` filters.
Only text comparisons were working. This fix will make both text and non-text filtering work.
GET URLs for testing:
```
// Text filter
http://localhost:8080/dhis/api/29/analytics/events/query/IpHINAT79UW.json?dimension=pe:LAST_12_MONTHS&dimension=ou:ImspTQPwCqd&dimension=ZzYYXq4fJie.OuJ6sgPyAbC:!LIKE:gff&stage=ZzYYXq4fJie&displayProperty=NAME&totalPages=false&outputType=EVENT&desc=eventdate&pageSize=100&page=1
```
```
// Numeric filter
http://localhost:8080/dhis/api/29/analytics/events/query/IpHINAT79UW.json?dimension=pe:LAST_12_MONTHS&dimension=ou:ImspTQPwCqd&dimension=ZzYYXq4fJie.GQY2lXrypjO:!EQ:3729&stage=ZzYYXq4fJie&displayProperty=NAME&totalPages=false&outputType=EVENT …
```
> fix: Numeric filter in event analytics [DHIS2-13693]

- dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/conf/ConfigurationKey.java
Provides a default for the DB driver class.
* remove `connection.driver_class` key-value from `dhis.conf` file
* start server and check startup and DB usage works
> feat: provide default for DN driver class configuration [DHIS2-13708]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/csv/CsvEventDataValue.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvEventService.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/csv/TrackerCsvEventServiceTest.java
its only used in the export, so moving it there. The high level view of the tracker web package
now more closely resembles our domain. Tracker supports import/export both of which have a package. The view package exists to tigh import/export together as we support importing exported data directly.
If you want to know more about each feature you can drill down in the packages. csv was not at the same level of abstraction
> chore: move tracker CSV package close to its usage DHIS2-13648

- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
* EventExporterTest did sort the UIDs in the parametrized test functions so that we could assert on UIDs irrespective of order. Use `assertContainsOnly` as it already asserts irrespective of order.
* use `assertEquals( List.of( "dUE514NMOlo", "QS6w44flWAf" ), trackedEntities );` is enough to assert the collection is not null, has the correct size and order
* use `DateUtils.parseDate` instead of `SimpleDateFormat` and UID constants in 
* use `assertIsEmpty` instead of `assertEquals( Collections.emptySet(), params.getAssignedUsers() )`
> test: clean up assertions DHIS2-13648

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DhisApiVersion.java
Default API version was still set to `V38`. This PR updates it to the correct `V39` (there should be no changes other than internal).
> fix: set default API version to 2.39

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DhisApiVersion.java
Adds API version `40` to our endpoints, and sets as default for.
> feat: Adds API version 40 and sets as default

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEnrollmentAnalyticsService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
Some “headers” columns are returning incorrect values in the response of the analytics endpoints /query/events and /query/enrollments.
This is a small change to rename some of those columns.
> fix: Column names in events/enrollments [DHIS2-13721]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
Add attribute order param in the select query so it is possible to order after the join.
This should fix the flaky test and it will solve the limitation of mixed order param with attributes.
Now we support multiple order params even if there are attributes in the list
> feat: Add ordering attribute column in select [DHIS2-13648]

- jenkinsfiles/canary
- jenkinsfiles/eos
- jenkinsfiles/stable
Related to https://github.com/dhis2/dhis2-core/pull/11606
There have been no dependency fetching related failures since the changes introduced with the PR above, so applying the options to the rest of the pipelines is in order.
> ci: Apply maven dependency fetching opts to non-dev pipelines [skip ci]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/11694
> ci: Keep dev build history for 5 days and always save reports [skip ci] [2.39]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/11694
> ci: Keep dev build history for 5 days and always save reports [skip ci] [2.38]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/11694
> ci: Keep dev build history for 5 days and always save reports [skip ci] [2.37]

- jenkinsfiles/dev
backport of https://github.com/dhis2/dhis2-core/pull/11694
> ci: Keep dev build history for 5 days and always save reports [skip ci] [2.36]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
A few tests like `NO_CACHE` and `CACHE_1_MINUTE` are enough to assert that the `CacheStrategy` passed to configureResponse is making it into the max-age=60 response header value. Most other durations just delegate to TimeUnit for making the calculation which we do not need to test.
`CACHE_6AM_TOMORROW` calls new Date(). So testing this we make 2 calls to it once in the test for the expected value and once in the implementation. Since we cannot control the time in the test, we can be a bit more lenient in the expectation of the max-age seconds.
```java
assertWithinRange(100, 20, 100);
```
leads to
```
org.opentest4j.AssertionFailedError: lower bound 100 must be < than the upper bound 20 ==> 
Expected :true
Actual   :false
```
```java
assertWithinRange(10, 20, 21);
```
leads to
```
Expected …
```
> test: be more lenient in cache header assertion

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
_[Backport from master/2.40]_
We should not fail the analytics export if the SQL execution fails.
It's better to log the exception related to the specific SQL/program and allow the process to continue.
Besides that, this change will allow brand new Programs to be exported through the analytics continuous process (`table_0`).
Without this fix, the continuous process fails when we execute the `removeUpdatedData` method making new Programs impossible to be exported into analytics `table_0`.
> fix: Skip failing SQL, so the process can continue [DHIS2-13514]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
backport of https://github.com/dhis2/dhis2-core/pull/11775
for some reason the test was Disabled in 2.38
> test: be more lenient in cache header assertion [2.38]

- dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/utils/Assertions.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
backport of https://github.com/dhis2/dhis2-core/pull/11775
for some reason the test was Disabled/Ignored in 2.37
note this backport is adapted to JUnit 4 in which the test is written in
> test: be more lenient in cache header assertion [2.37]

- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/service/GeoFeatureService.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/utils/ContextUtils.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/utils/ContextUtilsTest.java
- dhis-2/dhis-web/dhis-web-dataentry/pom.xml
- dhis-2/dhis-web/dhis-web-dataentry/src/main/java/org/hisp/dhis/de/action/GetDataSetAssociationsAction.java
- dhis-2/dhis-web/dhis-web-dataentry/src/main/java/org/hisp/dhis/de/action/GetMetaDataAction.java
Centralizes and tests web cache related methods.
Note that the Struts data entry module does not send any `If-None-Match` header so this does not take affect currently.
> fix: Centralize and test cache methods

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/UserSettingController.java
3rd attempt to fix the content type returned consistently. By writing directly to the output we hopefully get not odd interaction from jackson or spring overriding what ends up at the client based on accept headers send in the request.
> fix: always return text/plain content type for single user setting [DHIS2-12782]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultDataValueService.java
Same goal as #11691 but for single data value updates.
* goto data entry app (old)
* open some form
* change a value, check audit entry is created (might need database access, or new data entry)
* add a comment on a value, check no audit is created
> fix: only create data value audit if value changes - single update [DHIS2-13705]

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/util/DateUtils.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/util/DateUtilsTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultDataQueryService.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/IsoPeriodHolder.java
Refactor requested to align a few date methods:
_In DefaultDataQueryService we have custom handling of periods and dates.
Instead, the code should use existing classes such as `DateUtils`._
_It is important to centralize the handling of periods/dates and avoid different behaviour in different places. Methods such as safelyParseDate, tryParseDateRange and safelyParseDateUsingFormatter should be reviewed/avoided._
This is part of the ticket DHIS2-13618.
> refactor: Move date methods to DateUtils [DHIS2-13643]

- dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventSearchParams.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/tracker/EventExporterTest.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteria.java
Remove some null checks for initialized fields and use guard clauses to reduce nesting.
Separate validation from constructing the EventSearchParams.
> chore: reduce mutation in EventSearchParams DHIS2-13648

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingAndSortingCriteriaAdapter.java
- dhis-2/dhis-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/PagingCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/EventRequestToSearchParamsMapperTest.java
* saves us from dealing with nulls which we turn into false anyway
* make it clear how users can add multiple filters on one TEA if they provide the invalid syntax
> chore: turn skipPaging into primitive

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
Without this fix, the analytics event table for some Programs may not be populated. This small change should address this problem. This can be reproduced in Sierra Leone (Program `1150221`).
Some ProgramInstances may not have an OrgUnit associated (defined as null in such cases).
In Sierra Leone we have this particular case for Program `1150221`:
```
SELECT * FROM programinstance p WHERE organisationunitid IS NULL AND programid = 1150221;
```
This query will bring the column `organisationunitid` set to `NULL`.
Because of such cases, that might show up in production, we are changing how we join the respective statement (see the code changes). Instead of a `inner join` we are now using `left join`.
This brings back the population of the analytics events tables even in cases where there are …
> fix: Empty event table when OU is not defined in PSI [DHIS2-13754]

- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/query/planner/DefaultQueryPlanner.java
- dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/CrudControllerPagingTest.java
https://dhis2.atlassian.net/browse/DHIS2-13756
- In Maintenance App -> DataElement list, when click on page 2, there is only 1 DE shown
- The list of DE also not ordered by DisplayName.
- In QueryPlanner , we need to check if both `criterions` and `orders` of non-persisted queyry not are empty. If that is true then the pagination should be done by the in-memory query.
- Added various web-api tests
This can be tested in maintenance app:
- Navigate to DataElement list.
- Navigate to page 2.
- It should show 50 DE, and the list should be ordered by displayName.
> fix: broken paging with order parameter [DHIS2-13756]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteriaMapperTest.java
so we can safely adapt the new tracker endpoints without affecting old tracker endpoints
* duplicate mappers so we can have one dedicated for old and one for new tracker. Deliberate duplication, just so you know sonarqube 😋 
* adhere to
https://github.com/dhis2/wow-backend/blob/master/guides/spring_conventions.md#bean-id
> chore: split old/new tracker enrollment export mappers TECH-1414

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipCriteria.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerRelationshipCriteriaTest.java
Moving all new tracker web related code into the `org.hisp.dhis.webapi.controller.tracker` packages. When old tracker is removed one day, we should at least for the web portions only have to delete one package.
> chore: move new TrackerRelationshipCriteria to tracker package DHIS2-13648

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/AbstractJdbcTableManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/DefaultAnalyticsTableService.java
_[Backport from 2.40/master]_
I realized that using the job progress is a better choice in this case.
If the step fails, it will add the error to the final execution report and continue with the process (executing all the next steps).
This PR improves the previous fix related to `DHIS2-13514`.
> fix: Use progress job to improve reporting feedback [DHIS2-13514]

- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEventAnalyticsManager.java
just backport, please see: 
https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13638&quickFilter=497
> fix: Org. Unit Group Sets are considered as filters in events/enrollments queries [2.38-DHIS2-13638-backport]

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
to be consistent with the other criteria mappers. Until we settle on a better name for all of them.
In tests just use variable names `mapper`, `criteria` to be consistent with other tests for criteria mappers.
> chore: revert renaming TrackerEventCriteriaMapper DHIS2-13648

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceQueryParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
like we already did in `/tracker/events` separate out validations, transformations before mapping/returning the TrackedEntityInstanceQueryParams. Goal is to only construct a valid
TrackedEntityInstanceQueryParams.
* Reuse some parsing functions from `/tracker/events` by moving them into RequestParamUtils
* Add tests to ensure we do not try to fetch things like a program is the optional query parameter is empty
> chore: move validation to top TECH-1414

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/PeriodType.java
- dhis-2/dhis-api/src/test/java/org/hisp/dhis/period/PeriodTypeTest.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
- dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/util/PeriodOffsetUtils.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemPeriodBase.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemPeriodInYear.java
- dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/expression/dataitem/ItemYearlyPeriodCount.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/dataitem/ItemPeriodInYearTest.java
- dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/dataitem/ItemYearlyPeriodCountTest.java
- dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/data/AnalyticsServiceTest.java
See [DHIS2-13774](https://dhis2.atlassian.net/browse/DHIS2-13774). There are two problems with the yearToDate() function and associated expression constructs [periodInYear] and [yearlyPeriodCount] when used in combination with periodOffset():
1. The [periodInYear] and [yearlyPeriodCount] items do not take into account .periodOffset(), which means they cannot be used meaningfully together with yearToDate() when it is being used together with the .periodOffset() function.
2. When yearToDate() is used with multiple different and overlapping periodOffsets in a single analytics query, some of the data values are double-counted.
`ItemPeriodInYear` and `ItemYearlyPeriodCount` added code to shift the period by a periodOffset if present, before evaluating the period. Since this added even more …
> fix: yearToDate with periodOffset DHIS2-13774

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtils.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/RequestParamUtilsTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapperTest.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerTrackedEntityCriteriaMapperTest.java
Parsing request parameters `filter` (on `/tracker/trackedEntities` and `/tracker/events` )/`filterAttribute` (on /tracker/events) is identical as it should also behave in the same way.
Strings like `uid1:gt:2:lt:10` or similar need to be turned into `QueryItem` with `QueryFilter`s which is then passed to the DB fetching code.
This PR moves the duplicated code into one place `RequestParamUtils`. Removes duplicate tests as the also moved into `RequestParamUtilsTest`.
The process is (see `parseQueryItem`)
* split strings like `identifier:gt:2:lt:10`
* pass the identifier to a mapping function `String -> QueryItem`. This function can for example calls a service to find an entity in the DB or get it from a prefetched map like `attributeToQueryItem.`
* add `QueryFilter`s to the above …
> chore: refactoring duplication TECH-1414 

- dhis-2/dhis-api/src/main/java/org/hisp/dhis/program/ProgramInstanceQueryParams.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteriaMapper.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentsExportController.java
- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
- dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEnrollmentCriteriaMapperTest.java
* name all mapper methods `map`, the parameter `criteria`
* move validation in TrackerEnrollmentCriteriaMapper to the top using the same methods we use in other mappers
> chore: consistent naming and validation at top TECH-1414

- dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventCriteriaMapper.java
while using == instead of equals we missed the ! (negation). For some reason the mode has no default (so it is null) and are only checking and throwing an exception if it is not null and not PROVIDED
This will be addressed in https://dhis2.atlassian.net/browse/DHIS2-13765 For now keep the logic as it was in
https://github.com/dhis2/dhis2-core/pull/11797/files#diff-3f0399270e47bfe544d4ab0b3fa9d71c4edc117f71b520979957d18f343f5af9L215-L220
```java
if ( assignedUserSelectionMode != null && assignedUserIds != null && !assignedUserIds.isEmpty()
&& !assignedUserSelectionMode.equals( AssignedUserSelectionMode.PROVIDED ) )
{
throw new IllegalQueryException(
"Assigned User uid(s) cannot be specified if selectionMode is not PROVIDED" );
}
```
> fix: validation of assigned users in /tracker/events DHIS2-13648 [2.39]
